### ISSUE TITLE
Bug on "datalad get" python version 3.5

### ISSUE THREAD

**Issue by demianw** [datalad/datalad#1128]
When I try to execute "datalad get" on python 3.5 I get the error 
`[ERROR  ] unorderable types: tuple() < list() [version.py:_cmp:173] (TypeError)`

This doesn't happen when datalad is run from a python 2.7 interpreter

Thanks for this tool!

**Comment by yarikoptic** [comment]
thanks for the report and especial thanks for thanks! (after all it is a thanksgiving day here)
failed to replicate on a simple try ... would you be kind to gather more detail?  e.g. run it with --dbg (i.e. `datalad --dbg get`) which then should fall into pdb upon failure -- check what are the entries and traceback (ideally also the module for which testing is happening)

**Comment by yarikoptic** [comment]
you might like to try https://github.com/datalad/datalad/pull/1129 but not sure if it addresses your issue @demianw

**Comment by demianw** [comment]
OK, first the debugging info, it seems that it's just a matter of version control and that in python 3.5 it ends up being a comparison of lists against tuples

datalad --dbg  get .
Traceback (most recent call last):
  File "/Users/dwasserm/anaconda/envs/root3.5/bin/datalad", line 11, in <module>
    sys.exit(main())
  File "/Users/dwasserm/anaconda/envs/root3.5/lib/python3.5/site-packages/datalad/cmdline/main.py", line 261, in main
    ret = cmdlineargs.func(cmdlineargs)
  File "/Users/dwasserm/anaconda/envs/root3.5/lib/python3.5/site-packages/datalad/interface/base.py", line 303, in call_from_parser
    return cls.__call__(**kwargs)
  File "/Users/dwasserm/anaconda/envs/root3.5/lib/python3.5/site-packages/datalad/distribution/get.py", line 289, in __call__
    recursion_limit=recursion_limit)
  File "/Users/dwasserm/anaconda/envs/root3.5/lib/python3.5/site-packages/datalad/distribution/get.py", line 95, in _sort_paths_into_datasets
    path, recursion_limit=1).path
  File "/Users/dwasserm/anaconda/envs/root3.5/lib/python3.5/site-packages/datalad/distribution/dataset.py", line 453, in get_containing_subdataset
    absolute=False):
  File "/Users/dwasserm/anaconda/envs/root3.5/lib/python3.5/site-packages/datalad/distribution/dataset.py", line 257, in get_subdatasets
    repo = self.repo
  File "/Users/dwasserm/anaconda/envs/root3.5/lib/python3.5/site-packages/datalad/distribution/dataset.py", line 129, in repo
    self._repo = cls(self._path, create=False, **kw)
  File "/Users/dwasserm/anaconda/envs/root3.5/lib/python3.5/site-packages/datalad/support/annexrepo.py", line 141, in __init__
    self._check_git_annex_version()
  File "/Users/dwasserm/anaconda/envs/root3.5/lib/python3.5/site-packages/datalad/support/annexrepo.py", line 283, in _check_git_annex_version
    elif ver < cls.GIT_ANNEX_MIN_VERSION:
  File "/Users/dwasserm/anaconda/envs/root3.5/lib/python3.5/distutils/version.py", line 52, in __lt__
    c = self._cmp(other)
  File "/Users/dwasserm/anaconda/envs/root3.5/lib/python3.5/distutils/version.py", line 173, in _cmp
    if self.version < other.version:
TypeError: unorderable types: tuple() < list()

> /Users/dwasserm/anaconda/envs/root3.5/lib/python3.5/distutils/version.py(173)_cmp()
-> if self.version < other.version:
(Pdb) self.version
(6, 20161118, 0)
(Pdb) other.version
[6, 20160808]
(Pdb)

**Comment by demianw** [comment]
Sadly, #1129  doesn't solve the issue

**Comment by yarikoptic** [comment]
wow -- I didn't realize that LooseVersion and StrictVersion are not "consistent" that much!:

```shell
$> python -c 'from distutils.version import LooseVersion as LV, StrictVersion as SV; print(SV("6.20161118").version, LV("6.20161118").version)' 
((6, 20161118, 0), [6, 20161118])

$> python3 -c 'from distutils.version import LooseVersion as LV, StrictVersion as SV; print(SV("6.20161118").version, LV("6.20161118").version)' 
(6, 20161118, 0) [6, 20161118]
```
and I am just amazed how our tests managed to miss that since we do test for python3 on github :-/   looking into gory details on both aspects now

**Comment by yarikoptic** [comment]
ok -- test have missed it since we never tested on a system which has "stock" (non snapshot) installation of git-annex, which would have then lead to having `StrictVersion`.  Now #1129 should resolve it once and for all!  THANKS again.
