### ISSUE TITLE
Hidden Exception problem?

### ISSUE THREAD

**Issue by mih** [datalad/datalad#1176]
While restoring my dev environment I stumbled upon this, which may be hidden, when all deps are installed, but could also be something totally different.

````
======================================================================
ERROR: datalad.tests.test_utils_testrepos.test_BasicAnnexTestRepo
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/mih/hacking/datalad/git/datalad/support/annexrepo.py", line 774, in get_file_key
    expect_fail=True)
  File "/home/mih/hacking/datalad/git/datalad/support/annexrepo.py", line 398, in _run_annex_command
    raise e
  File "/home/mih/hacking/datalad/git/datalad/support/annexrepo.py", line 390, in _run_annex_command
    return self.cmd_call_wrapper.run(cmd_list, **kwargs)
  File "/home/mih/hacking/datalad/git/datalad/cmd.py", line 455, in run
    cmd, env=self.get_git_environ_adjusted(), *args, **kwargs)
  File "/home/mih/hacking/datalad/git/datalad/cmd.py", line 370, in run
    raise CommandError(str(cmd), msg, status, out[0], out[1])
datalad.support.exceptions.CommandError: CommandError: command '['git', '-c', 'receive.autogc=0', '-c', 'gc.auto=0', 'annex', 'lookupkey', 'test.dat']' failed with exitcode 1
Failed to run ['git', '-c', 'receive.autogc=0', '-c', 'gc.auto=0', 'annex', 'lookupkey', 'test.dat'] under '/tmp/datalad_temp_test_BasicAnnexTestRepou5y_6g0j'. Exit code=1. out= err=

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/nose/case.py", line 198, in runTest
    self.test(*self.arg)
  File "/home/mih/hacking/datalad/git/datalad/tests/utils.py", line 536, in newfunc
    return t(*(arg + (filename,)), **kw)
  File "/home/mih/hacking/datalad/git/datalad/tests/test_utils_testrepos.py", line 51, in test_BasicAnnexTestRepo
    _test_BasicAnnexTestRepo(path)
  File "/home/mih/hacking/datalad/git/datalad/tests/test_utils_testrepos.py", line 34, in _test_BasicAnnexTestRepo
    ok_file_under_git(trepo.path, 'test.dat')
  File "/home/mih/hacking/datalad/git/datalad/tests/utils.py", line 215, in ok_file_under_git
    repo.get_file_key(file_repo_path)
  File "/home/mih/hacking/datalad/git/datalad/support/gitrepo.py", line 290, in newfunc
    result = func(self, files_new, *args, **kwargs)
  File "/home/mih/hacking/datalad/git/datalad/support/annexrepo.py", line 786, in get_file_key
    filename=files)
TypeError: RuntimeError.__new__(FileInGitError) is not safe, use OSError.__new__()

----------------------------------------------------------------------
Ran 559 tests in 285.725s

FAILED (SKIP=67, errors=10)
````

**Comment by mih** [comment]
@yarikoptic suggests swapping order of base classes of FileInGitError.
