### ISSUE TITLE
Custom remote implementation broken in direct mode

### ISSUE THREAD

**Issue by mih** [datalad/datalad#1209]
From tests

````
======================================================================
ERROR: datalad.customremotes.tests.test_archives.test_annex_get_from_subdir
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/travis/virtualenv/python2.7.12/lib/python2.7/site-packages/nose/case.py", line 197, in runTest
    self.test(*self.arg)
  File "/home/travis/build/datalad/datalad/datalad/tests/utils.py", line 401, in newfunc
    return t(*(arg + (d,)), **kw)
  File "/home/travis/build/datalad/datalad/datalad/customremotes/tests/test_archives.py", line 127, in test_annex_get_from_subdir
    add_archive_content('a.tar.gz', annex=annex, delete=True)
  File "/home/travis/build/datalad/datalad/datalad/interface/add_archive_content.py", line 229, in __call__
    raise RuntimeError("You better commit all the changes and untracked files first")
RuntimeError: You better commit all the changes and untracked files first
````

**Comment by kyleam** [comment]
It's marked as a known failure and direct mode is now obsolete.  Closing.
