### ISSUE TITLE
Prevent GitRepo from calling `git add` in direct mode

### ISSUE THREAD

**Issue by mih** [datalad/datalad#1210]
To prevent errors like this:

````
======================================================================
ERROR: datalad.distribution.tests.test_create_test_dataset.test_create_test_dataset
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/travis/virtualenv/python2.7.12/lib/python2.7/site-packages/nose/case.py", line 197, in runTest
    self.test(*self.arg)
  File "/home/travis/build/datalad/datalad/datalad/distribution/tests/test_create_test_dataset.py", line 43, in test_create_test_dataset
    dss = create_test_dataset(spec='2/1-2')
  File "/home/travis/build/datalad/datalad/datalad/distribution/create_test_dataset.py", line 168, in __call__
    return list(_makeds(path, levels))
  File "/home/travis/build/datalad/datalad/datalad/distribution/create_test_dataset.py", line 115, in _makeds
    for d in _makeds(subds_fpath, levels_, ds=ds_):
  File "/home/travis/build/datalad/datalad/datalad/distribution/create_test_dataset.py", line 115, in _makeds
    for d in _makeds(subds_fpath, levels_, ds=ds_):
  File "/home/travis/build/datalad/datalad/datalad/distribution/create_test_dataset.py", line 122, in _makeds
    dataset=ds,
  File "/home/travis/build/datalad/datalad/datalad/distribution/add.py", line 232, in __call__
    commit=False)
  File "/home/travis/build/datalad/datalad/datalad/support/gitrepo.py", line 296, in newfunc
    result = func(self, files_new, *args, **kwargs)
  File "/home/travis/build/datalad/datalad/datalad/support/gitrepo.py", line 785, in add
    ['git', 'add'] + assure_list(git_options) + ['--verbose']
  File "/home/travis/build/datalad/datalad/datalad/support/gitrepo.py", line 296, in newfunc
    result = func(self, files_new, *args, **kwargs)
  File "/home/travis/build/datalad/datalad/datalad/support/gitrepo.py", line 1262, in _git_custom_command
    expect_fail=expect_fail)
  File "/home/travis/build/datalad/datalad/datalad/cmd.py", line 494, in run
    cmd, env=self.get_git_environ_adjusted(), *args, **kwargs)
  File "/home/travis/build/datalad/datalad/datalad/cmd.py", line 371, in run
    raise CommandError(str(cmd), msg, status, out[0], out[1])
CommandError: CommandError: command '['git', '-c', 'receive.autogc=0', '-c', 'gc.auto=0', 'add', '--verbose', 'r0', '.gitmodules']' failed with exitcode 128
Failed to run ['git', '-c', 'receive.autogc=0', '-c', 'gc.auto=0', 'add', '--verbose', 'r0', '.gitmodules'] under '/tmp/datalad_temp_ds_aMPFa3/r0'. Exit code=128. out= err=fatal: This operation must be run in a work tree
fatal: 'git status --porcelain' failed in submodule r0
````

**Comment by bpoldrack** [comment]
Just as a note for now: This seems to be a (direct mode) annex, which is accessed via `GitRepo` instead of `AnnexRepo`. Don't know why yet, but this probably the issue.

**Comment by bpoldrack** [comment]
This is not actually a direct mode issue. This is really #1852. We randomly try to treat a direct mode repo as a `GitRepo` in this test, which has no clue of direct mode. The bug here is the test. Closing in favor of #1852.
