### ISSUE TITLE
GitRepo.tag() not working in direct mode

### ISSUE THREAD

**Issue by mih** [datalad/datalad#1211]
````
======================================================================
ERROR: datalad.distribution.tests.test_dataset.test_subdatasets
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/travis/virtualenv/python2.7.12/lib/python2.7/site-packages/nose/case.py", line 197, in runTest
    self.test(*self.arg)
  File "/home/travis/build/datalad/datalad/datalad/tests/utils.py", line 536, in newfunc
    return t(*(arg + (filename,)), **kw)
  File "/home/travis/build/datalad/datalad/datalad/distribution/tests/test_dataset.py", line 219, in test_subdatasets
    ds.save("Hello!", version_tag=1)
  File "/home/travis/build/datalad/datalad/datalad/distribution/dataset.py", line 566, in apply_func
    return f(**kwargs)
  File "/home/travis/build/datalad/datalad/datalad/interface/save.py", line 173, in __call__
    version_tag=version_tag)
  File "/home/travis/build/datalad/datalad/datalad/interface/utils.py", line 260, in save_dataset_hierarchy
    version_tag=version_tag)
  File "/home/travis/build/datalad/datalad/datalad/interface/utils.py", line 375, in save_dataset
    ds.repo.tag(version_tag)
  File "/home/travis/build/datalad/datalad/datalad/support/gitrepo.py", line 1781, in tag
    '', ['git', 'tag', str(tag)]
  File "/home/travis/build/datalad/datalad/datalad/support/gitrepo.py", line 296, in newfunc
    result = func(self, files_new, *args, **kwargs)
  File "/home/travis/build/datalad/datalad/datalad/support/gitrepo.py", line 1262, in _git_custom_command
    expect_fail=expect_fail)
  File "/home/travis/build/datalad/datalad/datalad/cmd.py", line 494, in run
    cmd, env=self.get_git_environ_adjusted(), *args, **kwargs)
  File "/home/travis/build/datalad/datalad/datalad/cmd.py", line 371, in run
    raise CommandError(str(cmd), msg, status, out[0], out[1])
CommandError: CommandError: command '['git', '-c', 'receive.autogc=0', '-c', 'gc.auto=0', '-c', 'core.bare=False', 'tag', '1']' failed with exitcode 128
Failed to run ['git', '-c', 'receive.autogc=0', '-c', 'gc.auto=0', '-c', 'core.bare=False', 'tag', '1'] under '/tmp/datalad_temp_test_subdatasetswDFIVp'. Exit code=128. out= err=fatal: Failed to resolve 'HEAD' as a valid ref.
````

**Comment by mih** [comment]
This test runs OK at present  -- also in direct mode.
