### ISSUE TITLE
GitRepo.get_active_branch() broken

### ISSUE THREAD

**Issue by mih** [datalad/datalad#1212]
here its is:

````mih@meiner /tmp/demo % git init
Initialized empty Git repository in /tmp/demo/.git/
mih@meiner /tmp/demo (git)-[master] % python -c "from datalad.support.gitrepo import GitRepo; print(GitRepo('.').get_active_branch())"
master
mih@meiner /tmp/demo (git)-[master] % touch test
1 mih@meiner /tmp/demo (git)-[master] % git add .
mih@meiner /tmp/demo (git)-[master] % git commit test
[master (root-commit) 2b9ee4b] Demo
 1 file changed, 0 insertions(+), 0 deletions(-)
 create mode 100644 test
mih@meiner /tmp/demo (git)-[master] % python -c "from datalad.support.gitrepo import GitRepo; print(GitRepo('.').get_active_branch())"
master
mih@meiner /tmp/demo (git)-[master] % touch test2
mih@meiner /tmp/demo (git)-[master] % git add .
mih@meiner /tmp/demo (git)-[master] % git commit test2 -m demo
[master 1ad90ee] demo
 1 file changed, 0 insertions(+), 0 deletions(-)
 create mode 100644 test2
mih@meiner /tmp/demo (git)-[master] % python -c "from datalad.support.gitrepo import GitRepo; print(GitRepo('.').get_active_branch())"
master
mih@meiner /tmp/demo (git)-[master] % git co HEAD~1
Note: checking out 'HEAD~1'.

You are in 'detached HEAD' state. You can look around, make experimental
changes and commit them, and you can discard any commits you make in this
state without impacting any branches by performing another checkout.

If you want to create a new branch to retain commits you create, you may
do so (now or later) by using -b with the checkout command again. Example:

  git checkout -b <new-branch-name>

HEAD is now at 2b9ee4b... Demo
mih@meiner /tmp/demo (git)-[2b9ee4b...] % python -c "from datalad.support.gitrepo import GitRepo; print(GitRepo('.').get_active_branch())"
Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "/home/mih/hacking/datalad/git/datalad/support/gitrepo.py", line 1010, in get_active_branch
    return self.repo.active_branch.name
  File "/home/mih/.local/lib/python2.7/site-packages/git/repo/base.py", line 649, in active_branch
    return self.head.reference
  File "/home/mih/.local/lib/python2.7/site-packages/git/refs/symbolic.py", line 251, in _get_reference
    raise TypeError("%s is a detached symbolic reference as it points to %r" % (self, sha))
TypeError: HEAD is a detached symbolic reference as it points to '2b9ee4b46009ea8b8ba060164ed83881b307442a'
````

Without an active branch it should probably return `None` and not just crash.

**Comment by mih** [comment]
There is a second issue that I couldn't triage yet. Under some conditions `get_active_branch()` returns something like `'refs/heads/master'` instead of just `'master'`. It seems to happen in publish quite frequenctly. I suspect this ruins a few things, as this would be the value to look for matching branches. Searching for the reason...

**Comment by bpoldrack** [comment]
Re detached HEAD: Agree, should be None, probably. I think this is a one liner.

**Comment by mih** [comment]
Ah, sorry, ignore the last one that is from get_tracking_branch() and is intended.
