### ISSUE TITLE
we are breeding git zombies like crazy

### ISSUE THREAD

**Issue by yarikoptic** [datalad/datalad#132]
in the docker buildbot slaves, we produce around 2k (across all 4 dockers) ```git <defunc>``` for each sweep, which is quite a number:

if before running any tests we have around 586 zombies:
```
(venv)buildbot@33c1b2f3efed:/tmp/test$ ps auxw | grep defunc | nl | tail -1
   587  buildbot 17824  0.0  0.0   8872   772 ?        S+   19:04   0:00 grep --color=auto defunc
```
and running pure git tests doesn't change it:
```
(venv)buildbot@33c1b2f3efed:/tmp/test$ nosetests datalad/tests/test_gitrepo.py
........
----------------------------------------------------------------------
Ran 8 tests in 1.005s

OK
(venv)buildbot@33c1b2f3efed:/tmp/test$ ps auxw | grep defunc | nl | tail -1
   587  buildbot 17850  0.0  0.0   8872   784 ?        S+   19:04   0:00 grep --color=auto defunc
```
Running annex tests (until a failure which I am yet to comprehend) results in the growing number of zombies:
```
(venv)buildbot@33c1b2f3efed:/tmp/test$ nosetests -x datalad/tests/test_annexrepo.py
...E
======================================================================
ERROR: datalad.tests.test_annexrepo.test_AnnexRepo_get_file_backend
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/usr/lib/python2.7/dist-packages/nose/case.py", line 197, in runTest
    self.test(*self.arg)
  File "/tmp/test/datalad/tests/utils.py", line 425, in newfunc
    t(*(arg + (repo,)), **kw)
  File "/tmp/test/datalad/tests/utils.py", line 302, in newfunc
    return t(*(arg + (filename,)), **kw)
  File "/tmp/test/datalad/tests/test_annexrepo.py", line 363, in test_AnnexRepo_get_file_backend
    ok_annex_get(ar, 'test-annex.dat')
  File "/tmp/test/datalad/tests/utils.py", line 172, in ok_annex_get
    ar.annex_get(files)
  File "/tmp/test/datalad/support/annexrepo.py", line 52, in newfunc
    return func(self, *args, options=option_list)
  File "/tmp/test/datalad/support/gitrepo.py", line 145, in newfunc
    result = func(self, files_new, *args, **kwargs)
  File "/tmp/test/datalad/support/annexrepo.py", line 262, in annex_get
    log_online=True, expect_stderr=True)
  File "/tmp/test/datalad/support/annexrepo.py", line 172, in _run_annex_command
    raise e
CommandError: CommandError: command '['git', 'annex', 'get', 'test-annex.dat']' failed with exitcode 1.
Failed to run ['git', 'annex', 'get', 'test-annex.dat'] under '/tmp/datalad_temp_test_AnnexRepo_get_file_backendFjB66o'. Exit code=1
-------------------- >> begin captured logging << --------------------
datalad.cmd: ERROR: Failed to run ['git', 'annex', 'get', 'test-annex.dat'] under '/tmp/datalad_temp_test_AnnexRepo_get_file_backendFjB66o'. Exit code=1
--------------------- >> end captured logging << ---------------------

----------------------------------------------------------------------
Ran 4 tests in 3.266s

FAILED (errors=1)
(venv)buildbot@33c1b2f3efed:/tmp/test$ ps auxw | grep defunc | nl | tail -3
   604  buildbot 18364  0.0  0.0      0     0 ?        Z    19:04   0:00 [git] <defunct>
   605  buildbot 18385  0.0  0.0      0     0 ?        Z    19:04   0:00 [git] <defunct>
   606  buildbot 18398  0.0  0.0   8872   776 ?        S+   19:06   0:00 grep --color=auto defunc
```

even running a simple 'git annex init' creates a single zombie:
```
(venv)buildbot@33c1b2f3efed:/tmp/test$ ps auxw | grep defunc | nl | tail -3
   604  buildbot 18364  0.0  0.0      0     0 ?        Z    19:04   0:00 [git] <defunct>
   605  buildbot 18385  0.0  0.0      0     0 ?        Z    19:04   0:00 [git] <defunct>
   606  buildbot 18417  0.0  0.0   8872   776 ?        S+   19:07   0:00 grep --color=auto defunc
(venv)buildbot@33c1b2f3efed:/tmp/test$ git annex init
init  ok
(recording state in git...)
(venv)buildbot@33c1b2f3efed:/tmp/test$ ps auxw | grep defunc | nl | tail -3
   605  buildbot 18385  0.0  0.0      0     0 ?        Z    19:04   0:00 [git] <defunct>
   606  buildbot 18443  0.0  0.0      0     0 ?        Z    19:07   0:00 [git] <defunct>
   607  buildbot 18458  0.0  0.0   8872   804 ?        S+   19:07   0:00 grep --color=auto defunc
```
@joeyh  any hints?

**Comment by joeyh** [comment]
init is responsible for waiting on zombies, and thanks to docker, you don't have an init in that container. The only sensible solution seems to be to add one, even if it's just a minimal pid 1 that waits on zombies and nothing else.

**Comment by yarikoptic** [comment]
resolved by using init in the dockers -- no zombies survived ;)
