### ISSUE TITLE
fetch fails in create_sibling call

### ISSUE THREAD

**Issue by yarikoptic** [datalad/datalad#1365]
Originally "reported" in the original #1356 ... now I managed to reproduce it (although in another test):

```
(git)hopa:~datalad/datalad[bf-publish]git
$> DATALAD_TESTS_SSH=1 nosetests -s -v datalad/distribution/tests/test_publish.py:test_publish_depends
                                                                                                                                                        
ERROR
Versions: cmd:annex=6.20170220+gitg75a15e1ad-1~ndall+1 cmd:git=2.11.0 cmd:system-git=2.11.0 git=2.1.0 tqdm=4.11.2

======================================================================
ERROR: datalad.distribution.tests.test_publish.test_publish_depends
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/usr/lib/python2.7/dist-packages/nose/case.py", line 197, in runTest
    self.test(*self.arg)
  File "/home/yoh/proj/datalad/datalad/datalad/tests/utils.py", line 818, in newfunc
    return func(*args, **kwargs)
  File "/home/yoh/proj/datalad/datalad/datalad/tests/utils.py", line 734, in newfunc
    t(*(arg + (uri,)), **kw)
  File "/home/yoh/proj/datalad/datalad/datalad/tests/utils.py", line 564, in newfunc
    return t(*(arg + (filename,)), **kw)
  File "/home/yoh/proj/datalad/datalad/datalad/tests/utils.py", line 564, in newfunc
    return t(*(arg + (filename,)), **kw)
  File "/home/yoh/proj/datalad/datalad/datalad/tests/utils.py", line 564, in newfunc
    return t(*(arg + (filename,)), **kw)
  File "/home/yoh/proj/datalad/datalad/datalad/tests/utils.py", line 564, in newfunc
    return t(*(arg + (filename,)), **kw)
  File "/home/yoh/proj/datalad/datalad/datalad/distribution/tests/test_publish.py", line 336, in test_publish_depends
    name='target1')
  File "/home/yoh/proj/datalad/datalad/datalad/distribution/dataset.py", line 577, in apply_func
    return f(**kwargs)
  File "/home/yoh/proj/datalad/datalad/datalad/distribution/create_sibling.py", line 562, in __call__
    inherit
  File "/home/yoh/proj/datalad/datalad/datalad/distribution/create_sibling.py", line 217, in _create_dataset_sibling
    inherit=inherit
  File "/home/yoh/proj/datalad/datalad/datalad/distribution/add_sibling.py", line 268, in __call__
    repo.fetch(name)
  File "/home/yoh/proj/datalad/datalad/datalad/support/gitrepo.py", line 1388, in fetch
    fi_list += rm.fetch(refspec=refspec, progress=progress, **kwargs)
  File "/usr/lib/python2.7/dist-packages/git/remote.py", line 752, in fetch
    res = self._get_fetch_info_from_stderr(proc, progress)
  File "/usr/lib/python2.7/dist-packages/git/remote.py", line 638, in _get_fetch_info_from_stderr
    proc.wait(stderr=stderr_text)
  File "/usr/lib/python2.7/dist-packages/git/cmd.py", line 290, in wait
    raise GitCommandError(self.args, status, errstr)
GitCommandError: Cmd('/usr/lib/git-annex.linux/git') failed due to: exit code(128)
  cmdline: /usr/lib/git-annex.linux/git -c receive.autogc=0 -c gc.auto=0 fetch -v target1
  stderr: 'fatal: Could not read from remote repository.

Please make sure you have the correct access rights
and the repository exists.'
-------------------- >> begin captured logging << --------------------
datalad.utils: Level 5: Importing datalad.utils
datalad.utils: Level 5: Done importing datalad.utils
datalad.cmd: DEBUG: Will use git under '/usr/lib/git-annex.linux' (no adjustments to PATH if empty string)
datalad.cmd: DEBUG: Running: ['git', 'config', '-z', '-l']
cwd: None
datalad.cmd: Level 8: Finished running ['git', 'config', '-z', '-l'] with status 0
datalad.ui: Level 5: Starting importing ui
datalad.ui.dialog: Level 5: Starting importing ui.dialog
datalad.ui.dialog: Level 5: Done importing ui.dialog
datalad.ui: Level 5: Initiating UI switcher
datalad.ui: DEBUG: UI set to DialogUI(out=<file>)
datalad.ui: Level 5: Done importing ui
--------------------- >> end captured logging << ---------------------
```

the "trigger" for me is to be outside of the virtualenv environment ... not yet sure how that matters here.  But if I run when activating my virtualenv -- test passes.  git module version is the same -- uses system wide one .  so the divergence remains a mystery

**Comment by mih** [comment]
FTR: I don't see this.

**Comment by bpoldrack** [comment]
For me it happens, too. It does not happen in a up-to-date virtualenv, but in an older one.

**Comment by bpoldrack** [comment]
But: If I manually go into the repo in question (post mortem), I can do the fetch without any error.

**Comment by bpoldrack** [comment]
Hehe - it's not a bug. It's a feature. ;-)

Since it is a SSH remote it uses `datalad shhrun`, called by git itself. If I pass a `GIT_TRACE=1` into that call (which is a bit tricky) I find the following:

```
git.cmd: DEBUG: Popen(['/usr/lib/git-annex.linux/git', '-c', 'receive.autogc=0', '-c', 'gc.auto=0', 'fetch', 'target1'], cwd=/tmp/datalad_temp_test_publish_dependsxjehsK, universal_newlines=False, shell=None)
git.cmd: INFO: /usr/lib/git-annex.linux/git -c receive.autogc=0 -c gc.auto=0 fetch target1 -> 128; stdout: '<OUTPUT_STREAM>'; stderr: '12:09:17.265666 git.c:371               trace: built-in: git 'fetch' 'target1'
12:09:17.266087 run-command.c:350       trace: run_command: 'datalad sshrun' 'localhost' 'git-upload-pack '\''/tmp/datalad_temp_test_publish_dependsVG8ceH'\'''
12:09:17.266362 run-command.c:209       trace: exec: '/bin/sh' '-c' 'datalad sshrun "$@"' 'datalad sshrun' 'localhost' 'git-upload-pack '\''/tmp/datalad_temp_test_publish_dependsVG8ceH'\'''
Traceback (most recent call last):
  File "/usr/local/bin/datalad", line 5, in <module>
    from pkg_resources import load_entry_point
  File "/usr/lib/python2.7/dist-packages/pkg_resources/__init__.py", line 2927, in <module>
    @_call_aside
  File "/usr/lib/python2.7/dist-packages/pkg_resources/__init__.py", line 2913, in _call_aside
    f(*args, **kwargs)
  File "/usr/lib/python2.7/dist-packages/pkg_resources/__init__.py", line 2940, in _initialize_master_working_set
    working_set = WorkingSet._build_master()
  File "/usr/lib/python2.7/dist-packages/pkg_resources/__init__.py", line 637, in _build_master
    return cls._build_from_requirements(__requires__)
  File "/usr/lib/python2.7/dist-packages/pkg_resources/__init__.py", line 650, in _build_from_requirements
    dists = ws.resolve(reqs, Environment())
  File "/usr/lib/python2.7/dist-packages/pkg_resources/__init__.py", line 829, in resolve
    raise DistributionNotFound(req, requirers)
pkg_resources.DistributionNotFound: The 'datalad==0.2.dev1' distribution was not found and is required by the application
fatal: Could not read from remote repository.
```

It looks for the wrong datalad version. Which explains it for me, since this is up-to-date in new virtualenv only.

**Comment by yarikoptic** [comment]
Thank you Ben!!!
I guess there is nothing we could do really about this without major pain or performance hit (as we could check when we run any first git command, either we could run datalad at all... Which is actually sensible), so I will close
