### ISSUE TITLE
segfault crash troubleshooting with gdb notes

### ISSUE THREAD

**Issue by yarikoptic** [datalad/datalad#1382]
so -- troubleshooting #1350 segfault... things has changed from how they were but finally I got gdb to report the traceback and wanted to put notes out somewhere. They are adhoc, was done in neurodebian:nd90 buildbot docker

- `apt-get install python-dbg`
- get our repo
- `virtualenv --python=python-dbg --system-site-packages venv-dbg`
- `source venv-dbg/bin/activate`
- `pip install -e '.[full]'` (also I installed wrapt from git but in general not needed)
- `cp /usr/share/gdb/auto-load/usr/lib/x86_64-linux-gnu/libpython2.7.so.1.0-gdb.py  libpython.py`
- run gdb with python with nose
```
PYTHONPATH=$PWD DATALAD_LOG_LEVEL=2 gdb --args  python   -c 'import nose; nose.main()' -s -v datalad/distribution/tests/test_install.py:test_install_crcns
```
- load this libpython thingie 
```python import libpython```
- `r` and whenever crashes can use `py-bt`:

```(gdb) py-bt
Traceback (most recent call first):
  Garbage-collecting
  <built-in function collect>
  File "/home/buildbot/datalad-michael-broke-it/venv-dbg/local/lib/python2.7/site-packages/git/repo/base.py", line 194, in close
    gc.collect()
  File "/home/buildbot/datalad-michael-broke-it/venv-dbg/local/lib/python2.7/site-packages/git/repo/base.py", line 189, in __del__
    self.close()
  File "/home/buildbot/datalad-michael-broke-it/datalad/distribution/tests/test_install.py", line 174, in test_install_crcns
    ds2 = Dataset('all-nonrecursive').install('crcns')
  File "/home/buildbot/datalad-michael-broke-it/datalad/tests/utils.py", line 564, in newfunc
    return t(*(arg + (filename,)), **kw)
  File "/home/buildbot/datalad-michael-broke-it/datalad/tests/utils.py", line 564, in newfunc
    return t(*(arg + (filename,)), **kw)
  File "/home/buildbot/datalad-michael-broke-it/datalad/support/vcr_.py", line 77, in wrapper
    return t(*args, **kwargs)
  File "/home/buildbot/datalad-michael-broke-it/datalad/tests/utils.py", line 775, in newfunc
    return func(*args, **kwargs)
  File "/usr/lib/python2.7/dist-packages/nose/case.py", line 197, in runTest
    self.test(*self.arg)
  File "/usr/lib/python2.7/unittest/case.py", line 329, in run
    testMethod()
  File "/usr/lib/python2.7/unittest/case.py", line 393, in __call__
    return self.run(*args, **kwds)
  File "/usr/lib/python2.7/dist-packages/nose/case.py", line 151, in runTest
    test(result)
  File "/usr/lib/python2.7/dist-packages/nose/case.py", line 133, in run
    self.runTest(result)
  File "/usr/lib/python2.7/dist-packages/nose/case.py", line 45, in __call__
    return self.run(*arg, **kwarg)
  File "/usr/lib/python2.7/dist-packages/nose/suite.py", line 224, in run
    test(orig)
  File "/usr/lib/python2.7/dist-packages/nose/suite.py", line 177, in __call__
    return self.run(*arg, **kw)
  File "/usr/lib/python2.7/dist-packages/nose/suite.py", line 224, in run
    test(orig)
  File "/usr/lib/python2.7/dist-packages/nose/suite.py", line 177, in __call__
    return self.run(*arg, **kw)
  File "/usr/lib/python2.7/dist-packages/nose/core.py", line 62, in run
    test(result)
  File "/usr/lib/python2.7/dist-packages/nose/core.py", line 207, in runTests
    result = self.testRunner.run(self.test)
  File "/usr/lib/python2.7/unittest/main.py", line 95, in __init__
    self.runTests()
  File "/usr/lib/python2.7/dist-packages/nose/core.py", line 121, in __init__
    **extra_args)
  File "<string>", line 1, in <module>
```

and regular gdb traceback "top" is:
```
(gdb) bt 15
#0  __GI_raise (sig=sig@entry=6) at ../sysdeps/unix/sysv/linux/raise.c:58
#1  0x00007ffff6f2d40a in __GI_abort () at abort.c:89
#2  0x00007ffff6f24e47 in __assert_fail_base (fmt=<optimized out>, assertion=assertion@entry=0x5555557fae87 "gc->gc.gc_refs != 0", file=file@entry=0x5555557fae40 "../Modules/gcmodule.c", line=line@entry=351, 
    function=function@entry=0x5555557fb2d8 <__PRETTY_FUNCTION__.9755> "update_refs") at assert.c:92
#3  0x00007ffff6f24ef2 in __GI___assert_fail (assertion=0x5555557fae87 "gc->gc.gc_refs != 0", file=0x5555557fae40 "../Modules/gcmodule.c", line=351, function=0x5555557fb2d8 <__PRETTY_FUNCTION__.9755> "update_refs")
    at assert.c:101
#4  0x0000555555712c3b in update_refs (containers=0x555555a7cd20 <generations+96>) at ../Modules/gcmodule.c:351
#5  0x0000555555713e48 in collect (generation=2) at ../Modules/gcmodule.c:924
#6  0x000055555571432b in gc_collect (self=0x0, args=(), kws=0x0) at ../Modules/gcmodule.c:1121
#7  0x00005555556187a8 in PyCFunction_Call (func=<built-in function collect>, arg=(), kw=0x0) at ../Objects/methodobject.c:85
#8  0x00005555556c4fc2 in call_function (pp_stack=0x7fffffff4ea0, oparg=0) at ../Python/ceval.c:4352
#9  0x00005555556bf5e1 in PyEval_EvalFrameEx (
    f=Frame 0x7ffff3557ba0, for file /home/buildbot/datalad-michael-broke-it/venv-dbg/local/lib/python2.7/site-packages/git/repo/base.py, line 194, in close (self=<Repo(git=<Git at remote 0x7ffff3548cd8>, working_dir='/tmp/datalad_temp_test_install_crcnsrR0VqX/all-nonrecursive', _bare=False, git_dir='/tmp/datalad_temp_test_install_crcnsrR0VqX/all-nonrecursive/.git', odb=<GitCmdObjectDB(_ostream=None, _hexsha_to_file={}, _fd_open_flags=262144, _root_path='/tmp/datalad_temp_test_install_crcnsrR0VqX/all-nonrecursive/.git/objects', _git=<...>) at remote 0x7ffff3a8bfb0>, _working_tree_dir='/tmp/datalad_temp_test_install_crcnsrR0VqX/all-nonrecursive') at remote 0x7ffff3a8bd10>), throwflag=0) at ../Python/ceval.c:2989
#10 0x00005555556c54bc in fast_function (func=<function at remote 0x7ffff3b7d1b0>, pp_stack=0x7fffffff5310, n=1, na=1, nk=0) at ../Python/ceval.c:4437
#11 0x00005555556c51b5 in call_function (pp_stack=0x7fffffff5310, oparg=0) at ../Python/ceval.c:4372
#12 0x00005555556bf5e1 in PyEval_EvalFrameEx (
    f=Frame 0x7ffff35579c0, for file /home/buildbot/datalad-michael-broke-it/venv-dbg/local/lib/python2.7/site-packages/git/repo/base.py, line 189, in __del__ (self=<Repo(git=<Git at remote 0x7ffff3548cd8>, working_dir='/tmp/datalad_temp_test_install_crcnsrR0VqX/all-nonrecursive', _bare=False, git_dir='/tmp/datalad_temp_test_install_crcnsrR0VqX/all-nonrecursive/.git', odb=<GitCmdObjectDB(_ostream=None, _hexsha_to_file={}, _fd_open_flags=262144, _root_path='/tmp/datalad_temp_test_install_crcnsrR0VqX/all-nonrecursive/.git/objects', _git=<...>) at remote 0x7ffff3a8bfb0>, _working_tree_dir='/tmp/datalad_temp_test_install_crcnsrR0VqX/all-nonrecursive') at remote 0x7ffff3a8bd10>), throwflag=0) at ../Python/ceval.c:2989
#13 0x00005555556c25ee in PyEval_EvalCodeEx (co=0x7ffff3ba8b40, 
    globals={'handle_process_output': <function at remote 0x7ffff42abe28>, 'Git': <type at remote 0x5555561bd4b0>, 'find_submodule_git_dir': <function at remote 0x7ffff3b774f8>, 'osp': <module at remote 0x7ffff7ee6060>, 'PY3': False, 'Actor': <type at remote 0x555556198dc0>, 'hex_to_bin': <built-in function a2b_hex>, 'decygpath': <function at remote 0x7ffff42fc990>, 'Submodule': <type at remote 0x5555561f09a0>, 'gc': <module at remote 0x7ffff5aa7f68>, 'Commit': <type at remote 0x5555561b5190>, 'touch': <function at remote 0x7ffff3b773a8>, 'BlameEntry': <type at remote 0x5555561fe130>, 'DefaultDBType': <type at remote 0x5555561a4030>, 'Head': <type at remote 0x5555561f4590>, 'log': <Logger(name='git.repo.base', parent=<Logger(name='git', parent=<RootLogger(name='root', parent=None, handlers=[<MyMemoryHandler(level=0, buffer=['datalad.utils: Level 5: Importing datalad.utils', 'datalad.utils: Level 5: Done importing datalad.utils', "datalad.cmd: DEBUG: Will use git under '/usr/lib/git-annex.linux' (no adjustments to PATH if...(truncated), locals=0x0, args=0x7ffff3614be8, argcount=1, kws=0x0, kwcount=0, defs=0x0, 
    defcount=0, closure=0x0) at ../Python/ceval.c:3584
#14 0x00005555555f465f in function_call (func=<function at remote 0x7ffff3b7d108>, 
    arg=(<Repo(git=<Git at remote 0x7ffff3548cd8>, working_dir='/tmp/datalad_temp_test_install_crcnsrR0VqX/all-nonrecursive', _bare=False, git_dir='/tmp/datalad_temp_test_install_crcnsrR0VqX/all-nonrecursive/.git', odb=<GitCmdObjectDB(_ostream=None, _hexsha_to_file={}, _fd_open_flags=262144, _root_path='/tmp/datalad_temp_test_install_crcnsrR0VqX/all-nonrecursive/.git/objects', _git=<...>) at remote 0x7ffff3a8bfb0>, _working_tree_dir='/tmp/datalad_temp_test_install_crcnsrR0VqX/all-nonrecursive') at remote 0x7ffff3a8bd10>,), kw=0x0) at ../Objects/funcobject.c:523
...
#29 0x000055555561f0bb in _Py_Dealloc (
    op=<Dataset(_cfg=None, _repo=<GitRepo(realpath=<unknown at remote 0x7ffff354d9d0>, _GIT_COMMON_OPTIONS=['-c', 'receive.autogc=0', '-c', 'gc.auto=0'], cmd_call_wrapper=<unknown at remote 0x7ffff3580ec0>, repo=<Repo(git=<Git at remote 0x7ffff3548cd8>, working_dir='/tmp/datalad_temp_test_install_crcnsrR0VqX/all-nonrecursive', _bare=False, git_dir='/tmp/datalad_temp_test_install_crcnsrR0VqX/all-nonrecursive/.git', odb=<GitCmdObjectDB(_ostream=None, _hexsha_to_file={}, _fd_open_flags=262144, _root_path='/tmp/datalad_temp_test_install_crcnsrR0VqX/all-nonrecursive/.git/objects', _git=<...>) at remote 0x7ffff3a8bfb0>, _working_tree_dir='/tmp/datalad_temp_test_install_crcnsrR0VqX/all-nonrecursive') at remote 0x7ffff3a8bd10>, _cfg=None, path='/tmp/datalad_temp_test_install_crcnsrR0VqX/all-nonrecursive') at remote 0x7ffff373c370>, _id=None, _path='/tmp/datalad_temp_test_install_crcnsrR0VqX/all-nonrecursive') at remote 0x7ffff4b8e8b0>) at ../Objects/object.c:2262
#30 0x00007ffff4e323e4 in WraptFunctionWrapperBase_clear (self=0x7ffff3578ba0) at src/wrapt/_wrappers.c:1898
#31 0x00007ffff4e32657 in WraptFunctionWrapperBase_dealloc (self=0x7ffff3578ba0) at src/wrapt/_wrappers.c:1911
#32 0x000055555561f0bb in _Py_Dealloc (op=<BoundFunctionWrapper at remote 0x7ffff3578ba0>) at ../Objects/object.c:2262
#33 0x00005555556c52fd in call_function (pp_stack=0x7fffffff6030, oparg=1) at ../Python/ceval.c:4385
...
```

so at `#9` you can see the close call.  

`valgrind --leak-check=full --track-origins=yes` output around that point of crash is:

```
[DEBUG] Running: ['git', 'config', '-z', '-l']
| cwd: /tmp/datalad_temp_test_install_crcnswAlX64
[Level 8] Finished running ['git', 'config', '-z', '-l'] with status 0
==12629== Invalid write of size 8
==12629==    at 0x1E5A33: gc_list_remove (gcmodule.c:251)
==12629==    by 0x1E5A33: PyObject_GC_Del (gcmodule.c:1557)
==12629==    by 0x240DB8: PyTuple_ClearFreeList (tupleobject.c:905)
==12629==    by 0x1E6377: clear_freelists (gcmodule.c:843)
==12629==    by 0x1E6377: collect.lto_priv.1950 (gcmodule.c:1020)
==12629==    by 0x2A37E8: gc_collect.lto_priv.2658 (gcmodule.c:1121)
==12629==    by 0x2033C9: call_function (ceval.c:4352)
==12629==    by 0x2033C9: PyEval_EvalFrameEx (ceval.c:2989)
==12629==    by 0x208C1E: fast_function (ceval.c:4437)
==12629==    by 0x208C1E: call_function (ceval.c:4372)
==12629==    by 0x208C1E: PyEval_EvalFrameEx (ceval.c:2989)
==12629==    by 0x201534: PyEval_EvalCodeEx (ceval.c:3584)
==12629==    by 0x21DCED: function_call.lto_priv.296 (funcobject.c:523)
==12629==    by 0x1EF672: PyObject_Call (abstract.c:2547)
==12629==    by 0x233FED: instancemethod_call.lto_priv.215 (classobject.c:2602)
==12629==    by 0x1EF672: PyObject_Call (abstract.c:2547)
==12629==    by 0x20D47C: PyEval_CallObjectWithKeywords (ceval.c:4221)
==12629==  Address 0x8 is not stack'd, malloc'd or (recently) free'd
==12629==
==12629==
==12629== Process terminating with default action of signal 11 (SIGSEGV): dumping core
==12629==  Access not within mapped region at address 0x8
==12629==    at 0x1E5A33: gc_list_remove (gcmodule.c:251)
==12629==    by 0x1E5A33: PyObject_GC_Del (gcmodule.c:1557)
==12629==    by 0x240DB8: PyTuple_ClearFreeList (tupleobject.c:905)
==12629==    by 0x1E6377: clear_freelists (gcmodule.c:843)
==12629==    by 0x1E6377: collect.lto_priv.1950 (gcmodule.c:1020)
==12629==    by 0x2A37E8: gc_collect.lto_priv.2658 (gcmodule.c:1121)
==12629==    by 0x2033C9: call_function (ceval.c:4352)
==12629==    by 0x2033C9: PyEval_EvalFrameEx (ceval.c:2989)
==12629==    by 0x208C1E: fast_function (ceval.c:4437)
==12629==    by 0x208C1E: call_function (ceval.c:4372)
==12629==    by 0x208C1E: PyEval_EvalFrameEx (ceval.c:2989)
==12629==    by 0x201534: PyEval_EvalCodeEx (ceval.c:3584)
==12629==    by 0x21DCED: function_call.lto_priv.296 (funcobject.c:523)
==12629==    by 0x1EF672: PyObject_Call (abstract.c:2547)
==12629==    by 0x233FED: instancemethod_call.lto_priv.215 (classobject.c:2602)
==12629==    by 0x1EF672: PyObject_Call (abstract.c:2547)
==12629==    by 0x20D47C: PyEval_CallObjectWithKeywords (ceval.c:4221)
==12629==  If you believe this happened as a result of a stack
==12629==  overflow in your program's main thread (unlikely but
==12629==  possible), you can try to increase the size of the
==12629==  main thread stack using the --main-stacksize= flag.
==12629==  The main thread stack size used in this run was 8388608.
==12629==
==12629== HEAP SUMMARY:
==12629==     in use at exit: 14,248,744 bytes in 14,105 blocks
==12629==   total heap usage: 248,027 allocs, 233,922 frees, 218,197,419 bytes allocated
...
```
full log: http://www.onerussian.com/tmp/valgrind-track-origins.log

checking with wrapt:  https://github.com/GrahamDumpleton/wrapt/issues/98

**Comment by mih** [comment]
Closing. Ping #1392
