### ISSUE TITLE
crashes in non-friendly way when ran from non-existing dir

### ISSUE THREAD

**Issue by yarikoptic** [datalad/datalad#1402]
(/tmp/123 was removed before running)
```shell
hopa:/tmp/123
$> datalad --help
sh: 0: getcwd() failed: No such file or directory
No handlers could be found for logger "datalad.cmd"
Traceback (most recent call last):
  File "/usr/bin/datalad", line 7, in <module>
    from datalad.cmdline.main import main
  File "/usr/lib/python2.7/dist-packages/datalad/__init__.py", line 25, in <module>
    cfg = ConfigManager()
  File "/usr/lib/python2.7/dist-packages/datalad/config.py", line 160, in __init__
    self.reload()
  File "/usr/lib/python2.7/dist-packages/datalad/config.py", line 187, in reload
    stdout, stderr = self._run(['-z', '-l'], log_stderr=True)
  File "/usr/lib/python2.7/dist-packages/datalad/config.py", line 448, in _run
    out = self._runner.run(['git', 'config'] + args, **kwargs)
  File "/usr/lib/python2.7/dist-packages/datalad/cmd.py", line 383, in run
    raise CommandError(str(cmd), msg, status, out[0], out[1])
datalad.support.exceptions.CommandError: CommandError: command '['git', 'config', '-z', '-l']' failed with exitcode 128
Failed to run ['git', 'config', '-z', '-l'] under None. Exit code=128. out= err=fatal: Unable to read current working directory: No such file or directory
```
for comparison `git --help` is happy to be helpful in such case ;-)
we should at least crash without backtrace imho

**Comment by mih** [comment]
But what would be the fix? Wrap every command invocation with a test if the PWD is still there? And this has not much to do with a cmdline invocation. The same thing happens on `import datalad`. Shall we test for PWD on import? And if it is not there? If we don't want a backtrace we cannot raise an exception. I think it might be best not to remove PWD.

**Comment by yarikoptic** [comment]
fix could be as ugly as
```patch
$> git diff
diff --git a/datalad/config.py b/datalad/config.py
index 6abfebba..012c4f90 100644
--- a/datalad/config.py
+++ b/datalad/config.py
@@ -9,6 +9,7 @@
 """
 """
 
+from datalad.support.exceptions import CommandError
 from datalad.cmd import Runner
 from datalad.dochelpers import exc_str
 import re
@@ -184,9 +185,20 @@ class ConfigManager(object):
             self._store.update(self.overrides)
             return
 
-        stdout, stderr = self._run(['-z', '-l'], log_stderr=True)
-        self._store = _parse_gitconfig_dump(
-            stdout, self._store, replace=True)
+        try:
+            stdout, stderr = self._run(['-z', '-l'], log_stderr=True)
+            self._store = _parse_gitconfig_dump(
+                stdout, self._store, replace=True)
+        except CommandError as exc:
+            # For anal yoh who wants still to output --help output
+            # even when we fail to load precious config since running
+            # from non-existing directory
+            import sys
+            if '--help' in sys.argv and 'Unable to read current working' in exc.stderr:
+                # Just let it complain and output our precious help
+                self._store = {}
+            else:
+                raise  # re-raise otherwise
 
         # superimpose overrides
         self._store.update(self.overrides)
```
but indeed not sure if worth it... so whatever -- closing ;)
