### ISSUE TITLE
add an assert within setup_module to check if git was configured

### ISSUE THREAD

**Issue by yarikoptic** [datalad/datalad#1435]
ATM many tests would simply start to fail and even nose itself would then freak out
```
======================================================================
ERROR: Failure: TypeError (issubclass() arg 1 must be a class)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/opt/conda/lib/python3.5/site-packages/nose/failure.py", line 39, in runTest
    raise self.exc_val.with_traceback(self.tb)
  File "/opt/conda/lib/python3.5/site-packages/nose/loader.py", line 523, in makeTest
    return self._makeTest(obj, parent)
  File "/opt/conda/lib/python3.5/site-packages/nose/loader.py", line 576, in _makeTest
    if issubclass(parent, unittest.TestCase):
TypeError: issubclass() arg 1 must be a class
```
making it not really obvious of what is going on. so we better check if user.email and user.name are set in the config before we proceed to test anything

**Comment by yarikoptic** [comment]
@satra (FYI)
this is actually a common problem "in real world", e.g. has been happening to nipype workshop attendees who use docker to enter env, with (only) `~/work` being bind-mounted inside. So whatever settings they have done (in `~/.gitconfig`) in the previous container, were lost if a new container using an updated image was used.  Next time, I guess, would be better to bind-mount entire within-docker home  image so any changes to the settings are preserved across `run`s

So I think we should just make datalad do those checks (once) upon initial `GitRepo` construction
