### ISSUE TITLE
WindowsError: [Error 32] The process cannot access the file because it is being used by another process: 'C:\\tmp\\datalad_temp_outputs_od4enw'

### ISSUE THREAD

**Issue by yarikoptic** [datalad/datalad#147]
```
WindowsError: [Error 32] The process cannot access the file because it is being used by another process: 'C:\\tmp\\datalad_temp_outputs_od4enw'
```
full trace
```
======================================================================
ERROR: datalad.tests.test_annexrepo.test_AnnexRepo_backend_option
----------------------------------------------------------------------
Traceback (most recent call last):
  File "c:\python27\lib\site-packages\nose\case.py", line 197, in runTest
    self.test(*self.arg)
  File "c:\buildslave\datalad-pr-virtualbox-dl-win7-64\build\datalad\tests\utils.py", line 196, in newfunc
    t(*(arg + (d,)), **kw)
  File "c:\buildslave\datalad-pr-virtualbox-dl-win7-64\build\datalad\tests\utils.py", line 250, in newfunc
    func(*(arg + (path, url,)), **kw)
  File "c:\buildslave\datalad-pr-virtualbox-dl-win7-64\build\datalad\tests\test_annexrepo.py", line 346, in test_AnnexRepo_backend_option
    ar.annex_addurls([url +'faraway'], backend='SHA1')
  File "C:\Python27\Lib\contextlib.py", line 24, in __exit__
    self.gen.next()
  File "c:\buildslave\datalad-pr-virtualbox-dl-win7-64\build\datalad\utils.py", line 275, in swallow_outputs
    adapter.cleanup()
  File "c:\buildslave\datalad-pr-virtualbox-dl-win7-64\build\datalad\utils.py", line 246, in cleanup
    rmtemp(self._out.name)
  File "c:\buildslave\datalad-pr-virtualbox-dl-win7-64\build\datalad\utils.py", line 135, in rmtemp
    os.unlink(f)
WindowsError: [Error 32] The process cannot access the file because it is being used by another process: 'C:\\tmp\\datalad_temp_outputs_od4enw'
```
probably we need a workaround which would just try to remove a few times with some delay -- it feels like a race condition somewhere :-/

**Comment by yarikoptic** [comment]
I think it is a race condition with the gc which is to remove the handler instance we created -- "del"ing it explicitly prior unlink might help, looping within rmtemp could beneficial anyways

**Comment by bpoldrack** [comment]
Any ideas how to test a possible solution? As far as I'm aware, this doesn't always happen, so passing on windows isn't proving it's an actual solution.

**Comment by yarikoptic** [comment]
you could loop 10 times and verify that it works -- probably would be the best check we could come up with -- but do it prior fix and see if it gets triggered ;)

**Comment by yarikoptic** [comment]
well -- #152 is merged so let's let this one RiP
