### ISSUE TITLE
Dataset.add fails miserably due to crash within GitPython -- if operated within "reincarnated repo"

### ISSUE THREAD

**Issue by yarikoptic** [datalad/datalad#1512]
The code is as simple as `ds.add("newsub")` although ran within ASV benchmarking so may be there was some "massaging" of ds somehow (picking/unpickling but unlikely).  And then kaboom
```
               [INFO] Creating a new annex repo at /home/yoh/.tmp/datalad_temp_ds_rAq5E0_clone/newsubds 
               Traceback (most recent call last):
                 File "/home/yoh/proj/datalad/datalad/venvs/dev/local/lib/python2.7/site-packages/asv/benchmark.py", line 796, in <module>
                   commands[mode](args)
                 File "/home/yoh/proj/datalad/datalad/venvs/dev/local/lib/python2.7/site-packages/asv/benchmark.py", line 773, in main_run
                   result = benchmark.do_run()
                 File "/home/yoh/proj/datalad/datalad/venvs/dev/local/lib/python2.7/site-packages/asv/benchmark.py", line 456, in do_run
                   return self.run(*self._current_params)
                 File "/home/yoh/proj/datalad/datalad/venvs/dev/local/lib/python2.7/site-packages/asv/benchmark.py", line 549, in run
                   all_runs.extend(timer.repeat(repeat, number))
                 File "/usr/lib/python2.7/timeit.py", line 230, in repeat
                   t = self.timeit(number)
                 File "/usr/lib/python2.7/timeit.py", line 202, in timeit
                   timing = self.inner(it, self.timer)
                 File "/usr/lib/python2.7/timeit.py", line 100, in inner
                   _func()
                 File "/home/yoh/proj/datalad/datalad/venvs/dev/local/lib/python2.7/site-packages/asv/benchmark.py", line 513, in <lambda>
                   func = lambda: self.func(*param)
                 File "/home/yoh/proj/datalad/datalad/benchmarks/benchmarks.py", line 133, in time_createadd_to_dataset
                   self.ds.add(subds.path)
                 File "/home/yoh/proj/datalad/datalad/.asv/env/1b5862776063636a1bd6a1931ef20cce/local/lib/python2.7/site-packages/datalad/distribution/dataset.py", line 451, in apply_func
                   return f(**kwargs)
                 File "/home/yoh/proj/datalad/datalad/.asv/env/1b5862776063636a1bd6a1931ef20cce/local/lib/python2.7/site-packages/datalad/interface/utils.py", line 1109, in eval_func
                   return return_func(generator_func)(*args, **kwargs)
                 File "/home/yoh/proj/datalad/datalad/.asv/env/1b5862776063636a1bd6a1931ef20cce/local/lib/python2.7/site-packages/datalad/interface/utils.py", line 1097, in return_func
                   results = list(results)
                 File "/home/yoh/proj/datalad/datalad/.asv/env/1b5862776063636a1bd6a1931ef20cce/local/lib/python2.7/site-packages/datalad/interface/utils.py", line 1008, in generator_func
                   for res in results:
                 File "/home/yoh/proj/datalad/datalad/.asv/env/1b5862776063636a1bd6a1931ef20cce/local/lib/python2.7/site-packages/datalad/distribution/add.py", line 326, in __call__
                   message=message if message else '[DATALAD] added content'):
                 File "/home/yoh/proj/datalad/datalad/.asv/env/1b5862776063636a1bd6a1931ef20cce/local/lib/python2.7/site-packages/datalad/interface/utils.py", line 312, in save_dataset_hierarchy
                   version_tag=version_tag)
                 File "/home/yoh/proj/datalad/datalad/.asv/env/1b5862776063636a1bd6a1931ef20cce/local/lib/python2.7/site-packages/datalad/interface/utils.py", line 353, in save_dataset
                   orig_hexsha = ds.repo.get_hexsha()
                 File "/home/yoh/proj/datalad/datalad/.asv/env/1b5862776063636a1bd6a1931ef20cce/local/lib/python2.7/site-packages/datalad/support/gitrepo.py", line 993, in get_hexsha
                   return self.repo.head.object.hexsha
                 File "/home/yoh/proj/datalad/datalad/.asv/env/1b5862776063636a1bd6a1931ef20cce/local/lib/python2.7/site-packages/git/refs/symbolic.py", line 169, in _get_object
                   return Object.new_from_sha(self.repo, hex_to_bin(self.dereference_recursive(self.repo, self.path)))
                 File "/home/yoh/proj/datalad/datalad/.asv/env/1b5862776063636a1bd6a1931ef20cce/local/lib/python2.7/site-packages/git/objects/base.py", line 64, in new_from_sha
                   oinfo = repo.odb.info(sha1)
                 File "/home/yoh/proj/datalad/datalad/.asv/env/1b5862776063636a1bd6a1931ef20cce/local/lib/python2.7/site-packages/git/db.py", line 37, in info
                   hexsha, typename, size = self._git.get_object_header(bin_to_hex(sha))
                 File "/home/yoh/proj/datalad/datalad/.asv/env/1b5862776063636a1bd6a1931ef20cce/local/lib/python2.7/site-packages/git/cmd.py", line 936, in get_object_header
                   return self.__get_object_header(cmd, ref)
                 File "/home/yoh/proj/datalad/datalad/.asv/env/1b5862776063636a1bd6a1931ef20cce/local/lib/python2.7/site-packages/git/cmd.py", line 925, in __get_object_header
                   return self._parse_object_header(cmd.stdout.readline())
                 File "/home/yoh/proj/datalad/datalad/.asv/env/1b5862776063636a1bd6a1931ef20cce/local/lib/python2.7/site-packages/git/cmd.py", line 889, in _parse_object_header
                   raise ValueError("SHA %s could not be resolved, git returned: %r" % (tokens[0], header_line.strip()))
               ValueError: SHA 9cb3db34bd9dc9e43cda685491361c0ef0ee2466 could not be resolved, git returned: '9cb3db34bd9dc9e43cda685491361c0ef0ee2466 missing'
```
So far possible idea is just that 'gc' is performed somewhere and PythonGit's instance doesn't get aware of it

info -- datalad is of 0.5.x (0.5.1-97-gf817243a).

Actually I have somehow managed to "heal" it ... kept working on the benchmarks and then it was gone, not sure what change attributed, so I will open and then close this issue as non-reproducible but want to have a note of it.... ACTUALLY -- managed to reproduce!!!  as of  cdedf35df502762eeba977f03ad7842777543722  which will be pushed as a part of the next PR where I hope to get back to the usable state first :-/  so no autoclose :-/

**Comment by yarikoptic** [comment]
grr -- probably not calls to `gc` since when I shimmed all (hopefully) calls to git to call it with ` -c receive.autogc=0 -c gc.auto=0 `) -- the same story :-(  it sucks

**Comment by yarikoptic** [comment]
ok -- the reason is Singletons !  what is happening is 
- created a dataset, thus initiated GitRepo for it etc
- tarballed it, and removed original directory  (some batched processes remain running)
- extracted tarball under the same path -- singletons kicked in
- added a new commit
- requested that stale GitRepo instance which is running within now non existing repo to give me information about the HEAD
- kaboom!

So -- singletons should probably monitor also something about the original directory where they are running, e.g. inodes for their repo directory and verify that it is the same one whenever asked for already existing instance/path.

**Comment by bpoldrack** [comment]
Hm. Tried to reproduce the failure with test from within `test_gitrepo.py`
Doesn't fail. So, there's something I missed in your description of the reproductional procedure, I guess.

```python
@with_tempfile(mkdir=True)
@with_tempfile()
def test_GitRepo_flyweight_monitoring_inode(path, store):
    # testing for issue #1512

    repo = GitRepo(path, create=True)
    with open(opj(path, "testfile.txt"), "w") as f:
        f.write("whatever")
    repo.add("testfile.txt", commit=True, msg="some load")

    # move everything to store
    import os
    import shutil
    old_inode = os.stat(path).st_ino
    shutil.copytree(path, store, symlinks=True)
    # kill original
    rmtree(path)
    assert (not exists(path))
    # recreate
    shutil.copytree(store, path, symlinks=True)
    new_inode = os.stat(path).st_ino
    assert_not_equal(old_inode, new_inode)

    # requesting HEAD info from old instance
    hexsha = repo.repo.head.object.hexsha

    with open(opj(path, "testfile.txt"), "w") as f:
        f.write("whatever else")
    repo.add("testfile.txt", commit=True, msg="new commit")

    # requesting HEAD info from old instance
    hexsha = repo.repo.head.object.hexsha
```

May be you can point me to the actual code pieces, that are producing this.

**Comment by yarikoptic** [comment]
Hey -- thanks for looking into it @bpoldrack !!!
exact code is now merged:  https://github.com/datalad/datalad/blob/master/benchmarks/benchmarks.py#L103  

you should be able to reproduce it by running those benchmarks, after removing adding a unique indexed suffix in line  https://github.com/datalad/datalad/blob/master/benchmarks/benchmarks.py#L138   ... so let me try to reproduce:

```shell
$> echo asv run --python=2.7 --dry-run --bench .*SuperdatasetsOperationsSuite.time_createadd -v HEAD^..HEAD 
asv run --python=2.7 --dry-run --bench .*SuperdatasetsOperationsSuite.time_createadd -v HEAD^..HEAD
.... lots of output -- make terminal wide ,....

$> git diff benchmarks/benchmarks.py
diff --git a/benchmarks/benchmarks.py b/benchmarks/benchmarks.py
index 31d0ffec..efeeef5c 100644
--- a/benchmarks/benchmarks.py
+++ b/benchmarks/benchmarks.py
@@ -135,7 +135,7 @@ class SuperdatasetsOperationsSuite(SuprocBenchmarks):
 
         # TODO -- remove this abomination after https://github.com/datalad/datalad/issues/1512 is fixed
         epath = opj(tempdir, 'testds1')
-        epath_unique = epath + str(SuperdatasetsOperationsSuite.ds_count)
+        epath_unique = epath # + str(SuperdatasetsOperationsSuite.ds_count)
         os.rename(epath, epath_unique)
         SuperdatasetsOperationsSuite.ds_count += 1
         self.ds = Dataset(epath_unique)
````

**Comment by yarikoptic** [comment]
in your attempt you are dealing with GitRepo, not Dataset ... also try to request current branch hexsha I guess -- I believe it was that git batched command started by GitPython which was holding on ;)

**Comment by bpoldrack** [comment]
Update:
I can reproduce it now, by adding an additional request of `repo.repo.head.object.hexsha` to the code above. So yes: This apparently causes GitPython to keep a git process running. And using `GitRepo` is sufficient for reproducing of course ;-)
