### ISSUE TITLE
Build failures in master

### ISSUE THREAD

**Issue by mih** [datalad/datalad#1522]
These are old friends by now -- time to get rid of them...

TESTS_NONETWORK

````
======================================================================
FAIL: datalad.tests.test_tests_utils.test_get_resolved_values
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/travis/virtualenv/python2.7.13/lib/python2.7/site-packages/nose/case.py", line 197, in runTest
    self.test(*self.arg)
  File "/home/travis/build/datalad/datalad/datalad/tests/test_tests_utils.py", line 145, in test_get_resolved_values
    eq_(flavors, _get_resolved_flavors(flavors))
AssertionError: ['networkish', 'local'] != ['local']
````

Last remaining timeouts (actual timeout is happening very close to the end of the examples in both cases): 

- tests with sudo (any idea why this should be 10+ min slower than a normal full test run?)
- tests with traceback log

In general the performance differences between identical test runs on travis can be quite massive. We should probably further increase the runtime margin. In the present form the test success labels are mostly useless.

NFSMOUNT test currently re-running.

**Comment by mih** [comment]
master is happy
