### ISSUE TITLE
datalad does not work within Git bash on Windows

### ISSUE THREAD

**Issue by mih** [datalad/datalad#1566]
Not sure what the core issue is, or what could be done about it. I do know that GitPython doesn't see Git, maybe because it tries an absolute windows path that bash on Windows cannot handle.

````
$ DATALAD_LOG_LEVEL=1 python -c 'from datalad.support.gitrepo import GitRepo; r=GitRepo("dummy", create=True)'
[Level 5] Done importing main __init__
[Level 5] Importing support.network
[Level 5] Done importing support.network
[Level 5] Parsed ri dummy into fields {'username': '', 'scheme': '', 'fragment': '', 'hostname': '', 'query': '', 'path': 'dummy', 'password': '', 'port': ''}
[Level 5] Detected file ri
[DEBUG] Initialize empty Git repository at 'C:\Users\Pussy Galore\datalad\dummy'
Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "datalad\support\repo.py", line 146, in __call__
    instance = type.__call__(cls, *new_args, **new_kwargs)
  File "datalad\support\gitrepo.py", line 534, in __init__
    **git_opts)
  File "datalad\cmd.py", line 134, in __call__
    return self.call(cmd, *args, **kwargs)
  File "datalad\cmd.py", line 485, in call
    return f(*args, **kwargs)
  File "C:\Python27\lib\site-packages\git\repo\base.py", line 851, in init
    git.init(**kwargs)
  File "C:\Python27\lib\site-packages\git\cmd.py", line 423, in <lambda>
    return lambda *args, **kwargs: self._call_process(name, *args, **kwargs)
  File "C:\Python27\lib\site-packages\git\cmd.py", line 868, in _call_process
    return self.execute(call, **_kwargs)
  File "C:\Python27\lib\site-packages\git\cmd.py", line 600, in execute
    raise GitCommandNotFound(command, err)
git.exc.GitCommandNotFound: Cmd('C:\Program Files\Git\usr\bin\git') not found due to: WindowsError('[Error 2] Das System kann die angegebene Datei nicht finden')
  cmdline: C:\Program Files\Git\usr\bin\git init
[Level 5] Exiting
````

but

````
$ git version
git version 2.10.2.windows.1
````

**Comment by bpoldrack** [comment]
Looking into it.
We probably have the same issue - not just GitPython. Will check this out. I suspect the issue is the path. We (and probably GitPython) check whether we are on windows, which is true. The we use windows path notation. But that shell would use `/c/Program Files/...` instead of `C:\Program Files\...`.

**Comment by mih** [comment]
Yes. Given the SSH issue the question is what flavour of Windows we want to support. Maybe we should limit general support to basic functionality and recommend Win10+WSL for the complete experience.

**Comment by yarikoptic** [comment]
+1
I think providing full support might be too involved.

**Comment by mih** [comment]
I will close this now. Git bash is not part of the core issues that prevent windows functionality.
