### ISSUE TITLE
Unclear ignored exception in test -- segfault related?

### ISSUE THREAD

**Issue by mih** [datalad/datalad#1635]
This is in master 9f485f6182cf12361cacbaa97adfa1f045505f17

@yarikoptic 
````
DATALAD_LOG_LEVEL=warning PATH=~/hacking/datalad/git/bin:$PATH PYTHONPATH=~/hacking/datalad/git DATALAD_TESTS_SSH=1 nosetests3 -s datalad/interface/tests/test_annotate_paths.py:test_annotate_paths  -v     
datalad.interface.tests.test_annotate_paths.test_annotate_paths ... [ERROR  ] given reference dataset is not a dataset [annotate_path(/tmp/datalad_temp_test_annotate_paths0nbbwnnb)] 
Exception ignored in: <bound method AnnexRepo.__del__ of <AnnexRepo path=/tmp/datalad_temp_tree_test_annotate_pathsopcdq_hf/b/bb/bba/bbaa (<class 'datalad.support.annexrepo.AnnexRepo'>)>>
Traceback (most recent call last):
  File "/home/mih/hacking/datalad/git/datalad/support/annexrepo.py", line 275, in __del__
    super(AnnexRepo, self).__del__()
  File "/home/mih/hacking/datalad/git/datalad/support/gitrepo.py", line 695, in __del__
    if hasattr(self, 'repo') and self.repo is not None \
  File "/home/mih/hacking/datalad/git/datalad/support/gitrepo.py", line 582, in repo
    self._repo = self.cmd_call_wrapper(Repo, self.path)
  File "/home/mih/hacking/datalad/git/datalad/cmd.py", line 134, in __call__
    return self.call(cmd, *args, **kwargs)
  File "/home/mih/hacking/datalad/git/datalad/cmd.py", line 493, in call
    return f(*args, **kwargs)
  File "/home/mih/hacking/datalad/git/datalad/support/gitrepo.py", line 360, in Repo
    return gitpy.Repo(*args, **kwargs)
  File "/usr/lib/python3/dist-packages/git/repo/base.py", line 156, in __init__
    raise InvalidGitRepositoryError(epath)
git.exc.InvalidGitRepositoryError: /tmp/datalad_temp_tree_test_annotate_pathsopcdq_hf/b/bb/bba/bbaa
Exception ignored in: <bound method AnnexRepo.__del__ of <AnnexRepo path=/tmp/datalad_temp_tree_test_annotate_pathsopcdq_hf/b/bb/bba (<class 'datalad.support.annexrepo.AnnexRepo'>)>>
Traceback (most recent call last):
  File "/home/mih/hacking/datalad/git/datalad/support/annexrepo.py", line 275, in __del__
    super(AnnexRepo, self).__del__()
  File "/home/mih/hacking/datalad/git/datalad/support/gitrepo.py", line 695, in __del__
    if hasattr(self, 'repo') and self.repo is not None \
  File "/home/mih/hacking/datalad/git/datalad/support/gitrepo.py", line 582, in repo
    self._repo = self.cmd_call_wrapper(Repo, self.path)
  File "/home/mih/hacking/datalad/git/datalad/cmd.py", line 134, in __call__
    return self.call(cmd, *args, **kwargs)
  File "/home/mih/hacking/datalad/git/datalad/cmd.py", line 493, in call
    return f(*args, **kwargs)
  File "/home/mih/hacking/datalad/git/datalad/support/gitrepo.py", line 360, in Repo
    return gitpy.Repo(*args, **kwargs)
  File "/usr/lib/python3/dist-packages/git/repo/base.py", line 156, in __init__
    raise InvalidGitRepositoryError(epath)
git.exc.InvalidGitRepositoryError: /tmp/datalad_temp_tree_test_annotate_pathsopcdq_hf/b/bb/bba
Exception ignored in: <bound method AnnexRepo.__del__ of <AnnexRepo path=/tmp/datalad_temp_tree_test_annotate_pathsopcdq_hf/b/bb (<class 'datalad.support.annexrepo.AnnexRepo'>)>>
Traceback (most recent call last):
  File "/home/mih/hacking/datalad/git/datalad/support/annexrepo.py", line 275, in __del__
    super(AnnexRepo, self).__del__()
  File "/home/mih/hacking/datalad/git/datalad/support/gitrepo.py", line 695, in __del__
    if hasattr(self, 'repo') and self.repo is not None \
  File "/home/mih/hacking/datalad/git/datalad/support/gitrepo.py", line 582, in repo
    self._repo = self.cmd_call_wrapper(Repo, self.path)
  File "/home/mih/hacking/datalad/git/datalad/cmd.py", line 134, in __call__
    return self.call(cmd, *args, **kwargs)
  File "/home/mih/hacking/datalad/git/datalad/cmd.py", line 493, in call
    return f(*args, **kwargs)
  File "/home/mih/hacking/datalad/git/datalad/support/gitrepo.py", line 360, in Repo
    return gitpy.Repo(*args, **kwargs)
  File "/usr/lib/python3/dist-packages/git/repo/base.py", line 156, in __init__
    raise InvalidGitRepositoryError(epath)
git.exc.InvalidGitRepositoryError: /tmp/datalad_temp_tree_test_annotate_pathsopcdq_hf/b/bb
ok
Versions: cmd:annex=6.20170220+gitg75a15e1ad-1~ndall+1 cmd:git=2.11.0 cmd:system-git=2.11.0 cmd:system-ssh=7.4p1 git=2.1.1 tqdm=4.11.2

----------------------------------------------------------------------
Ran 1 test in 18.160s

OK
````

**Comment by mih** [comment]
PY2 run for comparison:

````
% DATALAD_LOG_LEVEL=warning PATH=~/hacking/datalad/git/bin:$PATH PYTHONPATH=~/hacking/datalad/git DATALAD_TESTS_SSH=1 nosetests -s datalad/interface/tests/test_annotate_paths.py:test_annotate_paths  -v 
datalad.interface.tests.test_annotate_paths.test_annotate_paths ... [ERROR  ] given reference dataset is not a dataset [annotate_path(/tmp/datalad_temp_test_annotate_pathsMYkWgc)] 
ok
Versions: cmd:annex=6.20170220+gitg75a15e1ad-1~ndall+1 cmd:git=2.11.0 cmd:system-git=2.11.0 cmd:system-ssh=7.4p1 git=2.1.1 tqdm=4.11.2

----------------------------------------------------------------------
Ran 1 test in 17.432s

OK
````

**Comment by yarikoptic** [comment]
My wild guess it's that s directory gets removed prior del is called. Worth checking i guess

**Comment by mih** [comment]
I cannot see this in master anymore.
