### ISSUE TITLE
test_plugins.py:test_plugin_call fails if invoked in source tree outside of git

### ISSUE THREAD

**Issue by yarikoptic** [datalad/datalad#1676]
which caused FTBFS of updated Debian package

```shell
(git)hopa:~datalad/datalad-master[debian]git
$> mv .git .git_aside
(dev) 2 32811 [2].....................................:Sun 30 Jul 2017 11:41:44 PM EDT:.
(git)hopa:~datalad[master]datalad-master
$> python -m nose -s -v datalad/plugin/tests/test_plugins.py:test_plugin_call
datalad.plugin.tests.test_plugins.test_plugin_call ... >>>/home/yoh/proj/datalad/datalad-master
ERROR
Versions: cmd:annex=6.20170525+gitge1cf095ae-1~ndall+1 cmd:git=2.11.0 cmd:system-git=2.11.0 cmd:system-ssh=7.4p1 git=2.1.1 tqdm=4.11.2

======================================================================
ERROR: datalad.plugin.tests.test_plugins.test_plugin_call
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/usr/lib/python2.7/dist-packages/nose/case.py", line 197, in runTest
    self.test(*self.arg)
  File "/home/yoh/proj/datalad/datalad-master/datalad/tests/utils.py", line 592, in newfunc
    return t(*(arg + (filename,)), **kw)
  File "/home/yoh/proj/datalad/datalad-master/datalad/tests/utils.py", line 592, in newfunc
    return t(*(arg + (filename,)), **kw)
  File "/home/yoh/proj/datalad/datalad-master/datalad/plugin/tests/test_plugins.py", line 106, in test_plugin_call
    res = list(plugin(['dummy', 'noval=one', 'obscure=some']))
  File "/home/yoh/proj/datalad/datalad-master/datalad/interface/utils.py", line 731, in eval_func
    return return_func(generator_func)(*args, **kwargs)
  File "/home/yoh/proj/datalad/datalad-master/datalad/interface/utils.py", line 719, in return_func
    results = list(results)
  File "/home/yoh/proj/datalad/datalad-master/datalad/interface/utils.py", line 676, in generator_func
    result_renderer, result_xfm, _result_filter, **_kwargs):
  File "/home/yoh/proj/datalad/datalad-master/datalad/interface/utils.py", line 743, in _process_results
    for res in results:
  File "/home/yoh/proj/datalad/datalad-master/datalad/plugin/__init__.py", line 245, in __call__
    purpose='handover to plugin')
  File "/home/yoh/proj/datalad/datalad-master/datalad/distribution/dataset.py", line 530, in require_dataset
    "{0}.".format(dataset.path))
ValueError: No installed dataset found at /home/yoh/proj/datalad/datalad-master.
-------------------- >> begin captured logging << --------------------
datalad.utils: Level 5: Importing datalad.utils
datalad.utils: Level 5: Done importing datalad.utils
datalad.cmd: DEBUG: Will use git under '/usr/lib/git-annex.linux' (no adjustments to PATH if empty string)
datalad.cmd: DEBUG: Running: ['git', 'version']
datalad.cmd: Level 8: Finished running ['git', 'version'] with status 0
datalad.cmd: DEBUG: Running: ['git', 'config', '-z', '-l', '--show-origin']
datalad.cmd: Level 8: Finished running ['git', 'config', '-z', '-l', '--show-origin'] with status 0
datalad.ui: Level 5: Starting importing ui
datalad.ui.dialog: Level 5: Starting importing ui.dialog
datalad.ui.dialog: Level 5: Done importing ui.dialog
datalad.ui: Level 5: Initiating UI switcher
datalad.ui: DEBUG: UI set to DialogUI(out=<file>)
datalad.ui: Level 5: Done importing ui
datalad.plugin: WARNING: ignoring plugin argument(s) set(['obscure']), not supported by plugin
--------------------- >> end captured logging << ---------------------
```

I am not quite sure if assumption here is indeed to be within dataset whenever plugin is invoked, and ideally probably some more descriptive message should be thrown describing that plugin must be invoked while under a dataset (or explicitly provided).  For now I will fix up the test to disregard that we are not in an installed dataset

**Comment by mih** [comment]
I guess this is fixed now?

**Comment by mih** [comment]
No longer an issue in master.
