### ISSUE TITLE
new way to push errors all the way up complicates --dbg troubleshooting

### ISSUE THREAD

**Issue by yarikoptic** [datalad/datalad#1698]
While looking at #1696  `--on-failure=stop`  worked out splendidly and stopped whenever first install failed! 
but also it stopped somewhat suboptimally with `--dbg` since now I just ending up somewhere in `datalad/interface/utils.py` while handling `incomplete_results` which resulted from the original exception I wanted to investigate, instead of that very exception... I wonder if we could do anything about that since it makes `--dbg` mode is largely useless

```
alchen@discovery:/mnt/scratch/yoh$ rm -rf datasets.datalad.org;  datalad install ///; datalad --dbg --on-failure=stop install -r datasets.datalad.org/adhd200
[INFO   ] Cloning dataset from 'http://datasets.datalad.org/' (trying 2 location candidate(s)) to '/mnt/scratch/yoh/datasets.datalad.org' 
install(ok): /mnt/scratch/yoh/datasets.datalad.org (dataset)
[INFO   ] Cloning dataset from 'http://datasets.datalad.org/adhd200/.git' (trying 1 location candidate(s)) to '/mnt/scratch/yoh/datasets.datalad.org/adhd200' 
[ERROR  ] Installation of subdatasets /mnt/scratch/yoh/datasets.datalad.org/adhd200 failed with exception: SHA could not be resolved, git returned: '' [cmd.py:_parse_object_header:891] [install(/mnt/scratch/yoh/datasets.datalad.org/adhd200)] 
Traceback (most recent call last):
  File "/usr/bin/datalad", line 8, in <module>
    main()
  File "/usr/lib/python2.7/dist-packages/datalad/cmdline/main.py", line 348, in main
    ret = cmdlineargs.func(cmdlineargs)
  File "/usr/lib/python2.7/dist-packages/datalad/interface/base.py", line 424, in call_from_parser
    ret = list(ret)
  File "/usr/lib/python2.7/dist-packages/datalad/interface/utils.py", line 707, in generator_func
    msg="Command did not complete successfully")
IncompleteResultsError: Command did not complete successfully [{'status': 'error', 'action': 'install', 'path': '/mnt/scratch/yoh/datasets.datalad.org/adhd200', 'type': 'dataset', 'message': ('Installation of subdatasets %s failed with exception: %s', '/mnt/scratch/yoh/datasets.datalad.org/adhd200', "SHA could not be resolved, git returned: '' [cmd.py:_parse_object_header:891]")}]
()
> /usr/lib/python2.7/dist-packages/datalad/interface/utils.py(707)generator_func()
-> msg="Command did not complete successfully")
(Pdb) l
702                                     for act in sorted(action_summary))))
703     
704                 if incomplete_results:
705                     raise IncompleteResultsError(
706                         failed=incomplete_results,
707  ->                     msg="Command did not complete successfully")
708     
709             if return_type == 'generator':
710                 # hand over the generator
711                 return generator_func(*args, **kwargs)
712             else:
(Pdb) p incomplete_results
[{'status': 'error', 'action': 'install', 'path': '/mnt/scratch/yoh/datasets.datalad.org/adhd200', 'type': 'dataset', 'message': ('Installation of subdatasets %s failed with exception: %s', '/mnt/scratch/yoh/datasets.datalad.org/adhd200', "SHA could not be resolved, git returned: '' [cmd.py:_parse_object_header:891]")}]
```

if original exception was propagated up as well (not just a message with some details), at least there may be was a chance to get to that frame?

**Comment by bpoldrack** [comment]
Indeed. We would need to include the original exception similarly to how we allow the original logger to be used, I guess.

**Comment by yarikoptic** [comment]
actually, if we don't reraise that exception (and instead raise a new IncompleteResultsError) I guess we would never be able to get to that stack position to investigate details... at least may be we could discover the stack

**Comment by mih** [comment]
I am closing this, because no additional info was provided and in more than two years the issue wasn't severe enough for anyone to actually work on it. The information is still present, even when it is closed.
