### ISSUE TITLE
test_failed_clone  fails locally

### ISSUE THREAD

**Issue by yarikoptic** [datalad/datalad#1704]
was testing a new build of git-annex with patched git to avoid #1678 and other nastiness on NFS
and the  test failed, downgraded -- the same:
```
$> nosetests -s -v /home/yoh/proj/datalad/datalad/datalad/distribution/tests/test_clone.py:test_failed_clone
datalad.distribution.tests.test_clone.test_failed_clone ... FAIL
Versions: cmd:annex=6.20170525+gitge1cf095ae-1~ndall+1 cmd:git=2.11.0 cmd:system-git=2.14.0 cmd:system-ssh=7.4p1 git=2.1.1 tqdm=4.11.2

======================================================================
FAIL: datalad.distribution.tests.test_clone.test_failed_clone
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/usr/lib/python2.7/dist-packages/nose/case.py", line 197, in runTest
    self.test(*self.arg)
  File "/home/yoh/proj/datalad/datalad/datalad/tests/utils.py", line 592, in newfunc
    return t(*(arg + (filename,)), **kw)
  File "/home/yoh/proj/datalad/datalad/datalad/distribution/tests/test_clone.py", line 280, in test_failed_clone
    assert_status('error', res)
  File "/home/yoh/proj/datalad/datalad/datalad/tests/utils.py", line 971, in assert_status
    assert_in(r['status'], label)
AssertionError: 'ok' not found in ['error']
-------------------- >> begin captured logging << --------------------
datalad.utils: Level 5: Importing datalad.utils
datalad.utils: Level 5: Done importing datalad.utils
datalad.cmd: DEBUG: Will use git under '/usr/lib/git-annex.linux' (no adjustments to PATH if empty string)
datalad.cmd: DEBUG: Running: ['git', 'version']
datalad.cmd: Level 8: Finished running ['git', 'version'] with status 0
datalad.cmd: DEBUG: Running: ['git', 'config', '-z', '-l', '--show-origin']
datalad.cmd: Level 8: Finished running ['git', 'config', '-z', '-l', '--show-origin'] with status 0
datalad.ui: Level 5: Starting importing ui
datalad.ui.dialog: Level 5: Starting importing ui.dialog
datalad.ui.dialog: Level 5: Done importing ui.dialog
datalad.ui: Level 5: Initiating UI switcher
datalad.ui: DEBUG: UI set to DialogUI(out=<file>)
datalad.ui: Level 5: Done importing ui
--------------------- >> end captured logging << ---------------------

----------------------------------------------------------------------
Ran 1 test in 1.918s

FAILED (failures=1)
```
since those two kept failing regardless of annex version, uploading that new standalone build to neurodebian

**Comment by mih** [comment]
Also note that master is broken since the merge of https://github.com/datalad/datalad/pull/1684

**Comment by mih** [comment]
```sh
% nosetests -s -v datalad/distribution/tests/test_clone.py:test_failed_clone     
datalad.distribution.tests.test_clone.test_failed_clone ... ok
Versions: cmd:annex=6.20170815+gitg22da64d0f-1~ndall+1 cmd:git=2.11.0 cmd:system-git=2.11.0 cmd:system-ssh=7.4p1 git=2.1.1 tqdm=4.11.2

----------------------------------------------------------------------
Ran 1 test in 1.414s

OK
```

Intermittent issue? Close?

**Comment by mih** [comment]
Will close this after a ~2 month grace period....
