### ISSUE TITLE
publish crashed with sequence item 1: expected string, NoneType found [publish.py:has_diff:90] (TypeError)

### ISSUE THREAD

**Issue by yarikoptic** [datalad/datalad#1811]
```shell
% datalad publish --to=datalad-public --missing=inherit -r
[INFO   ] Publishing <Dataset path=/mnt/btrfs/datasets/datalad/crawl/workshops/nipype-2017/ds000114> data to datalad-public 
[INFO   ] Actually copying 8 files 
publish(notneeded): workshops/nipype-2017/ds000114 (dataset)                                                                                            
publish(notneeded): workshops/nipype-2017 (dataset)
...  lots of notneeded entries, although I thought that by default --since last push should have been in effect!
publish(notneeded): crcns/aa-1 (dataset)
publish(notneeded): crcns (dataset)
[ERROR  ] sequence item 1: expected string, NoneType found [publish.py:has_diff:90] (TypeError) 
datalad publish --to=datalad-public --missing=inherit -r  166.99s user 55.13s system 61% cpu 6:03.21 total
```

datalad `0.8.1-210-g869f97e8` ... will retry now with --dbg to get a better glimpse (if reproducible)

**Comment by yarikoptic** [comment]
here is the reason -- detached head (shouldn't happen but we shouldn't crash I guess)
```shell
publish(notneeded): crcns (dataset)
2017-09-08 13:09:04,700 [DEBUG  ] Using existing Git repository at /mnt/btrfs/datasets/datalad/crawl/corr/Resources 
2017-09-08 13:09:04,700 [DEBUG  ] detached HEAD in <AnnexRepo path=/mnt/btrfs/datasets/datalad/crawl/corr/Resources (<class 'datalad.support.annexrepo.AnnexRepo'>)> 
Traceback (most recent call last):
  File "/home/yoh/proj/datalad/datalad-master/venvs/dev/bin/datalad", line 8, in <module>
    main()
  File "/home/yoh/proj/datalad/datalad-master/datalad/cmdline/main.py", line 348, in main
    ret = cmdlineargs.func(cmdlineargs)
  File "/home/yoh/proj/datalad/datalad-master/datalad/interface/base.py", line 424, in call_from_parser
    ret = list(ret)
  File "/home/yoh/proj/datalad/datalad-master/datalad/interface/utils.py", line 382, in generator_func
    result_renderer, result_xfm, _result_filter, **_kwargs):
  File "/home/yoh/proj/datalad/datalad-master/datalad/interface/utils.py", line 449, in _process_results
    for res in results:
  File "/home/yoh/proj/datalad/datalad-master/datalad/distribution/publish.py", line 792, in __call__
    **res_kwargs):
  File "/home/yoh/proj/datalad/datalad-master/datalad/distribution/publish.py", line 302, in _publish_dataset
    diff = True if force else has_diff(ds, refspec, remote, paths)
  File "/home/yoh/proj/datalad/datalad-master/datalad/distribution/publish.py", line 90, in has_diff
    remote_ref = '/'.join((remote, remote_branch_name))
TypeError: sequence item 1: expected string, NoneType found
()
> /home/yoh/proj/datalad/datalad-master/datalad/distribution/publish.py(90)has_diff()
-> remote_ref = '/'.join((remote, remote_branch_name))
```

**Comment by yarikoptic** [comment]
actually since I think we can't just `git push` a ref to the remote, we should probably crash BUT with an informative message ... that "impossible" result with explanation that HEAD is detached and we don't know which branch it should be pushed.

**Comment by mih** [comment]
Here is how to produce the error:

```
(datalad3-dev) mih@meiner /tmp % datalad create orig
[INFO   ] Creating a new annex repo at /tmp/orig 
create(ok): /tmp/orig (dataset)                                                                                              
(datalad3-dev) mih@meiner /tmp % touch orig/some
(datalad3-dev) mih@meiner /tmp % datalad save -d orig
add(ok): some (file)
save(ok): . (dataset)
action summary:
  add (ok: 1)
  save (ok: 1)
(datalad3-dev) mih@meiner /tmp % datalad install -s orig clone
[INFO   ] Cloning orig into '/tmp/clone' 
install(ok): /tmp/clone (dataset)
(datalad3-dev) mih@meiner /tmp % touch clone/somemore
(datalad3-dev) mih@meiner /tmp % rm orig/somemore
(datalad3-dev) mih@meiner /tmp % datalad save -d clone
add(ok): somemore (file)
save(ok): . (dataset)
action summary:
  add (ok: 1)
  save (ok: 1)
(datalad3-dev) mih@meiner /tmp % cd clone
(datalad3-dev) mih@meiner /tmp/clone (git)-[master] % git checkout HEAD~1
Note: checking out 'HEAD~1'.

You are in 'detached HEAD' state. You can look around, make experimental
changes and commit them, and you can discard any commits you make in this
state without impacting any branches by performing another checkout.

If you want to create a new branch to retain commits you create, you may
do so (now or later) by using -b with the checkout command again. Example:

  git checkout -b <new-branch-name>

HEAD is now at 9995911 [DATALAD] Recorded changes
(datalad3-dev) 1 mih@meiner /tmp/clone (git)-[9995911...] % datalad publish --to origin
[ERROR  ] sequence item 1: expected str instance, NoneType found [publish.py:has_diff:89] (TypeError) 
```

**Comment by mih** [comment]
Within the scope of https://github.com/datalad/datalad/pull/6666 I came to realize that the current behavior re this issue in `push` is suboptimal. I does error, but it does not seem to be true that

> we don't know which branch it should be pushed

in the standard case, we should push the `git-annex` branch, even when we are on a detached head. Currently `push` would refuse to work in such a case. Needlessly so, I think.
