### ISSUE TITLE
publish -r --since=COMMIT manages to consider a file to be a dataset

### ISSUE THREAD

**Issue by yarikoptic** [datalad/datalad#1813]
I let previously interrupted (see #1812) publish to go on and this time it crashed:

```shell
$> DATALAD_LOG_TIMESTAMP=1 datalad --dbg publish --to=datalad-public --missing=inherit -r --since=e1046e69133df9f6ab933a7759a64c2536b0ce0e      
Traceback (most recent call last):
  File "/home/yoh/proj/datalad/datalad-master/venvs/dev/bin/datalad", line 8, in <module>
    main()
  File "/home/yoh/proj/datalad/datalad-master/datalad/cmdline/main.py", line 348, in main
    ret = cmdlineargs.func(cmdlineargs)
  File "/home/yoh/proj/datalad/datalad-master/datalad/interface/base.py", line 424, in call_from_parser
    ret = list(ret)
  File "/home/yoh/proj/datalad/datalad-master/datalad/interface/utils.py", line 382, in generator_func
    result_renderer, result_xfm, _result_filter, **_kwargs):
  File "/home/yoh/proj/datalad/datalad-master/datalad/interface/utils.py", line 449, in _process_results
    for res in results:
  File "/home/yoh/proj/datalad/datalad-master/datalad/distribution/publish.py", line 723, in __call__
    ap['path'], ds_remote_info, to, missing)
  File "/home/yoh/proj/datalad/datalad-master/datalad/distribution/publish.py", line 487, in _get_remote_info
    elif to not in ds.repo.get_remotes():
AttributeError: 'NoneType' object has no attribute 'get_remotes'
()
> /home/yoh/proj/datalad/datalad-master/datalad/distribution/publish.py(487)_get_remote_info()
-> elif to not in ds.repo.get_remotes():
(Pdb) p ds
<Dataset path=/mnt/btrfs/datasets/datalad/crawl/openfmri/ds000002/changelog.txt>
(Pdb) p ds.repo
None
(Pdb) l
482  	            return ('notneeded',
483  	                    'Cannot determine target sibling, skipping publication')
484  	        else:
485  	            # we have no remote given and no upstream
486  	            return 'error', 'Cannot determine a default target sibling for publication'
487  ->	    elif to not in ds.repo.get_remotes():
488  	        # unknown given remote
489  	        if missing == 'skip':
490  	            ds_remote_info[ds_path] = None
491  	            return ('notneeded',
492  	                    ("Unkown target sibling '%s', skipping publication", to))
(Pdb) up
> /home/yoh/proj/datalad/datalad-master/datalad/distribution/publish.py(723)__call__()
-> ap['path'], ds_remote_info, to, missing)
(Pdb) l
718  	                # this is a dataset
719  	                if ap.get('state', None) == 'absent':
720  	                    continue
721  	                # get the remote info for itself
722  	                remote_info_result = _get_remote_info(
723  ->	                    ap['path'], ds_remote_info, to, missing)
724  	                ap['process_content'] = True
725  	            if remote_info_result is not None:
726  	                ap['status'] = remote_info_result[0]
727  	                ap['message'] = remote_info_result[1]
728  	                yield ap
(Pdb) p ap['path']
'/mnt/btrfs/datasets/datalad/crawl/openfmri/ds000002/changelog.txt'
(Pdb) p ds_remote_info
{'/mnt/btrfs/datasets/datalad/crawl/openfmri/ds000002': {'remote': 'datalad-public'}, '/mnt/btrfs/datasets/datalad/crawl/openfmri': {'remote': 'datalad-public'}, '/mnt/btrfs/datasets/datalad/crawl/openfmri/ds000001': {'remote': 'datalad-public'}, '/mnt/btrfs/datasets/datalad/crawl/openfmri/ds000006': {'remote': 'datalad-public'}, '/mnt/btrfs/datasets/datalad/crawl/openfmri/ds000003': {'remote': 'datalad-public'}, '/mnt/btrfs/datasets/datalad/crawl/kaggle': {'remote': 'datalad-public'}, '/mnt/btrfs/datasets/datalad/crawl/openfmri/ds000005': {'remote': 'datalad-public'}, '/mnt/btrfs/datasets/datalad/crawl/dbic/QA': {'remote': 'datalad-public'}, '/mnt/btrfs/datasets/datalad/crawl/dbic': {'remote': 'datalad-public'}}
(Pdb) p to
'datalad-public'
(Pdb) p missing
'inherit'
```
the situation is that apparently openfmri superdataset is dirty because that ds000002 progressed forward but wasn't yet committed within openfmri... and I guess crash is because that changelog.txt is the diff between previous and new states:
```shell
(git)smaug:/mnt/btrfs/datasets/datalad/crawl/openfmri[master]git
$> git diff ds000002 
diff --git a/ds000002 b/ds000002
index b98c69f..4f2be86 160000
--- a/ds000002
+++ b/ds000002
@@ -1 +1 @@
-Subproject commit b98c69ff35a0393d55bc957f0f419800d8b649f7
+Subproject commit 4f2be86d6d79139191971113d66aefc9b8e8621e
(dev)1 10296.....................................:Fri 08 Sep 2017 01:37:51 PM EDT:.
(git)smaug:/mnt/btrfs/datasets/datalad/crawl/openfmri[master]git
$> git -C ds000002 diff b98c69ff35a0393d55bc957f0f419800d8b649f7..4f2be86d6d79139191971113d66aefc9b8e8621e --stat
 .datalad/crawl/statuses/incoming.json | 19 ++++++++-----------
 changelog.txt                         |  1 -
```

In general I guess resolution for this particular should be to filter out annotated paths for having only datasets?

**Comment by yarikoptic** [comment]
and that is f.cking awesome @mih, thanks!
```shell
$> datalad diff -r    
   modified(dataset): ds000001
   modified(dataset): ds000002
   modified(dataset): ds000003
      modified(file): ds000001/.datalad/crawl/statuses/incoming.json
      modified(file): ds000002/.datalad/crawl/statuses/incoming.json
           deleted(): ds000002/changelog.txt
      modified(file): ds000003/.datalad/crawl/statuses/incoming.json
```

**Comment by mih** [comment]
Thanks @yarikoptic 

If you like that, you might want to keep in mind that you can also say `datalad diff -r --report-untracked all` which will then also go and figure out what untracked content is responsible for making a dataset subtree dirty. I found that quite handy when the tree is large and you already forgot how exactly you created the mess.

**Comment by yarikoptic** [comment]
lovely. it even almost worked for me  without crashing :-)
```shell
$> time git status
On branch master
Your branch is up-to-date with 'datalad-public/master'.

Changes not staged for commit:
  (use "git add <file>..." to update what will be committed)
  (use "git checkout -- <file>..." to discard changes in working directory)
  (commit or discard the untracked or modified content in submodules)

        modified:   kaggle (untracked content)
        modified:   labs (modified content)

Untracked files:
  (use "git add <file>..." to include in what will be committed)

        abide/
        hbn/
        princeton-dataspace/

no changes added to commit (use "git add" and/or "git commit -a")
git status  2.65s user 5.20s system 151% cpu 5.178 total
(dev)2 10764.....................................:Thu 14 Sep 2017 06:17:08 PM EDT:.
(git)smaug:/mnt/btrfs/datasets/datalad/crawl[master]
$> time datalad diff -r --report-untracked all
   modified(dataset): kaggle
   modified(dataset): labs
untracked(directory): abide
untracked(directory): hbn
untracked(directory): princeton-dataspace
untracked(directory): kaggle/passenger-screening-algorithm-challenge
   modified(dataset): labs/gobbini
   modified(dataset): labs/gobbini/famface
   modified(dataset): labs/gobbini/famface/data
         added(file): labs/gobbini/famface/data/.datalad/.gitattributes
         added(file): labs/gobbini/famface/data/.datalad/config
         added(file): labs/gobbini/famface/data/.gitmodules
      added(dataset): labs/gobbini/famface/data/scripts/mridefacer
Failed to run ['git', '--work-tree=.', 'diff', '--raw', '-z', '--ignore-submodules=none', '--abbrev=40', '4b825dc642cb6eb9a060e54bf8d69288fbee4904..0a41fe47681f15e254be89185d027d8ef6a69109', '--'] under '/mnt/btrfs/datasets/datalad/crawl/labs/gobbini/famface/data/scripts/mridefacer'. Exit code=128. out= err=fatal: Invalid revision range 4b825dc642cb6eb9a060e54bf8d69288fbee4904
fatal: Invalid revision range 4b825dc642cb6eb9a060e54bf8d69288fbee4904
datalad diff -r --report-untracked all  12.01s user 11.79s system 113% cpu 21.025 total
```
it smells like something I recently reported and may be even fixed somewhere.. but I guess it was a different one
