### ISSUE TITLE
test_failed_install  fails for me locally

### ISSUE THREAD

**Issue by yarikoptic** [datalad/datalad#1836]
```shell
$> WRAPT_DISABLE_EXTENSIONS=1 DATALAD_TESTS_SSH=1 python -m nose -s -v datalad/distribution/tests/test_{clone.py:test_clone_simple_local,install.py:test_failed_install}
datalad.distribution.tests.test_clone.test_clone_simple_local ... ok
datalad.distribution.tests.test_install.test_failed_install ... FAIL
Versions: cmd:annex=6.20170815+gitg22da64d0f-1~ndall+1 cmd:git=2.11.0 cmd:system-git=2.14.0 cmd:system-ssh=7.4p1 git=2.1.5 tqdm=4.11.2

======================================================================
FAIL: datalad.distribution.tests.test_install.test_failed_install
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/usr/lib/python2.7/dist-packages/nose/case.py", line 197, in runTest
    self.test(*self.arg)
  File "/home/yoh/proj/datalad/datalad/datalad/tests/utils.py", line 593, in newfunc
    return t(*(arg + (filename,)), **kw)
  File "/home/yoh/proj/datalad/datalad/datalad/distribution/tests/test_install.py", line 581, in test_failed_install
    source="http://nonexistingreallyanything.somewhere/bla")
AssertionError: IncompleteResultsError not raised

----------------------------------------------------------------------
Ran 2 tests in 23.137s

FAILED (failures=1)
WRAPT_DISABLE_EXTENSIONS=1 DATALAD_TESTS_SSH=1 python -m nose -s -v   11.15s user 3.32s system 59% cpu 24.119 total
(dev) 2 12126 ->1.....................................:Wed 13 Sep 2017 11:11:58 PM EDT:.
(git)hopa:~datalad/datalad[master]git
$> git describe
0.8.1-233-ge0aeb449
```

**Comment by mih** [comment]
@yarikoptic Is that still the case? If not, please close this.
