### ISSUE TITLE
wtf crashes: no module mutagen

### ISSUE THREAD

**Issue by yarikoptic** [datalad/datalad#1876]
`enh-metadata` branch
```
(dev) [yoh@rolando test]$ datalad plugin wtf
[WARNING] Metadata query results might be incomplete, initial metadata aggregation was not yet performed in 1 dataset at: ['/mnt/DICOM/test']
[ERROR  ] No module named mutagen [audio.py:<module>:17] (ImportError)
```
```
  File "/home/yoh/datalad/datalad/interface/utils.py", line 382, in generator_func
    result_renderer, result_xfm, _result_filter, **_kwargs):
  File "/home/yoh/datalad/datalad/interface/utils.py", line 449, in _process_results
    for res in results:
  File "/home/yoh/datalad/datalad/metadata/metadata.py", line 995, in __call__
    **res_kwargs):
  File "/home/yoh/datalad/datalad/metadata/metadata.py", line 359, in _query_aggregated_metadata
    cache, merge_mode):
  File "/home/yoh/datalad/datalad/metadata/metadata.py", line 403, in _query_aggregated_metadata_singlepath
    content_meta=False)
  File "/home/yoh/datalad/datalad/metadata/metadata.py", line 582, in _get_metadata
    from . import parsers
  File "/home/yoh/datalad/datalad/metadata/parsers/__init__.py", line 17, in <module>
    from . import audio
  File "/home/yoh/datalad/datalad/metadata/parsers/audio.py", line 17, in <module>
    from mutagen import File as audiofile
```

**Comment by yarikoptic** [comment]
same for exifread
```shell
[WARNING] Metadata query results might be incomplete, initial metadata aggregation was not yet performed in 1 dataset at: ['/mnt/DICOM/test']
Traceback (most recent call last):
  File "/home/yoh/datalad/venvs/dev/bin/datalad", line 8, in <module>
    main()
  File "/home/yoh/datalad/datalad/cmdline/main.py", line 348, in main
    ret = cmdlineargs.func(cmdlineargs)
  File "/home/yoh/datalad/datalad/interface/base.py", line 424, in call_from_parser
    ret = list(ret)
  File "/home/yoh/datalad/datalad/interface/utils.py", line 382, in generator_func
    result_renderer, result_xfm, _result_filter, **_kwargs):
  File "/home/yoh/datalad/datalad/interface/utils.py", line 449, in _process_results
    for res in results:
  File "/home/yoh/datalad/datalad/plugin/__init__.py", line 248, in __call__
    for res in plugin_call(**supported_args):
  File "/home/yoh/datalad/datalad/plugin/wtf.py", line 88, in dlplugin
    result_filter=lambda x: x['action'] == 'metadata')
  File "/home/yoh/datalad/datalad/interface/utils.py", line 437, in eval_func
    return return_func(generator_func)(*args, **kwargs)
  File "/home/yoh/datalad/datalad/interface/utils.py", line 425, in return_func
    results = list(results)
  File "/home/yoh/datalad/datalad/interface/utils.py", line 382, in generator_func
    result_renderer, result_xfm, _result_filter, **_kwargs):
  File "/home/yoh/datalad/datalad/interface/utils.py", line 449, in _process_results
    for res in results:
  File "/home/yoh/datalad/datalad/metadata/metadata.py", line 995, in __call__
    **res_kwargs):
  File "/home/yoh/datalad/datalad/metadata/metadata.py", line 359, in _query_aggregated_metadata
    cache, merge_mode):
  File "/home/yoh/datalad/datalad/metadata/metadata.py", line 403, in _query_aggregated_metadata_singlepath
    content_meta=False)
  File "/home/yoh/datalad/datalad/metadata/metadata.py", line 582, in _get_metadata
    from . import parsers
  File "/home/yoh/datalad/datalad/metadata/parsers/__init__.py", line 18, in <module>
    from . import exif
  File "/home/yoh/datalad/datalad/metadata/parsers/exif.py", line 16, in <module>
    from exifread import process_file
ImportError: No module named exifread
```

**Comment by yarikoptic** [comment]
same for 
```
  File "/home/yoh/datalad/datalad/metadata/metadata.py", line 582, in _get_metadata
    from . import parsers
  File "/home/yoh/datalad/datalad/metadata/parsers/__init__.py", line 19, in <module>
    from . import xmp
  File "/home/yoh/datalad/datalad/metadata/parsers/xmp.py", line 19, in <module>
    from libxmp.utils import file_to_dict
ImportError: No module named libxmp.utils
()
> /home/yoh/datalad/datalad/metadata/parsers/xmp.py(19)<module>()
-> from libxmp.utils import file_to_dict
```
so we should just guard things up better... meanwhile installing that new `metadata-extra` bundle

**Comment by yarikoptic** [comment]
but that one is not complete:
```shell
  File "/home/yoh/datalad/venvs/dev/local/lib/python2.7/site-packages/libxmp/exempi.py", line 60, in _load_exempi
    raise ExempiLoadError('Exempi library not found.')
ExempiLoadError: Exempi library not found.
()
> /home/yoh/datalad/venvs/dev/local/lib/python2.7/site-packages/libxmp/exempi.py(60)_load_exempi()
-> raise ExempiLoadError('Exempi library not found.')
```

**Comment by bpoldrack** [comment]
The last one you guys discussed in #1630 already ;-)

**Comment by yarikoptic** [comment]
ah and that one is anyways some external tool... can't install ATM.  all those imports in the `metadata/parsers/__init__.py`  must be guarded by try/except appropriately...

**Comment by yarikoptic** [comment]
I know -- the point is here wouldn't be enough to catch just ImportError

**Comment by mih** [comment]
I can do that shortly, unless you beat me to it.
