### ISSUE TITLE
test_run fail while testing in master in its one matrix env

### ISSUE THREAD

**Issue by yarikoptic** [datalad/datalad#1882]
#### What is the problem?
see https://travis-ci.org/datalad/datalad/builds/283273882
specific to it
```
$ export _DATALAD_UPSTREAM_GITPYTHON=1
$ export NOSE_OPTS=
```
and it seems that swallows kick back at us there
```
======================================================================

ERROR: datalad.interface.tests.test_run.test_basics

----------------------------------------------------------------------

Traceback (most recent call last):

  File "/home/travis/virtualenv/python2.7.13/lib/python2.7/site-packages/nose/case.py", line 197, in runTest

    self.test(*self.arg)

  File "/home/travis/build/datalad/datalad/datalad/tests/utils.py", line 822, in newfunc

    return func(*args, **kwargs)

  File "/home/travis/build/datalad/datalad/datalad/tests/utils.py", line 593, in newfunc

    return t(*(arg + (filename,)), **kw)

  File "/home/travis/build/datalad/datalad/datalad/tests/utils.py", line 593, in newfunc

    return t(*(arg + (filename,)), **kw)

  File "/home/travis/build/datalad/datalad/datalad/interface/tests/test_run.py", line 62, in test_basics

    ds.run('7i3amhmuch9invalid')

  File "/home/travis/virtualenv/python2.7.13/lib/python2.7/site-packages/wrapt/wrappers.py", line 562, in __call__

    args, kwargs)

  File "/home/travis/build/datalad/datalad/datalad/distribution/dataset.py", line 439, in apply_func

    return f(**kwargs)

  File "/home/travis/virtualenv/python2.7.13/lib/python2.7/site-packages/wrapt/wrappers.py", line 523, in __call__

    args, kwargs)

  File "/home/travis/build/datalad/datalad/datalad/interface/utils.py", line 437, in eval_func

    return return_func(generator_func)(*args, **kwargs)

  File "/home/travis/virtualenv/python2.7.13/lib/python2.7/site-packages/wrapt/wrappers.py", line 523, in __call__

    args, kwargs)

  File "/home/travis/build/datalad/datalad/datalad/interface/utils.py", line 425, in return_func

    results = list(results)

  File "/home/travis/build/datalad/datalad/datalad/interface/utils.py", line 382, in generator_func

    result_renderer, result_xfm, _result_filter, **_kwargs):

  File "/home/travis/build/datalad/datalad/datalad/interface/utils.py", line 449, in _process_results

    for res in results:

  File "/home/travis/build/datalad/datalad/datalad/interface/run.py", line 220, in __call__

    expect_fail=True,

  File "/home/travis/build/datalad/datalad/datalad/cmd.py", line 412, in run

    stdin=stdin)

  File "/opt/python/2.7.13/lib/python2.7/subprocess.py", line 382, in __init__

    errread, errwrite), to_close = self._get_handles(stdin, stdout, stderr)

  File "/opt/python/2.7.13/lib/python2.7/subprocess.py", line 818, in _get_handles

    c2pwrite = stdout.fileno()

AttributeError: StringIO instance has no attribute 'fileno'

======================================================================

ERROR: datalad.interface.tests.test_run.test_rerun

----------------------------------------------------------------------

Traceback (most recent call last):

  File "/home/travis/virtualenv/python2.7.13/lib/python2.7/site-packages/nose/case.py", line 197, in runTest

    self.test(*self.arg)

  File "/home/travis/build/datalad/datalad/datalad/tests/utils.py", line 822, in newfunc

    return func(*args, **kwargs)

  File "/home/travis/build/datalad/datalad/datalad/tests/utils.py", line 593, in newfunc

    return t(*(arg + (filename,)), **kw)

  File "/home/travis/build/datalad/datalad/datalad/tests/utils.py", line 593, in newfunc

    return t(*(arg + (filename,)), **kw)

  File "/home/travis/build/datalad/datalad/datalad/interface/tests/test_run.py", line 100, in test_rerun

    ds.run('echo x$(cat sub/sequence) > sub/sequence')

  File "/home/travis/virtualenv/python2.7.13/lib/python2.7/site-packages/wrapt/wrappers.py", line 562, in __call__

    args, kwargs)

  File "/home/travis/build/datalad/datalad/datalad/distribution/dataset.py", line 439, in apply_func

    return f(**kwargs)

  File "/home/travis/virtualenv/python2.7.13/lib/python2.7/site-packages/wrapt/wrappers.py", line 523, in __call__

    args, kwargs)

  File "/home/travis/build/datalad/datalad/datalad/interface/utils.py", line 437, in eval_func

    return return_func(generator_func)(*args, **kwargs)

  File "/home/travis/virtualenv/python2.7.13/lib/python2.7/site-packages/wrapt/wrappers.py", line 523, in __call__

    args, kwargs)

  File "/home/travis/build/datalad/datalad/datalad/interface/utils.py", line 425, in return_func

    results = list(results)

  File "/home/travis/build/datalad/datalad/datalad/interface/utils.py", line 382, in generator_func

    result_renderer, result_xfm, _result_filter, **_kwargs):

  File "/home/travis/build/datalad/datalad/datalad/interface/utils.py", line 449, in _process_results

    for res in results:

  File "/home/travis/build/datalad/datalad/datalad/interface/run.py", line 220, in __call__

    expect_fail=True,

  File "/home/travis/build/datalad/datalad/datalad/cmd.py", line 412, in run

    stdin=stdin)

  File "/opt/python/2.7.13/lib/python2.7/subprocess.py", line 382, in __init__

    errread, errwrite), to_close = self._get_handles(stdin, stdout, stderr)

  File "/opt/python/2.7.13/lib/python2.7/subprocess.py", line 818, in _get_handles

    c2pwrite = stdout.fileno()

AttributeError: StringIO instance has no attribute 'fileno'
```
may be #1870 would automagically resolve it , we will see

**Comment by bpoldrack** [comment]
I don't think it will resolve that issue, since it only cleared actual datalad code off of `swallow_logs`, not the tests. So we will need to replace `swallow_logs` and `swallow_outputs` entirely, I guess. At least their approach on doing it. We should go for handlers/filters instead as `disable_logger` does now. And for redirecting into a special file, we should use `datalad.log.target` instead.

**Comment by mih** [comment]
This report is outdated and the issue is no a current one.
