### ISSUE TITLE
How to use AutomagicIO within DataLad itself?

### ISSUE THREAD

**Issue by mih** [datalad/datalad#1884]
#### What is the problem?
DataLad might need to obtain file content for its internal processing (think: aggregated metadata). It would be great, if we could use automagicIO internally too, and not having to get()/unlock() things "by hand".

Any pointer on where/how to start with this?

Side-benefit: Creates a "dog-fooding" situation that should make this feature more robust over time.

**Comment by yarikoptic** [comment]
+1
Although bear in mind that it comes potentially with the performance impact if there is lots of files open calls.
https://github.com/datalad/datalad/blob/master/datalad/tests/test_auto.py
Should have all good examples

**Comment by mih** [comment]
Nice! That should have all I need.

**Comment by mih** [comment]
It seems that is not working as intended. Here is my approach: https://github.com/datalad/datalad/pull/1630/commits/a2d60296deab188213f60e7a369d56a7b114c836

This basically wraps the entire read-access of aggregated metadata into the context manager. The big diff is just a redindentation.

Here is the result:

```
% datalad --dbg search manowar --reindex
[INFO   ] Rebuilding search index 
[INFO   ] Scanning for metadata keys 
[INFO   ] Activating DataLad's AutoMagicIO 
Traceback (most recent call last):
  File "/home/mih/hacking/datalad/git/bin/datalad", line 8, in <module>
    main()
  File "/home/mih/hacking/datalad/git/datalad/cmdline/main.py", line 347, in main
    ret = cmdlineargs.func(cmdlineargs)
  File "/home/mih/hacking/datalad/git/datalad/interface/base.py", line 427, in call_from_parser
    ret = list(ret)
  File "/home/mih/hacking/datalad/git/datalad/interface/utils.py", line 382, in generator_func
    result_renderer, result_xfm, _result_filter, **_kwargs):
  File "/home/mih/hacking/datalad/git/datalad/interface/utils.py", line 449, in _process_results
    for res in results:
  File "/home/mih/hacking/datalad/git/datalad/metadata/search.py", line 593, in __call__
    index_dir, ds, force_reindex)
  File "/home/mih/hacking/datalad/git/datalad/metadata/search.py", line 303, in _get_search_index
    schema, definitions, per_ds_defs = _get_search_schema(ds)
  File "/home/mih/hacking/datalad/git/datalad/metadata/search.py", line 175, in _get_search_schema
    recursive=True):
  File "/home/mih/hacking/datalad/git/datalad/metadata/metadata.py", line 375, in _query_aggregated_metadata
    cache, merge_mode):
  File "/home/mih/hacking/datalad/git/datalad/metadata/metadata.py", line 435, in _query_aggregated_metadata_singlepath
    cache=cache['objcache'])
  File "/home/mih/hacking/datalad/git/datalad/metadata/metadata.py", line 235, in _load_json_object
    jsonload(fpath, fixup=True) if lexists(fpath) else {})
  File "/home/mih/hacking/datalad/git/datalad/support/json_py.py", line 88, in load
    with open(fname, 'r', encoding='utf-8') as f:
IOError: [Errno 2] No such file or directory: '/tmp/audioman_clone/.datalad/metadata/objects/3f8/ds-3e9471706ff614e51a940327a25f3'
()
> /home/mih/hacking/datalad/git/datalad/support/json_py.py(88)load()
-> with open(fname, 'r', encoding='utf-8') as f:
(Pdb) open
<built-in function open>
```

It seems the patch had no effect.

Alternatively, I could put the context manager deeper into the load helper function, but I wasn't sure how much this would cost -- I would basically activate/patch for every single file (so potentially many).

Also if we start using this internally the logging behavior must change: it is now taking on warning and info (the latter every single time).

Any ideas @yarikoptic ?

**Comment by yarikoptic** [comment]
Overall I feel that using AutomagicIO for this might be slightly an overkill but hey -- it should have worked.  
Ok, situation is multifold
- for AutomagicIO to work, underlying modules must not have those "open" etc methods pre-imported  in their spaces. So, instead of `from io import open`, use `import io; io.open`
- it had no support for `io` or `lzma`
I have quickly added those two into supported, but fighting some strange lzma.LZMAFile behavior... soon will submit a separate PR against masster, and will push into metadata branch
