### ISSUE TITLE
DICOM metadata aggregation crashes  TypeError: sequence item 0: expected string, Dataset found

### ISSUE THREAD

**Issue by yarikoptic** [datalad/datalad#1891]
#### What is the problem?
```
[INFO   ] Aggregate metadata for dataset /mnt/DICOM/test2/inbox/2016/09/07/unknown
[INFO   ] Attempting to extract DICOM metadata from 1285 files
Traceback (most recent call last):
  File "/home/yoh/datalad/venvs/dev/bin/datalad", line 8, in <module>
    main()
  File "/home/yoh/datalad/datalad/cmdline/main.py", line 354, in main
    ret = cmdlineargs.func(cmdlineargs)
  File "/home/yoh/datalad/datalad/interface/base.py", line 427, in call_from_parser
    ret = list(ret)
  File "/home/yoh/datalad/datalad/interface/utils.py", line 382, in generator_func
    result_renderer, result_xfm, _result_filter, **_kwargs):
  File "/home/yoh/datalad/datalad/interface/utils.py", line 449, in _process_results
    for res in results:
  File "/home/yoh/datalad/datalad/metadata/aggregate.py", line 606, in __call__
    to_save)
  File "/home/yoh/datalad/datalad/metadata/aggregate.py", line 199, in _extract_metadata
    paths=relevant_paths)
  File "/home/yoh/datalad/datalad/metadata/metadata.py", line 681, in _get_metadata
    for i in v) if isinstance(v, (tuple, list)) else v)
TypeError: sequence item 0: expected string, Dataset found
()
> /home/yoh/datalad/datalad/metadata/metadata.py(681)_get_metadata()
-> for i in v) if isinstance(v, (tuple, list)) else v)
(Pdb) l
676             for k, v in cm.items():
677                 # TODO instead of a set, it could be a set with counts
678                 vset = unique_cm.get(k, set())
679                 # prevent nested structures in unique prop list
680                 vset.add(', '.join(str(i) if isinstance(i, (int, float)) else i
681  ->                                for i in v) if isinstance(v, (tuple, list)) else v)
682                 unique_cm[k] = vset
683         if unique_cm:
684             dsmeta['unique_content_properties'] = {
685                 k: sorted(v) if len(v) > 1 else list(v)[0]
686                 for k, v in unique_cm.items()}
(Pdb) p k
'dicom:ReferencedImageSequence'
(Pdb) p v
<Sequence, length 1, at 7F15FA9D5208>
(Pdb) p v[0]
(0008, 1150) Referenced SOP Class UID            UI: MR Image Storage
(0008, 1155) Referenced SOP Instance UID         UI: 1.3.12.2.1107.5.2.43.66112.201609071017043239601831
(Pdb) p type(v[0])
<class 'dicom.dataset.Dataset'>
```

something was not flattened enough?

#### What version of DataLad are you using (run `datalad --version`)? On what operating system (consider running `datalad plugin wtf`)?
0.9.1-244-g85b5c069

**Comment by yarikoptic** [comment]
I think we should just skip those non-scalar fields, right?
