### ISSUE TITLE
OverflowError: 4294968772 is too big to fit in an array

### ISSUE THREAD

**Issue by yarikoptic** [datalad/datalad#1894]
#### What is the problem?

per request -- here is the detail
new (to be 0.10) aggregate-metadata (without switch `DATALAD_METADATA_SEARCHINDEX__DOCUMENTTYPE=datasets `) crashes
```
2017-10-12 08:15:06,720 [INFO   ] Adding information about Dataset 2017/04/26/A000633
Traceback (most recent call last):
  File "/home/yoh/datalad/venvs/dev/bin/datalad", line 8, in <module>
    main()
  File "/home/yoh/datalad/datalad/cmdline/main.py", line 354, in main
    ret = cmdlineargs.func(cmdlineargs)
  File "/home/yoh/datalad/datalad/interface/base.py", line 427, in call_from_parser
    ret = list(ret)
  File "/home/yoh/datalad/datalad/interface/utils.py", line 382, in generator_func
    result_renderer, result_xfm, _result_filter, **_kwargs):
  File "/home/yoh/datalad/datalad/interface/utils.py", line 449, in _process_results
    for res in results:
  File "/home/yoh/datalad/datalad/metadata/search.py", line 435, in __call__
    index_dir, ds, force_reindex)
  File "/home/yoh/datalad/datalad/metadata/search.py", line 300, in _get_search_index
    _add_document(idx, **doc_props)
  File "/home/yoh/datalad/datalad/metadata/search.py", line 67, in _add_document
    for k, v in kwargs.items()})
  File "/home/yoh/datalad/venvs/dev/local/lib/python2.7/site-packages/whoosh/writing.py", line 786, in add_document
    perdocwriter.finish_doc()
  File "/home/yoh/datalad/venvs/dev/local/lib/python2.7/site-packages/whoosh/codec/whoosh3.py", line 250, in finish_doc
    self.add_column_value("_stored", STORED_COLUMN, sf)
  File "/home/yoh/datalad/venvs/dev/local/lib/python2.7/site-packages/whoosh/codec/base.py", line 821, in add_column_value
    self._get_column(fieldname).add(self._docnum, value)
  File "/home/yoh/datalad/venvs/dev/local/lib/python2.7/site-packages/whoosh/columns.py", line 1265, in add
    self._child.add(docnum, v)
  File "/home/yoh/datalad/venvs/dev/local/lib/python2.7/site-packages/whoosh/columns.py", line 855, in add
    VarBytesColumn.Writer.add(self, docnum, v)
  File "/home/yoh/datalad/venvs/dev/local/lib/python2.7/site-packages/whoosh/columns.py", line 276, in add
    self._offsets.append(self._offset_base)
  File "/home/yoh/datalad/venvs/dev/local/lib/python2.7/site-packages/whoosh/util/numlists.py", line 59, in append
    self._retype(n)
  File "/home/yoh/datalad/venvs/dev/local/lib/python2.7/site-packages/whoosh/util/numlists.py", line 48, in _retype
    raise OverflowError("%r is too big to fit in an array" % maxnum)
OverflowError: 4294968772 is too big to fit in an array
()
> /home/yoh/datalad/venvs/dev/local/lib/python2.7/site-packages/whoosh/util/numlists.py(48)_retype()
-> raise OverflowError("%r is too big to fit in an array" % maxnum)
```

**Comment by mih** [comment]
I think we can close this now -- so much stuff has changed.
