### ISSUE TITLE
search fails expecting a set where dict is provided

### ISSUE THREAD

**Issue by yarikoptic** [datalad/datalad#1903]
#### What is the problem?
```
(git)smaug:/mnt/btrfs/scrap/datalad/tmp/datasets[master]git
$> datalad --dbg search *nwb*
[INFO   ] Rebuilding search index 
[INFO   ] Scanning for metadata keys 
Traceback (most recent call last):
  File "/home/yoh/proj/datalad/datalad/venvs/dev/bin/datalad", line 8, in <module>
    main()
  File "/home/yoh/proj/datalad/datalad/datalad/cmdline/main.py", line 347, in main
    ret = cmdlineargs.func(cmdlineargs)
  File "/home/yoh/proj/datalad/datalad/datalad/interface/base.py", line 427, in call_from_parser
    ret = list(ret)
  File "/home/yoh/proj/datalad/datalad/datalad/interface/utils.py", line 382, in generator_func
    result_renderer, result_xfm, _result_filter, **_kwargs):
  File "/home/yoh/proj/datalad/datalad/datalad/interface/utils.py", line 449, in _process_results
    for res in results:
  File "/home/yoh/proj/datalad/datalad/datalad/metadata/search.py", line 571, in __call__
    index_dir, ds, force_reindex)
  File "/home/yoh/proj/datalad/datalad/datalad/metadata/search.py", line 290, in _get_search_index
    schema, definitions, per_ds_defs = _get_search_schema(ds)
  File "/home/yoh/proj/datalad/datalad/datalad/metadata/search.py", line 184, in _get_search_schema
    set.add(', '.join(i for i in v) if isinstance(v, (tuple, list)) else v)
TypeError: descriptor 'add' requires a 'set' object but received a 'dict'
()
> /home/yoh/proj/datalad/datalad/datalad/metadata/search.py(184)_get_search_schema()
-> set.add(', '.join(i for i in v) if isinstance(v, (tuple, list)) else v)
(Pdb) p v
{u'@id': u'pato:0000011', u'description': u'age of a sample (organism) at the time of data acquisition in years', u'unit': u'uo:0000036'}
(Pdb) p k
u'dlp_bids:age(years)'
```

**Comment by yarikoptic** [comment]
more context
```
*(Pdb) p list(v)
[u'@id', u'description', u'unit']
(Pdb) p res
{'status': 'ok', 'dsid': u'6eeadb86-84be-11e6-b24c-002590f97d84', 'refcommit': u'd2d15b8150c7767759001ae1ae2e0582ace146cd', 'path': u'/mnt/btrfs/scrap/datalad/tmp/datasets/labs/haxby/raiders', 'type': 'dataset', 'metadata': {u'conformsto': u'http://bids.neuroimaging.io', u'fundedby': u'Funding was provided by National Institutes of Mental Health grant 5R01MH075706 (Haxby), and by a graduate fellowship from the Neukom Institute for Computational Sciences at Dartmouth (Guntupalli).', u'license': u'PDDL', u'author': [u'J. Swaroop Guntupalli', u'Yaroslav O. Halchenko', u'James V. Haxby'], u'unique_content_properties': {u'dcterms_format': [u'image/nifti', u'image/parrec'], u'distribution-restrictions': [u'proprietary', u'sensitive']}, u'citation': u'doi:10.1016/j.neuron.2011.08.026', u'@context': {u'@vocab': u'http://docs.datalad.org/schema_v2.0.json', u'dlp_bids:age(years)': {u'@id': u'pato:0000011', u'description': u'age of a sample (organism) at the time of data acquisition in years', u'unit': u'uo:0000036'}, u'dlp_bids:female': {u'@id': u'pato:0000383', u'description': u'A biological sex quality inhering in an individual or a population that only produces gametes that can be fertilised by male gametes'}, u'dlp_bids:male': {u'@id': u'pato:0000384', u'description': u'A biological sex quality inhering in an individual or a population whose sex organs contain only male gametes'}, u'dlp_bids': {u'type': u'http://purl.org/dc/dcam/VocabularyEncodingScheme', u'descr': u'Vocabulary of the DataLad BIDS metadata parser', u'def': u'TODO'}, u'dlp_bids:sex': {u'@id': u'pato:0000047', u'description': u'biological sex'}}, u'@id': u'6eeadb86-84be-11e6-b24c-002590f97d84', u'name': u'Dartmouth Raiders Dataset'}}
(Pdb) p definitions[k]
{'unit (http://purl.obolibrary.org/obo/UO_0000000)': u'http://purl.obolibrary.org/obo/UO_0000036', u'@id': u'http://purl.obolibrary.org/obo/PATO_0000011', 'description (http://schema.org/description)': None}
(Pdb) p v
{u'@id': u'pato:0000011', u'description': u'age of a sample (organism) at the time of data acquisition in years', u'unit': u'uo:0000036'}
(Pdb) p definitions
{u'dlp_bids': {u'type': u'http://purl.org/dc/dcam/VocabularyEncodingScheme', u'descr': u'Vocabulary of the DataLad BIDS metadata parser', u'def': u'TODO'}, u'contributors': u'http://schema.org/contributor', u'citation': u'http://schema.org/citation', u'tag': u'http://schema.org/keywords', 'parentds': 'path of the datasets that contains an entity', '@vocab': u'http://docs.datalad.org/schema_v2.0.json', u'author': u'http://schema.org/author', u'comment<group>': 'http://purl.obolibrary.org/obo/NCIT_C25393', u'version': u'http://usefulinc.com/ns/doap#Version', u'comment<participant_id>': 'http://purl.obolibrary.org/obo/NCIT_C25393', u'homepage': u'http://usefulinc.com/ns/doap#homepage', u'dlp_bids:sex': {u'@id': u'http://purl.obolibrary.org/obo/PATO_0000047', 'description (http://schema.org/description)': None}, u'description': u'http://schema.org/description', u'dlp_bids:age(years)': {'unit (http://purl.obolibrary.org/obo/UO_0000000)': u'http://purl.obolibrary.org/obo/UO_0000036', u'@id': u'http://purl.obolibrary.org/obo/PATO_0000011', 'description (http://schema.org/description)': None}, u'dlp_bids:male': {u'@id': u'pato:0000384', u'description': u'A biological sex quality inhering in an individual or a population whose sex organs contain only male gametes'}, 'path': 'path name of an entity relative to the searched base dataset', '@id': 'unique identifier of an entity', u'conformsto': u'http://purl.org/dc/terms/conformsTo', u'name': u'http://schema.org/name', u'license': 'http://www.w3.org/1999/xhtml/vocab#license', u'sameas': u'http://schema.org/sameAs', 'type': {'@id': u'http://purl.org/dc/terms/type', 'description': 'type or category of a resource (e.g. file, dataset)'}, u'dlp_bids:female': {u'@id': u'pato:0000383', u'description': u'A biological sex quality inhering in an individual or a population that only produces gametes that can be fertilised by male gametes'}, u'shortdescription': u'http://usefulinc.com/ns/doap#shortdesc'}
```
but overall it just seems an incorrect statement -- something was intended to be added somewhere but it was just a call to 'set.add' which indeed should have got the first argument to be a set... I guess this line is not even smoke tested

**Comment by yarikoptic** [comment]
something not yet quite right since breeds keys
```
dlp_bids:age(years)_62 {'@id': 'pato:0000011', 'description': 'age of a sample (organism) at the time of data acquisition in years', 'unit': 'uo:0000036'}
dlp_bids:age(years)_63 {'@id': 'pato:0000011', 'description': 'age of a sample (organism) at the time of data acquisition in years', 'unit': 'uo:0000036'}
dlp_bids:age(years)_64 {'@id': 'pato:0000011', 'description': 'age of a sample (organism) at the time of data acquisition in years', 'unit': 'uo:0000036'}
dlp_bids:age(years)_65 {'@id': 'pato:0000011', 'description': 'age of a sample (organism) at the time of data acquisition in years', 'unit': 'uo:0000036'}
dlp_bids:age(years)_66 {'@id': 'pato:0000011', 'description': 'age of a sample (organism) at the time of data acquisition in years', 'unit': 'uo:0000036'}
```

**Comment by yarikoptic** [comment]
and I think I will sanitize away `/` as well for now since I do not think we have a power to fix them up while saving index:
```
IOError: [Errno 2] No such file or directory: u'/mnt/btrfs/scrap/datalad/tmp/datasets/.git/datalad/search_index/MAIN_964q9p1i5lzurph0._comment<dospert_rt-hlth/saf>_len.col'
()
> /usr/lib/python2.7/dist-packages/whoosh/filedb/filestore.py(490)create_file()
-> fileobj = open(path, mode)
(Pdb) up
> /usr/lib/python2.7/dist-packages/whoosh/filedb/compound.py(298)save_as_files()
-> f = storage.create_file(name_fn(name))
(Pdb) p name
u'_comment<dospert_rt-hlth/saf>_len'
(Pdb) p name_fn
<bound method W3PerDocWriter._column_filename of <whoosh.codec.whoosh3.W3PerDocWriter object at 0x7fcf3e482190>>
```

**Comment by mih** [comment]
This fix is in master already.
