### ISSUE TITLE
test_nifti1.test_nifti on buildbots: Failed to get dataset metadata (nifti1): 'int' object has no attribute 'item' 

### ISSUE THREAD

**Issue by yarikoptic** [datalad/datalad#1977]
now that buildbots seems to be ok, and everyone knows how to knock to get access to the buildbot logs:
```
======================================================================
ERROR: datalad.metadata.parsers.tests.test_nifti1.test_nifti
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/usr/lib/python2.7/dist-packages/nose/case.py", line 197, in runTest
    self.test(*self.arg)
  File "/home/buildbot/datalad-tests-docker-dl-nd16_04/build/datalad/tests/utils.py", line 594, in newfunc
    return t(*(arg + (filename,)), **kw)
  File "/home/buildbot/datalad-tests-docker-dl-nd16_04/build/datalad/metadata/parsers/tests/test_nifti1.py", line 36, in test_nifti
    res = ds.aggregate_metadata()
  File "/home/buildbot/datalad-tests-docker-dl-nd16_04/build/venv-ci/local/lib/python2.7/site-packages/wrapt/wrappers.py", line 562, in __call__
    args, kwargs)
  File "/home/buildbot/datalad-tests-docker-dl-nd16_04/build/datalad/distribution/dataset.py", line 437, in apply_func
    return f(**kwargs)
  File "/home/buildbot/datalad-tests-docker-dl-nd16_04/build/venv-ci/local/lib/python2.7/site-packages/wrapt/wrappers.py", line 523, in __call__
    args, kwargs)
  File "/home/buildbot/datalad-tests-docker-dl-nd16_04/build/datalad/interface/utils.py", line 437, in eval_func
    return return_func(generator_func)(*args, **kwargs)
  File "/home/buildbot/datalad-tests-docker-dl-nd16_04/build/venv-ci/local/lib/python2.7/site-packages/wrapt/wrappers.py", line 523, in __call__
    args, kwargs)
  File "/home/buildbot/datalad-tests-docker-dl-nd16_04/build/datalad/interface/utils.py", line 425, in return_func
    results = list(results)
  File "/home/buildbot/datalad-tests-docker-dl-nd16_04/build/datalad/interface/utils.py", line 413, in generator_func
    msg="Command did not complete successfully")
IncompleteResultsError: Command did not complete successfully [{'action': 'aggregate_metadata', 'path': '/tmp/datalad_temp_test_nifti0qLhjn', 'status': 'error', 'message': 'Metadata extraction failed (see previous error message)'}]
-------------------- >> begin captured logging << --------------------
datalad.distribution.create: INFO: Creating a new annex repo at /tmp/datalad_temp_test_nifti0qLhjn
datalad.metadata.aggregate: INFO: Aggregate metadata for dataset /tmp/datalad_temp_test_nifti0qLhjn
datalad.metadata.metadata: ERROR: Failed to get dataset metadata (nifti1): 'int' object has no attribute 'item' [type_check.py:asscalar:453]
datalad.metadata.aggregate: ERROR: Metadata extraction failed (see previous error message) [aggregate_metadata(/tmp/datalad_temp_test_nifti0qLhjn)]
datalad.metadata.aggregate: INFO: Update aggregate metadata in dataset at: /tmp/datalad_temp_test_nifti0qLhjn
datalad.metadata.aggregate: INFO: Attempting to save 6 files/datasets
--------------------- >> end captured logging << ---------------------
```

**Comment by yarikoptic** [comment]
ok -- it is an interplay of two issues:
1. nibabel 2.1.0 returns None for slice_code (I guess if not defined):
```
$> python -c "import nibabel as nib; sc=nib.load('./datalad/metadata/tests/data/nifti1.nii.gz').header.get('slice_code'); print(type(sc), sc, nib.__version__)"
(<type 'NoneType'>, None, '2.1.0')

$> python -c "import nibabel as nib; sc=nib.load('./datalad/metadata/tests/data/nifti1.nii.gz').header.get('slice_code'); print(type(sc), sc, nib.__version__)"
(<type 'numpy.ndarray'>, array(0, dtype=uint8), '2.2.0')

```
2. `np.asscalar` doesn't tollerate scalars (bleh):
```
$> python -c 'import numpy as np; print np.asscalar(0)'
Traceback (most recent call last):         
  File "<string>", line 1, in <module>
  File "/usr/lib/python2.7/dist-packages/numpy/lib/type_check.py", line 480, in asscalar
    return a.item()
AttributeError: 'int' object has no attribute 'item'
```
so I will alter the default value to be a `np.array(0)`
