### ISSUE TITLE
sshconnector always tries to do something right upon import

### ISSUE THREAD

**Issue by yarikoptic** [datalad/datalad#2009]
#### What is the problem?
as recently "improved" travis setup, which now runs wtf upon completion shows after 'sudo'ed run of tests:  https://travis-ci.org/datalad/datalad/jobs/309577052
```shell
$ datalad plugin wtf
Traceback (most recent call last):
  File "/home/travis/virtualenv/python2.7.13/bin/datalad", line 7, in <module>
    from datalad.cmdline.main import main
  File "/home/travis/build/datalad/datalad/datalad/__init__.py", line 34, in <module>
    ssh_manager = SSHManager()
  File "/home/travis/build/datalad/datalad/datalad/support/sshconnector.py", line 359, in __init__
    for p in listdir(self.socket_dir)
  File "/home/travis/build/datalad/datalad/datalad/support/sshconnector.py", line 374, in socket_dir
    chmod(self._socket_dir, 0o700)
OSError: [Errno 1] Operation not permitted: '/home/travis/.cache/datalad/sockets'
```
SSHManager, even upon import already is doing some house keeping stuff. Since many, if not majority of datalad commands do not need ssh for their operation, it would be nice if SSHManager delayed any of those actions all the way until it actually needs to do something.

**Comment by yarikoptic** [comment]
I do not think this is longer the case, at least not at the mere import, and even 'wtf' does not crash if there is no permissions, so I will close
