### ISSUE TITLE
search '*a*' never completes

### ISSUE THREAD

**Issue by yarikoptic** [datalad/datalad#2052]
#### What is the problem?
Seems to relate to have metadata explicitly aggregated, gets stuck with the last message being `[INFO   ] Search index contains 134 documents` at any debug level:
```shell
hopa:/tmp
$> datalad install ///openfmri/ds000001
[INFO   ] Cloning http://datasets.datalad.org/openfmri/ds000001 to '/tmp/ds000001' 
[INFO   ] access to dataset sibling "datalad" not auto-enabled, enable with:
| 		datalad siblings -d "/tmp/ds000001" enable -s datalad 
install(ok): /tmp/ds000001 (dataset)
(dev) 2 14554 [1].....................................:Thu 21 Dec 2017 10:47:47 AM EST:.
hopa:/tmp
$> cd ds000001            
CHANGES                   sub-01/  sub-05/  sub-09/  sub-13/  task-balloonanalogrisktask_bold.json
README                    sub-02/  sub-06/  sub-10/  sub-14/
dataset_description.json  sub-03/  sub-07/  sub-11/  sub-15/
participants.tsv          sub-04/  sub-08/  sub-12/  sub-16/
(dev) 2 14555 [1].....................................:Thu 21 Dec 2017 10:47:52 AM EST:.
(git-annex)hopa:/tmp/ds000001[master]
$> datalad search '*a*' 
[INFO   ] Building search index 
[INFO   ] Scanning for metadata keys 
[INFO   ] Added 134 documents on dataset . 
[INFO   ] Search index contains 134 documents 
[INFO   ] Query completed in 0.0362000465393 sec. Reporting up to 20 top matches. 
search(ok): .
search(ok): sub-09/func/sub-09_task-balloonanalogrisktask_run-01_bold.nii.gz
search(ok): sub-08/func/sub-08_task-balloonanalogrisktask_run-02_events.tsv
search(ok): sub-07/func/sub-07_task-balloonanalogrisktask_run-03_bold.nii.gz
search(ok): sub-16/func/sub-16_task-balloonanalogrisktask_run-01_bold.nii.gz
search(ok): sub-16/func/sub-16_task-balloonanalogrisktask_run-03_bold.nii.gz
search(ok): sub-12/func/sub-12_task-balloonanalogrisktask_run-02_bold.nii.gz
search(ok): sub-11/anat/sub-11_T1w.nii.gz
search(ok): sub-10/func/sub-10_task-balloonanalogrisktask_run-03_events.tsv
search(ok): sub-15/func/sub-15_task-balloonanalogrisktask_run-01_events.tsv
search(ok): sub-02/func/sub-02_task-balloonanalogrisktask_run-02_events.tsv
search(ok): sub-15/func/sub-15_task-balloonanalogrisktask_run-02_bold.nii.gz
search(ok): sub-05/func/sub-05_task-balloonanalogrisktask_run-01_bold.nii.gz
search(ok): sub-09/func/sub-09_task-balloonanalogrisktask_run-03_bold.nii.gz
search(ok): sub-05/func/sub-05_task-balloonanalogrisktask_run-02_bold.nii.gz
search(ok): sub-06/func/sub-06_task-balloonanalogrisktask_run-03_bold.nii.gz
search(ok): sub-03/func/sub-03_task-balloonanalogrisktask_run-01_events.tsv
search(ok): sub-10/func/sub-10_task-balloonanalogrisktask_run-02_events.tsv
search(ok): sub-12/anat/sub-12_T1w.nii.gz
search(ok): sub-08/func/sub-08_task-balloonanalogrisktask_run-01_bold.nii.gz
[INFO   ] Reached the limit of 20 top matches, there could be more which were not reported. 
action summary:
  search (ok: 20)
(dev) 2 14556 [1].....................................:Thu 21 Dec 2017 10:48:00 AM EST:.
(git-annex)hopa:/tmp/ds000001[master]
$> datalad aggregate-metadata -r
[INFO   ] Aggregate metadata for dataset /tmp/ds000001 
[INFO   ] Update aggregate metadata in dataset at: /tmp/ds000001 
aggregate_metadata(ok): /tmp/ds000001 (dataset)                                                                 
[INFO   ] Attempting to save 6 files/datasets 
save(ok): /tmp/ds000001 (dataset)
action summary:
  aggregate_metadata (ok: 1)
  save (ok: 1)
(dev) 2 14557 [1].....................................:Thu 21 Dec 2017 10:48:06 AM EST:.
(git-annex)hopa:/tmp/ds000001[master]
$> datalad search '*a*'         
[INFO   ] Rebuilding search index 
[INFO   ] Scanning for metadata keys 
[INFO   ] Added 134 documents on dataset . 
[INFO   ] Search index contains 134 documents 

```
datalad as of #2050 0.9.1-527-g55b45529

I think AutomagicIO is not involved in this one:
```shell
$> datalad -l 2 search '*a*'
[DEBUG  ] Determined class of decorated function: <class 'datalad.metadata.search.Search'> 
[Level 5] Parsed ri /tmp/ds000001 into fields {'username': '', 'scheme': '', 'fragment': '', 'hostname': '', 'query': '', 'path': '/tmp/ds000001', 'password': '', 'port': ''} 
[Level 5] Detected file ri 
[DEBUG  ] Resolved dataset for dataset search: <Dataset path=/tmp/ds000001> 
[Level 5] Detected <class 'datalad.support.annexrepo.AnnexRepo'> at /tmp/ds000001 
[Level 5] Parsed ri /tmp/ds000001 into fields {'username': '', 'scheme': '', 'fragment': '', 'hostname': '', 'query': '', 'path': '/tmp/ds000001', 'password': '', 'port': ''} 
[Level 5] Detected file ri 
[Level 9] Running: ['git', 'annex', 'version', '--raw'] 
[Level 8] Finished running ['git', 'annex', 'version', '--raw'] with status 0 
[Level 9] Running: ['git', 'version'] 
[Level 8] Finished running ['git', 'version'] with status 0 
[Level 9] Running: ['git', 'config', '-z', '-l', '--show-origin'] 
[Level 8] Finished running ['git', 'config', '-z', '-l', '--show-origin'] with status 0 
[Level 5] Found 0 previous connections 
[Level 9] Running: ['git', 'config', 'user.name'] 
[Level 8] Finished running ['git', 'config', 'user.name'] with status 0 
[Level 9] Running: ['git', 'config', 'user.email'] 
[Level 8] Finished running ['git', 'config', 'user.email'] with status 0 
[Level 9] Running: ['git', 'version'] 
[Level 8] Finished running ['git', 'version'] with status 0 
[Level 9] Running: ['git', 'config', '-z', '-l', '--show-origin', '--file', '/tmp/ds000001/.datalad/config'] 
[Level 8] Finished running ['git', 'config', '-z', '-l', '--show-origin', '--file', '/tmp/ds000001/.datalad/config'] with status 0 
[Level 9] Running: ['git', 'config', '-z', '-l', '--show-origin'] 
[Level 8] Finished running ['git', 'config', '-z', '-l', '--show-origin'] with status 0 
[Level 5] Parsed ri http://datasets.datalad.org/openfmri/ds000001/.git into fields {'username': '', 'scheme': 'http', 'fragment': '', 'hostname': 'datasets.datalad.org', 'query': '', 'path': '/openfmri/ds000001/.git', 'password': '', 'port': ''} 
[Level 5] Detected url ri 
[Level 5] Detected <class 'datalad.support.annexrepo.AnnexRepo'> at /tmp/ds000001 
[Level 5] Parsed ri /tmp/ds000001 into fields {'username': '', 'scheme': '', 'fragment': '', 'hostname': '', 'query': '', 'path': '/tmp/ds000001', 'password': '', 'port': ''} 
[Level 5] Detected file ri 
[Level 5] Detected <class 'datalad.support.annexrepo.AnnexRepo'> at /tmp/ds000001 
[Level 5] Parsed ri /tmp/ds000001 into fields {'username': '', 'scheme': '', 'fragment': '', 'hostname': '', 'query': '', 'path': '/tmp/ds000001', 'password': '', 'port': ''} 
[Level 5] Detected file ri 
[Level 5] Detected <class 'datalad.support.annexrepo.AnnexRepo'> at /tmp/ds000001 
[Level 5] Parsed ri /tmp/ds000001 into fields {'username': '', 'scheme': '', 'fragment': '', 'hostname': '', 'query': '', 'path': '/tmp/ds000001', 'password': '', 'port': ''} 
[Level 5] Detected file ri 
[Level 9] Running: ['git', '-c', 'receive.autogc=0', '-c', 'gc.auto=0', 'log', '-n', '1', '--pretty=format:%H', '--', '.datalad/metadata/aggregate_v1.json'] 
[Level 8] Finished running ['git', '-c', 'receive.autogc=0', '-c', 'gc.auto=0', 'log', '-n', '1', '--pretty=format:%H', '--', '.datalad/metadata/aggregate_v1.json'] with status 0 
[DEBUG  ] Search index contains 134 documents 
```
whoosh bug?

**Comment by yarikoptic** [comment]
oh right - since authors asked for the output of wtf:
```
. (dataset): author,citation,comment<BIDSVersion>,conformsto,description,license,name,unique_content_properties
System
======
OS          : posix Linux 4.13.0-1-amd64 #1 SMP Debian 4.13.10-1 (2017-10-30)
Distribution: debian/buster/sid

Environment
===========
GIT_PYTHON_GIT_EXECUTABLE: /usr/lib/git-annex.linux/git
GIT_PAGER: less --no-init --quit-if-one-screen

Externals
=========
appdirs=1.4.3
boto=2.44.0
cmd:annex=6.20171211+gitgba511f4de-1~ndall+1
cmd:git=2.11.0
cmd:system-git=2.15.0
cmd:system-ssh=7.6p1
git=2.1.8
gitdb=2.0.2
humanize=0.5.1
iso8601=0.1.11
msgpack=0.4.8
requests=2.18.1
scrapy=1.4.0
six=1.11.0
tqdm=4.11.2
wrapt=1.9.0

Available metadata parsers
==========================
audio
base
bids
datacite
datalad_core
datalad_rfc822
dicom
exif
frictionless_datapackage
image
nifti1
xmp

Configuration
=============
alias.bc: branch --contains
alias.br: branch
alias.bra: branch -a
alias.cam: commit -a -m
alias.cc: !cat `pwd`/.git/config
alias.changes: diff --name-status -r
alias.ci: commit -a
alias.cm: commit -m
alias.co: checkout
alias.d: diff
alias.dc: diff --cached
alias.debug: !GIT_PAGER= gdb --args git
alias.diffc: diff --cached
alias.diffstat: diff --stat -r
alias.ec: config --edit
alias.egc: config --edit --global
alias.fa: !git remote | xargs -r -I REMOTE /bin/bash -c 'echo I: Fetching from REMOTE && git fetch --prune REMOTE && git fetch -t REMOTE' && [ -d .git/svn ] && bash -c 'echo I: Fetching from SVN && git svn fetch' || : && [ -e .gitmodules ] && bash -c 'echo I: Fetching submodules && git submodule foreach git fa' && [ -d .git/sd ] && bash -c 'echo I: Fetching bugs into sd && git-sd pull --all' || :
alias.ff: merge --ff-only
alias.kompare: difftool -x kompare --no-prompt
alias.lc: log ORIG_HEAD.. --stat --no-merges
alias.lg: log --graph --pretty=format:'%Cred%h%Creset -%C(yellow)%d%Creset %s %Cgreen(%cr) %C(bold blue)[%an]%Creset' --abbrev-commit --date=relative
alias.lgl: !bash -c 'git log --first-parent --pretty=oneline | while read l; do p=${l%% *}; gd=$(git describe $p 2>/dev/null); printf "%8s %-40s %20s " "${l:0:8}" "${l:40:40}" "$gd"; git diff --stat $p^..$p 2>/dev/null | grep --color=never "files* ch" || echo ; done'
alias.lgr: ! git log --graph --pretty=format:'%Cred%H%Creset -%C(yellow)%d%Creset %s %Cgreen(%cr) %C(bold blue)[%an]%Creset' --abbrev-commit --date=relative | while read -r l; do sha=$(echo "$l" | perl -ne 'print if s|^.*?([0-9a-f]{40}).*?$|\1|' ); [ -z "$sha" ] && echo $l || { d=$(git describe --contains $sha 2>/dev/null || git describe $sha 2>/dev/null); echo "$l" | sed -e "s,$sha,$d,g"; } ; done 
alias.lof: !sh -c 'git log --format=oneline --decorate=full $@ | git name-rev --stdin --name-only'
alias.lol: log --oneline --decorate
alias.lp: log -p
alias.ls: log --stat
alias.meld: difftool -x meld --no-prompt
alias.mff: merge --ff-only
alias.mffom: merge --ff-only origin/master
alias.mtheirs: !sh -c 'git merge -s ours --no-commit $1 && git read-tree -m -u $1' -
alias.nbdiff: difftool -x nbdiff --no-prompt
alias.niidiff: difftool -x niidiff --no-prompt
alias.p: !git push $@ && zsh -c "source ~/.zsh/func/giturl $1"
alias.pa: !git paremotes | tr ' ' '\n'  | xargs -r -l1 git push
alias.padry: !git paremotes | tr ' ' '\n' | xargs -r -l1 git push --dry-run
alias.paremotes: !git config remotes.push | grep '.' || echo origin
alias.pcb: !git push gh-yarikoptic `git rev-parse --abbrev-ref HEAD`
alias.pdfdiff: difftool -x diffpdf --no-prompt
alias.pdiff: diff 'HEAD@{1}'
alias.pdry: push --dry-run
alias.pff: pull --ff-only
alias.praise: blame
alias.pt: !git testremotes | tr ' ' '\n'  | xargs -r -l1 -I R git push -f R master
alias.ptdry: !git testremotes | tr ' ' '\n'  | xargs -r -l1 -I R git push -f --dry-run R master
alias.pu: !sh -c 'git push $0 $1 && $HOME/.zsh/func/giturl $0'
alias.re: repack -a -d -f --window=100
alias.root: !pwd
alias.slog: log --oneline --topo-order --graph
alias.st: status
alias.sts: !git status  | sed -n -e '/^[^a-zA-Z]\t[^ ]/,$p'
alias.stt: status --untracked=no
alias.tc: describe --tags --contains
alias.testremotes: !git config remotes.test | grep '.' || echo origin
alias.uncommit: !zsh -c 'if (($0))
alias.wdiff: diff --color-words
alias.whatis: show -s --pretty='tformat:%h (%s, %ad)' --date=short
alias.whois: !sh -c 'git log -i -1 --pretty="format:%an <%ae>\n" --author="$1"' -
annex.uuid: 725cbe32-3316-45d9-aba9-d3e199cf7a11
annex.version: 5
branch.master.merge: refs/heads/master
branch.master.remote: origin
color.branch: auto
color.diff: auto
color.grep: auto
color.pager: true
color.status: auto
color.ui: auto
core.bare: false
core.excludesfile: /home/yoh/.git.d/excludes
core.filemode: true
core.logallrefupdates: true
core.repositoryformatversion: 0
core.whitespace: error,-indent-with-non-tab,trailing-space
credential.helper: cache --timeout=7200
datalad.dataset.id: 233cc486-7d0e-11e6-855b-002590f97d84
difftool.nbdiff.cmd: nbdiff
difftool.niidiff.cmd: niidiff
dpm.pristinetarcommit: true
giggle.file-view-vpane-position: 518
giggle.history-view-vpane-position: 300
giggle.main-window-geometry: 1440x900+0+0
giggle.main-window-maximized: false
giggle.main-window-view: FileView
github.user: <HIDDEN>
merge.log: true
merge.summary: true
mergetool.nbmerge.cmd: nbmerge $LOCAL $BASE $REMOTE $MERGED
metadata.nativetype: bids
remote.datalad-archives.annex-availability: LocallyAvailable
remote.datalad-archives.annex-cost: 500.0
remote.datalad-archives.annex-externaltype: datalad-archives
remote.datalad-archives.annex-uuid: 899f0347-0888-48ef-91b6-bac213ca8cef
remote.origin.annex-bare: false
remote.origin.annex-uuid: f4cc85b8-e252-4c4d-9c35-6dc64ce87317
remote.origin.fetch: +refs/heads/*:refs/remotes/origin/*
remote.origin.url: http://datasets.datalad.org/openfmri/ds000001/.git
url.anonscm.debian.org:.pushinsteadof: ('git://anonscm.debian.org/', 'http://anonscm.debian.org')
url.git+ssh://git.debian.org/git/.insteadof: alioth:
url.git+ssh://yarikoptic@repo.or.cz/srv/git/.pushinsteadof: http://repo.or.cz/r/
url.git://git.madduck.net/madduck/.insteadof: madduck:
url.git://git.onerussian.com/.insteadof: 1r:
url.git://github.com/.insteadof: gh:
url.git://github.com/nipy/.insteadof: nipy:
url.git@github.com:.pushinsteadof: ('https://github.com/', 'git://github.com/')
url.git@gitorious.org:.pushinsteadof: git://gitorious.org/
url.http://datagit.org/.insteadof: dg:
url.smaug.datalad.org:/mnt/datasets/datalad/crawl/.insteadof: smaug-datasets:
url.ssh://git.debian.org/git/.pushinsteadof: ('git://git.debian.org', 'https://anonscm.debian.org/git/')
url.ssh://git.onerussian.com/~/git/pub/.pushinsteadof: http://git.onerussian.com/pub/
user.affiliation: <HIDDEN>
user.email: <HIDDEN>
user.name: <HIDDEN>
user.name2: <HIDDEN>
user.orcid: <HIDDEN>
user.signingkey: <HIDDEN>
user.xdg-and-user: <HIDDEN>

Dataset information
===================
path: /tmp/ds000001
repo: AnnexRepo

Metadata
--------
{
 "conformsto": "http://bids.neuroimaging.io/bids_spec1.0.0.pdf", 
 "citation": "Schonberg TS, Fox CR, Mumford JA, Congdon E, Trepel C, Poldrack RA (2012). Decreasing ventromedial prefrontal cortex activity during sequential risk-taking: An fMRI investigation of the Balloon Analogue Risk Task. Frontiers in Decision Neuroscience, 6:80 doi: 10.3389/fnins.2012.00080", 
 "description": "This dataset was obtained from the OpenfMRI project (http://www.openfmri.org).\nAccession #: ds001\nDescription: Balloon Analog Risk Task\n\nPlease cite the following references if you use these data:\n\nSchonberg TS, Fox CR, Mumford JA, Congdon E, Trepel C, Poldrack RA (2012). Decreasing ventromedial prefrontal cortex activity during sequential risk-taking: An fMRI investigation of the Balloon Analogue Risk Task. Frontiers in Decision Neuroscience, 6:80 doi: 10.3389/fnins.2012.00080\n\n\nRelease history:\n7/10/2012: initial release\n\n3/21/2013: Updated release with QA information\n\n2/18/2016: Fixed orientation information in nifti headers for more consistent left-right determination\n\n\nThis dataset is made available under the Public Domain Dedication and License \nv1.0, whose full text can be found at \nhttp://www.opendatacommons.org/licenses/pddl/1.0/. \nWe hope that all users will follow the ODC Attribution/Share-Alike \nCommunity Norms (http://www.opendatacommons.org/norms/odc-by-sa/); \nin particular, while not legally required, we hope that all users \nof the data will acknowledge the OpenfMRI project and NSF Grant \nOCI-1131441 (R. Poldrack, PI) in any publications.\n\n\n### Comments added by Openfmri Curators ###\n===========================================\n\n\nKnown Issues\n------------\nNot all subjects/sessions/runs have the same scanning parameters.\n  /sub-01/anat/sub-01_inplaneT2.nii.gz\n  /sub-01/func/sub-01_task-balloonanalogrisktask_run-01_bold.nii.gz\n  /sub-01/func/sub-01_task-balloonanalogrisktask_run-02_bold.nii.gz\n  /sub-01/func/sub-01_task-balloonanalogrisktask_run-03_bold.nii.gz\n\nDefacing\n--------\nPydeface was used on all anatomical images to ensure deindentification of subjects. The code\ncan be found at https://github.com/poldracklab/pydeface\n\n\nWhere to discuss the dataset\n----------------------------\n1) www.openfmri.org/dataset/ds******/ See the comments section at the bottom of the dataset\npage.\n2) www.neurostars.org Please tag any discussion topics with the tags openfmri and dsXXXXXX\naccession number.\n3) Send an email to submissions@openfmri.org. Please include the dsXXXXXX accession number in\nyour email.", 
 "license": "This dataset is made available under the Public Domain Dedication and License \nv1.0, whose full text can be found at \nhttp://www.opendatacommons.org/licenses/pddl/1.0/. \nWe hope that all users will follow the ODC Attribution/Share-Alike \nCommunity Norms (http://www.opendatacommons.org/norms/odc-by-sa/); \nin particular, while not legally required, we hope that all users \nof the data will acknowledge the OpenfMRI project and NSF Grant \nOCI-1131441 (R. Poldrack, PI) in any publications.", 
 "author": [
  "Schonberg TS", 
  "Fox CR", 
  "Mumford JA", 
  "Congdon E", 
  "Trepel C", 
  "Poldrack RA"
 ], 
 "unique_content_properties": {
  "bids:participant_id": [
   "sub-01", 
   "sub-02", 
   "sub-03", 
   "sub-04", 
   "sub-05", 
   "sub-06", 
   "sub-07", 
   "sub-08", 
   "sub-09", 
   "sub-10", 
   "sub-11", 
   "sub-12", 
   "sub-13", 
   "sub-14", 
   "sub-15", 
   "sub-16"
  ], 
  "bids:age(years)": [
   "19", 
   "20", 
   "21", 
   "22", 
   "24", 
   "26", 
   "27", 
   "30"
  ], 
  "comment<participant#sex>": [
   "female", 
   "male"
  ], 
  "bids:TaskName": "balloon analog risk task", 
  "bids:RepetitionTime": 2.0
 }, 
 "comment<BIDSVersion>": "1.0.0", 
 "@context": {
  "bids:age(years)": {
   "unit_label": "year", 
   "@id": "pato:0000011", 
   "description": "age of a sample (organism) at the time of data acquisition in years", 
   "unit": "uo:0000036"
  }, 
  "@vocab": "http://docs.datalad.org/schema_v2.0.json", 
  "bids": {
   "type": "http://purl.org/dc/dcam/VocabularyEncodingScheme", 
   "@id": "http://bids.neuroimaging.io/bids_spec1.0.0.pdf#", 
   "description": "ad-hoc vocabulary for the Brain Imaging Data Structure (BIDS) standard"
  }
 }, 
 "@id": "233cc486-7d0e-11e6-855b-002590f97d84", 
 "name": "Balloon Analog Risk Task"
}

```

**Comment by yarikoptic** [comment]
here is some traceback thanks to #2053 
```
[DEBUG  ] Search index contains 134 documents 
^CERROR: 
Interrupted by user while doing magic: KeyboardInterrupt() [binary.py:is_active:160]
Traceback (most recent call last):
  File "/home/yoh/proj/datalad/datalad-master/venvs/dev/bin/datalad", line 8, in <module>
    main()
  File "/home/yoh/proj/datalad/datalad-master/datalad/cmdline/main.py", line 354, in main
    ret = cmdlineargs.func(cmdlineargs)
  File "/home/yoh/proj/datalad/datalad-master/datalad/interface/base.py", line 432, in call_from_parser
    ret = list(ret)
  File "/home/yoh/proj/datalad/datalad-master/datalad/interface/utils.py", line 382, in generator_func
    result_renderer, result_xfm, _result_filter, **_kwargs):
  File "/home/yoh/proj/datalad/datalad-master/datalad/interface/utils.py", line 449, in _process_results
    for res in results:
  File "/home/yoh/proj/datalad/datalad-master/datalad/metadata/search.py", line 660, in __call__
    limit=max_nresults if max_nresults > 0 else None)
  File "/usr/lib/python2.7/dist-packages/whoosh/searching.py", line 786, in search
    self.search_with_collector(q, c)
  File "/usr/lib/python2.7/dist-packages/whoosh/searching.py", line 819, in search_with_collector
    collector.run()
  File "/usr/lib/python2.7/dist-packages/whoosh/collectors.py", line 144, in run
    self.collect_matches()
  File "/usr/lib/python2.7/dist-packages/whoosh/collectors.py", line 633, in collect_matches
    for sub_docnum in self.matches():
  File "/usr/lib/python2.7/dist-packages/whoosh/collectors.py", line 409, in matches
    self.skipped_times += matcher.skip_to_quality(minscore)
  File "/usr/lib/python2.7/dist-packages/whoosh/matching/binary.py", line 774, in skip_to_quality
    while a.is_active() and b.is_active() and aq + bq <= minquality:
  File "/usr/lib/python2.7/dist-packages/whoosh/matching/binary.py", line 160, in is_active
    return self.a.is_active() or self.b.is_active()
  File "/usr/lib/python2.7/dist-packages/whoosh/matching/binary.py", line 160, in is_active
    return self.a.is_active() or self.b.is_active()
KeyboardInterrupt
()
> /usr/lib/python2.7/dist-packages/whoosh/matching/binary.py(160)is_active()
-> return self.a.is_active() or self.b.is_active()
(Pdb) up
> /usr/lib/python2.7/dist-packages/whoosh/matching/binary.py(160)is_active()
-> return self.a.is_active() or self.b.is_active()
(Pdb) 
> /usr/lib/python2.7/dist-packages/whoosh/matching/binary.py(774)skip_to_quality()
-> while a.is_active() and b.is_active() and aq + bq <= minquality:
(Pdb) 
> /usr/lib/python2.7/dist-packages/whoosh/collectors.py(409)matches()
-> self.skipped_times += matcher.skip_to_quality(minscore)
(Pdb) 
> /usr/lib/python2.7/dist-packages/whoosh/collectors.py(633)collect_matches()
-> for sub_docnum in self.matches():
(Pdb) 
> /usr/lib/python2.7/dist-packages/whoosh/collectors.py(144)run()
-> self.collect_matches()
(Pdb) 
> /usr/lib/python2.7/dist-packages/whoosh/searching.py(819)search_with_collector()
-> collector.run()
(Pdb) 
> /usr/lib/python2.7/dist-packages/whoosh/searching.py(786)search()
-> self.search_with_collector(q, c)
(Pdb) p q
Or([Wildcard('@id', u'*a*'), Wildcard(u'author', u'*a*'), Wildcard(u'bids:RepetitionTime', u'*a*'), Wildcard(u'bids:TaskName', u'*a*'), Wildcard(u'bids:age(years)', u'*a*'), Wildcard(u'bids:participant_id', u'*a*'), Wildcard(u'citation', u'*a*'), Wildcard(u'comment<BIDSVersion>', u'*a*'), Wildcard(u'comment<participant#sex>', u'*a*'), Wildcard(u'conformsto', u'*a*'), Wildcard(u'description', u'*a*'), Wildcard(u'license', u'*a*'), Wildcard(u'name', u'*a*'), Wildcard('parentds', u'*a*'), Wildcard('path', u'*a*'), Wildcard('type', u'*a*')])

```

**Comment by mih** [comment]
I can no longer replicate this with #2127.

**Comment by mih** [comment]
So here is what happens on the new big search index (1M records) and current #2157:

```
% datalad search '*ab*'
[INFO   ] Query completed in 8.3466770649 sec. Reporting up to 20 top matches. 
search(ok): openfmri/ds000030/phenotype/spanish_vocab.tsv (file)
...
datalad search '*ab*'  8.82s user 0.11s system 100% cpu 8.882 total
```

Which is slooow.

The same with `'*a*` will take "forever". The reason is that whoosh does not simply compile a sequential list of hits, but scores them to provide the "best" hits first: it is a search engine, not grep. With `*a*` it is tasked to find the best combination of any occurences of a single character `a` in any of 1M candidate string. I do not see the point in such a query, but if it is needed to support that, we better implement a frontend for a `grep` through a metadata dump.

I will close this now.

**Comment by mih** [comment]
I kept thinking about this. We do not actually need to implement anything in other to support "grep-through-all-metadata". The following is done right after `datalad install ///` -- not index building or preprocessing whatsoever:

```
% datalad -f '{path}: {metadata}' metadata -r . --reporton datasets | grep -i Halchenko | cut -d ':' -f1
/tmp/hotshit/dbic
/tmp/hotshit/labs/gobbini
/tmp/hotshit/labs/gobbini/famface/data
/tmp/hotshit/labs/haxby
/tmp/hotshit/labs/haxby/attention
/tmp/hotshit/labs/haxby/life
/tmp/hotshit/labs/haxby/raiders
/tmp/hotshit/openfmri
/tmp/hotshit/openfmri/ds000233
/tmp/hotshit/openfmri/ds000241
/tmp/hotshit/workshops/mind-2017
/tmp/hotshit/workshops/nih-2017
/tmp/hotshit/workshops/nipype-2017
```

On the present state of `///` this has a sub-second runtime. The "worst case" grepping through every known bit of metadata (datasets and files) does not even take a minute for 1M files (with metadata) across 490 datasets:

```
% datalad -f '{path}: {metadata}' metadata -r . --reporton all |grep -i Halchenko | cut -d ':' -f1 
/tmp/hotshit/dbic
/tmp/hotshit/labs/gobbini
/tmp/hotshit/labs/gobbini/famface/data
/tmp/hotshit/labs/haxby
/tmp/hotshit/labs/haxby/attention
/tmp/hotshit/labs/haxby/life
/tmp/hotshit/labs/haxby/raiders
/tmp/hotshit/openfmri
/tmp/hotshit/openfmri/ds000233
/tmp/hotshit/openfmri/ds000241
/tmp/hotshit/workshops/mind-2017
/tmp/hotshit/workshops/nih-2017
/tmp/hotshit/workshops/nipype-2017
datalad -f '{path}: {metadata}' metadata -r . --reporton all  45.68s user 1.53s system 100% cpu 47.004 total
```

Granted, our simplistic output formatter keeps the markup of the `metadata` records as JSON, but otherwise one's full shell script foo can be unleashed.

@yarikoptic @bpoldrack

**Comment by bpoldrack** [comment]
Nice. I think that's sufficient. We can simply have a `datalad-simple-search` script, that does the above, passing its argument into grep and may be (optionally) do a little beautification of json output.

**Comment by mih** [comment]
Or `search --mode regex`

**Comment by yarikoptic** [comment]
Congratulations! Just add ability to print only specific fields in metadata, and we have converged on the old style search 100% just implemented straight in python without shell ;-)

**Comment by mih** [comment]
Except that we have nested metadata (requires a parser to actually get the depth-structure). In the mood to write that?

**Comment by mih** [comment]
Hold on, I was again fooled into thinking we cannot do that. But no. `--output-format` can be used to report arbitrary fields (and combinations even any depth AFAICR) in any result for any command. Hence also for `search`. The issue was that the old search never was a new-style command, hence it had all custom options and procedures.
