### ISSUE TITLE
One test failure and one error with git 2.16.0

### ISSUE THREAD

**Issue by yarikoptic** [datalad/datalad#2089]
https://lwn.net/Articles/744749/

New release, has many changes relating to submodules handling. Would be good to check if no new issues or incompatibilities, and report here... Reporting with #2090 , on 0.9.x branch I observe:
```shell
$> DATALAD_TESTS_SSH=1 PATH=/home/yoh/proj/misc/git/INSTALL-2.16.1/bin:$PATH DATALAD_USE_DEFAULT_GIT=true python -m nose -s -v datalad.distribution.tests.test_uninstall:{test_drop_nocrash_absent_subds,test_uninstall_without_super}
datalad.distribution.tests.test_uninstall.test_drop_nocrash_absent_subds ... ERROR
datalad.distribution.tests.test_uninstall.test_uninstall_without_super ... FAIL
Versions: appdirs=1.4.3 boto=2.44.0 cmd:annex=6.20171211+gitgba511f4de-1~ndall+1 cmd:git=2.16.1 cmd:system-git=2.16.1 cmd:system-ssh=7.6p1 git=2.1.8 gitdb=2.0.2 humanize=0.5.1 iso8601=0.1.11 msgpack=0.4.8 requests=2.18.4 scrapy=1.4.0 six=1.11.0 tqdm=4.19.5 wrapt=1.9.0

======================================================================
ERROR: datalad.distribution.tests.test_uninstall.test_drop_nocrash_absent_subds
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/usr/lib/python2.7/dist-packages/nose/case.py", line 197, in runTest
    self.test(*self.arg)
  File "/home/yoh/proj/datalad/datalad/datalad/tests/utils.py", line 627, in newfunc
    return t(*(arg + (filename,)), **kw)
  File "/home/yoh/proj/datalad/datalad/datalad/distribution/tests/test_uninstall.py", line 522, in test_drop_nocrash_absent_subds
    assert_status('notneeded', drop('.', recursive=True))
  File "/home/yoh/proj/datalad/datalad/datalad/interface/utils.py", line 437, in eval_func
    return return_func(generator_func)(*args, **kwargs)
  File "/home/yoh/proj/datalad/datalad/datalad/interface/utils.py", line 425, in return_func
    results = list(results)
  File "/home/yoh/proj/datalad/datalad/datalad/interface/utils.py", line 382, in generator_func
    result_renderer, result_xfm, _result_filter, **_kwargs):
  File "/home/yoh/proj/datalad/datalad/datalad/interface/utils.py", line 449, in _process_results
    for res in results:
  File "/home/yoh/proj/datalad/datalad/datalad/distribution/drop.py", line 217, in __call__
    handle_dirty_dataset(ds, mode=if_dirty)
  File "/home/yoh/proj/datalad/datalad/datalad/interface/utils.py", line 100, in handle_dirty_dataset
    raise RuntimeError('dataset {} is not yet installed'.format(ds))
RuntimeError: dataset <Dataset path=/tmp/datalad_temp_test_drop_nocrash_absent_subds1F46lj/sub> is not yet installed
-------------------- >> begin captured logging << --------------------
datalad.utils: Level 5: Importing datalad.utils
datalad.utils: Level 5: Done importing datalad.utils
datalad.cmd: Level 9: Will use default git /home/yoh/proj/misc/git/INSTALL-2.16.1/bin/git
datalad.cmd: Level 9: Running: ['git', 'version']
datalad.cmd: Level 8: Finished running ['git', 'version'] with status 0
datalad.cmd: Level 9: Running: ['git', 'config', '-z', '-l', '--show-origin']
datalad.cmd: Level 8: Finished running ['git', 'config', '-z', '-l', '--show-origin'] with status 0
datalad.ui: Level 5: Starting importing ui
datalad.ui.dialog: Level 5: Starting importing ui.dialog
datalad.ui.dialog: Level 5: Done importing ui.dialog
datalad.ui: Level 5: Initiating UI switcher
datalad.ui: DEBUG: UI set to DialogUI(out=<file>)
datalad.ui: Level 5: Done importing ui
--------------------- >> end captured logging << ---------------------

======================================================================
FAIL: datalad.distribution.tests.test_uninstall.test_uninstall_without_super
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/usr/lib/python2.7/dist-packages/nose/case.py", line 197, in runTest
    self.test(*self.arg)
  File "/home/yoh/proj/datalad/datalad/datalad/tests/utils.py", line 627, in newfunc
    return t(*(arg + (filename,)), **kw)
  File "/home/yoh/proj/datalad/datalad/datalad/distribution/tests/test_uninstall.py", line 506, in test_uninstall_without_super
    assert_result_count(subreport, 1, path=sub.path, state='absent')
  File "/home/yoh/proj/datalad/datalad/datalad/tests/utils.py", line 1185, in assert_result_count
    dumps(results, indent=1, default=lambda x: "<not serializable>")))
AssertionError: Got 0 instead of 1 expected results matching {'path': '/tmp/datalad_temp_test_uninstall_without_superQr8FHA/sub', 'state': 'absent'}. Inspected 1 record(s):
[
 {
  "status": "ok", 
  "gitmodule_name": "sub", 
  "parentds": "/tmp/datalad_temp_test_uninstall_without_superQr8FHA", 
  "state": "clean", 
  "revision_descr": "(null)", 
  "gitmodule_url": "./sub", 
  "action": "subdataset", 
  "path": "/tmp/datalad_temp_test_uninstall_without_superQr8FHA/sub", 
  "type": "dataset", 
  "refds": "/tmp/datalad_temp_test_uninstall_without_superQr8FHA", 
  "revision": "8dd60313164ed7d521cd4608bc2179f60d6c0930"
 }
]

----------------------------------------------------------------------
Ran 2 tests in 4.378s

FAILED (errors=1, failures=1)
```
whenever it is all kosher if without that new git:
```shell
$> DATALAD_TESTS_SSH=1 PATH=/home/yoh/proj/misc/git/INSTALL-2.16.1/bin:$PATH python -m nose -s -v datalad.distribution.tests.test_uninstall:{test_drop_nocrash_absent_subds,test_uninstall_without_super}        
datalad.distribution.tests.test_uninstall.test_drop_nocrash_absent_subds ... ok
datalad.distribution.tests.test_uninstall.test_uninstall_without_super ... ok
Versions: appdirs=1.4.3 boto=2.44.0 cmd:annex=6.20171211+gitgba511f4de-1~ndall+1 cmd:git=2.11.0 cmd:system-git=2.16.1 cmd:system-ssh=7.6p1 git=2.1.8 gitdb=2.0.2 humanize=0.5.1 iso8601=0.1.11 msgpack=0.4.8 requests=2.18.4 scrapy=1.4.0 six=1.11.0 tqdm=4.19.5 wrapt=1.9.0
```

**Comment by yarikoptic** [comment]
updated with the results @datalad/developers , have a look please

**Comment by yarikoptic** [comment]
on master (after merging that #2090 ) seems to be one more (I have two other failing regardless of which git, not listing here):
```shell
$> DATALAD_TESTS_SSH=1 PATH=/home/yoh/proj/misc/git/INSTALL-2.16.1/bin:$PATH DATALAD_USE_DEFAULT_GIT=1 python -m nose -s -v datalad/metadata/tests/test_aggregation.py:test_basic_aggregate 
datalad.metadata.tests.test_aggregation.test_basic_aggregate ... sub (dataset): homepage
. (dataset): 
dataset_description.json (file): -
sub (dataset): homepage
sub/dataset_description.json (file): -
sub/subsub (dataset): 
sub/subsub/dataset_description.json (file): -
. (dataset): 
dataset_description.json (file): -
sub (dataset): homepage
sub/dataset_description.json (file): -
sub/subsub (dataset): 
ERROR
Versions: appdirs=1.4.3 boto=2.44.0 cmd:annex=6.20171211+gitgba511f4de-1~ndall+1 cmd:git=2.16.1 cmd:system-git=2.16.1 cmd:system-ssh=7.6p1 git=2.1.8 gitdb=2.0.2 humanize=0.5.1 iso8601=0.1.11 msgpack=0.4.8 requests=2.18.4 scrapy=1.4.0 six=1.11.0 tqdm=4.19.5 wrapt=1.9.0

======================================================================
ERROR: datalad.metadata.tests.test_aggregation.test_basic_aggregate
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/usr/lib/python2.7/dist-packages/nose/case.py", line 197, in runTest
    self.test(*self.arg)
  File "/home/yoh/proj/datalad/datalad/datalad/tests/utils.py", line 493, in newfunc
    return t(*(arg + (d,)), **kw)
  File "/home/yoh/proj/datalad/datalad/datalad/tests/utils.py", line 869, in newfunc
    return func(*args, **kwargs)
  File "/home/yoh/proj/datalad/datalad/datalad/tests/utils.py", line 1021, in newfunc
    return func(*args, **kwargs)
  File "/home/yoh/proj/datalad/datalad/datalad/metadata/tests/test_aggregation.py", line 76, in test_basic_aggregate
    agg_meta = base.metadata(recursive=True, return_type='list')
  File "/home/yoh/proj/datalad/datalad/datalad/distribution/dataset.py", line 437, in apply_func
    return f(**kwargs)
  File "/home/yoh/proj/datalad/datalad/datalad/interface/utils.py", line 437, in eval_func
    return return_func(generator_func)(*args, **kwargs)
  File "/home/yoh/proj/datalad/datalad/datalad/interface/utils.py", line 425, in return_func
    results = list(results)
  File "/home/yoh/proj/datalad/datalad/datalad/interface/utils.py", line 382, in generator_func
    result_renderer, result_xfm, _result_filter, **_kwargs):
  File "/home/yoh/proj/datalad/datalad/datalad/interface/utils.py", line 449, in _process_results
    for res in results:
  File "/home/yoh/proj/datalad/datalad/datalad/metadata/metadata.py", line 1093, in __call__
    **res_kwargs):
  File "/home/yoh/proj/datalad/datalad/datalad/metadata/metadata.py", line 375, in query_aggregated_metadata
    cache, merge_mode):
  File "/home/yoh/proj/datalad/datalad/datalad/metadata/metadata.py", line 484, in _query_aggregated_metadata_singlepath
    files = list(_get_metadatarelevant_paths(ds, cache['subds_relpaths']))
  File "/home/yoh/proj/datalad/datalad/datalad/metadata/metadata.py", line 253, in _get_metadatarelevant_paths
    return (f for f in ds.repo.get_files()
  File "/home/yoh/proj/datalad/datalad/datalad/support/gitrepo.py", line 1278, in get_files
    return self.get_indexed_files()
  File "/home/yoh/proj/datalad/datalad/datalad/support/gitrepo.py", line 1084, in get_indexed_files
    self.repo.index.entries.keys)]
  File "/home/yoh/proj/datalad/datalad/datalad/support/gitrepo.py", line 618, in repo
    self._repo = self.cmd_call_wrapper(Repo, self.path)
  File "/home/yoh/proj/datalad/datalad/datalad/cmd.py", line 134, in __call__
    return self.call(cmd, *args, **kwargs)
  File "/home/yoh/proj/datalad/datalad/datalad/cmd.py", line 492, in call
    return f(*args, **kwargs)
  File "/home/yoh/proj/datalad/datalad/datalad/support/gitrepo.py", line 387, in Repo
    return gitpy.Repo(*args, **kwargs)
  File "/usr/lib/python2.7/dist-packages/git/repo/base.py", line 161, in __init__
    raise InvalidGitRepositoryError(epath)
InvalidGitRepositoryError: /tmp/datalad_temp_tree_test_basic_aggregateaWbpkg/origin/sub/subsub
-------------------- >> begin captured logging << --------------------
datalad.utils: Level 5: Importing datalad.utils
datalad.utils: Level 5: Done importing datalad.utils
datalad.cmd: Level 9: Will use default git /home/yoh/proj/misc/git/INSTALL-2.16.1/bin/git
datalad.cmd: Level 9: Running: ['git', 'version']
datalad.cmd: Level 8: Finished running ['git', 'version'] with status 0
datalad.cmd: Level 9: Running: ['git', 'config', '-z', '-l', '--show-origin']
datalad.cmd: Level 8: Finished running ['git', 'config', '-z', '-l', '--show-origin'] with status 0
datalad.ui: Level 5: Starting importing ui
datalad.ui.dialog: Level 5: Starting importing ui.dialog
datalad.ui.dialog: Level 5: Done importing ui.dialog
datalad.ui: Level 5: Initiating UI switcher
datalad.ui: DEBUG: UI set to DialogUI(out=<file>)
datalad.ui: Level 5: Done importing ui
--------------------- >> end captured logging << ---------------------

----------------------------------------------------------------------
Ran 1 test in 7.713s

```

**Comment by yarikoptic** [comment]
@mih - this is the failure I am seeing after installing git from experimental:
```shell
$> git describe
0.9.1-842-g4ab98cf5

$> sudo apt-get install git{,-man,k,-svn,-gui,-email}=1:2.16.1+next.20180209-1
....

$> git --version
git version 2.16.1.291.g4437f3f132
(dev) 2 11731 [1].....................................:Sun 18 Feb 2018 11:11:05 PM EST:.
(git)hopa:~datalad/datalad-master[master]git
$> DATALAD_TESTS_SSH=1 DATALAD_USE_DEFAULT_GIT=1 python -m nose -s -v datalad/metadata/tests/test_aggregation.py:test_basic_aggregate        
datalad.metadata.tests.test_aggregation.test_basic_aggregate ... . (dataset): datalad_core
dataset_description.json (file): 
sub (dataset): datalad_core
sub/dataset_description.json (file): 
sub/subsub (dataset): datalad_core
sub/subsub/dataset_description.json (file): 
. (dataset): datalad_core
dataset_description.json (file): 
sub (dataset): datalad_core
sub/dataset_description.json (file): 
sub/subsub (dataset): -
('/home/yoh/.tmp/datalad_temp_tree_test_basic_aggregateYnNG7e/origin', '/home/yoh/.tmp/datalad_temp_tree_test_basic_aggregateYnNG7e/origin')
('/home/yoh/.tmp/datalad_temp_tree_test_basic_aggregateYnNG7e/origin/dataset_description.json', '/home/yoh/.tmp/datalad_temp_tree_test_basic_aggregateYnNG7e/origin/dataset_description.json')
(u'/home/yoh/.tmp/datalad_temp_tree_test_basic_aggregateYnNG7e/origin/sub', u'/home/yoh/.tmp/datalad_temp_tree_test_basic_aggregateYnNG7e/origin/sub')
(u'/home/yoh/.tmp/datalad_temp_tree_test_basic_aggregateYnNG7e/origin/sub/dataset_description.json', u'/home/yoh/.tmp/datalad_temp_tree_test_basic_aggregateYnNG7e/origin/sub/dataset_description.json')
(u'/home/yoh/.tmp/datalad_temp_tree_test_basic_aggregateYnNG7e/origin/sub/subsub', u'/home/yoh/.tmp/datalad_temp_tree_test_basic_aggregateYnNG7e/origin/sub/subsub')
FAIL
Versions: appdirs=1.4.3 boto=2.44.0 cmd:annex=6.20180206+gitg638032f3a-1~ndall+1 cmd:git=2.16.1.291.g4437f3f132 cmd:system-git=2.16.1.291.g4437f3f132 cmd:system-ssh=7.6p1 git=2.1.8 gitdb=2.0.2 humanize=0.5.1 iso8601=0.1.11 msgpack=0.4.8 requests=2.18.4 scrapy=1.4.0 six=1.11.0 tqdm=4.19.5 wrapt=1.10.11

======================================================================
FAIL: datalad.metadata.tests.test_aggregation.test_basic_aggregate
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/usr/lib/python2.7/dist-packages/nose/case.py", line 197, in runTest
    self.test(*self.arg)
  File "/home/yoh/proj/datalad/datalad-master/datalad/tests/utils.py", line 493, in newfunc
    return t(*(arg + (d,)), **kw)
  File "/home/yoh/proj/datalad/datalad-master/datalad/tests/utils.py", line 869, in newfunc
    return func(*args, **kwargs)
  File "/home/yoh/proj/datalad/datalad-master/datalad/tests/utils.py", line 1021, in newfunc
    return func(*args, **kwargs)
  File "/home/yoh/proj/datalad/datalad-master/datalad/metadata/tests/test_aggregation.py", line 79, in test_basic_aggregate
    assert_dict_equal(d, a)
  File "/home/yoh/proj/datalad/datalad-master/datalad/tests/utils.py", line 1139, in assert_dict_equal
    raise AssertionError("dicts differ:\n%s" % "\n".join(msgs))
AssertionError: dicts differ:
 ['refcommit'] differs: u'8fc0d98c2c8a47ac831c1aae5cfd68bb4a4d2bf6' != None
 ['metadata'] differs: {u'@context': {u'@vocab': u'http://docs.datalad.org/schema_v2.0.json'}, u'datalad_core': {u'@id': u'ed6b8b12-152a-11e8-bee2-8019340ce7f2'}} != {}
```
it passes with the git version in debian-devel for stretch 1:2.13.0~rc1+next.20170430-1~nd90+1  and sid already has 2.16.1 !

**Comment by yarikoptic** [comment]
heh, and here is few more with 2.16.1 from unstable
```
Versions: appdirs=1.4.3 boto=2.44.0 cmd:annex=6.20180206+gitg638032f3a-1~ndall+1 cmd:git=2.16.1 cmd:system-git=2.16.1 cmd:system-ssh=7.6p1 git=2.1.8 gitdb=2.0.2 humanize=0.5.1 iso8601=0.1.11 mock=2.0.0 msgpack=0.4.8 patoolib=1.12 requests=2.18.4 scrapy=1.4.0 six=1.11.0 tqdm=4.19.5 wrapt=1.10.11

======================================================================
ERROR: datalad.distribution.tests.test_uninstall.test_drop_nocrash_absent_subds
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/usr/lib/python2.7/dist-packages/nose/case.py", line 197, in runTest
    self.test(*self.arg)
  File "/home/yoh/proj/datalad/datalad-master/datalad/tests/utils.py", line 628, in newfunc
    return t(*(arg + (filename,)), **kw)
  File "/home/yoh/proj/datalad/datalad-master/datalad/distribution/tests/test_uninstall.py", line 522, in test_drop_nocrash_absent_subds
    assert_status('notneeded', drop('.', recursive=True))
  File "/home/yoh/proj/datalad/datalad-master/datalad/interface/utils.py", line 463, in eval_func
    return return_func(generator_func)(*args, **kwargs)
  File "/home/yoh/proj/datalad/datalad-master/datalad/interface/utils.py", line 451, in return_func
    results = list(results)
  File "/home/yoh/proj/datalad/datalad-master/datalad/interface/utils.py", line 408, in generator_func
    result_renderer, result_xfm, _result_filter, **_kwargs):
  File "/home/yoh/proj/datalad/datalad-master/datalad/interface/utils.py", line 475, in _process_results
    for res in results:
  File "/home/yoh/proj/datalad/datalad-master/datalad/distribution/drop.py", line 217, in __call__
    handle_dirty_dataset(ds, mode=if_dirty)
  File "/home/yoh/proj/datalad/datalad-master/datalad/interface/utils.py", line 100, in handle_dirty_dataset
    raise RuntimeError('dataset {} is not yet installed'.format(ds))
RuntimeError: dataset <Dataset path=/tmp/datalad_temp_test_drop_nocrash_absent_subdsNx9ROO/sub> is not yet installed

======================================================================
ERROR: datalad.tests.test_s3.test_version_url_deleted
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/usr/lib/python2.7/dist-packages/nose/case.py", line 197, in runTest
    self.test(*self.arg)
  File "/usr/lib/python2.7/dist-packages/vcr/cassette.py", line 105, in __call__
    function, args, kwargs
  File "/usr/lib/python2.7/dist-packages/vcr/cassette.py", line 120, in _execute_function
    return self._handle_function(fn=handle_function)
  File "/usr/lib/python2.7/dist-packages/vcr/cassette.py", line 141, in _handle_function
    return fn(cassette)
  File "/usr/lib/python2.7/dist-packages/vcr/cassette.py", line 113, in handle_function
    return function(*args, **kwargs)
  File "/home/yoh/proj/datalad/datalad-master/datalad/tests/test_s3.py", line 64, in test_version_url_deleted
    eq_(get_versioned_url(url), turl)
  File "/home/yoh/proj/datalad/datalad-master/datalad/support/s3.py", line 373, in get_versioned_url
    assert(all_keys[0].is_latest)
IndexError: list index out of range

======================================================================
FAIL: datalad.distribution.tests.test_uninstall.test_uninstall_without_super
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/usr/lib/python2.7/dist-packages/nose/case.py", line 197, in runTest
    self.test(*self.arg)
  File "/home/yoh/proj/datalad/datalad-master/datalad/tests/utils.py", line 628, in newfunc
    return t(*(arg + (filename,)), **kw)
  File "/home/yoh/proj/datalad/datalad-master/datalad/distribution/tests/test_uninstall.py", line 506, in test_uninstall_without_super
    assert_result_count(subreport, 1, path=sub.path, state='absent')
  File "/home/yoh/proj/datalad/datalad-master/datalad/tests/utils.py", line 1192, in assert_result_count
    dumps(results, indent=1, default=lambda x: "<not serializable>")))
AssertionError: Got 0 instead of 1 expected results matching {'path': '/tmp/datalad_temp_test_uninstall_without_superEYoCS7/sub', 'state': 'absent'}. Inspected 1 record(s):
[
 {
  "status": "ok", 
  "gitmodule_name": "sub", 
  "parentds": "/tmp/datalad_temp_test_uninstall_without_superEYoCS7", 
  "state": "clean", 
  "revision_descr": "(null)", 
  "gitmodule_url": "./sub", 
  "action": "subdataset", 
  "path": "/tmp/datalad_temp_test_uninstall_without_superEYoCS7/sub", 
  "type": "dataset", 
  "refds": "/tmp/datalad_temp_test_uninstall_without_superEYoCS7", 
  "revision": "30bb6a9e3b15de03f8bd28f3ae45390dbae92d9c"
 }
]
```

**Comment by mih** [comment]
I ran `sudo apt-get install git{,-man,k,-svn,-gui,-email}=1:2.16.1-1`, and it seems I cannot replicate any of the failures that are listed here.

**Comment by mih** [comment]
On a full test run on my laptop I get tons of these:

```
======================================================================
ERROR: datalad.distribution.tests.test_dataset.test_is_installed
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/usr/lib/python2.7/dist-packages/nose/case.py", line 197, in runTest
    self.test(*self.arg)
  File "/home/mih/hacking/datalad/git/datalad/tests/utils.py", line 783, in newfunc
    testrepos_uris = _get_testrepos_uris(regex, flavors_)
  File "/home/mih/hacking/datalad/git/datalad/tests/utils.py", line 735, in _get_testrepos_uris
    uris.append(clone_url(spec['local']))
  File "/home/mih/hacking/datalad/git/datalad/tests/utils.py", line 672, in clone_url
    if GitRepo(tdir).is_with_annex():
  File "/home/mih/hacking/datalad/git/datalad/support/gitrepo.py", line 786, in is_with_annex
    for b in self.get_remote_branches())) or \
  File "/home/mih/hacking/datalad/git/datalad/support/gitrepo.py", line 1216, in get_remote_branches
    for ref in remote.refs:
  File "/usr/lib/python2.7/dist-packages/git/remote.py", line 533, in refs
    out_refs.extend(RemoteReference.list_items(self.repo, remote=self.name))
  File "/usr/lib/python2.7/dist-packages/git/util.py", line 932, in list_items
    out_list.extend(cls.iter_items(repo, *args, **kwargs))
  File "/usr/lib/python2.7/dist-packages/git/refs/symbolic.py", line 613, in _iter_items
    for sha, rela_path in cls._iter_packed_refs(repo):  # @UnusedVariable
  File "/usr/lib/python2.7/dist-packages/git/refs/symbolic.py", line 97, in _iter_packed_refs
    raise TypeError("PackingType of packed-Refs not understood: %r" % line)
TypeError: PackingType of packed-Refs not understood: '# pack-refs with: peeled fully-peeled sorted'
```

The traceback varies, but the common denominator seems to be the `get_remote_branches()` call.

**Comment by yarikoptic** [comment]
Make sure you use DATALAD_USE_DEFAULT_GIT and that reported git is the new one

**Comment by mih** [comment]
Ah, right. annex standalone. However, that doesn't explain the above behavior. But if it does, that is a bug on its own.

**Comment by mih** [comment]
All the "TypeError: PackingType of packed-Refs not understood: '# pack-refs with: peeled fully-peeled sorted'" error could be resolved with an upgrade of GitPython.

**Comment by yarikoptic** [comment]
package builds now on debian sid, which comes with 2.16.2, so issues were dealt with AFAIK
