### ISSUE TITLE
Automagic IO crash that doesn't lead to a failure

### ISSUE THREAD

**Issue by mih** [datalad/datalad#2107]
#### What is the problem?

From https://travis-ci.org/datalad/datalad/jobs/333356795

Looks like an infinite loop that is somehow caught and does not leed to a test failure.

```
datalad.interface.tests.test_utils.test_result_filter ... ok
                                                                                ok
                                                                                Traceback (most recent call last):
  File "/opt/python/2.7.14/lib/python2.7/logging/handlers.py", line 78, in emit
    logging.FileHandler.emit(self, record)
  File "/opt/python/2.7.14/lib/python2.7/logging/__init__.py", line 957, in emit
    StreamHandler.emit(self, record)
Traceback (most recent call last):
  File "/opt/python/2.7.14/lib/python2.7/logging/__init__.py", line 861, in emit
    msg = self.format(record)
  File "/opt/python/2.7.14/lib/python2.7/logging/__init__.py", line 734, in format
    return fmt.format(record)
  File "/home/travis/build/datalad/datalad/datalad/log.py", line 151, in format
    record.msg = self._tb() + "  " + record.msg
  File "/home/travis/build/datalad/datalad/datalad/log.py", line 68, in __call__
    ftb = self._extract_stack(limit=200)[:-2]
  File "/opt/python/2.7.14/lib/python2.7/traceback.py", line 306, in extract_stack
Traceback (most recent call last):
Traceback (most recent call last):
  File "/opt/python/2.7.14/lib/python2.7/logging/handlers.py", line 78, in emit
    logging.FileHandler.emit(self, record)
  File "/opt/python/2.7.14/lib/python2.7/logging/__init__.py", line 957, in emit
    StreamHandler.emit(self, record)
  File "/opt/python/2.7.14/lib/python2.7/logging/__init__.py", line 889, in emit
    self.handleError(record)
  File "/opt/python/2.7.14/lib/python2.7/logging/__init__.py", line 812, in handleError
    None, sys.stderr)
  File "/opt/python/2.7.14/lib/python2.7/traceback.py", line 125, in print_exception
    print_tb(tb, limit, file)
  File "/opt/python/2.7.14/lib/python2.7/traceback.py", line 67, in print_tb
    '  File "%s", line %d, in %s' % (filename, lineno, name))
RuntimeError: maximum recursion depth exceeded
Logged from file auto.py, line 146
    line = linecache.getline(filename, lineno, f.f_globals)
  File "/home/travis/virtualenv/python2.7.14/lib/python2.7/linecache.py", line 14, in getline
Traceback (most recent call last):
Traceback (most recent call last):
  File "/opt/python/2.7.14/lib/python2.7/logging/handlers.py", line 78, in emit
    logging.FileHandler.emit(self, record)
  File "/opt/python/2.7.14/lib/python2.7/logging/__init__.py", line 957, in emit
    StreamHandler.emit(self, record)
  File "/opt/python/2.7.14/lib/python2.7/logging/__init__.py", line 889, in emit
    self.handleError(record)
  File "/opt/python/2.7.14/lib/python2.7/logging/__init__.py", line 812, in handleError
    None, sys.stderr)
  File "/opt/python/2.7.14/lib/python2.7/traceback.py", line 125, in print_exception
    print_tb(tb, limit, file)
  File "/opt/python/2.7.14/lib/python2.7/traceback.py", line 67, in print_tb
    '  File "%s", line %d, in %s' % (filename, lineno, name))
RuntimeError: maximum recursion depth exceeded
Logged from file auto.py, line 146
    lines = getlines(filename, module_globals)
  File "/home/travis/virtualenv/python2.7.14/lib/python2.7/linecache.py", line 41, in getlines
    return updatecache(filename, module_globals)
  File "/home/travis/virtualenv/python2.7.14/lib/python2.7/linecache.py", line 131, in updatecache
    with open(fullname, 'rU') as fp:
  File "/home/travis/build/datalad/datalad/datalad/auto.py", line 196, in _proxy_open
    *args, **kwargs)
  File "/home/travis/build/datalad/datalad/datalad/auto.py", line 183, in _proxy_open_name_mode
    lgr.log(2, " skipping since " + (e.msg % e.args))
  File "/opt/python/2.7.14/lib/python2.7/logging/__init__.py", line 1231, in log
    self._log(level, msg, args, **kwargs)
  File "/opt/python/2.7.14/lib/python2.7/logging/__init__.py", line 1286, in _log
    self.handle(record)
  File "/opt/python/2.7.14/lib/python2.7/logging/__init__.py", line 1296, in handle
    self.callHandlers(record)
  File "/opt/python/2.7.14/lib/python2.7/logging/__init__.py", line 1336, in callHandlers
    hdlr.handle(record)
  File "/opt/python/2.7.14/lib/python2.7/logging/__init__.py", line 759, in handle
    self.emit(record)
  File "/opt/python/2.7.14/lib/python2.7/logging/handlers.py", line 82, in emit
    self.handleError(record)
  File "/opt/python/2.7.14/lib/python2.7/logging/__init__.py", line 812, in handleError
    None, sys.stderr)
  File "/opt/python/2.7.14/lib/python2.7/traceback.py", line 126, in print_exception
    lines = format_exception_only(etype, value)
  File "/opt/python/2.7.14/lib/python2.7/traceback.py", line 178, in format_exception_only
    return [_format_final_exc_line(stype, value)]
  File "/opt/python/2.7.14/lib/python2.7/traceback.py", line 205, in _format_final_exc_line
    valuestr = _some_str(value)
  File "/opt/python/2.7.14/lib/python2.7/traceback.py", line 222, in _some_str
    return '<unprintable %s object>' % type(value).__name__
RuntimeError: maximum recursion depth exceeded while calling a Python object
Logged from file auto.py, line 183
audio.mp3 (file): comment<bitrate>,comment<date>,comment<tracknumber>,duration(s),format,music:Genre,music:album,music:artist,music:channels,music:sample_rate,name
ok
LFA_Read: read failure
ok
```

**Comment by yarikoptic** [comment]
good find! I will have a look

**Comment by yarikoptic** [comment]
I have failed to find a real cause for the issue... difficult to get into debugger whenever you are already at "maximum" ;)  but it is an interplay of auto/logging (at level 2, works at 3)/ and traceback.  I believe it would appear only when we are trying to log the traceback as well.  I do not think that it leads to any kind of failure (besides some log message is not printed).  I thought to submit a PR handling failure to get a traceback which removes those nasty long tracebacks above but then one more came up instead and outside of our control seems to me.  I will keep it open for now since still couldn't figure out the actual cause (could be within traceback module trying to open some new submodules ... unlikely but possible)

**Comment by mih** [comment]
Another instance of this (from #2187):

```
Traceback (most recent call last):
  File "/usr/lib/python2.7/logging/__init__.py", line 861, in emit
    msg = self.format(record)
  File "/usr/lib/python2.7/logging/__init__.py", line 734, in format
    return fmt.format(record)
  File "/home/mih/hacking/datalad/git/datalad/log.py", line 151, in format
    record.msg = self._tb() + "  " + record.msg
  File "/home/mih/hacking/datalad/git/datalad/log.py", line 68, in __call__
    ftb = self._extract_stack(limit=200)[:-2]
  File "/usr/lib/python2.7/traceback.py", line 306, in extract_stack
Traceback (most recent call last):
  File "/usr/lib/python2.7/logging/handlers.py", line 78, in emit
    logging.FileHandler.emit(self, record)
  File "/usr/lib/python2.7/logging/__init__.py", line 957, in emit
    StreamHandler.emit(self, record)
  File "/usr/lib/python2.7/logging/__init__.py", line 889, in emit
    self.handleError(record)
  File "/usr/lib/python2.7/logging/__init__.py", line 812, in handleError
    None, sys.stderr)
  File "/usr/lib/python2.7/traceback.py", line 125, in print_exception
Traceback (most recent call last):
  File "/usr/lib/python2.7/logging/handlers.py", line 78, in emit
Traceback (most recent call last):
  File "/usr/lib/python2.7/logging/handlers.py", line 78, in emit
Traceback (most recent call last):
  File "/usr/lib/python2.7/logging/__init__.py", line 861, in emit
    msg = self.format(record)
  File "/usr/lib/python2.7/logging/__init__.py", line 734, in format
    return fmt.format(record)
  File "/home/mih/hacking/datalad/git/datalad/log.py", line 151, in format
    record.msg = self._tb() + "  " + record.msg
  File "/home/mih/hacking/datalad/git/datalad/log.py", line 68, in __call__
    ftb = self._extract_stack(limit=200)[:-2]
  File "/usr/lib/python2.7/traceback.py", line 306, in extract_stack
    line = linecache.getline(filename, lineno, f.f_globals)
  File "/usr/lib/python2.7/linecache.py", line 14, in getline
    lines = getlines(filename, module_globals)
  File "/usr/lib/python2.7/linecache.py", line 41, in getlines
    return updatecache(filename, module_globals)
  File "/usr/lib/python2.7/linecache.py", line 131, in updatecache
    with open(fullname, 'rU') as fp:
  File "/home/mih/hacking/datalad/git/datalad/auto.py", line 196, in _proxy_open
    *args, **kwargs)
  File "/home/mih/hacking/datalad/git/datalad/auto.py", line 183, in _proxy_open_name_mode
    lgr.log(2, " skipping since " + (e.msg % e.args))
  File "/usr/lib/python2.7/logging/__init__.py", line 1231, in log
    self._log(level, msg, args, **kwargs)
  File "/usr/lib/python2.7/logging/__init__.py", line 1286, in _log
    self.handle(record)
  File "/usr/lib/python2.7/logging/__init__.py", line 1296, in handle
    self.callHandlers(record)
  File "/usr/lib/python2.7/logging/__init__.py", line 1336, in callHandlers
    hdlr.handle(record)
  File "/usr/lib/python2.7/logging/__init__.py", line 759, in handle
    self.emit(record)
  File "/usr/lib/python2.7/logging/handlers.py", line 82, in emit
    self.handleError(record)
  File "/usr/lib/python2.7/logging/__init__.py", line 812, in handleError
    None, sys.stderr)
  File "/usr/lib/python2.7/traceback.py", line 125, in print_exception
    print_tb(tb, limit, file)
  File "/usr/lib/python2.7/traceback.py", line 69, in print_tb
    line = linecache.getline(filename, lineno, f.f_globals)
  File "/usr/lib/python2.7/linecache.py", line 14, in getline
    lines = getlines(filename, module_globals)
  File "/usr/lib/python2.7/linecache.py", line 41, in getlines
    return updatecache(filename, module_globals)
  File "/usr/lib/python2.7/linecache.py", line 131, in updatecache
    with open(fullname, 'rU') as fp:
  File "/home/mih/hacking/datalad/git/datalad/auto.py", line 196, in _proxy_open
    *args, **kwargs)
  File "/home/mih/hacking/datalad/git/datalad/auto.py", line 188, in _proxy_open_name_mode
    lgr.warning("Failed proxying open with %r, %r: %s", args, kwargs, exc_str(e))
  File "/usr/lib/python2.7/logging/__init__.py", line 1179, in warning
    self._log(WARNING, msg, args, **kwargs)
  File "/usr/lib/python2.7/logging/__init__.py", line 1286, in _log
    self.handle(record)
  File "/usr/lib/python2.7/logging/__init__.py", line 1296, in handle
    self.callHandlers(record)
  File "/usr/lib/python2.7/logging/__init__.py", line 1336, in callHandlers
    hdlr.handle(record)
  File "/usr/lib/python2.7/logging/__init__.py", line 759, in handle
    self.emit(record)
  File "/usr/lib/python2.7/logging/handlers.py", line 82, in emit
    self.handleError(record)
  File "/usr/lib/python2.7/logging/__init__.py", line 812, in handleError
    None, sys.stderr)
  File "/usr/lib/python2.7/traceback.py", line 125, in print_exception
    print_tb(tb, limit, file)
  File "/usr/lib/python2.7/traceback.py", line 68, in print_tb
    linecache.checkcache(filename)
  File "/usr/lib/python2.7/linecache.py", line 68, in checkcache
    if size != stat.st_size or mtime != stat.st_mtime:
RuntimeError: maximum recursion depth exceeded in cmp
```

**Comment by mih** [comment]
The last error I can reproduce reliable, but only under PY2, runs fine under PY3.

**Comment by yarikoptic** [comment]
What is the reliable way to reproduce (command etc)?

**Comment by mih** [comment]
```
DATALAD_LOG_LEVEL=2 DATALAD_LOG_TARGET=/dev/null DATALAD_LOG_TRACEBACK=collide DATALAD_API_ALWAYSRENDER=1 DATALAD_TESTS_PROTOCOLREMOTE=1 DATALAD_TESTS_DATALADREMOTE=1 DATALAD_LOG_CMD_CWD=1 DATALAD_LOG_CMD_OUTPUTS=1 DATALAD_LOG_CMD_ENV=1 DATALAD_LOG_CMD_STDIN=1 DATALAD_TESTS_UI_BACKEND=console DATALAD_TESTS_OBSCURE_PREFIX=-   nosetests -s datalad/metadata/tests/test_aggregation.py:test_basic_aggregate
```

**Comment by yarikoptic** [comment]
ok, FTR caught it with change in datalad/log.py
```diff
@@ -148,7 +148,10 @@ class ColorFormatter(logging.Formatter):
             record.levelname = levelname_color
         record.msg = record.msg.replace("\n", "\n| ")
         if self._tb:
-            record.msg = self._tb() + "  " + record.msg
+            try:
+                record.msg = self._tb() + "  " + record.msg
+            except Exception as exc:
+                import pdb; pdb.set_trace()
 
         return logging.Formatter.format(self, record)
```

so it "loops" in 
```
  /home/yoh/proj/datalad/datalad-master/datalad/auto.py(183)_proxy_open_name_mode()
-> lgr.log(2, " skipping since " + (e.msg % e.args))
  /usr/lib/python2.7/logging/__init__.py(1238)log()
-> self._log(level, msg, args, **kwargs)
  /usr/lib/python2.7/logging/__init__.py(1293)_log()
-> self.handle(record)
  /usr/lib/python2.7/logging/__init__.py(1303)handle()
-> self.callHandlers(record)
  /usr/lib/python2.7/logging/__init__.py(1343)callHandlers()
-> hdlr.handle(record)
  /usr/lib/python2.7/logging/__init__.py(766)handle()
-> self.emit(record)
  /usr/lib/python2.7/logging/handlers.py(78)emit()
-> logging.FileHandler.emit(self, record)
  /usr/lib/python2.7/logging/__init__.py(964)emit()
-> StreamHandler.emit(self, record)
  /usr/lib/python2.7/logging/__init__.py(868)emit()
-> msg = self.format(record)
  /usr/lib/python2.7/logging/__init__.py(741)format()
-> return fmt.format(record)
  /home/yoh/proj/datalad/datalad-master/datalad/log.py(152)format()
-> record.msg = self._tb() + "  " + record.msg
  /home/yoh/proj/datalad/datalad-master/datalad/log.py(68)__call__()
-> ftb = self._extract_stack(limit=100)[:-2]
  /usr/lib/python2.7/traceback.py(306)extract_stack()
-> line = linecache.getline(filename, lineno, f.f_globals)
  /home/yoh/proj/datalad/datalad-master/venvs/dev/lib/python2.7/linecache.py(14)getline()
-> lines = getlines(filename, module_globals)
  /home/yoh/proj/datalad/datalad-master/venvs/dev/lib/python2.7/linecache.py(41)getlines()
-> return updatecache(filename, module_globals)
  /home/yoh/proj/datalad/datalad-master/venvs/dev/lib/python2.7/linecache.py(131)updatecache()
-> with open(fullname, 'rU') as fp:
  /home/yoh/proj/datalad/datalad-master/datalad/auto.py(196)_proxy_open()
-> *args, **kwargs)
  /home/yoh/proj/datalad/datalad-master/datalad/auto.py(183)_proxy_open_name_mode()
-> lgr.log(2, " skipping since " + (e.msg % e.args))
```
