### ISSUE TITLE
test_bids2scidata.test_minimal fails and leaves temporary directory in the codebase

### ISSUE THREAD

**Issue by yarikoptic** [datalad/datalad#2140]
#### What is the problem?
```shell
(git)hopa:~datalad/datalad-master[master]git
$> rm -rf scidata*
(dev) 3 8911 [2].....................................:Sun 11 Feb 2018 01:10:10 PM EST:.
(git)hopa:~datalad/datalad-master[master]git
$> ls -dl scidata*                                          
ls: cannot access 'scidata*': No such file or directory
(dev) 3 8912 ->2 [2].....................................:Sun 11 Feb 2018 01:10:12 PM EST:.
(git)hopa:~datalad/datalad-master[master]git
$> nosetests -s -v datalad/plugin/tests/test_bids2scidata.py
datalad.plugin.tests.test_bids2scidata.test_minimal ... ERROR
datalad.plugin.tests.test_bids2scidata.test_noop ... ok
Versions: appdirs=1.4.3 boto=2.44.0 cmd:annex=6.20180206+gitg638032f3a-1~ndall+1 cmd:git=2.11.0 cmd:system-git=2.15.1 cmd:system-ssh=7.6p1 git=2.1.8 gitdb=2.0.2 humanize=0.5.1 iso8601=0.1.11 msgpack=0.4.8 requests=2.18.4 scrapy=1.4.0 six=1.11.0 tqdm=4.19.5 wrapt=1.9.0

======================================================================
ERROR: datalad.plugin.tests.test_bids2scidata.test_minimal
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/usr/lib/python2.7/dist-packages/nose/case.py", line 197, in runTest
    self.test(*self.arg)
  File "/home/yoh/proj/datalad/datalad-master/datalad/tests/utils.py", line 493, in newfunc
    return t(*(arg + (d,)), **kw)
  File "/home/yoh/proj/datalad/datalad-master/datalad/plugin/tests/test_bids2scidata.py", line 95, in test_minimal
    ds.aggregate_metadata()
  File "/home/yoh/proj/datalad/datalad-master/datalad/distribution/dataset.py", line 437, in apply_func
    return f(**kwargs)
  File "/home/yoh/proj/datalad/datalad-master/datalad/interface/utils.py", line 437, in eval_func
    return return_func(generator_func)(*args, **kwargs)
  File "/home/yoh/proj/datalad/datalad-master/datalad/interface/utils.py", line 425, in return_func
    results = list(results)
  File "/home/yoh/proj/datalad/datalad-master/datalad/interface/utils.py", line 413, in generator_func
    msg="Command did not complete successfully")
IncompleteResultsError: Command did not complete successfully [{'action': 'aggregate_metadata', 'path': '/home/yoh/.tmp/datalad_temp_tree_test_minimalcBTBJK/ds', 'status': 'error', 'message': 'Metadata extraction failed (see previous error message)'}]
-------------------- >> begin captured logging << --------------------
datalad.utils: Level 5: Importing datalad.utils
datalad.utils: Level 5: Done importing datalad.utils
datalad.cmd: Level 9: Will use git under '/usr/lib/git-annex.linux' (no adjustments to PATH if empty string)
datalad.cmd: Level 9: Running: ['git', 'version']
datalad.cmd: Level 8: Finished running ['git', 'version'] with status 0
datalad.cmd: Level 9: Running: ['git', 'config', '-z', '-l', '--show-origin']
datalad.cmd: Level 8: Finished running ['git', 'config', '-z', '-l', '--show-origin'] with status 0
datalad.ui: Level 5: Starting importing ui
datalad.ui.dialog: Level 5: Starting importing ui.dialog
datalad.ui.dialog: Level 5: Done importing ui.dialog
datalad.ui: Level 5: Initiating UI switcher
datalad.ui: DEBUG: UI set to DialogUI(out=<file>)
datalad.ui: Level 5: Done importing ui
--------------------- >> end captured logging << ---------------------

----------------------------------------------------------------------
Ran 2 tests in 4.648s

FAILED (errors=1)
nosetests -s -v datalad/plugin/tests/test_bids2scidata.py  3.94s user 2.23s system 108% cpu 5.697 total
(dev) 3 8913 ->1 [2].....................................:Sun 11 Feb 2018 01:10:21 PM EST:.
(git)hopa:~datalad/datalad-master[master]git
$> ls -dl scidata*                                          
drwx------ 2 yoh yoh 4096 Feb 11 13:10 scidata_isatab_276e3582061e86ee04a4f2874a60e10c0ccadbbd/

```
#### What version of DataLad are you using (run `datalad --version`)? On what operating system (consider running `datalad plugin wtf`)?

```shell
$> git describe
0.9.1-725-g8a31e828
```

**Comment by mih** [comment]
I cannot replicate the failure locally, and I do not seem to have such commit. Please let me know what branch this is and what other conditions might apply. Please try rerunning with master after the merge of #2143 and set `datalad.runtime.raiseonerror=yes` to pinpoint the source of the failure.

**Comment by yarikoptic** [comment]
may be wasn't yet merged? dunno -- currently part of master
```shell
$> git branch --contains 0.9.1-725-g8a31e828
  enh-merge-0.9.x
* master
```
replicated with current 0.9.1-801-g7dc2b8f9 
Crash is due to later observed bug with symlinks in bids extractor: #2150
Left over file is unrelated to the crash and still there:

```shell
 $> rm -rf scidata*; TMPDIR=/tmp python -m nose -s -v datalad/plugin/tests/test_bids2scidata.py 
datalad.plugin.tests.test_bids2scidata.test_minimal ... ok
datalad.plugin.tests.test_bids2scidata.test_noop ... ok
Versions: appdirs=1.4.3 boto=2.44.0 cmd:annex=6.20180206+gitg638032f3a-1~ndall+1 cmd:git=2.11.0 cmd:system-git=2.15.1 cmd:system-ssh=7.6p1 git=2.1.8 gitdb=2.0.2 humanize=0.5.1 iso8601=0.1.11 msgpack=0.4.8 requests=2.18.4 scrapy=1.4.0 six=1.11.0 tqdm=4.19.5 wrapt=1.10.11

----------------------------------------------------------------------
Ran 2 tests in 5.990s

OK
TMPDIR=/tmp python -m nose -s -v datalad/plugin/tests/test_bids2scidata.py  4.63s user 2.29s system 97% cpu 7.075 total
(dev) 3 10233.....................................:Thu 15 Feb 2018 09:48:10 AM EST:.
(git)hopa:~datalad/datalad-master[master]git
$> ls -ld scidata_isatab_5b55c1175e34d66e3a5d04ca72acada23d3bc526 
drwx------ 2 yoh yoh 4096 Feb 15 09:48 scidata_isatab_5b55c1175e34d66e3a5d04ca72acada23d3bc526/
```

**Comment by yarikoptic** [comment]
I will push the fix but I am really interested how the leftover directory didn't reproduce for you since it was created in current directory for sure by the test_noop
