### ISSUE TITLE
another crash of aggregate-metadata: No matching aggregated metadata in Dataset at /mnt/btrfs/datasets-meta6-1/datalad/crawl

### ISSUE THREAD

**Issue by yarikoptic** [datalad/datalad#2142]
#### What is the problem?
This is a follow up to #2135 -- that one seems to be fixed.  The next one is
```
save(ok): /mnt/btrfs/datasets-meta6-1/datalad/crawl (dataset)
action summary:
  aggregate_metadata (error: 8, impossible: 1, ok: 490)
  save (ok: 490)
Traceback (most recent call last):
  File "/home/yoh/proj/datalad/datalad-master/venvs/dev/bin/datalad", line 8, in <module>
    main()
  File "/home/yoh/proj/datalad/datalad-master/datalad/cmdline/main.py", line 354, in main
    ret = cmdlineargs.func(cmdlineargs)
  File "/home/yoh/proj/datalad/datalad-master/datalad/interface/base.py", line 432, in call_from_parser
    ret = list(ret)
  File "/home/yoh/proj/datalad/datalad-master/datalad/interface/utils.py", line 413, in generator_func
    msg="Command did not complete successfully")
IncompleteResultsError: Command did not complete successfully [{'action': 'aggregate_metadata', 'path': '/mnt/btrfs/datasets-meta6-1/datalad/crawl/dicoms', 'status': 'impossible', 'message': ('No matching aggregated metadata in Dataset at %s', '/mnt/btrfs/datasets-meta6-1/datalad/crawl')}, {'action': 'aggregate_metadata', 'path': '/mnt/btrfs/datasets-meta6-1/datalad/crawl/openfmri/ds000030', 'status': 'error', 'message': 'Metadata extraction failed (see previous error message)'}, {'action': 'aggregate_metadata', 'path': '/mnt/btrfs/datasets-meta6-1/datalad/crawl/openfmri/ds000053', 'status': 'error', 'message': 'Metadata extraction failed (see previous error message)'}, {'action': 'aggregate_metadata', 'path': '/mnt/btrfs/datasets-meta6-1/datalad/crawl/openfmri/ds000117', 'status': 'error', 'message': 'Metadata extraction failed (see previous error message)'}, {'action': 'aggregate_metadata', 'path': '/mnt/btrfs/datasets-meta6-1/datalad/crawl/openfmri/ds000164', 'status': 'error', 'message': 'Metadata extraction failed (see previous error message)'}, {'action': 'aggregate_metadata', 'path': '/mnt/btrfs/datasets-meta6-1/datalad/crawl/openfmri/ds000214', 'status': 'error', 'message': 'Metadata extraction failed (see previous error message)'}, {'action': 'aggregate_metadata', 'path': '/mnt/btrfs/datasets-meta6-1/datalad/crawl/openfmri/ds000216', 'status': 'error', 'message': 'Metadata extraction failed (see previous error message)'}, {'action': 'aggregate_metadata', 'path': '/mnt/btrfs/datasets-meta6-1/datalad/crawl/openfmri/ds000221', 'status': 'error', 'message': 'Metadata extraction failed (see previous error message)'}, {'action': 'aggregate_metadata', 'path': '/mnt/btrfs/datasets-meta6-1/datalad/crawl/openfmri/ds000224', 'status': 'error', 'message': 'Metadata extraction failed (see previous error message)'}]
()
> /home/yoh/proj/datalad/datalad-master/datalad/interface/utils.py(413)generator_func()
-> msg="Command did not complete successfully")
```

I really dislike `see previous error message` approach since as you can see here hard to deduce which previous message -- I guess it could be the `"No matching aggregated metadata in Dataset at %s"` which is also not clear where it is coming from etc

**Comment by mih** [comment]
Given that I have the result on my laptop, I think this can be closed.
