### ISSUE TITLE
Generating autofield search index for /// fails

### ISSUE THREAD

**Issue by mih** [datalad/datalad#2162]
#### What is the problem?

```
...
[INFO   ] Added 212 documents on dataset workshops/repronim-sfn-2017/challenge 
[ERROR  ] [Errno 2] No such file or directory: u'/tmp/hotshit/.git/datalad/search_index/autofield/MAIN_ydpeac96i6hf3hmw._bids.participant.care_negcons_aggr/illeg_len.col' [filestore.py:create_file:490] (IOError) 
datalad search --mode autofield --reindex  795.88s user 3.35s system 99% cpu 13:21.16 total
```

and sure thing it does that hundreds of datasets and 13min into the process. Thanks!

**Comment by mih** [comment]
Reproduced, with traceback:

```
Traceback (most recent call last):
  File "/home/mih/hacking/datalad/git/bin/datalad", line 8, in <module>
    main()
  File "/home/mih/hacking/datalad/git/datalad/cmdline/main.py", line 354, in main
    ret = cmdlineargs.func(cmdlineargs)
  File "/home/mih/hacking/datalad/git/datalad/interface/base.py", line 432, in call_from_parser
    ret = list(ret)
  File "/home/mih/hacking/datalad/git/datalad/interface/utils.py", line 382, in generator_func
    result_renderer, result_xfm, _result_filter, **_kwargs):
  File "/home/mih/hacking/datalad/git/datalad/interface/utils.py", line 449, in _process_results
    for res in results:
  File "/home/mih/hacking/datalad/git/datalad/metadata/search.py", line 635, in __call__
    documenttype)
  File "/home/mih/hacking/datalad/git/datalad/metadata/search.py", line 408, in _get_search_index
    idx.commit(optimize=True)
  File "/usr/lib/python2.7/dist-packages/whoosh/writing.py", line 927, in commit
    finalsegments.append(self._finalize_segment())
  File "/usr/lib/python2.7/dist-packages/whoosh/writing.py", line 866, in _finalize_segment
    self._flush_segment()
  File "/usr/lib/python2.7/dist-packages/whoosh/writing.py", line 830, in _flush_segment
    self.perdocwriter.close()
  File "/usr/lib/python2.7/dist-packages/whoosh/codec/whoosh3.py", line 267, in close
    self._cols.save_as_files(self._storage, self._column_filename)
  File "/usr/lib/python2.7/dist-packages/whoosh/filedb/compound.py", line 298, in save_as_files
    f = storage.create_file(name_fn(name))
  File "/usr/lib/python2.7/dist-packages/whoosh/filedb/filestore.py", line 490, in create_file
    fileobj = open(path, mode)
```

I suspect that getting schema fields with names like this `u'bids.participant.care_engaging_aggr/illeg'` is the problem. Not yet clear where they are from.

**Comment by mih** [comment]
Ok, works now. Few key things FTR and @yarikoptic :

15min to generate the index, with 780 different keys

```
[INFO   ] Search index contains 1085975 documents 
datalad search --mode autofield --reindex  910.10s user 9.95s system 99% cpu 15:24.15 total
```
Huge when uncompressed
```
% du -sh .git/datalad/search_index/autofield
1.2G    .git/datalad/search_index/autofield
```
Much potential for homogenization, e.g.:

```
bids.participant.age(years)
bids.participant.age_(5_year_bins)
bids.participant.age_(years)
bids.participant.age_at_baseline_
bids.participant.age_at_onset_first_cb_use
bids.participant.age_at_onset_frequent_cb_use
```
Otherwise quite usable:

```
% datalad -f '{query_matched}' search --mode autofield female bids.participant.age_(years):'[24 TO 26]'
[INFO   ] Query completed in 0.041130065918 sec. Reporting up to 20 top matches. 
{u'bids.participant.age_(years)': u'25', u'bids.participant.sex': u'female', u'bids.description': u'female'}
{u'bids.participant.age_(years)': u'26', u'bids.participant.sex': u'female'}
{u'bids.participant.age_(years)': u'26', u'bids.participant.sex': u'female'}
{u'bids.participant.age_(years)': u'24', u'bids.participant.sex': u'female'}
{u'bids.participant.age_(years)': u'24', u'bids.participant.sex': u'female'}
{u'bids.participant.age_(years)': u'24', u'bids.participant.sex': u'female'}
{u'bids.participant.age_(years)': u'24', u'bids.participant.sex': u'female'}
{u'bids.participant.age_(years)': u'25', u'bids.participant.sex': u'female'}
{u'bids.participant.age_(years)': u'25', u'bids.participant.sex': u'female'}
{u'bids.participant.age_(years)': u'25', u'bids.participant.sex': u'female'}
...
```
