### ISSUE TITLE
whoosh search index writer issues on NFS

### ISSUE THREAD

**Issue by mih** [datalad/datalad#2192]
#### What is the problem?

```
% datalad --dbg search mr
[INFO   ] Rebuilding search index 
[INFO   ] Processing metadata records for 5 datasets 
[INFO   ] Added 1 document on dataset . 
[INFO   ] Added 1 document on dataset 7t 
[INFO   ] Added 1 document on dataset 7t/yx11_2014/dicoms 
[INFO   ] Added 1 document on dataset 7t/yx11_2015/dicoms 
[INFO   ] Added 1 document on dataset 7t/yx11_2022/dicoms 
Traceback (most recent call last):
  File "/home/mih/datalad4users/bin/datalad", line 9, in <module>
    load_entry_point('datalad==0.3.0.dev1', 'console_scripts', 'datalad')()
  File "/home/mih/datalad4users/datalad/cmdline/main.py", line 354, in main
    ret = cmdlineargs.func(cmdlineargs)
  File "/home/mih/datalad4users/datalad/interface/base.py", line 432, in call_from_parser
    ret = list(ret)
  File "/home/mih/datalad4users/datalad/interface/utils.py", line 408, in generator_func
    result_renderer, result_xfm, _result_filter, **_kwargs):
  File "/home/mih/datalad4users/datalad/interface/utils.py", line 475, in _process_results
    for res in results:
  File "/home/mih/datalad4users/datalad/metadata/search.py", line 638, in __call__
    documenttype)
  File "/home/mih/datalad4users/datalad/metadata/search.py", line 411, in _get_search_index
    idx.commit(optimize=True)
  File "/usr/lib/python2.7/dist-packages/whoosh/writing.py", line 935, in commit
    self._finish()
  File "/usr/lib/python2.7/dist-packages/whoosh/writing.py", line 884, in _finish
    self._tempstorage.destroy()
  File "/usr/lib/python2.7/dist-packages/whoosh/filedb/filestore.py", line 458, in destroy
    self.clean()
  File "/usr/lib/python2.7/dist-packages/whoosh/filedb/filestore.py", line 518, in clean
    os.remove(os.path.join(path, fname))
OSError: [Errno 16] Device or resource busy: '/home/mih/scratch/cbbstest/lin/.git/datalad/search_index/default/MAIN.tmp/.nfs0000000000392db500027c44'
```

Sadly a simple delay doesn't work around this issue, as whoosh doesn't expect this situation:

```diff
diff --git a/datalad/metadata/search.py b/datalad/metadata/search.py
index a7aa7b5b..f4cf0eb0 100644
--- a/datalad/metadata/search.py
+++ b/datalad/metadata/search.py
@@ -40,6 +40,7 @@ from datalad.consts import LOCAL_CENTRAL_PATH
 from datalad.consts import SEARCH_INDEX_DOTGITDIR
 from datalad.utils import assure_list
 from datalad.utils import assure_unicode
+from datalad.dochelpers import exc_str
 from datalad.support.exceptions import NoDatasetArgumentFound
 from datalad.ui import ui
 from datalad.dochelpers import single_or_plural
@@ -408,7 +409,15 @@ def _get_search_index(index_dir, label, ds, force_reindex, get_schema, meta2doc,
             old_ds_rpath)
 
     lgr.debug("Committing index")
-    idx.commit(optimize=True)
+    try:
+        idx.commit(optimize=True)
+    except OSError as e:
+        lgr.warning(
+            'Failed to store search index, trying again in two seconds [{}]'.format(
+                exc_str(e)))
+        import time
+        time.sleep(2)
+        idx.commit()
 
     # "timestamp" the search index to allow for automatic invalidation
     with open(stamp_fname, 'w') as f:
```

```
<snip>
[WARNING] Failed to store search index, trying again in two seconds [[Errno 16] Device or resource busy: '/home/mih/scratch/cbbstest/lin/.git/datalad/search_index/default/MAIN.tmp/.nfs0000000000392dd300027c4a' [filestore.py:clean:518]] 
Traceback (most recent call last):
  File "/home/mih/datalad4users/bin/datalad", line 9, in <module>
    load_entry_point('datalad==0.3.0.dev1', 'console_scripts', 'datalad')()
  File "/home/mih/datalad4users/datalad/cmdline/main.py", line 354, in main
    ret = cmdlineargs.func(cmdlineargs)
  File "/home/mih/datalad4users/datalad/interface/base.py", line 432, in call_from_parser
    ret = list(ret)
  File "/home/mih/datalad4users/datalad/interface/utils.py", line 408, in generator_func
    result_renderer, result_xfm, _result_filter, **_kwargs):
  File "/home/mih/datalad4users/datalad/interface/utils.py", line 475, in _process_results
    for res in results:
  File "/home/mih/datalad4users/datalad/metadata/search.py", line 647, in __call__
    documenttype)
  File "/home/mih/datalad4users/datalad/metadata/search.py", line 420, in _get_search_index
    idx.commit()
  File "/usr/lib/python2.7/dist-packages/whoosh/writing.py", line 927, in commit
    finalsegments.append(self._finalize_segment())
  File "/usr/lib/python2.7/dist-packages/whoosh/writing.py", line 866, in _finalize_segment
    self._flush_segment()
  File "/usr/lib/python2.7/dist-packages/whoosh/writing.py", line 830, in _flush_segment
    self.perdocwriter.close()
  File "/usr/lib/python2.7/dist-packages/whoosh/codec/whoosh3.py", line 267, in close
    self._cols.save_as_files(self._storage, self._column_filename)
  File "/usr/lib/python2.7/dist-packages/whoosh/filedb/compound.py", line 297, in save_as_files
    for name, blocks in self._readback():
  File "/usr/lib/python2.7/dist-packages/whoosh/filedb/compound.py", line 278, in _readback
    temp.close()
  File "/usr/lib/python2.7/dist-packages/whoosh/filedb/structfile.py", line 123, in close
    raise Exception("This file is already closed")
Exception: This file is already closed
```

**Comment by yarikoptic** [comment]
IIRC this happens if file was not closed properly before process terminated... ?

**Comment by yarikoptic** [comment]
I would have first tried with master whoosh to make sure it is not smth fixed upstream already.  And then try to check if that file is properly closed ... I know that it sounds moronic but code
```python
        if self.is_closed:
            raise Exception("This file is already closed")
        if self.onclose:
            self.onclose(self)
        if hasattr(self.file, "close"):
            self.file.close()
        self.is_closed = True
```
leaves at least an opportunity that `self.file` somehow is not `.close()`d (since they have that check for having a close for some reason) -- could be some kind of abstraction without proper close etc

**Comment by mih** [comment]
Please see #2326 for a related RF.

**Comment by yarikoptic** [comment]
I don't think `whoosh` is the default search mechanism ATM (so actual `datalad --dbg search mr` works), unlikely anyone uses it ATM, or someone would run into this issue.  I will close it to free up an "issue space".
