### ISSUE TITLE
Some tests should be rugged to skip if depends are missing etc

### ISSUE THREAD

**Issue by yarikoptic** [datalad/datalad#2199]
#### What is the problem?
ideally we should just skip the tests which miss some non-core dependency.  This is what tests fail/error out while building as root within docker neurodebian (no pybids/grabbits yet either):
```
======================================================================
ERROR: Failure: ImportError (No module named bids.grabbids)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/usr/lib/python2.7/dist-packages/nose/loader.py", line 418, in loadTestsFromName
    addr.filename, addr.module)
  File "/usr/lib/python2.7/dist-packages/nose/importer.py", line 47, in importFromPath
    return self.importFromDir(dir_path, fqname)
  File "/usr/lib/python2.7/dist-packages/nose/importer.py", line 94, in importFromDir
    mod = load_module(part_fqname, fh, filename, desc)
  File "/tmp/datalad/datalad/metadata/extractors/tests/test_bids.py", line 14, in <module>
    from datalad.metadata.extractors.bids import MetadataExtractor
  File "/tmp/datalad/datalad/metadata/extractors/bids.py", line 13, in <module>
    from bids.grabbids import BIDSLayout
ImportError: No module named bids.grabbids

======================================================================
ERROR: Failure: ImportError (No module named bids.grabbids)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/usr/lib/python2.7/dist-packages/nose/loader.py", line 418, in loadTestsFromName
    addr.filename, addr.module)
  File "/usr/lib/python2.7/dist-packages/nose/importer.py", line 47, in importFromPath
    return self.importFromDir(dir_path, fqname)
  File "/usr/lib/python2.7/dist-packages/nose/importer.py", line 94, in importFromDir
    mod = load_module(part_fqname, fh, filename, desc)
  File "/tmp/datalad/datalad/metadata/tests/test_aggregation.py", line 29, in <module>
    from ..extractors.tests.test_bids import bids_template
  File "/tmp/datalad/datalad/metadata/extractors/tests/test_bids.py", line 14, in <module>
    from datalad.metadata.extractors.bids import MetadataExtractor
  File "/tmp/datalad/datalad/metadata/extractors/bids.py", line 13, in <module>
    from bids.grabbids import BIDSLayout
ImportError: No module named bids.grabbids

======================================================================
ERROR: datalad.metadata.tests.test_base.test_aggregation
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/usr/lib/python2.7/dist-packages/nose/case.py", line 197, in runTest
    self.test(*self.arg)
  File "/tmp/datalad/datalad/tests/utils.py", line 869, in newfunc
    return func(*args, **kwargs)
  File "/tmp/datalad/datalad/tests/utils.py", line 1021, in newfunc
    return func(*args, **kwargs)
  File "/tmp/datalad/datalad/tests/utils.py", line 493, in newfunc
    return t(*(arg + (d,)), **kw)
  File "/tmp/datalad/datalad/metadata/tests/test_base.py", line 113, in test_aggregation
    res = ds.aggregate_metadata(recursive=True)
  File "/tmp/datalad/datalad/distribution/dataset.py", line 437, in apply_func
    return f(**kwargs)
  File "/tmp/datalad/datalad/interface/utils.py", line 437, in eval_func
    return return_func(generator_func)(*args, **kwargs)
  File "/tmp/datalad/datalad/interface/utils.py", line 425, in return_func
    results = list(results)
  File "/tmp/datalad/datalad/interface/utils.py", line 413, in generator_func
    msg="Command did not complete successfully")
IncompleteResultsError: Command did not complete successfully [{'action': 'aggregate_metadata', 'path': '/tmp/datalad_temp_tree_test_aggregationw_rMnK/origin', 'status': 'error', 'message': 'Metadata extraction failed (see previous error message, set datalad.runtime.raiseonerror=yes to fail immediately)'}, {'action': 'aggregate_metadata', 'path': '/tmp/datalad_temp_tree_test_aggregationw_rMnK/origin/sub', 'status': 'error', 'message': 'Metadata extraction failed (see previous error message, set datalad.runtime.raiseonerror=yes to fail immediately)'}, {'action': 'aggregate_metadata', 'path': '/tmp/datalad_temp_tree_test_aggregationw_rMnK/origin/sub/subsub', 'status': 'error', 'message': 'Metadata extraction failed (see previous error message, set datalad.runtime.raiseonerror=yes to fail immediately)'}]

======================================================================
ERROR: Failure: ImportError (No module named bids.grabbids)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/usr/lib/python2.7/dist-packages/nose/loader.py", line 418, in loadTestsFromName
    addr.filename, addr.module)
  File "/usr/lib/python2.7/dist-packages/nose/importer.py", line 47, in importFromPath
    return self.importFromDir(dir_path, fqname)
  File "/usr/lib/python2.7/dist-packages/nose/importer.py", line 94, in importFromDir
    mod = load_module(part_fqname, fh, filename, desc)
  File "/tmp/datalad/datalad/metadata/tests/test_search.py", line 33, in <module>
    from datalad.metadata.extractors.tests.test_bids import bids_template
  File "/tmp/datalad/datalad/metadata/extractors/tests/test_bids.py", line 14, in <module>
    from datalad.metadata.extractors.bids import MetadataExtractor
  File "/tmp/datalad/datalad/metadata/extractors/bids.py", line 13, in <module>
    from bids.grabbids import BIDSLayout
ImportError: No module named bids.grabbids

======================================================================
ERROR: datalad.plugin.tests.test_bids2scidata.test_minimal
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/usr/lib/python2.7/dist-packages/nose/case.py", line 197, in runTest
    self.test(*self.arg)
  File "/tmp/datalad/datalad/tests/utils.py", line 493, in newfunc
    return t(*(arg + (d,)), **kw)
  File "/tmp/datalad/datalad/plugin/tests/test_bids2scidata.py", line 98, in test_minimal
    ds.aggregate_metadata()
  File "/tmp/datalad/datalad/distribution/dataset.py", line 437, in apply_func
    return f(**kwargs)
  File "/tmp/datalad/datalad/interface/utils.py", line 437, in eval_func
    return return_func(generator_func)(*args, **kwargs)
  File "/tmp/datalad/datalad/interface/utils.py", line 425, in return_func
    results = list(results)
  File "/tmp/datalad/datalad/interface/utils.py", line 413, in generator_func
    msg="Command did not complete successfully")
IncompleteResultsError: Command did not complete successfully [{'action': 'aggregate_metadata', 'path': '/tmp/datalad_temp_tree_test_minimalBbCffc/ds', 'status': 'error', 'message': 'Metadata extraction failed (see previous error message, set datalad.runtime.raiseonerror=yes to fail immediately)'}]

======================================================================
ERROR: datalad.plugin.tests.test_bids2scidata.test_noop
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/usr/lib/python2.7/dist-packages/nose/case.py", line 197, in runTest
    self.test(*self.arg)
  File "/tmp/datalad/datalad/tests/utils.py", line 493, in newfunc
    return t(*(arg + (d,)), **kw)
  File "/tmp/datalad/datalad/tests/utils.py", line 628, in newfunc
    return t(*(arg + (filename,)), **kw)
  File "/tmp/datalad/datalad/plugin/tests/test_bids2scidata.py", line 85, in test_noop
    repo_url='http://example.com',
  File "/usr/lib/python2.7/unittest/case.py", line 473, in assertRaises
    callableObj(*args, **kwargs)
  File "/tmp/datalad/datalad/distribution/dataset.py", line 437, in apply_func
    return f(**kwargs)
  File "/tmp/datalad/datalad/interface/utils.py", line 437, in eval_func
    return return_func(generator_func)(*args, **kwargs)
  File "/tmp/datalad/datalad/interface/utils.py", line 425, in return_func
    results = list(results)
  File "/tmp/datalad/datalad/interface/utils.py", line 382, in generator_func
    result_renderer, result_xfm, _result_filter, **_kwargs):
  File "/tmp/datalad/datalad/interface/utils.py", line 449, in _process_results
    for res in results:
  File "/tmp/datalad/datalad/plugin/__init__.py", line 264, in __call__
    for res in plugin_call(**supported_args):
  File "/tmp/datalad/datalad/plugin/bids2scidata.py", line 599, in dlplugin
    'Comment[Data Record URI]': repo_url},
  File "/tmp/datalad/datalad/plugin/bids2scidata.py", line 389, in extract
    import pandas
ImportError: No module named pandas

======================================================================
ERROR: datalad.plugin.tests.test_plugins.test_add_readme
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/usr/lib/python2.7/dist-packages/nose/case.py", line 197, in runTest
    self.test(*self.arg)
  File "/tmp/datalad/datalad/tests/utils.py", line 493, in newfunc
    return t(*(arg + (d,)), **kw)
  File "/tmp/datalad/datalad/plugin/tests/test_plugins.py", line 257, in test_add_readme
    ds.aggregate_metadata()
  File "/tmp/datalad/datalad/distribution/dataset.py", line 437, in apply_func
    return f(**kwargs)
  File "/tmp/datalad/datalad/interface/utils.py", line 437, in eval_func
    return return_func(generator_func)(*args, **kwargs)
  File "/tmp/datalad/datalad/interface/utils.py", line 425, in return_func
    results = list(results)
  File "/tmp/datalad/datalad/interface/utils.py", line 413, in generator_func
    msg="Command did not complete successfully")
IncompleteResultsError: Command did not complete successfully [{'action': 'aggregate_metadata', 'path': '/tmp/datalad_temp_tree_test_add_readme06mLBw', 'status': 'error', 'message': 'Metadata extraction failed (see previous error message, set datalad.runtime.raiseonerror=yes to fail immediately)'}]

======================================================================
FAIL: datalad.cmdline.tests.test_main.test_cfg_override
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/usr/lib/python2.7/dist-packages/nose/case.py", line 197, in runTest
    self.test(*self.arg)
  File "/tmp/datalad/datalad/tests/utils.py", line 628, in newfunc
    return t(*(arg + (filename,)), **kw)
  File "/tmp/datalad/datalad/cmdline/tests/test_main.py", line 200, in test_cfg_override
    assert_in('datalad.dummy: this', out)
AssertionError: 'datalad.dummy: this' not found in '\nConfiguration\n=============\ndatalad.datasets.topurl: http://datasets-tests.datalad.org/\ndatalad.log.level: 100\ndatalad.tests.nonetwork: 1\nuser.email: <HIDDEN>\nuser.name: <HIDDEN>\n\n\n'

----------------------------------------------------------------------
Ran 813 tests in 4271.855s

FAILED (SKIP=81, errors=7, failures=1)
```

**Comment by yarikoptic** [comment]
bids ones should be gone -- check for the other ones in a clean docker
