### ISSUE TITLE
Unicode issue with PY3.5

### ISSUE THREAD

**Issue by mih** [datalad/datalad#2244]
PY3.5 test on container from #2242 fails with unicode error

```
======================================================================
ERROR: datalad.tests.test_config.test_something
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/usr/local/lib/python3.5/dist-packages/nose/case.py", line 198, in runTest
    self.test(*self.arg)
  File "/usr/local/lib/python3.5/dist-packages/datalad/tests/utils.py", line 492, in newfunc
    create_tree(d, tree, archives_leading_dir=archives_leading_dir)
  File "/usr/local/lib/python3.5/dist-packages/datalad/tests/utils.py", line 174, in create_tree
    create_tree(full_name, load, archives_leading_dir=archives_leading_dir)
  File "/usr/local/lib/python3.5/dist-packages/datalad/tests/utils.py", line 174, in create_tree
    create_tree(full_name, load, archives_leading_dir=archives_leading_dir)
  File "/usr/local/lib/python3.5/dist-packages/datalad/tests/utils.py", line 182, in create_tree
    f.write(load)
UnicodeEncodeError: 'ascii' codec can't encode character '\u306e' in position 94: ordinal not in range(128)

======================================================================
ERROR: datalad.tests.test_utils.test_read_csv_lines_tsv_unicode
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/usr/local/lib/python3.5/dist-packages/nose/case.py", line 198, in runTest
    self.test(*self.arg)
  File "/usr/local/lib/python3.5/dist-packages/datalad/tests/utils.py", line 629, in newfunc
    return t(*(arg + (filename,)), **kw)
  File "/usr/local/lib/python3.5/dist-packages/datalad/tests/test_utils.py", line 914, in test_read_csv_lines_tsv_unicode
    list(gen),
  File "/usr/local/lib/python3.5/dist-packages/datalad/utils.py", line 1455, in read_csv_lines
    for row in csv_reader:
  File "/usr/lib/python3.5/encodings/ascii.py", line 26, in decode
    return codecs.ascii_decode(input, self.errors)[0]
UnicodeDecodeError: 'ascii' codec can't decode byte 0xd0 in position 9: ordinal not in range(128)
```

**Comment by mih** [comment]
I wondered we we didn't see this before and realized that travis is not testing for PY3.5. However, this is the default PY3 on Debian stable (not 3.4) any reason why this is like this @yarikoptic ? Or shall we just switch.

**Comment by yarikoptic** [comment]
Because something was (or still) in the way:
https://github.com/datalad/datalad/pull/1528

**Comment by mih** [comment]
FTR: #2248 is the first step towards possibly avoiding the issue in #1528 and get PY3.(5,6) being tested.

**Comment by mih** [comment]
Transition to PY3.5 and 3.7 has long been done. Closing.
