### ISSUE TITLE
datalad test  might pick up local

### ISSUE THREAD

**Issue by yarikoptic** [datalad/datalad#2252]
#### What is the problem?

running the flashu singularity image so way too many errors and only later mentioned that all datalad paths refer to the local datalad repo 

```shell
[yhalchen@ndoli ~]$ head -n 30 datalad-datalad-master-fullmaster.tests.log      
Could not import jpeg_ls
Could not import gdcm
.EEE......F.......E.Running unit tests for datalad
Python version 3.5.3 (default, Jan 19 2017, 14:11:04) [GCC 6.3.0 20170118]
nose version 1.3.7
                                                                                    .E..SSS....SSSSSEEEEEE...EEEEEEE.E...EEEES...................................S.S..........................S....S.SSS.SS.EEEEEEEE.....E.........S...................E...SSS......SS..................S............ESSSSSSSSS....S...................................EE..................SEE....F.......FE................E.............E...
----------------------------------------------------------------------
Ran 1 test in 0.001s

OK
......SS.E................/tmp/datalad_temp_test_annex_add_no_dotfiles_daqnnbx
Running unit tests for datalad
Python version 3.5.3 (default, Jan 19 2017, 14:11:04) [GCC 6.3.0 20170118]
nose version 1.3.7
....S...................EE..S........S..E......................E
======================================================================
ERROR: datalad.cmdline.tests.test_formatters.test_parser_access
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/usr/local/lib/python3.5/dist-packages/nose/case.py", line 198, in runTest
    self.test(*self.arg)
  File "/ihome/yhalchen/datalad/datalad/cmdline/tests/test_formatters.py", line 87, in test_parser_access
    parsers = setup_parser(return_subparsers=True)
TypeError: setup_parser() missing 1 required positional argument: 'cmdlineargs'
...
======================================================================
FAIL: datalad.tests.test_cmd.test_runner_dry
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/usr/local/lib/python3.5/dist-packages/nose/case.py", line 198, in runTest
    self.test(*self.arg)
  File "/ihome/yhalchen/datalad/datalad/tests/utils.py", line 1086, in newfunc
    func(*args, **kwargs)
  File "/ihome/yhalchen/datalad/datalad/tests/utils.py", line 927, in newfunc
    reraise(*exc_info)
  File "/usr/lib/python3/dist-packages/six.py", line 686, in reraise
    raise value
  File "/ihome/yhalchen/datalad/datalad/tests/utils.py", line 903, in newfunc
    func(*args, **kwargs)
  File "/ihome/yhalchen/datalad/datalad/tests/utils.py", line 593, in newfunc
    return t(*(arg + (filename,)), **kw)
  File "/ihome/yhalchen/datalad/datalad/tests/test_cmd.py", line 46, in test_runner_dry
    cml.assert_logged("{DryRunProtocol} Running: %s" % cmd, regex=False)
  File "/usr/local/lib/python3.5/dist-packages/datalad/utils.py", line 901, in assert_logged
    (assert_re_in if regex else assert_in)(match, self.out, **kwargs)
AssertionError: '{DryRunProtocol} Running: echo Testing dry run > /tmp/datalad_temp_test_runner_drytncihsv0' not found in ''

----------------------------------------------------------------------
Ran 506 tests in 1006.191s

FAILED (SKIP=42, errors=80, failures=3)


```
FWIW, PYTHONPATH is clean ... also seems to pick up system nose... I don't get it

it was ran as
```
./datalad-datalad-master-fullmaster.simg test 2>&1 | tee ./datalad-datalad-master-fullmaster.tests.log
```

**Comment by bpoldrack** [comment]
I'm running in the same trouble, I think. This is because - at least for PY2 - my setup is somewhat messed up: My local stuff is in `sys.path`:

```
% python -m site
sys.path = [
    '/tmp',
    '/usr/lib/python2.7',
    '/usr/lib/python2.7/plat-x86_64-linux-gnu',
    '/usr/lib/python2.7/lib-tk',
    '/usr/lib/python2.7/lib-old',
    '/usr/lib/python2.7/lib-dynload',
    '/home/ben/.local/lib/python2.7/site-packages',
    '/usr/local/lib/python2.7/dist-packages',
    '/home/ben/Development/datalad',
    '/usr/local/lib/python2.7/dist-packages/gitdb2-2.0.0-py2.7.egg',
    '/usr/local/lib/python2.7/dist-packages/GitPython-2.1.6-py2.7.egg',
    '/usr/lib/python2.7/dist-packages',
    '/usr/lib/python2.7/dist-packages/PILcompat',
    '/usr/lib/python2.7/dist-packages/gtk-2.0',
    '/usr/lib/pymodules/python2.7',
    '/usr/lib/python2.7/dist-packages/wx-3.0-gtk2',
]
USER_BASE: '/home/ben/.local' (exists)
USER_SITE: '/home/ben/.local/lib/python2.7/site-packages' (exists)
ENABLE_USER_SITE: True
```

While in PY3 it's not the case:

```
 % python3 -m site
sys.path = [
    '/tmp',
    '/usr/lib/python35.zip',
    '/usr/lib/python3.5',
    '/usr/lib/python3.5/plat-x86_64-linux-gnu',
    '/usr/lib/python3.5/lib-dynload',
    '/usr/local/lib/python3.5/dist-packages',
    '/usr/lib/python3/dist-packages',
]
USER_BASE: '/home/ben/.local' (exists)
USER_SITE: '/home/ben/.local/lib/python3.5/site-packages' (doesn't exist)
ENABLE_USER_SITE: True
```

This is all while having that `/home/ben/Development/datalad` not in PATH or PYTHONPATH and calling the above from withn `/tmp`.

Conclusion this is neither about datalad nor the container. I messed it up somehow ;-)

**Comment by mih** [comment]
I think this issue can be closed. We have a completely different approach to a test setup now, and such behavior has not been reported again over the past years.
