### ISSUE TITLE
tests failing at pkg build time on sid for 0.9.2

### ISSUE THREAD

**Issue by yarikoptic** [datalad/datalad#2259]
#### What is the problem?
FTR -- if any looks familiar (possibly fixed in master?) speak up ;)  I will checkmark those which I fixed up already

- [x] 1 
```
======================================================================
ERROR: datalad.distribution.tests.test_uninstall.test_drop_nocrash_absent_subds
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/usr/lib/python2.7/dist-packages/nose/case.py", line 197, in runTest
    self.test(*self.arg)
  File "/build/datalad-0.9.2/.pybuild/pythonX.Y_2.7/build/datalad/tests/utils.py", line 627, in newfunc
    return t(*(arg + (filename,)), **kw)
  File "/build/datalad-0.9.2/.pybuild/pythonX.Y_2.7/build/datalad/distribution/tests/test_uninstall.py", line 522, in test_drop_nocrash_absent_subds
    assert_status('notneeded', drop('.', recursive=True))
  File "/build/datalad-0.9.2/.pybuild/pythonX.Y_2.7/build/datalad/interface/utils.py", line 439, in eval_func
    return return_func(generator_func)(*args, **kwargs)
  File "/build/datalad-0.9.2/.pybuild/pythonX.Y_2.7/build/datalad/interface/utils.py", line 427, in return_func
    results = list(results)
  File "/build/datalad-0.9.2/.pybuild/pythonX.Y_2.7/build/datalad/interface/utils.py", line 384, in generator_func
    result_renderer, result_xfm, _result_filter, **_kwargs):
  File "/build/datalad-0.9.2/.pybuild/pythonX.Y_2.7/build/datalad/interface/utils.py", line 451, in _process_results
    for res in results:
  File "/build/datalad-0.9.2/.pybuild/pythonX.Y_2.7/build/datalad/distribution/drop.py", line 217, in __call__
    handle_dirty_dataset(ds, mode=if_dirty)
  File "/build/datalad-0.9.2/.pybuild/pythonX.Y_2.7/build/datalad/interface/utils.py", line 102, in handle_dirty_dataset
    raise RuntimeError('dataset {} is not yet installed'.format(ds))
RuntimeError: dataset <Dataset path=/tmp/datalad_temp_test_drop_nocrash_absent_subdsGPWxzh/sub> is not yet installed
```
- [x] 2 
```
======================================================================
FAIL: datalad.distribution.tests.test_uninstall.test_uninstall_without_super
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/usr/lib/python2.7/dist-packages/nose/case.py", line 197, in runTest
    self.test(*self.arg)
  File "/build/datalad-0.9.2/.pybuild/pythonX.Y_2.7/build/datalad/tests/utils.py", line 627, in newfunc
    return t(*(arg + (filename,)), **kw)
  File "/build/datalad-0.9.2/.pybuild/pythonX.Y_2.7/build/datalad/distribution/tests/test_uninstall.py", line 506, in test_uninstall_without_super
    assert_result_count(subreport, 1, path=sub.path, state='absent')
  File "/build/datalad-0.9.2/.pybuild/pythonX.Y_2.7/build/datalad/tests/utils.py", line 1185, in assert_result_count
    dumps(results, indent=1, default=lambda x: "<not serializable>")))
AssertionError: Got 0 instead of 1 expected results matching {'path': '/tmp/datalad_temp_test_uninstall_without_superRTZmYI/sub', 'state': 'absent'}. Inspected 1 record(s):
[
 {
  "status": "ok",
  "gitmodule_name": "sub",
  "parentds": "/tmp/datalad_temp_test_uninstall_without_superRTZmYI",
  "state": "clean",
  "revision_descr": "(null)",
  "gitmodule_url": "./sub",
  "action": "subdataset",
  "path": "/tmp/datalad_temp_test_uninstall_without_superRTZmYI/sub",
  "type": "dataset",
  "refds": "/tmp/datalad_temp_test_uninstall_without_superRTZmYI",
  "revision": "0e124f552526af66f8ba3f988ee007eb11a01a36"
 }
]
```
- [x]  3
```
======================================================================
FAIL: datalad.tests.test_base.test_git_config_fixture
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/usr/lib/python2.7/dist-packages/nose/case.py", line 197, in runTest
    self.test(*self.arg)
  File "/build/datalad-0.9.2/.pybuild/pythonX.Y_2.7/build/datalad/tests/test_base.py", line 45, in test_git_config_fixture
    'user.email': 'test@example.com'
AssertionError: {'user.name': 'TESTING', 'user.email': 'TESTING@example.com'} != {'user.name': 'DataLad Tester', 'user.email': 'test@example.com'}
- {'user.email': 'TESTING@example.com', 'user.name': 'TESTING'}
?                 ^^^^^^^                              ^^^^^^

+ {'user.email': 'test@example.com', 'user.name': 'DataLad Tester'}
?                 ^^^^                             ++++++++ ^^^^^

```

**Comment by yarikoptic** [comment]
not sure yet what causes 2:  in both cases (in pkg build and locally) output of command seems to be 
```
$> git --work-tree=. submodule status
 0ea39dd71d2fe238b4c4384a36fc160b1d678591 sub ((null))
```
so it should be `clean`, so need to figure out how it was expected to be "absent"

**Comment by yarikoptic** [comment]
2 is an "unpleasant" one:
```shell
$> git --work-tree=. submodule status
 a598723e834a7b6e12339efe6a62f0d788e54cd1 sub ((null))

$> /usr/lib/git-annex.linux/git --work-tree=. submodule status
-a598723e834a7b6e12339efe6a62f0d788e54cd1 sub

$> ls -la sub
total 8
drwx------ 2 yoh yoh 4096 Mar  3 21:25 ./
drwx------ 6 yoh yoh 4096 Mar  3 21:25 ../
```
and I think it is the system wide, which is also a newer one (and thus used on sid with regular build of git-annex), which is not right:
```
$> git --version
git version 2.16.2

$> /usr/lib/git-annex.linux/git --version
git version 2.11.0
```
and it is a "known" issue: https://github.com/datalad/datalad/issues/2089 , heh. I guess the new way to deal with submodules "resolved" it but now  I need to figure it out for older type of handling :-/

**Comment by yarikoptic** [comment]
resolved
- submodules listing: ab0306a10ace71ab7e593f062befd2042a468b50
- test for git config: 7f9f210a3c206dc364c382184b36e6195178d888
