### ISSUE TITLE
Robustify tests wrt to PY2 vs PY3

### ISSUE THREAD

**Issue by mih** [datalad/datalad#2287]
Below is a test that fails in our singularity image, because there is no PY2. Would be could to not require that. @kyleam ?

```
======================================================================
ERROR: datalad.interface.tests.test_run.test_rerun_subdir
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/usr/local/lib/python3.5/dist-packages/datalad/interface/run.py", line 173, in run_command
    expect_fail=True,
  File "/usr/local/lib/python3.5/dist-packages/datalad/cmd.py", line 520, in run
    raise CommandError(str(cmd), msg, status, out[0], out[1])
datalad.support.exceptions.CommandError: CommandError: command 'python -c 'open("test.dat", "wb").close()'' failed with exitcode 127
Failed to run 'python -c \'open("test.dat", "wb").close()\'' under '/tmp/datalad_temp_test_rerun_subdir7r6913gm/subdir'. Exit code=127. out= err=

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/lib/python3.5/dist-packages/nose/case.py", line 198, in runTest
    self.test(*self.arg)
  File "/usr/local/lib/python3.5/dist-packages/datalad/tests/utils.py", line 1290, in newfunc
    func(*args, **kwargs)
  File "/usr/local/lib/python3.5/dist-packages/datalad/tests/utils.py", line 664, in newfunc
    return t(*(arg + (filename,)), **kw)
  File "/usr/local/lib/python3.5/dist-packages/datalad/interface/tests/test_run.py", line 408, in test_rerun_subdir
    run("python -c 'open(\"test.dat\", \"wb\").close()'")
  File "/usr/local/lib/python3.5/dist-packages/wrapt/wrappers.py", line 523, in __call__
    args, kwargs)
  File "/usr/local/lib/python3.5/dist-packages/datalad/interface/utils.py", line 466, in eval_func
    return return_func(generator_func)(*args, **kwargs)
  File "/usr/local/lib/python3.5/dist-packages/wrapt/wrappers.py", line 523, in __call__
    args, kwargs)
  File "/usr/local/lib/python3.5/dist-packages/datalad/interface/utils.py", line 454, in return_func
    results = list(results)
  File "/usr/local/lib/python3.5/dist-packages/datalad/interface/utils.py", line 411, in generator_func
    result_renderer, result_xfm, _result_filter, **_kwargs):
  File "/usr/local/lib/python3.5/dist-packages/datalad/interface/utils.py", line 478, in _process_results
    for res in results:
  File "/usr/local/lib/python3.5/dist-packages/datalad/interface/run.py", line 100, in __call__
    for r in run_command(cmd, dataset, message):
  File "/usr/local/lib/python3.5/dist-packages/datalad/interface/run.py", line 193, in run_command
    raise CommandError(code=cmd_exitcode)
datalad.support.exceptions.CommandError: CommandError:  failed with exitcode 127
```

**Comment by kyleam** [comment]
Yeah, there's no reason to assume that an executable named "python" is present.

**Comment by kyleam** [comment]
And one of the py3.5 builds seems to consistently have rerun tests [failures](https://travis-ci.org/datalad/datalad/builds/350683078):

```
ERROR: datalad.interface.tests.test_run.test_rerun_subdir
ERROR: datalad.interface.tests.test_run.test_rerun
ERROR: datalad.interface.tests.test_run.test_rerun_ambiguous_revision_file
ERROR: datalad.interface.tests.test_run.test_rerun_branch
ERROR: datalad.interface.tests.test_run.test_rerun_chain
ERROR: datalad.interface.tests.test_run.test_rerun_cherry_pick
ERROR: datalad.interface.tests.test_run.test_rerun_just_one_commit
ERROR: datalad.interface.tests.test_run.test_rerun_old_flag_compatibility
ERROR: datalad.interface.tests.test_run.test_rerun_onto
ERROR: datalad.interface.tests.test_run.test_rerun_outofdate_tree
```

All of the errors look something like

```
======================================================================
ERROR: datalad.interface.tests.test_run.test_rerun
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/travis/virtualenv/python3.5.5/lib/python3.5/site-packages/nose/case.py", line 198, in runTest
    self.test(*self.arg)
  File "/home/travis/build/datalad/datalad/datalad/tests/utils.py", line 1290, in newfunc
    func(*args, **kwargs)
  File "/home/travis/build/datalad/datalad/datalad/tests/utils.py", line 893, in newfunc
    return func(*args, **kwargs)
  File "/home/travis/build/datalad/datalad/datalad/tests/utils.py", line 664, in newfunc
    return t(*(arg + (filename,)), **kw)
  File "/home/travis/build/datalad/datalad/datalad/tests/utils.py", line 664, in newfunc
    return t(*(arg + (filename,)), **kw)
  File "/home/travis/build/datalad/datalad/datalad/interface/tests/test_run.py", line 141, in test_rerun
    ds.rerun(revision="HEAD~", message="rerun buried")
  File "/home/travis/virtualenv/python3.5.5/lib/python3.5/site-packages/wrapt/wrappers.py", line 562, in __call__
    args, kwargs)
  File "/home/travis/build/datalad/datalad/datalad/distribution/dataset.py", line 437, in apply_func
    return f(**kwargs)
  File "/home/travis/virtualenv/python3.5.5/lib/python3.5/site-packages/wrapt/wrappers.py", line 523, in __call__
    args, kwargs)
  File "/home/travis/build/datalad/datalad/datalad/interface/utils.py", line 466, in eval_func
    return return_func(generator_func)(*args, **kwargs)
  File "/home/travis/virtualenv/python3.5.5/lib/python3.5/site-packages/wrapt/wrappers.py", line 523, in __call__
    args, kwargs)
  File "/home/travis/build/datalad/datalad/datalad/interface/utils.py", line 454, in return_func
    results = list(results)
  File "/home/travis/build/datalad/datalad/datalad/interface/utils.py", line 411, in generator_func
    result_renderer, result_xfm, _result_filter, **_kwargs):
  File "/home/travis/build/datalad/datalad/datalad/interface/utils.py", line 478, in _process_results
    for res in results:
  File "/home/travis/build/datalad/datalad/datalad/interface/rerun.py", line 267, in __call__
    rerun_info=rev.info):
  File "/home/travis/build/datalad/datalad/datalad/interface/run.py", line 173, in run_command
    expect_fail=True,
  File "/home/travis/build/datalad/datalad/datalad/cmd.py", line 476, in run
    stdin=stdin)
  File "/opt/python/3.5.5/lib/python3.5/subprocess.py", line 640, in __init__
    errread, errwrite) = self._get_handles(stdin, stdout, stderr)
  File "/opt/python/3.5.5/lib/python3.5/subprocess.py", line 1137, in _get_handles
    c2pwrite = stdout.fileno()
io.UnsupportedOperation: fileno
```

**Comment by mih** [comment]
@bpoldrack was looking into those -- not sure what the verdict was...

**Comment by yarikoptic** [comment]
I think an initial issue was handled, and now there is @2359 dedicated to `fileno` issue
