### ISSUE TITLE
buildbots test_addurls_metafail - IncompleteResultsError not raised

### ISSUE THREAD

**Issue by yarikoptic** [datalad/datalad#2298]
#### What is the problem?
see eg at the bottom of http://smaug.datalad.org:8020/builders/datalad-pr-docker-dl-nd16_04/builds/2238/steps/nosetests/logs/stdio
```
======================================================================
FAIL: datalad.plugin.tests.test_addurls.TestAddurls.test_addurls_metafail
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/usr/lib/python2.7/dist-packages/nose/case.py", line 197, in runTest
    self.test(*self.arg)
  File "/home/buildbot/datalad-pr-docker-dl-nd16_04/build/datalad/tests/utils.py", line 664, in newfunc
    return t(*(arg + (filename,)), **kw)
  File "/home/buildbot/datalad-pr-docker-dl-nd16_04/build/datalad/plugin/tests/test_addurls.py", line 493, in test_addurls_metafail
    ds.addurls(self.json_file, "{url}", "{name}")
AssertionError: IncompleteResultsError not raised
```
failed to reproduce locally so far :-/

**Comment by yarikoptic** [comment]
it was due to an outdated (we had 201702.. version) annex which didn't fail on command
```shell
git annex metadata --json --debug -s bla+=blah -- nonex
```
meanwhile -- updating git-annex on all the buildbots and this issue will be resolved by demanding current git-annex version (would be good anyway)

**Comment by yarikoptic** [comment]
I will close this one since we figured it out and eventually will probably just raise required git-annex so it would be 'handled'
