### ISSUE TITLE
test_basic_aggregate: json.decoder.JSONDecodeError: Extra data: line 1 column 166 (char 165)

### ISSUE THREAD

**Issue by yarikoptic** [datalad/datalad#2301]
#### What is the problem?
Happened (or may be regularly) in that heavy debug mode matrix run (only):
https://travis-ci.org/datalad/datalad/jobs/353137426

```
======================================================================
ERROR: datalad.metadata.tests.test_aggregation.test_basic_aggregate
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/travis/virtualenv/python3.5.5/lib/python3.5/site-packages/nose/case.py", line 198, in runTest
    self.test(*self.arg)
  File "/home/travis/build/datalad/datalad/datalad/tests/utils.py", line 494, in newfunc
    return t(*(arg + (d,)), **kw)
  File "/home/travis/build/datalad/datalad/datalad/tests/utils.py", line 905, in newfunc
    return func(*args, **kwargs)
  File "/home/travis/build/datalad/datalad/datalad/tests/utils.py", line 1057, in newfunc
    return func(*args, **kwargs)
  File "/home/travis/build/datalad/datalad/datalad/metadata/tests/test_aggregation.py", line 67, in test_basic_aggregate
    base.aggregate_metadata(recursive=True)
  File "/home/travis/virtualenv/python3.5.5/lib/python3.5/site-packages/wrapt/wrappers.py", line 562, in __call__
    args, kwargs)
  File "/home/travis/build/datalad/datalad/datalad/distribution/dataset.py", line 436, in apply_func
    return f(**kwargs)
  File "/home/travis/virtualenv/python3.5.5/lib/python3.5/site-packages/wrapt/wrappers.py", line 523, in __call__
    args, kwargs)
  File "/home/travis/build/datalad/datalad/datalad/interface/utils.py", line 470, in eval_func
    return return_func(generator_func)(*args, **kwargs)
  File "/home/travis/virtualenv/python3.5.5/lib/python3.5/site-packages/wrapt/wrappers.py", line 523, in __call__
    args, kwargs)
  File "/home/travis/build/datalad/datalad/datalad/interface/utils.py", line 458, in return_func
    results = list(results)
  File "/home/travis/build/datalad/datalad/datalad/interface/utils.py", line 414, in generator_func
    result_renderer, result_xfm, _result_filter, **_kwargs):
  File "/home/travis/build/datalad/datalad/datalad/interface/utils.py", line 482, in _process_results
    for res in results:
  File "/home/travis/build/datalad/datalad/datalad/metadata/aggregate.py", line 732, in __call__
    to_save)
  File "/home/travis/build/datalad/datalad/datalad/metadata/aggregate.py", line 472, in _update_ds_agginfo
    save=False, result_renderer=None, return_type=list)
  File "/home/travis/virtualenv/python3.5.5/lib/python3.5/site-packages/wrapt/wrappers.py", line 562, in __call__
    args, kwargs)
  File "/home/travis/build/datalad/datalad/datalad/distribution/dataset.py", line 436, in apply_func
    return f(**kwargs)
  File "/home/travis/virtualenv/python3.5.5/lib/python3.5/site-packages/wrapt/wrappers.py", line 523, in __call__
    args, kwargs)
  File "/home/travis/build/datalad/datalad/datalad/interface/utils.py", line 470, in eval_func
    return return_func(generator_func)(*args, **kwargs)
  File "/home/travis/virtualenv/python3.5.5/lib/python3.5/site-packages/wrapt/wrappers.py", line 523, in __call__
    args, kwargs)
  File "/home/travis/build/datalad/datalad/datalad/interface/utils.py", line 458, in return_func
    results = list(results)
  File "/home/travis/build/datalad/datalad/datalad/interface/utils.py", line 414, in generator_func
    result_renderer, result_xfm, _result_filter, **_kwargs):
  File "/home/travis/build/datalad/datalad/datalad/interface/utils.py", line 482, in _process_results
    for res in results:
  File "/home/travis/build/datalad/datalad/datalad/distribution/add.py", line 424, in __call__
    **add_kw
  File "/home/travis/build/datalad/datalad/datalad/support/gitrepo.py", line 300, in newfunc
    result = func(self, files_new, *args, **kwargs)
  File "/home/travis/build/datalad/datalad/datalad/support/annexrepo.py", line 1535, in add
    expect_stderr=True
  File "/home/travis/build/datalad/datalad/datalad/support/annexrepo.py", line 2394, in _run_annex_command_json
    json_objects = [j for j in json_objects if 'byte-progress' not in j]
  File "/home/travis/build/datalad/datalad/datalad/support/annexrepo.py", line 2394, in <listcomp>
    json_objects = [j for j in json_objects if 'byte-progress' not in j]
  File "/home/travis/build/datalad/datalad/datalad/support/annexrepo.py", line 2392, in <genexpr>
    for line in out.splitlines() if line.startswith('{'))
  File "/opt/python/3.5.5/lib/python3.5/json/__init__.py", line 319, in loads
    return _default_decoder.decode(s)
  File "/opt/python/3.5.5/lib/python3.5/json/decoder.py", line 342, in decode
    raise JSONDecodeError("Extra data", s, end)
json.decoder.JSONDecodeError: Extra data: line 1 column 166 (char 165)
-------------------- >> begin captured logging << --------------------
```

**Comment by mih** [comment]
Please see #2326 for a related RF.

**Comment by yarikoptic** [comment]
ok -- caught it thanks to added recentish more logging:
https://api.travis-ci.org/v3/job/359910159/log.txt

```
simplejson.errors.JSONDecodeError: Extra data: line 1 column 166 - line 1 column 328 (char 165 - 327)
...
datalad.cmd: Level 8: ...>cmd:664,523,578>handlers:73  Finished running ['git', '-c', 'receive.autogc=0', '-c', 'gc.auto=0', 'annex', 'add', '--debug', '--json', '--', '.datalad/metadata/objects/16/ds-e67ee59a218533e3364760936efd44', '.datalad/metadata/objects/93/ds-fd5bd806f9ee64d7b175e9407e938f', '.datalad/metadata/objects/6d/cn-2afdf89480065720dd2b4028d067b7.xz', '.datalad/metadata/objects/93/cn-fd5bd806f9ee64d7b175e9407e938f.xz', '.datalad/metadata/objects/16/cn-e67ee59a218533e3364760936efd44.xz', '.datalad/metadata/objects/6d/ds-2afdf89480065720dd2b4028d067b7'] with status 0
datalad: ERROR: ...>annexrepo:1541,2402,2402,2400>json_py:94>handlers:73  Failed to load content from '{"command":"add","note":"non-large file; adding content to git repository","success":true,"file":".datalad/metadata/objects/16/cn-e67ee59a218533e3364760936efd44.xz"}{"command":"add","note":"non-large file; adding content to git repository","success":true,"file":".datalad/metadata/objects/6d/ds-2afdf89480065720dd2b4028d067b7"}' with args=() kwargs={}
```
so somehow it looks like multiple json records got printed/read into a single line.... I wonder how that could have happened... ?

**Comment by yarikoptic** [comment]
@joeyh  is there any chance/way that `git annex add --json --debug -- bunch of files` would return multiple json records in a single line?

**Comment by joeyh** [comment]
Yaroslav Halchenko wrote:
> @joeyh is there any chance/way that git annex add --json --debug -- bunch of
> files would return multiple json records in a single line?

It should always be one json record per line, and one record per file.

Otherwise we'd have to deal with complex partial serialization of
incomplete json records while processing the set of files.

-- 
see shy jo
