### ISSUE TITLE
test_run.py:test_rerun_branch - AssertionError: Got 2 instead of 3 expected results matching {}

### ISSUE THREAD

**Issue by yarikoptic** [datalad/datalad#2307]
#### What is the problem?

I first encountered it while working on #2305 but then saw that it fails on 0.9.x.  It might be due to me locally trying super-fresh git-annex but I thought that tests did pass for it yesterday

```shell
$> DATALAD_TESTS_SSH=1 python -m nose -s -v datalad/interface/tests/test_run.py:test_rerun_branch
datalad.interface.tests.test_run.test_rerun_branch ... cat: run-file: No such file or directory
cat: run-file: No such file or directory
FAIL
Versions: appdirs=1.4.3 boto=2.44.0 cmd:annex=6.20180314+gitg10d3b7fc6-1~ndall+1 cmd:git=2.16.2 cmd:system-git=2.16.2 cmd:system-ssh=7.6p1 git=2.1.8 gitdb=2.0.3 humanize=0.5.1 iso8601=0.1.11 msgpack=0.5.5 requests=2.18.4 scrapy=1.5.0 six=1.11.0 tqdm=4.19.5 wrapt=1.10.11

======================================================================
FAIL: datalad.interface.tests.test_run.test_rerun_branch
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/usr/lib/python2.7/dist-packages/nose/case.py", line 197, in runTest
    self.test(*self.arg)
  File "/home/yoh/proj/datalad/datalad/datalad/tests/utils.py", line 1240, in newfunc
    func(*args, **kwargs)
  File "/home/yoh/proj/datalad/datalad/datalad/tests/utils.py", line 856, in newfunc
    return func(*args, **kwargs)
  File "/home/yoh/proj/datalad/datalad/datalad/tests/utils.py", line 627, in newfunc
    return t(*(arg + (filename,)), **kw)
  File "/home/yoh/proj/datalad/datalad/datalad/interface/tests/test_run.py", line 316, in test_rerun_branch
    ds.repo.repo.git.rev_list(revrange).split(), 3)
  File "/home/yoh/proj/datalad/datalad/datalad/tests/utils.py", line 1185, in assert_result_count
    dumps(results, indent=1, default=lambda x: "<not serializable>")))
AssertionError: Got 2 instead of 3 expected results matching {}. Inspected 2 record(s):
[
 "e707b5a4a317788a42c54f442577ebd3786eb420", 
 "df9895b835c6dfff2cdcaea361aa6feac1fe9cc8"
]
-------------------- >> begin captured logging << --------------------
datalad.utils: Level 5: Importing datalad.utils
datalad.utils: Level 5: Done importing datalad.utils
datalad.cmd: Level 9: Will use git under '/usr/lib/git-annex.linux' (no adjustments to PATH if empty string)
datalad.cmd: Level 9: Running: ['git', 'version']
datalad.cmd: Level 8: Finished running ['git', 'version'] with status 0
datalad.cmd: Level 9: Running: ['git', 'config', '-z', '-l', '--show-origin']
datalad.cmd: Level 8: Finished running ['git', 'config', '-z', '-l', '--show-origin'] with status 0
datalad.ui: Level 5: Starting importing ui
datalad.ui.dialog: Level 5: Starting importing ui.dialog
datalad.ui.dialog: Level 5: Done importing ui.dialog
datalad.ui: Level 5: Initiating UI switcher
datalad.ui: DEBUG: UI set to DialogUI(out=<file>)
datalad.ui: Level 5: Done importing ui
--------------------- >> end captured logging << ---------------------
```
just documenting for now - yet to dig in

**Comment by yarikoptic** [comment]
ha ha ha -- might as well be due to me reusing that shell where I was torturing things for #2306 which I didn't check yet about the failures it leads to
```shell
$> export | grep GIT
GIT_AUTHOR_DATE='Thu, 07 Apr 2005 22:13:13 +0200'
GIT_AUTHOR_EMAIL=committer@example.com
GIT_AUTHOR_NAME=blah
GIT_COMMITTER_DATE='Thu, 07 Apr 2005 22:13:13 +0200'
GIT_COMMITTER_EMAIL=committer@example.com
GIT_COMMITTER_NAME=blah
GIT_COMMITTER_NEMA=blah_committer
GIT_PAGER='less --no-init --quit-if-one-screen'
```
and yes  passes in a cleaner shell, thus closing for now
