### ISSUE TITLE
search -- too many open files

### ISSUE THREAD

**Issue by yarikoptic** [datalad/datalad#2316]
#### What is the problem?
```shell
(git)smaug:~/datalad-meta6-4[master]
$> datalad search --mode autofield bids.participant.sex:female bids.participant.age(years):'[19 TO 26]' bids.type:t1w
[INFO   ] Building search index
[INFO   ] Actually getting 489 files
                                                                                                                [INFO   ] Actually getting 389 files
Datasets: 100%|████████████████████████████████████████████████████████████████| 514/514 [17:46<00:00, 5.41ds/s][ERROR  ] [Errno 24] Too many open files: u'/home/yoh/datalad-meta6-4/.git/datalad/search_index/autofield/MAIN_vp5ntuv5ltjp9nts._exif.GPSLatitudeRef_len.col' [filestore.py:open_file:504] (IOError)
````
There is indeed some garballed output due to progressbars and parallel downloads.

#### What version of DataLad are you using (run `datalad --version`)? On what operating system (consider running `datalad wtf`)?

This was done using 781ae6f4c9c3116fe713a06db339e40532dbdcd7  which I will push shortly into #2309 : it was the one with merges from 0.9.x but also with autoenabling of parallel downloads to speed up fetching all the metadata, which it did like a pro ;)

**Comment by mih** [comment]
Hmm, haven't seen this yet, cannot reproduce on my code. So it seems that some change that was introduced recently is breaking some things. Maybe autoenabling parallel downloads isn't such a good thing if it leads to this situation?

**Comment by yarikoptic** [comment]
not sure if that was autoenable of parallel downloads -- it shouldn't have effect (parallelization is happening at the level of annex, not datalad).  Would you mind trying on fresh master?  I will try now as well

**Comment by yarikoptic** [comment]
reproduced locally and on smaug on a rerun so I guess no files were `get`ed at all... rerunning with `DATALAD_EXC_STR_TBLIMIT=100 datalad --dbg` to see if I could catch at least the moment and see what open files we have... ATM I do not see any many files being open:
```
$> pstree -p 1679995
datalad(1679995)───{datalad}(1698412)
(dev)2 18931.....................................:Mon 19 Mar 2018 12:48:06 PM EDT:.
smaug:/mnt/btrfs/scrap/tmp
$> ls -l /proc/1679995/fd
total 0
lrwx------ 1 yoh yoh 64 Mar 19 12:48 0 -> /dev/pts/13
lrwx------ 1 yoh yoh 64 Mar 19 12:48 1 -> /dev/pts/13
lrwx------ 1 yoh yoh 64 Mar 19 12:48 2 -> /dev/pts/13
l-wx------ 1 yoh yoh 64 Mar 19 12:48 3 -> /home/yoh/datalad-meta6-4/.git/datalad/search_index/autofield/MAIN_WRITELOCK*
lrwx------ 1 yoh yoh 64 Mar 19 12:48 4 -> /home/yoh/datalad-meta6-4/.git/datalad/search_index/autofield/MAIN.tmp/v36mq2alpv9cqxkzupn92xvs8uhd.ctmp
l-wx------ 1 yoh yoh 64 Mar 19 12:48 5 -> /home/yoh/datalad-meta6-4/.git/datalad/search_index/autofield/MAIN_iu2aasnuisepcoxr.trm
l-wx------ 1 yoh yoh 64 Mar 19 12:48 6 -> /home/yoh/datalad-meta6-4/.git/datalad/search_index/autofield/MAIN_iu2aasnuisepcoxr.pst
lr-x------ 1 yoh yoh 64 Mar 19 12:48 7 -> /dev/urandom
(dev)2 18932.....................................:Mon 19 Mar 2018 12:48:13 PM EDT:.
smaug:/mnt/btrfs/scrap/tmp
$> ls -l /proc/1698412/fd
total 0
lrwx------ 1 yoh yoh 64 Mar 19 12:48 0 -> /dev/pts/13
lrwx------ 1 yoh yoh 64 Mar 19 12:48 1 -> /dev/pts/13
lrwx------ 1 yoh yoh 64 Mar 19 12:48 2 -> /dev/pts/13
l-wx------ 1 yoh yoh 64 Mar 19 12:48 3 -> /home/yoh/datalad-meta6-4/.git/datalad/search_index/autofield/MAIN_WRITELOCK*
lrwx------ 1 yoh yoh 64 Mar 19 12:48 4 -> /home/yoh/datalad-meta6-4/.git/datalad/search_index/autofield/MAIN.tmp/v36mq2alpv9cqxkzupn92xvs8uhd.ctmp
l-wx------ 1 yoh yoh 64 Mar 19 12:48 5 -> /home/yoh/datalad-meta6-4/.git/datalad/search_index/autofield/MAIN_iu2aasnuisepcoxr.trm
l-wx------ 1 yoh yoh 64 Mar 19 12:48 6 -> /home/yoh/datalad-meta6-4/.git/datalad/search_index/autofield/MAIN_iu2aasnuisepcoxr.pst
lr-x------ 1 yoh yoh 64 Mar 19 12:48 7 -> /dev/urandom
```

**Comment by yarikoptic** [comment]
failed miserably, probably because could not open just few more files:
```
()
Error in sys.excepthook:
Traceback (most recent call last):
  File "/home/yoh/proj/datalad/datalad-master/datalad/utils.py", line 987, in _datalad_pdb_excepthook
ImportError: No module named pdb

Original exception was:
Traceback (most recent call last):
  File "/home/yoh/proj/datalad/datalad-master/venvs/dev/bin/datalad", line 8, in <module>
  File "/home/yoh/proj/datalad/datalad-master/datalad/cmdline/main.py", line 366, in main
  File "/home/yoh/proj/datalad/datalad-master/datalad/interface/base.py", line 420, in call_from_parser
  File "/home/yoh/proj/datalad/datalad-master/datalad/interface/utils.py", line 414, in generator_func
  File "/home/yoh/proj/datalad/datalad-master/datalad/interface/utils.py", line 482, in _process_results
  File "/home/yoh/proj/datalad/datalad-master/datalad/metadata/search.py", line 829, in __call__
  File "/home/yoh/proj/datalad/datalad-master/datalad/metadata/search.py", line 246, in __init__
  File "/home/yoh/proj/datalad/datalad-master/datalad/metadata/search.py", line 413, in _mk_search_index
  File "/home/yoh/proj/datalad/datalad-master/venvs/dev/local/lib/python2.7/site-packages/whoosh/writing.py", line 927, in commit
  File "/home/yoh/proj/datalad/datalad-master/venvs/dev/local/lib/python2.7/site-packages/whoosh/writing.py", line 866, in _finalize_segment
  File "/home/yoh/proj/datalad/datalad-master/venvs/dev/local/lib/python2.7/site-packages/whoosh/writing.py", line 836, in _flush_segment
  File "/home/yoh/proj/datalad/datalad-master/venvs/dev/local/lib/python2.7/site-packages/whoosh/codec/base.py", line 228, in add_postings
  File "/home/yoh/proj/datalad/datalad-master/venvs/dev/local/lib/python2.7/site-packages/whoosh/codec/whoosh3.py", line 422, in doc_field_length
  File "/home/yoh/proj/datalad/datalad-master/venvs/dev/local/lib/python2.7/site-packages/whoosh/codec/whoosh3.py", line 412, in _cached_reader
  File "/home/yoh/proj/datalad/datalad-master/venvs/dev/local/lib/python2.7/site-packages/whoosh/codec/whoosh3.py", line 399, in column_reader
  File "/home/yoh/proj/datalad/datalad-master/venvs/dev/local/lib/python2.7/site-packages/whoosh/codec/whoosh3.py", line 394, in _get_column_file
  File "/home/yoh/proj/datalad/datalad-master/venvs/dev/local/lib/python2.7/site-packages/whoosh/filedb/filestore.py", line 504, in open_file
IOError: [Errno 24] Too many open files: u'/home/yoh/datalad-meta6-4/.git/datalad/search_index/autofield/MAIN_iu2aasnuisepcoxr._exif.GPSLatitudeRef_len.col'
DATALAD_EXC_STR_TBLIMIT=100 datalad --dbg search --mode autofield     1253.89s user 7.97s system 99% cpu 21:12.39 total
```
and it suggests that it is due to an issue with whoosh and having all those autofield files getting opened at the same time? (I see 3583 files in that autofield/ directory)

**Comment by yarikoptic** [comment]
ok, confirmed (after I preimported pdb) -- process has over 1k open of those .col files which is what I guess drives it down for me

**Comment by yarikoptic** [comment]
I am stopping exploring this on my end since my whoosh knowledge is absent and it would be more efficient if troubleshooted/addressed one way or another by a more knowledgeable person.  Again -- I have replicated it on smaug happen someone needs a system for that.

**Comment by mih** [comment]
I will propose a PR that takes all this functionality out.

**Comment by mih** [comment]
Please see #2326 for a related RF.

**Comment by yarikoptic** [comment]
Resolution so far was to raise default limits on a linux system on the number of opened files:
```shell
$> grep nofile /etc/security/limits.conf 
#        - nofile - max number of open files
yoh 		 - 	 nofile 	 16384
```
(`yoh` is me, could be a `*` if for everyone) which also required reboot to get into effect.  After that I was able to build the index.  Ideally this should not be needed (either incremental index construction or seeking internal to whoosh fixup avoiding opening so many files at once) so I will leave it open but will remove from 0.10.0 milestone

**Comment by yarikoptic** [comment]
FWIW, I saw similar problem with recentish (0.12.2?) installation of datalad via conda on some mac air.   Unfortunately I didn't have a chance to troubleshoot/get more information at that point, and attempts to reproduce on another box didn't "succeed". 

original invocation (bids metadata has changed) doesn't fail for me ATM (under some test user) even though also doesn't return any hits:
```
test@smaug:~$ datalad search --mode autofield 'bids.subject.age(years):[19 TO 26]'
It is highly recommended to configure Git before using DataLad. Set both 'user.name' and 'user.email' configuration variables.
It is highly recommended to configure Git before using DataLad. Set both 'user.name' and 'user.email' configuration variables.
No DataLad dataset found at current location
Would you like to install the DataLad superdataset at '/home/test/datalad'? (choices: yes, no): yes

[INFO   ]                                                                                                                                  
[INFO   ] *** Please tell me who you are. 
[INFO   ]  
[INFO   ] Run 
[INFO   ]  
[INFO   ]   git config --global user.email "you@example.com" 
[INFO   ]   git config --global user.name "Your Name" 
[INFO   ] to set your account's default identity. 
[INFO   ] Omit --global to set the identity only in this repository. 
[INFO   ] fatal: empty ident name (for <test@smaug.datalad.org>) not allowed 
From now on you can refer to this dataset using the label '///'
[INFO   ] Performing search using DataLad superdataset '/home/test/datalad' 
[INFO   ] no hits                                                                                                                          
test@smaug:~$ datalad --version
It is highly recommended to configure Git before using DataLad. Set both 'user.name' and 'user.email' configuration variables.
It is highly recommended to configure Git before using DataLad. Set both 'user.name' and 'user.email' configuration variables.
datalad 0.12.2
```

and In my case now (no changes to limits AFAIK) I have not experienced this issue for awhile, we also had chased many open files issues away, so I will close it for now.

**Comment by yarikoptic** [comment]
ok , reproduced this issue and filed [an initial report against git-annex](https://git-annex.branchable.com/bugs/get_-J8_on_OSX_leads_to_git-annex__58___git__58___createProcess__58___runInteractiveProcess__58___pipe__58___resource_exhausted___40__Too_many_open_files__41__/?updated) . Since issue is not caused by datalad this issue could RiP closed.
