### ISSUE TITLE
(Singularity) test failures due to configuration

### ISSUE THREAD

**Issue by mih** [datalad/datalad#2320]
Only two failures remaining for me when testing todays singularity image. FTR:
```
======================================================================
ERROR: datalad.plugin.tests.test_metadata.test_error
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/usr/local/lib/python3.5/dist-packages/nose/case.py", line 198, in runTest
    self.test(*self.arg)
  File "/usr/local/lib/python3.5/dist-packages/datalad/tests/utils.py", line 664, in newfunc
    return t(*(arg + (filename,)), **kw)
  File "/usr/local/lib/python3.5/dist-packages/datalad/plugin/tests/test_metadata.py", line 39, in test_error
    files=[testpath])
  File "/usr/local/lib/python3.5/dist-packages/wrapt/wrappers.py", line 523, in __call__
    args, kwargs)
  File "/usr/local/lib/python3.5/dist-packages/datalad/interface/utils.py", line 470, in eval_func
    return return_func(generator_func)(*args, **kwargs)
  File "/usr/local/lib/python3.5/dist-packages/wrapt/wrappers.py", line 523, in __call__
    args, kwargs)
  File "/usr/local/lib/python3.5/dist-packages/datalad/interface/utils.py", line 458, in return_func
    results = list(results)
  File "/usr/local/lib/python3.5/dist-packages/datalad/interface/utils.py", line 414, in generator_func
    result_renderer, result_xfm, _result_filter, **_kwargs):
  File "/usr/local/lib/python3.5/dist-packages/datalad/interface/utils.py", line 482, in _process_results
    for res in results:
  File "/usr/local/lib/python3.5/dist-packages/datalad/plugin/extract_metadata.py", line 90, in __call__
    paths=files)
  File "/usr/local/lib/python3.5/dist-packages/datalad/metadata/metadata.py", line 443, in _get_metadata
    package=extractors.__package__)
  File "/usr/lib/python3.5/importlib/__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 986, in _gcd_import
  File "<frozen importlib._bootstrap>", line 969, in _find_and_load
  File "<frozen importlib._bootstrap>", line 956, in _find_and_load_unlocked
ImportError: No module named 'datalad.metadata.extractors.bogus__'

======================================================================
FAIL: datalad.tests.test_config.test_something
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/usr/local/lib/python3.5/dist-packages/nose/case.py", line 198, in runTest
    self.test(*self.arg)
  File "/usr/local/lib/python3.5/dist-packages/datalad/tests/utils.py", line 494, in newfunc
    return t(*(arg + (d,)), **kw)
  File "/usr/local/lib/python3.5/dist-packages/datalad/tests/utils.py", line 664, in newfunc
    return t(*(arg + (filename,)), **kw)
  File "/usr/local/lib/python3.5/dist-packages/datalad/tests/test_config.py", line 56, in test_something
    assert_false(len(cfg))
AssertionError: 1 is not false

----------------------------------------------------------------------
Ran 857 tests in 3021.078s

FAILED (SKIP=76, errors=1, failures=1)
datalad -c datalad.runtime.raiseonerror=yes test -v  635.89s user 1094.34s system 57% cpu 50:26.32 total
```

Both are an artifact of me running it is `datalad -c datalad.runtime.raiseonerror=yes ...`, which clearly should make the cfg non empty, and also causes the test of a bogus extractor import to blow up and not just error calmly.

Suggestions on how these tests could be made more robust? In general using to flag by default would help debugging test failures, as it will point to the true source of an issue.

**Comment by yarikoptic** [comment]
The config setting triggered my attention as well when I saw original post on the email - isn't it intended only for debugging? We could make setup_module fixture reset it for the duration of the tests

**Comment by yarikoptic** [comment]
as shown in #4458 these tests seems no longer fail, so closing
