### ISSUE TITLE
test_is_available fails sometimes in the heavy debug output matrix

### ISSUE THREAD

**Issue by yarikoptic** [datalad/datalad#2330]
#### What is the problem?
```
ERROR: datalad.support.tests.test_annexrepo.test_is_available(True, False)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/travis/virtualenv/python3.5.5/lib/python3.5/site-packages/nose/case.py", line 198, in runTest
    self.test(*self.arg)
  File "/home/travis/build/datalad/datalad/datalad/tests/utils.py", line 836, in newfunc
    t(*(arg + (uri,)), **kw)
  File "/home/travis/build/datalad/datalad/datalad/support/tests/test_annexrepo.py", line 1354, in test_is_available
    assert_false(is_available("boguskey", key=True))
  File "/home/travis/build/datalad/datalad/datalad/support/gitrepo.py", line 297, in newfunc
    for f in files_new
  File "/home/travis/build/datalad/datalad/datalad/support/gitrepo.py", line 297, in <listcomp>
    for f in files_new
  File "/home/travis/build/datalad/datalad/datalad/support/annexrepo.py", line 2853, in is_available
    "Received output %r from annex, whenever expect 0 or 1" % out
ValueError: Received output None from annex, whenever expect 0 or 1
```
from https://travis-ci.org/datalad/datalad/jobs/356874244 

It kept coming I believe so we should track it down what is going available?

more info about env:
```
$ export BOTO_CONFIG=/tmp/nowhere
$ export DATALAD_TESTS_SSH=1
$ export DATALAD_LOG_CMD_ENV=GIT_SSH_COMMAND
$ export TESTS_TO_PERFORM=
$ export NOSE_OPTS=-s
$ export NOSE_SELECTION_OP="not "
$ export COVERAGE=coverage
$ export DATALAD_DATASETS_TOPURL=http://datasets-tests.datalad.org
$ export DATALAD_LOG_LEVEL=2
$ export DATALAD_LOG_TARGET=/dev/null
$ export DATALAD_LOG_TRACEBACK=collide
$ export DATALAD_TESTS_PROTOCOLREMOTE=1
$ export DATALAD_TESTS_DATALADREMOTE=1
$ export DATALAD_LOG_CMD_CWD=1
$ export DATALAD_LOG_CMD_OUTPUTS=1
$ export DATALAD_LOG_CMD_ENV=1
$ export DATALAD_LOG_CMD_STDIN=1
$ export DATALAD_TESTS_UI_BACKEND=console
$ export DATALAD_TESTS_OBSCURE_PREFIX=-
$ export DATALAD_SEED=1
$ export GIT_AUTHOR_DATE="Thu, 07 Apr 2005 22:13:13 +0200"
$ export GIT_AUTHOR_NAME=blah
$ export GIT_AUTHOR_EMAIL=committer@example.com
$ export GIT_COMMITTER_DATE="Thu, 07 Apr 2005 22:13:13 +0200"
$ export GIT_COMMITTER_NAME=blah
$ export GIT_COMMITTER_EMAIL=committer@example.com
$ source ~/virtualenv/python3.5/bin/activate
```

**Comment by yarikoptic** [comment]
happens only in batch mode seems to me:
```
$> zgrep ERROR.*test_is_available 48*/*gz 
4800/11-1.txt.gz:ERROR: datalad.support.tests.test_annexrepo.test_is_available(True, False)
4802/11-1.txt.gz:ERROR: datalad.support.tests.test_annexrepo.test_is_available(True, True)
4825/11-1.txt.gz:ERROR: datalad.support.tests.test_annexrepo.test_is_available(True, False)
4825/11-1.txt.gz:ERROR: datalad.support.tests.test_annexrepo.test_is_available(True, True)
4843/11-1.txt.gz:ERROR: datalad.support.tests.test_annexrepo.test_is_available(True, True)
4851/11-1.txt.gz:ERROR: datalad.support.tests.test_annexrepo.test_is_available(True, True)
4870/11-1.txt.gz:ERROR: datalad.support.tests.test_annexrepo.test_is_available(True, False)
4895/11-1.txt.gz:ERROR: datalad.support.tests.test_annexrepo.test_is_available(True, True)
```
and actual reason - batch'ed git-annex process dies off:
```
datalad.annex: Level 5: ...>test_annexrepo:1354>gitrepo:297,297>annexrepo:2844,3384>handlers:73  Sending 'boguskey\n' to batched annex BatchedAnnex(annex_cmd=['checkpresentkey'], annex_options=[], git_options=<<['-c', 'receive.autogc...>>, output_proc=<function>, path=<<'/tmp/datalad_temp_clo...>>)
datalad.annex: Level 5: ...>annexrepo:2844,3392>handlers:73  Done sending.
datalad.annex: WARNING: ...>annexrepo:2844,3395,3352>handlers:73  Process <subprocess.Popen object at 0x7f86c76dfb38> was terminated with returncode 1
datalad.annex: DEBUG: ...>annexrepo:2844,3395,3353,3422>handlers:73  Closing stdin of <subprocess.Popen object at 0x7f86c76dfb38> and waiting process to finish
datalad.annex: DEBUG: ...>annexrepo:2844,3395,3353,3427>handlers:73  Process <subprocess.Popen object at 0x7f86c76dfb38> has finished
datalad.annex: Level 5: ...>annexrepo:2844,3402>handlers:73  Received output: None
datalad.utils: Level 5: ...>utils:840,321>handlers:73  Removing temp file: /tmp/datalad_temp_clone_url_pa2omqn7
```
and seems to happen only when we pass a bogus key... I will now try adding logging output of stderr from batched processes if they terminate abnormally

**Comment by yarikoptic** [comment]
aha in https://travis-ci.org/datalad/datalad/jobs/361459024 it showed its ugly face again, so we got this log:
```
datalad.annex: WARNING: ...>annexrepo:2849,3420>handlers:73  Received output in stderr: '/bin/bash: warning: setlocale: LC_ALL: cannot change locale (en_US.UTF-8)\ngit-annex: Bad key\n'
```
which is all legit, key is indeed bogus... and git annex indeed exits with non-0 code if a bogus key is provided... 

I guess it is some kind of a race/and our incorrect handling within BatchedAnnex, e.g. in
```python
stdout = self.output_proc(process.stdout) if not process.stdout.closed else None
```
so if it closes before we get to it, we would return `None`, and otherwise possibly an empty string... so I will fix up for this with "planned" https://github.com/datalad/datalad/pull/2373
