### ISSUE TITLE
io.UnsupportedOperation: fileno python3.5 upstream gitpython and git-annex versions

### ISSUE THREAD

**Issue by yarikoptic** [datalad/datalad#2359]
#### What is the problem?
Initially reported in https://github.com/datalad/datalad/issues/2287#issuecomment-371491219 but I have decided to make a dedicated issue so it is not really lost.  It is happening consistently on master in the matrix run (only) with
```
    - _DATALAD_UPSTREAM_GITPYTHON=1
    - _DATALAD_UPSTREAM_GITANNEX=1
```
since we are close to the upstream git annex version (but different build) -- likely a GitPython issue?  should be relatively easy to try to reproduce ;)

#### Original report from @kyleam 
And one of the py3.5 builds seems to consistently have rerun tests [failures](https://travis-ci.org/datalad/datalad/builds/350683078):

```
ERROR: datalad.interface.tests.test_run.test_rerun_subdir
ERROR: datalad.interface.tests.test_run.test_rerun
ERROR: datalad.interface.tests.test_run.test_rerun_ambiguous_revision_file
ERROR: datalad.interface.tests.test_run.test_rerun_branch
ERROR: datalad.interface.tests.test_run.test_rerun_chain
ERROR: datalad.interface.tests.test_run.test_rerun_cherry_pick
ERROR: datalad.interface.tests.test_run.test_rerun_just_one_commit
ERROR: datalad.interface.tests.test_run.test_rerun_old_flag_compatibility
ERROR: datalad.interface.tests.test_run.test_rerun_onto
ERROR: datalad.interface.tests.test_run.test_rerun_outofdate_tree
```

All of the errors look something like

```
======================================================================
ERROR: datalad.interface.tests.test_run.test_rerun
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/travis/virtualenv/python3.5.5/lib/python3.5/site-packages/nose/case.py", line 198, in runTest
    self.test(*self.arg)
  File "/home/travis/build/datalad/datalad/datalad/tests/utils.py", line 1290, in newfunc
    func(*args, **kwargs)
  File "/home/travis/build/datalad/datalad/datalad/tests/utils.py", line 893, in newfunc
    return func(*args, **kwargs)
  File "/home/travis/build/datalad/datalad/datalad/tests/utils.py", line 664, in newfunc
    return t(*(arg + (filename,)), **kw)
  File "/home/travis/build/datalad/datalad/datalad/tests/utils.py", line 664, in newfunc
    return t(*(arg + (filename,)), **kw)
  File "/home/travis/build/datalad/datalad/datalad/interface/tests/test_run.py", line 141, in test_rerun
    ds.rerun(revision="HEAD~", message="rerun buried")
  File "/home/travis/virtualenv/python3.5.5/lib/python3.5/site-packages/wrapt/wrappers.py", line 562, in __call__
    args, kwargs)
  File "/home/travis/build/datalad/datalad/datalad/distribution/dataset.py", line 437, in apply_func
    return f(**kwargs)
  File "/home/travis/virtualenv/python3.5.5/lib/python3.5/site-packages/wrapt/wrappers.py", line 523, in __call__
    args, kwargs)
  File "/home/travis/build/datalad/datalad/datalad/interface/utils.py", line 466, in eval_func
    return return_func(generator_func)(*args, **kwargs)
  File "/home/travis/virtualenv/python3.5.5/lib/python3.5/site-packages/wrapt/wrappers.py", line 523, in __call__
    args, kwargs)
  File "/home/travis/build/datalad/datalad/datalad/interface/utils.py", line 454, in return_func
    results = list(results)
  File "/home/travis/build/datalad/datalad/datalad/interface/utils.py", line 411, in generator_func
    result_renderer, result_xfm, _result_filter, **_kwargs):
  File "/home/travis/build/datalad/datalad/datalad/interface/utils.py", line 478, in _process_results
    for res in results:
  File "/home/travis/build/datalad/datalad/datalad/interface/rerun.py", line 267, in __call__
    rerun_info=rev.info):
  File "/home/travis/build/datalad/datalad/datalad/interface/run.py", line 173, in run_command
    expect_fail=True,
  File "/home/travis/build/datalad/datalad/datalad/cmd.py", line 476, in run
    stdin=stdin)
  File "/opt/python/3.5.5/lib/python3.5/subprocess.py", line 640, in __init__
    errread, errwrite) = self._get_handles(stdin, stdout, stderr)
  File "/opt/python/3.5.5/lib/python3.5/subprocess.py", line 1137, in _get_handles
    c2pwrite = stdout.fileno()
io.UnsupportedOperation: fileno
```

**Comment by yarikoptic** [comment]
@kyleam - could you please have a look?  issue persists while testing on travis "on cron" where this matrix is ran.  Here eg a fresh one: https://travis-ci.org/datalad/datalad/jobs/366226075

**Comment by yarikoptic** [comment]
just a thing I guess that our "skipper" is not good enough -- will push a fixup

**Comment by kyleam** [comment]
I had looked at this a few times since the initial report and was always baffled, so I'm happy to see your fix :]

**Comment by yarikoptic** [comment]
Yeah... Unfortunately that whole decorator is more of a butt plug, not a fix ;-)

**Comment by yarikoptic** [comment]
Since the author knows a persona not grata
