### ISSUE TITLE
OSX buildbot is unhealthy - exempi library, and now PIL

### ISSUE THREAD

**Issue by yarikoptic** [datalad/datalad#2374]
#### What is the problem?
see e.g. http://smaug.datalad.org:8020/builders/datalad-pr-dl-osx-64/builds/3939/steps/nosetests/logs/stdio

exempi issue is that one which occurred first with #2360 : `ExempiLoadError: Exempi library not found.` and now consistent (including #2372)

a "new" one (which I might have just missed initial occurrence) 
```
ERROR: datalad.metadata.extractors.tests.test_image.test_image
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/Users/datalad/buildslave/datalad-pr-dl-osx-64/build/venv-ci/lib/python2.7/site-packages/nose/case.py", line 197, in runTest
    self.test(*self.arg)
  File "/Users/datalad/buildslave/datalad-pr-dl-osx-64/build/datalad/tests/utils.py", line 664, in newfunc
    return t(*(arg + (filename,)), **kw)
  File "/Users/datalad/buildslave/datalad-pr-dl-osx-64/build/datalad/metadata/extractors/tests/test_image.py", line 47, in test_image
    res = ds.aggregate_metadata()
  File "/Users/datalad/buildslave/datalad-pr-dl-osx-64/build/venv-ci/lib/python2.7/site-packages/wrapt/wrappers.py", line 562, in __call__
    args, kwargs)
  File "/Users/datalad/buildslave/datalad-pr-dl-osx-64/build/datalad/distribution/dataset.py", line 436, in apply_func
    return f(**kwargs)
  File "/Users/datalad/buildslave/datalad-pr-dl-osx-64/build/venv-ci/lib/python2.7/site-packages/wrapt/wrappers.py", line 523, in __call__
    args, kwargs)
  File "/Users/datalad/buildslave/datalad-pr-dl-osx-64/build/datalad/interface/utils.py", line 470, in eval_func
    return return_func(generator_func)(*args, **kwargs)
  File "/Users/datalad/buildslave/datalad-pr-dl-osx-64/build/venv-ci/lib/python2.7/site-packages/wrapt/wrappers.py", line 523, in __call__
    args, kwargs)
  File "/Users/datalad/buildslave/datalad-pr-dl-osx-64/build/datalad/interface/utils.py", line 458, in return_func
    results = list(results)
  File "/Users/datalad/buildslave/datalad-pr-dl-osx-64/build/datalad/interface/utils.py", line 414, in generator_func
    result_renderer, result_xfm, _result_filter, **_kwargs):
  File "/Users/datalad/buildslave/datalad-pr-dl-osx-64/build/datalad/interface/utils.py", line 482, in _process_results
    for res in results:
  File "/Users/datalad/buildslave/datalad-pr-dl-osx-64/build/datalad/metadata/aggregate.py", line 702, in __call__
    to_save)
  File "/Users/datalad/buildslave/datalad-pr-dl-osx-64/build/datalad/metadata/aggregate.py", line 205, in _extract_metadata
    paths=relevant_paths)
  File "/Users/datalad/buildslave/datalad-pr-dl-osx-64/build/datalad/metadata/metadata.py", line 454, in _get_metadata
    mtype, ds, exc_str(e))
ValueError: ("Failed to load metadata extractor for '%s', broken dataset configuration (%s)?: %s", 'image', <Dataset path=/private/tmp/datalad_temp_test_imageEz3NrM>, 'dlopen(/Users/datalad/buildslave/datalad-pr-dl-osx-64/build/venv-ci/lib/python2.7/site-packages/PIL/_imaging.so, 2): Symbol not found: _clock_gettime\n  Referenced from: /Users/datalad/buildslave/datalad-pr-dl-osx-64/build/venv-ci/lib/python2.7/site-packages/PIL/.dylibs/liblzma.5.dylib (which was built for Mac OS X 10.12)\n  Expected in: /usr/lib/libSystem.B.dylib\n in /Users/datalad/buildslave/datalad-pr-dl-osx-64/build/venv-ci/lib/python2.7/site-packages/PIL/.dylibs/liblzma.5.dylib [Image.py:<module>:60]')
```
not sure the reason -- possibly new upstreams of those python modules

**Comment by mih** [comment]
I think this was happening on anfvoff for some time. Also "total" failure is happening frequently, where the build bot hangs at an early stage and probably gets killed. Amd it is just the OSX one that seems to be this moody.

**Comment by yarikoptic** [comment]
PIL issue, from https://github.com/pocoproject/poco/issues/1453 

      clock_gettime() was added in macOS 10.12. You need to build against an earlier SDK if you want to be backwards compatible.

so it might be that current PIL wheel was built against newer one.  @joeyh already asked about upgrading that box since similar compatibility issues happened with git-annex, but we were not 100% sure (Joey could correct me if I am wrong) if that wouldn't cause backward compatibility issues for then built in this environment git-annex builds, so I haven't went forward with the upgrade at that point.

**Comment by yarikoptic** [comment]
the beast got unhealthy again due to outdated pip being unable to update itself!  I just made it use miniconda as the base - seems to work (at least passes through all the pip installs etc): http://smaug.datalad.org:8020/builders/datalad-pr-dl-osx-64/builds/3979 but tests are still runing
