### ISSUE TITLE
GitPython cannot find Windows Git in PATH

### ISSUE THREAD

**Issue by mih** [datalad/datalad#2436]
Excerpt from https://ci.appveyor.com/project/mih/datalad/build/1.0.13

Both `git` and `git annex` invocation work immediately before the call to `datalad wtf`, but GitPython complains that there is no Git in the PATH. This issue could be related to #1566, but here we have no bash that could take the blame....

```
cd __testhome__
[00:02:28] git version
[00:02:28] git version 2.16.2.windows.1
[00:02:28] git annex version
[00:02:28] git-annex version: 6.20180409-gfb0780266
[00:02:28] build flags: Assistant Webapp Pairing S3(multipartupload)(storageclasses) WebDAV ConcurrentOutput TorrentParser Feeds Testsuite
[00:02:28] dependency versions: aws-0.17.1 bloomfilter-2.0.1.0 cryptonite-0.23 DAV-1.3.1 feed-0.3.12.0 ghc-8.0.2 http-client-0.5.7.1 persistent-sqlite-2.6.2 torrent-10000.1.1 uuid-1.3.13 yesod-1.4.5
[00:02:28] key/value backends: SHA256E SHA256 SHA512E SHA512 SHA224E SHA224 SHA384E SHA384 SHA3_256E SHA3_256 SHA3_512E SHA3_512 SHA3_224E SHA3_224 SHA3_384E SHA3_384 SKEIN256E SKEIN256 SKEIN512E SKEIN512 BLAKE2B256E BLAKE2B256 BLAKE2B512E BLAKE2B512 BLAKE2B160E BLAKE2B160 BLAKE2B224E BLAKE2B224 BLAKE2B384E BLAKE2B384 BLAKE2S256E BLAKE2S256 BLAKE2S160E BLAKE2S160 BLAKE2S224E BLAKE2S224 BLAKE2SP256E BLAKE2SP256 BLAKE2SP224E BLAKE2SP224 SHA1E SHA1 MD5E MD5 WORM URL
[00:02:28] remote types: git gcrypt p2p S3 bup directory rsync web bittorrent webdav adb tahoe glacier ddar hook external
[00:02:28] local repository version: unknown
[00:02:28] supported repository versions: 3 5 6
[00:02:28] upgrade supported from repository versions: 2 3 4 5
[00:02:28] operating system: mingw32 i386
[00:02:28] datalad wtf
[00:02:30] Traceback (most recent call last):
[00:02:30]   File "C:\Miniconda35\envs\test-environment\Scripts\datalad-script.py", line 11, in <module>
[00:02:30]     load_entry_point('datalad', 'console_scripts', 'datalad')()
[00:02:30]   File "c:\projects\datalad\datalad\cmdline\main.py", line 326, in main
[00:02:30]     parser = setup_parser(args or sys.argv)
[00:02:30]   File "c:\projects\datalad\datalad\cmdline\main.py", line 79, in setup_parser
[00:02:30]     from ..interface.base import dedent_docstring, get_interface_groups, \
[00:02:30]   File "c:\projects\datalad\datalad\interface\base.py", line 27, in <module>
[00:02:30]     from datalad.interface.common_opts import eval_params
[00:02:30]   File "c:\projects\datalad\datalad\interface\common_opts.py", line 15, in <module>
[00:02:30]     from datalad.interface.results import known_result_xfms
[00:02:30]   File "c:\projects\datalad\datalad\interface\results.py", line 27, in <module>
[00:02:30]     from datalad.distribution.dataset import Dataset
[00:02:30]   File "c:\projects\datalad\datalad\distribution\dataset.py", line 30, in <module>
[00:02:30]     from datalad.support.annexrepo import AnnexRepo
[00:02:30]   File "c:\projects\datalad\datalad\support\annexrepo.py", line 43, in <module>
[00:02:30]     from git import InvalidGitRepositoryError
[00:02:30]   File "C:\Miniconda35\envs\test-environment\lib\site-packages\git\__init__.py", line 82, in <module>
[00:02:30]     refresh()
[00:02:30]   File "C:\Miniconda35\envs\test-environment\lib\site-packages\git\__init__.py", line 73, in refresh
[00:02:30]     if not Git.refresh(path=path):
[00:02:30]   File "C:\Miniconda35\envs\test-environment\lib\site-packages\git\cmd.py", line 292, in refresh
[00:02:30]     raise ImportError(err)
[00:02:30] ImportError: Bad git executable.
[00:02:30] The git executable must be specified in one of the following ways:
[00:02:30]     - be included in your $PATH
[00:02:30]     - be set via $GIT_PYTHON_GIT_EXECUTABLE
[00:02:30]     - explicitly set via git.refresh()
[00:02:30] 
[00:02:30] All git commands will error until this is rectified.
[00:02:30] 
[00:02:30] This initial warning can be silenced or aggravated in the future by setting the
[00:02:30] $GIT_PYTHON_REFRESH environment variable. Use one of the following values:
[00:02:30]     - quiet|q|silence|s|none|n|0: for no warning or exception
[00:02:30]     - warn|w|warning|1: for a printed warning
[00:02:30]     - error|e|raise|r|2: for a raised exception
[00:02:30] 
[00:02:30] Example:
[00:02:30]     export GIT_PYTHON_REFRESH=quiet
[00:02:30] 
[00:02:30] Command exited with code 1
```

**Comment by ThHanke** [comment]
Yes! Exactly the same on Win7 with all dependencys installed. We switched to a Debian based solution with cifs mount of a windows server 2012 share.

**Comment by mih** [comment]
@ThHanke Thanks. So it is a general issue. We need to figure out a way to address this, as ATM windows incompatibility starts at `import datalad` -- which is much worse than 12 months ago.
