### ISSUE TITLE
`install()` returns None not Dataset instance

### ISSUE THREAD

**Issue by mih** [datalad/datalad#2449]
Happening on windows: https://ci.appveyor.com/api/buildjobs/0dhdwhy706yvdv03/log
```
[00:03:57] ======================================================================
[00:03:57] ERROR: datalad_neuroimaging.tests.test_dicomconv.test_dicom_metadata_aggregation
[00:03:57] ----------------------------------------------------------------------
[00:03:57] Traceback (most recent call last):
[00:03:57]   File "C:\Miniconda35\envs\test-environment\lib\site-packages\nose\case.py", line 198, in runTest
[00:03:57]     self.test(*self.arg)
[00:03:57]   File "C:\Miniconda35\envs\test-environment\lib\site-packages\datalad\tests\utils.py", line 661, in newfunc
[00:03:57]     return t(*(arg + (filename,)), **kw)
[00:03:57]   File "c:\projects\datalad-neuroimaging\datalad_neuroimaging\tests\test_dicomconv.py", line 28, in test_dicom_metadata_aggregation
[00:03:57]     dicoms = get_dicom_dataset('structural')
[00:03:57]   File "c:\projects\datalad-neuroimaging\datalad_neuroimaging\tests\utils.py", line 17, in get_dicom_dataset
[00:03:57]     ok_clean_git(ds.path)
[00:03:57] AttributeError: 'NoneType' object has no attribute 'path'
```

in this code

```
def get_dicom_dataset(flavor):
    ds = install(
        dataset=normpath(opj(_modpath, pardir)),
        path=opj(_modpath, 'tests', 'data', 'dicoms', flavor))
    # fail on any "surprising" changes made to this dataset
    ok_clean_git(ds.path)
    return ds
```

**Comment by mih** [comment]
So this is intentional. `install` uses a `successdataset-or-none` return value policy by default. So inside that call on windows something goes wrong, but that doesn't lead to any real error (maybe just some output message). Hence the failure goes unnoticed until later in the code.

I have difficulties rationalizing this behavior...

In any case, this is not a windows issue, although the underlying cause probably is.

**Comment by mih** [comment]
No, it is somehow worse. None is returned regardless of the `result_xfm`

**Comment by mih** [comment]
And it was a windows bug...
