### ISSUE TITLE
"Integration" testing failures

### ISSUE THREAD

**Issue by yarikoptic** [datalad/datalad#2493]
#### What is the problem?

Below you could see a list of failed tests discovered after doing 
```shell
mkdir datalad-integration
cd datalad-integration
virtualenv --system-site-packages venvs/dev
source venvs/dev/bin/activate
pip install -e ../datalad-master ../datalad-neuroimaging ../datalad-crawler
DATALAD_TESTS_SSH=1 python -m nose -s -v datalad datalad_crawler datalad_neuroimaging 2>&1 | tee tests.log
```

- I've excluded the ones for #2489 (and khm, failure which #2490 was supposed to fix and I thought it did... need to look again on a fresh eye)
- Just now realized that I was running it with git annex 6.20180510+gitg500f7ea78-1~ndall+1 which I've been test driving before uploading ... I will make it available now in debian-devel of neurodebian

Some failures seems to hint on not installed resources needed for tests
```
======================================================================
ERROR: datalad_neuroimaging.extractors.tests.test_dicom.test_dicom
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/usr/lib/python2.7/dist-packages/nose/case.py", line 197, in runTest
    self.test(*self.arg)
  File "/home/yoh/proj/datalad/datalad-integration/venvs/dev/local/lib/python2.7/site-packages/datalad/tests/utils.py", line 662, in newfunc
    return t(*(arg + (filename,)), **kw)
  File "/home/yoh/proj/datalad/datalad-integration/venvs/dev/local/lib/python2.7/site-packages/datalad_neuroimaging/extractors/tests/test_dicom.py", line 37, in test_dicom
    path)
  File "/usr/lib/python2.7/shutil.py", line 133, in copy
    copyfile(src, dst)
  File "/usr/lib/python2.7/shutil.py", line 96, in copyfile
    with open(src, 'rb') as fsrc:
IOError: [Errno 2] No such file or directory: '/home/yoh/proj/datalad/datalad-integration/venvs/dev/local/lib/python2.7/site-packages/datalad_neuroimaging/tests/data/dicom.dcm'

======================================================================
ERROR: datalad_neuroimaging.extractors.tests.test_nidm.test_nidm
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/usr/lib/python2.7/dist-packages/nose/case.py", line 197, in runTest
    self.test(*self.arg)
  File "/home/yoh/proj/datalad/datalad-integration/venvs/dev/local/lib/python2.7/site-packages/datalad/tests/utils.py", line 662, in newfunc
    return t(*(arg + (filename,)), **kw)
  File "/home/yoh/proj/datalad/datalad-integration/venvs/dev/local/lib/python2.7/site-packages/datalad_neuroimaging/extractors/tests/test_nidm.py", line 28, in test_nidm
    path)
  File "/usr/lib/python2.7/shutil.py", line 133, in copy
    copyfile(src, dst)
  File "/usr/lib/python2.7/shutil.py", line 96, in copyfile
    with open(src, 'rb') as fsrc:
IOError: [Errno 2] No such file or directory: '/home/yoh/proj/datalad/datalad-integration/venvs/dev/local/lib/python2.7/site-packages/datalad_neuroimaging/tests/data/nifti1.nii.gz'

======================================================================
ERROR: datalad_neuroimaging.extractors.tests.test_nifti1.test_nifti
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/usr/lib/python2.7/dist-packages/nose/case.py", line 197, in runTest
    self.test(*self.arg)
  File "/home/yoh/proj/datalad/datalad-integration/venvs/dev/local/lib/python2.7/site-packages/datalad/tests/utils.py", line 662, in newfunc
    return t(*(arg + (filename,)), **kw)
  File "/home/yoh/proj/datalad/datalad-integration/venvs/dev/local/lib/python2.7/site-packages/datalad_neuroimaging/extractors/tests/test_nifti1.py", line 63, in test_nifti
    path)
  File "/usr/lib/python2.7/shutil.py", line 133, in copy
    copyfile(src, dst)
  File "/usr/lib/python2.7/shutil.py", line 96, in copyfile
    with open(src, 'rb') as fsrc:
IOError: [Errno 2] No such file or directory: '/home/yoh/proj/datalad/datalad-integration/venvs/dev/local/lib/python2.7/site-packages/datalad_neuroimaging/tests/data/nifti1.nii.gz'

======================================================================
ERROR: datalad_neuroimaging.tests.test_bids2scidata.test_minimal
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/usr/lib/python2.7/dist-packages/nose/case.py", line 197, in runTest
    self.test(*self.arg)
  File "/home/yoh/proj/datalad/datalad-integration/venvs/dev/local/lib/python2.7/site-packages/datalad/tests/utils.py", line 492, in newfunc
    return t(*(arg + (d,)), **kw)
  File "/home/yoh/proj/datalad/datalad-integration/venvs/dev/local/lib/python2.7/site-packages/datalad_neuroimaging/tests/test_bids2scidata.py", line 108, in test_minimal
    repo_url='http://example.com',
  File "/home/yoh/proj/datalad/datalad-integration/venvs/dev/local/lib/python2.7/site-packages/datalad/distribution/dataset.py", line 439, in apply_func
    return f(**kwargs)
  File "/home/yoh/proj/datalad/datalad-integration/venvs/dev/local/lib/python2.7/site-packages/datalad/interface/utils.py", line 470, in eval_func
    return return_func(generator_func)(*args, **kwargs)
  File "/home/yoh/proj/datalad/datalad-integration/venvs/dev/local/lib/python2.7/site-packages/datalad/interface/utils.py", line 458, in return_func
    results = list(results)
  File "/home/yoh/proj/datalad/datalad-integration/venvs/dev/local/lib/python2.7/site-packages/datalad/interface/utils.py", line 414, in generator_func
    result_renderer, result_xfm, _result_filter, **_kwargs):
  File "/home/yoh/proj/datalad/datalad-integration/venvs/dev/local/lib/python2.7/site-packages/datalad/interface/utils.py", line 482, in _process_results
    for res in results:
  File "/home/yoh/proj/datalad/datalad-integration/venvs/dev/local/lib/python2.7/site-packages/datalad_neuroimaging/bids2scidata.py", line 678, in __call__
    itmpl = open(itmpl_path, encoding='utf-8').read()
IOError: [Errno 2] No such file or directory: '/home/yoh/proj/datalad/datalad-integration/venvs/dev/local/lib/python2.7/site-packages/datalad_neuroimaging/resources/isatab/scidata_bids_investigator.txt'

======================================================================
ERROR: datalad_neuroimaging.tests.test_dicomconv.test_dicom_metadata_aggregation
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/usr/lib/python2.7/dist-packages/nose/case.py", line 197, in runTest
    self.test(*self.arg)
  File "/home/yoh/proj/datalad/datalad-integration/venvs/dev/local/lib/python2.7/site-packages/datalad/tests/utils.py", line 662, in newfunc
    return t(*(arg + (filename,)), **kw)
  File "/home/yoh/proj/datalad/datalad-integration/venvs/dev/local/lib/python2.7/site-packages/datalad_neuroimaging/tests/test_dicomconv.py", line 40, in test_dicom_metadata_aggregation
    dicoms = get_dicom_dataset('structural')
  File "/home/yoh/proj/datalad/datalad-integration/venvs/dev/local/lib/python2.7/site-packages/datalad_neuroimaging/tests/test_dicomconv.py", line 32, in get_dicom_dataset
    path=opj(modpath, 'tests', 'data', 'dicoms', flavor))
  File "/home/yoh/proj/datalad/datalad-integration/venvs/dev/local/lib/python2.7/site-packages/datalad/interface/utils.py", line 470, in eval_func
    return return_func(generator_func)(*args, **kwargs)
  File "/home/yoh/proj/datalad/datalad-integration/venvs/dev/local/lib/python2.7/site-packages/datalad/interface/utils.py", line 458, in return_func
    results = list(results)
  File "/home/yoh/proj/datalad/datalad-integration/venvs/dev/local/lib/python2.7/site-packages/datalad/interface/utils.py", line 414, in generator_func
    result_renderer, result_xfm, _result_filter, **_kwargs):
  File "/home/yoh/proj/datalad/datalad-integration/venvs/dev/local/lib/python2.7/site-packages/datalad/interface/utils.py", line 482, in _process_results
    for res in results:
  File "/home/yoh/proj/datalad/datalad-integration/venvs/dev/local/lib/python2.7/site-packages/datalad/distribution/install.py", line 194, in __call__
    purpose='installation')
  File "/home/yoh/proj/datalad/datalad-integration/venvs/dev/local/lib/python2.7/site-packages/datalad/distribution/dataset.py", line 505, in require_dataset
    "{0}.".format(dataset.path))
ValueError: No installed dataset found at /home/yoh/proj/datalad/datalad-integration/venvs/dev/local/lib/python2.7/site-packages.

======================================================================
FAIL: datalad.cmdline.tests.test_main.test_help_np
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/usr/lib/python2.7/dist-packages/nose/case.py", line 197, in runTest
    self.test(*self.arg)
  File "/home/yoh/proj/datalad/datalad-integration/venvs/dev/local/lib/python2.7/site-packages/datalad/cmdline/tests/test_main.py", line 100, in test_help_np
    'Plugins'})
AssertionError: Items in the first set but not the second:
'Neuroimaging tools'
'Crawl web resources'

======================================================================
FAIL: datalad.distribution.tests.test_create_sibling.test_target_ssh_simple
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/usr/lib/python2.7/dist-packages/nose/case.py", line 197, in runTest
    self.test(*self.arg)
  File "/home/yoh/proj/datalad/datalad-integration/venvs/dev/local/lib/python2.7/site-packages/datalad/tests/utils.py", line 943, in newfunc
    return func(*args, **kwargs)
  File "/home/yoh/proj/datalad/datalad-integration/venvs/dev/local/lib/python2.7/site-packages/datalad/tests/utils.py", line 835, in newfunc
    t(*(arg + (uri,)), **kw)
  File "/home/yoh/proj/datalad/datalad-integration/venvs/dev/local/lib/python2.7/site-packages/datalad/tests/utils.py", line 662, in newfunc
    return t(*(arg + (filename,)), **kw)
  File "/home/yoh/proj/datalad/datalad-integration/venvs/dev/local/lib/python2.7/site-packages/datalad/tests/utils.py", line 662, in newfunc
    return t(*(arg + (filename,)), **kw)
  File "/home/yoh/proj/datalad/datalad-integration/venvs/dev/local/lib/python2.7/site-packages/datalad/distribution/tests/test_create_sibling.py", line 186, in test_target_ssh_simple
    ok_endswith(target_description, target_path)
  File "/home/yoh/proj/datalad/datalad-integration/venvs/dev/local/lib/python2.7/site-packages/datalad/tests/utils.py", line 395, in ok_endswith
    msg="String %r doesn't end with %r" % (s, suffix))
AssertionError: String 'yoh@hopa:~/.tmp/datalad_temp_test_target_ssh_simplefXVh8F/basic' doesn't end with '/home/yoh/.tmp/datalad_temp_test_target_ssh_simplefXVh8F/basic'
```

**Comment by mih** [comment]
And those repos are all on latest master? Those failures look all too familiar and should have been fixed already.

**Comment by mih** [comment]
Here is evidence that the issue seems to be the state of your repos:

```
mih@meiner /tmp/datalad-integration % virtualenv bug2493
Running virtualenv with interpreter /usr/bin/python2
New python executable in /tmp/datalad-integration/bug2493/bin/python2
Also creating executable in /tmp/datalad-integration/bug2493/bin/python
Installing setuptools, pkg_resources, pip, wheel...done.
mih@meiner /tmp/datalad-integration % source bug2493/bin/activate
(bug2493) mih@meiner /tmp/datalad-integration % pip install datalad-neuroimaging datalad-crawler
```

without `virtualenv --system-site-packages` it ends up without pyliblzma (which is a bug), so:

```
mih@meiner /tmp/datalad-integration % pip install pyliblzma
```

But then (only going for a bit more than the examples that you listed):

```
DATALAD_TESTS_SSH=1 python -m nose -s -v datalad_neuroimaging.extractors.tests datalad_neuroimaging.tests.test_bids2scidata datalad_neuroimaging.tests.test_dicomconv datalad.cmdline.tests.test_main datalad.distribution.tests.test_create_sibling
 <snip>
======================================================================
FAIL: datalad.cmdline.tests.test_main.test_help_np
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/tmp/datalad-integration/bug2493/local/lib/python2.7/site-packages/nose/case.py", line 197, in runTest
    self.test(*self.arg)
  File "/tmp/datalad-integration/bug2493/local/lib/python2.7/site-packages/datalad/cmdline/tests/test_main.py", line 100, in test_help_np
    'Plugins'})
AssertionError: Items in the first set but not the second:
'Neuroimaging tools'
'Crawl web resources'

----------------------------------------------------------------------
Ran 28 tests in 161.157s

FAILED (failures=1)
```

And this failure was addressed in 492e32d9292a1003601cef4df7efd3fbf88845b1

**Comment by yarikoptic** [comment]
yeah, I was suspicious as well... I will try again (note that in your case you seems to pip install "released" versions, whenever in mine I install from local  clones which I did check to correspond to current masters...)

**Comment by yarikoptic** [comment]
I found that my datalad-neuroimaging was severily outdated and since there was some (non important) commit never pushed, `git pull --ff-only` failed and I guess I have missed that and assumed that it is all up to date.... I will close for now

**Comment by yarikoptic** [comment]
FWIW added -intgr builders for our buildbot which should test all of those ... not sure if works anyhow and fail to trigger manually -- let's wait for the night to come!
