### ISSUE TITLE
datalad_neuroimaging.__file__ can be not absolute

### ISSUE THREAD

**Issue by yarikoptic** [datalad/datalad#2514]
#### What is the problem?
I have been chasing following failure on a local installation for a while:
```
======================================================================
ERROR: datalad_neuroimaging.tests.test_bids2scidata.test_minimal
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/usr/lib/python2.7/dist-packages/nose/case.py", line 197, in runTest
    self.test(*self.arg)
  File "/home/yoh/proj/datalad/datalad-master/datalad/tests/utils.py", line 493, in newfunc
    return t(*(arg + (d,)), **kw)
  File "datalad_neuroimaging/tests/test_bids2scidata.py", line 113, in test_minimal
    repo_url='http://example.com',
  File "/home/yoh/proj/datalad/datalad-master/datalad/distribution/dataset.py", line 439, in apply_func
    return f(**kwargs)
  File "/home/yoh/proj/datalad/datalad-master/datalad/interface/utils.py", line 470, in eval_func
    return return_func(generator_func)(*args, **kwargs)
  File "/home/yoh/proj/datalad/datalad-master/datalad/interface/utils.py", line 458, in return_func
    results = list(results)
  File "/home/yoh/proj/datalad/datalad-master/datalad/interface/utils.py", line 414, in generator_func
    result_renderer, result_xfm, _result_filter, **_kwargs):
  File "/home/yoh/proj/datalad/datalad-master/datalad/interface/utils.py", line 482, in _process_results
    for res in results:
  File "datalad_neuroimaging/bids2scidata.py", line 678, in __call__
    itmpl = open(itmpl_path, encoding='utf-8').read()
IOError: [Errno 2] No such file or directory: 'datalad_neuroimaging/resources/isatab/scidata_bids_investigator.txt'
```
and it seems due to the fact that in that run, when I run it via
```shell
DATALAD_TESTS_SSH=1 DATALAD_TESTS_TEMP_KEEP=1 python -m nose -s -v datalad datalad_crawler datalad_neuroimaging
```
from `datalad-neuroimaging` repository using local virtualenv which has all others installed into it (in develop mode), then `datalad_neuroimaging.__file__` is relative to that path (although cwd is different) and thus loading fails... seems to be sufficient to have `datalad_crawler` (without `datalad`) in the above invocation... 

if any obvious idea what is going on -- I am all ears

**Comment by yarikoptic** [comment]
and + interaction with:
- if I run `nose   datalad_neuroimaging` then nose imports it first and it gets full path already before we even get to loading entry points
- if I run e.g. `nose datalad_crawler datalad_neuroimaging` then it imports datalad, and that I guess goes through our loading of entry points, and that is where it gets imported with relative path

I would say we "Fix" it by testing the path to be absolute (when loading entry points, we have it in two places) and making it absolute it if it is not

**Comment by yarikoptic** [comment]
thinking about it -- it might not work reliably since we might actually rely on paths in submodules and I am not sure if those would get the abs path... grrr... yeap -- they all get relative paths
```
[DEBUG  ] Loaded entrypoint neuroimaging from datalad.extensions 
> /home/yoh/proj/datalad/datalad-master/datalad/api.py(53)_generate_extension_api()
-> for intfspec in interfaces:
*(Pdb) [m  for m in modules.keys() if 'neuro' in m]
['datalad_neuroimaging', 'datalad_neuroimaging.version', 'datalad_neuroimaging.datalad']
(Pdb) modules['datalad_neuroimaging.version'].__file__
'datalad_neuroimaging/version.pyc'
```
so we would need to fix them all up then :-/

**Comment by yarikoptic** [comment]
ok, giving up... I do not see any non-screwy up way to correct for that.  I will just add an assertion demanding a full path in that function accessing `__file__` in datalad_neuroimaging demanding to run outside of the source tree since module path is not absolute.  It would be too late to figure out the path correctly.

**Comment by yarikoptic** [comment]
I will close on this note for now
