### ISSUE TITLE
Git-reported path handling on Windows broken

### ISSUE THREAD

**Issue by mih** [datalad/datalad#2528]
```
[00:09:50] ======================================================================
[00:09:50] ERROR: datalad.distribution.tests.test_add.test_add_files
[00:09:50] ----------------------------------------------------------------------
[00:09:50] Traceback (most recent call last):
[00:09:50]   File "C:\Miniconda35\envs\test-environment\lib\site-packages\nose\case.py", line 198, in runTest
[00:09:50]     self.test(*self.arg)
[00:09:50]   File "C:\Miniconda35\envs\test-environment\lib\site-packages\datalad\tests\utils.py", line 499, in newfunc
[00:09:50]     return t(*(arg + (d,)), **kw)
[00:09:50]   File "C:\Miniconda35\envs\test-environment\lib\site-packages\datalad\distribution\tests\test_add.py", line 103, in test_add_files
[00:09:50]     indexed.remove(opj('.datalad', 'config'))
[00:09:50] KeyError: '.datalad\\config'
```

**Comment by mih** [comment]
Waiting for #2546

**Comment by mih** [comment]
https://github.com/datalad/datalad-revolution now demos a new and superior approach to path handling via pathlib

**Comment by mih** [comment]
We are now extensively using pathlib. Of course it is not certain how many of such bugs are left in the code base, but this issue is not needed to (or indeed does) track the specific bugs.
