### ISSUE TITLE
Known-to-fail test runs on windows

### ISSUE THREAD

**Issue by mih** [datalad/datalad#2530]
```
[00:09:50] ======================================================================
[00:09:50] ERROR: datalad.distribution.tests.test_create_sibling.test_invalid_call
[00:09:50] ----------------------------------------------------------------------
[00:09:50] Traceback (most recent call last):
[00:09:50]   File "C:\Miniconda35\envs\test-environment\lib\site-packages\nose\case.py", line 198, in runTest
[00:09:50]     self.test(*self.arg)
[00:09:50]   File "C:\Miniconda35\envs\test-environment\lib\site-packages\datalad\tests\utils.py", line 669, in newfunc
[00:09:50]     return t(*(arg + (filename,)), **kw)
[00:09:50]   File "C:\Miniconda35\envs\test-environment\lib\contextlib.py", line 77, in __exit__
[00:09:50]     self.gen.throw(type, value, traceback)
[00:09:50]   File "C:\Miniconda35\envs\test-environment\lib\site-packages\datalad\utils.py", line 1307, in make_tempfile
[00:09:50]     yield filename
[00:09:50]   File "C:\Miniconda35\envs\test-environment\lib\site-packages\datalad\tests\utils.py", line 669, in newfunc
[00:09:50]     return t(*(arg + (filename,)), **kw)
[00:09:50]   File "C:\Miniconda35\envs\test-environment\lib\site-packages\datalad\distribution\tests\test_create_sibling.py", line 117, in test_invalid_call
[00:09:50]     assert_raises(InsufficientArgumentsError, create_sibling, '')
[00:09:50]   File "C:\Miniconda35\envs\test-environment\lib\unittest\case.py", line 727, in assertRaises
[00:09:50]     return context.handle('assertRaises', args, kwargs)
[00:09:50]   File "C:\Miniconda35\envs\test-environment\lib\unittest\case.py", line 176, in handle
[00:09:50]     callable_obj(*args, **kwargs)
[00:09:50]   File "C:\Miniconda35\envs\test-environment\lib\site-packages\datalad\interface\utils.py", line 470, in eval_func
[00:09:50]     return return_func(generator_func)(*args, **kwargs)
[00:09:50]   File "C:\Miniconda35\envs\test-environment\lib\site-packages\datalad\interface\utils.py", line 458, in return_func
[00:09:50]     results = list(results)
[00:09:50]   File "C:\Miniconda35\envs\test-environment\lib\site-packages\datalad\interface\utils.py", line 414, in generator_func
[00:09:50]     result_renderer, result_xfm, _result_filter, **_kwargs):
[00:09:50]   File "C:\Miniconda35\envs\test-environment\lib\site-packages\datalad\interface\utils.py", line 482, in _process_results
[00:09:50]     for res in results:
[00:09:50]   File "C:\Miniconda35\envs\test-environment\lib\site-packages\datalad\distribution\create_sibling.py", line 422, in __call__
[00:09:50]     "Support for SSH connections is not yet implemented in Windows")
[00:09:50]   File "C:\Miniconda35\envs\test-environment\lib\site-packages\datalad\utils.py", line 122, in not_supported_on_windows
[00:09:50]     + (": %s" % msg if msg else ""))
[00:09:50] NotImplementedError: This functionality is not yet implemented for Windows OS: Support for SSH connections is not yet implemented in Windows

```

**Comment by mih** [comment]
This issue is now invalid, as SSH works just fine on Windows and is enabled in a coming PR.
