### ISSUE TITLE
POSIX path assumption in various tests

### ISSUE THREAD

**Issue by mih** [datalad/datalad#2531]
```
[00:09:50] ======================================================================
[00:09:50] FAIL: datalad.distribution.tests.test_add.test_relpath_add
[00:09:50] ----------------------------------------------------------------------
[00:09:50] Traceback (most recent call last):
[00:09:50]   File "C:\Miniconda35\envs\test-environment\lib\site-packages\nose\case.py", line 198, in runTest
[00:09:50]     self.test(*self.arg)
[00:09:50]   File "C:\Miniconda35\envs\test-environment\lib\site-packages\datalad\tests\utils.py", line 499, in newfunc
[00:09:50]     return t(*(arg + (d,)), **kw)
[00:09:50]   File "C:\Miniconda35\envs\test-environment\lib\site-packages\datalad\distribution\tests\test_add.py", line 233, in test_relpath_add
[00:09:50]     opj(ds.path, 'dir', 'testindir'))
[00:09:50] AssertionError: 'C:\\Users\\appveyor\\AppData\\Local\\Temp\\1\\datalad_temp_tree_krytm7_f\\dir/testindir' != 'C:\\Users\\appveyor\\AppData\\Local\\Temp\\1\\datalad_temp_tree_krytm7_f\\dir\\testindir'


[00:09:50] ======================================================================
[00:09:50] FAIL: datalad.distribution.tests.test_get.test_get_flexible_source_candidates_for_submodule
[00:09:50] ----------------------------------------------------------------------
[00:09:50] Traceback (most recent call last):
[00:09:50]   File "C:\Miniconda35\envs\test-environment\lib\site-packages\nose\case.py", line 198, in runTest
[00:09:50]     self.test(*self.arg)
[00:09:50]   File "C:\Miniconda35\envs\test-environment\lib\site-packages\datalad\tests\utils.py", line 669, in newfunc
[00:09:50]     return t(*(arg + (filename,)), **kw)
[00:09:50]   File "C:\Miniconda35\envs\test-environment\lib\site-packages\datalad\tests\utils.py", line 669, in newfunc
[00:09:50]     return t(*(arg + (filename,)), **kw)
[00:09:50]   File "C:\Miniconda35\envs\test-environment\lib\site-packages\datalad\distribution\tests\test_get.py", line 89, in test_get_flexible_source_candidates_for_submodule
[00:09:50]     eq_(f(clone, 'sub'), [t + '/sub'])
[00:09:50] AssertionError: ['C:\\Users\\appveyor\\AppData\\Local\\Temp\\1\\datalad_temp_xflvkser\\sub'] != ['C:\\Users\\appveyor\\AppData\\Local\\Temp\\1\\datalad_temp_xflvkser/sub']

[00:09:50] ======================================================================
[00:09:50] FAIL: datalad.distribution.tests.test_utils.test_get_flexible_source_candidates
[00:09:50] ----------------------------------------------------------------------
[00:09:50] Traceback (most recent call last):
[00:09:50]   File "C:\Miniconda35\envs\test-environment\lib\site-packages\nose\case.py", line 198, in runTest
[00:09:50]     self.test(*self.arg)
[00:09:50]   File "C:\Miniconda35\envs\test-environment\lib\site-packages\datalad\distribution\tests\test_utils.py", line 43, in test_get_flexible_source_candidates
[00:09:50]     eq_(f('../r', '.'), ['../r'])
[00:09:50] AssertionError: ['..\\r'] != ['../r']

[00:04:01] ======================================================================
[00:04:01] FAIL: datalad.interface.tests.test_run.test_new_or_modified
[00:04:01] ----------------------------------------------------------------------
[00:04:01] Traceback (most recent call last):
[00:04:01]   File "C:\Miniconda35\envs\test-environment\lib\site-packages\nose\case.py", line 198, in runTest
[00:04:01]     self.test(*self.arg)
[00:04:01]   File "C:\Miniconda35\envs\test-environment\lib\site-packages\datalad\tests\utils.py", line 499, in newfunc
[00:04:01]     return t(*(arg + (d,)), **kw)
[00:04:01]   File "C:\Miniconda35\envs\test-environment\lib\site-packages\datalad\interface\tests\test_run.py", line 527, in test_new_or_modified
[00:04:01]     {"to_modify", "d/to_modify"})
[00:04:01] AssertionError: {'to_modify', 'd\\to_modify'} != {'d/to_modify', 'to_modify'}

```

**Comment by mih** [comment]
Waiting for #2546

**Comment by mih** [comment]
```
[00:15:30] ======================================================================
[00:15:30] FAIL: datalad.plugin.tests.test_addurls.test_extract
[00:15:30] ----------------------------------------------------------------------
[00:15:30] Traceback (most recent call last):
[00:15:30]   File "C:\Miniconda35\envs\test-environment\lib\site-packages\nose\case.py", line 198, in runTest
[00:15:30]     self.test(*self.arg)
[00:15:30]   File "C:\Miniconda35\envs\test-environment\lib\site-packages\datalad\plugin\tests\test_addurls.py", line 230, in test_extract
[00:15:30]     {"kid", "kid/no", "adult", "adult/yes", "adult/no"})
[00:15:30] AssertionError: {'kid', 'adult', 'adult\\no', 'kid\\no', 'adult\\yes'} != {'adult/no', 'kid', 'kid/no', 'adult/yes', 'adult'}

[00:15:30] ======================================================================
[00:15:30] FAIL: datalad.plugin.tests.test_addurls.test_get_subpaths
[00:15:30] ----------------------------------------------------------------------
[00:15:30] Traceback (most recent call last):
[00:15:30]   File "C:\Miniconda35\envs\test-environment\lib\site-packages\nose\case.py", line 198, in runTest
[00:15:30]     self.test(*self.arg)
[00:15:30]   File "C:\Miniconda35\envs\test-environment\lib\site-packages\datalad\plugin\tests\test_addurls.py", line 126, in test_get_subpaths
[00:15:30]     eq_(au.get_subpaths(fname), expect)
[00:15:30] AssertionError: ('p1\\n', ['p1']) != ('p1/n', ['p1'])

[00:15:30] ======================================================================
[00:15:30] FAIL: datalad.interface.tests.test_run.test_new_or_modified
[00:15:30] ----------------------------------------------------------------------
[00:15:30] Traceback (most recent call last):
[00:15:30]   File "C:\Miniconda35\envs\test-environment\lib\site-packages\nose\case.py", line 198, in runTest
[00:15:30]     self.test(*self.arg)
[00:15:30]   File "C:\Miniconda35\envs\test-environment\lib\site-packages\datalad\tests\utils.py", line 499, in newfunc
[00:15:30]     return t(*(arg + (d,)), **kw)
[00:15:30]   File "C:\Miniconda35\envs\test-environment\lib\site-packages\datalad\interface\tests\test_run.py", line 557, in test_new_or_modified
[00:15:30]     {"to_modify", "d/to_modify"})
[00:15:30] AssertionError: {'d\\to_modify', 'to_modify'} != {'to_modify', 'd/to_modify'}

[00:15:30] ======================================================================
[00:15:30] FAIL: datalad.distribution.tests.test_utils.test_get_flexible_source_candidates
[00:15:30] ----------------------------------------------------------------------
[00:15:30] Traceback (most recent call last):
[00:15:30]   File "C:\Miniconda35\envs\test-environment\lib\site-packages\nose\case.py", line 198, in runTest
[00:15:30]     self.test(*self.arg)
[00:15:30]   File "C:\Miniconda35\envs\test-environment\lib\site-packages\datalad\distribution\tests\test_utils.py", line 43, in test_get_flexible_source_candidates
[00:15:30]     eq_(f('../r', '.'), ['../r'])
[00:15:30] AssertionError: ['..\\r'] != ['../r']

```

**Comment by mih** [comment]
We do not need a global issue for this, the code base is still full of them.
