### ISSUE TITLE
Potential issue with http_serve helper

### ISSUE THREAD

**Issue by mih** [datalad/datalad#2535]
It seems unlikely that HTTP requests would not work on windows...
```
[00:04:01] ======================================================================
[00:04:01] ERROR: datalad.interface.tests.test_download_url.test_download_url_return
[00:04:01] ----------------------------------------------------------------------
[00:04:01] Traceback (most recent call last):
[00:04:01]   File "C:\Miniconda35\envs\test-environment\lib\site-packages\nose\case.py", line 198, in runTest
[00:04:01]     self.test(*self.arg)
[00:04:01]   File "C:\Miniconda35\envs\test-environment\lib\site-packages\datalad\tests\utils.py", line 1138, in newfunc
[00:04:01]     reraise(*exc_info)
[00:04:01]   File "C:\Miniconda35\envs\test-environment\lib\site-packages\six.py", line 693, in reraise
[00:04:01]     raise value
[00:04:01]   File "C:\Miniconda35\envs\test-environment\lib\site-packages\datalad\tests\utils.py", line 1114, in newfunc
[00:04:01]     func(*args, **kwargs)
[00:04:01]   File "C:\Miniconda35\envs\test-environment\lib\site-packages\datalad\tests\utils.py", line 499, in newfunc
[00:04:01]     return t(*(arg + (d,)), **kw)
[00:04:01]   File "C:\Miniconda35\envs\test-environment\lib\site-packages\datalad\tests\utils.py", line 610, in newfunc
[00:04:01]     return tfunc(*(args + (path, url)), **kwargs)
[00:04:01]   File "C:\Miniconda35\envs\test-environment\lib\site-packages\datalad\tests\utils.py", line 669, in newfunc
[00:04:01]     return t(*(arg + (filename,)), **kw)
[00:04:01]   File "C:\Miniconda35\envs\test-environment\lib\contextlib.py", line 77, in __exit__
[00:04:01]     self.gen.throw(type, value, traceback)
[00:04:01]   File "C:\Miniconda35\envs\test-environment\lib\site-packages\datalad\utils.py", line 1307, in make_tempfile
[00:04:01]     yield filename
[00:04:01]   File "C:\Miniconda35\envs\test-environment\lib\site-packages\datalad\tests\utils.py", line 669, in newfunc
[00:04:01]     return t(*(arg + (filename,)), **kw)
[00:04:01]   File "C:\Miniconda35\envs\test-environment\lib\site-packages\datalad\interface\tests\test_download_url.py", line 59, in test_download_url_return
[00:04:01]     out3 = download_url(urls, path=outdir, overwrite=True)
[00:04:01]   File "C:\Miniconda35\envs\test-environment\lib\contextlib.py", line 77, in __exit__
[00:04:01]     self.gen.throw(type, value, traceback)
[00:04:01]   File "C:\Miniconda35\envs\test-environment\lib\site-packages\datalad\utils.py", line 884, in swallow_outputs
[00:04:01]     yield adapter
[00:04:01]   File "C:\Miniconda35\envs\test-environment\lib\site-packages\datalad\interface\tests\test_download_url.py", line 59, in test_download_url_return
[00:04:01]     out3 = download_url(urls, path=outdir, overwrite=True)
[00:04:01]   File "C:\Miniconda35\envs\test-environment\lib\site-packages\datalad\interface\download_url.py", line 110, in __call__
[00:04:01]     raise RuntimeError("%d url(s) failed to download" % len(failed_urls))
[00:04:01] RuntimeError: 2 url(s) failed to download
[00:04:01] -------------------- >> begin captured logging << --------------------
[00:04:01] urllib3.connectionpool: DEBUG: Starting new HTTP connection (1): 127.0.0.1
[00:04:01] urllib3.connectionpool: DEBUG: http://127.0.0.1:1093 "GET /file1.txt HTTP/1.1" 200 3
[00:04:01] urllib3.connectionpool: DEBUG: Resetting dropped connection: 127.0.0.1
[00:04:01] urllib3.connectionpool: DEBUG: http://127.0.0.1:1093 "GET /file1.txt HTTP/1.1" 200 3
[00:04:01] urllib3.connectionpool: DEBUG: Starting new HTTP connection (2): 127.0.0.1
[00:04:01] urllib3.connectionpool: DEBUG: http://127.0.0.1:1093 "GET /file2.txt HTTP/1.1" 200 3
[00:04:01] urllib3.connectionpool: DEBUG: Resetting dropped connection: 127.0.0.1
[00:04:01] urllib3.connectionpool: DEBUG: http://127.0.0.1:1093 "GET /file1.txt HTTP/1.1" 200 3
[00:04:01] urllib3.connectionpool: DEBUG: Resetting dropped connection: 127.0.0.1
[00:04:01] urllib3.connectionpool: DEBUG: http://127.0.0.1:1093 "GET /file2.txt HTTP/1.1" 200 3
[00:04:01] --------------------- >> end captured logging << ---------------------
```

**Comment by mih** [comment]
More evidence:

```
[00:15:30] ======================================================================
[00:15:30] FAIL: datalad.tests.test_tests_utils.test_serve_path_via_http(' ;abc',)
[00:15:30] ----------------------------------------------------------------------
[00:15:30] Traceback (most recent call last):
[00:15:30]   File "C:\Miniconda35\envs\test-environment\lib\site-packages\nose\case.py", line 198, in runTest
[00:15:30]     self.test(*self.arg)
[00:15:30]   File "C:\Miniconda35\envs\test-environment\lib\site-packages\datalad\tests\utils.py", line 669, in newfunc
[00:15:30]     return t(*(arg + (filename,)), **kw)
[00:15:30]   File "C:\Miniconda35\envs\test-environment\lib\site-packages\datalad\tests\test_tests_utils.py", line 424, in _test_serve_path_via_http
[00:15:30]     test_path_and_url()
[00:15:30]   File "C:\Miniconda35\envs\test-environment\lib\site-packages\datalad\tests\utils.py", line 610, in newfunc
[00:15:30]     return tfunc(*(args + (path, url)), **kwargs)
[00:15:30]   File "C:\Miniconda35\envs\test-environment\lib\site-packages\datalad\tests\test_tests_utils.py", line 407, in test_path_and_url
[00:15:30]     assert_false('http_proxy' in os.environ)
[00:15:30] AssertionError: True is not false
[00:15:30] 
[00:15:30] ======================================================================
[00:15:30] FAIL: datalad.tests.test_tests_utils.test_without_http_proxy
[00:15:30] ----------------------------------------------------------------------
[00:15:30] Traceback (most recent call last):
[00:15:30]   File "C:\Miniconda35\envs\test-environment\lib\site-packages\nose\case.py", line 198, in runTest
[00:15:30]     self.test(*self.arg)
[00:15:30]   File "C:\Miniconda35\envs\test-environment\lib\site-packages\datalad\tests\test_tests_utils.py", line 454, in test_without_http_proxy
[00:15:30]     check(1)
[00:15:30]   File "C:\Miniconda35\envs\test-environment\lib\site-packages\datalad\tests\utils.py", line 640, in newfunc
[00:15:30]     return tfunc(*args, **kwargs)
[00:15:30]   File "C:\Miniconda35\envs\test-environment\lib\site-packages\datalad\tests\test_tests_utils.py", line 447, in check
[00:15:30]     assert_false('http_proxy' in os.environ)
[00:15:30] AssertionError: True is not false

```

**Comment by mih** [comment]
There are now tests that use this helper continuously running on Github CI, appveyor, and a real win10 box.
