### ISSUE TITLE
os.symlink() works on recent windows version, but does not do a POSIX thing!

### ISSUE THREAD

**Issue by mih** [datalad/datalad#2536]
A symlink on windows is its own entity that does not magically resolve to the target. Hence all test that assume this behavior must not be executed on windows to avoid false-positive. For example:

```
[00:04:01] ======================================================================
[00:04:01] ERROR: datalad.interface.tests.test_save.test_symlinked_relpath
[00:04:01] ----------------------------------------------------------------------
[00:04:01] Traceback (most recent call last):
[00:04:01]   File "C:\Miniconda35\envs\test-environment\lib\site-packages\nose\case.py", line 198, in runTest
[00:04:01]     self.test(*self.arg)
[00:04:01]   File "C:\Miniconda35\envs\test-environment\lib\site-packages\datalad\tests\utils.py", line 669, in newfunc
[00:04:01]     return t(*(arg + (filename,)), **kw)
[00:04:01]   File "C:\Miniconda35\envs\test-environment\lib\contextlib.py", line 77, in __exit__
[00:04:01]     self.gen.throw(type, value, traceback)
[00:04:01]   File "C:\Miniconda35\envs\test-environment\lib\site-packages\datalad\utils.py", line 1307, in make_tempfile
[00:04:01]     yield filename
[00:04:01]   File "C:\Miniconda35\envs\test-environment\lib\site-packages\datalad\tests\utils.py", line 669, in newfunc
[00:04:01]     return t(*(arg + (filename,)), **kw)
[00:04:01]   File "C:\Miniconda35\envs\test-environment\lib\site-packages\datalad\interface\tests\test_save.py", line 360, in test_symlinked_relpath
[00:04:01]     ds.save("committing", path="./mike2")
[00:04:01]   File "C:\Miniconda35\envs\test-environment\lib\site-packages\datalad\distribution\dataset.py", line 439, in apply_func
[00:04:01]     return f(**kwargs)
[00:04:01]   File "C:\Miniconda35\envs\test-environment\lib\site-packages\datalad\interface\utils.py", line 470, in eval_func
[00:04:01]     return return_func(generator_func)(*args, **kwargs)
[00:04:01]   File "C:\Miniconda35\envs\test-environment\lib\site-packages\datalad\interface\utils.py", line 458, in return_func
[00:04:01]     results = list(results)
[00:04:01]   File "C:\Miniconda35\envs\test-environment\lib\site-packages\datalad\interface\utils.py", line 446, in generator_func
[00:04:01]     msg="Command did not complete successfully")
[00:04:01] datalad.support.exceptions.IncompleteResultsError: Command did not complete successfully [{'path': 'C:\\Users\\appveyor\\AppData\\Local\\Temp\\1\\datalad_temp_x6th9eot\\linked\\mike2', 'action': 'save', 'status': 'impossible', 'parentds': 'C:\\Users\\appveyor\\AppData\\Local\\Temp\\1\\datalad_temp_x6th9eot\\linked', 'refds': 'C:\\Users\\appveyor\\AppData\\Local\\Temp\\1\\datalad_temp_x6th9eot\\linked', 'message': ('path does not exist: %s', 'C:\\Users\\appveyor\\AppData\\Local\\Temp\\1\\datalad_temp_x6th9eot\\linked\\mike2'), 'raw_input': True, 'state': 'absent', 'orig_request': './mike2'}]
```

**Comment by mih** [comment]
Apparently, having symlinks behave like symlinks is configurable on Windows now, and the Git installer asks how one wants it.

It looks more an more that we should stay away from platform checks and move towards platform capability checks like annex does.
