### ISSUE TITLE
GitPython on Windows does not find `git`

### ISSUE THREAD

**Issue by mih** [datalad/datalad#2537]
```
[00:02:42] ======================================================================
[00:02:42] ERROR: datalad.support.tests.test_annexrepo.test_AnnexRepo_backend_option
[00:02:42] ----------------------------------------------------------------------
[00:02:42] Traceback (most recent call last):
[00:02:42]   File "C:\Miniconda35\envs\test-environment\lib\site-packages\git\cmd.py", line 735, in execute
[00:02:42]     **subprocess_kwargs
[00:02:42]   File "C:\Miniconda35\envs\test-environment\lib\subprocess.py", line 845, in __init__
[00:02:42]     _cleanup()
[00:02:42]   File "C:\Miniconda35\envs\test-environment\lib\subprocess.py", line 505, in _cleanup
[00:02:42]     res = inst._internal_poll(_deadstate=sys.maxsize)
[00:02:42]   File "C:\Miniconda35\envs\test-environment\lib\subprocess.py", line 1255, in _internal_poll
[00:02:42]     if _WaitForSingleObject(self._handle, 0) == _WAIT_OBJECT_0:
[00:02:42] OSError: [WinError 6] The handle is invalid
[00:02:42] 
[00:02:42] During handling of the above exception, another exception occurred:
[00:02:42] 
[00:02:42] Traceback (most recent call last):
[00:02:42]   File "C:\Miniconda35\envs\test-environment\lib\site-packages\nose\case.py", line 198, in runTest
[00:02:42]     self.test(*self.arg)
[00:02:42]   File "C:\Miniconda35\envs\test-environment\lib\site-packages\datalad\tests\utils.py", line 499, in newfunc
[00:02:42]     return t(*(arg + (d,)), **kw)
[00:02:42]   File "C:\Miniconda35\envs\test-environment\lib\site-packages\datalad\tests\utils.py", line 610, in newfunc
[00:02:42]     return tfunc(*(args + (path, url)), **kwargs)
[00:02:42]   File "C:\Miniconda35\envs\test-environment\lib\site-packages\datalad\support\tests\test_annexrepo.py", line 576, in test_AnnexRepo_backend_option
[00:02:42]     ar = AnnexRepo(path, backend='MD5')
[00:02:42]   File "C:\Miniconda35\envs\test-environment\lib\site-packages\datalad\support\repo.py", line 146, in __call__
[00:02:42]     instance = type.__call__(cls, *new_args, **new_kwargs)
[00:02:42]   File "C:\Miniconda35\envs\test-environment\lib\site-packages\datalad\support\annexrepo.py", line 185, in __init__
[00:02:42]     fake_dates=fake_dates)
[00:02:42]   File "C:\Miniconda35\envs\test-environment\lib\site-packages\datalad\support\gitrepo.py", line 578, in __init__
[00:02:42]     **git_opts)
[00:02:42]   File "C:\Miniconda35\envs\test-environment\lib\site-packages\datalad\cmd.py", line 186, in __call__
[00:02:42]     return self.call(cmd, *args, **kwargs)
[00:02:42]   File "C:\Miniconda35\envs\test-environment\lib\site-packages\datalad\cmd.py", line 565, in call
[00:02:42]     return f(*args, **kwargs)
[00:02:42]   File "C:\Miniconda35\envs\test-environment\lib\site-packages\git\repo\base.py", line 900, in init
[00:02:42]     git.init(**kwargs)
[00:02:42]   File "C:\Miniconda35\envs\test-environment\lib\site-packages\git\cmd.py", line 548, in <lambda>
[00:02:42]     return lambda *args, **kwargs: self._call_process(name, *args, **kwargs)
[00:02:42]   File "C:\Miniconda35\envs\test-environment\lib\site-packages\git\cmd.py", line 1014, in _call_process
[00:02:42]     return self.execute(call, **exec_kwargs)
[00:02:42]   File "C:\Miniconda35\envs\test-environment\lib\site-packages\git\cmd.py", line 738, in execute
[00:02:42]     raise GitCommandNotFound(command, err)
[00:02:42] git.exc.GitCommandNotFound: Cmd('git') not found due to: OSError('[WinError 6] The handle is invalid')
[00:02:42]   cmdline: git init
```

**Comment by mih** [comment]
Whatever it is, it is not what the title says. GitPython in normal/manual use works just fine on windows. 

When the test is ran in isolation, the results are much different:

```
C:\projects\datalad-5sgef>python -m nose datalad.support.tests.test_annexrepo:te
st_AnnexRepo_backend_option
E
======================================================================
ERROR: datalad.support.tests.test_annexrepo.test_AnnexRepo_backend_option
----------------------------------------------------------------------
Traceback (most recent call last):
  File "C:\Miniconda35\envs\test-environment\lib\site-packages\nose\case.py", li
ne 198, in runTest
    self.test(*self.arg)
  File "C:\projects\datalad-5sgef\datalad\tests\utils.py", line 499, in newfunc
    return t(*(arg + (d,)), **kw)
  File "C:\projects\datalad-5sgef\datalad\tests\utils.py", line 610, in newfunc
    return tfunc(*(args + (path, url)), **kwargs)
  File "C:\projects\datalad-5sgef\datalad\support\tests\test_annexrepo.py", line
 589, in test_AnnexRepo_backend_option
    eq_(ar.get_file_backend('remotefile2'), 'SHA1')
  File "C:\projects\datalad-5sgef\datalad\support\gitrepo.py", line 301, in newf
unc
    result = func(self, files_new, *args, **kwargs)
  File "C:\projects\datalad-5sgef\datalad\support\annexrepo.py", line 2947, in g
et_file_backend
    return [self.get_file_key(f).split('-')[0] for f in files]
  File "C:\projects\datalad-5sgef\datalad\support\annexrepo.py", line 2947, in <
listcomp>
    return [self.get_file_key(f).split('-')[0] for f in files]
  File "C:\projects\datalad-5sgef\datalad\support\gitrepo.py", line 301, in newf
unc
    result = func(self, files_new, *args, **kwargs)
  File "C:\projects\datalad-5sgef\datalad\support\annexrepo.py", line 1601, in g
et_file_key
    raise IOError(e.code, "File not found.", files)
PermissionError: [Errno 1] File not found.: 'remotefile2'
-------------------- >> begin captured logging << --------------------
datalad.utils: Level 5: Importing datalad.utils
datalad.utils: Level 5: Done importing datalad.utils
datalad.cmd: Level 9: Will use git under '' (no adjustments to PATH if empty str
ing)
datalad.cmd: Level 9: Running: ['git', 'version']
datalad.cmd: Level 8: Finished running ['git', 'version'] with status 0
datalad.cmd: Level 9: Running: ['git', 'config', '-z', '-l', '--show-origin']
datalad.cmd: Level 8: Finished running ['git', 'config', '-z', '-l', '--show-ori
gin'] with status 0
datalad.ui: Level 5: Starting importing ui
datalad.ui.dialog: Level 5: Starting importing ui.dialog
datalad.ui.dialog: Level 5: Done importing ui.dialog
datalad.ui: Level 5: Initiating UI switcher
datalad.ui: DEBUG: UI set to ConsoleLog(out=<StringIO>)
datalad.ui: Level 5: Done importing ui
--------------------- >> end captured logging << ---------------------

----------------------------------------------------------------------
Ran 1 test in 4.746s

FAILED (errors=1)
```

The original failure can be replicated, if the entire test module is run. I suspect that something fucks up the state of GitPython in one of the test. I assume this is a testrepo issue, as those repos persist across tests and would then introduce failure to any other test using that testrepo.

**Comment by mih** [comment]
The former, which is implied by the latter -- so it shouldn't matter.

**Comment by bpoldrack** [comment]
Doesn't matter for replication but for narrowing down where the mess is happening.

**Comment by yarikoptic** [comment]
I do not think that original issue is only about running tests "in isolation" since as https://ci.appveyor.com/project/mih/datalad/build/1.0.494/job/ongu8fi5jovxwqqu shows (part of the wild try in https://github.com/datalad/datalad/pull/2791) which runs all the tests, and it is the case as well.  I thought, probably incorrectly, that for GitPython we do set location of git to be the one which comes bundled with git-annex. May be that is where we are doing it wrong.
