### ISSUE TITLE
test for SSH on windows is wrong

### ISSUE THREAD

**Issue by mih** [datalad/datalad#2539]
SSH comes with Git for windows. See #1569 
```
[00:02:42] ======================================================================
[00:02:42] FAIL: datalad.support.tests.test_external_versions.test_system_ssh_version
[00:02:42] ----------------------------------------------------------------------
[00:02:42] Traceback (most recent call last):
[00:02:42]   File "C:\Miniconda35\envs\test-environment\lib\site-packages\nose\case.py", line 198, in runTest
[00:02:42]     self.test(*self.arg)
[00:02:42]   File "C:\Miniconda35\envs\test-environment\lib\site-packages\datalad\support\tests\test_external_versions.py", line 217, in test_system_ssh_version
[00:02:42]     assert ev['cmd:system-ssh']  # usually we have some available at boxes we test
[00:02:42] AssertionError
[00:02:42] 
```

**Comment by mih** [comment]
Also

```
[00:02:42] ======================================================================
[00:02:42] ERROR: datalad.support.tests.test_sshconnector.test_ssh_manager_close_no_throw
[00:02:42] ----------------------------------------------------------------------
[00:02:42] Traceback (most recent call last):
[00:02:42]   File "C:\Miniconda35\envs\test-environment\lib\site-packages\nose\case.py", line 198, in runTest
[00:02:42]     self.test(*self.arg)
[00:02:42]   File "C:\Miniconda35\envs\test-environment\lib\site-packages\datalad\tests\utils.py", line 669, in newfunc
[00:02:42]     return t(*(arg + (filename,)), **kw)
[00:02:42]   File "C:\Miniconda35\envs\test-environment\lib\contextlib.py", line 77, in __exit__
[00:02:42]     self.gen.throw(type, value, traceback)
[00:02:42]   File "C:\Miniconda35\envs\test-environment\lib\site-packages\datalad\utils.py", line 1307, in make_tempfile
[00:02:42]     yield filename
[00:02:42]   File "C:\Miniconda35\envs\test-environment\lib\site-packages\datalad\tests\utils.py", line 669, in newfunc
[00:02:42]     return t(*(arg + (filename,)), **kw)
[00:02:42]   File "C:\Miniconda35\envs\test-environment\lib\site-packages\datalad\support\tests\test_sshconnector.py", line 134, in test_ssh_manager_close_no_throw
[00:02:42]     manager = SSHManager()
[00:02:42]   File "C:\Miniconda35\envs\test-environment\lib\site-packages\datalad\support\sshconnector.py", line 350, in __init__
[00:02:42]     not_supported_on_windows("TODO: Make this an abstraction to "
[00:02:42]   File "C:\Miniconda35\envs\test-environment\lib\site-packages\datalad\utils.py", line 122, in not_supported_on_windows
[00:02:42]     + (": %s" % msg if msg else ""))
[00:02:42] NotImplementedError: This functionality is not yet implemented for Windows OS: TODO: Make this an abstraction to interface platform dependent SSH

```
