### ISSUE TITLE
Unicode issues on Windows

### ISSUE THREAD

**Issue by mih** [datalad/datalad#2561]
```
[00:15:30] ======================================================================
[00:15:30] FAIL: datalad.tests.test_utils.test_read_csv_lines_tsv_unicode
[00:15:30] ----------------------------------------------------------------------
[00:15:30] Traceback (most recent call last):
[00:15:30]   File "C:\Miniconda35\envs\test-environment\lib\site-packages\nose\case.py", line 198, in runTest
[00:15:30]     self.test(*self.arg)
[00:15:30]   File "C:\Miniconda35\envs\test-environment\lib\site-packages\datalad\tests\utils.py", line 669, in newfunc
[00:15:30]     return t(*(arg + (filename,)), **kw)
[00:15:30]   File "C:\Miniconda35\envs\test-environment\lib\site-packages\datalad\tests\test_utils.py", line 979, in test_read_csv_lines_tsv_unicode
[00:15:30]     {u'h1': u'v1', u'h2': u'\u0434\u0430\u0442\u0430'},
[00:15:30] AssertionError: [{'h1': 'v1', 'h2': 'дата'}] != [{'h1': 'v1', 'h2': '\u0434\u0430\u0442\u0430'}]
```

**Comment by mih** [comment]
```
[00:15:30] ======================================================================
[00:15:30] ERROR: datalad.tests.test_cmd.test_runner_log_stdout
[00:15:30] ----------------------------------------------------------------------
[00:15:30] Traceback (most recent call last):
[00:15:30]   File "C:\Miniconda35\envs\test-environment\lib\site-packages\nose\case.py", line 198, in runTest
[00:15:30]     self.test(*self.arg)
[00:15:30]   File "C:\Miniconda35\envs\test-environment\lib\site-packages\datalad\tests\utils.py", line 1325, in newfunc
[00:15:30]     func(*args, **kwargs)
[00:15:30]   File "C:\Miniconda35\envs\test-environment\lib\site-packages\datalad\tests\test_cmd.py", line 160, in test_runner_log_stdout
[00:15:30]     ret = runner.run(cmd, log_stdout=True, **kw)
[00:15:30]   File "C:\Miniconda35\envs\test-environment\lib\site-packages\datalad\cmd.py", line 513, in run
[00:15:30]     out = tuple(map(decode_if_not_None, out))
[00:15:30]   File "C:\Miniconda35\envs\test-environment\lib\site-packages\datalad\cmd.py", line 511, in decode_if_not_None
[00:15:30]     return "" if x is None else binary_type.decode(x)
[00:15:30] UnicodeDecodeError: 'utf-8' codec can't decode byte 0x84 in position 16: invalid start byte
[00:15:30] -------------------- >> begin captured logging << --------------------
[00:15:30] datalad.cmd: Level 9: Running: ['echo', 'stdout-Message ���\u6771 should be logged']
[00:15:30] --------------------- >> end captured logging << ---------------------

```

**Comment by mih** [comment]
Digging into this more I find that unicode handling is a big issue for us on Windows. However, I am not even sure if our test setups are properly configured, or what that even means. I think it makes sense to disable unicode use in the tests on windows for now, in order to make the general problem (have it working) on Windows more manageable. Once we have a large-ish test battery running, we can bring them back and investigate the topic separately from everything else that is presently going on.

**Comment by mih** [comment]
I am closing this issue, the info here is outdated and does not inform further work anymore.
