### ISSUE TITLE
`import_modules` broken on  Windows (or just its test)

### ISSUE THREAD

**Issue by mih** [datalad/datalad#2565]
```
[00:15:30] ======================================================================
[00:15:30] FAIL: datalad.tests.test_utils.test_import_modules
[00:15:30] ----------------------------------------------------------------------
[00:15:30] Traceback (most recent call last):
[00:15:30]   File "C:\Miniconda35\envs\test-environment\lib\site-packages\nose\case.py", line 198, in runTest
[00:15:30]     self.test(*self.arg)
[00:15:30]   File "C:\Miniconda35\envs\test-environment\lib\site-packages\datalad\tests\utils.py", line 499, in newfunc
[00:15:30]     return t(*(arg + (d,)), **kw)
[00:15:30]   File "C:\Miniconda35\envs\test-environment\lib\site-packages\datalad\tests\test_utils.py", line 1017, in test_import_modules
[00:15:30]     eq_(len(mods), 1)
[00:15:30] AssertionError: 0 != 1
```

**Comment by mih** [comment]
Works on master as of now.
