### ISSUE TITLE
`find_files` broken on Windows

### ISSUE THREAD

**Issue by mih** [datalad/datalad#2566]
```
[00:15:30] ======================================================================
[00:15:30] FAIL: datalad.tests.test_utils.test_find_files
[00:15:30] ----------------------------------------------------------------------
[00:15:30] Traceback (most recent call last):
[00:15:30]   File "C:\Miniconda35\envs\test-environment\lib\site-packages\nose\case.py", line 198, in runTest
[00:15:30]     self.test(*self.arg)
[00:15:30]   File "C:\Miniconda35\envs\test-environment\lib\site-packages\datalad\tests\test_utils.py", line 482, in test_find_files
[00:15:30]     assert_in(opj(tests_dir, 'test_utils.py'), files3)
[00:15:30] AssertionError: 'C:\\Miniconda35\\envs\\test-environment\\lib\\site-packages\\datalad\\tests\\test_utils.py' not found in []
[00:15:30] 
[00:15:30] ======================================================================
[00:15:30] FAIL: datalad.tests.test_utils.test_find_files_exclude_vcs
[00:15:30] ----------------------------------------------------------------------
[00:15:30] Traceback (most recent call last):
[00:15:30]   File "C:\Miniconda35\envs\test-environment\lib\site-packages\nose\case.py", line 198, in runTest
[00:15:30]     self.test(*self.arg)
[00:15:30]   File "C:\Miniconda35\envs\test-environment\lib\site-packages\datalad\tests\utils.py", line 499, in newfunc
[00:15:30]     return t(*(arg + (d,)), **kw)
[00:15:30]   File "C:\Miniconda35\envs\test-environment\lib\site-packages\datalad\tests\test_utils.py", line 500, in test_find_files_exclude_vcs
[00:15:30]     assert_equal({basename(f) for f in files}, {'d1', 'git'})
[00:15:30] AssertionError: Items in the first set but not the second:
[00:15:30] '.git'
[00:15:30] '1'
```

**Comment by mih** [comment]
Still the case today.
