### ISSUE TITLE
Need line-ending equalizer for Windows tests

### ISSUE THREAD

**Issue by mih** [datalad/datalad#2567]
To cover stuff like this:

```
[00:15:30] ======================================================================
[00:15:30] FAIL: datalad.tests.test_protocols.test_protocol_commons
[00:15:30] ----------------------------------------------------------------------
[00:15:30] Traceback (most recent call last):
[00:15:30]   File "C:\Miniconda35\envs\test-environment\lib\site-packages\nose\case.py", line 198, in runTest
[00:15:30]     self.test(*self.arg)
[00:15:30]   File "C:\Miniconda35\envs\test-environment\lib\site-packages\datalad\tests\utils.py", line 669, in newfunc
[00:15:30]     return t(*(arg + (filename,)), **kw)
[00:15:30]   File "C:\Miniconda35\envs\test-environment\lib\site-packages\datalad\tests\test_protocols.py", line 61, in test_protocol_commons
[00:15:30]     assert_equal(str_, read_str)
[00:15:30] AssertionError: "Dry run protocol:\r\n\r\ncommand: ['some_command', 'some_op[42 chars]\r\n" != "Dry run protocol:\n\n\n\ncommand: ['some_command', 'some_op[42 chars]\n\n"
[00:15:30] - Dry run protocol:

[00:15:30] ?                  -
[00:15:30] + Dry run protocol:
[00:15:30] - 

[00:15:30] + 
[00:15:30] + 
[00:15:30] + 
[00:15:30] - command: ['some_command', 'some_option']

[00:15:30] ?                                         -
[00:15:30] + command: ['some_command', 'some_option']
[00:15:30] - 

[00:15:30] + 
[00:15:30] + 
[00:15:30] + 
[00:15:30] - command: ['another_command']

[00:15:30] ?                             -
[00:15:30] + command: ['another_command']
[00:15:30] + 
[00:15:30] 
[00:15:30] 

```

**Comment by mih** [comment]
```
[00:15:30] ======================================================================
[00:15:30] FAIL: datalad.tests.test_cmd.test_process_remaining_output
[00:15:30] ----------------------------------------------------------------------
[00:15:30] Traceback (most recent call last):
[00:15:30]   File "C:\Miniconda35\envs\test-environment\lib\site-packages\nose\case.py", line 198, in runTest
[00:15:30]     self.test(*self.arg)
[00:15:30]   File "C:\Miniconda35\envs\test-environment\lib\site-packages\datalad\tests\test_cmd.py", line 326, in test_process_remaining_output
[00:15:30]     eq_(runner._process_remaining_output(None, out_bytes, *args), target)
[00:15:30] AssertionError: b's\n\xd0\xbf\n\r\n' != b's\r\n\xd0\xbf\r\n'

```

**Comment by mih** [comment]
Tons of such tests have been rectified over the past years.
