### ISSUE TITLE
Color formatter test should not run in Windows shell

### ISSUE THREAD

**Issue by mih** [datalad/datalad#2568]
```
[00:15:30] ======================================================================
[00:15:30] FAIL: datalad.tests.test_log.test_color_formatter
[00:15:30] ----------------------------------------------------------------------
[00:15:30] Traceback (most recent call last):
[00:15:30]   File "C:\Miniconda35\envs\test-environment\lib\site-packages\nose\case.py", line 198, in runTest
[00:15:30]     self.test(*self.arg)
[00:15:30]   File "C:\Miniconda35\envs\test-environment\lib\site-packages\datalad\tests\test_log.py", line 146, in test_color_formatter
[00:15:30]     (assert_in if use_color else assert_not_in)(colors.RESET_SEQ, cf.format(rec))
[00:15:30] AssertionError: '\x1b[0m' not found in '[DEBUG] very long message '
```

**Comment by yarikoptic** [comment]
I thought coloring is possible with colorama's help

**Comment by mih** [comment]
Color works fine on windows with colorama, indeed.
