### ISSUE TITLE
Any test involving inodes should not run on Windows

### ISSUE THREAD

**Issue by mih** [datalad/datalad#2569]
FAT or NTFS don't have this concept.

Some of these errors look as if we rely on inodes to be meaningful for some functionality. This should obviously be fixed.

```
[00:15:30] ======================================================================
[00:15:30] FAIL: datalad.tests.test_cmd.test_link_file_load
[00:15:30] ----------------------------------------------------------------------
[00:15:30] Traceback (most recent call last):
[00:15:30]   File "C:\Miniconda35\envs\test-environment\lib\site-packages\nose\case.py", line 198, in runTest
[00:15:30]     self.test(*self.arg)
[00:15:30]   File "C:\Miniconda35\envs\test-environment\lib\site-packages\datalad\tests\utils.py", line 669, in newfunc
[00:15:30]     return t(*(arg + (filename,)), **kw)
[00:15:30]   File "C:\Miniconda35\envs\test-environment\lib\site-packages\datalad\tests\test_cmd.py", line 276, in test_link_file_load
[00:15:30]     ok_(inode(tempfile) != inode(tempfile2))
[00:15:30] AssertionError

[00:15:30] ======================================================================
[00:15:30] ERROR: datalad.support.tests.test_annexrepo.test_AnnexRepo_flyweight_monitoring_inode
[00:15:30] ----------------------------------------------------------------------
[00:15:30] Traceback (most recent call last):
[00:15:30]   File "C:\Miniconda35\envs\test-environment\lib\site-packages\nose\case.py", line 198, in runTest
[00:15:30]     self.test(*self.arg)
[00:15:30]   File "C:\Miniconda35\envs\test-environment\lib\site-packages\datalad\tests\utils.py", line 669, in newfunc
[00:15:30]     return t(*(arg + (filename,)), **kw)
[00:15:30]   File "C:\Miniconda35\envs\test-environment\lib\site-packages\datalad\tests\utils.py", line 669, in newfunc
[00:15:30]     return t(*(arg + (filename,)), **kw)
[00:15:30]   File "C:\Miniconda35\envs\test-environment\lib\site-packages\datalad\support\tests\test_annexrepo.py", line 2256, in test_AnnexRepo_flyweight_monitoring_inode
[00:15:30]     check_repo_deals_with_inode_change(AnnexRepo, path, store)
[00:15:30]   File "C:\Miniconda35\envs\test-environment\lib\site-packages\datalad\support\tests\utils.py", line 24, in check_repo_deals_with_inode_change
[00:15:30]     hexsha = repo.repo.head.object.hexsha
[00:15:30]   File "C:\Miniconda35\envs\test-environment\lib\site-packages\git\refs\symbolic.py", line 193, in _get_object
[00:15:30]     return Object.new_from_sha(self.repo, hex_to_bin(self.dereference_recursive(self.repo, self.path)))
[00:15:30]   File "C:\Miniconda35\envs\test-environment\lib\site-packages\git\refs\symbolic.py", line 135, in dereference_recursive
[00:15:30]     hexsha, ref_path = cls._get_ref_info(repo, ref_path)
[00:15:30]   File "C:\Miniconda35\envs\test-environment\lib\site-packages\git\refs\symbolic.py", line 184, in _get_ref_info
[00:15:30]     return cls._get_ref_info_helper(repo, ref_path)
[00:15:30]   File "C:\Miniconda35\envs\test-environment\lib\site-packages\git\refs\symbolic.py", line 167, in _get_ref_info_helper
[00:15:30]     raise ValueError("Reference at %r does not exist" % ref_path)
[00:15:30] ValueError: Reference at 'refs/heads/annex/direct/master' does not exist

[00:15:30] ======================================================================
[00:15:30] ERROR: datalad.support.tests.test_gitrepo.test_GitRepo_flyweight_monitoring_inode
[00:15:30] ----------------------------------------------------------------------
[00:15:30] Traceback (most recent call last):
[00:15:30]   File "C:\Miniconda35\envs\test-environment\lib\site-packages\nose\case.py", line 198, in runTest
[00:15:30]     self.test(*self.arg)
[00:15:30]   File "C:\Miniconda35\envs\test-environment\lib\site-packages\datalad\tests\utils.py", line 669, in newfunc
[00:15:30]     return t(*(arg + (filename,)), **kw)
[00:15:30]   File "C:\Miniconda35\envs\test-environment\lib\site-packages\datalad\tests\utils.py", line 669, in newfunc
[00:15:30]     return t(*(arg + (filename,)), **kw)
[00:15:30]   File "C:\Miniconda35\envs\test-environment\lib\site-packages\datalad\support\tests\test_gitrepo.py", line 1153, in test_GitRepo_flyweight_monitoring_inode
[00:15:30]     check_repo_deals_with_inode_change(GitRepo, path, store)
[00:15:30]   File "C:\Miniconda35\envs\test-environment\lib\site-packages\datalad\support\tests\utils.py", line 32, in check_repo_deals_with_inode_change
[00:15:30]     rmtree(path)
[00:15:30]   File "C:\Miniconda35\envs\test-environment\lib\site-packages\datalad\utils.py", line 313, in rmtree
[00:15:30]     shutil.rmtree(path, *args, **kwargs)
[00:15:30]   File "C:\Miniconda35\envs\test-environment\lib\shutil.py", line 488, in rmtree
[00:15:30]     return _rmtree_unsafe(path, onerror)
[00:15:30]   File "C:\Miniconda35\envs\test-environment\lib\shutil.py", line 387, in _rmtree_unsafe
[00:15:30]     onerror(os.rmdir, path, sys.exc_info())
[00:15:30]   File "C:\Miniconda35\envs\test-environment\lib\shutil.py", line 385, in _rmtree_unsafe
[00:15:30]     os.rmdir(path)
[00:15:30] PermissionError: [WinError 32] The process cannot access the file because it is being used by another process: 'C:\\Users\\appveyor\\AppData\\Local\\Temp\\1\\datalad_temp_m9o9jneq'

```

**Comment by mih** [comment]
Tests either don't exist in this form anymore, or are properly skipped on windows.
