### ISSUE TITLE
Issue with date/time setup on Windows

### ISSUE THREAD

**Issue by mih** [datalad/datalad#2570]
It might just be the test environment, but not sure yet.

```
[00:15:30] ======================================================================
[00:15:30] ERROR: datalad.tests.test_utils.test_get_timestamp_suffix
[00:15:30] ----------------------------------------------------------------------
[00:15:30] Traceback (most recent call last):
[00:15:30]   File "C:\Miniconda35\envs\test-environment\lib\site-packages\datalad\tests\test_utils.py", line 611, in test_get_timestamp_suffix
[00:15:30]     time.tzset()
[00:15:30] AttributeError: module 'time' has no attribute 'tzset'
[00:15:30] 
[00:15:30] During handling of the above exception, another exception occurred:
[00:15:30] 
[00:15:30] Traceback (most recent call last):
[00:15:30]   File "C:\Miniconda35\envs\test-environment\lib\site-packages\nose\case.py", line 198, in runTest
[00:15:30]     self.test(*self.arg)
[00:15:30]   File "C:\Miniconda35\envs\test-environment\lib\site-packages\datalad\tests\test_utils.py", line 625, in test_get_timestamp_suffix
[00:15:30]     time.tzset()
[00:15:30] AttributeError: module 'time' has no attribute 'tzset'

```

**Comment by mih** [comment]
Duplicate of #2452
