### ISSUE TITLE
annex init fails on Windows

### ISSUE THREAD

**Issue by mih** [datalad/datalad#2571]
In more than one test ~~~(possibly all of them automagicio-related)~~~ -- example:
```
[00:15:30] ======================================================================
[00:15:30] ERROR: datalad.tests.test_auto.test_proxying_io_open_regular(<function test_proxying_io_open_regular.<locals>.generate_dat at 0x05B536A8>, <function test_proxying_io_open_regular.<locals>.verify_dat at 0x05B536F0>)
[00:15:30] ----------------------------------------------------------------------
[00:15:30] Traceback (most recent call last):
[00:15:30]   File "C:\Miniconda35\envs\test-environment\lib\site-packages\nose\case.py", line 198, in runTest
[00:15:30]     self.test(*self.arg)
[00:15:30]   File "C:\Miniconda35\envs\test-environment\lib\site-packages\datalad\tests\utils.py", line 669, in newfunc
[00:15:30]     return t(*(arg + (filename,)), **kw)
[00:15:30]   File "C:\Miniconda35\envs\test-environment\lib\contextlib.py", line 77, in __exit__
[00:15:30]     self.gen.throw(type, value, traceback)
[00:15:30]   File "C:\Miniconda35\envs\test-environment\lib\site-packages\datalad\utils.py", line 1341, in make_tempfile
[00:15:30]     yield filename
[00:15:30]   File "C:\Miniconda35\envs\test-environment\lib\site-packages\datalad\tests\utils.py", line 669, in newfunc
[00:15:30]     return t(*(arg + (filename,)), **kw)
[00:15:30]   File "C:\Miniconda35\envs\test-environment\lib\site-packages\datalad\tests\test_auto.py", line 117, in _test_proxying_open
[00:15:30]     annex2 = AnnexRepo.clone(repo, repo2)
[00:15:30]   File "C:\Miniconda35\envs\test-environment\lib\site-packages\datalad\support\gitrepo.py", line 739, in clone
[00:15:30]     gr = cls(path, *args, repo=repo, **kwargs)
[00:15:30]   File "C:\Miniconda35\envs\test-environment\lib\site-packages\datalad\support\repo.py", line 146, in __call__
[00:15:30]     instance = type.__call__(cls, *new_args, **new_kwargs)
[00:15:30]   File "C:\Miniconda35\envs\test-environment\lib\site-packages\datalad\support\annexrepo.py", line 229, in __init__
[00:15:30]     self._init(version=version, description=description)
[00:15:30]   File "C:\Miniconda35\envs\test-environment\lib\site-packages\datalad\support\annexrepo.py", line 1256, in _init
[00:15:30]     self._run_annex_command('init', annex_options=opts)
[00:15:30]   File "C:\Miniconda35\envs\test-environment\lib\site-packages\datalad\support\annexrepo.py", line 1053, in _run_annex_command
[00:15:30]     raise e
[00:15:30]   File "C:\Miniconda35\envs\test-environment\lib\site-packages\datalad\support\annexrepo.py", line 1045, in _run_annex_command
[00:15:30]     return self.cmd_call_wrapper.run(cmd_list, env=env, **kwargs)
[00:15:30]   File "C:\Miniconda35\envs\test-environment\lib\site-packages\datalad\cmd.py", line 670, in run
[00:15:30]     cmd, env=self.get_git_environ_adjusted(env), *args, **kwargs)
[00:15:30]   File "C:\Miniconda35\envs\test-environment\lib\site-packages\datalad\cmd.py", line 530, in run
[00:15:30]     raise CommandError(str(cmd), msg, status, out[0], out[1])
[00:15:30] datalad.support.exceptions.CommandError: CommandError: command '['git', '-c', 'receive.autogc=0', '-c', 'gc.auto=0', 'annex', 'init']' failed with exitcode 1
[00:15:30] Failed to run ['git', '-c', 'receive.autogc=0', '-c', 'gc.auto=0', 'annex', 'init'] under 'C:\\Users\\appveyor\\AppData\\Local\\Temp\\1\\datalad_temp_95ef7tvl_2'. Exit code=1. out=init  

[00:15:30] 

[00:15:30] 

[00:15:30] (merging origin/git-annex into git-annex...)

[00:15:30] (recording state in git...)

[00:15:30] 

[00:15:30] 

[00:15:30] failed

[00:15:30]  err=  Detected a filesystem without fifo support.

[00:15:30]   Disabling ssh connection caching.

[00:15:30]   Detected a crippled filesystem.

[00:15:30]   Enabling direct mode.

[00:15:30] git-annex: .git\annex\objects\5b7\d0f\SHA256E-s3--a665a45920422f9d417e4867efdc4fb8a04a1f3fff1fa07e998e86f7f7a27ae3\: openTempFile: does not exist (No such file or directory)

[00:15:30] git-annex: init: 1 failed
```

**Comment by yarikoptic** [comment]
I forgot about that issue of limited max path length on Windows (due API restrictive) - is it no longer the case somehow? Ref: https://msdn.microsoft.com/en-us/library/windows/desktop/aa365247(v=vs.85).aspx

**Comment by yarikoptic** [comment]
I think I've ran into this one also while trying to `datalad install -r`  which was surprising since I did not use `-g` so I guess it should have not fetched anything but then it pukes on some .nii.gz key:
![why](http://www.onerussian.com/tmp/gkrellShoot_07-13-18_140705.png)
and the file is actually there
![there](http://www.onerussian.com/tmp/gkrellShoot_07-13-18_140752.png)
@joeyh any ideas?  I think I've also spotted at some point the webapp web frontend to appear -- is webapp running by default on windows somehow?

**Comment by yarikoptic** [comment]
ah, this is a good old issue: http://git-annex.branchable.com/bugs/__34__git-annex__58___direct__58___1_failed__34___on_Windows/  . A resolution suggested was to enable long file names support.  In my case  I am on Windows 7 6.1.7601 ... not yet sure if long files support is possible on that beast

**Comment by joeyh** [comment]
Yaroslav Halchenko wrote:
> I think I've ran into this one also while trying to datalad install -r which
> was surprising since I did not use -g so I guess it should have not fetched
> anything but then it pukes on some .nii.gz key:
> why
> and the file is actually there
> there

Windows path limits are still very much an issue, and that is the
failure mode I've seen when the path is too long. It's traversing
all annex links in the repository to enable direct mode.

The full path is something like 
C:\\Users\\DatLad\\datalad\\labs\\gobbini\\famface\\data\.git\annex\objects\db3\781\SHA256E-s684528--\f43c828ffc1ad6cf854f8545f60c2d50f27ff3cfe8cabe2aa7a207cfb02b6f61281b.nii.gz
which is around 177 characters.. git-annex uses relative paths where it can and it
seems to have done so here, which is only 120 characters. The windows MAX_PATH is
actually supposed to be 260 characters, so it's a bit surprising it fails on that.

Although that path is to the object directory, the temp file within it would add
more length -- perhaps openTempFile is reporting the name of the directory it's
making the temp file in and not the full temp file path. It might also
be making the path absolute internally.

Running Linux git-annex in WSL is a good way to avoid all this horribleness,
it works pretty well except for one recent reversion in WSL that makes
sqlite crash.

> @joeyh any ideas? I think I've also spotted at some point the webapp web
> frontend to appear -- is webapp running by default on windows somehow?

There's a git-annex-autostart.vbs that gets linked to
"$SMSTARTUP/git-annex-autostart.lnk", but it runs git annex assistant
--autostart; while that will start the webapp if you've configured
git-annex to autostart in some repository, it will not open a web
browser on the webapp. (Aside from the nonsense of a visual basic script
that opens a hidden DOS box, this is identical to the Linux desktop
autostart that git-annex installs.)

There's a git-annex-webapp.vbs that gets linked to
"$SMPROGRAMS/Git Annex (Webapp).lnk" to put it on the Start menu
to open the web browser.

Not being a MS certified engineer, I can't comment as to what Windows
might do with items on the Start menu, as far as deciding to start them
without you clicking on them.. Noone has ever complained to me about
that happening.

-- 
see shy jo

**Comment by yarikoptic** [comment]
Thank you @joeyh for the details! -- FWIW I've tried on another repo (openfmri/ds0000001) where we used MD5E backend, so key names were shorter and everything seemed to work out nicely (could install/get/drop without problem), so indeed I guess I've ran into that path length issue.  I guess may be on this system the limit is even shorter.
FWIW -- added a check to `datalad wtf` to try creating files of growing length... got up to 259 successfully in that directory so that system is nohow special ;-)  Moreover I did in IPython right there -- was able to open a file under there for writing following that path:
![img](http://www.onerussian.com/tmp/gkrellShoot_07-13-18_154244.png)
so it might be then haskell specific or something else...

**Comment by yarikoptic** [comment]
uff... so it is likely to be indeed just running into the limit of the max path length:
```
In [1]: len(r'C:\Users\DataLad\datalad\labs\gobbini\famface\data\.git\annex\objec
   ...: ts\db3\781\SHA256E-s6845828--f4ec828ffc1ad6cf8545f60c2d50f27ff3cfe8cabe2a
   ...: a7a207cfb02b6f61281b.nii.gz\SHA256E-s6845828--f4ec828ffc1ad6cf8545f60c2d5
   ...: 0f27ff3cfe8cabe2aa7a207cfb02b6f61281b.nii.gz')
Out[1]: 257
```
When I moved that repo up under `c:\tmp` `git annex init` finished correctly...

longer story: couldn't "let it be", so installed this niceish app for windows: https://docs.microsoft.com/en-us/sysinternals/downloads/procmon  and monitored execution when ran `git annex init` in that case where openTempFile fails.  Here is grepped for the SHA256E in csv export: http://www.onerussian.com/tmp/Logfile-1.CSV-781SHA256.txt and with +-5 lines around: http://www.onerussian.com/tmp/Logfile-1.CSV-781SHA256+5.txt .  So if we ever to debug calls etc on windows -- seems to be a nice tool! (didn't manage to get anywhere with windbg).

**Comment by yarikoptic** [comment]
since I think it is nothing more which could be fixed/accomplished for that , closing
