### ISSUE TITLE
`support.archives.unixify_path()` has type issue on Windows

### ISSUE THREAD

**Issue by mih** [datalad/datalad#2572]
More tests fail, but it is always this traceback tail.
```
[00:15:30] ======================================================================
[00:15:30] ERROR: datalad.tests.test_archives.test_compress_file('.tar',)
[00:15:30] ----------------------------------------------------------------------
[00:15:30] Traceback (most recent call last):
[00:15:30]   File "C:\Miniconda35\envs\test-environment\lib\site-packages\nose\case.py", line 198, in runTest
[00:15:30]     self.test(*self.arg)
[00:15:30]   File "C:\Miniconda35\envs\test-environment\lib\site-packages\datalad\tests\utils.py", line 499, in newfunc
[00:15:30]     return t(*(arg + (d,)), **kw)
[00:15:30]   File "C:\Miniconda35\envs\test-environment\lib\site-packages\datalad\tests\utils.py", line 669, in newfunc
[00:15:30]     return t(*(arg + (filename,)), **kw)
[00:15:30]   File "C:\Miniconda35\envs\test-environment\lib\site-packages\datalad\tests\test_archives.py", line 92, in check_compress_file
[00:15:30]     decompress_file(archive, name_extracted, leading_directories='strip')
[00:15:30]   File "C:\Miniconda35\envs\test-environment\lib\site-packages\datalad\support\archives.py", line 141, in decompress_file
[00:15:30]     patoolib._extract_archive(unixify_path(archive),
[00:15:30]   File "C:\Miniconda35\envs\test-environment\lib\site-packages\datalad\support\archives.py", line 107, in unixify_path
[00:15:30]     path_ = path_.split(os.sep)
[00:15:30] TypeError: a bytes-like object is required, not 'str'

```

**Comment by mih** [comment]
I thought this would be an easy fix, but I was wrong. This function is used with `str` input and also with *forced* `bytes` input values. If I RF it to always return the same type it received, things break left and right. I will stop here.

**Comment by mih** [comment]
I think it might be useful to RF this function to build on `get_local_file_url()` which has recently seen a number of cross-platform robustifications, and is known to yield workable results on windows. This function could just strip the `file://` prefix and be done.

**Comment by mih** [comment]
With #4041 this code is no longer executed on windows.

**Comment by mih** [comment]
Merged.
