### ISSUE TITLE
OSX failures of test_aggregate_with_unavailable_objects_from_subds

### ISSUE THREAD

**Issue by yarikoptic** [datalad/datalad#2619]
occasional failures on OSX, e.g. http://smaug.datalad.org:8020/builders/datalad-pr-dl-osx-64/builds/4287/steps/nosetests/logs/stdio
```
======================================================================
ERROR: datalad.metadata.tests.test_aggregation.test_aggregate_with_unavailable_objects_from_subds
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/Users/datalad/miniconda2/lib/python2.7/site-packages/nose/case.py", line 197, in runTest
    self.test(*self.arg)
  File "/Users/datalad/buildslave/datalad-pr-dl-osx-64/build/datalad/tests/utils.py", line 417, in newfunc
    return t(*(arg + (d,)), **kw)
  File "/Users/datalad/buildslave/datalad-pr-dl-osx-64/build/datalad/tests/utils.py", line 587, in newfunc
    return t(*(arg + (filename,)), **kw)
  File "/Users/datalad/buildslave/datalad-pr-dl-osx-64/build/datalad/tests/utils.py", line 854, in newfunc
    return func(*args, **kwargs)
  File "/Users/datalad/buildslave/datalad-pr-dl-osx-64/build/datalad/tests/utils.py", line 1009, in newfunc
    return func(*args, **kwargs)
  File "/Users/datalad/buildslave/datalad-pr-dl-osx-64/build/datalad/metadata/tests/test_aggregation.py", line 213, in test_aggregate_with_unavailable_objects_from_subds
    force_extraction=False)
  File "/Users/datalad/buildslave/datalad-pr-dl-osx-64/build/venv-ci/lib/python2.7/site-packages/wrapt/wrappers.py", line 562, in __call__
    args, kwargs)
  File "/Users/datalad/buildslave/datalad-pr-dl-osx-64/build/datalad/distribution/dataset.py", line 444, in apply_func
    return f(**kwargs)
  File "/Users/datalad/buildslave/datalad-pr-dl-osx-64/build/venv-ci/lib/python2.7/site-packages/wrapt/wrappers.py", line 523, in __call__
    args, kwargs)
  File "/Users/datalad/buildslave/datalad-pr-dl-osx-64/build/datalad/interface/utils.py", line 478, in eval_func
    return return_func(generator_func)(*args, **kwargs)
  File "/Users/datalad/buildslave/datalad-pr-dl-osx-64/build/venv-ci/lib/python2.7/site-packages/wrapt/wrappers.py", line 523, in __call__
    args, kwargs)
  File "/Users/datalad/buildslave/datalad-pr-dl-osx-64/build/datalad/interface/utils.py", line 466, in return_func
    results = list(results)
  File "/Users/datalad/buildslave/datalad-pr-dl-osx-64/build/datalad/interface/utils.py", line 421, in generator_func
    result_renderer, result_xfm, _result_filter, **_kwargs):
  File "/Users/datalad/buildslave/datalad-pr-dl-osx-64/build/datalad/interface/utils.py", line 490, in _process_results
    for res in results:
  File "/Users/datalad/buildslave/datalad-pr-dl-osx-64/build/datalad/metadata/aggregate.py", line 925, in __call__
    to_save)
  File "/Users/datalad/buildslave/datalad-pr-dl-osx-64/build/datalad/metadata/aggregate.py", line 584, in _update_ds_agginfo
    result_renderer='disabled')
  File "/Users/datalad/buildslave/datalad-pr-dl-osx-64/build/venv-ci/lib/python2.7/site-packages/wrapt/wrappers.py", line 562, in __call__
    args, kwargs)
  File "/Users/datalad/buildslave/datalad-pr-dl-osx-64/build/datalad/distribution/dataset.py", line 444, in apply_func
    return f(**kwargs)
  File "/Users/datalad/buildslave/datalad-pr-dl-osx-64/build/venv-ci/lib/python2.7/site-packages/wrapt/wrappers.py", line 523, in __call__
    args, kwargs)
  File "/Users/datalad/buildslave/datalad-pr-dl-osx-64/build/datalad/interface/utils.py", line 478, in eval_func
    return return_func(generator_func)(*args, **kwargs)
  File "/Users/datalad/buildslave/datalad-pr-dl-osx-64/build/venv-ci/lib/python2.7/site-packages/wrapt/wrappers.py", line 523, in __call__
    args, kwargs)
  File "/Users/datalad/buildslave/datalad-pr-dl-osx-64/build/datalad/interface/utils.py", line 466, in return_func
    results = list(results)
  File "/Users/datalad/buildslave/datalad-pr-dl-osx-64/build/datalad/interface/utils.py", line 454, in generator_func
    msg="Command did not complete successfully")
IncompleteResultsError: Command did not complete successfully [{'status': u'error', 'message': u'Try making some of these repositories available:; \t054115f3-e358-498a-803b-b7aee9a488f5 -- datalad@datalads-imac.kiewit.dartmouth.edu:/private/tmp/datalad_temp_tree_test_aggregate_with_unavailable_objects_from_subdsCTLW5D/origin [origin]', 'annexkey': u'MD5E-s32--a39e73f232d88ed23a6821d1ede10d39.xz', 'action': u'get', 'path': u'/private/tmp/datalad_temp_test_aggregate_with_unavailable_objects_from_subdsn0yX3u/base/.datalad/metadata/objects/08/cn-6c61082bf0ae9b413ce1e6add34f67.xz', 'type': u'file', 'refds': u'/private/tmp/datalad_temp_test_aggregate_with_unavailable_objects_from_subdsn0yX3u'}]
```

**Comment by yarikoptic** [comment]
uuuu I will use the `bit bisecthumanflesh` and `git blamethrower` to figure it all out!!!!

**Comment by mih** [comment]
Man, what did you have for breakfast?

**Comment by yarikoptic** [comment]
a blank stare at a can of beer ;-)

**Comment by yarikoptic** [comment]
ok, it felt like annex is not getting an idea in time that it has that file, or some kind of race competition between parallel get'ings... and annex was as old as 6.20170816-g266bf43 (so kudos to us that everything kinda worked even with that old one) so I've upgraded it on OSX buildbot to annex 6.20170816-g266bf43 and that failure is gone now.  Thus closing since I think nothing to be fixed any longer on our end ;-)
