### ISSUE TITLE
bids extractor "fails" on benign CHANGES

### ISSUE THREAD

**Issue by yarikoptic** [datalad/datalad#2626]
#### What is the problem?
I've made mistake to run it with datalad.runtime.raiseonerror=1 I guess so "internal" error caused pdb to kick in...   I am not sure what it is whining about since IIRC CHANGES is part of BIDS spec

``` QA>: File '/mnt/btrfs/datasets/datalad/crawl/dbic/QA/CHANGES' does not have a valid type definition, most likely because it is not a valid BIDS file. 
[bids.py:_get_cnmeta:170,bids_layout.py:get_metadata:161,bids_layout.py:_get_nearest_helper:129]
Traceback (most recent call last):
  File "/home/yoh/proj/datalad/datalad-neuroimaging/venvs/dev/bin/datalad", line 8, in <module>
    main()
  File "/home/yoh/proj/datalad/datalad-master/datalad/cmdline/main.py", line 507, in main
    ret = cmdlineargs.func(cmdlineargs)
  File "/home/yoh/proj/datalad/datalad-master/datalad/interface/base.py", line 424, in call_from_parser
    ret = list(ret)
  File "/home/yoh/proj/datalad/datalad-master/datalad/interface/utils.py", line 421, in generator_func
    result_renderer, result_xfm, _result_filter, **_kwargs):
  File "/home/yoh/proj/datalad/datalad-master/datalad/interface/utils.py", line 490, in _process_results
    for res in results:
  File "/home/yoh/proj/datalad/datalad-master/datalad/metadata/aggregate.py", line 878, in __call__
    force_extraction)
  File "/home/yoh/proj/datalad/datalad-master/datalad/metadata/aggregate.py", line 253, in _dump_extracted_metadata
    subds_relpaths)
  File "/home/yoh/proj/datalad/datalad-master/datalad/metadata/aggregate.py", line 327, in _extract_metadata
    paths=relevant_paths)
  File "/home/yoh/proj/datalad/datalad-master/datalad/metadata/metadata.py", line 539, in _get_metadata
    for loc, meta in contentmeta_t or {}:
  File "/home/yoh/proj/datalad/datalad-neuroimaging/datalad_neuroimaging/extractors/bids.py", line 170, in _get_cnmeta
    include_entities=True).items()
  File "/home/yoh/proj/datalad/datalad-neuroimaging/venvs/dev/local/lib/python2.7/site-packages/bids/grabbids/bids_layout.py", line 161, in get_metadata
    potentialJSONs = self._get_nearest_helper(path, '.json', **kwargs)
  File "/home/yoh/proj/datalad/datalad-neuroimaging/venvs/dev/local/lib/python2.7/site-packages/bids/grabbids/bids_layout.py", line 129, in _get_nearest_helper
    "likely because it is not a valid BIDS file." % path
ValueError: File '/mnt/btrfs/datasets/datalad/crawl/dbic/QA/CHANGES' does not have a valid type definition, most likely because it is not a valid BIDS file.
()
> /home/yoh/proj/datalad/datalad-neuroimaging/venvs/dev/local/lib/python2.7/site-packages/bids/grabbids/bids_layout.py(129)_get_nearest_helper()
-> "likely because it is not a valid BIDS file." % path
```

**Comment by yarikoptic** [comment]
moved to https://github.com/datalad/datalad-neuroimaging/issues/34
