### ISSUE TITLE
aggregate-metadata could cause detached HEAD and crash publish?

### ISSUE THREAD

**Issue by yarikoptic** [datalad/datalad#2637]
#### What is the problem?
With about to become 0.10.0 (0.10.0.rc5.dev62)
```
...
[INFO   ] Publishing <Dataset path=/mnt/btrfs/datasets/datalad/crawl/corr/JHU-preproc-connectomes/cpacv0392> to datalad-public
publish(ok): corr/JHU-preproc-connectomes/cpacv0392 (dataset) [pushed to datalad-public: ['[up to date]', 'a57c7d2..e8887b5', '[up to date]', '[up to date]', 'a57c7d2..e8887b5']]
Traceback (most recent call last):
  File "/home/yoh/proj/datalad/datalad-master/venvs/dev/bin/datalad", line 8, in <module>
    main()
  File "/home/yoh/proj/datalad/datalad-master/datalad/cmdline/main.py", line 512, in main
    ret = cmdlineargs.func(cmdlineargs)
  File "/home/yoh/proj/datalad/datalad-master/datalad/interface/base.py", line 426, in call_from_parser
    ret = list(ret)
  File "/home/yoh/proj/datalad/datalad-master/datalad/interface/utils.py", line 421, in generator_func
    result_renderer, result_xfm, _result_filter, **_kwargs):
  File "/home/yoh/proj/datalad/datalad-master/datalad/interface/utils.py", line 490, in _process_results
    for res in results:
  File "/home/yoh/proj/datalad/datalad-master/datalad/distribution/publish.py", line 824, in __call__
    **res_kwargs):
  File "/home/yoh/proj/datalad/datalad-master/datalad/distribution/publish.py", line 313, in _publish_dataset
    diff = True if force else has_diff(ds, refspec, remote, paths)
  File "/home/yoh/proj/datalad/datalad-master/datalad/distribution/publish.py", line 93, in has_diff
    remote_ref = '/'.join((remote, remote_branch_name))
TypeError: sequence item 1: expected string, NoneType found
()
> /home/yoh/proj/datalad/datalad-master/datalad/distribution/publish.py(93)has_diff()
-> remote_ref = '/'.join((remote, remote_branch_name))
(Pdb) p ds
<Dataset path=/mnt/btrfs/datasets/datalad/crawl/corr/JHU-preproc-connectomes>
(Pdb) p remote
'datalad-public'
(Pdb) p remote_branch_name
None
```
repository managed somehow to be in detached HEAD mode with a commit for metadata update
```
$> git log
commit 44f948ca24dca53eadceb3c8e264fd90d77aa29b (HEAD)
Author: Yaroslav Halchenko <debian@onerussian.com>
Date:   Fri Jun 8 11:56:42 2018 -0400

    [DATALAD] Dataset aggregate metadata update

commit 7027a0933723d764a8ff86a950a646820394dcf2 (datalad-public/synced/master, datalad-public/master, synced/master, master)
Author: Yaroslav Halchenko <debian@onerussian.com>
Date:   Wed May 24 12:49:05 2017 -0400

    [DATALAD] aggregated meta data
```
although it was in master just right before then
```
$> grep JHU-preproc-connectomes /tmp/datalad-ls-20180605.txt | head
corr/JHU-preproc-connectomes                                [annex]  -  - 2017-05-24/12:49:05  OK  0 Bytes/0 Bytes
corr/JHU-preproc-connectomes/cpacv0392                      [annex]  master  - 2017-05-24/12:49:02  OK  0 Bytes/0 Bytes
...
```

**Comment by mih** [comment]
I have no idea how that would be possible.

**Comment by yarikoptic** [comment]
I don't know either, but it somehow happened, just an observation.  For now fixed up manually... if I do not run into similar one, let's keep this one burried
