### ISSUE TITLE
not supported ATM to reference additional remotes [network.py:as_git_url:782] (NotImplementedError)

### ISSUE THREAD

**Issue by chrisfilo** [datalad/datalad#2643]
#### What is the problem?
`datalad install` does not work
#### What steps will reproduce the problem?
```
me@christop ~ $ datalad search NSF
No DataLad dataset found at current location
Would you like to install the DataLad superdataset at 'C:\\Users\\me\\datalad'? (choices: yes, no): ERROR:
Interrupted by user while doing magic: KeyboardInterrupt() [getpass.py:win_getpass:110]
me@christop ~ $ cd /c/stanford_gdrive/data/
me@christop /c/stanford_gdrive/data $ datalad search NSF
No DataLad dataset found at current location
Would you like to install the DataLad superdataset at 'C:\\Users\\me\\datalad'? (choices: yes, no):
[INFO] Cloning http://datasets.datalad.org/ to 'C:\Users\me\datalad'
From now on you can refer to this dataset using the label '///'
[INFO] Performing search using DataLad superdataset 'C:\\Users\\me\\datalad'
[INFO] Reached the limit of 20 top matches, there could be more which were not reported.
search(ok): C:\Users\me\datalad\crcns\cai-2 (dataset)
search(ok): C:\Users\me\datalad\crcns\hc-11 (dataset)
search(ok): C:\Users\me\datalad\hbnssi (dataset)
search(ok): C:\Users\me\datalad\labs\haxby\attention (dataset)
search(ok): C:\Users\me\datalad\labs\haxby\life (dataset)
search(ok): C:\Users\me\datalad\openfmri\ds000001 (dataset)
search(ok): C:\Users\me\datalad\openfmri\ds000002 (dataset)
search(ok): C:\Users\me\datalad\openfmri\ds000003 (dataset)
search(ok): C:\Users\me\datalad\openfmri\ds000005 (dataset)
search(ok): C:\Users\me\datalad\openfmri\ds000006 (dataset)
search(ok): C:\Users\me\datalad\openfmri\ds000007 (dataset)
search(ok): C:\Users\me\datalad\openfmri\ds000008 (dataset)
search(ok): C:\Users\me\datalad\openfmri\ds000011 (dataset)
search(ok): C:\Users\me\datalad\openfmri\ds000017 (dataset)
search(ok): C:\Users\me\datalad\openfmri\ds000030 (dataset)
search(ok): C:\Users\me\datalad\openfmri\ds000051 (dataset)
search(ok): C:\Users\me\datalad\openfmri\ds000052 (dataset)
search(ok): C:\Users\me\datalad\openfmri\ds000101 (dataset)
search(ok): C:\Users\me\datalad\openfmri\ds000102 (dataset)
search(ok): C:\Users\me\datalad\openfmri\ds000105 (dataset)
action summary:
  search (ok: 20)
me@christop /c/stanford_gdrive/data $ datalad install ///openfmri/ds000002
[ERROR] not supported ATM to reference additional remotes [network.py:as_git_url:782] (NotImplementedError)
```
#### What version of DataLad are you using (run `datalad --version`)? On what operating system (consider running `datalad wtf`)?
```
me@christop /c/stanford_gdrive/data $ datalad wtf
DataLad
=======
Version     : 0.10.0
Full version: 0.10.0

System
======
OS          : nt Windows 10 10.0.17134
Distribution:   10/10.0.17134/SP0/Multiprocessor Free

Locale/Encoding
===============
default        : utf-8
filesystem     : utf-8
locale.prefered: cp1252

Environment
===========
LANG='en_US.UTF-8'
PATH='c:\\users\\me\\miniconda3\\Library\\bin;C:\\Users\\me\\bin;C:\\Program Files\\Git\\mingw64\\bin;C:\\Program Files\\Git\\usr\\local\\bin;C:\\Program Files\\Git\\usr\\bin;C:\\Program Files\\Git\\usr\\bin;C:\\Program Files\\Git\\cmd;C:\\Program Files\\ConEmu\\ConEmu\\Scripts;C:\\Program Files\\ConEmu;C:\\Program Files\\ConEmu\\ConEmu;C:\\Program Files\\NVIDIA GPU Computing Toolkit\\CUDA\\v9.2\\bin;C:\\Program Files\\NVIDIA GPU Computing Toolkit\\CUDA\\v9.2\\libnvvp;C:\\Program Files (x86)\\Common Files\\Oracle\\Java\\javapath;C:\\Program Files\\Docker\\Docker\\Resources\\bin;C:\\Program Files (x86)\\Intel\\Intel(R) Management Engine Components\\iCLS;C:\\Program Files\\Intel\\Intel(R) Management Engine Components\\iCLS;C:\\Windows\\system32;C:\\Windows;C:\\Windows\\System32\\Wbem;C:\\Windows\\System32\\WindowsPowerShell\\v1.0;C:\\Program Files (x86)\\Intel\\Intel(R) Management Engine Components\\DAL;C:\\Program Files\\Intel\\Intel(R) Management Engine Components\\DAL;C:\\Program Files (x86)\\Intel\\Intel(R) Management Engine Components\\IPT;C:\\Program Files\\Intel\\Intel(R) Management Engine Components\\IPT;C:\\Program Files\\Intel\\WiFi\\bin;C:\\Program Files\\Common Files\\Intel\\WirelessCommon;C:\\Program Files (x86)\\NVIDIA Corporation\\PhysX\\Common;C:\\WINDOWS\\system32;C:\\WINDOWS;C:\\WINDOWS\\System32\\Wbem;C:\\WINDOWS\\System32\\WindowsPowerShell\\v1.0;C:\\WINDOWS\\System32\\OpenSSH;C:\\ProgramData\\chocolatey\\bin;C:\\Program Files\\Git\\cmd;C:\\Program Files\\PuTTY;C:\\Program Files\\nodejs;C:\\Users\\me\\Miniconda3;C:\\Users\\me\\Miniconda3\\Library\\mingw-w64\\bin;C:\\Users\\me\\Miniconda3\\Library\\usr\\bin;C:\\Users\\me\\Miniconda3\\Library\\bin;C:\\Users\\me\\Miniconda3\\Scripts;C:\\Users\\me\\AppData\\Local\\Microsoft\\WindowsApps;C:\\Program Files\\Intel\\WiFi\\bin;C:\\Program Files\\Common Files\\Intel\\WirelessCommon;C:\\Users\\me\\AppData\\Local\\atom\\bin;C:\\Users\\me\\AppData\\Roaming\\npm;C:\\Program Files\\Git\\usr\\bin\\vendor_perl;C:\\Program Files\\Git\\usr\\bin\\core_perl'
PYTHONIOENCODING='UTF-8'

Externals
=========
appdirs=1.4.3
boto=2.48.0
cmd:annex=6.20180525-g940444994
cmd:git=2.17.1.windows.2
cmd:system-git=2.17.1.windows.2
cmd:system-ssh=7.7p1
git=2.1.10
gitdb=2.0.3
humanize=0.5.1
iso8601=0.1.12
msgpack=0.5.6
requests=2.18.4
six=1.11.0
tqdm=4.23.4
wrapt=1.10.11

Installed extensions
====================


Known metadata extractors
=========================
annex: OK
audio: BROKEN (No module named 'mutagen' [audio.py:<module>:17])
datacite: OK
datalad_core: OK
datalad_rfc822: OK
exif: BROKEN (No module named 'exifread' [exif.py:<module>:16])
frictionless_datapackage: OK
image: OK
xmp: BROKEN (No module named 'libxmp' [xmp.py:<module>:20])

Configuration
=============
<Sensitive data, use -s=some or -s=all to show>
```
#### Is there anything else that would be useful to know in this context?
I'm using 64bit installation of Git which is theoretically discouraged (at least it used to be).

#### Have you had any success using DataLad before? (to assess your expertise/prior luck.  We would welcome your testimonial additions to https://github.com/datalad/datalad/wiki/Testimonials as well)
You and me go way back.

**Comment by chrisfilo** [comment]
I'm glad it's on your radar! Some context: OpenNeuro.org will be switching to a datalad based backend this month and we are hoping some users will use it directly via datalad CLI. However, over 50% of our visitors use Windows...

**Comment by mih** [comment]
Ah, nice! Let's talk next week. Curious about this!

**Comment by yarikoptic** [comment]
@chrisfilo ha -- interesting bug somewhere in us parsing our DataLadRI (the one starting with ///) on Windows.  I will try to replicate after I fire up some ancient Windows VM ;-)

 Since you have our main "superdataset" installed already (thus search working), you could just instruct datalad to install those paths, e.g. could you please try
```
datalad install C:\Users\me\datalad\openfmri\ds000002
```
or
```
cd C:\Users\me\datalad\
datalad install openfmri\ds000002
```

**Comment by yarikoptic** [comment]
I've brought back my windows VM and tested with datalad 0.10.0 and current master (0.10.2+) and cannot reproduce yet :-/
I also do not think that
```
I'm using 64bit installation of Git which is theoretically discouraged (at least it used to be).
```
is the reason.  If you could add `--dbg` to your datalad call, you should end up in pdb whenever that error happens.  Please print `self`, `self.remote`, `self.path`.  Thank you in advance

**Comment by chrisfilo** [comment]
Thanks for looking into this. Upgraded to 0.10.2 still getting the error
```
me@christop ~/Downloads/datalad_test $ datalad --dbg install ///openfmri/ds000002
Traceback (most recent call last):
  File "c:\users\me\miniconda3\lib\runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "c:\users\me\miniconda3\lib\runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "C:\Users\me\Miniconda3\Scripts\datalad.exe\__main__.py", line 9, in <module>
    sys.exit(main())
  File "c:\users\me\miniconda3\lib\site-packages\datalad\cmdline\main.py", line 511, in main
    ret = cmdlineargs.func(cmdlineargs)
  File "c:\users\me\miniconda3\lib\site-packages\datalad\interface\base.py", line 426, in call_from_parser
    ret = list(ret)
  File "c:\users\me\miniconda3\lib\site-packages\datalad\interface\utils.py", line 421, in generator_func
    result_renderer, result_xfm, _result_filter, **_kwargs):
  File "c:\users\me\miniconda3\lib\site-packages\datalad\interface\utils.py", line 490, in _process_results
    for res in results:
  File "c:\users\me\miniconda3\lib\site-packages\datalad\distribution\install.py", line 232, in __call__
    **common_kwargs):
  File "c:\users\me\miniconda3\lib\site-packages\datalad\interface\utils.py", line 421, in generator_func
    result_renderer, result_xfm, _result_filter, **_kwargs):
  File "c:\users\me\miniconda3\lib\site-packages\datalad\interface\utils.py", line 490, in _process_results
    for res in results:
  File "c:\users\me\miniconda3\lib\site-packages\datalad\distribution\install.py", line 354, in __call__
    for r in res:
  File "c:\users\me\miniconda3\lib\site-packages\datalad\interface\utils.py", line 421, in generator_func
    result_renderer, result_xfm, _result_filter, **_kwargs):
  File "c:\users\me\miniconda3\lib\site-packages\datalad\interface\utils.py", line 490, in _process_results
    for res in results:
  File "c:\users\me\miniconda3\lib\site-packages\datalad\distribution\clone.py", line 164, in __call__
    source_ = _get_git_url_from_source(source)
  File "c:\users\me\miniconda3\lib\site-packages\datalad\distribution\utils.py", line 104, in _get_git_url_from_source
    source = source_ri.as_git_url()
  File "c:\users\me\miniconda3\lib\site-packages\datalad\support\network.py", line 801, in as_git_url
    raise NotImplementedError("not supported ATM to reference additional remotes")
NotImplementedError: not supported ATM to reference additional remotes
```

**Comment by yarikoptic** [comment]
Unfortunately I could not replicate and would appreciate a bit of debugging, see above about --dbg option. Also try to install given the path

**Comment by chrisfilo** [comment]
The problem was that `///` has special meaning in Windows Git Bash. I managed to get around it with
```
MSYS_NO_PATHCONV=1 datalad install ///openfmri/ds000002
```

More on the conversion rules: http://www.mingw.org/wiki/Posix_path_conversion

**Comment by chrisfilo** [comment]
I don't think that actually was a solution. Even though the command worked
```
me@christop ~/Downloads/datalad_test $ MSYS_NO_PATHCONV=1 datalad install ///openfmri/ds000002
[INFO] Cloning http://datasets.datalad.org/openfmri/ds000002 to '\c\Users\me\Downloads\datalad_test\ds000002'
[INFO] access to dataset sibling "datalad" not auto-enabled, enable with:
|               datalad siblings -d "\c\Users\me\Downloads\datalad_test\ds000002" enable -s datalad
install(ok): \c\Users\me\Downloads\datalad_test\ds000002 (dataset)
```
The dataset is not there:
```
me@christop ~/Downloads/datalad_test $ ls /c/Users/me/Downloads/datalad_test/ds000002
ls: cannot access '/c/Users/me/Downloads/datalad_test/ds000002': No such file or directory
```

**Comment by yarikoptic** [comment]
Crap... We didn't know about that convention! Bad...
May be it is under  \c\Users\me\Downloads\datalad_test\ds000002 ? ;-)

**Comment by chrisfilo** [comment]
```
me@christop ~/Downloads/datalad_test $ ls \c\Users\me\Downloads\datalad_test\ds000002
ls: cannot access 'cUsersmeDownloadsdatalad_testds000002': No such file or directory
```

```
me@christop ~/Downloads/datalad_test $ MSYS_NO_PATHCONV=1 ls \c\Users\me\Downloads\datalad_test\ds000002
ls: cannot access 'cUsersmeDownloadsdatalad_testds000002': No such file or directory
```

**Comment by yarikoptic** [comment]
Thank you. I will try to figure it out now that I know which specific shell it is.

**Comment by chrisfilo** [comment]
Thanks - much appreciated. I think this shell will be the first choice for
most of datalad windows users since they need to install git anyway.

**Comment by yarikoptic** [comment]
I was about to hack up a workaround in datalad, but could not find a reliable indicator of Mays/mingw/...another  which would tell us that argument was tempered. So may be then we should just educate our windows users about this feature is the Shell they use and prepend one more /?

**Comment by yarikoptic** [comment]
Counter-argument to my suggestion would be non-portability of analysis scripts which have installation steps, e.g. our http://datalad.org/asciicast/reproducible_analysis.sh where there is `datalad install ///...` calls are used.
That is because while still in the shell (i.e. also in bash scripts), MSYS does not do any paths mapping:
![gkrellshoot_07-17-18_093850](https://user-images.githubusercontent.com/39889/42820927-58f92ea2-89a5-11e8-99fe-065196ba104f.png)
So I thought back that we are doomed to do some analysis, including consideration of the MSYS_NO_PATHCONV variable and adjust any command line argument to not do it, **but** then I have ran into another blow:
![gkrellshoot_07-17-18_094431](https://user-images.githubusercontent.com/39889/42821226-13439860-89a6-11e8-9646-022fc7e798ce.png)
so, with their mapping there is no way (in the future, since not supported ATM as above exception shows) to distinguish between `///x/y` and `//x/y`  which is a boomer and IMHO was a wrong design on their part in MSYSes.
So I am not yet sure what should we do besides ATM warning whenever detecting MSYS system above and considering any url/path provided with leading // .  Or any other ideas @chrisfilo @mih @kyleam ?

**Comment by yarikoptic** [comment]
regarding the location... all the path mangling madness... try
```
ls '\c\Users\me\Downloads\datalad_test\ds000002'
```
(quotes are important!) ;-)  or 
```
ls /c/c/Users/...
```
I guess somewhere our paths manipulations get all deranged and use `\` convention (start from the root of the drive?) while including the drive letter instead of `/` convention (includes the drive?).  Seems to function a bit more consistent if you use conventional Windows paths or specify paths explicitly.  @mih - does this somehow resonate with your Windows paths "experiences"?

**Comment by mih** [comment]
Paths are tricky, and oyr setup is convoluted (at best). I created an issue on path handling a few weeks ago ( no ref right now, sorry). Conclusion was to abandon all platform path handling and go plain posix internally, converting UNC paths and DOS paths on the way into datalad.

Also grep for unixifypaths or something similar, which is another contraption that makes life difficult on windows. I assume this was written without considering UNC paths as an option.

/braindump

**Comment by yarikoptic** [comment]
ok, for now fixing up all this sacrificing that unused feature of `//[remote]/` on those windows system for now. PR will come

**Comment by yarikoptic** [comment]
re paths issue: https://github.com/datalad/datalad/issues/2546  so let's indeed leave any comments there if any ;-)
