### ISSUE TITLE
datalad test   is not functioning correctly

### ISSUE THREAD

**Issue by yarikoptic** [datalad/datalad#2704]
#### What is the problem?
With system wide installation it seems to not discover any tests modules, so need to specify explicitly:
```shell
$> datalad test                         
[INFO   ] Starting test run for module(s): ['datalad'] 
Running unit tests for datalad
Python version 3.6.5 (default, May 11 2018, 13:30:17) [GCC 7.3.0]
nose version 1.3.7

----------------------------------------------------------------------
Ran 0 tests in 0.001s

OK

$> datalad test datalad
[INFO   ] Starting test run for module(s): ['datalad'] 
Running unit tests for datalad
Python version 3.6.5 (default, May 11 2018, 13:30:17) [GCC 7.3.0]
nose version 1.3.7

----------------------------------------------------------------------
Ran 0 tests in 0.001s

OK

$> datalad test datalad.support.tests.test_network
[INFO   ] Starting test run for module(s): ['datalad.support.tests.test_network'] 
Running unit tests for datalad
Python version 3.6.5 (default, May 11 2018, 13:30:17) [GCC 7.3.0]
nose version 1.3.7
...............S............Versions: appdirs=1.4.3 boto=2.44.0 cmd:annex=6.20180521+gitg0e3bebd71-1~ndall+1 cmd:git=2.17.0 cmd:system-git=2.18.0 cmd:system-ssh=7.6p1 exifread=2.1.2 git=2.1.8 gitdb=2.0.3 humanize=0.5.1 iso8601=0.1.11 msgpack=0.5.1 mutagen=1.38 requests=2.18.4 six=1.11.0 wrapt=1.9.0
Obscure filename: str=b' "\';a&b&c\xce\x94\xd0\x99\xd7\xa7\xd9\x85\xe0\xb9\x97\xe3\x81\x82 `| ' repr=' "\';a&b&cΔЙקم๗あ `| '
Encodings: default='utf-8' filesystem='utf-8' locale.prefered='UTF-8'
Environment: PATH='/home/yoh/gocode/bin:/home/yoh/gocode/bin:/home/yoh/bin:/home/yoh/.local/bin:/usr/local/bin:/usr/bin:/bin:/usr/local/games:/usr/games:/snap/bin:/sbin:/usr/sbin:/usr/local/sbin' LANG='en_US.utf8' GIT_PAGER='less --no-init --quit-if-one-screen' GIT_PYTHON_GIT_EXECUTABLE='/usr/lib/git-annex.linux/git'

----------------------------------------------------------------------
Ran 28 tests in 1.070s

```
in virtualenv - for some reason can't import consts module from datalad but I do not see an immediate recursion (typical reason for such cases) or alike:
```
$> datalad test datalad.support.tests.test_network
[INFO   ] Starting test run for module(s): ['datalad.support.tests.test_network'] 
Running unit tests for datalad
Python version 2.7.14+ (default, Mar 13 2018, 15:23:44) [GCC 7.3.0]
nose version 1.3.7
E
======================================================================
ERROR: test suite for <module 'datalad.support.tests.test_network' from '/home/yoh/proj/datalad/datalad/datalad/support/tests/test_network.pyc'>
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/usr/lib/python2.7/dist-packages/nose/suite.py", line 209, in run
    self.setUp()
  File "/usr/lib/python2.7/dist-packages/nose/suite.py", line 292, in setUp
    self.setupContext(ancestor)
  File "/usr/lib/python2.7/dist-packages/nose/suite.py", line 315, in setupContext
    try_run(context, names)
  File "/usr/lib/python2.7/dist-packages/nose/util.py", line 471, in try_run
    return func()
  File "/home/yoh/proj/datalad/datalad/datalad/__init__.py", line 97, in setup_package
    from datalad import consts
ImportError: cannot import name consts

----------------------------------------------------------------------
Ran 0 tests in 0.001s

FAILED (errors=1)

$> datalad test                                   
[INFO   ] Starting test run for module(s): ['datalad', 'datalad_crawler'] 
Running unit tests for datalad
Python version 2.7.14+ (default, Mar 13 2018, 15:23:44) [GCC 7.3.0]
nose version 1.3.7
/usr/lib/python2.7/dist-packages/h5py/__init__.py:36: FutureWarning: Conversion of the second argument of issubdtype from `float` to `np.floating` is deprecated. In future, it will be treated as `np.float64 == np.dtype(float).type`.
  from ._conv import register_converters as _register_converters
E
======================================================================
ERROR: test suite for <module 'datalad' from '/home/yoh/proj/datalad/datalad/datalad/__init__.pyc'>
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/usr/lib/python2.7/dist-packages/nose/suite.py", line 209, in run
    self.setUp()
  File "/usr/lib/python2.7/dist-packages/nose/suite.py", line 292, in setUp
    self.setupContext(ancestor)
  File "/usr/lib/python2.7/dist-packages/nose/suite.py", line 315, in setupContext
    try_run(context, names)
  File "/usr/lib/python2.7/dist-packages/nose/util.py", line 471, in try_run
    return func()
  File "/home/yoh/proj/datalad/datalad/datalad/__init__.py", line 97, in setup_package
    from datalad import consts
ImportError: cannot import name consts

----------------------------------------------------------------------
Ran 0 tests in 0.000s

FAILED (errors=1)
```

any clues/ideas?

**Comment by mih** [comment]
Closing after a long time.
