### ISSUE TITLE
WSL: datalad test errors and failures

### ISSUE THREAD

**Issue by yarikoptic** [datalad/datalad#2711]
#### What is the problem?

In general it seems that Windows Subsytem for Linux (WSL, Windows 10 Enterprise, version 1709 build 16299.125) might be ready to be used "in production" with datalad!  while running `datalad test` under two environments (Debian stretch and Ubuntu xenial) some tests have errorred (the same badname we yet to resolve is among them) or failed, here are the full logs:
http://www.onerussian.com/tmp/datalad-0.10.2-tests-wsl-stretch-1.log
http://www.onerussian.com/tmp/datalad-0.10.2-tests-wsl-xenial-1.log

here is some worth first looking at and present in both envs:

- [ ] locking
```
======================================================================
FAIL: datalad.interface.tests.test_unlock.test_unlock
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/nose/case.py", line 198, in runTest
    self.test(*self.arg)
  File "/usr/lib/python3/dist-packages/datalad/tests/utils.py", line 854, in newfunc
    return func(*args, **kwargs)
  File "/usr/lib/python3/dist-packages/datalad/tests/utils.py", line 762, in newfunc
    t(*(arg + (uri,)), **kw)
  File "/usr/lib/python3/dist-packages/datalad/interface/tests/test_unlock.py", line 121, in test_unlock
    assert_raises(IOError, open, opj(path, 'test-annex.dat'), "w")
AssertionError: OSError not raised by open

======================================================================
FAIL: datalad.support.tests.test_locking.test_lock_if_check_fails
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/nose/case.py", line 198, in runTest
    self.test(*self.arg)
  File "/usr/lib/python3/dist-packages/datalad/tests/utils.py", line 587, in newfunc
    return t(*(arg + (filename,)), **kw)
  File "/usr/lib/python3/dist-packages/datalad/support/tests/test_locking.py", line 71, in test_lock_if_check_fails
    assert q.get() is False
AssertionError: 
-------------------- >> begin captured logging << --------------------
fasteners.process_lock: Level 5: Acquired file lock `/mnt/c/tmp/ubuntu/datalad_temp_test_lock_if_check_failsvx7hq7st.lck` after waiting 0.000s [1 attempts were required]
fasteners.process_lock: Level 5: Unlocked and closed file lock open on `/mnt/c/tmp/ubuntu/datalad_temp_test_lock_if_check_failsvx7hq7st.lck`
fasteners.process_lock: Level 5: Acquired file lock `/mnt/c/tmp/ubuntu/datalad_temp_test_lock_if_check_failsvx7hq7st.get-lck` after waiting 0.000s [1 attempts were required]
fasteners.process_lock: Level 5: Unlocked and closed file lock open on `/mnt/c/tmp/ubuntu/datalad_temp_test_lock_if_check_failsvx7hq7st.get-lck`
fasteners.process_lock: Level 5: Acquired file lock `/mnt/c/tmp/ubuntu/datalad_temp_test_lock_if_check_failsvx7hq7st.lck` after waiting 0.000s [1 attempts were required]
fasteners.process_lock: Level 5: Unlocked and closed file lock open on `/mnt/c/tmp/ubuntu/datalad_temp_test_lock_if_check_failsvx7hq7st.lck`
--------------------- >> end captured logging << ---------------------
```

- [ ] RO

```
======================================================================
FAIL: datalad.tests.test_utils.test_rotree
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/nose/case.py", line 198, in runTest
    self.test(*self.arg)
  File "/usr/lib/python3/dist-packages/datalad/tests/utils.py", line 587, in newfunc
    return t(*(arg + (filename,)), **kw)
  File "/usr/lib/python3/dist-packages/datalad/tests/test_utils.py", line 143, in test_rotree
    assert_raises(OSError, os.unlink, f)
AssertionError: OSError not raised by unlink
```

- [ ] unicode 

```
======================================================================
FAIL: datalad.tests.test_tests_utils.test_get_most_obscure_supported_name
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/nose/case.py", line 198, in runTest
    self.test(*self.arg)
  File "/usr/lib/python3/dist-packages/datalad/tests/test_tests_utils.py", line 206, in test_get_most_obscure_supported_name
    eq_(n, OBSCURE_PREFIX + OBSCURE_FILENAMES[1])
AssertionError: ' ;abc╬Ф╨Щ╫з┘Ер╣ЧуБВ ' != ' "\';a&b&c╬Ф╨Щ╫з┘Ер╣ЧуБВ `| '
```

Meanwhile I will setup development environment in that brand new Windows VM we have on smaug for datalad

#### What version of DataLad are you using (run `datalad --version`)? On what operating system (consider running `datalad wtf`)?
0.10.2

**Comment by yarikoptic-gitmate** [comment]
[GitMate.io](https://gitmate.io) thinks possibly related issues are https://github.com/datalad/datalad/issues/1843 (git 2.14.1 ERROR: datalad.support.tests.test_annexrepo.test_AnnexRepo_add_unexpected_direct_mode), https://github.com/datalad/datalad/issues/2252 (datalad test  might pick up local), https://github.com/datalad/datalad/issues/2493 ("Integration" testing failures), https://github.com/datalad/datalad/issues/585 (Tests failures on NTFS partition), and https://github.com/datalad/datalad/issues/1193 (datalad mv).

**Comment by yarikoptic** [comment]
probably not worth keeping open since it has been awhile
