### ISSUE TITLE
BadName strikes back

### ISSUE THREAD

**Issue by yarikoptic** [datalad/datalad#2778]
#### What is the problem?
from https://travis-ci.org/datalad/datalad/jobs/419745297 . I will restart it now but I did store a copy of the log at http://www.onerussian.com/tmp/datalad-travis-419745297.txt.gz 
```
ERROR: datalad.distribution.tests.test_create_sibling.test_replace_and_relative_sshpath
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/travis/virtualenv/python3.6.3/lib/python3.6/site-packages/nose/case.py", line 198, in runTest
    self.test(*self.arg)
  File "/home/travis/build/datalad/datalad/datalad/tests/utils.py", line 825, in newfunc
    return func(*args, **kwargs)
  File "/home/travis/build/datalad/datalad/datalad/tests/utils.py", line 868, in newfunc
    return func(*args, **kwargs)
  File "/home/travis/build/datalad/datalad/datalad/tests/utils.py", line 587, in newfunc
    return t(*(arg + (filename,)), **kw)
  File "/home/travis/build/datalad/datalad/datalad/tests/utils.py", line 587, in newfunc
    return t(*(arg + (filename,)), **kw)
  File "/home/travis/build/datalad/datalad/datalad/distribution/tests/test_create_sibling.py", line 483, in test_replace_and_relative_sshpath
    published2 = ds.publish(to='localhost', transfer_data='all')
  File "/home/travis/virtualenv/python3.6.3/lib/python3.6/site-packages/wrapt/wrappers.py", line 562, in __call__
    args, kwargs)
  File "/home/travis/build/datalad/datalad/datalad/distribution/dataset.py", line 444, in apply_func
    return f(**kwargs)
  File "/home/travis/virtualenv/python3.6.3/lib/python3.6/site-packages/wrapt/wrappers.py", line 523, in __call__
    args, kwargs)
  File "/home/travis/build/datalad/datalad/datalad/interface/utils.py", line 478, in eval_func
    return return_func(generator_func)(*args, **kwargs)
  File "/home/travis/virtualenv/python3.6.3/lib/python3.6/site-packages/wrapt/wrappers.py", line 523, in __call__
    args, kwargs)
  File "/home/travis/build/datalad/datalad/datalad/interface/utils.py", line 466, in return_func
    results = list(results)
  File "/home/travis/build/datalad/datalad/datalad/interface/utils.py", line 421, in generator_func
    result_renderer, result_xfm, _result_filter, **_kwargs):
  File "/home/travis/build/datalad/datalad/datalad/interface/utils.py", line 490, in _process_results
    for res in results:
  File "/home/travis/build/datalad/datalad/datalad/distribution/publish.py", line 824, in __call__
    **res_kwargs):
  File "/home/travis/build/datalad/datalad/datalad/distribution/publish.py", line 415, in _publish_dataset
    ds.repo.fetch(remote=remote)
  File "/home/travis/build/datalad/datalad/datalad/support/gitrepo.py", line 1735, in fetch
    fi_list += rm.fetch(refspec=refspec, progress=progress, **kwargs)
  File "/home/travis/virtualenv/python3.6.3/lib/python3.6/site-packages/git/remote.py", line 789, in fetch
    res = self._get_fetch_info_from_stderr(proc, progress)
  File "/home/travis/virtualenv/python3.6.3/lib/python3.6/site-packages/git/remote.py", line 706, in _get_fetch_info_from_stderr
    for err_line, fetch_line in zip(fetch_info_lines, fetch_head_info))
  File "/home/travis/virtualenv/python3.6.3/lib/python3.6/site-packages/git/remote.py", line 706, in <genexpr>
    for err_line, fetch_line in zip(fetch_info_lines, fetch_head_info))
  File "/home/travis/virtualenv/python3.6.3/lib/python3.6/site-packages/git/remote.py", line 325, in _from_line
    old_commit = repo.rev_parse(operation.split(split_token)[0])
  File "/home/travis/virtualenv/python3.6.3/lib/python3.6/site-packages/git/repo/fun.py", line 334, in rev_parse
    obj = name_to_object(repo, rev)
  File "/home/travis/virtualenv/python3.6.3/lib/python3.6/site-packages/git/repo/fun.py", line 147, in name_to_object
    raise BadName(name)
gitdb.exc.BadName: Ref '577e25a' did not resolve to an object
```
The original issue #2550 was workedaround in #2712 at the level of datalad/distribution/update.py around invocation to GitRepo.fetch which was the most common point to trigger that situation. But as above shows, that problem could be triggered in other cases as well, so we might need to guard within `.fetch` itself.

**Comment by yarikoptic-gitmate** [comment]
[GitMate.io](https://gitmate.io) thinks possibly related issues are https://github.com/datalad/datalad/issues/365 (BadObject racing strikes again), https://github.com/datalad/datalad/issues/1282 (bring --kill back?), https://github.com/datalad/datalad/issues/1659 (copy_to/publish ATM do not report errors back :-/), https://github.com/datalad/datalad/issues/2301 (test_basic_aggregate: json.decoder.JSONDecodeError: Extra data: line 1 column 166 (char 165)), and https://github.com/datalad/datalad/issues/2550 (Failing (randomly) test(s?): Ref 'a7b0fde' did not resolve to an object).
