### ISSUE TITLE
cannot "datalad install" within subsubdir submodule (?)

### ISSUE THREAD

**Issue by yarikoptic** [datalad/datalad#2787]
```shell
hopa:/tmp
$> datalad install http://github.com/MRtrix3/mrtrix3
[INFO   ] Cloning http://github.com/MRtrix3/mrtrix3 to '/tmp/mrtrix3' 
install(ok): /tmp/mrtrix3 (dataset)

$> cd mrtrix3/testing/data

$> datalad install .
[INFO   ] Cloning http://github.com/MRtrix3/mrtrix3/testing/data to '/tmp/mrtrix3/testing/data' 
[WARNING] Something went wrong while installing testing/data: [Errno 2] No such file or directory [base.py:clone_from:979] 
[ERROR  ] Installation of subdatasets /tmp/mrtrix3/testing/data failed with exception: InstallFailedError: 
Failed to install dataset from any of: ['http://github.com/MRtrix3/mrtrix3/testing/data', 'https://github.com/MRtrix3/test_data'] [get.py:_install_subds_from_flexible_source:182] [install(/tmp/mrtrix3/testing/data)] 
[ERROR  ] [Errno 2] No such file or directory [posixpath.py:abspath:364] (OSError)
```
works ok with stock submodule update ran within root of the repo:
```
$> cd ../../

$> git submodule update --init
Submodule 'testing/data' (https://github.com/MRtrix3/test_data) registered for path 'testing/data'
Cloning into '/tmp/mrtrix3/testing/data'...
Submodule path 'testing/data': checked out '6e6196af03e27948154f1f11285aa11d35af4a36'

```

datalad 0.10.2-207-g6b829527

**Comment by yarikoptic-gitmate** [comment]
[GitMate.io](https://gitmate.io) thinks possibly related issues are https://github.com/datalad/datalad/issues/558 (datalad install -d . subds didn't really register it as a submodule to current git), https://github.com/datalad/datalad/issues/405 (datalad install of a subdataset into a dataset fails since provides None to git submodule call), https://github.com/datalad/datalad/issues/2551 (datalad diff would crash on an uninstalled submodule), https://github.com/datalad/datalad/issues/884 (datalad install   no longer can take multiple args), and https://github.com/datalad/datalad/issues/2211 (datalad install doesn't like gvfs).

**Comment by yarikoptic** [comment]
also note that INFO message is misleading when I try to install from under `data/`:
```shell
$> datalad install data 
[INFO   ] Cloning https://github.com/MRtrix3/mrtrix3/testing/data to '/home/yoh/proj/misc/mrtrix3/testing/data' 
install(ok): /home/yoh/proj/misc/mrtrix3/testing/data (dataset) [Installed subdataset in order to get /home/yoh/proj/misc/mrtrix3/testing/data]

$> grep url  data/.git/config   
	url = https://github.com/MRtrix3/test_data
```

so it cloned not from https://github.com/MRtrix3/mrtrix3/testing/data !

**Comment by yarikoptic** [comment]
re original issue -- problem is twofold:
- we "wipe" out the target directory after failed attempt (we should leave an empty dir if it existed before)
- we crash in results rendering whenever curdir is gone!  makes our process less "robust" (imho we shouldn't crash unless it is critical)
```shell
(git)hopa:~/proj/misc/mrtrix3[debian]testing/data
$> datalad --dbg -l debug install .
...
[DEBUG  ] Wiping out unsuccessful clone attempt at: /home/yoh/proj/misc/mrtrix3/testing/data 
[DEBUG  ] Attempting to clone https://github.com/MRtrix3/mrtrix3/testing/data/.git (2 out of 4 candidates) to '/home/yoh/proj/misc/mrtrix3/testing/data' 
[DEBUG  ] Git clone from https://github.com/MRtrix3/mrtrix3/testing/data/.git to /home/yoh/proj/misc/mrtrix3/testing/data 
[WARNING] Something went wrong while installing testing/data: [Errno 2] No such file or directory [base.py:clone_from:979] 
[ERROR  ] Installation of subdatasets /home/yoh/proj/misc/mrtrix3/testing/data failed with exception: InstallFailedError: 
Failed to install dataset from any of: ['https://github.com/MRtrix3/mrtrix3/testing/data', 'https://github.com/MRtrix3/test_data'] [get.py:_install_subds_from_flexible_source:182] [install(/home/yoh/proj/misc/mrtrix3/testing/data)] 
Traceback (most recent call last):
  File "/home/yoh/proj/datalad/datalad/venvs/dev/bin/datalad", line 8, in <module>
    main()
  File "/home/yoh/proj/datalad/datalad/datalad/cmdline/main.py", line 495, in main
    ret = cmdlineargs.func(cmdlineargs)
  File "/home/yoh/proj/datalad/datalad/datalad/interface/base.py", line 628, in call_from_parser
    ret = list(ret)
  File "/home/yoh/proj/datalad/datalad/datalad/interface/utils.py", line 421, in generator_func
    result_renderer, result_xfm, _result_filter, **_kwargs):
  File "/home/yoh/proj/datalad/datalad/datalad/interface/utils.py", line 539, in _process_results
    if not result_filter(res):
  File "/home/yoh/proj/datalad/datalad/datalad/interface/utils.py", line 362, in _result_filter
    return result_filter(res, **allkwargs)
  File "/home/yoh/proj/datalad/datalad/datalad/interface/results.py", line 279, in is_result_matching_pathsource_argument
    elif any(abspath(p) == respath for p in paths):
  File "/home/yoh/proj/datalad/datalad/datalad/interface/results.py", line 279, in <genexpr>
    elif any(abspath(p) == respath for p in paths):
  File "/home/yoh/proj/datalad/datalad/venvs/dev/lib/python2.7/posixpath.py", line 364, in abspath
    cwd = os.getcwd()
OSError: [Errno 2] No such file or directory
()
> /home/yoh/proj/datalad/datalad/venvs/dev/lib/python2.7/posixpath.py(364)abspath()
-> cwd = os.getcwd()
(Pdb) 
```

**Comment by yarikoptic** [comment]
ok, it is not per se about subsubdirectory but about going the order in which we are going through the candidates for installation and that effect of killing curdir. Will submit now a PR to fix it (no time for unittest ATM)
