### ISSUE TITLE
Python2 not supported on Windows

### ISSUE THREAD

**Issue by mih** [datalad/datalad#2846]
Fails during install

```
Collecting pyliblzma (from datalad==0.10.2)
  Using cached https://files.pythonhosted.org/packages/17/48/5292ade507dafe573360560ba53783395587dc42eb32b347feb2ac70fc6b/pyliblzma-0.5.3.tar.bz2
    Complete output from command python setup.py egg_info:
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "c:\users\pussyg~1\appdata\local\temp\pip-build-siu_we\pyliblzma\setup.py", line 48, in <module>
        shell=True, stdout=subprocess.PIPE, stderr=subprocess.STDOUT, close_fds=True).stdout.read():
      File "c:\python27\lib\subprocess.py", line 668, in __init__
        raise ValueError("close_fds is not supported on Windows "
    ValueError: close_fds is not supported on Windows platforms if you redirect stdin/stdout/stderr

    ----------------------------------------
```

I don't think we should do anything other than document it.

**Comment by yarikoptic** [comment]
I could have sworn that I have filed this issue before, at least FOI, but indeed we should document it now, although AFAIK the library is needed only for the metadata handling, correct?

**Comment by mih** [comment]
Yes, but metadata handling working by default is more important than PY2 on windows by default.

**Comment by mih** [comment]
PY2 is no longer supported on any platform for coming releases.

**Comment by yarikoptic** [comment]
Just a clarification, 0.11.x series releases (if any) would still have python 2
