### ISSUE TITLE
publish crashes with confusing exception when does not find remote branch name

### ISSUE THREAD

**Issue by chrispycheng** [datalad/datalad#2855]
#### What is the problem?

```shell
Chriss-MacBook:nuisance chrischeng$ datalad publish -r --to=origin
[INFO   ] Publishing <Dataset path=/Users/chrischeng/nuisance/data/extractions> to origin 
publish(ok): data/extractions (dataset) [pushed to origin: ['b145a90..9f9a005', 'a3bcdd1..3ac0a6c']]
publish(notneeded): data/QA/derivatives/mriqc (dataset)
[ERROR  ] sequence item 1: expected str instance, NoneType found [publish.py:has_diff:93] (TypeError) 
Chriss-MacBook:nuisance chrischeng$ datalad --dbg publish -r --to=origin
publish(notneeded): data/extractions (dataset)
publish(notneeded): data/QA/derivatives/mriqc (dataset)
Traceback (most recent call last):
  File "/anaconda3/bin/datalad", line 8, in <module>
    main()
  File "/anaconda3/lib/python3.6/site-packages/datalad/cmdline/main.py", line 495, in main
    ret = cmdlineargs.func(cmdlineargs)
  File "/anaconda3/lib/python3.6/site-packages/datalad/interface/base.py", line 628, in call_from_parser
    ret = list(ret)
  File "/anaconda3/lib/python3.6/site-packages/datalad/interface/utils.py", line 422, in generator_func
    result_renderer, result_xfm, _result_filter, **_kwargs):
  File "/anaconda3/lib/python3.6/site-packages/datalad/interface/utils.py", line 491, in _process_results
    for res in results:
  File "/anaconda3/lib/python3.6/site-packages/datalad/distribution/publish.py", line 824, in __call__
    **res_kwargs):
  File "/anaconda3/lib/python3.6/site-packages/datalad/distribution/publish.py", line 313, in _publish_dataset
    diff = True if force else has_diff(ds, refspec, remote, paths)
  File "/anaconda3/lib/python3.6/site-packages/datalad/distribution/publish.py", line 93, in has_diff
    remote_ref = '/'.join((remote, remote_branch_name))
TypeError: sequence item 1: expected str instance, NoneType found

> /anaconda3/lib/python3.6/site-packages/datalad/distribution/publish.py(93)has_diff()
-> remote_ref = '/'.join((remote, remote_branch_name))
(Pdb) p remote
'origin'
(Pdb) p remote_branch_name
None
(Pdb) ups # some number of them
(Pdb) p ds
<Dataset path=/Users/chrischeng/nuisance/data/QA>
(Pdb) p remote_info
{'remote': 'origin'}
[1]+  Stopped                 datalad --dbg publish -r --to=origin
```
but cannot see the difference between super and that sub dataset config which should matter
```shell
Chriss-MacBook:nuisance chrischeng$ cat .git/config 
[core]
	repositoryformatversion = 0
	filemode = true
	bare = false
	logallrefupdates = true
	ignorecase = true
	precomposeunicode = true
[remote "origin"]
	url = chrispycheng@smaug:proj/nuisance
	fetch = +refs/heads/*:refs/remotes/origin/*
	annex-uuid = eadaaee6-cf06-4f29-b8e7-2c80ff44d5d4
[branch "master"]
	remote = origin
	merge = refs/heads/master
[annex]
	uuid = 185654ce-4e1d-4cad-bac0-952734113227
	version = 5
[submodule "data/QA"]
	active = true
	url = http://datasets.datalad.org/dbic/QA/.git
[submodule "data/extractions"]
	url = chrispycheng@smaug:proj/nuisance/data/extractions
	active = true
Chriss-MacBook:nuisance chrischeng$ cat data/QA/.git/config 
[core]
	repositoryformatversion = 0
	filemode = true
	bare = false
	logallrefupdates = true
	ignorecase = true
	precomposeunicode = true
[remote "origin"]
	url = chrispycheng@smaug:proj/nuisance/data/QA
	fetch = +refs/heads/*:refs/remotes/origin/*
	annex-uuid = 12c6c7d9-ca30-4d63-b7d2-8a52b740f64e
[branch "master"]
	remote = origin
	merge = refs/heads/master
[annex]
	uuid = f4ebf7b1-8f28-471e-a052-d714e0bac946
	version = 5
[submodule "derivatives/mriqc"]
	active = true
	url = chrispycheng@smaug:proj/nuisance/data/QA/derivatives/mriqc
[remote "datasets.datalad.org"]
	url = http://datasets.datalad.org/dbic/QA/.git
	fetch = +refs/heads/*:refs/remotes/datasets.datalad.org/*
	annex-bare = false
	annex-uuid = 7d9ed214-3e5f-4cc8-ac88-f397145b2d4c
```

datalad 0.10.3.1 with wtf
```
# WTF
- path: /Users/chrischeng/nuisance
- type: dataset
- logger: <Logger datalad.plugin.wtf (INFO)>
## configuration <SENSITIVE, report disabled by configuration>
## datalad 
  - full_version: 0.10.3.1
  - version: 0.10.3.1
## dataset 
  - metadata: <SENSITIVE, report disabled by configuration>
  - path: /Users/chrischeng/nuisance
  - repo: AnnexRepo
## dependencies 
  - appdirs: 1.4.3
  - boto: 2.48.0
  - cmd:annex: 6.20180427
  - cmd:git: 2.16.3
  - cmd:system-git: 2.16.3
  - cmd:system-ssh: 7.4p1
  - git: 2.1.11
  - gitdb: 2.0.4
  - humanize: 0.5.1
  - iso8601: 0.1.12
  - msgpack: 0.5.6
  - requests: 2.18.4
  - six: 1.10.0
  - tqdm: 4.26.0
  - wrapt: 1.10.11
## environment 
  - LANG: en_US.UTF-8
  - PATH: /anaconda3/bin:/opt/local/bin:/opt/local/sbin:/Library/Frameworks/Python.framework/Versions/3.6/bin:/anaconda/bin:/Library/Frameworks/Python.framework/Versions/3.6/bin:/usr/local/bin:/usr/bin:/bin:/usr/sbin:/sbin:/opt/X11/bin:/usr/local/MacGPG2/bin
## extentions 
## metadata_extractors 
  - annex: 
    - load_error: None
    - module: datalad.metadata.extractors.annex
    - version: None
  - audio: 
    - load_error: No module named 'mutagen' [audio.py:<module>:17]
    - module: datalad.metadata.extractors.audio
  - datacite: 
    - load_error: None
    - module: datalad.metadata.extractors.datacite
    - version: None
  - datalad_core: 
    - load_error: None
    - module: datalad.metadata.extractors.datalad_core
    - version: None
  - datalad_rfc822: 
    - load_error: None
    - module: datalad.metadata.extractors.datalad_rfc822
    - version: None
  - exif: 
    - load_error: No module named 'exifread' [exif.py:<module>:16]
    - module: datalad.metadata.extractors.exif
  - frictionless_datapackage: 
    - load_error: None
    - module: datalad.metadata.extractors.frictionless_datapackage
    - version: None
  - image: 
    - load_error: None
    - module: datalad.metadata.extractors.image
    - version: None
  - xmp: 
    - load_error: No module named 'libxmp' [xmp.py:<module>:20]
    - module: datalad.metadata.extractors.xmp
## system 
  - distribution:  10.12.6/x86_64
  - encoding: 
    - default: utf-8
    - filesystem: utf-8
    - locale.prefered: UTF-8
  - max_path_length: 282
  - name: Darwin
  - release: 16.7.0
  - type: posix
  - version: Darwin Kernel Version 16.7.0: Thu Jun 15 17:36:27 PDT 2017; root:xnu-3789.70.16~2/RELEASE_X86_64
```

**Comment by chrispycheng** [comment]
and the reason was-- detached HEAD
```shell
Chriss-MacBook:nuisance chrischeng$ cd data/QA
Chriss-MacBook:QA chrischeng$ git push
fatal: You are not currently on a branch.
To push the history leading to the current (detached HEAD)
state now, use

    git push origin HEAD:<name-of-remote-branch>

Chriss-MacBook:QA chrischeng$ git branch
* (HEAD detached at a416241c)
  git-annex
```
@yarikoptic thinks that in detached head it should still manage to push objects somehow and avoid pushing actual branch pointer (if that all somehow possible)
