### ISSUE TITLE
annex_addurl_to_file fails to operate under subdir of the repo

### ISSUE THREAD

**Issue by yarikoptic** [datalad/datalad#292]
time to introduce tests for that ;)

annex_addurl_to_file (or to say @normalize_path) resolves name relative to the top dir, not to the current dir (if I give full path or relative -- the same story) to feed them into annex which simply makes it impossible to addurl to a file while under a subdir... or may be I have missed where to fix...

Here is somewhat obscure demo from WiP

```
$> datalad --dbg add-archive-content -l info svgtune_0.2.0.orig.tar.gz
Got  svgtune_0.2.0.orig.tar.gz False None None
2015-11-09 22:33:25,880 [INFO   ] mv /tmp/test-archive-annex/.git/datalad/tmp/archives/dd89b7d50e/svgtune-0.2.0/svgtune svgtune-0.2.0/svgtune. URL: dl+archive:SHA256E-s5121--6d8f7d10206a120a42bec2cd29bc2365d09889fdf070ac8c67d1cff0b1539f63.tar.gz/svgtune-0.2.0/svgtune (add_archive_content.py:172)
> /home/yoh/proj/datalad/datalad/datalad/interface/add_archive_content.py(178)__call__()
-> annex.annex_addurl_to_file(target_path, url)
(Pdb) p target_path
'/tmp/test-archive-annex/2/3/4/svgtune-0.2.0/svgtune'
(Pdb) p annex.path
'/tmp/test-archive-annex'
(Pdb) curdir()
*** TypeError: 'str' object is not callable
(Pdb) getpwd()
'/tmp/test-archive-annex/2/3/4'
(Pdb) c
  while adding a new url to an already annexed file, failed to verify url exists: dl+archive:SHA256E-s5121--6d8f7d10206a120a42bec2cd29bc2365d09889fdf070ac8c67d1cff0b1539f63.tar.gz/svgtune-0.2.0/svgtune
git-annex: addurl: 1 failed
2015-11-09 22:34:19,861 [ERROR  ] Failed to run ['git-annex', 'addurl', '--file=2/3/4/svgtune-0.2.0/svgtune', 'dl+archive:SHA256E-s5121--6d8f7d10206a120a42bec2cd29bc2365d09889fdf070ac8c67d1cff0b1539f63.tar.gz/svgtune-0.2.0/svgtune'] under '/tmp/test-archive-annex'. Exit code=1. out=addurl 2/3/4/svgtune-0.2.0/svgtune 
| failed
|  err= (cmd.py:269)
Traceback (most recent call last):
  File "/home/yoh/proj/datalad/datalad/venv-tests/bin/datalad", line 9, in <module>
    load_entry_point('datalad==0.1.dev0', 'console_scripts', 'datalad')()
  File "/home/yoh/proj/datalad/datalad/datalad/cmdline/main.py", line 199, in main
    cmdlineargs.func(cmdlineargs)
  File "/home/yoh/proj/datalad/datalad/datalad/interface/base.py", line 146, in call_from_parser
    return self(**kwargs)
  File "/home/yoh/proj/datalad/datalad/datalad/interface/add_archive_content.py", line 178, in __call__
    annex.annex_addurl_to_file(target_path, url)
  File "/home/yoh/proj/datalad/datalad/datalad/support/gitrepo.py", line 116, in newfunc
    return func(self, file_new, *args, **kwargs)
  File "/home/yoh/proj/datalad/datalad/datalad/support/annexrepo.py", line 515, in annex_addurl_to_file
    log_stderr=False)
  File "/home/yoh/proj/datalad/datalad/datalad/support/annexrepo.py", line 227, in _run_annex_command
    raise e
CommandError: CommandError: command '['git-annex', 'addurl', '--file=2/3/4/svgtune-0.2.0/svgtune', 'dl+archive:SHA256E-s5121--6d8f7d10206a120a42bec2cd29bc2365d09889fdf070ac8c67d1cff0b1539f63.tar.gz/svgtune-0.2.0/svgtune']' failed with exitcode 1.
Failed to run ['git-annex', 'addurl', '--file=2/3/4/svgtune-0.2.0/svgtune', 'dl+archive:SHA256E-s5121--6d8f7d10206a120a42bec2cd29bc2365d09889fdf070ac8c67d1cff0b1539f63.tar.gz/svgtune-0.2.0/svgtune'] under '/tmp/test-archive-annex'. Exit code=1. out=addurl 2/3/4/svgtune-0.2.0/svgtune 
failed
 err=
()
> /home/yoh/proj/datalad/datalad/datalad/support/annexrepo.py(227)_run_annex_command()
-> raise e
```

P.S. I see lots of new getcwd used -- better to use getpwd introduced in f2f9ab0b5b994dfd3b74975a8bf5e303550346bd  so we could reliably chdir if needed and go back.  see that commit comment on reasoning

**Comment by bpoldrack** [comment]
To me it seems to be correct. 
Your getpwd shows '/tmp/test-archive-annex/2/3/4'
Your target is ' /tmp/test-archive-annex/2/3/4/svgtune-0.2.0/svgtune'
passed to git-annex "2/3/4/svgtune-0.2.0/svgtune"
And git-annex should run from within annex.path '/tmp/test-archive-annex'.
Did you try the git-annex call manually?

**Comment by yarikoptic** [comment]
ah -- doesn't annex runs from current directory?  ok -- I will check this in detail as well

**Comment by bpoldrack** [comment]
By default, the runner is configured to run from base dir of the repo.
Except you changed something or pass your own runner.

2015-11-12 17:50 GMT+01:00 Yaroslav Halchenko <notifications@github.com>:

**Comment by yarikoptic** [comment]
tried again and it worked... may be some fluke (may be I did run git init there in subdir or smth). so will close for now
