### ISSUE TITLE
test_clone_report_permission_issue test fail

### ISSUE THREAD

**Issue by yarikoptic** [datalad/datalad#2920]
#### What is the problem?
Happens on my laptop -- is that just the trailing `\n` in the message mismatch?  I wonder why only me , travis I believe is happy (it is on current master 0.10.3.1-132-g37990573)
```shell
$> python -m nose -s -v datalad/distribution/tests/test_clone.py:test_clone_report_permission_issue
datalad.distribution.tests.test_clone.test_clone_report_permission_issue ... FAIL
Versions: appdirs=1.4.3 boto=2.44.0 cmd:annex=6.20181011+git7-g373c2abc2-1~ndall+1 cmd:git=2.19.1 cmd:system-git=2.19.0 cmd:system-ssh=7.6p1 exifread=2.1.2 git=git gitdb=2.0.3 humanize=0.5.1 iso8601=0.1.11 msgpack=0.5.6 mutagen=1.40.0 requests=2.18.4 scrapy=1.5.0 six=1.11.0 tqdm=4.19.5 wrapt=1.9.0
Obscure filename: str= "';a&b&cΔЙקم๗あ `|  repr=u' "\';a&b&c\u0394\u0419\u05e7\u0645\u0e57\u3042 `| '
Encodings: default='ascii' filesystem='UTF-8' locale.prefered='UTF-8'
Environment: GIT_PYTHON_GIT_EXECUTABLE='/usr/lib/git-annex.linux/git' LANG='en_US.utf8' GIT_PAGER='less --no-init --quit-if-one-screen' PATH='/home/yoh/proj/datalad/datalad-master/venvs/dev/bin:/home/yoh/gocode/bin:/home/yoh/gocode/bin:/home/yoh/bin:/home/yoh/.local/bin:/usr/local/bin:/usr/bin:/bin:/usr/local/games:/usr/games:/snap/bin:/sbin:/usr/sbin:/usr/local/sbin'

======================================================================
FAIL: datalad.distribution.tests.test_clone.test_clone_report_permission_issue
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/usr/lib/python2.7/dist-packages/nose/case.py", line 197, in runTest
    self.test(*self.arg)
  File "/home/yoh/proj/datalad/datalad-master/datalad/tests/utils.py", line 860, in newfunc
    return func(*args, **kwargs)
  File "/home/yoh/proj/datalad/datalad-master/datalad/tests/utils.py", line 591, in newfunc
    return t(*(arg + (filename,)), **kw)
  File "/home/yoh/proj/datalad/datalad-master/datalad/distribution/tests/test_clone.py", line 345, in test_clone_report_permission_issue
    % (pdir, get_datasets_topdir())
  File "/home/yoh/proj/datalad/datalad-master/datalad/tests/utils.py", line 1223, in assert_result_count
    dumps(results, indent=1, default=lambda x: "<not serializable>")))
AssertionError: Got 0 instead of 1 expected results matching {'status': 'error', 'message': "could not create work tree dir '/home/yoh/.tmp/datalad_temp_test_clone_report_permission_issueEwqayZ/protected/datasets-tests.datalad.org': Permission denied"}. Inspected 1 record(s):
[
 {
  "status": "error", 
  "source_url": "///", 
  "action": "install", 
  "path": "/home/yoh/.tmp/datalad_temp_test_clone_report_permission_issueEwqayZ/protected/datasets-tests.datalad.org", 
  "type": "dataset", 
  "message": "could not create work tree dir '/home/yoh/.tmp/datalad_temp_test_clone_report_permission_issueEwqayZ/protected/datasets-tests.datalad.org': Permission denied\n"
 }
]
-------------------- >> begin captured logging << --------------------
datalad.utils: Level 5: Importing datalad.utils
datalad.utils: Level 5: Done importing datalad.utils
datalad.cmd: Level 9: Will use git under '/usr/lib/git-annex.linux' (no adjustments to PATH if empty string)
datalad.cmd: Level 9: Running: ['git', 'version']
datalad.cmd: Level 8: Finished running ['git', 'version'] with status 0
datalad.cmd: Level 9: Running: ['git', 'config', '-z', '-l', '--show-origin']
datalad.cmd: Level 8: Finished running ['git', 'config', '-z', '-l', '--show-origin'] with status 0
datalad.ui: Level 5: Starting importing ui
datalad.ui.dialog: Level 5: Starting importing ui.dialog
datalad.ui.dialog: Level 5: Done importing ui.dialog
datalad.ui: Level 5: Initiating UI switcher
datalad.ui: DEBUG: UI set to DialogUI(out=<file>)
datalad.ui: Level 5: Done importing ui
--------------------- >> end captured logging << ---------------------

----------------------------------------------------------------------
Ran 1 test in 0.279s

FAILED (failures=1)
```

**Comment by kyleam** [comment]
> Happens on my laptop -- is that just the trailing `\n` in the message mismatch? 

Yes, looks like it.

> I wonder why only me , travis I believe is happy (it is on current master 0.10.3.1-132-g37990573)

My laptop is happy as well.

**Comment by yarikoptic** [comment]
we have not seen it for awhile so I guess it was resolved
