### ISSUE TITLE
Failing test due to keyring module upgrade

### ISSUE THREAD

**Issue by yarikoptic** [datalad/datalad#2959]
Originally detected in https://github.com/datalad/datalad/pull/2958#issuecomment-433878230
```
======================================================================
FAIL: datalad.downloaders.tests.test_credentials.test_credentials_from_env
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/travis/virtualenv/python3.5.6/lib/python3.5/site-packages/nose/case.py", line 198, in runTest
    self.test(*self.arg)
  File "/home/travis/virtualenv/python3.5.6/lib/python3.5/site-packages/datalad/downloaders/tests/test_credentials.py", line 108, in test_credentials_from_env
    assert_equal(cred.get('key_id'), '1')
AssertionError: None != '1'
-------------------- >> begin captured logging << --------------------
datalad: DEBUG: Importing keyring
datalad.downloaders.credentials: WARNING: Failed to query keyring: No recommended backend was available. Install the keyrings.alt package if you want to use the non-recommended backends. See README.rst for details. [fail.py:get_password:23]
--------------------- >> end captured logging << ---------------------
```
probably relates to the fresh keyring 16.0.0 instead of previous 15.1.0

**Comment by yarikoptic** [comment]
FWIW locally doesn't reproduce (probably because I do have credentials available):
```
$> python -m nose -s -v datalad/downloaders/tests/test_credentials.py                          
datalad.downloaders.tests.test_credentials.test_keyring ... SKIP: provide tests for Keyring which interfaces keyring module
datalad.downloaders.tests.test_credentials.test_credentials_from_env ... ok
datalad.downloaders.tests.test_credentials.test_composite_credential1 ... ok
datalad.downloaders.tests.test_credentials.test_cred1_call ... ok
datalad.downloaders.tests.test_credentials.test_cred1_enter_new ... ok
Versions: appdirs=1.4.3 boto=2.44.0 cmd:annex=6.20180926+git93-gdc47dfe90-1~ndall+1 cmd:git=2.19.0 cmd:system-git=2.19.0 cmd:system-ssh=7.6p1 exifread=2.1.2 git=git gitdb=2.0.3 humanize=0.5.1 iso8601=0.1.11 keyring=16.0.0 keyrings.alt=3.1 msgpack=0.5.6 mutagen=1.40.0 requests=2.18.4 scrapy=1.5.0 six=1.11.0 wrapt=1.9.0
Obscure filename: str= "';a&b&cΔЙקم๗あ `|  repr=u' "\';a&b&c\u0394\u0419\u05e7\u0645\u0e57\u3042 `| '
Encodings: default='ascii' filesystem='UTF-8' locale.prefered='UTF-8'
Environment: GIT_PYTHON_GIT_EXECUTABLE='/usr/lib/git-annex.linux/git' LANG='en_US.utf8' GIT_PAGER='less --no-init --quit-if-one-screen' PATH='/home/yoh/proj/datalad/datalad-master/venvs/dev/bin:/home/yoh/gocode/bin:/home/yoh/gocode/bin:/home/yoh/bin:/home/yoh/.local/bin:/usr/local/bin:/usr/bin:/bin:/usr/local/games:/usr/games:/snap/bin:/sbin:/usr/sbin:/usr/local/sbin'

----------------------------------------------------------------------
Ran 5 tests in 0.373s

OK (SKIP=1)
(dev) 1 14754.....................................:Mon 29 Oct 2018 08:56:22 AM EDT:.
(git)hopa:~datalad/datalad-master[bf-2959]git
$> datalad wtf | grep keyring                                         
  - keyring: 16.0.0
  - keyrings.alt: 3.1
```
