### ISSUE TITLE
No log output when running in Python shell

### ISSUE THREAD

**Issue by yarikoptic** [datalad/datalad#2987]
While filing #2986 saw that we have no log output while working in Python:
```shell
$> python
Python 2.7.14 (default, Sep 17 2017, 18:50:44) 
[GCC 7.2.0] on linux2
Type "help", "copyright", "credits" or "license" for more information.
>>> from datalad.api import run; run("touch 1234; exit 1");
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/yoh/proj/datalad/datalad/venvs/dev/local/lib/python2.7/site-packages/datalad/interface/utils.py", line 479, in eval_func
    return return_func(generator_func)(*args, **kwargs)
  File "/home/yoh/proj/datalad/datalad/venvs/dev/local/lib/python2.7/site-packages/datalad/interface/utils.py", line 467, in return_func
    results = list(results)
  File "/home/yoh/proj/datalad/datalad/venvs/dev/local/lib/python2.7/site-packages/datalad/interface/utils.py", line 455, in generator_func
    msg="Command did not complete successfully")
datalad.support.exceptions.IncompleteResultsError: Command did not complete successfully [{'action': u'run', 'path': u'/tmp/testds', 'message': u'unsaved modifications present, cannot detect changes by command', 'status': u'impossible', 'type': u'dataset'}]
>>> 
```
even if I set `DATALAD_LOG_LEVEL`:
```shell
$> DATALAD_LOG_LEVEL=INFO python
Python 2.7.14 (default, Sep 17 2017, 18:50:44) 
[GCC 7.2.0] on linux2
Type "help", "copyright", "credits" or "license" for more information.
>>> from datalad.api import run; run("touch 1234; exit 1");
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/yoh/proj/datalad/datalad/venvs/dev/local/lib/python2.7/site-packages/datalad/interface/utils.py", line 479, in eval_func
    return return_func(generator_func)(*args, **kwargs)
  File "/home/yoh/proj/datalad/datalad/venvs/dev/local/lib/python2.7/site-packages/datalad/interface/utils.py", line 467, in return_func
    results = list(results)
  File "/home/yoh/proj/datalad/datalad/venvs/dev/local/lib/python2.7/site-packages/datalad/interface/utils.py", line 455, in generator_func
    msg="Command did not complete successfully")
```

**Comment by mih** [comment]
Seems to work now
```
(datalad3-dev) mih@meiner /tmp % DATALAD_LOG_LEVEL=debug python
Python 3.7.3 (default, Apr  3 2019, 05:39:12) 
[GCC 8.3.0] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> from datalad.api import run; run("touch 1234; exit 1");
[DEBUG  ] parseParameters: Given "exclude_special_remotes: bool, optional
|   if True, don't return annex special remotes", we split into [('exclude_special_remotes', "exclude_special_remotes: bool, optional\n  if True, don't return annex special remotes")] 
[DEBUG  ] parseParameters: Given "with_urls_only : bool, optional
|   return only remotes which have urls", we split into [('with_urls_only', 'with_urls_only : bool, optional\n  return only remotes which have urls')] 
[DEBUG  ] Building doc for <class 'datalad.core.local.create.Create'> 
[DEBUG  ] Building doc for <class 'datalad.local.subdatasets.Subdatasets'> 
[DEBUG  ] Building doc for <class 'datalad.core.distributed.clone.Clone'> 
[DEBUG  ] Building doc for <class 'datalad.distribution.get.Get'> 
[DEBUG  ] Building doc for <class 'datalad.distribution.install.Install'> 
[DEBUG  ] Building doc for <class 'datalad.interface.annotate_paths.AnnotatePaths'> 
...
```
