### ISSUE TITLE
test_annex_copy_to failed for me while building 0.11.1 for trusty (nd14.04) only

### ISSUE THREAD

**Issue by yarikoptic** [datalad/datalad#3015]
I didn't find any record of this failing before, so decided to document
```
======================================================================
FAIL: datalad.support.tests.test_annexrepo.test_annex_copy_to
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/usr/lib/python2.7/dist-packages/nose/case.py", line 197, in runTest
    self.test(*self.arg)
  File "/build/datalad-0.11.1/.pybuild/pythonX.Y_2.7/build/datalad/tests/utils.py", line 772, in newfunc
    t(*(arg + (uri,)), **kw)
  File "/build/datalad-0.11.1/.pybuild/pythonX.Y_2.7/build/datalad/tests/utils.py", line 596, in newfunc
    return t(*(arg + (filename,)), **kw)
  File "/build/datalad-0.11.1/.pybuild/pythonX.Y_2.7/build/datalad/support/tests/test_annexrepo.py", line 1343, in test_annex_copy_to
    eq_(repo.copy_to(["copied2", "copied1", "existed"], "target"),
  File "/build/datalad-0.11.1/.pybuild/pythonX.Y_2.7/build/datalad/support/gitrepo.py", line 313, in newfunc
    result = func(self, files_new, *args, **kwargs)
  File "/build/datalad-0.11.1/.pybuild/pythonX.Y_2.7/build/datalad/support/annexrepo.py", line 3237, in copy_to
    files, ['--in', 'here', '--not', '--in', remote])
  File "/build/datalad-0.11.1/.pybuild/pythonX.Y_2.7/build/datalad/support/annexrepo.py", line 1411, in _get_expected_files
    'find', opts=expr, files=files
  File "/build/datalad-0.11.1/.pybuild/pythonX.Y_2.7/build/datalad/support/annexrepo.py", line 2410, in _run_annex_command_json
    **kwargs)
  File "/build/datalad-0.11.1/.pybuild/pythonX.Y_2.7/build/datalad/support/tests/test_annexrepo.py", line 1334, in ok_copy
    assert_in('copied1', kwargs['annex_options'])
AssertionError: 'copied1' not found in ['--json', '--in', 'here', '--not', '--in', 'target', '--', 'copied2']
```

edit 1: failed to replicate in local trusty chroot -- might be some fluke/race in our tests/annex

**Comment by yarikoptic** [comment]
surprise surprise!
```
(Pdb) p os.sysconf('SC_ARG_MAX')
-1
```
but it is not what we are "born with":
```
root@smaug:/tmp/datalad_temp_clone_url_ani9gg# python -c "import os; print(os.sysconf('SC_ARG_MAX'))"
2097152
```
that is why that test doesn't fail if I just run it alone, although I am really not sure how then our datalad.utils manages to get imported late enough after such an atrocious act of changing that variable... anyways, I will make initial conditioning a bit stronger to fall back to fall back to hardcoded if non-positive

**Comment by yarikoptic** [comment]
FTR -- nah, it is kinda "right away" screw up
```
I: pybuild base:170: cd /build/datalad-0.11.1/.pybuild/pythonX.Y_2.7/build; python2.7 -m nose --with-doctest -s -v --pdb
> /build/datalad-0.11.1/.pybuild/pythonX.Y_2.7/build/datalad/utils.py(89)<module>()
-> try:
(Pdb) n
> /build/datalad-0.11.1/.pybuild/pythonX.Y_2.7/build/datalad/utils.py(90)<module>()
-> CMD_MAX_ARG = os.sysconf('SC_ARG_MAX') or CMD_MAX_ARG_HARDCODED
(Pdb) 
> /build/datalad-0.11.1/.pybuild/pythonX.Y_2.7/build/datalad/utils.py(105)<module>()
-> CMD_MAX_ARG = int(0.5 * CMD_MAX_ARG)
(Pdb) p CMD_MAX_ARG
-1
(Pdb) p os.sysconf('SC_ARG_MAX')
-1
(Pdb) 
```
