### ISSUE TITLE
test__version__ is now failing on some py3 runs

### ISSUE THREAD

**Issue by kyleam** [datalad/datalad#3024]
Observed [here](https://travis-ci.org/datalad/datalad/jobs/460830536#L3487) and [here](https://travis-ci.org/datalad/datalad/jobs/460830537#L2820).

```
======================================================================
ERROR: datalad.tests.test_version.test__version__
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/travis/virtualenv/python3.6.3/lib/python3.6/site-packages/nose/case.py", line 198, in runTest
    self.test(*self.arg)
  File "/home/travis/build/datalad/datalad/datalad/tests/test_version.py", line 43, in test__version__
    if not line.startswith('## '):
TypeError: startswith first arg must be bytes or a tuple of bytes, not str
```

**Comment by yarikoptic** [comment]
Thanks! strange that I've not ran into it while building debian/conda pkgs... need to verify that we test python3 there :-/
