### ISSUE TITLE
unlock: Argument list too long via use of _run_annex_command (not _json counterpart)

### ISSUE THREAD

**Issue by yarikoptic** [datalad/datalad#3086]
```
.gz']'': [Errno 7] Argument list too long [subprocess.py:_execute_child:1024]
Traceback (most recent call last):
  File "/data/R03/WM-R03/venv/bin/datalad", line 8, in <module>
    main()
  File "/home/amanelis/proj/datalad/datalad/datalad/cmdline/main.py", line 495, in main
    ret = cmdlineargs.func(cmdlineargs)
  File "/home/amanelis/proj/datalad/datalad/datalad/interface/base.py", line 628, in call_from_parser
    ret = list(ret)
  File "/home/amanelis/proj/datalad/datalad/datalad/interface/utils.py", line 428, in generator_func
    result_renderer, result_xfm, _result_filter, **_kwargs):
  File "/home/amanelis/proj/datalad/datalad/datalad/interface/utils.py", line 521, in _process_results
    for res in results:
  File "/home/amanelis/proj/datalad/datalad/datalad/interface/run.py", line 219, in __call__
    sidecar=sidecar):
  File "/home/amanelis/proj/datalad/datalad/datalad/interface/run.py", line 512, in run_command
    for res in _unlock_or_remove(ds, outputs.expand(full=True)):
  File "/home/amanelis/proj/datalad/datalad/datalad/interface/run.py", line 303, in _unlock_or_remove
    for res in dset.unlock(existing, on_failure="ignore"):
  File "/home/amanelis/proj/datalad/datalad/datalad/distribution/dataset.py", line 494, in apply_func
    return f(**kwargs)
  File "/home/amanelis/proj/datalad/datalad/datalad/interface/utils.py", line 491, in eval_func
    return return_func(generator_func)(*args, **kwargs)
  File "/home/amanelis/proj/datalad/datalad/datalad/interface/utils.py", line 479, in return_func
    results = list(results)
  File "/home/amanelis/proj/datalad/datalad/datalad/interface/utils.py", line 428, in generator_func
    result_renderer, result_xfm, _result_filter, **_kwargs):
  File "/home/amanelis/proj/datalad/datalad/datalad/interface/utils.py", line 521, in _process_results
    for res in results:
  File "/home/amanelis/proj/datalad/datalad/datalad/interface/unlock.py", line 171, in __call__
    for r in ds.repo.unlock([ap['path'] for ap in to_unlock]):
  File "/home/amanelis/proj/datalad/datalad/datalad/support/gitrepo.py", line 313, in newfunc
    result = func(self, files_new, *args, **kwargs)
  File "/home/amanelis/proj/datalad/datalad/datalad/support/annexrepo.py", line 1754, in unlock
    'unlock', annex_options=options, files=files
  File "/home/amanelis/proj/datalad/datalad/datalad/support/annexrepo.py", line 1082, in _run_annex_command
    return self.cmd_call_wrapper.run(cmd_list, env=env, **kwargs)
  File "/home/amanelis/proj/datalad/datalad/datalad/cmd.py", line 673, in run
    cmd, env=self.get_git_environ_adjusted(env), *args, **kwargs)
  File "/home/amanelis/proj/datalad/datalad/datalad/cmd.py", line 487, in run
    stdin=stdin)
  File "/usr/lib/python2.7/subprocess.py", line 390, in __init__
    errread, errwrite)
  File "/usr/lib/python2.7/subprocess.py", line 1024, in _execute_child
    raise child_exception
OSError: [Errno 7] Argument list too long
()
> /usr/lib/python2.7/subprocess.py(1024)_execute_child()
-> raise child_exception
```
happens with
```
(Pdb) p cmd[:8]
['git', '-c', 'receive.autogc=0', '-c', 'gc.auto=0', 'annex', 'unlock', '--']
```
and due to us using `_run_annex_command` not `_run_annex_command_json` which would do chunking for us and have multiple git annex calls.  Since annex commands do not commit, it should be safe/ok to shift chunking into `_run_annex_command`.  But not sure if it wouldn't somehow negatively interact with progress reporting etc.  So may be we should first migrate all other commands which do have `--json` support in annex and take `files` as argument (lock, unlock, etc), to use `_run_annex_command_json`

**Comment by yarikoptic** [comment]
I think such issues finally got addressed in 0.11.2~3^2~5 (b591334047578c895561ca2f79548800cd0c73af)
