### ISSUE TITLE
[ERROR] a bytes-like object is required, not 'str' [subprocess.py:list2cmdline:530] (TypeError)

### ISSUE THREAD

**Issue by chrisgorgo** [datalad/datalad#3116]
#### What is the problem?
`datalad run` errors
#### What steps will reproduce the problem?
Following http://www.reproducibleimaging.org/coco2019-training/02-02-distros/

```
me@christop /c/scratch/ds000114 (adjusted/master(unlocked)) $ git status
On branch adjusted/master(unlocked)
nothing to commit, working tree clean
me@christop /c/scratch/ds000114 (adjusted/master(unlocked)) $ datalad run 'nib-ls  -s sub-01/ses-test/anat/sub-01_ses-test_T1w.nii.gz > INFO.txt'
[INFO] == Command start (output follows) =====
[INFO] == Command exit (modification check follows) =====
[ERROR] a bytes-like object is required, not 'str' [subprocess.py:list2cmdline:530] (TypeError)
```
#### What version of DataLad are you using (run `datalad --version`)? On what operating system (consider running `datalad wtf`)?
```
# WTF
- path: C:\scratch\ds000114
- type: dataset
## configuration <SENSITIVE, report disabled by configuration>
## datalad 
  - full_version: 0.11.1
  - version: 0.11.1
## dataset 
  - metadata: <SENSITIVE, report disabled by configuration>
  - path: C:\scratch\ds000114
  - repo: AnnexRepo
## dependencies 
  - appdirs: 1.4.3
  - boto: 2.48.0
  - cmd:annex: 7.20181206-gc4b6115f7
  - cmd:git: 2.20.1.windows.1
  - cmd:system-git: 2.20.1.windows.1
  - cmd:system-ssh: 7.9p1
  - git: 2.1.10
  - gitdb: 2.0.3
  - humanize: 0.5.1
  - iso8601: 0.1.12
  - keyring: 12.2.1
  - keyrings.alt: 3.1
  - msgpack: 0.5.6
  - requests: 2.21.0
  - six: 1.12.0
  - tqdm: 4.23.4
  - wrapt: 1.10.11
## environment 
  - LANG: en_US.UTF-8
  - PATH: C:\Users\me\.yarn\bin;C:\Users\me\.config\yarn\global\node_modules\.bin;C:\Users\me\bin;C:\Program Files\Git\mingw64\bin;C:\Program Files\Git\usr\local\bin;C:\Program Files\Git\usr\bin;C:\Program Files\Git\usr\bin;C:\Program Files\Git\cmd;C:\Program Files\Git\usr\bin;C:\Program Files\ConEmu\ConEmu\Scripts;C:\Program Files\ConEmu;C:\Program Files\ConEmu\ConEmu;C:\Program Files\NVIDIA GPU Computing Toolkit\CUDA\v10.0\bin;C:\Program Files\NVIDIA GPU Computing Toolkit\CUDA\v10.0\libnvvp;C:\ProgramData\DockerDesktop\version-bin;C:\Program Files\Docker\Docker\Resources\bin;C:\ProgramData\Boxstarter;C:\Program Files (x86)\Intel\Intel(R) Management Engine Components\iCLS;C:\Program Files\Intel\Intel(R) Management Engine Components\iCLS;C:\Windows\system32;C:\Windows;C:\Windows\System32\Wbem;C:\Windows\System32\WindowsPowerShell\v1.0;C:\Program Files (x86)\Intel\Intel(R) Management Engine Components\DAL;C:\Program Files\Intel\Intel(R) Management Engine Components\DAL;C:\Program Files (x86)\Intel\Intel(R) Management Engine Components\IPT;C:\Program Files\Intel\Intel(R) Management Engine Components\IPT;C:\Program Files (x86)\NVIDIA Corporation\PhysX\Common;C:\WINDOWS\system32;C:\WINDOWS;C:\WINDOWS\System32\Wbem;C:\WINDOWS\System32\WindowsPowerShell\v1.0;C:\WINDOWS\System32\OpenSSH;C:\ProgramData\chocolatey\bin;C:\Program Files\PuTTY;C:\Program Files (x86)\MIT\Kerberos\bin;C:\Program Files\MiKTeX 2.9\miktex\bin\x64;C:\Program Files\NVIDIA Corporation\NVIDIA NvDLISR;C:\HashiCorp\Vagrant\bin;C:\WINDOWS\system32;C:\WINDOWS;C:\WINDOWS\System32\Wbem;C:\WINDOWS\System32\WindowsPowerShell\v1.0;C:\WINDOWS\System32\OpenSSH;C:\Program Files\Git\cmd;C:\Program Files\Git\mingw64\bin;C:\Program Files\Git\usr\bin;C:\Program Files\nodejs;C:\Users\me\.cargo\bin;C:\Program Files\nodejs\node_modules\npm\node_modules\npm-lifecycle\node-gyp-bin;C:\Users\me\AppData\Roaming\npm\node_modules\windows-build-tools\node_modules\.bin;C:\Users\me\AppData\Roaming\npm\node_modules\.bin;C:\Program Files\NVIDIA GPU Computing Toolkit\CUDA\v10.0\bin;C:\Program Files\NVIDIA GPU Computing Toolkit\CUDA\v10.0\libnvvp;C:\Program Files (x86)\Common Files\Oracle\Java\javapath;C:\Program Files\Docker\Docker\Resources\bin;C:\Program Files (x86)\Intel\Intel(R) Management Engine Components\iCLS;C:\Program Files\Intel\Intel(R) Management Engine Components\iCLS;C:\Windows\system32;C:\Windows;C:\Windows\System32\Wbem;C:\Windows\System32\WindowsPowerShell\v1.0;C:\Program Files (x86)\Intel\Intel(R) Management Engine Components\DAL;C:\Program Files\Intel\Intel(R) Management Engine Components\DAL;C:\Program Files (x86)\Intel\Intel(R) Management Engine Components\IPT;C:\Program Files\Intel\Intel(R) Management Engine Components\IPT;C:\Program Files (x86)\NVIDIA Corporation\PhysX\Common;C:\WINDOWS\system32;C:\WINDOWS;C:\WINDOWS\System32\Wbem;C:\WINDOWS\System32\WindowsPowerShell\v1.0;C:\WINDOWS\System32\OpenSSH;C:\ProgramData\chocolatey\bin;C:\Program Files\PuTTY;C:\Program Files (x86)\MIT\Kerberos\bin;C:\Program Files\Intel\WiFi\bin;C:\Program Files\Common Files\Intel\WirelessCommon;C:\Program Files\Git\cmd;C:\Program Files\Git\mingw64\bin;C:\Program Files\Git\usr\bin;C:\Program Files\nodejs;C:\Users\me\Miniconda3;C:\Users\me\Miniconda3\Library\mingw-w64\bin;C:\Users\me\Miniconda3\Library\usr\bin;C:\Users\me\Miniconda3\Library\bin;C:\Users\me\Miniconda3\Scripts;C:\Users\me\AppData\Local\Microsoft\WindowsApps;C:\Users\me\AppData\Local\atom\bin;C:\Program Files\dcm2niix;C:\Users\me\.windows-build-tools\python27;C:\Users\me\AppData\Local\Programs\Microsoft VS Code\bin;C:\Users\me\AppData\Local\Pandoc;C:\Program Files\Oracle\VirtualBox;C:\Users\me\AppData\Local\Microsoft\WindowsApps;C:\Users\me\AppData\Roaming\npm;C:\Program Files\Git\usr\bin\vendor_perl;C:\Program Files\Git\usr\bin\core_perl
  - PYTHONIOENCODING: UTF-8
## extentions 
## git-annex 
  - build flags: 
    - Assistant
    - Webapp
    - Pairing
    - S3(multipartupload)(storageclasses)
    - WebDAV
    - TorrentParser
    - Feeds
    - Testsuite
  - dependency versions: 
    - aws-0.17.1
    - bloomfilter-2.0.1.0
    - cryptonite-0.23
    - DAV-1.3.1
    - feed-0.3.12.0
    - ghc-8.0.2
    - http-client-0.5.7.1
    - persistent-sqlite-2.6.2
    - torrent-10000.1.1
    - uuid-1.3.13
    - yesod-1.4.5
  - key/value backends: 
    - SHA256E
    - SHA256
    - SHA512E
    - SHA512
    - SHA224E
    - SHA224
    - SHA384E
    - SHA384
    - SHA3_256E
    - SHA3_256
    - SHA3_512E
    - SHA3_512
    - SHA3_224E
    - SHA3_224
    - SHA3_384E
    - SHA3_384
    - SKEIN256E
    - SKEIN256
    - SKEIN512E
    - SKEIN512
    - BLAKE2B256E
    - BLAKE2B256
    - BLAKE2B512E
    - BLAKE2B512
    - BLAKE2B160E
    - BLAKE2B160
    - BLAKE2B224E
    - BLAKE2B224
    - BLAKE2B384E
    - BLAKE2B384
    - BLAKE2S256E
    - BLAKE2S256
    - BLAKE2S160E
    - BLAKE2S160
    - BLAKE2S224E
    - BLAKE2S224
    - BLAKE2SP256E
    - BLAKE2SP256
    - BLAKE2SP224E
    - BLAKE2SP224
    - SHA1E
    - SHA1
    - MD5E
    - MD5
    - WORM
    - URL
  - local repository version: 7
  - operating system: mingw32 i386
  - remote types: 
    - git
    - gcrypt
    - p2p
    - S3
    - bup
    - directory
    - rsync
    - web
    - bittorrent
    - webdav
    - adb
    - tahoe
    - glacier
    - ddar
    - hook
    - external
  - supported repository versions: 
    - 5
    - 7
  - upgrade supported from repository versions: 
    - 2
    - 3
    - 4
    - 5
    - 6
  - version: 7.20181206-gc4b6115f7
## metadata_extractors 
  - annex: 
    - load_error: None
    - module: datalad.metadata.extractors.annex
    - version: None
  - audio: 
    - load_error: No module named 'mutagen' [audio.py:<module>:17]
    - module: datalad.metadata.extractors.audio
  - datacite: 
    - load_error: None
    - module: datalad.metadata.extractors.datacite
    - version: None
  - datalad_core: 
    - load_error: None
    - module: datalad.metadata.extractors.datalad_core
    - version: None
  - datalad_rfc822: 
    - load_error: None
    - module: datalad.metadata.extractors.datalad_rfc822
    - version: None
  - exif: 
    - load_error: No module named 'exifread' [exif.py:<module>:16]
    - module: datalad.metadata.extractors.exif
  - frictionless_datapackage: 
    - load_error: None
    - module: datalad.metadata.extractors.frictionless_datapackage
    - version: None
  - image: 
    - load_error: None
    - module: datalad.metadata.extractors.image
    - version: None
  - xmp: 
    - load_error: No module named 'libxmp' [xmp.py:<module>:20]
    - module: datalad.metadata.extractors.xmp
## system 
  - distribution:   10/10.0.17763/SP0/Multiprocessor Free
  - encoding: 
    - default: utf-8
    - filesystem: utf-8
    - locale.prefered: cp1252
  - max_path_length: 259
  - name: Windows
  - release: 10
  - type: nt
  - version: 10.0.17763
```

#### Is there anything else that would be useful to know in this context?
This is a Windows machine. The error happens in Git Bash as well as Powershell.

**Comment by kyleam** [comment]
Thanks for the report.  Tagging as windows-specific because I don't have any luck triggering it on GNU/Linux (py2 or py3).

**Comment by mih** [comment]
I tried on Win7 (didn't have nibabel on it so I used a dummy command with redirection `echo whatever > NOTES`). I cannot replicate this behavior, neither in the standard shell, nor powershell. However, I had to use double-quotes to wrap the command, not single-quotes to get the shell to parse it properly (however, that would be a outside the scope of datalad).

I don't have a Win10 environment around ATM.

Is there error specific to this particular command, or do you see it in general?

There is little chance that it would have an impact, but could you try installing `datalad-revolution` from pip and replace the `run` sub-command with `rev-run` and try that one? Thanks!

**Comment by chrisfilo** [comment]
```
me@christop /c/scratch/datalad_test/test (adjusted/master(unlocked)) $ datalad --dbg run 'echo 123 > test.md'
[INFO] == Command start (output follows) =====
[INFO] == Command exit (modification check follows) =====
Traceback (most recent call last):
  File "c:\users\me\miniconda3\lib\runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "c:\users\me\miniconda3\lib\runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "C:\Users\me\Miniconda3\Scripts\datalad.exe\__main__.py", line 9, in <module>
    sys.exit(main())
  File "c:\users\me\miniconda3\lib\site-packages\datalad\cmdline\main.py", line 495, in main
    ret = cmdlineargs.func(cmdlineargs)
  File "c:\users\me\miniconda3\lib\site-packages\datalad\interface\base.py", line 628, in call_from_parser
    ret = list(ret)
  File "c:\users\me\miniconda3\lib\site-packages\datalad\interface\utils.py", line 422, in generator_func
    result_renderer, result_xfm, _result_filter, **_kwargs):
  File "c:\users\me\miniconda3\lib\site-packages\datalad\interface\utils.py", line 509, in _process_results
    for res in results:
  File "c:\users\me\miniconda3\lib\site-packages\datalad\interface\run.py", line 222, in __call__
    sidecar=sidecar):
  File "c:\users\me\miniconda3\lib\site-packages\datalad\interface\run.py", line 716, in run_command
    for r in ds.add(outputs_to_save, recursive=True, message=msg):
  File "c:\users\me\miniconda3\lib\site-packages\datalad\distribution\dataset.py", line 494, in apply_func
    return f(**kwargs)
  File "c:\users\me\miniconda3\lib\site-packages\datalad\interface\utils.py", line 479, in eval_func
    return return_func(generator_func)(*args, **kwargs)
  File "c:\users\me\miniconda3\lib\site-packages\datalad\interface\utils.py", line 467, in return_func
    results = list(results)
  File "c:\users\me\miniconda3\lib\site-packages\datalad\interface\utils.py", line 422, in generator_func
    result_renderer, result_xfm, _result_filter, **_kwargs):
  File "c:\users\me\miniconda3\lib\site-packages\datalad\interface\utils.py", line 509, in _process_results
    for res in results:
  File "c:\users\me\miniconda3\lib\site-packages\datalad\distribution\add.py", line 511, in __call__
    on_failure='ignore'):
  File "c:\users\me\miniconda3\lib\site-packages\datalad\interface\utils.py", line 422, in generator_func
    result_renderer, result_xfm, _result_filter, **_kwargs):
  File "c:\users\me\miniconda3\lib\site-packages\datalad\interface\utils.py", line 509, in _process_results
    for res in results:
  File "c:\users\me\miniconda3\lib\site-packages\datalad\interface\save.py", line 398, in __call__
    message=message)
  File "c:\users\me\miniconda3\lib\site-packages\datalad\interface\save.py", line 142, in save_dataset
    careless=True)
  File "c:\users\me\miniconda3\lib\site-packages\datalad\support\annexrepo.py", line 2963, in commit
    files=files_to_commit)
  File "c:\users\me\miniconda3\lib\site-packages\datalad\support\gitrepo.py", line 1308, in commit
    index_file=index_file)
  File "c:\users\me\miniconda3\lib\site-packages\datalad\support\annexrepo.py", line 1256, in _git_custom_command
    return super(AnnexRepo, self)._git_custom_command(*args, **kwargs)
  File "c:\users\me\miniconda3\lib\site-packages\datalad\support\gitrepo.py", line 313, in newfunc
    result = func(self, files_new, *args, **kwargs)
  File "c:\users\me\miniconda3\lib\site-packages\datalad\support\gitrepo.py", line 1747, in _git_custom_command
    expect_fail=expect_fail)
  File "c:\users\me\miniconda3\lib\site-packages\datalad\cmd.py", line 673, in run
    cmd, env=self.get_git_environ_adjusted(env), *args, **kwargs)
  File "c:\users\me\miniconda3\lib\site-packages\datalad\cmd.py", line 487, in run
    stdin=stdin)
  File "c:\users\me\miniconda3\lib\subprocess.py", line 729, in __init__
    restore_signals, start_new_session)
  File "c:\users\me\miniconda3\lib\subprocess.py", line 991, in _execute_child
    args = list2cmdline(args)
  File "c:\users\me\miniconda3\lib\subprocess.py", line 481, in list2cmdline
    needquote = (" " in arg) or ("\t" in arg) or not arg
TypeError: a bytes-like object is required, not 'str'
```

**Comment by chrisfilo** [comment]
installing `datalad-revolution` did not help

**Comment by mih** [comment]
While looking into https://github.com/datalad/datalad/issues/3637 and a possible fix https://github.com/datalad/datalad/pull/3688 I realized that this bug is potentially pointing at the same underlying issue: https://github.com/datalad/datalad/pull/3688#issuecomment-533090988

**Comment by mih** [comment]
OK, here is the state of things on win10 with current master:

```
(base) C:\Users\mih>datalad create quote
[INFO] Creating a new annex repo at C:\Users\mih\quote
[INFO]   Detected a filesystem without fifo support.
[INFO]   Disabling ssh connection caching.
[INFO]   Detected a crippled filesystem.
[INFO]   Entering an adjusted branch where files are unlocked as this filesystem does not support locked files.
[INFO] Switched to branch 'adjusted/master(unlocked)'
create(ok): C:\Users\mih\quote (dataset)

(base) C:\Users\mih>cd quote

(base) C:\Users\mih\quote>datalad run cp .gitattributes test
[INFO] == Command start (output follows) =====
[INFO] == Command exit (modification check follows) =====
add(ok): test (file)
save(ok): . (dataset)
action summary:
  add (ok: 1)
  save (ok: 1)

(base) C:\Users\mih\quote>git log
commit c0d16c97feddbf263d5b69be086022ca425ef95f
Author: Michael Hanke <michael.hanke@gmail.com>
Date:   Sat Sep 21 13:56:53 2019 +0200

    [DATALAD RUNCMD] cp .gitattributes test

    === Do not change lines below ===
    {
     "chain": [],
     "cmd": "cp .gitattributes test",
     "dsid": "d41d2764-dc66-11e9-8e06-309c23c2cf5c",
     "exit": 0,
     "extra_inputs": [],
     "inputs": [],
     "outputs": [],
     "pwd": "."
    }
    ^^^ Do not change lines above ^^^
```

So there is no fundamental issue with `datalad run`.

Now for the full replication:

```
(base) C:\Users\mih\quote>git annex addurl https://nifti.nimh.nih.gov/nifti-1/data/avg152T1_LR_nifti.nii.gz
addurl https://nifti.nimh.nih.gov/nifti-1/data/avg152T1_LR_nifti.nii.gz
(to nifti.nimh.nih.gov_nifti_1_data_avg152T1_LR_nifti.nii.gz) ok
(recording state in git...)

(base) C:\Users\mih\quote>datalad save
save(ok): . (dataset)

(base) C:\Users\mih\quote>nib-ls -s nifti.nimh.nih.gov_nifti_1_data_avg152T1_LR_nifti.nii.gz
nifti.nimh.nih.gov_nifti_1_data_avg152T1_LR_nifti.nii.gz uint8 [ 91, 109,  91] 2.00x2.00x2.00   sform [902569] [1, 2.6e+02]

(base) C:\Users\mih\quote>datalad run 'nib-ls -s nifti.nimh.nih.gov_nifti_1_data_avg152T1_LR_nifti.nii.gz > INFO.txt'

(base) C:\Users\mih\quote>ls
"INFO.txt'"   nifti.nimh.nih.gov_nifti_1_data_avg152T1_LR_nifti.nii.gz   test
```

Clearly, the command line handling is broken, because the filename ends up being `INFO.txt'`. For reasons unclear to me `datalad run` also does not pick up the created file.

```
(base) C:\Users\mih\quote>datalad status OR datalad diff
untracked: INFO.txt' (file)
```

However, switching to double-quotes let's datalad behave as desired:

```
(base) C:\Users\mih\quote>datalad run "nib-ls -s nifti.nimh.nih.gov_nifti_1_data_avg152T1_LR_nifti.nii.gz > INFO.txt"
[INFO] == Command start (output follows) =====
[INFO] == Command exit (modification check follows) =====
add(ok): INFO.txt (file)
save(ok): . (dataset)
action summary:
  add (ok: 1)
  save (ok: 1)

(base) C:\Users\mih\quote>git log
commit 88a66ac1b87c22528634bbd54fdd095c154a0871 (HEAD -> adjusted/master(unlocked))
Author: Michael Hanke <michael.hanke@gmail.com>
Date:   Sat Sep 21 14:14:03 2019 +0200

    [DATALAD RUNCMD] nib-ls -s nifti.nimh.nih.gov_nifti_1_dat...

    === Do not change lines below ===
    {
     "chain": [],
     "cmd": "nib-ls -s nifti.nimh.nih.gov_nifti_1_data_avg152T1_LR_nifti.nii.gz > INFO.txt",
     "dsid": "d41d2764-dc66-11e9-8e06-309c23c2cf5c",
     "exit": 0,
     "extra_inputs": [],
     "inputs": [],
     "outputs": [],
     "pwd": "."
    }
    ^^^ Do not change lines above ^^^
```

Based on this result I conclude that

1) I have little to no idea on how quoting is supposed to work on Windows (or more specifically with `subprocess` on Windows)
2) we can close the bug, because the original behavior can no longer be found. But we have to take care of https://github.com/datalad/datalad/issues/3697
