### ISSUE TITLE
appveyor became unhappy (recent annex release?)

### ISSUE THREAD

**Issue by yarikoptic** [datalad/datalad#3130]
initially ran into in https://github.com/datalad/datalad/pull/3129

I think it is due to new annex cmd:annex: 7.20190122-gc94b3a389  since a few days prior that tests were all green.
failure
```
======================================================================
FAIL: datalad.distribution.tests.test_install.test_datasets_datalad_org('',)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "C:\Miniconda35\envs\test-environment\lib\site-packages\nose\case.py", line 198, in runTest
    self.test(*self.arg)
  File "C:\Miniconda35\envs\test-environment\lib\site-packages\datalad\tests\utils.py", line 849, in newfunc
    return func(*args, **kwargs)
  File "C:\Miniconda35\envs\test-environment\lib\site-packages\datalad\tests\utils.py", line 615, in newfunc
    return t(*(arg + (filename,)), **kw)
  File "C:\Miniconda35\envs\test-environment\lib\site-packages\datalad\distribution\tests\test_install.py", line 945, in check_datasets_datalad_org
    status='ok')
  File "C:\Miniconda35\envs\test-environment\lib\site-packages\datalad\tests\utils.py", line 1281, in assert_result_count
    dumps(results, indent=1, default=lambda x: str(x))))
AssertionError: Got 0 instead of 1 expected results matching {'status': 'ok'}. Inspected 1 record(s):
[
 {
  "status": "notneeded",
  "path": "C:\\Users\\appveyor\\AppData\\Local\\Temp\\1\\datalad_temp_81qc9hhh\\001-anat-scout_ses-{date}\\000001.dcm",
  "type": "file",
  "refds": "C:\\Users\\appveyor\\AppData\\Local\\Temp\\1\\datalad_temp_81qc9hhh",
  "action": "get",
  "message": "already present"
 }
]
======================================================================
FAIL: datalad.distribution.tests.test_install.test_datasets_datalad_org('/.git',)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "C:\Miniconda35\envs\test-environment\lib\site-packages\nose\case.py", line 198, in runTest
    self.test(*self.arg)
  File "C:\Miniconda35\envs\test-environment\lib\site-packages\datalad\tests\utils.py", line 849, in newfunc
    return func(*args, **kwargs)
  File "C:\Miniconda35\envs\test-environment\lib\site-packages\datalad\tests\utils.py", line 615, in newfunc
    return t(*(arg + (filename,)), **kw)
  File "C:\Miniconda35\envs\test-environment\lib\site-packages\datalad\distribution\tests\test_install.py", line 945, in check_datasets_datalad_org
    status='ok')
  File "C:\Miniconda35\envs\test-environment\lib\site-packages\datalad\tests\utils.py", line 1281, in assert_result_count
    dumps(results, indent=1, default=lambda x: str(x))))
AssertionError: Got 0 instead of 1 expected results matching {'status': 'ok'}. Inspected 1 record(s):
[
 {
  "status": "notneeded",
  "path": "C:\\Users\\appveyor\\AppData\\Local\\Temp\\1\\datalad_temp_fi91roug\\001-anat-scout_ses-{date}\\000001.dcm",
  "type": "file",
  "refds": "C:\\Users\\appveyor\\AppData\\Local\\Temp\\1\\datalad_temp_fi91roug",
  "action": "get",
  "message": "already present"
 }
]
```

**Comment by kyleam** [comment]
> initially ran into in #3129

Going further back, this looks to be the same failures as gh-2976, which were [addressed with a newer annex][0].

[0]: https://github.com/datalad/datalad/issues/2976#issuecomment-443841055

> I think it is due to new annex cmd:annex: 7.20190122-gc94b3a389 since a few days prior that tests were all green.

My uneducated guess is 5759e9344 (honor init --version=5 on crippled filesystem, 2018-12-19).  I'll have a go at bisecting it later today.

**Comment by yarikoptic** [comment]
Fwiw, never built it on Windows, but isn't there a similar make rule to 'make linuxstandalone'? Also it smells like it is not Windows specific issue but if the crippled filesystems, which you could test on Linux using eg https://github.com/datalad/datalad/blob/master/tools/eval_under_testloopfs

**Comment by kyleam** [comment]
Right, I was using tools/eval_under_testloopfs to try to trigger it, following [your post][0] I linked to above.  I wouldn't have dared attempting to build on Windows :]

> make linuxstandalone

That appears to build with cabal rather than stack by default, so it should work.  My point was simply that my old setup of using stack, which was working well for building git-annex in the past, no longer is. (It looks to be a stack/stretch issue.)  And so my statement that I'd "have a go at bisecting it" will be delayed until I get around to troubleshooting my stack build or switching to another method.  I of course wouldn't mind if someone else tested my suspicion that 5759e9344 is the culprit :]

[0]: https://github.com/datalad/datalad/issues/2976#issuecomment-443841055

**Comment by kyleam** [comment]
OK, I've tried to bisect it. Sadly I can't trigger the failure with tools/eval_under_testloopfs using a recent annex commit, including the failing commit from [this] appveyor run or my guess culprit 5759e9344.  As a sanity check, if I go back to a failing commit from gh-2976 (6ba6c6b53), I **can** trigger the test failures.

[this]: https://ci.appveyor.com/project/mih/datalad/builds/21947044/job/ute7avuac7oi12jp

**Comment by mih** [comment]
I was trying to find the core issue with all the Windows test failures in -revolution. I can confirm that git-annex behavior changed on windows between Nov and now. Below is a demo of how to get to the most frequently reported test failure state.

```
C:\Users\IEUser\AppData\Local\Temp>mkdir test
C:\Users\IEUser\AppData\Local\Temp>cd test
C:\Users\IEUser\AppData\Local\Temp\test>git init
Initialized empty Git repository in C:/Users/IEUser/AppData/Local/Temp/test/.git/

C:\Users\IEUser\AppData\Local\Temp\test>git annex init
init
  Detected a filesystem without fifo support.
  Disabling ssh connection caching.
  Detected a crippled filesystem.
  Disabling core.symlinks.

  Entering an adjusted branch where files are unlocked as this filesystem does not support locked files.

Switched to branch 'adjusted/master(unlocked)'
ok
(recording state in git...)

C:\Users\IEUser\AppData\Local\Temp\test>echo "some" > test
C:\Users\IEUser\AppData\Local\Temp\test>git annex add test
add test ok
(recording state in git...)

C:\Users\IEUser\AppData\Local\Temp\test>git status
On branch adjusted/master(unlocked)
Changes to be committed:
  (use "git reset HEAD <file>..." to unstage)

        new file:   test

Changes not staged for commit:
  (use "git add <file>..." to update what will be committed)
  (use "git checkout -- <file>..." to discard changes in working directory)

        modified:   test

C:\Users\IEUser\AppData\Local\Temp\test>git commit -m test
[adjusted/master(unlocked) caebd32] test
 1 file changed, 1 insertion(+)
 create mode 100644 test

C:\Users\IEUser\AppData\Local\Temp\test>git status
On branch adjusted/master(unlocked)
Changes not staged for commit:
  (use "git add <file>..." to update what will be committed)
  (use "git checkout -- <file>..." to discard changes in working directory)

        modified:   test

no changes added to commit (use "git add" and/or "git commit -a")

C:\Users\IEUser\AppData\Local\Temp\test>git diff
diff --git a/test b/test
index 94cb737..fd55ba7 100644
--- a/test
+++ b/test
@@ -1 +1 @@
-/annex/objects/SHA256E-s9--dc23eba28929ba6739c0fd55c24497f32121fd544db8854a6498dcaea04f899e
+"some"

C:\Users\IEUser\AppData\Local\Temp\test>git branch
* adjusted/master(unlocked)
  git-annex
  master
```

**Comment by mih** [comment]
A second issue on Windows is that git-annex does not provide info on annex'ed content anymore. This affects commands like `whereis`, `find`, and `findref`.

```

```

**Comment by mih** [comment]
```
C:\Users\IEUser\AppData\Local\Temp>datalad rev-create testwin
[INFO] Creating a new annex repo at C:\Users\IEUser\AppData\Local\Temp\testwin
[INFO]   Detected a filesystem without fifo support.
[INFO]   Disabling ssh connection caching.
[INFO]   Detected a crippled filesystem.
[INFO]   Disabling core.symlinks.
[INFO]   Entering an adjusted branch where files are unlocked as this filesystem does not support locked files.
[INFO] Switched to branch 'adjusted/master(unlocked)'
create(ok): C:\Users\IEUser\AppData\Local\Temp\testwin (dataset)

C:\Users\IEUser\AppData\Local\Temp>cd testwin

C:\Users\IEUser\AppData\Local\Temp\testwin>echo "nothing" > dummy

C:\Users\IEUser\AppData\Local\Temp\testwin>datalad rev-save
add(ok): dummy (file)
save(ok): . (dataset)
action summary:
  add (ok: 1)
  save (ok: 1)

C:\Users\IEUser\AppData\Local\Temp\testwin>git annex whereis dummy

C:\Users\IEUser\AppData\Local\Temp\testwin>git status
On branch adjusted/master(unlocked)
nothing to commit, working tree clean

C:\Users\IEUser\AppData\Local\Temp\testwin>git annex find --include=* --json

C:\Users\IEUser\AppData\Local\Temp\testwin>git annex findref HEAD --json

C:\Users\IEUser\AppData\Local\Temp\testwin>git annex version
git-annex version: 7.20190122-g49b31f7c0
build flags: Assistant Webapp Pairing S3(multipartupload)(storageclasses) WebDAV TorrentParser Feeds Testsuite
dependency versions: aws-0.17.1 bloomfilter-2.0.1.0 cryptonite-0.23 DAV-1.3.1 feed-0.3.12.0 ghc-8.0.2 http-clien
key/value backends: SHA256E SHA256 SHA512E SHA512 SHA224E SHA224 SHA384E SHA384 SHA3_256E SHA3_256 SHA3_512E SHA
remote types: git gcrypt p2p S3 bup directory rsync web bittorrent webdav adb tahoe glacier ddar hook external
operating system: mingw32 i386
supported repository versions: 5 7
upgrade supported from repository versions: 2 3 4 5 6
local repository version: 7

C:\Users\IEUser\AppData\Local\Temp\testwin>git annex info
repository mode: indirect
trusted repositories: 0
semitrusted repositories: 3
        00000000-0000-0000-0000-000000000001 -- web
        00000000-0000-0000-0000-000000000002 -- bittorrent
        d0e85834-9f73-4753-9219-7f5606806443 -- IEUser@IEWIN7:~/AppData\Local\Temp\testwin [here]
untrusted repositories: 0
transfers in progress: none
available local disk space: 24.22 gigabytes (+1 megabyte reserved)
local annex keys: 1
local annex size: 12 bytes
annexed files in working tree: 0
size of annexed files in working tree: 0 bytes
bloom filter size:
  bloomfilter capacity too large to represent; falling back to sane value
32 mebibytes (0% full)
backend usage:
```

**Comment by yarikoptic** [comment]
I found similar illness symptoms while trying in appveyor - like annex does no longer care about the files which get annexed
![image](https://user-images.githubusercontent.com/39889/52541947-ccf57d80-2d68-11e9-8cc4-f69793264488.png)
I am just not sure how come only that single test is failing and not the rest.
@joeyh - what do you know about current windows release usability on windows and changed behaviors from the previous one?

**Comment by joeyh** [comment]
http://git-annex.branchable.com/bugs/windows_support_totally_bitrotted/

-- 
see shy jo

**Comment by mih** [comment]
git-annex on windows is back in business. Thanks @joeyh
