### ISSUE TITLE
Make tests smarter for testing unicode on (file)systems without unicode support

### ISSUE THREAD

**Issue by yarikoptic** [datalad/datalad#3148]
unicode strikes more while building debian packages for 0.11.2  (LANG=C) causing 5 tests failures

<details>
<summary>5 tests</summary>

```
Finished processing dependencies for datalad==0.11.2
I: pybuild base:217: cd /build/datalad-0.11.2/.pybuild/cpython2_2.7_datalad/build; python2.7 -m nose -v -s -v
nose.config: INFO: Ignoring files matching ['^\\.', '^_', '^setup\\.py$']
Failure: SkipTest () ... SKIP
datalad.cmdline.tests.test_helpers.test_strip_arg_from_argv ... ok
datalad.cmdline.tests.test_helpers.test_get_repo_instance_annex ... ok
datalad.cmdline.tests.test_helpers.test_get_repo_instance_git ... ok
...
======================================================================
ERROR: datalad.distribution.tests.test_add.test_add_message_file
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/usr/lib/python2.7/dist-packages/nose/case.py", line 197, in runTest
    self.test(*self.arg)
  File "/build/datalad-0.11.2/.pybuild/cpython2_2.7_datalad/build/datalad/tests/utils.py", line 615, in newfunc
    return t(*(arg + (filename,)), **kw)
  File "/build/datalad-0.11.2/.pybuild/cpython2_2.7_datalad/build/datalad/distribution/tests/test_add.py", line 74, in test_add_message_file
    ds.add("foo", message_file=opj(ds.path, "msg"))
  File "/usr/lib/python2.7/dist-packages/wrapt/wrappers.py", line 562, in __call__
    args, kwargs)
  File "/build/datalad-0.11.2/.pybuild/cpython2_2.7_datalad/build/datalad/distribution/dataset.py", line 494, in apply_func
    return f(**kwargs)
  File "/usr/lib/python2.7/dist-packages/wrapt/wrappers.py", line 523, in __call__
    args, kwargs)
...
  File "/build/datalad-0.11.2/.pybuild/cpython2_2.7_datalad/build/datalad/interface/utils.py", line 479, in return_func
    results = list(results)
  File "/build/datalad-0.11.2/.pybuild/cpython2_2.7_datalad/build/datalad/interface/utils.py", line 428, in generator_func
    result_renderer, result_xfm, _result_filter, **_kwargs):
  File "/build/datalad-0.11.2/.pybuild/cpython2_2.7_datalad/build/datalad/interface/utils.py", line 521, in _process_results
    for res in results:
  File "/build/datalad-0.11.2/.pybuild/cpython2_2.7_datalad/build/datalad/distribution/add.py", line 525, in __call__
    on_failure='ignore'):
  File "/build/datalad-0.11.2/.pybuild/cpython2_2.7_datalad/build/datalad/interface/utils.py", line 428, in generator_func
    result_renderer, result_xfm, _result_filter, **_kwargs):
  File "/build/datalad-0.11.2/.pybuild/cpython2_2.7_datalad/build/datalad/interface/utils.py", line 521, in _process_results
    for res in results:
  File "/build/datalad-0.11.2/.pybuild/cpython2_2.7_datalad/build/datalad/interface/save.py", line 390, in __call__
    message=message)
  File "/build/datalad-0.11.2/.pybuild/cpython2_2.7_datalad/build/datalad/interface/save.py", line 144, in save_dataset
    careless=True)
  File "/build/datalad-0.11.2/.pybuild/cpython2_2.7_datalad/build/datalad/support/annexrepo.py", line 2949, in commit
    files=files_to_commit)
  File "/build/datalad-0.11.2/.pybuild/cpython2_2.7_datalad/build/datalad/support/gitrepo.py", line 1312, in commit
    index_file=index_file)
  File "/build/datalad-0.11.2/.pybuild/cpython2_2.7_datalad/build/datalad/support/annexrepo.py", line 1261, in _git_custom_command
    return super(AnnexRepo, self)._git_custom_command(*args, **kwargs)
  File "/build/datalad-0.11.2/.pybuild/cpython2_2.7_datalad/build/datalad/support/gitrepo.py", line 316, in newfunc
    result = func(self, files_new, *args, **kwargs)
  File "/build/datalad-0.11.2/.pybuild/cpython2_2.7_datalad/build/datalad/support/gitrepo.py", line 1748, in _git_custom_command
    expect_fail=expect_fail)
  File "/build/datalad-0.11.2/.pybuild/cpython2_2.7_datalad/build/datalad/support/gitrepo.py", line 1800, in _run_command_files_split
    *args, **kwargs)
  File "/build/datalad-0.11.2/.pybuild/cpython2_2.7_datalad/build/datalad/cmd.py", line 683, in run
    cmd, env=self.get_git_environ_adjusted(env), *args, **kwargs)
  File "/build/datalad-0.11.2/.pybuild/cpython2_2.7_datalad/build/datalad/cmd.py", line 496, in run
    stdin=stdin)
  File "/usr/lib/python2.7/subprocess.py", line 394, in __init__
    errread, errwrite)
  File "/usr/lib/python2.7/subprocess.py", line 1047, in _execute_child
    raise child_exception
UnicodeEncodeError: 'ascii' codec can't encode character u'\u03b2' in position 4: ordinal not in range(128)

======================================================================
ERROR: datalad.interface.tests.test_run.test_py2_unicode_command
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/usr/lib/python2.7/dist-packages/nose/case.py", line 197, in runTest
    self.test(*self.arg)
  File "/build/datalad-0.11.2/.pybuild/cpython2_2.7_datalad/build/datalad/tests/utils.py", line 615, in newfunc
    return t(*(arg + (filename,)), **kw)
  File "/build/datalad-0.11.2/.pybuild/cpython2_2.7_datalad/build/datalad/interface/tests/test_run.py", line 146, in test_py2_unicode_command
    ds.run(cmd_str)
  File "/usr/lib/python2.7/dist-packages/wrapt/wrappers.py", line 562, in __call__
    args, kwargs)
  File "/build/datalad-0.11.2/.pybuild/cpython2_2.7_datalad/build/datalad/distribution/dataset.py", line 494, in apply_func
    return f(**kwargs)
  File "/usr/lib/python2.7/dist-packages/wrapt/wrappers.py", line 523, in __call__
    args, kwargs)
  File "/build/datalad-0.11.2/.pybuild/cpython2_2.7_datalad/build/datalad/interface/utils.py", line 491, in eval_func
    return return_func(generator_func)(*args, **kwargs)
  File "/usr/lib/python2.7/dist-packages/wrapt/wrappers.py", line 523, in __call__
    args, kwargs)
  File "/build/datalad-0.11.2/.pybuild/cpython2_2.7_datalad/build/datalad/interface/utils.py", line 479, in return_func
    results = list(results)
  File "/build/datalad-0.11.2/.pybuild/cpython2_2.7_datalad/build/datalad/interface/utils.py", line 428, in generator_func
    result_renderer, result_xfm, _result_filter, **_kwargs):
  File "/build/datalad-0.11.2/.pybuild/cpython2_2.7_datalad/build/datalad/interface/utils.py", line 521, in _process_results
    for res in results:
  File "/build/datalad-0.11.2/.pybuild/cpython2_2.7_datalad/build/datalad/interface/run.py", line 221, in __call__
    sidecar=sidecar):
  File "/build/datalad-0.11.2/.pybuild/cpython2_2.7_datalad/build/datalad/interface/run.py", line 551, in run_command
    expected_exit=rerun_info.get("exit", 0) if rerun_info else None)
  File "/build/datalad-0.11.2/.pybuild/cpython2_2.7_datalad/build/datalad/interface/run.py", line 390, in _execute_command
    expect_fail=True,
  File "/build/datalad-0.11.2/.pybuild/cpython2_2.7_datalad/build/datalad/cmd.py", line 496, in run
    stdin=stdin)
  File "/usr/lib/python2.7/subprocess.py", line 394, in __init__
    errread, errwrite)
  File "/usr/lib/python2.7/subprocess.py", line 1047, in _execute_child
    raise child_exception
TypeError: execv() arg 2 must contain only strings

======================================================================
ERROR: datalad.interface.tests.test_save.test_save_message_file
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/usr/lib/python2.7/dist-packages/nose/case.py", line 197, in runTest
    self.test(*self.arg)
  File "/build/datalad-0.11.2/.pybuild/cpython2_2.7_datalad/build/datalad/tests/utils.py", line 615, in newfunc
    return t(*(arg + (filename,)), **kw)
  File "/build/datalad-0.11.2/.pybuild/cpython2_2.7_datalad/build/datalad/interface/tests/test_save.py", line 279, in test_save_message_file
    ds.save(message_file=opj(ds.path, "msg"))
  File "/usr/lib/python2.7/dist-packages/wrapt/wrappers.py", line 562, in __call__
    args, kwargs)
...
  File "/build/datalad-0.11.2/.pybuild/cpython2_2.7_datalad/build/datalad/interface/utils.py", line 479, in return_func
    results = list(results)
  File "/build/datalad-0.11.2/.pybuild/cpython2_2.7_datalad/build/datalad/interface/utils.py", line 428, in generator_func
    result_renderer, result_xfm, _result_filter, **_kwargs):
  File "/build/datalad-0.11.2/.pybuild/cpython2_2.7_datalad/build/datalad/interface/utils.py", line 521, in _process_results
    for res in results:
  File "/build/datalad-0.11.2/.pybuild/cpython2_2.7_datalad/build/datalad/interface/save.py", line 390, in __call__
    message=message)
  File "/build/datalad-0.11.2/.pybuild/cpython2_2.7_datalad/build/datalad/interface/save.py", line 144, in save_dataset
    careless=True)
  File "/build/datalad-0.11.2/.pybuild/cpython2_2.7_datalad/build/datalad/support/annexrepo.py", line 2949, in commit
    files=files_to_commit)
  File "/build/datalad-0.11.2/.pybuild/cpython2_2.7_datalad/build/datalad/support/gitrepo.py", line 1312, in commit
    index_file=index_file)
  File "/build/datalad-0.11.2/.pybuild/cpython2_2.7_datalad/build/datalad/support/annexrepo.py", line 1261, in _git_custom_command
    return super(AnnexRepo, self)._git_custom_command(*args, **kwargs)
  File "/build/datalad-0.11.2/.pybuild/cpython2_2.7_datalad/build/datalad/support/gitrepo.py", line 316, in newfunc
    result = func(self, files_new, *args, **kwargs)
  File "/build/datalad-0.11.2/.pybuild/cpython2_2.7_datalad/build/datalad/support/gitrepo.py", line 1748, in _git_custom_command
    expect_fail=expect_fail)
  File "/build/datalad-0.11.2/.pybuild/cpython2_2.7_datalad/build/datalad/support/gitrepo.py", line 1800, in _run_command_files_split
    *args, **kwargs)
  File "/build/datalad-0.11.2/.pybuild/cpython2_2.7_datalad/build/datalad/cmd.py", line 683, in run
    cmd, env=self.get_git_environ_adjusted(env), *args, **kwargs)
  File "/build/datalad-0.11.2/.pybuild/cpython2_2.7_datalad/build/datalad/cmd.py", line 496, in run
    stdin=stdin)
  File "/usr/lib/python2.7/subprocess.py", line 394, in __init__
    errread, errwrite)
  File "/usr/lib/python2.7/subprocess.py", line 1047, in _execute_child
    raise child_exception
UnicodeEncodeError: 'ascii' codec can't encode character u'\u03b2' in position 4: ordinal not in range(128)
======================================================================
ERROR: datalad.support.tests.test_globbedpaths.test_globbedpaths
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/usr/lib/python2.7/dist-packages/nose/case.py", line 197, in runTest
    self.test(*self.arg)
  File "/build/datalad-0.11.2/.pybuild/cpython2_2.7_datalad/build/datalad/tests/utils.py", line 440, in newfunc
    create_tree(d, tree, archives_leading_dir=archives_leading_dir)
  File "/build/datalad-0.11.2/.pybuild/cpython2_2.7_datalad/build/datalad/utils.py", line 2139, in create_tree
    with open_func(full_name, "wb") as f:
UnicodeEncodeError: 'ascii' codec can't encode character u'\u03b2' in position 48: ordinal not in range(128)

======================================================================
ERROR: datalad.tests.test_cmd.test_runner_failure_unicode
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/usr/lib/python2.7/dist-packages/nose/case.py", line 197, in runTest
    self.test(*self.arg)
  File "/build/datalad-0.11.2/.pybuild/cpython2_2.7_datalad/build/datalad/tests/utils.py", line 615, in newfunc
    return t(*(arg + (filename,)), **kw)
  File "/build/datalad-0.11.2/.pybuild/cpython2_2.7_datalad/build/datalad/tests/test_cmd.py", line 261, in test_runner_failure_unicode
    runner.run(u"β-command-doesnt-exist", cwd=path)
  File "/build/datalad-0.11.2/.pybuild/cpython2_2.7_datalad/build/datalad/cmd.py", line 496, in run
    stdin=stdin)
  File "/usr/lib/python2.7/subprocess.py", line 394, in __init__
    errread, errwrite)
  File "/usr/lib/python2.7/subprocess.py", line 1047, in _execute_child
    raise child_exception
TypeError: execv() arg 2 must contain only strings

----------------------------------------------------------------------
Ran 880 tests in 2496.874s
```
</details>

where we have environment without unicode support:

```shell
root@smaug:/build/datalad-0.11.2/.pybuild/cpython2_2.7_datalad/build# PYTHONPATH=$PWD python -c 'from datalad.api import wtf;print(wtf())'
# WTF
...
## environment 
  - GIT_PYTHON_GIT_EXECUTABLE: /usr/bin/git
  - LANG: C
  - LC_ALL: C
  - PATH: /usr/sbin:/usr/bin:/sbin:/bin
  - PYTHONPATH: /build/datalad-0.11.2/.pybuild/cpython2_2.7_datalad/build

# python -c 'import sys; print(sys.getfilesystemencoding())'
ANSI_X3.4-1968
```
and I already carry debian/patches/deb_no_utf8  (debian branch) which tunes some tests to avoid utf-8 in them,  but as this pain shows -- tests should be smarter to either not use unicode on systems where unicode is not supported, or just skip those tests.
For now I will need to adjust the patch :-/

**Comment by mih** [comment]
I have the impression that this can be closed. Do you agree @yarikoptic ?

**Comment by yarikoptic** [comment]
we still have some issues, have some adhoc patching in debian package (could be dropped or not -- dunnot yet), I will submit some workaround PR shortly, but yeah -- let's close -- reported with 2.7 - long gone
