### ISSUE TITLE
Debian jessie nd80 FTBFS - libxpm is N/A - import fails

### ISSUE THREAD

**Issue by yarikoptic** [datalad/datalad#3170]
This is due to python-libxmp removed from build-depends in 0.11.2-2, but it is ok for everywhere else, probably some intricacy of nose (1.3.4-1 vs 1.3.7-2 in nd90) itself?
```
======================================================================
ERROR: Failure: ImportError (No module named libxmp.utils)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/usr/lib/python2.7/dist-packages/nose/loader.py", line 414, in loadTestsFromName
    addr.filename, addr.module)
  File "/usr/lib/python2.7/dist-packages/nose/importer.py", line 47, in importFromPath
    return self.importFromDir(dir_path, fqname)
  File "/usr/lib/python2.7/dist-packages/nose/importer.py", line 94, in importFromDir
    mod = load_module(part_fqname, fh, filename, desc)
  File "/build/datalad-0.11.3/.pybuild/pythonX.Y_2.7/build/datalad/metadata/extractors/xmp.py", line 20, in <module>
    from libxmp.utils import file_to_dict
ImportError: No module named libxmp.utils

----------------------------------------------------------------------
Ran 892 tests in 3692.223s

FAILED (SKIP=99, errors=1)
```

**Comment by yarikoptic** [comment]
was fixed via build-depends for 0.11.3-1
