### ISSUE TITLE
A few issues while running the tests on conda installed new annex and datalad

### ISSUE THREAD

**Issue by yarikoptic** [datalad/datalad#3224]
just so we know

```shell
$> datalad --version
datalad 0.11.3

$> python -m nose -s -v datalad
....
datalad.tests.test_version.test__version__ ... SKIP: no /home/yoh/anaconda-4.4.0-3.6/envs/git-annex-test/lib/python3.7/site-packages/datalad/tests/../../CHANGELOG.md found
Versions: appdirs=1.4.3 boto=2.49.0 cmd:annex=7.20190219-g16f7885 cmd:git=2.19.1 cmd:system-git=2.19.1 cmd:system-ssh=7.9p1 exifread=2.1.2 git=2.1.11 gitdb=2.0.5 humanize=0.5.1 iso8601=0.1.12 keyring=18.0.0 keyrings.alt=3.1 msgpack=0.6.1 mutagen=1.41.1 patoolib=1.12 requests=2.21.0 six=1.12.0 tqdm=4.31.1 wrapt=1.11.1
Obscure filename: str=b' "\';a&b&c\xce\x94\xd0\x99\xd7\xa7\xd9\x85\xe0\xb9\x97\xe3\x81\x82 `| ' repr=' "\';a&b&cΔЙקم๗あ `| '
Encodings: default='utf-8' filesystem='utf-8' locale.prefered='UTF-8'
Environment: PATH='/home/yoh/anaconda-4.4.0-3.6/envs/git-annex-test/bin:/home/yoh/anaconda-2018.12-3.7/bin:/home/yoh/gocode/bin:/home/yoh/gocode/bin:/home/yoh/bin:/home/yoh/.local/bin:/usr/local/bin:/usr/bin:/bin:/usr/local/games:/usr/games:/snap/bin:/sbin:/usr/sbin:/usr/local/sbin' LANG='en_US.utf8' GIT_PAGER='less --no-init --quit-if-one-screen' GIT_PYTHON_GIT_EXECUTABLE='/home/yoh/anaconda-4.4.0-3.6/envs/git-annex-test/bin/git'
ERROR
Exception ignored in: <function _Database.close at 0x7fb50841f9d8>
Traceback (most recent call last):
  File "/home/yoh/anaconda-4.4.0-3.6/envs/git-annex-test/lib/python3.7/dbm/dumb.py", line 284, in close
    self._commit()
  File "/home/yoh/anaconda-4.4.0-3.6/envs/git-annex-test/lib/python3.7/dbm/dumb.py", line 135, in _commit
    with self._io.open(self._dirfile, 'w', encoding="Latin-1") as f:
FileNotFoundError: [Errno 2] No such file or directory: '/home/yoh/.tmp/datalad_temp_22j7xv4a/.config/datalad/cookies.dir'

======================================================================
ERROR: datalad.distribution.tests.test_add.test_add_mimetypes
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/yoh/anaconda-4.4.0-3.6/envs/git-annex-test/lib/python3.7/site-packages/nose/case.py", line 197, in runTest
    self.test(*self.arg)
  File "/home/yoh/anaconda-4.4.0-3.6/envs/git-annex-test/lib/python3.7/site-packages/datalad/tests/utils.py", line 442, in newfunc
    return t(*(arg + (d,)), **kw)
  File "/home/yoh/anaconda-4.4.0-3.6/envs/git-annex-test/lib/python3.7/site-packages/datalad/distribution/tests/test_add.py", line 398, in test_add_mimetypes
    __not_tested__ = ds.add(['file.txt', 'empty'])
  File "/home/yoh/anaconda-4.4.0-3.6/envs/git-annex-test/lib/python3.7/site-packages/datalad/distribution/dataset.py", line 524, in apply_func
    return f(**kwargs)
  File "/home/yoh/anaconda-4.4.0-3.6/envs/git-annex-test/lib/python3.7/site-packages/datalad/interface/utils.py", line 491, in eval_func
    return return_func(generator_func)(*args, **kwargs)
  File "/home/yoh/anaconda-4.4.0-3.6/envs/git-annex-test/lib/python3.7/site-packages/datalad/interface/utils.py", line 479, in return_func
    results = list(results)
  File "/home/yoh/anaconda-4.4.0-3.6/envs/git-annex-test/lib/python3.7/site-packages/datalad/interface/utils.py", line 428, in generator_func
    result_renderer, result_xfm, _result_filter, **_kwargs):
  File "/home/yoh/anaconda-4.4.0-3.6/envs/git-annex-test/lib/python3.7/site-packages/datalad/interface/utils.py", line 521, in _process_results
    for res in results:
  File "/home/yoh/anaconda-4.4.0-3.6/envs/git-annex-test/lib/python3.7/site-packages/datalad/distribution/add.py", line 422, in __call__
    for a in added:
  File "/home/yoh/anaconda-4.4.0-3.6/envs/git-annex-test/lib/python3.7/site-packages/datalad/support/annexrepo.py", line 1602, in add_
    expect_stderr=True):
  File "/home/yoh/anaconda-4.4.0-3.6/envs/git-annex-test/lib/python3.7/site-packages/datalad/support/annexrepo.py", line 2504, in _run_annex_command_json
    raise e
  File "/home/yoh/anaconda-4.4.0-3.6/envs/git-annex-test/lib/python3.7/site-packages/datalad/support/annexrepo.py", line 2416, in _run_annex_command_json
    **kwargs)
  File "/home/yoh/anaconda-4.4.0-3.6/envs/git-annex-test/lib/python3.7/site-packages/datalad/support/annexrepo.py", line 1095, in _run_annex_command
    env=env, **kwargs)
  File "/home/yoh/anaconda-4.4.0-3.6/envs/git-annex-test/lib/python3.7/site-packages/datalad/support/gitrepo.py", line 1800, in _run_command_files_split
    *args, **kwargs)
  File "/home/yoh/anaconda-4.4.0-3.6/envs/git-annex-test/lib/python3.7/site-packages/datalad/cmd.py", line 683, in run
    cmd, env=self.get_git_environ_adjusted(env), *args, **kwargs)
  File "/home/yoh/anaconda-4.4.0-3.6/envs/git-annex-test/lib/python3.7/site-packages/datalad/cmd.py", line 542, in run
    raise CommandError(text_type(cmd), msg, status, out[0], out[1])
datalad.support.exceptions.CommandError: CommandError: command '['git', '-c', 'receive.autogc=0', '-c', 'gc.auto=0', 'annex', 'add', '--json', '--', '/home/yoh/.tmp/datalad_temp_tree_test_add_mimetypesj9jcge73/file.txt', '/home/yoh/.tmp/datalad_temp_tree_test_add_mimetypesj9jcge73/empty']' failed with exitcode 1
Failed to run ['git', '-c', 'receive.autogc=0', '-c', 'gc.auto=0', 'annex', 'add', '--json', '--', '/home/yoh/.tmp/datalad_temp_tree_test_add_mimetypesj9jcge73/file.txt', '/home/yoh/.tmp/datalad_temp_tree_test_add_mimetypesj9jcge73/empty'] under '/home/yoh/.tmp/datalad_temp_tree_test_add_mimetypesj9jcge73'. Exit code=1.

======================================================================
ERROR: datalad.distribution.tests.test_create.test_create_text_no_annex
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/yoh/anaconda-4.4.0-3.6/envs/git-annex-test/lib/python3.7/site-packages/nose/case.py", line 197, in runTest
    self.test(*self.arg)
  File "/home/yoh/anaconda-4.4.0-3.6/envs/git-annex-test/lib/python3.7/site-packages/datalad/tests/utils.py", line 615, in newfunc
    return t(*(arg + (filename,)), **kw)
  File "/home/yoh/anaconda-4.4.0-3.6/envs/git-annex-test/lib/python3.7/site-packages/datalad/distribution/tests/test_create.py", line 350, in test_create_text_no_annex
    ds.add(['t', 'b'])
  File "/home/yoh/anaconda-4.4.0-3.6/envs/git-annex-test/lib/python3.7/site-packages/datalad/distribution/dataset.py", line 524, in apply_func
    return f(**kwargs)
  File "/home/yoh/anaconda-4.4.0-3.6/envs/git-annex-test/lib/python3.7/site-packages/datalad/interface/utils.py", line 491, in eval_func
    return return_func(generator_func)(*args, **kwargs)
  File "/home/yoh/anaconda-4.4.0-3.6/envs/git-annex-test/lib/python3.7/site-packages/datalad/interface/utils.py", line 479, in return_func
    results = list(results)
  File "/home/yoh/anaconda-4.4.0-3.6/envs/git-annex-test/lib/python3.7/site-packages/datalad/interface/utils.py", line 428, in generator_func
    result_renderer, result_xfm, _result_filter, **_kwargs):
  File "/home/yoh/anaconda-4.4.0-3.6/envs/git-annex-test/lib/python3.7/site-packages/datalad/interface/utils.py", line 521, in _process_results
    for res in results:
  File "/home/yoh/anaconda-4.4.0-3.6/envs/git-annex-test/lib/python3.7/site-packages/datalad/distribution/add.py", line 422, in __call__
    for a in added:
  File "/home/yoh/anaconda-4.4.0-3.6/envs/git-annex-test/lib/python3.7/site-packages/datalad/support/annexrepo.py", line 1602, in add_
    expect_stderr=True):
  File "/home/yoh/anaconda-4.4.0-3.6/envs/git-annex-test/lib/python3.7/site-packages/datalad/support/annexrepo.py", line 2504, in _run_annex_command_json
    raise e
  File "/home/yoh/anaconda-4.4.0-3.6/envs/git-annex-test/lib/python3.7/site-packages/datalad/support/annexrepo.py", line 2416, in _run_annex_command_json
    **kwargs)
  File "/home/yoh/anaconda-4.4.0-3.6/envs/git-annex-test/lib/python3.7/site-packages/datalad/support/annexrepo.py", line 1095, in _run_annex_command
    env=env, **kwargs)
  File "/home/yoh/anaconda-4.4.0-3.6/envs/git-annex-test/lib/python3.7/site-packages/datalad/support/gitrepo.py", line 1800, in _run_command_files_split
    *args, **kwargs)
  File "/home/yoh/anaconda-4.4.0-3.6/envs/git-annex-test/lib/python3.7/site-packages/datalad/cmd.py", line 683, in run
    cmd, env=self.get_git_environ_adjusted(env), *args, **kwargs)
  File "/home/yoh/anaconda-4.4.0-3.6/envs/git-annex-test/lib/python3.7/site-packages/datalad/cmd.py", line 542, in run
    raise CommandError(text_type(cmd), msg, status, out[0], out[1])
datalad.support.exceptions.CommandError: CommandError: command '['git', '-c', 'receive.autogc=0', '-c', 'gc.auto=0', 'annex', 'add', '--json', '--', '/home/yoh/.tmp/datalad_temp_test_create_text_no_annex97xxwyu0/t', '/home/yoh/.tmp/datalad_temp_test_create_text_no_annex97xxwyu0/b']' failed with exitcode 1
Failed to run ['git', '-c', 'receive.autogc=0', '-c', 'gc.auto=0', 'annex', 'add', '--json', '--', '/home/yoh/.tmp/datalad_temp_test_create_text_no_annex97xxwyu0/t', '/home/yoh/.tmp/datalad_temp_test_create_text_no_annex97xxwyu0/b'] under '/home/yoh/.tmp/datalad_temp_test_create_text_no_annex97xxwyu0'. Exit code=1.

======================================================================
ERROR: test suite for <module 'datalad' from '/home/yoh/anaconda-4.4.0-3.6/envs/git-annex-test/lib/python3.7/site-packages/datalad/__init__.py'>
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/yoh/anaconda-4.4.0-3.6/envs/git-annex-test/lib/python3.7/site-packages/nose/suite.py", line 228, in run
    self.tearDown()
  File "/home/yoh/anaconda-4.4.0-3.6/envs/git-annex-test/lib/python3.7/site-packages/nose/suite.py", line 351, in tearDown
    self.teardownContext(ancestor)
  File "/home/yoh/anaconda-4.4.0-3.6/envs/git-annex-test/lib/python3.7/site-packages/nose/suite.py", line 367, in teardownContext
    try_run(context, names)
  File "/home/yoh/anaconda-4.4.0-3.6/envs/git-annex-test/lib/python3.7/site-packages/nose/util.py", line 471, in try_run
    return func()
  File "/home/yoh/anaconda-4.4.0-3.6/envs/git-annex-test/lib/python3.7/site-packages/datalad/__init__.py", line 216, in teardown_package
    cookies_db.close()
  File "/home/yoh/anaconda-4.4.0-3.6/envs/git-annex-test/lib/python3.7/site-packages/datalad/support/cookies.py", line 62, in close
    self._cookies_db.close()
  File "/home/yoh/anaconda-4.4.0-3.6/envs/git-annex-test/lib/python3.7/shelve.py", line 144, in close
    self.sync()
  File "/home/yoh/anaconda-4.4.0-3.6/envs/git-annex-test/lib/python3.7/shelve.py", line 168, in sync
    self[key] = entry
  File "/home/yoh/anaconda-4.4.0-3.6/envs/git-annex-test/lib/python3.7/shelve.py", line 125, in __setitem__
    self.dict[key.encode(self.keyencoding)] = f.getvalue()
  File "/home/yoh/anaconda-4.4.0-3.6/envs/git-annex-test/lib/python3.7/dbm/dumb.py", line 216, in __setitem__
    self._index[key] = self._setval(pos, val)
  File "/home/yoh/anaconda-4.4.0-3.6/envs/git-annex-test/lib/python3.7/dbm/dumb.py", line 178, in _setval
    with _io.open(self._datfile, 'rb+') as f:
FileNotFoundError: [Errno 2] No such file or directory: '/home/yoh/.tmp/datalad_temp_22j7xv4a/.config/datalad/cookies.dat'

----------------------------------------------------------------------
Ran 889 tests in 913.608s

FAILED (SKIP=82, errors=3)
python -m nose -s -v datalad  531.20s user 383.20s system 99% cpu 15:14.95 total

```

**Comment by notestaff** [comment]
@yarikoptic the new git-annex conda recipe does not enable magicmime compile-time flag like the old one did, could that be related?  I can try re-enabling it.

**Comment by yarikoptic** [comment]
that would explain two out of three errors ;)

**Comment by notestaff** [comment]
https://github.com/conda-forge/git-annex-feedstock/pull/38 seems to fix the datalad test in my local docker-based testing.  circleci is having issues so it might be some time before the fix makes it to conda-forge channel.

**Comment by yarikoptic** [comment]
Thank you @notestaff! 
Are you sure you can't join us in Montreal in a week? ;-)

**Comment by yarikoptic** [comment]
life is different now -- may be they are gone may be not... we will see ;)
