### ISSUE TITLE
AttributeError: 'NoneType' object has no attribute 'stat' in AnnexRepo.__del__

### ISSUE THREAD

**Issue by yarikoptic** [datalad/datalad#3269]
When exporting to figshare, at the end got
```
[Published archive https://ndownloader.figshare.com/files/14680097]
Exception ignored in: <function AnnexRepo.__del__ at 0x7fdbaa3da598>
Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/datalad/support/annexrepo.py", line 365, in __del__
  File "/usr/lib/python3/dist-packages/datalad/support/gitrepo.py", line 878, in __del__
  File "/usr/lib/python3.7/genericpath.py", line 19, in exists
AttributeError: 'NoneType' object has no attribute 'stat'
```
datalad 0.11.3

**Comment by yarikoptic** [comment]
uff... here it is about `os.stat` so we got there because it was already destroyed before even our class's `._repo` was annihilated.  Truly the order of destruction upon exit in python3 is unpredictable!

**Comment by yarikoptic** [comment]
I believe it was addressed by https://github.com/datalad/datalad/pull/3527
