### ISSUE TITLE
appveyor fails to annex init for v6 in test_add_recursive

### ISSUE THREAD

**Issue by yarikoptic** [datalad/datalad#3287]
Fresh failure on appveyor https://ci.appveyor.com/project/mih/datalad/builds/23566971/job/k617r2yxoprmg547, smells like just some instability in annex since none other test fails on this basic operation?

```
======================================================================
ERROR: datalad.core.local.tests.test_save.test_add_recursive
----------------------------------------------------------------------
Traceback (most recent call last):
  File "C:\Miniconda35\envs\test-environment\lib\site-packages\nose\case.py", line 198, in runTest
    self.test(*self.arg)
  File "C:\Miniconda35\envs\test-environment\lib\site-packages\datalad\tests\utils.py", line 607, in newfunc
    return t(*(arg + (filename,)), **kw)
  File "C:\Miniconda35\envs\test-environment\lib\contextlib.py", line 77, in __exit__
    self.gen.throw(type, value, traceback)
  File "C:\Miniconda35\envs\test-environment\lib\site-packages\datalad\utils.py", line 1598, in make_tempfile
    yield filename
  File "C:\Miniconda35\envs\test-environment\lib\site-packages\datalad\tests\utils.py", line 607, in newfunc
    return t(*(arg + (filename,)), **kw)
  File "C:\Miniconda35\envs\test-environment\lib\site-packages\datalad\core\local\tests\test_save.py", line 486, in test_add_recursive
    parent = Dataset(path).rev_create()
  File "C:\Miniconda35\envs\test-environment\lib\site-packages\datalad\distribution\dataset.py", line 553, in apply_func
    return f(**kwargs)
  File "C:\Miniconda35\envs\test-environment\lib\site-packages\datalad\interface\utils.py", line 492, in eval_func
    return return_func(generator_func)(*args, **kwargs)
  File "C:\Miniconda35\envs\test-environment\lib\site-packages\datalad\interface\utils.py", line 480, in return_func
    results = list(results)
  File "C:\Miniconda35\envs\test-environment\lib\site-packages\datalad\interface\utils.py", line 429, in generator_func
    result_renderer, result_xfm, _result_filter, **_kwargs):
  File "C:\Miniconda35\envs\test-environment\lib\site-packages\datalad\interface\utils.py", line 522, in _process_results
    for res in results:
  File "C:\Miniconda35\envs\test-environment\lib\site-packages\datalad\core\local\create.py", line 313, in __call__
    fake_dates=fake_dates
  File "C:\Miniconda35\envs\test-environment\lib\site-packages\datalad\support\repo.py", line 146, in __call__
    instance = type.__call__(cls, *new_args, **new_kwargs)
  File "C:\Miniconda35\envs\test-environment\lib\site-packages\datalad\support\annexrepo.py", line 256, in __init__
    self._init(version=version, description=description)
  File "C:\Miniconda35\envs\test-environment\lib\site-packages\datalad\support\annexrepo.py", line 1157, in _init
    annex_options=opts)
  File "C:\Miniconda35\envs\test-environment\lib\site-packages\datalad\support\annexrepo.py", line 981, in _run_annex_command
    env=env, **kwargs)
  File "C:\Miniconda35\envs\test-environment\lib\site-packages\datalad\support\gitrepo.py", line 1866, in _run_command_files_split
    *args, **kwargs)
  File "C:\Miniconda35\envs\test-environment\lib\site-packages\datalad\cmd.py", line 691, in run
    cmd, env=self.get_git_environ_adjusted(env), *args, **kwargs)
  File "C:\Miniconda35\envs\test-environment\lib\site-packages\datalad\cmd.py", line 550, in run
    raise CommandError(text_type(cmd), msg, status, out[0], out[1])
datalad.support.exceptions.CommandError: CommandError: command '['git', '-c', 'receive.autogc=0', '-c', 'gc.auto=0', 'annex', 'init', '--version', '6']' failed with exitcode 1
Failed to run ['git', '-c', 'receive.autogc=0', '-c', 'gc.auto=0', 'annex', 'init', '--version', '6'] under 'C:\\Users\\appveyor\\AppData\\Local\\Temp\\1\\datalad_temp_y9ho49u4'. Exit code=1.
```

**Comment by kyleam** [comment]
FWIW the latest appveyor builds passed: https://ci.appveyor.com/project/mih/datalad/builds/23574826

**Comment by kyleam** [comment]
I don't recall seeing this in any recent builds.  @yarikoptic, safe to close this (at least until we see it resurface)?

**Comment by yarikoptic** [comment]
ok, thanks!
