### ISSUE TITLE
older git (2.11.0) ls-files does not list cwd which belongs subdataset

### ISSUE THREAD

**Issue by yarikoptic** [datalad/datalad#3295]
While testing git-annex build on jessie (for maximum portability across kernels) using "stack" distribution of ghc and libraries, ran into our safe-guard test failing:
```
======================================================================
FAIL: datalad.distribution.tests.test_dataset.test_is_installed
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/usr/lib/python2.7/dist-packages/nose/case.py", line 197, in runTest
    self.test(*self.arg)
  File "/home/yoh/proj/datalad/datalad/datalad/tests/utils.py", line 791, in newfunc
    t(*(arg + (uri,)), **kw)
  File "/home/yoh/proj/datalad/datalad/datalad/tests/utils.py", line 615, in newfunc
    return t(*(arg + (filename,)), **kw)
  File "/home/yoh/proj/datalad/datalad/datalad/distribution/tests/test_dataset.py", line 111, in test_is_installed
    subds.create()
AssertionError: PathKnownToRepositoryError not raised
```

which is due to
```
(git-annex)hopa:~/.tmp/datalad_temp_test_is_installedd9cRgg[master]subm 1
$> /usr/lib/git-annex.linux/git ls-files       
$> /usr/lib/git-annex.linux/git --version
git version 2.11.0
````
as compared to
```shell
$> git ls-files                                
./
$> git --version
git version 2.20.1
```
so it seems we need to check also for minimal git version compatibility :-/  

master version (0.12.0rc2-128-gf9ff64ea) seems to be ok on that test, but now I will run the full battery to see if any other effect

**Comment by yarikoptic** [comment]
FTR - that elderly git doesn't behave well if ran with `.` 

```shell
$> /usr/lib/git-annex.linux/git ls-files .
git: pathspec.c:317: prefix_pathspec: Assertion `item->nowildcard_len <= item->len && item->prefix <= item->len' failed.
[1]    25462 abort      /usr/lib/git-annex.linux/git ls-files .

$> git ls-files .      
./
```
so can't be used as a workaround :/   the only way seems to be to check from above
```shell
$> eval "( builtin cd ..; git ls-files $PWD; )"
datasets.datalad.org
```

but the question still remains - either I should build on jessie with such an outdated git... or should I backport git as well for the sake of peace of mind...
