### ISSUE TITLE
Tests error with upstream GitPython

### ISSUE THREAD

**Issue by kyleam** [datalad/datalad#3395]
On our Travis cron build for 0.11.x, the upstream GitPython run [fails with an import error][0].  Locally I've bisected this to GitPython's ce21f63 (Fix setup.py and use of requirements files), but I haven't dug any deeper yet.

```
======================================================================
ERROR: test suite for <module 'datalad' from '/home/travis/virtualenv/python3.5.6/lib/python3.5/site-packages/datalad/__init__.py'>
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/travis/virtualenv/python3.5.6/lib/python3.5/site-packages/git/__init__.py", line 25, in _init_externals
    import gitdb
ImportError: No module named 'gitdb'
During handling of the above exception, another exception occurred:
Traceback (most recent call last):
  File "/home/travis/virtualenv/python3.5.6/lib/python3.5/site-packages/nose/suite.py", line 210, in run
    self.setUp()
  File "/home/travis/virtualenv/python3.5.6/lib/python3.5/site-packages/nose/suite.py", line 293, in setUp
    self.setupContext(ancestor)
  File "/home/travis/virtualenv/python3.5.6/lib/python3.5/site-packages/nose/suite.py", line 316, in setupContext
    try_run(context, names)
  File "/home/travis/virtualenv/python3.5.6/lib/python3.5/site-packages/nose/util.py", line 471, in try_run
    return func()
  File "/home/travis/virtualenv/python3.5.6/lib/python3.5/site-packages/datalad/__init__.py", line 130, in setup_package
    from datalad.support.gitrepo import check_git_configured
  File "/home/travis/virtualenv/python3.5.6/lib/python3.5/site-packages/datalad/support/gitrepo.py", line 43, in <module>
    import git as gitpy
  File "/home/travis/virtualenv/python3.5.6/lib/python3.5/site-packages/git/__init__.py", line 33, in <module>
    _init_externals()
  File "/home/travis/virtualenv/python3.5.6/lib/python3.5/site-packages/git/__init__.py", line 27, in _init_externals
    raise ImportError("'gitdb' could not be found in your PYTHONPATH")
ImportError: 'gitdb' could not be found in your PYTHONPATH
```

[0]: https://travis-ci.org/datalad/datalad/jobs/529418036

**Comment by yarikoptic** [comment]
interesting! 
<details>
<summary>It is indeed broken:</summary>
```shell
(git)hopa:~deb/python-git[upstream-master]git
$> virtualenv venv-install-gitdb                                                              
Running virtualenv with interpreter /usr/bin/python2
New python executable in /home/yoh/deb/gits/python-git/venv-install-gitdb/bin/python2
Also creating executable in /home/yoh/deb/gits/python-git/venv-install-gitdb/bin/python
Installing setuptools, pkg_resources, pip, wheel...done.
1 10860.....................................:Tue 07 May 2019 05:09:11 PM EDT:.
(git)hopa:~deb/python-git[upstream-master]git
$> venv-install-gitdb/bin/pip install .
DEPRECATION: Python 2.7 will reach the end of its life on January 1st, 2020. Please upgrade your Python as Python 2.7 won't be maintained after that date. A future version of pip will drop support for Python 2.7.
Processing /home/yoh/deb/gits/python-git
Building wheels for collected packages: GitPython
  Building wheel for GitPython (setup.py) ... done
  Stored in directory: /home/yoh/.cache/pip/wheels/9b/ce/2b/d5e8c69f06873f6b4e334ea1ad3704117175b738f8d3d80976
Successfully built GitPython
Installing collected packages: GitPython
Successfully installed GitPython-2.1.11
1 10861.....................................:Tue 07 May 2019 05:09:20 PM EDT:.
(git)hopa:~deb/python-git[upstream-master]git
$> venv-install-gitdb/bin/python -c 'import gitdb'             
Traceback (most recent call last):
  File "<string>", line 1, in <module>
ImportError: No module named gitdb
1 10862 ->1.....................................:Tue 07 May 2019 05:09:31 PM EDT:.
(git)hopa:~deb/python-git[upstream-master]git
$> venv-install-gitdb/bin/python -c 'import gitdb2'
Traceback (most recent call last):
  File "<string>", line 1, in <module>
ImportError: No module named gitdb2
1 10863 ->1.....................................:Tue 07 May 2019 05:09:35 PM EDT:.
(git)hopa:~deb/python-git[upstream-master]git
$> venv-install-gitdb/bin/python -c 'import git'   
Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "git/__init__.py", line 33, in <module>
    _init_externals()
  File "git/__init__.py", line 27, in _init_externals
    raise ImportError("'gitdb' could not be found in your PYTHONPATH")
ImportError: 'gitdb' could not be found in your PYTHONPATH
```
</details>

But I am bit unclear 
- I added cron job run for 0.11.x only recently
- but master cron job of the same kind seems passed last time 4 days ago just fine
- no relevant recent changes to GitPython itself 

so not clear what could have possibly "triggered" cron job failure NOW

**Comment by yarikoptic** [comment]
I think I got it, will submit a PR to fix it up

**Comment by kyleam** [comment]
>     * but master cron job of the same kind seems passed last time 4 days ago just fine

But four days ago would have been the 3rd, and the GitPython commit I pointed to has a commit date on May 5th.

**Comment by yarikoptic** [comment]
> > ```
> > * but master cron job of the same kind seems passed last time 4 days ago just fine
> > ```
> 
> But four days ago would have been the 3rd, and the GitPython commit I pointed to has a commit date on May 5th.

on 5th of May there was 11fd713f77bb0bc817ff3c17215fd7961c025d7e .  the [ce21f6 you mentioned](https://github.com/gitpython-developers/GitPython/commit/ce21f63f7acba9b82cea22790c773e539a39c158) was in January:
```
$> git show ce21f63 | head
commit ce21f63f7acba9b82cea22790c773e539a39c158
Author: James E. King III <jking@apache.org>
Date:   Tue Jan 15 16:16:33 2019 -0500

    Fix setup.py and use of requirements files.

diff --git a/.appveyor.yml b/.appveyor.yml
index 8eeca50..2df96e4 100644
--- a/.appveyor.yml
```

or am I missing smth?

**Comment by yarikoptic** [comment]
oh
```
Author: James E. King III <jking@apache.org>  2019-01-15 16:16:33
Committer: Sebastian Thiel <byronimo@gmail.com>  2019-05-05 03:52:53
```
so -- the crime was done in January but it was adopted on May 5th... got it!

**Comment by kyleam** [comment]
This was fixed by the linked PR on GitPython's side.
