### ISSUE TITLE
-m datalad  fails with cryptic errors (list has no get, Compressor 'fileobj_factory' attribute should implement)

### ISSUE THREAD

**Issue by yarikoptic** [datalad/datalad#3428]
```shell
(git-annex)hopa:~/proj/experiments/localizer[master]
$> python -m datalad code/cv_clf_glm_main.py --inputfile derivatives/ds_groupspace/avmovie_groupdataset_transposed.hdf5 --analysis avmovie --eventdir 'derivatives/stimuli/researchcut/downsampled_event_files/' --bilateral --output derivatives/groupspace_analysis/avmovie/GNB/full/FFA-BRAIN --annotation sourcedata/annotations/researchcut/locations.tsv --roipair FFA brain --classifier gnb --dataset full -n True --plot_time_series
[INFO   ] Running code of code/cv_clf_glm_main.py 
/home/yoh/proj/datalad/datalad/venvs/dev/local/lib/python2.7/site-packages/nibabel/testing/__init__.py:21: DeprecationWarning: Importing from numpy.testing.decorators is deprecated since numpy 1.15.0, import from numpy.testing instead.
  from numpy.testing.decorators import skipif
[INFO   ] AutomagicIO: retrieving file content of /home/yoh/proj/experiments/localizer 
[WARNING] Failed proxying open with ('/home/yoh/proj/experiments/localizer',), {}: 'list' object has no attribute 'get' [auto.py:_dataset_auto_get:289] 
[INFO   ] AutomagicIO: retrieving file content of /home/yoh/proj/experiments/localizer 
[WARNING] Failed proxying open with ('/home/yoh/proj/experiments/localizer',), {}: 'list' object has no attribute 'get' [auto.py:_dataset_auto_get:289] 
[INFO   ] AutomagicIO: retrieving file content of /home/yoh/proj/experiments/localizer 
[WARNING] Failed proxying open with ('/home/yoh/proj/experiments/localizer',), {}: 'list' object has no attribute 'get' [auto.py:_dataset_auto_get:289] 
[INFO   ] AutomagicIO: retrieving file content of /home/yoh/proj/experiments/localizer 
[WARNING] Failed proxying open with ('/home/yoh/proj/experiments/localizer',), {}: 'list' object has no attribute 'get' [auto.py:_dataset_auto_get:289] 
[INFO   ] AutomagicIO: retrieving file content of /home/yoh/proj/experiments/localizer 
[WARNING] Failed proxying open with ('/home/yoh/proj/experiments/localizer',), {}: 'list' object has no attribute 'get' [auto.py:_dataset_auto_get:289] 
[INFO   ] AutomagicIO: retrieving file content of /home/yoh/proj/experiments/localizer 
[WARNING] Failed proxying open with ('/home/yoh/proj/experiments/localizer',), {}: 'list' object has no attribute 'get' [auto.py:_dataset_auto_get:289] 
[INFO   ] AutomagicIO: retrieving file content of /home/yoh/proj/experiments/localizer 
[WARNING] Failed proxying open with ('/home/yoh/proj/experiments/localizer',), {}: 'list' object has no attribute 'get' [auto.py:_dataset_auto_get:289] 
[INFO   ] AutomagicIO: retrieving file content of /home/yoh/proj/experiments/localizer 
[WARNING] Failed proxying open with ('/home/yoh/proj/experiments/localizer',), {}: 'list' object has no attribute 'get' [auto.py:_dataset_auto_get:289] 
[INFO   ] AutomagicIO: retrieving file content of /home/yoh/proj/experiments/localizer 
[WARNING] Failed proxying open with ('/home/yoh/proj/experiments/localizer',), {}: 'list' object has no attribute 'get' [auto.py:_dataset_auto_get:289] 
[INFO   ] AutomagicIO: retrieving file content of /home/yoh/proj/experiments/localizer 
[WARNING] Failed proxying open with ('/home/yoh/proj/experiments/localizer',), {}: 'list' object has no attribute 'get' [auto.py:_dataset_auto_get:289] 
Traceback (most recent call last):
  File "/usr/lib/python2.7/runpy.py", line 174, in _run_module_as_main
    "__main__", fname, loader, pkg_name)
  File "/usr/lib/python2.7/runpy.py", line 72, in _run_code
    exec code in run_globals
  File "/home/yoh/proj/datalad/datalad/datalad/__main__.py", line 102, in <module>
    main()
  File "/home/yoh/proj/datalad/datalad/datalad/__main__.py", line 93, in main
    runctx(code, globs, globs)
  File "/home/yoh/proj/datalad/datalad/datalad/__main__.py", line 41, in runctx
    exec(cmd, globals, locals)
  File "code/cv_clf_glm_main.py", line 3, in <module>
    import mvpa2.suite as mv
  File "/usr/lib/python2.7/dist-packages/mvpa2/suite.py", line 88, in <module>
    if externals.exists('skl'):
  File "/usr/lib/python2.7/dist-packages/mvpa2/base/externals.py", line 699, in exists
    exec _KNOWN[dep]
  File "<string>", line 1, in <module>
  File "/usr/lib/python2.7/dist-packages/mvpa2/base/externals.py", line 241, in __assign_skl_version
    import sklearn as skl
  File "/usr/lib/python2.7/dist-packages/sklearn/__init__.py", line 64, in <module>
    from .base import clone
  File "/usr/lib/python2.7/dist-packages/sklearn/base.py", line 13, in <module>
    from .utils.fixes import signature
  File "/usr/lib/python2.7/dist-packages/sklearn/utils/__init__.py", line 14, in <module>
    from . import _joblib
  File "/usr/lib/python2.7/dist-packages/sklearn/utils/_joblib.py", line 22, in <module>
    from ..externals import joblib
  File "/usr/lib/python2.7/dist-packages/sklearn/externals/joblib.py", line 16, in <module>
    locals().update(import_non_local('joblib').__dict__)
  File "/usr/lib/python2.7/dist-packages/sklearn/externals/joblib.py", line 9, in import_non_local
    module = imp.load_module(custom_name, f, pathname, desc)
  File "/usr/lib/python2.7/dist-packages/joblib/__init__.py", line 112, in <module>
    from .memory import Memory, MemorizedResult, register_store_backend
  File "/usr/lib/python2.7/dist-packages/joblib/memory.py", line 31, in <module>
    from ._store_backends import StoreBackendBase, FileSystemStoreBackend
  File "/usr/lib/python2.7/dist-packages/joblib/_store_backends.py", line 18, in <module>
    from . import numpy_pickle
  File "/usr/lib/python2.7/dist-packages/joblib/numpy_pickle.py", line 38, in <module>
    register_compressor('lzma', LZMACompressorWrapper())
  File "/usr/lib/python2.7/dist-packages/joblib/compressor.py", line 75, in register_compressor
    .format(compressor.fileobj_factory))
ValueError: Compressor 'fileobj_factory' attribute should implement the file object interface, '<bound method AutomagicIO._proxy_lzma_LZMAFile of <datalad.auto.AutomagicIO object at 0x7f23835fcfd0>>' given.
python -m datalad code/cv_clf_glm_main.py --inputfile  --analysis avmovie      10.29s user 5.48s system 75% cpu 20.847 total
```

**Comment by yarikoptic** [comment]
since we are no longer using python2 and pymvpa is not yet python3, case is unreproducible, thus closed! ;)
