### ISSUE TITLE
testing against datalad-neuroimaging started to fail

### ISSUE THREAD

**Issue by yarikoptic** [datalad/datalad#3432]
either due to datalad-neuroimaging release or some changes here (happens for PRs against 0.11.x) and I failed so far to reproduce locally (python2)
```
38.26s$ http_proxy= PATH=$PWD/../tools/coverage-bin:$PATH $NOSE_WRAPPER `which nosetests` $NOSE_OPTS -A "$NOSE_SELECTION_OP($NOSE_SELECTION)" --with-doctest --with-cov --cover-package datalad --logging-level=INFO $TESTS_TO_PERFORM
.........SS.E.S.
======================================================================
ERROR: datalad_neuroimaging.tests.test_procedure.test_bids_procedure
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/travis/virtualenv/python3.5.6/lib/python3.5/site-packages/nose/case.py", line 198, in runTest
    self.test(*self.arg)
  File "/home/travis/virtualenv/python3.5.6/lib/python3.5/site-packages/datalad/tests/utils.py", line 615, in newfunc
    return t(*(arg + (filename,)), **kw)
  File "/home/travis/virtualenv/python3.5.6/lib/python3.5/site-packages/datalad_neuroimaging/tests/test_procedure.py", line 13, in test_bids_procedure
    ds.run_procedure(['cfg_bids'])
  File "/home/travis/virtualenv/python3.5.6/lib/python3.5/site-packages/datalad/distribution/dataset.py", line 526, in apply_func
    return f(**kwargs)
  File "/home/travis/virtualenv/python3.5.6/lib/python3.5/site-packages/datalad/interface/utils.py", line 492, in eval_func
    return return_func(generator_func)(*args, **kwargs)
  File "/home/travis/virtualenv/python3.5.6/lib/python3.5/site-packages/datalad/interface/utils.py", line 480, in return_func
    results = list(results)
  File "/home/travis/virtualenv/python3.5.6/lib/python3.5/site-packages/datalad/interface/utils.py", line 468, in generator_func
    msg="Command did not complete successfully")
datalad.support.exceptions.IncompleteResultsError: Command did not complete successfully [{'action': 'run_procedure', 'status': 'impossible', 'refds': '/tmp/datalad_temp_test_bids_procedure0ucvyzgv', 'path': 'cfg_bids', 'message': "Cannot find procedure with name 'cfg_bids'"}]
```

**Comment by yarikoptic** [comment]
@mih @bpoldrack - any immediate ideas?

**Comment by mih** [comment]
Didnt look i to it, but sounds like pip install from github that doesn't install package data, hence no procedure. Would need pip install -e, if that is the reason.

**Comment by yarikoptic** [comment]
we just do [`pip install datalad-neuroimaging`](https://github.com/datalad/datalad/blob/master/.travis.yml#L289) so probably not the "install from github" issue

**Comment by yarikoptic** [comment]
I think it will be addressed in https://github.com/datalad/datalad-neuroimaging/pull/68

**Comment by yarikoptic** [comment]
neuroimaging 0.2.2 uploaded to pypi and sample rerun succeeded: https://travis-ci.org/datalad/datalad/builds/534685969?utm_source=github_status&utm_medium=notification
