### ISSUE TITLE
New AppVeyor error

### ISSUE THREAD

**Issue by kyleam** [datalad/datalad#3482]
The run for gh-3481 (which only touches .travis.yml) shows a consistent error in both builds:

```
======================================================================
ERROR: datalad.core.local.tests.test_run.test_py2_unicode_command
----------------------------------------------------------------------
Traceback (most recent call last):
  File "C:\Miniconda35\envs\test-environment\lib\site-packages\nose\case.py", line 198, in runTest
    self.test(*self.arg)
  File "C:\Miniconda35\envs\test-environment\lib\site-packages\datalad\tests\utils.py", line 607, in newfunc
    return t(*(arg + (filename,)), **kw)
  File "C:\Miniconda35\envs\test-environment\lib\contextlib.py", line 77, in __exit__
    self.gen.throw(type, value, traceback)
  File "C:\Miniconda35\envs\test-environment\lib\site-packages\datalad\utils.py", line 1659, in make_tempfile
    yield filename
  File "C:\Miniconda35\envs\test-environment\lib\site-packages\datalad\tests\utils.py", line 607, in newfunc
    return t(*(arg + (filename,)), **kw)
  File "C:\Miniconda35\envs\test-environment\lib\site-packages\datalad\core\local\tests\test_run.py", line 146, in test_py2_unicode_command
    ds.run(cmd_str)
  File "C:\Miniconda35\envs\test-environment\lib\site-packages\datalad\distribution\dataset.py", line 525, in apply_func
    return f(**kwargs)
  File "C:\Miniconda35\envs\test-environment\lib\site-packages\datalad\interface\utils.py", line 491, in eval_func
    return return_func(generator_func)(*args, **kwargs)
  File "C:\Miniconda35\envs\test-environment\lib\site-packages\datalad\interface\utils.py", line 479, in return_func
    results = list(results)
  File "C:\Miniconda35\envs\test-environment\lib\site-packages\datalad\interface\utils.py", line 428, in generator_func
    result_renderer, result_xfm, _result_filter, **_kwargs):
  File "C:\Miniconda35\envs\test-environment\lib\site-packages\datalad\interface\utils.py", line 520, in _process_results
    for res in results:
  File "C:\Miniconda35\envs\test-environment\lib\site-packages\datalad\core\local\run.py", line 202, in __call__
    sidecar=sidecar):
  File "C:\Miniconda35\envs\test-environment\lib\site-packages\datalad\core\local\run.py", line 614, in run_command
    for r in saver(dataset, outputs_to_save, msg):
  File "C:\Miniconda35\envs\test-environment\lib\site-packages\datalad\interface\utils.py", line 467, in generator_func
    msg="Command did not complete successfully")
datalad.support.exceptions.IncompleteResultsError: Command did not complete successfully [{'refds': 'C:\\Users\\appveyor\\AppData\\Local\\Temp\\1\\datalad_temp_7mz5ehec', 'action': 'add', 'type': 'file', 'key': None, 'path': 'C:\\Users\\appveyor\\AppData\\Local\\Temp\\1\\datalad_temp_7mz5ehec\\b\u03b20.dat', 'status': 'error'}]
```

<https://ci.appveyor.com/project/mih/datalad/builds/25400704/job/658y98ast126g40k#L1044>

The AppVeyor was passing recently ([for example][0]), so it might be worth trying to spot differences in those environments.

[0]: https://ci.appveyor.com/project/mih/datalad/builds/25236248/job/dxxyia0dtukt0cn2

**Comment by kyleam** [comment]
Comparing the logs between a [failing] build and a [passing] one, I didn't spot any suspicious differences in the environment.  That made me think it was probably a commit on our end.  Of the commits since the passing build, none look likely to be culprits, but 203aa652a (RF: remove  receive.autogc=0 and gc.auto=0 options to git calls, 2019-05-24) seems most likely of the unlikely.  And an error in test_run.test_py2_unicode_command wouldn't be caught in that PR's appveyor build because it was submitted against 0.11.x, where that test doesn't run on appveyor.

Reverting 203aa652a appears to [resolve] the error.  Of course, that doesn't explain *why* this test errors on appveyor when git's automatic gc is enabled.

[failing]: https://ci.appveyor.com/project/mih/datalad/builds/25400704/job/658y98ast126g40k#L1044
[passing]: https://ci.appveyor.com/project/mih/datalad/builds/25236248/job/dxxyia0dtukt0cn2
[resolve]: https://ci.appveyor.com/project/mih/datalad/builds/25418895/job/wx9mtcu4sre5dfjc#L876

**Comment by kyleam** [comment]
I'd rather not revert 203aa65 in order to fix one test on appveyor that errors for unknown reason.  My current plan is to make test_run.test_py2_unicode_command disable auto-gc via the test repos .git/config when running on appveyor.

**Comment by yarikoptic** [comment]
if only we could see the actual stderr from running that command - it might have given us a hint on what is going on

**Comment by kyleam** [comment]
> if only we could see the actual stderr from running that command - it might have given us a hint on what is going on

The output for that `ds.run()` isn't swallowed, so if any stderr is produced, it should be there.  The IncompleteResultsError is coming from the save call.
