### ISSUE TITLE
confusing crash/error upon `datalad create -d .`

### ISSUE THREAD

**Issue by yarikoptic** [datalad/datalad#3484]
I thought it should be legit invocation but I guess not
```shell
.../analyses/2nd-level$ datalad create -d .
[ERROR  ] '.' does not start with '..' [pathlib.py:relative_to:864] (ValueError)
.../analyses/2nd-level$ datalad --version
datalad 0.12.0rc4.dev122
```
I will try to reproduce it in minimalized env later on

**Comment by kyleam** [comment]
FWIW I don't see this error on master (9dce81cb4):

```sh
#!/bin/sh

set -eux

cd $(mktemp -dt dl-XXXXXXX)
datalad --version
datalad create -d .
```

```
+ mktemp -dt dl-XXXXXXX
+ cd /tmp/dl-elCO8Cu
+ datalad --version
datalad 0.12.0rc4.dev122
+ datalad create -d .
[INFO   ] Creating a new annex repo at /tmp/dl-elCO8Cu 
create(ok): . (dataset)
```

**Comment by yarikoptic** [comment]
Here is a bit more info
```shell
...WM-R03/analyses/test$ datalad create -d .
[ERROR  ] '.' does not start with '..' [pathlib.py:relative_to:864] (ValueError) 

.../WM-R03/analyses/test$ datalad --dbg create -d .
Traceback (most recent call last):
  File ".../WM-R03/venvs/master/bin/datalad", line 8, in <module>
    main()
  File ".../datalad-master/datalad/cmdline/main.py", line 500, in main
    ret = cmdlineargs.func(cmdlineargs)
  File ".../datalad-master/datalad/interface/base.py", line 645, in call_from_parser
    ret = list(ret)
  File ".../datalad-master/datalad/interface/utils.py", line 428, in generator_func
    result_renderer, result_xfm, _result_filter, **_kwargs):
  File ".../datalad-master/datalad/interface/utils.py", line 520, in _process_results
    for res in results:
  File ".../datalad-master/datalad/core/local/create.py", line 245, in __call__
    paths=[check_path.relative_to(parentds_path)])
  File "/usr/lib/python3.5/pathlib.py", line 864, in relative_to
    .format(str(self), str(formatted)))
ValueError: '.' does not start with '..'

> /usr/lib/python3.5/pathlib.py(864)relative_to()
-> .format(str(self), str(formatted)))
(Pdb) p self
PosixPath('.')
(Pdb) p formatted
'..'

(Pdb) p parentds_path
PosixPath('..')
(Pdb) p check_path
PosixPath('.')
(Pdb) l
240                 # uninstalled/added subdatasets too
241                 check_path = ut.Path(path)
242                 pstatus = prepo.status(
243                     untracked='no',
244                     # limit query to target path for a potentially massive speed-up
245  ->                 paths=[check_path.relative_to(parentds_path)])
246                 if any(
247                         check_path == p or check_path in p.parents
248                         for p in pstatus):
249                     # redo the check in a slower fashion, it is already broken
250                     # let's take our time for a proper error message
```

**Comment by yarikoptic** [comment]
ok, the requirement is for it to be a subdataset:
```shell
$> bash /tmp/crash                                      
++ mktemp -dt dl-XXXXXXX
+ cd /home/yoh/.tmp/dl-HUsPII2
+ datalad --version
datalad 0.12.0rc4.dev108
+ datalad create -d .
[INFO   ] Creating a new annex repo at /home/yoh/.tmp/dl-HUsPII2 
create(ok): . (dataset)                                                                                                                                                                                                           
+ for l in 1 2 3
+ echo 'Level 1'
Level 1
+ mkdir d1
+ cd d1
+ datalad create -d .
[ERROR  ] '.' does not start with '..' [__init__.py:relative_to:1077] (ValueError) 

$> cat /tmp/crash
#!/bin/sh

set -eux

cd $(mktemp -dt dl-XXXXXXX)
datalad --version
datalad create -d .
for l in 1 2 3; do
	echo "Level $l"
	mkdir d$l
	cd d$l
	datalad create -d .
done
```
works fine with 0.11.5, crashes with master
