### ISSUE TITLE
cookies saving atexit should be more robust

### ISSUE THREAD

**Issue by yarikoptic** [datalad/datalad#3489]
From a failed (tests failure, not directly this as a cause I believe) conda-forge build of 0.11.5:
```
Error in atexit._run_exitfuncs:
Traceback (most recent call last):
  File "/home/conda/feedstock_root/build_artifacts/datalad_1561498363479/_test_env_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehol/lib/python3.7/shelve.py", line 144, in close
    self.sync()
  File "/home/conda/feedstock_root/build_artifacts/datalad_1561498363479/_test_env_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehol/lib/python3.7/shelve.py", line 172, in sync
…FileNotFoundError: [Errno 2] No such file or directory: '/tmp/datalad_temp_plhxtodg/.config/datalad/cookies.dir'
```

**Comment by yarikoptic** [comment]
This was addressed by #3611
