### ISSUE TITLE
Appveyor started to fail

### ISSUE THREAD

**Issue by yarikoptic** [datalad/datalad#3500]
I think we had some notice/discussion in one of the recent PRs but didn't find on a quick search and do not see a dedicated issue, so here it is: e.g. from a 3 day old run of master
https://ci.appveyor.com/project/mih/datalad/builds/25616717/job/chid03xmfdb40wfa and failures happen also on PRs like https://github.com/datalad/datalad/pull/3476 :

```
======================================================================
FAIL: datalad.core.local.tests.test_save.test_add_files
----------------------------------------------------------------------
Traceback (most recent call last):
  File "C:\Miniconda35\envs\test-environment\lib\site-packages\nose\case.py", line 198, in runTest
    self.test(*self.arg)
  File "C:\Miniconda35\envs\test-environment\lib\site-packages\datalad\tests\utils.py", line 434, in newfunc
    return t(*(arg + (d,)), **kw)
  File "C:\Miniconda35\envs\test-environment\lib\site-packages\datalad\core\local\tests\test_save.py", line 366, in test_add_files
    assert p.get('key', None) is not None, f
AssertionError: C:\Users\appveyor\AppData\Local\Temp\1\datalad_temp_tree_t1ptehtt\test_annex.txt
======================================================================
FAIL: datalad.core.local.tests.test_status.test_status
----------------------------------------------------------------------
Traceback (most recent call last):
  File "C:\Miniconda35\envs\test-environment\lib\site-packages\nose\case.py", line 198, in runTest
    self.test(*self.arg)
  File "C:\Miniconda35\envs\test-environment\lib\site-packages\datalad\tests\utils.py", line 607, in newfunc
    return t(*(arg + (filename,)), **kw)
  File "C:\Miniconda35\envs\test-environment\lib\site-packages\datalad\tests\utils.py", line 607, in newfunc
    return t(*(arg + (filename,)), **kw)
  File "C:\Miniconda35\envs\test-environment\lib\site-packages\datalad\core\local\tests\test_status.py", line 139, in test_status
    'MD5E-s5--275876e34cf609db118f3d84b799a790.txt'))
  File "C:\Miniconda35\envs\test-environment\lib\site-packages\datalad\tests\utils.py", line 1265, in assert_result_count
    dumps(results, indent=1, default=lambda x: str(x))))
AssertionError: Got 0 instead of 1 expected results matching {'key': 'MD5E-s5--275876e34cf609db118f3d84b799a790.txt', 'path': 'C:\\Users\\appveyor\\AppData\\Local\\Temp\\1\\datalad_temp_1la4h1_j\\subdir\\annexed_file.txt', 'has_content': True, 'objloc': 'C:\\Users\\appveyor\\AppData\\Local\\Temp\\1\\datalad_temp_1la4h1_j\\.git\\annex\\objects\\f33\\94b\\MD5E-s5--275876e34cf609db118f3d84b799a790.txt\\MD5E-s5--275876e34cf609db118f3d84b799a790.txt'}. Inspected 14 record(s):
[
 {
  "refds": "C:\\Users\\appveyor\\AppData\\Local\\Temp\\1\\datalad_temp_1la4h1_j",
  "parentds": "C:\\Users\\appveyor\\AppData\\Local\\Temp\\1\\datalad_temp_1la4h1_j",
...
```

**Comment by kyleam** [comment]
I suspect this is all due to the `find --json` [issue] in annex.  AppVeyor is [now running][ag] with a git-annex that includes the upstream fix, so we should find out on the next AppVeyor run for master.

[issue]: http://git-annex.branchable.com/bugs/Regression_in___96__find_--json__96___output/
[ag]: https://ci.appveyor.com/project/mih/datalad/builds/25824403/job/y2k9g724mwqar0dc#L544

**Comment by kyleam** [comment]
> so we should find out on the next AppVeyor run for master.

Actually I've just pushed a scratch branch that's in line with the current master.  Let's see how [that build][0] does.

[0]: https://ci.appveyor.com/project/mih/datalad/builds/25826310

**Comment by kyleam** [comment]
>  Let's see how [that build](https://ci.appveyor.com/project/mih/datalad/builds/25826310) does.

First run was green: https://ci.appveyor.com/project/mih/datalad/builds/25826310
