### ISSUE TITLE
`datalad status --annex basic` fails with URL-type keys

### ISSUE THREAD

**Issue by mih** [datalad/datalad#3519]
```
(datalad3-dev) mih@meiner /tmp/machinelearning-books (git)-[master] % dl status --annex all
[ERROR  ] invalid literal for int() with base 10: 'unknown' [annexrepo.py:get_content_annexinfo:3141] (ValueError) 
(datalad3-dev) 1 mih@meiner /tmp/machinelearning-books (git)-[master] % dl --dbg status --annex all
Traceback (most recent call last):
  File "/home/mih/env/datalad3-dev/bin/datalad", line 8, in <module>
    main()
  File "/home/mih/hacking/datalad/git/datalad/cmdline/main.py", line 505, in main
    ret = cmdlineargs.func(cmdlineargs)
  File "/home/mih/hacking/datalad/git/datalad/interface/base.py", line 645, in call_from_parser
    ret = list(ret)
  File "/home/mih/hacking/datalad/git/datalad/interface/utils.py", line 428, in generator_func
    result_renderer, result_xfm, _result_filter, **_kwargs):
  File "/home/mih/hacking/datalad/git/datalad/interface/utils.py", line 520, in _process_results
    for res in results:
  File "/home/mih/hacking/datalad/git/datalad/core/local/status.py", line 370, in __call__
    content_info_cache):
  File "/home/mih/hacking/datalad/git/datalad/core/local/status.py", line 124, in _yield_status
    ref=None)
  File "/home/mih/hacking/datalad/git/datalad/support/annexrepo.py", line 3141, in get_content_annexinfo
    rec['bytesize'] = int(rec['bytesize'])
ValueError: invalid literal for int() with base 10: 'unknown'

> /home/mih/hacking/datalad/git/datalad/support/annexrepo.py(3141)get_content_annexinfo()
-> rec['bytesize'] = int(rec['bytesize'])
(Pdb) rec
{'state': 'clean', 'type': 'file', 'gitshasum': 'fce89a7c7c64b30b6ec47b409b01b51a26817cfb', 'bytesize': 'unknown', 'prev_gitshasum': 'fce89a7c7c64b30b6ec47b409b01b51a26817cfb', 'mtime': 'unknown', 'keyname': 'http://ciml.info/dl/v0_9/ciml-v0_9-all.pdf', 'backend': 'URL', 'key': 'URL--http://ciml.info/dl/v0_9/ciml-v0_9-all.pdf', 'humansize': 'unknown', 'hashdirmixed': 'x9/7W/', 'hashdirlower': '49c/39f/'}
```

Essentially the result renderer assumed that any record with a key also has information on the filesize. This is not valid for URL-type keys.

**Comment by mih** [comment]
Turns out that it only happens with URL keys that contain no size info -- which are actually hard to come by ;-)
