### ISSUE TITLE
travis: sphinx-build call in py2 runs is failing

### ISSUE THREAD

**Issue by kyleam** [datalad/datalad#3548]
I first spotted the failures on the py2 runs of [this build](https://travis-ci.org/datalad/datalad/builds/561961139):

```
make: Entering directory '/home/travis/build/datalad/datalad/docs'
sphinx-build -b html -d build/doctrees  -W source build/html
Traceback (most recent call last):
  File "/home/travis/virtualenv/python2.7.15/bin/sphinx-build", line 6, in <module>
    from sphinx.cmd.build import main
  File "/home/travis/virtualenv/python2.7.15/lib/python2.7/site-packages/sphinx/cmd/build.py", line 20, in <module>
    from docutils.utils import SystemMessage
  File "/home/travis/virtualenv/python2.7.15/lib/python2.7/site-packages/docutils/utils/__init__.py", line 21, in <module>
    import docutils.io
  File "/home/travis/virtualenv/python2.7.15/lib/python2.7/site-packages/docutils/io.py", line 348
    (self.destination.mode, mode)), file=self._stderr)
                                        ^
SyntaxError: invalid syntax
Makefile:55: recipe for target 'html' failed
make: *** [html] Error 1
```

It seems docutils v0.15 (released July 21) has a py2 compatibility issue.

**Comment by kyleam** [comment]
> It seems docutils v0.15 (released July 21) has a py2 compatibility issue.

The above failure happened on a 0.11.x build.  If the failure were simply due to the docutils release, I'd expect master to show the same issue, but the latest build on master has a green [py27 run](https://travis-ci.org/datalad/datalad/jobs/562074538).

I suppose we should wait and see if the 0.11.x builds continue to show the failure.

**Comment by kyleam** [comment]
I pushed a scratch branch based off of 0.11.x, and the sphinx-build call looks fine: <https://travis-ci.org/datalad/datalad/builds/562099955>

So, whatever the source of the issue was, things seem to be resolved.  I'll re-open this if the failures reemerge.

**Comment by kyleam** [comment]
For posterity: https://sourceforge.net/p/docutils/bugs/365/
