### ISSUE TITLE
test_import_meta_handle failure while building debian pkg

### ISSUE THREAD

**Issue by yarikoptic** [datalad/datalad#357]
Was looking into building updated debian package, and this test is the only one left failing after #356 :

```
======================================================================
FAIL: datalad.interface.tests.test_import_metadata.test_import_meta_handle
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/usr/lib/python2.7/dist-packages/nose/case.py", line 197, in runTest
    self.test(*self.arg)
  File "/home/yoh/proj/datalad/build-area/datalad-0.1+git576-g961f246/.pybuild/pythonX.Y_2.7/build/datalad/tests/utils.py", line 710, in newfunc
    reraise(*exc_info)
  File "/home/yoh/proj/datalad/build-area/datalad-0.1+git576-g961f246/.pybuild/pythonX.Y_2.7/build/datalad/tests/utils.py", line 686, in newfunc
    func(*args, **kwargs)
  File "/home/yoh/proj/datalad/build-area/datalad-0.1+git576-g961f246/.pybuild/pythonX.Y_2.7/build/datalad/tests/utils.py", line 615, in newfunc
    t(*(arg + (uri,)), **kw)
  File "/home/yoh/proj/datalad/build-area/datalad-0.1+git576-g961f246/.pybuild/pythonX.Y_2.7/build/datalad/tests/utils.py", line 430, in newfunc
    return t(*(arg + (filename,)), **kw)
  File "/home/yoh/proj/datalad/build-area/datalad-0.1+git576-g961f246/.pybuild/pythonX.Y_2.7/build/datalad/tests/utils.py", line 430, in newfunc
    return t(*(arg + (filename,)), **kw)
  File "/home/yoh/proj/datalad/build-area/datalad-0.1+git576-g961f246/.pybuild/pythonX.Y_2.7/build/datalad/interface/tests/test_import_metadata.py", line 108, in test_import_meta_handle
    predicate=PAV.createdBy)))
AssertionError: set([rdflib.term.URIRef(u'mailto:justanemail@address.tl'), rdflib.term.URIRef(u'mailto:benjaminpoldrack@gmail.com'), rdflib.term.URIRef(u'https://www.myfancypage.com/digital'), rdflib.term.URIRef(u'file:///home/yoh/proj/datalad/build-area/datalad-0.1+git576-g961f246/.pybuild/pythonX.Y_2.7/build/#author1')]) != set([rdflib.term.URIRef(u'file:///home/yoh/proj/datalad/build-area/datalad-0.1%2Bgit576-g961f246/.pybuild/pythonX.Y_2.7/build/#author1'), rdflib.term.URIRef(u'mailto:justanemail@address.tl'), rdflib.term.URIRef(u'https://www.myfancypage.com/digital'), rdflib.term.URIRef(u'mailto:benjaminpoldrack@gmail.com')])
```

while at it, probably best replacing personal emails with some fictitious or a dedicate `testemail@datalad.org`

**Comment by yarikoptic** [comment]
not pertinent any longer
