### ISSUE TITLE
UnboundLocalError: local variable 'e' referenced before assignment

### ISSUE THREAD

**Issue by mih** [datalad/datalad#3621]
Seen when running 0.12 tests on an installed Debian package https://github.com/datalad/datalad/pull/3620 I have no S3 config in place, but it shouldn't crash

```
======================================================================
ERROR: datalad.interface.tests.test_ls.test_ls_s3
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/nose/case.py", line 197, in runTest
    self.test(*self.arg)
  File "/usr/lib/python3/dist-packages/datalad/tests/utils.py", line 841, in newfunc
    return func(*args, **kwargs)
  File "/usr/lib/python3/dist-packages/vcr/cassette.py", line 109, in __call__
    function, args, kwargs
  File "/usr/lib/python3/dist-packages/vcr/cassette.py", line 124, in _execute_function
    return self._handle_function(fn=handle_function)
  File "/usr/lib/python3/dist-packages/vcr/cassette.py", line 151, in _handle_function
    return fn(cassette)
  File "/usr/lib/python3/dist-packages/vcr/cassette.py", line 117, in handle_function
    return function(*args, **kwargs)
  File "/usr/lib/python3/dist-packages/datalad/interface/tests/test_ls.py", line 47, in test_ls_s3
    res = ls(url)
  File "/usr/lib/python3/dist-packages/datalad/interface/ls.py", line 144, in __call__
    **kw)
  File "/usr/lib/python3/dist-packages/datalad/interface/ls.py", line 580, in _ls_s3
    bucket = downloader.access(lambda url: downloader.bucket, loc)
  File "/usr/lib/python3/dist-packages/datalad/downloaders/base.py", line 199, in access
    "reraising: %s" % exc_str(e))
UnboundLocalError: local variable 'e' referenced before assignment
```

**Comment by mih** [comment]
I feel like if have seen this before and we already talked about it, but I don't seem to be able to find the issue, and also I am not sure what reraising outside try/except is supposed to accomplish. Which kinda contradicts:

```
if access_denied:  # moved logic outside of except for clarity
```

I suspect the solution would be to move the error handling conditional back into the `AccessDeniedError` except block.
