### ISSUE TITLE
datalad.core test failures on real win10/conda

### ISSUE THREAD

**Issue by mih** [datalad/datalad#3633]
The appveyor environment is supercharged in many ways. Here is a glimpse of reality starting from https://github.com/datalad-handbook/book/issues/132:

```
> python -m nose datalad.core
======================================================================
ERROR: datalad.core.local.tests.test_create.test_create_with_obscure_name({'path': ' ;abcΔЙקم๗ あ'},)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "C:\Users\mih\Miniconda3\lib\site-packages\nose\case.py", line 198, in runTest
    self.test(*self.arg)
  File "c:\users\mih\code\datalad\datalad\tests\utils.py", line 607, in newfunc
    return t(*(arg + (filename,)), **kw)
  File "c:\users\mih\code\datalad\datalad\core\local\tests\test_create.py", line 470, in check_create_obscure
    ds = create(result_renderer="default", **create_kwargs)
  File "C:\Users\mih\Miniconda3\lib\site-packages\wrapt\wrappers.py", line 564, in __call__
    args, kwargs)
  File "c:\users\mih\code\datalad\datalad\interface\utils.py", line 499, in eval_func
    return return_func(generator_func)(*args, **kwargs)
  File "C:\Users\mih\Miniconda3\lib\site-packages\wrapt\wrappers.py", line 564, in __call__
    args, kwargs)
  File "c:\users\mih\code\datalad\datalad\interface\utils.py", line 487, in return_func
    results = list(results)
  File "c:\users\mih\code\datalad\datalad\interface\utils.py", line 435, in generator_func
    result_renderer, result_xfm, _result_filter, **_kwargs):
  File "c:\users\mih\code\datalad\datalad\interface\utils.py", line 595, in _process_results
    default_result_renderer(res)
  File "c:\users\mih\code\datalad\datalad\interface\utils.py", line 526, in default_result_renderer
    if 'message' in res else ''))
  File "c:\users\mih\code\datalad\datalad\ui\dialog.py", line 75, in message
    self.out.write(msg)
  File "C:\Users\mih\Miniconda3\lib\encodings\cp1252.py", line 19, in encode
    return codecs.charmap_encode(input,self.errors,encoding_table)[0]
UnicodeEncodeError: 'charmap' codec can't encode characters in position 71-76: character maps to <undefined>

======================================================================
ERROR: datalad.core.local.tests.test_diff.test_path_diff
----------------------------------------------------------------------
Traceback (most recent call last):
  File "C:\Users\mih\Miniconda3\lib\site-packages\nose\case.py", line 198, in runTest
    self.test(*self.arg)
  File "c:\users\mih\code\datalad\datalad\tests\utils.py", line 607, in newfunc
    return t(*(arg + (filename,)), **kw)
  File "c:\users\mih\code\datalad\datalad\tests\utils.py", line 607, in newfunc
    return t(*(arg + (filename,)), **kw)
  File "c:\users\mih\code\datalad\datalad\core\local\tests\test_diff.py", line 305, in test_path_diff
    ds = get_deeply_nested_structure(str(_path))
  File "c:\users\mih\code\datalad\datalad\tests\utils.py", line 1754, in get_deeply_nested_structure
    'annexed_file.txt')
  File "C:\Users\mih\Miniconda3\lib\pathlib.py", line 1330, in symlink_to
    self._accessor.symlink(target, self, target_is_directory)
OSError: symbolic link privilege not held

======================================================================
ERROR: datalad.core.local.tests.test_run.test_py2_unicode_command
----------------------------------------------------------------------
Traceback (most recent call last):
  File "C:\Users\mih\Miniconda3\lib\site-packages\nose\case.py", line 198, in runTest
    self.test(*self.arg)
  File "c:\users\mih\code\datalad\datalad\tests\utils.py", line 607, in newfunc
    return t(*(arg + (filename,)), **kw)
  File "c:\users\mih\code\datalad\datalad\core\local\tests\test_run.py", line 149, in test_py2_unicode_command
    ds.run(cmd_str)
  File "C:\Users\mih\Miniconda3\lib\site-packages\wrapt\wrappers.py", line 603, in __call__
    args, kwargs)
  File "c:\users\mih\code\datalad\datalad\distribution\dataset.py", line 526, in apply_func
    return f(**kwargs)
  File "C:\Users\mih\Miniconda3\lib\site-packages\wrapt\wrappers.py", line 564, in __call__
    args, kwargs)
  File "c:\users\mih\code\datalad\datalad\interface\utils.py", line 499, in eval_func
    return return_func(generator_func)(*args, **kwargs)
  File "C:\Users\mih\Miniconda3\lib\site-packages\wrapt\wrappers.py", line 564, in __call__
    args, kwargs)
  File "c:\users\mih\code\datalad\datalad\interface\utils.py", line 487, in return_func
    results = list(results)
  File "c:\users\mih\code\datalad\datalad\interface\utils.py", line 435, in generator_func
    result_renderer, result_xfm, _result_filter, **_kwargs):
  File "c:\users\mih\code\datalad\datalad\interface\utils.py", line 536, in _process_results
    for res in results:
  File "c:\users\mih\code\datalad\datalad\core\local\run.py", line 203, in __call__
    sidecar=sidecar):
  File "c:\users\mih\code\datalad\datalad\core\local\run.py", line 648, in run_command
    for r in saver(ds, outputs_to_save, msg):
  File "c:\users\mih\code\datalad\datalad\interface\utils.py", line 474, in generator_func
    msg="Command did not complete successfully")
datalad.support.exceptions.IncompleteResultsError: Command did not complete successfully [{'action': 'add', 'path': 'C:\\Users\\mih\\AppData\\Local\\Temp\\datalad_temp_nzuxpxpy\\bβ0.dat', 'type': 'file', 'refds': 'C:\\Users\\mih\\AppData\\Local\\Temp\\datalad_temp_nzuxpxpy', 'status': 'error', 'key': None}]

======================================================================
ERROR: datalad.core.local.tests.test_save.test_add_files
----------------------------------------------------------------------
Traceback (most recent call last):
  File "C:\Users\mih\Miniconda3\lib\site-packages\nose\case.py", line 198, in runTest
    self.test(*self.arg)
  File "c:\users\mih\code\datalad\datalad\tests\utils.py", line 434, in newfunc
    return t(*(arg + (d,)), **kw)
  File "c:\users\mih\code\datalad\datalad\core\local\tests\test_save.py", line 358, in test_add_files
    result = ds.save('dir', to_git=arg[1])
  File "C:\Users\mih\Miniconda3\lib\site-packages\wrapt\wrappers.py", line 603, in __call__
    args, kwargs)
  File "c:\users\mih\code\datalad\datalad\distribution\dataset.py", line 526, in apply_func
    return f(**kwargs)
  File "C:\Users\mih\Miniconda3\lib\site-packages\wrapt\wrappers.py", line 564, in __call__
    args, kwargs)
  File "c:\users\mih\code\datalad\datalad\interface\utils.py", line 499, in eval_func
    return return_func(generator_func)(*args, **kwargs)
  File "C:\Users\mih\Miniconda3\lib\site-packages\wrapt\wrappers.py", line 564, in __call__
    args, kwargs)
  File "c:\users\mih\code\datalad\datalad\interface\utils.py", line 487, in return_func
    results = list(results)
  File "c:\users\mih\code\datalad\datalad\interface\utils.py", line 474, in generator_func
    msg="Command did not complete successfully")
datalad.support.exceptions.IncompleteResultsError: Command did not complete successfully [{'action': 'add', 'path': 'C:\\Users\\mih\\AppData\\Local\\Temp\\datalad_temp_tree_ba7d91yb\\dir\\ ;abcΔЙקم๗あ', 'type': 'file', 'refds': 'C:\\Users\\mih\\AppData\\Local\\Temp\\datalad_temp_tree_ba7d91yb', 'status': 'error', 'key': None}]

======================================================================
ERROR: datalad.core.local.tests.test_save.test_add_subdataset
----------------------------------------------------------------------
Traceback (most recent call last):
  File "C:\Users\mih\Miniconda3\lib\site-packages\nose\case.py", line 198, in runTest
    self.test(*self.arg)
  File "c:\users\mih\code\datalad\datalad\tests\utils.py", line 434, in newfunc
    return t(*(arg + (d,)), **kw)
  File "c:\users\mih\code\datalad\datalad\tests\utils.py", line 607, in newfunc
    return t(*(arg + (filename,)), **kw)
  File "c:\users\mih\code\datalad\datalad\core\local\tests\test_save.py", line 382, in test_add_subdataset
    save(dataset=subds.path)
  File "C:\Users\mih\Miniconda3\lib\site-packages\wrapt\wrappers.py", line 564, in __call__
    args, kwargs)
  File "c:\users\mih\code\datalad\datalad\interface\utils.py", line 499, in eval_func
    return return_func(generator_func)(*args, **kwargs)
  File "C:\Users\mih\Miniconda3\lib\site-packages\wrapt\wrappers.py", line 564, in __call__
    args, kwargs)
  File "c:\users\mih\code\datalad\datalad\interface\utils.py", line 487, in return_func
    results = list(results)
  File "c:\users\mih\code\datalad\datalad\interface\utils.py", line 474, in generator_func
    msg="Command did not complete successfully")
datalad.support.exceptions.IncompleteResultsError: Command did not complete successfully [{'action': 'add', 'path': 'C:\\Users\\mih\\AppData\\Local\\Temp\\datalad_temp_tree_5fx0ftm8\\dir\\ ;abcΔЙקم๗あ', 'type': 'file', 'refds': 'C:\\Users\\mih\\AppData\\Local\\Temp\\datalad_temp_tree_5fx0ftm8\\dir', 'status': 'error', 'key': None}]

======================================================================
ERROR: datalad.core.local.tests.test_save.test_relpath_add
----------------------------------------------------------------------
Traceback (most recent call last):
  File "C:\Users\mih\Miniconda3\lib\site-packages\nose\case.py", line 198, in runTest
    self.test(*self.arg)
  File "c:\users\mih\code\datalad\datalad\tests\utils.py", line 434, in newfunc
    return t(*(arg + (d,)), **kw)
  File "c:\users\mih\code\datalad\datalad\core\local\tests\test_save.py", line 542, in test_relpath_add
    save('..')
  File "C:\Users\mih\Miniconda3\lib\site-packages\wrapt\wrappers.py", line 564, in __call__
    args, kwargs)
  File "c:\users\mih\code\datalad\datalad\interface\utils.py", line 499, in eval_func
    return return_func(generator_func)(*args, **kwargs)
  File "C:\Users\mih\Miniconda3\lib\site-packages\wrapt\wrappers.py", line 564, in __call__
    args, kwargs)
  File "c:\users\mih\code\datalad\datalad\interface\utils.py", line 487, in return_func
    results = list(results)
  File "c:\users\mih\code\datalad\datalad\interface\utils.py", line 474, in generator_func
    msg="Command did not complete successfully")
datalad.support.exceptions.IncompleteResultsError: Command did not complete successfully [{'action': 'add', 'path': 'C:\\Users\\mih\\AppData\\Local\\Temp\\datalad_temp_tree_1m2x5350\\ ;abcΔЙקم๗あ', 'type': 'file', 'refds': 'C:\\Users\\mih\\AppData\\Local\\Temp\\datalad_temp_tree_1m2x5350', 'status': 'error', 'key': None}, {'action': 'add', 'path': 'C:\\Users\\mih\\AppData\\Local\\Temp\\datalad_temp_tree_1m2x5350\\dir\\ ;abcΔЙקم๗あ', 'type': 'file', 'refds': 'C:\\Users\\mih\\AppData\\Local\\Temp\\datalad_temp_tree_1m2x5350', 'status': 'error', 'key': None}]

======================================================================
ERROR: datalad.core.local.tests.test_save.test_save_obscure_name
----------------------------------------------------------------------
Traceback (most recent call last):
  File "C:\Users\mih\Miniconda3\lib\site-packages\nose\case.py", line 198, in runTest
    self.test(*self.arg)
  File "c:\users\mih\code\datalad\datalad\tests\utils.py", line 434, in newfunc
    return t(*(arg + (d,)), **kw)
  File "c:\users\mih\code\datalad\datalad\core\local\tests\test_save.py", line 744, in test_save_obscure_name
    ds.save(path=fname, result_renderer="default")
  File "C:\Users\mih\Miniconda3\lib\site-packages\wrapt\wrappers.py", line 603, in __call__
    args, kwargs)
  File "c:\users\mih\code\datalad\datalad\distribution\dataset.py", line 526, in apply_func
    return f(**kwargs)
  File "C:\Users\mih\Miniconda3\lib\site-packages\wrapt\wrappers.py", line 564, in __call__
    args, kwargs)
  File "c:\users\mih\code\datalad\datalad\interface\utils.py", line 499, in eval_func
    return return_func(generator_func)(*args, **kwargs)
  File "C:\Users\mih\Miniconda3\lib\site-packages\wrapt\wrappers.py", line 564, in __call__
    args, kwargs)
  File "c:\users\mih\code\datalad\datalad\interface\utils.py", line 487, in return_func
    results = list(results)
  File "c:\users\mih\code\datalad\datalad\interface\utils.py", line 435, in generator_func
    result_renderer, result_xfm, _result_filter, **_kwargs):
  File "c:\users\mih\code\datalad\datalad\interface\utils.py", line 595, in _process_results
    default_result_renderer(res)
  File "c:\users\mih\code\datalad\datalad\interface\utils.py", line 526, in default_result_renderer
    if 'message' in res else ''))
  File "c:\users\mih\code\datalad\datalad\ui\dialog.py", line 75, in message
    self.out.write(msg)
  File "C:\Users\mih\Miniconda3\lib\encodings\cp1252.py", line 19, in encode
    return codecs.charmap_encode(input,self.errors,encoding_table)[0]
UnicodeEncodeError: 'charmap' codec can't encode characters in position 17-22: character maps to <undefined>

======================================================================
ERROR: datalad.core.local.tests.test_status.test_status
----------------------------------------------------------------------
Traceback (most recent call last):
  File "C:\Users\mih\Miniconda3\lib\site-packages\nose\case.py", line 198, in runTest
    self.test(*self.arg)
  File "c:\users\mih\code\datalad\datalad\tests\utils.py", line 607, in newfunc
    return t(*(arg + (filename,)), **kw)
  File "c:\users\mih\code\datalad\datalad\tests\utils.py", line 607, in newfunc
    return t(*(arg + (filename,)), **kw)
  File "c:\users\mih\code\datalad\datalad\core\local\tests\test_status.py", line 111, in test_status
    ds = get_deeply_nested_structure(text_type(_path))
  File "c:\users\mih\code\datalad\datalad\tests\utils.py", line 1754, in get_deeply_nested_structure
    'annexed_file.txt')
  File "C:\Users\mih\Miniconda3\lib\pathlib.py", line 1330, in symlink_to
    self._accessor.symlink(target, self, target_is_directory)
OSError: symbolic link privilege not held

======================================================================
FAIL: datalad.core.local.tests.test_save.test_encoding
----------------------------------------------------------------------
Traceback (most recent call last):
  File "C:\Users\mih\Miniconda3\lib\site-packages\nose\case.py", line 198, in runTest
    self.test(*self.arg)
  File "c:\users\mih\code\datalad\datalad\tests\utils.py", line 434, in newfunc
    return t(*(arg + (d,)), **kw)
  File "c:\users\mih\code\datalad\datalad\core\local\tests\test_save.py", line 337, in test_encoding
    assert_repo_status(ds.path, added=[staged], untracked=[untracked])
  File "c:\users\mih\code\datalad\datalad\tests\utils.py", line 1554, in assert_repo_status
    % (state, state_files, oktobefound))
AssertionError: unexpected content of state "added": [] != [WindowsPath('C:/Users/mih/AppData/Local/Temp/datalad_temp_tree_6_uf2fjs/ ;abcΔЙקم๗あ_staged')]

----------------------------------------------------------------------
Ran 70 tests in 562.922s

FAILED (SKIP=9, errors=8, failures=1)
```

**Comment by mih** [comment]
Closing this. The situation is much improved now.
