### ISSUE TITLE
datalad.distribution.tests.test_get failures on real win10/conda

### ISSUE THREAD

**Issue by mih** [datalad/datalad#3634]
The appveyor environment is supercharged in many ways. Here is a glimpse of reality starting from https://github.com/datalad-handbook/book/issues/132:

```
> python -m nose datalad.distribution.tests.test_get
======================================================================
FAIL: datalad.distribution.tests.test_get.test_get_recurse_dirs
----------------------------------------------------------------------
Traceback (most recent call last):
  File "c:\users\mih\code\datalad\datalad\tests\utils.py", line 1228, in assert_status
    assert_in(r['status'], label)
  File "C:\Users\mih\Miniconda3\lib\unittest\case.py", line 1106, in assertIn
    self.fail(self._formatMessage(msg, standardMsg))
  File "C:\Users\mih\Miniconda3\lib\unittest\case.py", line 680, in fail
    raise self.failureException(msg)
AssertionError: 'notneeded' not found in ['ok']

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\mih\Miniconda3\lib\site-packages\nose\case.py", line 198, in runTest
    self.test(*self.arg)
  File "c:\users\mih\code\datalad\datalad\tests\utils.py", line 434, in newfunc
    return t(*(arg + (d,)), **kw)
  File "c:\users\mih\code\datalad\datalad\tests\utils.py", line 607, in newfunc
    return t(*(arg + (filename,)), **kw)
  File "c:\users\mih\code\datalad\datalad\distribution\tests\test_get.py", line 229, in test_get_recurse_dirs
    assert_status('ok', result)
  File "c:\users\mih\code\datalad\datalad\tests\utils.py", line 1234, in assert_status
    dumps(results, indent=1, default=lambda x: str(x))))
AssertionError: Test 4/4: expected status ['ok'] not found in:
[
 {
  "type": "file",
  "refds": "C:\\Users\\mih\\AppData\\Local\\Temp\\datalad_temp_n06xb8w0",
  "status": "ok",
  "path": "C:\\Users\\mih\\AppData\\Local\\Temp\\datalad_temp_n06xb8w0\\subdir/subsubdir/file4.txt",
  "action": "get",
  "annexkey": "MD5E-s9--437b930db84b8079c2dd804a71936b5f.txt",
  "message": "from origin..."
 },
 {
  "type": "file",
  "refds": "C:\\Users\\mih\\AppData\\Local\\Temp\\datalad_temp_n06xb8w0",
  "status": "ok",
  "path": "C:\\Users\\mih\\AppData\\Local\\Temp\\datalad_temp_n06xb8w0\\subdir/file2.txt",
  "action": "get",
  "annexkey": "MD5E-s14--6c7ba9c5a141421e1c03cb9807c97c74.txt",
  "message": "from origin..."
 },
 {
  "type": "file",
  "refds": "C:\\Users\\mih\\AppData\\Local\\Temp\\datalad_temp_n06xb8w0",
  "status": "ok",
  "path": "C:\\Users\\mih\\AppData\\Local\\Temp\\datalad_temp_n06xb8w0\\subdir/subsubdir/file3.txt",
  "action": "get",
  "annexkey": "MD5E-s30--c22e53b13855f9e313a02bcb7c26a7cc.txt",
  "message": "from origin..."
 },
 {
  "action": "get",
  "path": "C:\\Users\\mih\\AppData\\Local\\Temp\\datalad_temp_n06xb8w0\\subdir",
  "type": "directory",
  "refds": "C:\\Users\\mih\\AppData\\Local\\Temp\\datalad_temp_n06xb8w0",
  "status": "notneeded",
  "message": [
   "nothing to get from %s",
   "C:\\Users\\mih\\AppData\\Local\\Temp\\datalad_temp_n06xb8w0\\subdir"
  ]
 }
]

======================================================================
FAIL: datalad.distribution.tests.test_get.test_get_flexible_source_candidates_for_submodule
----------------------------------------------------------------------
Traceback (most recent call last):
  File "C:\Users\mih\Miniconda3\lib\site-packages\nose\case.py", line 198, in runTest
    self.test(*self.arg)
  File "c:\users\mih\code\datalad\datalad\tests\utils.py", line 607, in newfunc
    return t(*(arg + (filename,)), **kw)
  File "c:\users\mih\code\datalad\datalad\tests\utils.py", line 607, in newfunc
    return t(*(arg + (filename,)), **kw)
  File "c:\users\mih\code\datalad\datalad\distribution\tests\test_get.py", line 87, in test_get_flexible_source_candidates_for_submodule
    eq_(f(clone, 'sub'), [t + '/sub'])
AssertionError: ['C:\\Users\\mih\\AppData\\Local\\Temp\\datalad_temp_et9vdsui\\sub'] != ['C:\\Users\\mih\\AppData\\Local\\Temp\\datalad_temp_et9vdsui/sub']

----------------------------------------------------------------------
Ran 13 tests in 241.061s

FAILED (SKIP=5, failures=2)
```

**Comment by mih** [comment]
Same situation as of https://github.com/datalad/datalad/commit/193ee353b97805dad9da8aea15041228ce6a03d3

**Comment by mih** [comment]
WIth #3719 both failures are gone on win10.
