### ISSUE TITLE
datalad.support.tests.test_annexrepo failures on real win10/conda

### ISSUE THREAD

**Issue by mih** [datalad/datalad#3636]
The appveyor environment is supercharged in many ways. Here is a glimpse of reality starting from https://github.com/datalad-handbook/book/issues/132:

```
> python -m nose datalad.support.tests.test_annexrepo
======================================================================
ERROR: datalad.support.tests.test_annexrepo.test_AnnexRepo_addurl_to_file_batched
----------------------------------------------------------------------
Traceback (most recent call last):
  File "C:\Users\mih\Miniconda3\lib\site-packages\nose\case.py", line 198, in runTest
    self.test(*self.arg)
  File "c:\users\mih\code\datalad\datalad\tests\utils.py", line 434, in newfunc
    return t(*(arg + (d,)), **kw)
  File "c:\users\mih\code\datalad\datalad\tests\utils.py", line 546, in newfunc
    return tfunc(*(args + (path, url)), **kwargs)
  File "c:\users\mih\code\datalad\datalad\tests\utils.py", line 607, in newfunc
    return t(*(arg + (filename,)), **kw)
  File "c:\users\mih\code\datalad\datalad\support\tests\test_annexrepo.py", line 982, in test_AnnexRepo_addurl_to_file_batched
    eq_(info['size'], 14)
TypeError: 'NoneType' object is not subscriptable

======================================================================
ERROR: datalad.support.tests.test_annexrepo.test_find_batch_equivalence
----------------------------------------------------------------------
Traceback (most recent call last):
  File "c:\users\mih\code\datalad\datalad\tests\utils.py", line 434, in newfunc
    return t(*(arg + (d,)), **kw)
  File "c:\users\mih\code\datalad\datalad\support\tests\test_annexrepo.py", line 492, in test_find_batch_equivalence
    eq_(expected, ar.find(query, batch=True))
  File "c:\users\mih\code\datalad\datalad\support\gitrepo.py", line 331, in newfunc
    result = func(self, files_new, *args, **kwargs)
  File "c:\users\mih\code\datalad\datalad\support\annexrepo.py", line 1506, in find
    for f, json_out in zip(files, find(files))}
  File "c:\users\mih\code\datalad\datalad\cmd.py", line 781, in __call__
    output = [o for o in self.yield_(cmds)]
  File "c:\users\mih\code\datalad\datalad\cmd.py", line 781, in <listcomp>
    output = [o for o in self.yield_(cmds)]
  File "c:\users\mih\code\datalad\datalad\cmd.py", line 791, in yield_
    yield self.proc1(entry)
  File "c:\users\mih\code\datalad\datalad\cmd.py", line 809, in proc1
    process.stdin.write(assure_bytes(entry) if PY2 else entry)
  File "C:\Users\mih\Miniconda3\lib\encodings\cp1252.py", line 19, in encode
    return codecs.charmap_encode(input,self.errors,encoding_table)[0]
UnicodeEncodeError: 'charmap' codec can't encode characters in position 5-10: character maps to <undefined>

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\mih\Miniconda3\lib\site-packages\nose\case.py", line 198, in runTest
    self.test(*self.arg)
  File "c:\users\mih\code\datalad\datalad\tests\utils.py", line 437, in newfunc
    rmtemp(d)
  File "c:\users\mih\code\datalad\datalad\utils.py", line 531, in rmtemp
    rmtree(f, *args, **kwargs)
  File "c:\users\mih\code\datalad\datalad\utils.py", line 444, in rmtree
    _rmtree(path, *args, **kwargs)
  File "c:\users\mih\code\datalad\datalad\utils.py", line 1872, in wrapped
    return f(*args, **kwargs)
  File "c:\users\mih\code\datalad\datalad\utils.py", line 1912, in _rmtree
    return shutil.rmtree(*args, **kwargs)
  File "C:\Users\mih\Miniconda3\lib\shutil.py", line 513, in rmtree
    return _rmtree_unsafe(path, onerror)
  File "C:\Users\mih\Miniconda3\lib\shutil.py", line 401, in _rmtree_unsafe
    onerror(os.rmdir, path, sys.exc_info())
  File "C:\Users\mih\Miniconda3\lib\shutil.py", line 399, in _rmtree_unsafe
    os.rmdir(path)
PermissionError: [WinError 32] Der Prozess kann nicht auf die Datei zugreifen, da sie von einem anderen Prozess verwendet wird: 'C:\\Users\\mih\\AppData\\Local\\Temp\\datalad_temp_tree_fh6izqpg'

======================================================================
ERROR: datalad.support.tests.test_annexrepo.test_AnnexRepo_metadata
----------------------------------------------------------------------
Traceback (most recent call last):
  File "C:\Users\mih\Miniconda3\lib\site-packages\nose\case.py", line 198, in runTest
    self.test(*self.arg)
  File "c:\users\mih\code\datalad\datalad\tests\utils.py", line 607, in newfunc
    return t(*(arg + (filename,)), **kw)
  File "c:\users\mih\code\datalad\datalad\support\tests\test_annexrepo.py", line 1834, in test_AnnexRepo_metadata
    'd o w n.dat': 'lowcontent'
  File "c:\users\mih\code\datalad\datalad\utils.py", line 2240, in create_tree
    remove_existing=remove_existing)
  File "c:\users\mih\code\datalad\datalad\utils.py", line 2216, in create_tree
    os.makedirs(path)
  File "C:\Users\mih\Miniconda3\lib\os.py", line 221, in makedirs
    mkdir(name, mode)
OSError: [WinError 123] Die Syntax für den Dateinamen, Verzeichnisnamen oder die Datenträgerbezeichnung ist falsch: 'C:\\Users\\mih\\AppData\\Local\\Temp\\datalad_temp_e8coqzgy\\d o"w n'

======================================================================
ERROR: datalad.support.tests.test_annexrepo.test_repo_version
----------------------------------------------------------------------
Traceback (most recent call last):
  File "C:\Users\mih\Miniconda3\lib\site-packages\nose\case.py", line 198, in runTest
    self.test(*self.arg)
  File "c:\users\mih\code\datalad\datalad\tests\utils.py", line 607, in newfunc
    return t(*(arg + (filename,)), **kw)
  File "c:\users\mih\code\datalad\datalad\tests\utils.py", line 607, in newfunc
    return t(*(arg + (filename,)), **kw)
  File "c:\users\mih\code\datalad\datalad\tests\utils.py", line 607, in newfunc
    return t(*(arg + (filename,)), **kw)
  File "c:\users\mih\code\datalad\datalad\support\tests\test_annexrepo.py", line 1232, in test_repo_version
    annex = AnnexRepo(path3, create=True, version=5)
  File "c:\users\mih\code\datalad\datalad\support\repo.py", line 146, in __call__
    instance = type.__call__(cls, *new_args, **new_kwargs)
  File "c:\users\mih\code\datalad\datalad\support\annexrepo.py", line 275, in __init__
    "Git configuration reports repository being in direct mode"
datalad.support.exceptions.DirectModeNoLongerSupportedError:  Git configuration reports repository being in direct mode, but direct mode of operation is being deprecated in git-annex and no longer supported by DataLad. Please use 'git annex upgrade' under C:\Users\mih\AppData\Local\Temp\datalad_temp_jr7x16ai to upgrade your direct mode repository to annex v6 (or later).

======================================================================
ERROR: datalad.support.tests.test_annexrepo.test_commit_annex_commit_changed(True,)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "c:\users\mih\code\datalad\datalad\tests\utils.py", line 434, in newfunc
    return t(*(arg + (d,)), **kw)
  File "c:\users\mih\code\datalad\datalad\support\tests\test_annexrepo.py", line 2092, in check_commit_annex_commit_changed
    ok_clean_git(path)
  File "c:\users\mih\code\datalad\datalad\tests\utils.py", line 203, in ok_clean_git
    eq_(index_diffs, [])
  File "C:\Users\mih\Miniconda3\lib\site-packages\nose\tools\trivial.py", line 29, in eq_
    raise AssertionError(msg or "%r != %r" % (a, b))
AssertionError: ['.gitattributes\n=======================================================\nlhs: 100644 | c62e2b7543b4f451b57dd6ff12870bf6057e01ab\nrhs: None'] != []

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\mih\Miniconda3\lib\site-packages\nose\case.py", line 198, in runTest
    self.test(*self.arg)
  File "c:\users\mih\code\datalad\datalad\tests\utils.py", line 437, in newfunc
    rmtemp(d)
  File "c:\users\mih\code\datalad\datalad\utils.py", line 531, in rmtemp
    rmtree(f, *args, **kwargs)
  File "c:\users\mih\code\datalad\datalad\utils.py", line 444, in rmtree
    _rmtree(path, *args, **kwargs)
  File "c:\users\mih\code\datalad\datalad\utils.py", line 1872, in wrapped
    return f(*args, **kwargs)
  File "c:\users\mih\code\datalad\datalad\utils.py", line 1912, in _rmtree
    return shutil.rmtree(*args, **kwargs)
  File "C:\Users\mih\Miniconda3\lib\shutil.py", line 513, in rmtree
    return _rmtree_unsafe(path, onerror)
  File "C:\Users\mih\Miniconda3\lib\shutil.py", line 401, in _rmtree_unsafe
    onerror(os.rmdir, path, sys.exc_info())
  File "C:\Users\mih\Miniconda3\lib\shutil.py", line 399, in _rmtree_unsafe
    os.rmdir(path)
PermissionError: [WinError 32] Der Prozess kann nicht auf die Datei zugreifen, da sie von einem anderen Prozess verwendet wird: 'C:\\Users\\mih\\AppData\\Local\\Temp\\datalad_temp_tree_w4xxl5vb'

======================================================================
ERROR: datalad.support.tests.test_annexrepo.test_commit_annex_commit_changed(False,)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "c:\users\mih\code\datalad\datalad\tests\utils.py", line 434, in newfunc
    return t(*(arg + (d,)), **kw)
  File "c:\users\mih\code\datalad\datalad\support\tests\test_annexrepo.py", line 2092, in check_commit_annex_commit_changed
    ok_clean_git(path)
  File "c:\users\mih\code\datalad\datalad\tests\utils.py", line 203, in ok_clean_git
    eq_(index_diffs, [])
  File "C:\Users\mih\Miniconda3\lib\site-packages\nose\tools\trivial.py", line 29, in eq_
    raise AssertionError(msg or "%r != %r" % (a, b))
AssertionError: ['.gitattributes\n=======================================================\nlhs: 100644 | c62e2b7543b4f451b57dd6ff12870bf6057e01ab\nrhs: None'] != []

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\mih\Miniconda3\lib\site-packages\nose\case.py", line 198, in runTest
    self.test(*self.arg)
  File "c:\users\mih\code\datalad\datalad\tests\utils.py", line 437, in newfunc
    rmtemp(d)
  File "c:\users\mih\code\datalad\datalad\utils.py", line 531, in rmtemp
    rmtree(f, *args, **kwargs)
  File "c:\users\mih\code\datalad\datalad\utils.py", line 444, in rmtree
    _rmtree(path, *args, **kwargs)
  File "c:\users\mih\code\datalad\datalad\utils.py", line 1872, in wrapped
    return f(*args, **kwargs)
  File "c:\users\mih\code\datalad\datalad\utils.py", line 1912, in _rmtree
    return shutil.rmtree(*args, **kwargs)
  File "C:\Users\mih\Miniconda3\lib\shutil.py", line 513, in rmtree
    return _rmtree_unsafe(path, onerror)
  File "C:\Users\mih\Miniconda3\lib\shutil.py", line 401, in _rmtree_unsafe
    onerror(os.rmdir, path, sys.exc_info())
  File "C:\Users\mih\Miniconda3\lib\shutil.py", line 399, in _rmtree_unsafe
    os.rmdir(path)
PermissionError: [WinError 32] Der Prozess kann nicht auf die Datei zugreifen, da sie von einem anderen Prozess verwendet wird: 'C:\\Users\\mih\\AppData\\Local\\Temp\\datalad_temp_tree_sgc027jy'

======================================================================
ERROR: datalad.support.tests.test_annexrepo.test_files_split(<class 'datalad.support.gitrepo.GitRepo'>,)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "C:\Users\mih\Miniconda3\lib\site-packages\nose\case.py", line 198, in runTest
    self.test(*self.arg)
  File "c:\users\mih\code\datalad\datalad\tests\utils.py", line 432, in newfunc
    create_tree(d, tree, archives_leading_dir=archives_leading_dir)
  File "c:\users\mih\code\datalad\datalad\utils.py", line 2240, in create_tree
    remove_existing=remove_existing)
  File "c:\users\mih\code\datalad\datalad\utils.py", line 2245, in create_tree
    with open_func(full_name, "wb") as f:
FileNotFoundError: [Errno 2] No such file or directory: 'C:\\Users\\mih\\AppData\\Local\\Temp\\datalad_temp_tree_tr31qvk6\\dddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddd000\\ffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffff000'

======================================================================
ERROR: datalad.support.tests.test_annexrepo.test_files_split(<class 'datalad.support.annexrepo.AnnexRepo'>,)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "C:\Users\mih\Miniconda3\lib\site-packages\nose\case.py", line 198, in runTest
    self.test(*self.arg)
  File "c:\users\mih\code\datalad\datalad\tests\utils.py", line 432, in newfunc
    create_tree(d, tree, archives_leading_dir=archives_leading_dir)
  File "c:\users\mih\code\datalad\datalad\utils.py", line 2240, in create_tree
    remove_existing=remove_existing)
  File "c:\users\mih\code\datalad\datalad\utils.py", line 2245, in create_tree
    with open_func(full_name, "wb") as f:
FileNotFoundError: [Errno 2] No such file or directory: 'C:\\Users\\mih\\AppData\\Local\\Temp\\datalad_temp_tree_6gle5e9o\\dddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddd000\\ffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffff000'

======================================================================
FAIL: datalad.support.tests.test_annexrepo.test_AnnexRepo_web_remote
----------------------------------------------------------------------
Traceback (most recent call last):
  File "C:\Users\mih\Miniconda3\lib\site-packages\nose\case.py", line 198, in runTest
    self.test(*self.arg)
  File "c:\users\mih\code\datalad\datalad\tests\utils.py", line 434, in newfunc
    return t(*(arg + (d,)), **kw)
  File "c:\users\mih\code\datalad\datalad\tests\utils.py", line 546, in newfunc
    return tfunc(*(args + (path, url)), **kwargs)
  File "c:\users\mih\code\datalad\datalad\tests\utils.py", line 607, in newfunc
    return t(*(arg + (filename,)), **kw)
  File "c:\users\mih\code\datalad\datalad\support\tests\test_annexrepo.py", line 457, in test_AnnexRepo_web_remote
    eq_(set(ar.whereis(testfile3, output='full').keys()), {ar.WEB_UUID, non_web_remote})
AssertionError: {'d/sub.txt'} != {'00000000-0000-0000-0000-000000000001', 'ef8d7665-b8b9-4ced-9350-7a6ccba12e1e'}

======================================================================
FAIL: datalad.support.tests.test_annexrepo.test_AnnexRepo_always_commit
----------------------------------------------------------------------
Traceback (most recent call last):
  File "C:\Users\mih\Miniconda3\lib\site-packages\nose\case.py", line 198, in runTest
    self.test(*self.arg)
  File "c:\users\mih\code\datalad\datalad\tests\utils.py", line 607, in newfunc
    return t(*(arg + (filename,)), **kw)
  File "c:\users\mih\code\datalad\datalad\support\tests\test_annexrepo.py", line 671, in test_AnnexRepo_always_commit
    eq_(len(out_list), 1)
AssertionError: 0 != 1

======================================================================
FAIL: datalad.support.tests.test_annexrepo.test_AnnexRepo_is_direct_mode_gitrepo
----------------------------------------------------------------------
Traceback (most recent call last):
  File "C:\Users\mih\Miniconda3\lib\site-packages\nose\case.py", line 198, in runTest
    self.test(*self.arg)
  File "c:\users\mih\code\datalad\datalad\tests\utils.py", line 607, in newfunc
    return t(*(arg + (filename,)), **kw)
  File "c:\users\mih\code\datalad\datalad\support\tests\test_annexrepo.py", line 197, in test_AnnexRepo_is_direct_mode_gitrepo
    ok_(dm)
AssertionError: None

======================================================================
FAIL: datalad.support.tests.test_annexrepo.test_wanted
----------------------------------------------------------------------
Traceback (most recent call last):
  File "C:\Users\mih\Miniconda3\lib\site-packages\nose\case.py", line 198, in runTest
    self.test(*self.arg)
  File "c:\users\mih\code\datalad\datalad\tests\utils.py", line 607, in newfunc
    return t(*(arg + (filename,)), **kw)
  File "c:\users\mih\code\datalad\datalad\support\tests\test_annexrepo.py", line 1801, in test_wanted
    eq_(ar.get_preferred_content('wanted'), None)
AssertionError: '' != None

======================================================================
FAIL: datalad.support.tests.test_annexrepo.test_v7_detached_get
----------------------------------------------------------------------
Traceback (most recent call last):
  File "C:\Users\mih\Miniconda3\lib\site-packages\nose\case.py", line 198, in runTest
    self.test(*self.arg)
  File "c:\users\mih\code\datalad\datalad\tests\utils.py", line 895, in newfunc
    return func(*args, **kwargs)
  File "c:\users\mih\code\datalad\datalad\tests\utils.py", line 434, in newfunc
    return t(*(arg + (d,)), **kw)
  File "c:\users\mih\code\datalad\datalad\tests\utils.py", line 607, in newfunc
    return t(*(arg + (filename,)), **kw)
  File "c:\users\mih\code\datalad\datalad\support\tests\test_annexrepo.py", line 903, in test_v7_detached_get
    ok_file_has_content(op.join(repo.path, 'file.dat'), "content")
  File "c:\users\mih\code\datalad\datalad\tests\utils.py", line 417, in ok_file_has_content
    assert_equal(content, file_content, **kwargs)
AssertionError: 'content' != '/annex/objects/SHA256E-s7--ed7002b439e9ac[52 chars]at\n'
- content
+ /annex/objects/SHA256E-s7--ed7002b439e9ac845f22357d822bac1444730fbdb6016d3ec9432297b9ec9f73.dat



----------------------------------------------------------------------
Ran 74 tests in 197.297s

FAILED (SKIP=32, errors=8, failures=5)
```

**Comment by mih** [comment]
Closing this outdated report. The situation now isn't necessarily better, but different.
