### ISSUE TITLE
Optimized gitrepo cloning broken on win10

### ISSUE THREAD

**Issue by mih** [datalad/datalad#3639]
Originally reported in #3635. Making it a separate issue, because the test will be disabled on win in order to make progress on more important issues.

This issue is legit, inodes seem to be reported properly, but do not match.

```
======================================================================
FAIL: datalad.support.tests.test_gitrepo.test_optimized_cloning
----------------------------------------------------------------------
Traceback (most recent call last):
  File "C:\Users\mih\Miniconda3\lib\site-packages\nose\case.py", line 198, in runTest
    self.test(*self.arg)
  File "c:\users\mih\code\datalad\datalad\tests\utils.py", line 607, in newfunc
    return t(*(arg + (filename,)), **kw)
  File "c:\users\mih\code\datalad\datalad\support\tests\test_gitrepo.py", line 1161, in test_optimized_cloning
    eq_(origin_inodes, clone_inodes, msg='with src={}'.format(src))
AssertionError: with src=file:///C%3A/Users/mih/AppData/Local/Temp/datalad_temp_xfuka682/origin
```

**Comment by mih** [comment]
This is not just a windows issue, but affects crippled FS as well.

```
======================================================================
FAIL: datalad.support.tests.test_gitrepo.test_optimized_cloning
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/mih/env/datalad3-dev/lib/python3.7/site-packages/nose/case.py", line 198, in runTest
    self.test(*self.arg)
  File "/home/mih/hacking/datalad/git/datalad/tests/utils.py", line 187, in newfunc
    return func(*args, **kwargs)
  File "/home/mih/hacking/datalad/git/datalad/tests/utils.py", line 715, in newfunc
    return t(*(arg + (filename,)), **kw)
  File "/home/mih/hacking/datalad/git/datalad/support/tests/test_gitrepo.py", line 1152, in test_optimized_cloning
    eq_(origin_inodes, clone_inodes, msg='with src={}'.format(src))
AssertionError: with src=/media/mih/Samsung_T5/tmp/datalad_temp_test_optimized_cloningby6pyqhk/origin
```

Revealed via gh-4708

**Comment by yarikoptic** [comment]
FWIW, on a verge of 2022 we still have that test disabled on windows 
```
(git)lena:~datalad/datalad-maint[maint]git
$> git grep -4 test_optimized_cloning
datalad/support/tests/test_gitrepo.py-# this is simply broken on win, but less important
datalad/support/tests/test_gitrepo.py-# https://github.com/datalad/datalad/issues/3639
datalad/support/tests/test_gitrepo.py-@skip_if_on_windows
datalad/support/tests/test_gitrepo.py-@with_tempfile
datalad/support/tests/test_gitrepo.py:def test_optimized_cloning(path):
```
so it is 50/50 chance it still exists! ;-)

**Comment by mih** [comment]
Confirm to still be happening on crippled FS.

**Comment by mih** [comment]
Closing this old issue of mine. In three years at has never made a priority level that led to actual fixes.
