### ISSUE TITLE
test_annex_ssh flakes out while testing 0.11.x

### ISSUE THREAD

**Issue by yarikoptic** [datalad/datalad#3647]
https://travis-ci.org/datalad/datalad/jobs/580117784  (but I will restart it now since I think it is just a flaky functioning/test and it had been passing before)
```
======================================================================
FAIL: datalad.support.tests.test_annexrepo.test_annex_ssh
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/travis/virtualenv/python3.6.7/lib/python3.6/site-packages/nose/case.py", line 198, in runTest
    self.test(*self.arg)
  File "/home/travis/virtualenv/python3.6.7/lib/python3.6/site-packages/datalad/tests/utils.py", line 921, in newfunc
    return func(*args, **kwargs)
  File "/home/travis/virtualenv/python3.6.7/lib/python3.6/site-packages/datalad/tests/utils.py", line 615, in newfunc
    return t(*(arg + (filename,)), **kw)
  File "/home/travis/virtualenv/python3.6.7/lib/python3.6/site-packages/datalad/tests/utils.py", line 791, in newfunc
    t(*(arg + (uri,)), **kw)
  File "/home/travis/virtualenv/python3.6.7/lib/python3.6/site-packages/datalad/tests/utils.py", line 791, in newfunc
    t(*(arg + (uri,)), **kw)
  File "/home/travis/virtualenv/python3.6.7/lib/python3.6/site-packages/datalad/support/tests/test_annexrepo.py", line 1218, in test_annex_ssh
    ok_(exists(socket_1))
AssertionError: None
```
 Commit fc66340

**Comment by yarikoptic** [comment]
the same is happening on master now: https://travis-ci.org/datalad/datalad/jobs/626325531?utm_medium=notification&utm_source=email

**Comment by mih** [comment]
I haven't seen this in ages. Closing.
