### ISSUE TITLE
`datalad test` reporting errors due to inappropriate write attempt

### ISSUE THREAD

**Issue by mih** [datalad/datalad#3662]
Running the tests via `datalad test` on a system that has 0.12rc5 deployed via the Debian package from https://github.com/datalad/datalad/pull/3620 I see this error.

I haven't looked into it yet, but it smells like a test setup problem. Tests run as a normal user.

```
======================================================================
ERROR: datalad.cmdline.tests.test_main.test_script_shims
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/nose/case.py", line 198, in runTest
    self.test(*self.arg)
  File "/usr/lib/python3/dist-packages/datalad/cmdline/tests/test_main.py", line 182, in test_script_shims
    with open(which.rstrip()) as f:
PermissionError: [Errno 13] Permission denied: '/usr/local/bin/git-annex-remote-datalad-archives'

======================================================================
ERROR: datalad.customremotes.tests.test_archives.test_annex_get_from_subdir
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/nose/case.py", line 198, in runTest
    self.test(*self.arg)
  File "/usr/lib/python3/dist-packages/datalad/tests/utils.py", line 434, in newfunc
    return t(*(arg + (d,)), **kw)
  File "/usr/lib/python3/dist-packages/datalad/customremotes/tests/test_archives.py", line 168, in test_annex_get_from_subdir
    add_archive_content('a.tar.gz', annex=annex, delete=True)
  File "/usr/lib/python3/dist-packages/datalad/interface/add_archive_content.py", line 308, in __call__
    init_datalad_remote(annex, ARCHIVES_SPECIAL_REMOTE, autoenable=True)
  File "/usr/lib/python3/dist-packages/datalad/customremotes/base.py", line 688, in init_datalad_remote
    return repo.init_remote(remote, remote_opts + opts)
  File "/usr/lib/python3/dist-packages/datalad/support/annexrepo.py", line 1631, in init_remote
    self._run_annex_command('initremote', annex_options=[name] + options)
  File "/usr/lib/python3/dist-packages/datalad/support/annexrepo.py", line 886, in _run_annex_command
    env=env, **kwargs)
  File "/usr/lib/python3/dist-packages/datalad/support/gitrepo.py", line 1920, in _run_command_files_split
    *args, **kwargs)
  File "/usr/lib/python3/dist-packages/datalad/cmd.py", line 698, in run
    cmd, env=self.get_git_environ_adjusted(env), *args, **kwargs)
  File "/usr/lib/python3/dist-packages/datalad/cmd.py", line 553, in run
    raise CommandError(text_type(cmd), msg, status, out[0], out[1])
datalad.support.exceptions.CommandError: CommandError: command '['git-annex', 'initremote', 'datalad-archives', 'encryption=none', 'type=external', 'autoenable=true', 'externaltype=datalad-archives', 'uuid=c04eb54b-4b4e-5755-8436-866b043170fa']' failed with exitcode 1
Failed to run ['git-annex', 'initremote', 'datalad-archives', 'encryption=none', 'type=external', 'autoenable=true', 'externaltype=datalad-archives', 'uuid=c04eb54b-4b4e-5755-8436-866b043170fa'] under '/tmp/datalad_temp_tree_test_annex_get_from_subdirzdjxvht8'. Exit code=1. out=initremote datalad-archives 
failed
 err=/usr/bin/python: can't open file '/usr/local/bin/git-annex-remote-datalad-archives': [Errno 13] Permission denied
/usr/bin/python: can't open file '/usr/local/bin/git-annex-remote-datalad-archives': [Errno 13] Permission denied
git-annex: external special remote protocol error, unexpectedly received "" (unable to parse command)
git-annex: initremote: 1 failed
```

**Comment by mih** [comment]
Looking into it with a refreshed brain the issue is obvious: A left-over custom installation of datalad in `/usr/local` that is found by the `which` call in the test helper.

Given that such scenario is likely to cause issue on a wider scale, I don't think we need to blame our test helpers.

Closing.
