### ISSUE TITLE
Consider removing or improving _run_simple_annex_command

### ISSUE THREAD

**Issue by kyleam** [datalad/datalad#3675]
This failure was first seen in gh-3667, but I pushed a branch with an empty commit on top of master, and that triggers the failure too:

https://ci.appveyor.com/project/mih/datalad/build/job/twie1e8nxddgufn0#L1385

```
======================================================================
FAIL: datalad.distribution.tests.test_update.test_multiway_merge
----------------------------------------------------------------------
Traceback (most recent call last):
  File "C:\Miniconda35\envs\test-environment\lib\site-packages\nose\case.py", line 198, in runTest
    self.test(*self.arg)
  File "C:\Miniconda35\envs\test-environment\lib\site-packages\datalad\tests\utils.py", line 607, in newfunc
    return t(*(arg + (filename,)), **kw)
  File "C:\Miniconda35\envs\test-environment\lib\site-packages\datalad\distribution\tests\test_update.py", line 399, in test_multiway_merge
    assert_status('ok', ds.publish(to='r1'))
  File "C:\Miniconda35\envs\test-environment\lib\site-packages\datalad\distribution\dataset.py", line 526, in apply_func
    return f(**kwargs)
  File "C:\Miniconda35\envs\test-environment\lib\site-packages\datalad\interface\utils.py", line 499, in eval_func
    return return_func(generator_func)(*args, **kwargs)
  File "C:\Miniconda35\envs\test-environment\lib\site-packages\datalad\interface\utils.py", line 487, in return_func
    results = list(results)
  File "C:\Miniconda35\envs\test-environment\lib\site-packages\datalad\interface\utils.py", line 435, in generator_func
    result_renderer, result_xfm, _result_filter, **_kwargs):
  File "C:\Miniconda35\envs\test-environment\lib\site-packages\datalad\interface\utils.py", line 536, in _process_results
    for res in results:
  File "C:\Miniconda35\envs\test-environment\lib\site-packages\datalad\distribution\publish.py", line 816, in __call__
    **res_kwargs):
  File "C:\Miniconda35\envs\test-environment\lib\site-packages\datalad\distribution\publish.py", line 360, in _publish_dataset
    **kwargs):
  File "C:\Miniconda35\envs\test-environment\lib\site-packages\datalad\distribution\publish.py", line 164, in _publish_data
    remote_wanted = ds.repo.get_preferred_content('wanted', remote)
  File "C:\Miniconda35\envs\test-environment\lib\site-packages\datalad\support\annexrepo.py", line 2437, in get_preferred_content
    annex_options=[remote or '.'])
  File "C:\Miniconda35\envs\test-environment\lib\site-packages\datalad\support\annexrepo.py", line 935, in _run_simple_annex_command
    assert(len(lines_) <= 1)
AssertionError
```

The [last passing build][0] had git-annex 7.20190731-gc131c0f0c, and this failing one is at 7.20190912-g05bc37910.

[0]: https://ci.appveyor.com/project/mih/datalad/builds/27389604/job/mdymsm41isx4mt3d?fullLog=true#L523

**Comment by yarikoptic** [comment]
I guess we need to make that assertion message more informative and include actual lines to see what unexpected lines we get there

**Comment by mih** [comment]
FTR: I cannot replicate this on a real win10 box.

**Comment by mih** [comment]
I can confirm that this failure is triggered by the git-annex version change on a real win10 box, as reported by @kyleam

**Comment by mih** [comment]
This is how things look like at the point of failure:

```
> c:\users\mih\code\datalad\datalad\support\annexrepo.py(931)_run_simple_annex_command()
-> assert len(lines_) <= 1, lines_
(Pdb) out
'\r\n\r\n'
(Pdb) err
'  First run: git-annex init\r\n'
(Pdb) lines = out.rstrip('\n').splitlines()
(Pdb) lines
['', '']
(Pdb) lines_
['', '']
```

So there are two empty lines, instead of the expected single line?

However, it is not clear to me, what this function is trying to accomplish. Moreover, it has no dedicated tests, and is only used by annexrepo.py internally -- for preferred content related helper functions. It also completely ignores `err` (which seems to contain a hint, see above).

I think we should remove this helper function.

The failure seem to have its origin in an uninitialized repo, but I have no idea re details yet.

**Comment by kyleam** [comment]
@mih Thanks for providing more details.  I agree.

#3682 will close this when it hits master, but I'll re-open and re-title it.
