### ISSUE TITLE
path_is_under() cannot handle abspaths from different windows drives

### ISSUE THREAD

**Issue by mih** [datalad/datalad#3724]
Example:

```
2019-09-26T12:35:50.1532954Z ======================================================================
2019-09-26T12:35:50.1533192Z ERROR: datalad.core.local.tests.test_create.test_create_force_subds
2019-09-26T12:35:50.1533353Z ----------------------------------------------------------------------
2019-09-26T12:35:50.1533525Z Traceback (most recent call last):
2019-09-26T12:35:50.1560520Z   File "C:\hostedtoolcache\windows\Python\3.7.4\x64\lib\site-packages\nose\case.py", line 198, in runTest
2019-09-26T12:35:50.1560769Z     self.test(*self.arg)
2019-09-26T12:35:50.1560979Z   File "C:\hostedtoolcache\windows\Python\3.7.4\x64\lib\site-packages\datalad\tests\utils.py", line 602, in newfunc
2019-09-26T12:35:50.1561159Z     return t(*(arg + (filename,)), **kw)
2019-09-26T12:35:50.1561355Z   File "C:\hostedtoolcache\windows\Python\3.7.4\x64\lib\site-packages\datalad\core\local\tests\test_create.py", line 141, in test_create_force_subds
2019-09-26T12:35:50.1561502Z     subds.uninstall()
2019-09-26T12:35:50.1561678Z   File "C:\hostedtoolcache\windows\Python\3.7.4\x64\lib\site-packages\datalad\distribution\dataset.py", line 520, in apply_func
2019-09-26T12:35:50.1561814Z     return f(**kwargs)
2019-09-26T12:35:50.1561969Z   File "C:\hostedtoolcache\windows\Python\3.7.4\x64\lib\site-packages\datalad\interface\utils.py", line 473, in eval_func
2019-09-26T12:35:50.1562110Z     return return_func(generator_func)(*args, **kwargs)
2019-09-26T12:35:50.1562291Z   File "C:\hostedtoolcache\windows\Python\3.7.4\x64\lib\site-packages\datalad\interface\utils.py", line 461, in return_func
2019-09-26T12:35:50.1562429Z     results = list(results)
2019-09-26T12:35:50.1562613Z   File "C:\hostedtoolcache\windows\Python\3.7.4\x64\lib\site-packages\datalad\interface\utils.py", line 409, in generator_func
2019-09-26T12:35:50.1563197Z     result_renderer, result_xfm, _result_filter, **_kwargs):
2019-09-26T12:35:50.1563432Z   File "C:\hostedtoolcache\windows\Python\3.7.4\x64\lib\site-packages\datalad\interface\utils.py", line 503, in _process_results
2019-09-26T12:35:50.1563584Z     for res in results:
2019-09-26T12:35:50.1563782Z   File "C:\hostedtoolcache\windows\Python\3.7.4\x64\lib\site-packages\datalad\distribution\uninstall.py", line 165, in __call__
2019-09-26T12:35:50.1563957Z     path_is_under([ap['path']]):  # wants a sequence!
2019-09-26T12:35:50.1564161Z   File "C:\hostedtoolcache\windows\Python\3.7.4\x64\lib\site-packages\datalad\interface\utils.py", line 160, in path_is_under
2019-09-26T12:35:50.1564326Z     rpath = relpath(p, start=path)
2019-09-26T12:35:50.1564507Z   File "C:\hostedtoolcache\windows\Python\3.7.4\x64\lib\ntpath.py", line 562, in relpath
2019-09-26T12:35:50.1564649Z     path_drive, start_drive))
2019-09-26T12:35:50.1564764Z ValueError: path is on mount 'C:', start on mount 'D:'
```

it might also be specifcally `uninstall`-related. Reproducible on a real win10 system.

Haha, here is the problem:

```
> z:\code\datalad\datalad\interface\utils.py(160)path_is_under()
-> rpath = relpath(p, start=path)
(Pdb) print(p)
C:\Users\mih\AppData\Local\Temp\datalad_temp_s4hw9e26\ds- ;abc
(Pdb) print(path)
Z:\code\datalad
```

**Comment by mih** [comment]
Fixed by 396864502cedebc214d9dd0a48e44d0797d82d10
