### ISSUE TITLE
provide informative message when operating from a non-existing directory

### ISSUE THREAD

**Issue by yarikoptic** [datalad/datalad#3874]
We (git?) removes current directory whenever we `datalad remove` all files within it. Subsequent operation of datalad results in a scary tracebacks instead of a concise informative message or even doing what it was asked to do which relates to no directory (e.g. when asked for a `--version`):

```
(git-annex)lena:/tmp/testds[master]subdir
$> datalad remove --nocheck *
remove(ok): subdir/1
remove(ok): subdir/2
save(ok): /tmp/testds (dataset)
action summary:
  remove (ok: 2)
  save (ok: 1)

$> datalad --version
sh: 0: getcwd() failed: No such file or directory
Traceback (most recent call last):
  File "/home/yoh/deb/gits/python-git/git/__init__.py", line 83, in <module>
    refresh()
  File "/home/yoh/deb/gits/python-git/git/__init__.py", line 73, in refresh
    if not Git.refresh(path=path):
  File "/home/yoh/deb/gits/python-git/git/cmd.py", line 224, in refresh
    cls().version()
  File "/home/yoh/deb/gits/python-git/git/cmd.py", line 545, in <lambda>
    return lambda *args, **kwargs: self._call_process(name, *args, **kwargs)
  File "/home/yoh/deb/gits/python-git/git/cmd.py", line 1014, in _call_process
    return self.execute(call, **exec_kwargs)
  File "/home/yoh/deb/gits/python-git/git/cmd.py", line 689, in execute
    cwd = self._working_dir or os.getcwd()
FileNotFoundError: [Errno 2] No such file or directory

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/yoh/proj/datalad/datalad/venvs/dev3/bin/datalad", line 8, in <module>
    main()
  File "/home/yoh/proj/datalad/datalad/datalad/cmdline/main.py", line 441, in main
    parser = setup_parser(args)
  File "/home/yoh/proj/datalad/datalad/datalad/cmdline/main.py", line 94, in setup_parser
    from ..interface.base import dedent_docstring, get_interface_groups, \
  File "/home/yoh/proj/datalad/datalad/datalad/interface/base.py", line 33, in <module>
    from datalad.interface.common_opts import eval_params
  File "/home/yoh/proj/datalad/datalad/datalad/interface/common_opts.py", line 15, in <module>
    from datalad.interface.results import known_result_xfms
  File "/home/yoh/proj/datalad/datalad/datalad/interface/results.py", line 28, in <module>
    from datalad.distribution.dataset import Dataset
  File "/home/yoh/proj/datalad/datalad/datalad/distribution/dataset.py", line 29, in <module>
    from datalad.support.annexrepo import AnnexRepo
  File "/home/yoh/proj/datalad/datalad/datalad/support/annexrepo.py", line 43, in <module>
    from git import InvalidGitRepositoryError
  File "/home/yoh/deb/gits/python-git/git/__init__.py", line 85, in <module>
    raise ImportError('Failed to initialize: {0}'.format(exc))
ImportError: Failed to initialize: [Errno 2] No such file or directory
```

```
$> cd /tmp/testds; datalad --version
datalad 0.11.8.dev16
```
and the same with 0.12.0rc6.dev92

**Comment by mih** [comment]
The current `remove` implementation will not remove CWD (ensured by tests).
