### ISSUE TITLE
datalad get results in "not all arguments converted during string formatting"

### ISSUE THREAD

**Issue by yarikoptic** [datalad/datalad#3899]
```
$> ls -l /home/yoh/datalad/dbic/QA/sourcedata/sub-qa/ses-20180904
total 0
drwx--S--- 1 yoh yoh 158 Mar 11  2019 anat/
drwx--S--- 1 yoh yoh 194 Mar 11  2019 dwi/
drwx--S--- 1 yoh yoh 220 Mar 11  2019 func/
(dev3) 1 9433 [1].....................................:Thu 05 Dec 2019 04:39:04 PM EST:.
(git-annex)lena:/tmp/reproin.p9OBM6/data/bids[master]git-annex
$> datalad get /home/yoh/datalad/dbic/QA/sourcedata/sub-qa/ses-20180904
[ERROR  ] not all arguments converted during string formatting [utils.py:default_result_renderer:505] (TypeError) 
(dev3) 1 9434 ->1 [1].....................................:Thu 05 Dec 2019 04:39:06 PM EST:.
(git-annex)lena:/tmp/reproin.p9OBM6/data/bids[master]git-annex
$> datalad --version
datalad 0.12.0rc6.dev118
```

```
$> datalad --dbg get /home/yoh/datalad/dbic/QA/sourcedata/sub-qa/ses-20180904
Traceback (most recent call last):
  File "/home/yoh/proj/datalad/datalad-neuroimaging/venvs/dev3/bin/datalad", line 8, in <module>
    main()
  File "/home/yoh/proj/datalad/datalad-master/datalad/cmdline/main.py", line 525, in main
    ret = cmdlineargs.func(cmdlineargs)
  File "/home/yoh/proj/datalad/datalad-master/datalad/interface/base.py", line 720, in call_from_parser
    ret = list(ret)
  File "/home/yoh/proj/datalad/datalad-master/datalad/interface/utils.py", line 421, in generator_func
    result_log_level, **_kwargs):
  File "/home/yoh/proj/datalad/datalad-master/datalad/interface/utils.py", line 575, in _process_results
    default_result_renderer(res)
  File "/home/yoh/proj/datalad/datalad-master/datalad/interface/utils.py", line 505, in default_result_renderer
    if res.get('message', None) else ''))
TypeError: not all arguments converted during string formatting

> /home/yoh/proj/datalad/datalad-master/datalad/interface/utils.py(505)default_result_renderer()
-> if res.get('message', None) else ''))
(Pdb) p res
{'action': 'get', 'path': '/home/yoh/datalad/dbic/QA/sourcedata/sub-qa/ses-20180904', 'status': 'error', 'message': ('path not associated with dataset', <Dataset path=/tmp/reproin.p9OBM6/data/bids>)}
(Pdb) l
500  	                ) if 'type' in res else '',
501  	                msg=' [{}]'.format(
502  	                        res['message'][0] % res['message'][1:]
503  	                        if isinstance(res['message'], tuple) else res[
504  	                            'message'])
505  ->	                if res.get('message', None) else ''))
506  	
507  	
508  	def _process_results(
509  	        results, cmd_class,
510  	        action_summary, on_failure, incomplete_results,
```
resorting to 0.11.8 worked.

Underlying trigger is a manifestation of #3759 (trying to `get` an external to current dataset path)

**Comment by mih** [comment]
I was meaning to fix that for some time now and keep forgetting... Thx for the issue!

**Comment by mih** [comment]
Do you have the chance to run this again, and show what is in `res['message']`? Somewhere there must be an error message that has more arguments than placeholders.
