### ISSUE TITLE
Crash asking with status of dataset in dataset (not subdataset)

### ISSUE THREAD

**Issue by mih** [datalad/datalad#3900]
```
❱ datalad --dbg status -d . 966975                                                                                       1 !
Traceback (most recent call last):
  File "/usr/bin/datalad", line 8, in <module>
    main()
  File "/usr/lib/python3/dist-packages/datalad/cmdline/main.py", line 522, in main
    ret = cmdlineargs.func(cmdlineargs)
  File "/usr/lib/python3/dist-packages/datalad/interface/base.py", line 644, in call_from_parser
    ret = list(ret)
  File "/usr/lib/python3/dist-packages/datalad/interface/utils.py", line 421, in generator_func
    result_log_level, **_kwargs):
  File "/usr/lib/python3/dist-packages/datalad/interface/utils.py", line 516, in _process_results
    for res in results:
  File "/usr/lib/python3/dist-packages/datalad/core/local/status.py", line 389, in __call__
    content_info_cache):
  File "/usr/lib/python3/dist-packages/datalad/core/local/status.py", line 121, in _yield_status
    _cache=cache)
  File "/usr/lib/python3/dist-packages/datalad/support/gitrepo.py", line 3352, in diffstatus
    _cache)
  File "/usr/lib/python3/dist-packages/datalad/support/gitrepo.py", line 3388, in _diffstatus
    eval_file_type=eval_file_type)
  File "/usr/lib/python3/dist-packages/datalad/support/gitrepo.py", line 3129, in get_content_info
    submodules = [s.path for s in self.get_submodules()]
  File "/usr/lib/python3/dist-packages/datalad/support/gitrepo.py", line 2587, in get_submodules
    xs = sorted(xs, key=key)
  File "/usr/lib/python3/dist-packages/datalad/support/gitrepo.py", line 2578, in <genexpr>
    for p in xs)
KeyError: 'gitmodule_name'

> /usr/lib/python3/dist-packages/datalad/support/gitrepo.py(2578)<genexpr>()
-> for p in xs)
```

OTOH

```
❱ datalad status -d 966975                                                                                               2 !
❱ grep 966975 .gitmodules                                                                                                1 !
```

```

**Comment by mih** [comment]
So the cause was a mutilated superdataset with a submodule commit, but no .gitmodules entry. In any case, `git submodule` complains about exactly that and then exits. We should do something similar.

**Comment by adswa** [comment]
I have tried to replicate this failure by removing a subdatasets gitmodules entry in a superdataset (it should lead to the presence of a subproject commit without a .gitmodules entry as you described), but failed to produce the (any) error with a ``datalad status`` call. I suspect you might have fixed this in your rewrite of the status command. Unless someone knows a way to trigger this error, I'd propose to close it.

**Comment by bpoldrack** [comment]
Same here. No crash, just the "correct" status whether modified or not.
However, the question is whether no error/message is the right thing here. With respect to what may be there to save, the reporting is fine as is. OTOH: What other command could detect and report such an issue?

There are other potential issues with a dataset that - I think - warrant at least a special mode for `status` in order to give users the means to discover a problem. So, I tend to agree with @mih's assessment (`We should do something similar.`).
I do wonder, though, whether we should rather go for a dedicated `check` command or alike to report on potential problems with a dataset. That way there's no runtime impact on important general purpose commands, but we have a place for analyzing problems when something doesn't work properly. (And I don't think `wtf` is the right place either).
See also issues such as https://github.com/datalad/datalad/issues/7137#issuecomment-1302385177.

**Comment by mih** [comment]
Nobody could ever replicate this. Closing this issue of mine.
