### ISSUE TITLE
get_local_file_url() broken on windows (i.e. for use as annex input)

### ISSUE THREAD

**Issue by mih** [datalad/datalad#3974]
In short:

```
======================================================================
ERROR: datalad.tests.test_utils_testrepos.test_BasicAnnexTestRepo_random_location_generated
----------------------------------------------------------------------
Traceback (most recent call last):
  File "C:\Users\mih\Miniconda3\lib\site-packages\nose\case.py", line 198, in runTest
    self.test(*self.arg)
  File "C:\Users\mih\code\datalad\datalad\tests\test_utils_testrepos.py", line 42, in test_BasicAnnexTestRepo_random_location_generated
    _test_BasicAnnexTestRepo(None)  # without explicit path -- must be generated
  File "C:\Users\mih\code\datalad\datalad\tests\test_utils_testrepos.py", line 28, in _test_BasicAnnexTestRepo
    trepo.create()
  File "C:\Users\mih\code\datalad\datalad\tests\utils_testrepos.py", line 90, in create
    self.populate()
  File "C:\Users\mih\code\datalad\datalad\tests\utils_testrepos.py", line 117, in populate
    self.repo.add_url_to_file("test-annex.dat", fileurl)
  File "C:\Users\mih\code\datalad\datalad\support\gitrepo.py", line 231, in newfunc
    return func(self, file_new, *args, **kwargs)
  File "C:\Users\mih\code\datalad\datalad\support\annexrepo.py", line 1895, in add_url_to_file
    % (url, str(out_json)))
datalad.support.exceptions.CommandError: CommandError: command 'addurl'
Error, annex reported failure for addurl (url='file:///C%3A/Users/mih/AppData/Local/Temp/datalad_temp_testrepo_fpl3aaoz'): {'command': 'addurl', 'success': False, 'error-messages': ['  download failed: /C:/Users/mih/AppData/Local/Temp/datalad_temp_testrepo_fpl3aaoz: openBinaryFile: invalid argument (Invalid argument)'], 'file': 'test-annex.dat'}
```

This function is used at the core of the testrepo setup, hence its breakage is a key reason for the disfunctionality of a large part of our test battery on windows.

It took me forever to find this, because the tests that cover it were disabled 4 years ago https://github.com/datalad/datalad/commit/c53298e46e3cf64d3b3294758aaeeb2f2b3d28c5

It is not clear to me how a working `file://` URL could look like. According to https://en.wikipedia.org/wiki/File_URI_scheme#Windows it is not too far off. Maybe just one slash less would do it. But I cannot seem to make anything work with git-annex directly:

```
> git -c annex.security.allowed-url-schemes=file annex addurl file://./c:/Windows/clock.avi
addurl file://./c:/Windows/clock.avi

  download failed: /c:/Windows/clock.avi: openBinaryFile: invalid argument (Invalid argument)
failed
git-annex: addurl: 1 failed

>git -c annex.security.allowed-url-schemes=file annex addurl file://c$/Windows/clock.avi
addurl file://c$/Windows/clock.avi

  download failed: /Windows/clock.avi: openBinaryFile: does not exist (No such file or directory)
failed
git-annex: addurl: 1 failed

>git -c annex.security.allowed-url-schemes=file annex addurl file:///c$/Windows/clock.avi
addurl file:///c$/Windows/clock.avi

  download failed: /c$/Windows/clock.avi: openBinaryFile: does not exist (No such file or directory)
failed
git-annex: addurl: 1 failed

>git -c annex.security.allowed-url-schemes=file annex addurl file://localhost/c$/Windows/clock.avi
addurl file://localhost/c$/Windows/clock.avi

  download failed: /c$/Windows/clock.avi: openBinaryFile: does not exist (No such file or directory)
failed
git-annex: addurl: 1 failed

>git -c annex.security.allowed-url-schemes=file annex addurl file://localhost/c:/Windows/clock.avi
addurl file://localhost/c:/Windows/clock.avi

  download failed: /c:/Windows/clock.avi: openBinaryFile: invalid argument (Invalid argument)
failed
git-annex: addurl: 1 failed
```

**Comment by mih** [comment]
OK, figured it out:

```
(base) C:\Users\mih\code\datalad\this>git -c annex.security.allowed-url-schemes=file annex addurl file:///Windows/Notepad.exe
addurl file:///Windows/Notepad.exe
(to _Windows_Notepad.exe) ok
(recording state in git...)

(base) C:\Users\mih\code\datalad\this>git -c annex.security.allowed-url-schemes=file annex addurl file://C/Windows/Notepad.exe
addurl file://C/Windows/Notepad.exe
(to C_Windows_Notepad.exe) ok
(recording state in git...)
```

i.e. tripple-slash when no drive letter, double-slash otherwise, and no colons
