### ISSUE TITLE
test_ls_webui.test_ls_json observed to fail with more recent git and/or git-annex

### ISSUE THREAD

**Issue by kyleam** [datalad/datalad#3984]
This is split off from gh-3890.  The failure was initially observed with git-annex 7.20191114+git43-ge29663773.  As mentioned at gh-3890, the failure appears to be flaky on Travis, I haven't been able to trigger this locally, and it may be specific to 0.11.x.

```
======================================================================
ERROR: datalad.interface.tests.test_ls_webui.test_ls_json
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/travis/virtualenv/python2.7.15/lib/python2.7/site-packages/nose/case.py", line 197, in runTest
    self.test(*self.arg)
  File "/home/travis/virtualenv/python2.7.15/lib/python2.7/site-packages/datalad/tests/utils.py", line 442, in newfunc
    return t(*(arg + (d,)), **kw)
  File "/home/travis/virtualenv/python2.7.15/lib/python2.7/site-packages/datalad/tests/utils.py", line 554, in newfunc
    return tfunc(*(args + (path, url)), **kwargs)
  File "/home/travis/virtualenv/python2.7.15/lib/python2.7/site-packages/datalad/interface/tests/test_ls_webui.py", line 173, in test_ls_json
    ds.add(opj('dir', 'subgit'))                        # add the non-dataset git repo to annex
  File "/home/travis/virtualenv/python2.7.15/lib/python2.7/site-packages/datalad/distribution/dataset.py", line 527, in apply_func
    return f(**kwargs)
  File "/home/travis/virtualenv/python2.7.15/lib/python2.7/site-packages/datalad/interface/utils.py", line 499, in eval_func
    return return_func(generator_func)(*args, **kwargs)
  File "/home/travis/virtualenv/python2.7.15/lib/python2.7/site-packages/datalad/interface/utils.py", line 487, in return_func
    results = list(results)
  File "/home/travis/virtualenv/python2.7.15/lib/python2.7/site-packages/datalad/interface/utils.py", line 474, in generator_func
    msg="Command did not complete successfully")
IncompleteResultsError: Command did not complete successfully [{'status': u'error', 'orig_request': u'dir/subgit', 'message': u"'dir/subgit' already exists in the index\n", 'raw_input': True, 'parentds': u'/tmp/datalad_temp_tree_test_ls_jsonlkIb3R', 'action': u'add', 'path': u'/tmp/datalad_temp_tree_test_ls_jsonlkIb3R/dir/subgit', 'type': u'dataset', 'refds': u'/tmp/datalad_temp_tree_test_ls_jsonlkIb3R'}]
```

**Comment by kyleam** [comment]
On the [latest][0] git-annex -devel run, this test was the cause of all of the failing builds (7).

[0]: https://travis-ci.org/datalad/datalad/builds/632550925

**Comment by mih** [comment]
We no longer support or run PY2.
