### ISSUE TITLE
test_partial_aggregation observed to fail with more recent git and/or git-annex

### ISSUE THREAD

**Issue by kyleam** [datalad/datalad#3985]
This is split off from gh-3890. The failure was initially observed with git-annex 7.20191114+git43-ge29663773. As mentioned at gh-3890, the failure appears to be flaky on Travis, and, after having brief initial luck triggering it locally, I haven't been able to.

```
======================================================================
FAIL: datalad.metadata.tests.test_aggregation.test_partial_aggregation
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/travis/virtualenv/python2.7.15/lib/python2.7/site-packages/nose/case.py", line 197, in runTest
    self.test(*self.arg)
  File "/home/travis/virtualenv/python2.7.15/lib/python2.7/site-packages/datalad/tests/utils.py", line 442, in newfunc
    return t(*(arg + (d,)), **kw)
  File "/home/travis/virtualenv/python2.7.15/lib/python2.7/site-packages/datalad/metadata/tests/test_aggregation.py", line 403, in test_partial_aggregation
    ok_clean_git(path)
  File "/home/travis/virtualenv/python2.7.15/lib/python2.7/site-packages/datalad/tests/utils.py", line 211, in ok_clean_git
    eq_(index_diffs, [])
AssertionError: ['sub1\n=======================================================\nlhs: 160000 | 1f25e78d89a958ce5c0cdd0f31b6da24a6ca586a\nrhs: 160000 | 1f25e78d89a958ce5c0cdd0f31b6da24a6ca586a'] != []
```

**Comment by kyleam** [comment]
This failure didn't show up on the [latest][0] git-annex -devel run for 0.11.x, but, given that it appears to be flaky, that might not mean much.

[0]: https://travis-ci.org/datalad/datalad/builds/632550925

**Comment by kyleam** [comment]
If this pops up again, this will be easy enough to locate with a search.
