### ISSUE TITLE
add-archive-content crashed with --key and no --use-current-dir

### ISSUE THREAD

**Issue by mih** [datalad/datalad#3995]
Documentation of `--use-current-dir` says:

> Note that it will be of no effect if --key is given.

which I understand and interpret as: need not give that option with --key

But:

```
% datalad --dbg add-archive-content --allow-dirty --key MD5E-s52672588--4fb54d6d47783b3f2c279e8e57dbbd8e.zip
Traceback (most recent call last):
  File "/usr/bin/datalad", line 8, in <module>
    main()
  File "/usr/lib/python3/dist-packages/datalad/cmdline/main.py", line 522, in main
    ret = cmdlineargs.func(cmdlineargs)
  File "/usr/lib/python3/dist-packages/datalad/interface/base.py", line 642, in call_from_parser
    ret = cls.__call__(**kwargs)
  File "/usr/lib/python3/dist-packages/datalad/interface/add_archive_content.py", line 277, in __call__
    extract_rpath = relpath(archive_dir, annex_path)
  File "/usr/lib/python3.7/posixpath.py", line 457, in relpath
    raise ValueError("no path specified")
ValueError: no path specified

> /usr/lib/python3.7/posixpath.py(457)relpath()
-> raise ValueError("no path specified")
(Pdb) u
> /usr/lib/python3/dist-packages/datalad/interface/add_archive_content.py(277)__call__()
-> extract_rpath = relpath(archive_dir, annex_path)
(Pdb) archive_dir
(Pdb) 
```

whereas:

```
% datalad --dbg add-archive-content --use-current-dir --allow-dirty --key MD5E-s52672588--4fb54d6d47783b3f2c279e8e57dbbd8e.zip
[INFO   ] Adding content of the archive MD5E-s52672588--4fb54d6d47783b3f2c279e8e57dbbd8e.zip into annex <AnnexRepo path=/data/project/rehab_biobank/datalad_trial/1008788 (<class 'datalad.support.annexrepo.AnnexRepo'>)> 
[INFO   ] Initiating special remote datalad-archives 
[INFO   ] Finished adding MD5E-s52672588--4fb54d6d47783b3f2c279e8e57dbbd8e.zip: Files processed: 45, +annex: 45 
```

**Comment by mih** [comment]
FTR: With https://github.com/datalad/datalad-ukbiobank/pull/20 some code now relies on the assumption that `--use-current-dir` continues to work even with `--key`, like it does at the moment.
