### ISSUE TITLE
test_diff_nonexistent_ref_unicode: ERRORS while building debian pkg with python 3.5, 3.6

### ISSUE THREAD

**Issue by yarikoptic** [datalad/datalad#4016]
```
======================================================================
ERROR: datalad.core.local.tests.test_diff.test_diff_nonexistent_ref_unicode
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/nose/case.py", line 198, in runTest
    self.test(*self.arg)
  File "/build/datalad-0.12.0/.pybuild/pythonX.Y_3.5/build/datalad/tests/utils.py", line 732, in newfunc
    return t(*(arg + (filename,)), **kw)
  File "/build/datalad-0.12.0/.pybuild/pythonX.Y_3.5/build/datalad/core/local/tests/test_diff.py", line 480, in test_diff_nonexistent_ref_unicode
    ds.diff(fr="HEAD", to=u"\u03b2", on_failure="ignore"),
  File "/usr/lib/python3/dist-packages/wrapt/wrappers.py", line 557, in __call__
    args, kwargs)
  File "/build/datalad-0.12.0/.pybuild/pythonX.Y_3.5/build/datalad/distribution/dataset.py", line 500, in apply_func
    return f(**kwargs)
  File "/usr/lib/python3/dist-packages/wrapt/wrappers.py", line 518, in __call__
    args, kwargs)
  File "/build/datalad-0.12.0/.pybuild/pythonX.Y_3.5/build/datalad/interface/utils.py", line 493, in eval_func
    return return_func(generator_func)(*args, **kwargs)
  File "/usr/lib/python3/dist-packages/wrapt/wrappers.py", line 518, in __call__
    args, kwargs)
  File "/build/datalad-0.12.0/.pybuild/pythonX.Y_3.5/build/datalad/interface/utils.py", line 481, in return_func
    results = list(results)
  File "/build/datalad-0.12.0/.pybuild/pythonX.Y_3.5/build/datalad/interface/utils.py", line 412, in generator_func
    allkwargs):
  File "/build/datalad-0.12.0/.pybuild/pythonX.Y_3.5/build/datalad/interface/utils.py", line 528, in _process_results
    for res in results:
  File "/build/datalad-0.12.0/.pybuild/pythonX.Y_3.5/build/datalad/core/local/diff.py", line 125, in __call__
    recursion_limit=recursion_limit):
  File "/build/datalad-0.12.0/.pybuild/pythonX.Y_3.5/build/datalad/core/local/diff.py", line 220, in _diff_cmd
    cache=content_info_cache):
  File "/build/datalad-0.12.0/.pybuild/pythonX.Y_3.5/build/datalad/core/local/diff.py", line 254, in _diff_ds
    _cache=cache)
  File "/build/datalad-0.12.0/.pybuild/pythonX.Y_3.5/build/datalad/support/gitrepo.py", line 3438, in diffstatus
    _cache)
  File "/build/datalad-0.12.0/.pybuild/pythonX.Y_3.5/build/datalad/support/gitrepo.py", line 3496, in _diffstatus
    paths=paths, ref=to, eval_file_type=eval_file_type)
  File "/build/datalad-0.12.0/.pybuild/pythonX.Y_3.5/build/datalad/support/gitrepo.py", line 3234, in get_content_info
    expect_fail=True)
  File "/build/datalad-0.12.0/.pybuild/pythonX.Y_3.5/build/datalad/support/gitrepo.py", line 316, in newfunc
    result = func(self, files_new, *args, **kwargs)
  File "/build/datalad-0.12.0/.pybuild/pythonX.Y_3.5/build/datalad/support/gitrepo.py", line 1901, in _git_custom_command
    expect_fail=expect_fail)
  File "/build/datalad-0.12.0/.pybuild/pythonX.Y_3.5/build/datalad/support/gitrepo.py", line 1938, in _run_command_files_split
    *args, **kwargs)
  File "/build/datalad-0.12.0/.pybuild/pythonX.Y_3.5/build/datalad/cmd.py", line 712, in run
    cmd, env=self.get_git_environ_adjusted(env), *args, **kwargs)
  File "/build/datalad-0.12.0/.pybuild/pythonX.Y_3.5/build/datalad/cmd.py", line 500, in run
    stdin=stdin)
  File "/usr/lib/python3.5/subprocess.py", line 676, in __init__
    restore_signals, start_new_session)
  File "/usr/lib/python3.5/subprocess.py", line 1221, in _execute_child
    restore_signals, start_new_session, preexec_fn)
UnicodeEncodeError: 'ascii' codec can't encode character '\u03b2' in position 0: ordinal not in range(128)
```

```
neurodebian@smaug ~/deb/builds/datalad/0.12.0-1 % cat summary.build                     
datalad_0.12.0-1_amd64.build    OK      51:28.15 real, 1824.03 user, 1448.72 sys, 4318992 out
datalad_0.12.0-1~nd80+1_amd64.build     FAILED  0:18.25 real, 13.63 user, 5.78 sys, 115368 out
datalad_0.12.0-1~nd90+1_amd64.build     FAILED  41:28.75 real, 1605.39 user, 1125.86 sys, 2723728 out
datalad_0.12.0-1~nd100+1_amd64.build    OK      44:49.82 real, 1690.86 user, 1238.54 sys, 2700400 out
datalad_0.12.0-1~nd110+1_amd64.build    OK      54:15.90 real, 1915.71 user, 1566.35 sys, 4334712 out
datalad_0.12.0-1~nd+1_amd64.build       OK      55:13.25 real, 1902.11 user, 1649.83 sys, 4315144 out
datalad_0.12.0-1~nd14.04+1_amd64.build  FAILED  0:55.49 real, 41.65 user, 18.15 sys, 120600 out
datalad_0.12.0-1~nd16.04+1_amd64.build  FAILED  0:53.74 real, 40.31 user, 17.98 sys, 131376 out
datalad_0.12.0-1~nd18.04+1_amd64.build  FAILED  46:31.40 real, 1751.63 user, 1288.82 sys, 2780080 out
datalad_0.12.0-1~nd18.10+1_amd64.build  FAILED  1:28:51 real, 3366.78 user, 2450.43 sys, 4186056 out
datalad_0.12.0-1~nd19.04+1_amd64.build  OK      46:07.81 real, 1717.38 user, 1295.20 sys, 2715680 out
```
and we have python before 3.7 there:
```
neurodebian@smaug ~/deb/builds/datalad/0.12.0-1 % grep -B2 'codec can.t encode character' *build
datalad_0.12.0-1~nd18.04+1_amd64.build-  File "/usr/lib/python3.6/subprocess.py", line 1275, in _execute_child
datalad_0.12.0-1~nd18.04+1_amd64.build-    restore_signals, start_new_session, preexec_fn)
datalad_0.12.0-1~nd18.04+1_amd64.build:UnicodeEncodeError: 'ascii' codec can't encode character '\u03b2' in position 0: ordinal not in range(128)
--
datalad_0.12.0-1~nd18.10+1_amd64.build-  File "/usr/lib/python3.6/subprocess.py", line 1275, in _execute_child
datalad_0.12.0-1~nd18.10+1_amd64.build-    restore_signals, start_new_session, preexec_fn)
datalad_0.12.0-1~nd18.10+1_amd64.build:UnicodeEncodeError: 'ascii' codec can't encode character '\u03b2' in position 0: ordinal not in range(128)
--
datalad_0.12.0-1~nd90+1_amd64.build-  File "/usr/lib/python3.5/subprocess.py", line 1221, in _execute_child
datalad_0.12.0-1~nd90+1_amd64.build-    restore_signals, start_new_session, preexec_fn)
datalad_0.12.0-1~nd90+1_amd64.build:UnicodeEncodeError: 'ascii' codec can't encode character '\u03b2' in position 0: ordinal not in range(128)
```
full build logs at http://neuro.debian.net/_files/_buildlogs/datalad/0.12.0

**Comment by mih** [comment]
The patch series already disable unicode-related tests. I guess we should just extend it?

**Comment by yarikoptic** [comment]
may be, at least as a quick and dirty fix. interestingly it seems to not fail with python3.7 (debian unstable/stable). I guess many of those disabled might also pass there now

**Comment by yarikoptic** [comment]
uploaded 0.12.1-1 with adjusted patch to not use unicode if python `< 3.7`. Current success status
```
neurodebian@smaug ~/deb/builds/datalad/0.12.1-1 % cat summary.build 
datalad_0.12.1-1_amd64.build	OK	54:41.89 real, 1920.30 user, 1593.42 sys, 4299960 out
datalad_0.12.1-1~nd80+1_amd64.build	FAILED	0:19.27 real, 14.51 user, 5.95 sys, 115464 out
datalad_0.12.1-1~nd90+1_amd64.build	OK	44:40.73 real, 1668.56 user, 1281.49 sys, 2619016 out
datalad_0.12.1-1~nd100+1_amd64.build	OK	45:22.78 real, 1677.59 user, 1278.79 sys, 2676608 out
datalad_0.12.1-1~nd110+1_amd64.build	OK	55:21.98 real, 1906.28 user, 1662.36 sys, 4314968 out
datalad_0.12.1-1~nd+1_amd64.build	OK	54:57.56 real, 1914.38 user, 1633.00 sys, 4320720 out
datalad_0.12.1-1~nd14.04+1_amd64.build	FAILED	0:58.49 real, 43.05 user, 20.08 sys, 120656 out
datalad_0.12.1-1~nd16.04+1_amd64.build	FAILED	0:54.04 real, 40.36 user, 18.40 sys, 131464 out
datalad_0.12.1-1~nd18.04+1_amd64.build	OK	47:03.77 real, 1767.94 user, 1301.85 sys, 2673480 out
datalad_0.12.1-1~nd18.10+1_amd64.build	OK	1:30:31 real, 3374.70 user, 2543.67 sys, 4224192 out
datalad_0.12.1-1~nd19.04+1_amd64.build	OK	45:25.87 real, 1724.57 user, 1240.64 sys, 2694112 out
```
