### ISSUE TITLE
Datalad swallows `git-clone` errors

### ISSUE THREAD

**Issue by mih** [datalad/datalad#4038]
Found in gh-4036, and affects gh-4035

Here is an investigation using a scenario where `clone --branch` is used, hence we can see errors that are not due to the actual clone stage, but happen during post-processing. The demo is in the context of #4036, where we can instruct `datalad clone` to obtain a specific version of a dataset.
We try to obtain a version that actually doesn't exist in order to provoke an error.

#### Datalad

```
% datalad clone "ria+http://127.0.0.1:41207/#33c2e000-38fa-11ea-aa8f-f0d5bf7b5561@impossible"
[ERROR  ] Failed to clone from all attempted sources: ['http://127.0.0.1:41207/33c/2e000-38fa-11ea-aa8f-f0d5bf7b5561', 'http://127.0.0.1:41207/33c/2e000-38fa-11ea-aa8f-f0d5bf7b5561/.git'] [install(/tmp/33c2e000-38fa-11ea-aa8f-f0d5bf7b5561)] 
install(error): /tmp/33c2e000-38fa-11ea-aa8f-f0d5bf7b5561 (dataset) [Failed to clone from all attempted sources: ['http://127.0.0.1:41207/33c/2e000-38fa-11ea-aa8f-f0d5bf7b5561', 'http://127.0.0.1:41207/33c/2e000-38fa-11ea-aa8f-f0d5bf7b5561/.git']]
```

If we ignore the pointless double-reporting, we see that the error is wrong. The clone worked just fine, but the checkout failed. I would expect `git-clone` to be more clever, and just say it like it is.

#### Git

Turns out it is
```
% git clone --branch impossible http://127.0.0.1:41207/33c/2e000-38fa-11ea-aa8f-f0d5bf7b5561
Cloning into '2e000-38fa-11ea-aa8f-f0d5bf7b5561'...
fatal: Remote branch impossible not found in upstream origin
```

#### DataLad GitRepo

```
(Pdb) GitRepo.clone(url='http://127.0.0.1:41207/33c/2e000-38fa-11ea-aa8f-f0d5bf7b5561', path='/tmp/broken', create=True, clone_options={'branch': 'impossible'})
[DEBUG  ] Git clone from http://127.0.0.1:41207/33c/2e000-38fa-11ea-aa8f-f0d5bf7b5561 to /tmp/broken 
[DEBUG  ] HTTP: "GET /33c/2e000-38fa-11ea-aa8f-f0d5bf7b5561/info/refs?service=git-upload-pack HTTP/1.1" 200 - 
[DEBUG  ] HTTP: "GET /33c/2e000-38fa-11ea-aa8f-f0d5bf7b5561/HEAD HTTP/1.1" 200 - 
*** git.exc.GitCommandError: Cmd('/usr/bin/git') failed due to: exit code(128)
  cmdline: /usr/bin/git clone --progress -v --branch=impossible http://127.0.0.1:41207/33c/2e000-38fa-11ea-aa8f-f0d5bf7b5561 /tmp/broken
```

#### GitPy

Also reveals the issue, but does not seem to include the critical information in the exception

```
(Pdb) gitpy.Repo.clone_from('http://127.0.0.1:32771/2bd/222e6-38fc-11ea-a876-f0d5bf7b5561', '/tmp/broken', multi_options=['--branch=impossible'])
[DEBUG  ] HTTP: "GET /2bd/222e6-38fc-11ea-a876-f0d5bf7b5561/info/refs?service=git-upload-pack HTTP/1.1" 200 - 
[DEBUG  ] HTTP: "GET /2bd/222e6-38fc-11ea-a876-f0d5bf7b5561/HEAD HTTP/1.1" 200 - 
*** git.exc.GitCommandError: Cmd('/usr/bin/git') failed due to: exit code(128)
  cmdline: /usr/bin/git clone -v --branch=impossible http://127.0.0.1:32771/2bd/222e6-38fc-11ea-a876-f0d5bf7b5561 /tmp/broken
  stderr: 'Cloning into '/tmp/broken'...
fatal: Remote branch impossible not found in upstream origin
...

-> e_str = exc_str(e)
(Pdb) e.stderr
''
(Pdb) e.stdout
''
(Pdb) e.status
128
(Pdb) str(e)
"Cmd('/usr/bin/git') failed due to: exit code(128)\n  cmdline: /usr/bin/git clone --progress -v http://127.0.0.1:38771/a23/42448-38fc-11ea-a812-f0d5bf7b5561/subdir/subds /tmp/datalad_temp_tree_test_ria_httph0n4roy6/clone/subdir/subds"
```

Possibly the progress reporting makes the output vanish

```
(Pdb) git_progress = GitPythonProgressBar("Cloning")
(Pdb) gitpy.Repo.clone_from('http://127.0.0.1:38771/a23/42448-38fc-11ea-a812-f0d5bf7b5561', '/tmp/broken', multi_options=['--branch=impossible'], progress=git_progress)
[DEBUG  ] HTTP: "GET /a23/42448-38fc-11ea-a812-f0d5bf7b5561/info/refs?service=git-upload-pack HTTP/1.1" 200 - 
[DEBUG  ] HTTP: "GET /a23/42448-38fc-11ea-a812-f0d5bf7b5561/HEAD HTTP/1.1" 200 - 
*** git.exc.GitCommandError: Cmd('/usr/bin/git') failed due to: exit code(128)
  cmdline: /usr/bin/git clone --progress -v --branch=impossible http://127.0.0.1:38771/a23/42448-38fc-11ea-a812-f0d5bf7b5561 /tmp/broken
```

Seems to be the case :(
But it is not git's fault:

```
% /usr/bin/git clone --progress -v --branch=impossible http://127.0.0.1:38771/a23/42448-38fc-11ea-a812-f0d5bf7b5561 /tmp/broken

Cloning into '/tmp/broken'...
fatal: Remote branch impossible not found in upstream origin
```

@bpoldrack points out that this line may give a hint on where we are discarding this information
https://github.com/datalad/datalad/blame/master/datalad/support/gitrepo.py#L480/datalad/datalad/commit/0610dda16d4181d2525af0f5dd90c4da370ed840

**Comment by kyleam** [comment]
Thanks for writing up the details.  Just yesterday I began looking into `GitRepo.fetch` dropping some information.  I wonder if this will end up being the same source.

<details>
<summary>dropped fetch output</summary>

When fetching with the default `--recurse-submodules` behavior, `git fetch` and `repo.git.fetch` clearly report the "Fetching submodule sub" output, which makes it clear that the failure below pertains to it.  `GitRepo.fetch` drops that line.

```sh
#!/bin/sh

set -eu

quiet_git () {
    git "$@" >/dev/null 2>&1
}

run () {
    (
        cd "$(mktemp -d --tmpdir dl-XXXXXXX)"
        quiet_git init a
        quiet_git init a/sub
        quiet_git -C a/sub commit --allow-empty -mc1
        quiet_git -C a submodule add ./sub sub
        quiet_git -C a commit -m"add sub"

        quiet_git clone --recurse-submodules -o rem a b
        quiet_git -C b/sub remote rename origin rem

        quiet_git -C a/sub commit --allow-empty -mc2
        quiet_git -C a commit -a -m"change sub"
        echo "# $@"
        "$@" || true
        echo
        echo
    )
}

run git -C b fetch
run python -c "from datalad.support.gitrepo import GitRepo; GitRepo('b').fetch()"
run python -c "from datalad.support.gitrepo import GitRepo; GitRepo('b').repo.git.fetch()"
```

```
# git -C b fetch
From /tmp/dl-jdxpgG8/a
   7e402ad..ef618aa  master     -> rem/master
Fetching submodule sub
fatal: 'origin' does not appear to be a git repository
fatal: Could not read from remote repository.

Please make sure you have the correct access rights
and the repository exists.


# python -c from datalad.support.gitrepo import GitRepo; GitRepo('b').fetch()
Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "/home/kyle/src/python/datalad/datalad/support/gitrepo.py", line 412, in wrapped
    return func(repo, *args, **kwargs)
  File "/home/kyle/src/python/datalad/datalad/support/gitrepo.py", line 2174, in fetch
    **kwargs
  File "/home/kyle/src/python/datalad/datalad/support/gitrepo.py", line 2203, in _call_gitpy_with_progress
    ret = callable(**git_kwargs)
  File "/home/kyle/src/python/gitpython/git/remote.py", line 792, in fetch
    res = self._get_fetch_info_from_stderr(proc, progress)
  File "/home/kyle/src/python/gitpython/git/remote.py", line 676, in _get_fetch_info_from_stderr
    proc.wait(stderr=stderr_text)
  File "/home/kyle/src/python/gitpython/git/cmd.py", line 417, in wait
    raise GitCommandError(self.args, status, errstr)
git.exc.GitCommandError: Cmd('git') failed due to: exit code(1)
  cmdline: git fetch --progress -v rem refs/heads/master
  stderr: 'fatal: 'origin' does not appear to be a git repository
fatal: Could not read from remote repository.

Please make sure you have the correct access rights
and the repository exists.'


# python -c from datalad.support.gitrepo import GitRepo; GitRepo('b').repo.git.fetch()
Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "/home/kyle/src/python/gitpython/git/cmd.py", line 551, in <lambda>
    return lambda *args, **kwargs: self._call_process(name, *args, **kwargs)
  File "/home/kyle/src/python/gitpython/git/cmd.py", line 1020, in _call_process
    return self.execute(call, **exec_kwargs)
  File "/home/kyle/src/python/gitpython/git/cmd.py", line 831, in execute
    raise GitCommandError(command, status, stderr_value, stdout_value)
git.exc.GitCommandError: Cmd('git') failed due to: exit code(1)
  cmdline: git fetch
  stderr: 'From /tmp/dl-HQ2rgKp/a
   c229c39..d51c642  master     -> rem/master
Fetching submodule sub
fatal: 'origin' does not appear to be a git repository
fatal: Could not read from remote repository.

Please make sure you have the correct access rights
and the repository exists.'


```

</details>

**Comment by kyleam** [comment]
I've looked into this and pinpointed where it's being dropped.  I'll put together a PR later today.

**Comment by mih** [comment]
Wonderful!

**Comment by kyleam** [comment]
I said:

> I began looking into `GitRepo.fetch` dropping some information. I wonder if this will end up being the same source.

So, this is kind of the same source, but the fix would be more involved.  GitPython's `RemoteProgress` has a helper (`_parse_progress_line`) that looks at the stderr and decides what to do with it.  Its logic boils down to

  * if it looks like an error line (starts with "fatal:" or "error:"), store it in `.error_lines` and process all remaining lines as error lines
  * if it looks like a progress line from git, do the progress thing
  * otherwise, store it in `.other_lines`

`.other lines` is where "Fetching submodule sub" ends up.

I think this approach is pretty unfortunate.  There is so much important information that could be lost.  In the fetch case I show, the "Fetch submodule" line is crucial to understanding the error.  And even if the caller looks at `.other_lines`, they don't know where that line came relative to the error line.

My impression is that resolving it would involve either substantial changes on GitPython's end or large amounts of re-implementation and/or kludges on our end.  Given that our eventual goal is to remove the use of GitPython, our efforts are probably better spent trying to do that, a large part of which is figuring out how to handle progress reporting in clone/fetch/push.  (In other words, it seems silly to spend time to build on top of GitPython if we're just going to turn around an spend time figuring out how to do it another way.)

**Comment by mih** [comment]
@kyleam I agree with your assessment. Given that I have no practical experience with the problem, I am wondering though, what approach would work for us? We need to capture `stderr` to report on errors in a structured way. But if filtering `stderr` to separate progress info from error messages, can't we just let `stderr` send back to `stderr` in "CC", i.e. expose `git-clone`s native talk?
