### ISSUE TITLE
problem with super-fresh git 2.8.1+next.20160414: refusing to merge unrelated histories

### ISSUE THREAD

**Issue by yarikoptic** [datalad/datalad#406]
works with 2.8.1 but fails with the one available from debian experimental
```
$> git --version
git version 2.8.1.369.geae769a

$> nosetests -s -v datalad/tests/test_gitrepo.py:test_GitRepo_get_merge_base
datalad.tests.test_gitrepo.test_GitRepo_get_merge_base ... 2016-04-21 11:39:37,971 [ERROR  ] stderr| fatal: refusing to merge unrelated histories (cmd.py:351)
2016-04-21 11:39:37,972 [ERROR  ] Failed to run ['git', '-c', 'receive.autogc=0', '-c', 'gc.auto=0', 'merge', 'master'] under '/tmp/datalad_temp_test_GitRepo_get_merge_baseb1i8gl'. Exit code=128. out= err=fatal: refusing to merge unrelated histories
|  (cmd.py:295)
ERROR

======================================================================
ERROR: datalad.tests.test_gitrepo.test_GitRepo_get_merge_base
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/yoh/proj/datalad/datalad/venv-tests/local/lib/python2.7/site-packages/nose/case.py", line 197, in runTest
    self.test(*self.arg)
  File "/home/yoh/proj/datalad/datalad/datalad/tests/utils.py", line 455, in newfunc
    return t(*(arg + (filename,)), **kw)
  File "/home/yoh/proj/datalad/datalad/datalad/tests/test_gitrepo.py", line 548, in test_GitRepo_get_merge_base
    repo.git_merge(branch1)
  File "/home/yoh/proj/datalad/datalad/datalad/support/gitrepo.py", line 759, in git_merge
    self._git_custom_command('', ['git', 'merge'] + options + [name], **kwargs)
  File "/home/yoh/proj/datalad/datalad/datalad/support/gitrepo.py", line 206, in newfunc
    result = func(self, files_new, *args, **kwargs)
  File "/home/yoh/proj/datalad/datalad/datalad/support/gitrepo.py", line 636, in _git_custom_command
    env=env, shell=shell, expect_fail=expect_fail)
  File "/home/yoh/proj/datalad/datalad/datalad/cmd.py", line 296, in run
    raise CommandError(str(cmd), msg, status, out[0], out[1])
CommandError: CommandError: command '['git', '-c', 'receive.autogc=0', '-c', 'gc.auto=0', 'merge', 'master']' failed with exitcode 128.
Failed to run ['git', '-c', 'receive.autogc=0', '-c', 'gc.auto=0', 'merge', 'master'] under '/tmp/datalad_temp_test_GitRepo_get_merge_baseb1i8gl'. Exit code=128. out= err=fatal: refusing to merge unrelated histories

-------------------- >> begin captured logging << --------------------
datalad.cmd: ERROR  : stderr| fatal: refusing to merge unrelated histories
datalad.cmd: ERROR  : Failed to run ['git', '-c', 'receive.autogc=0', '-c', 'gc.auto=0', 'merge', 'master'] under '/tmp/datalad_temp_test_GitRepo_get_merge_baseb1i8gl'. Exit code=128. out= err=fatal: refusing to merge unrelated histories
| 
--------------------- >> end captured logging << ---------------------

----------------------------------------------------------------------
Ran 1 test in 0.083s

FAILED (errors=1)
```

inquiring with git folks atm either it is a feature or a regression

**Comment by yarikoptic** [comment]
ok -- seems to be intentional:  https://github.com/git/git/pull/158/commits/e379fdf34fee96cd205be83ff4e71699bdc32b18  so we would need to use `--allow-unrelated-histories` for such merges (or just always, but then depending on git version etc.... bleh), apparently it is explicitly stated that "no configuration variable to enable this by default exists and will not be added"... so -- what should we do? we relied on this feature in quite a few spots... I will whine on git mailing list then

**Comment by yarikoptic** [comment]
http://thread.gmane.org/gmane.comp.version-control.git/292145  is supposed to address it but we would need to use an env variable to allow for such "evil" merges ;)  Close whenever git accepts the patch and we add use of the variable

**Comment by yarikoptic** [comment]
I think this issue was addressed

**Comment by bingbings** [comment]
I want to change the version.

**Comment by yarikoptic** [comment]
version of what and where @bingbings ?

**Comment by bingbings** [comment]
I use the git 2.7.2 windows x64 
here: http://pan.baidu.com/s/1kTTGgPh
