### ISSUE TITLE
circular imports caused by spreading around "interface" components

### ISSUE THREAD

**Issue by yarikoptic** [datalad/datalad#408]
not sure how it works somewhat really but there is a problem... may be that idea wasn't as good as straightforward it seemed ;)
`interfaces/__init__.py`  imports (non-lazily, which was one of my whinings at some point) all the Interface subclasses from all around, which in turn import `interfaces/base.py` to get the base `Interface` class which causes circular import of `interfaces/__init__.py`:

```
$> python -c 'import datalad.distribution.add_sibling'
Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "datalad/distribution/add_sibling.py", line 22, in <module>
    from ..interface.base import Interface
  File "datalad/interface/__init__.py", line 30, in <module>
    from ..distribution.add_sibling import AddSibling
ImportError: cannot import name AddSibling
()
> /home/yoh/proj/datalad/datalad/datalad/interface/__init__.py(30)<module>()
-> from ..distribution.add_sibling import AddSibling
(Pdb) 
```

possible resolutions
1. move Interface out of interfaces/
2. move all the imports from `interfaces/__init__.py` back into `api.py`
3. anything better?

assigning to the Interfaces guru, but might tackle it myself or may be @bpoldrack would resolve it before then.

**Comment by yarikoptic** [comment]
was actually fixed by #415
