### ISSUE TITLE
failing test_archives.test_ExtractedArchive of 0.12.2 on NFS mount

### ISSUE THREAD

**Issue by yarikoptic** [datalad/datalad#4101]
https://travis-ci.org/datalad/datalad/jobs/642979829?utm_medium=notification&utm_source=email
building state as of debian pkg for the release
https://travis-ci.org/datalad/datalad/builds/642979821?utm_medium=notification&utm_source=email :
```
======================================================================
FAIL: datalad.tests.test_archives.test_ExtractedArchive
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/travis/virtualenv/python3.5.6/lib/python3.5/site-packages/nose/case.py", line 198, in runTest
    self.test(*self.arg)
  File "/home/travis/virtualenv/python3.5.6/lib/python3.5/site-packages/datalad/tests/utils.py", line 559, in newfunc
    return t(*(arg + (d,)), **kw)
  File "/home/travis/virtualenv/python3.5.6/lib/python3.5/site-packages/datalad/tests/test_archives.py", line 196, in test_ExtractedArchive
    op.join(fn_archive_obscure, '3.txt')
AssertionError: [' "\';b&b&cΔЙקم๗あ `| / "\';a&b&cΔЙקم๗あ `| '] != [' "\';b&b&cΔЙקم๗あ `| / "\';a&b&cΔЙקم๗あ `| ', ' "\';b&b&cΔЙקم๗あ `| /3.txt']
```
so smells like similar (but different) indigestion to https://github.com/datalad/datalad/issues/3769 of plain 7z invocation on tricky filenames?

**Comment by yarikoptic** [comment]
strangely it passed on master https://travis-ci.org/datalad/datalad/jobs/642975399 or https://travis-ci.org/datalad/datalad/jobs/642747907

**Comment by bpoldrack** [comment]
This test failed again the same way here: https://app.travis-ci.com/github/datalad/datalad/jobs/587461343
