### ISSUE TITLE
ConfigManager CWD setup leads to errors (on Windows)

### ISSUE THREAD

**Issue by mih** [datalad/datalad#4179]
Happens whenever a once configured Runner CWD (no longer) exists:
```
(Pdb) ar.config.reload(force=True)
[Level 11] Failed to start ['git', 'config', '-z', '-l', '--show-origin']'': [WinError 267] Invalid directory name [subprocess.py:_execute_child:1178]
```

Maybe each execution should be guarded with an `exists()`.

**Comment by adswa** [comment]
I was wondering if this bug still exists, but I as I almost never use the config manager, I struggle to find out how to trigger/test this - can someone help me out?

**Comment by bpoldrack** [comment]
@adswa 

Sorry for being too quick with the first reply. Now, that I look at it again, I realize that the `Dataset` vs `Repo` use may actually be the problem here. If the repo vanishes, `Dataset.repo` will be reevaluated and `Dataset.config` as a consequence, too. That may not happen from within the `Repo` classes and this may be the issue here.

Could you retry:

```
ds = Dataset('where/ever').create()
repo = ds.repo
rmtree('where/ever')
repo.config.reload(force=True)
```

If that fails, `configuration` may need a fix. Otherwise we can close for now, I guess.

**Comment by adswa** [comment]
Thx, tried that, but didn't yet get to the config failure - I for now got what seems to be a path encoding issue I'll need to follow up first

```
>>> ds = dl.Dataset("somedsmore").create()
[INFO] Detected a filesystem without fifo support.
[INFO] Disabling ssh connection caching.
[INFO] Detected a crippled filesystem.
[INFO] Entering an adjusted branch where files are unlocked as this filesystem does not support locked files.
[INFO] Switched to branch 'adjusted/master(unlocked)'
create(ok): . (dataset)
>>> repo = ds.repo
>>> repo
AnnexRepo('C:\\Users\\adina\\testing\\fudystorrest-data\\somedsmore')
>>> rmtree("somedsmore")
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "C:\Users\adina\repos\datalad\datalad\[utils.py](http://utils.py/)", line 505, in rmtree
    _rmtree(path, *args, **kwargs)
  File "C:\Users\adina\repos\datalad\datalad\[utils.py](http://utils.py/)", line 2075, in _wrap_try_multiple_dec
    return f(*args, **kwargs)
  File "C:\Users\adina\repos\datalad\datalad\[utils.py](http://utils.py/)", line 2116, in _rmtree
    return shutil.rmtree(*args, **kwargs)
  File "C:\Users\adina\AppData\Local\Programs\Python\Python310\lib\[shutil.py](http://shutil.py/)", line 749, in rmtree
    return _rmtree_unsafe(path, onerror)
  File "C:\Users\adina\AppData\Local\Programs\Python\Python310\lib\[shutil.py](http://shutil.py/)", line 600, in _rmtree_unsafe
    onerror(os.scandir, path, sys.exc_info())
  File "C:\Users\adina\AppData\Local\Programs\Python\Python310\lib\[shutil.py](http://shutil.py/)", line 597, in _rmtree_unsafe
    with os.scandir(path) as scandir_it:
FileNotFoundError: [WinError 3] The system cannot find the path specified: '\\\\?\\somedsmore'
```
