### ISSUE TITLE
`test_get_open_files()` fails on Windows

### ISSUE THREAD

**Issue by mih** [datalad/datalad#4192]
AFAICS this is only concerning a test helper, hence a minor issue. The underlying problem is #4055 and the fix requires #4057 to be completed

```
=====================================================================
ERROR: datalad.tests.test_utils.test_get_open_files
----------------------------------------------------------------------
Traceback (most recent call last):
  File "C:\hostedtoolcache\windows\Python\3.7.6\x64\lib\site-packages\nose\case.py", line 198, in runTest
    self.test(*self.arg)
  File "C:\hostedtoolcache\windows\Python\3.7.6\x64\lib\site-packages\datalad\tests\utils.py", line 586, in newfunc
    return t(*(arg + (d,)), **kw)
  File "C:\hostedtoolcache\windows\Python\3.7.6\x64\lib\site-packages\datalad\tests\test_utils.py", line 1206, in test_get_open_files
    eq_(get_open_files(subd)[op.realpath(subd)].pid, proc.pid)
KeyError: 'C:\\Users\\RUNNER~1\\AppData\\Local\\Temp\\datalad_temp_tree_ydko39bg\\d'
```

**Comment by mih** [comment]
Fix merged.
