### ISSUE TITLE
Another current "open files" issues

### ISSUE THREAD

**Issue by mih** [datalad/datalad#4201]
Variant of #2518

```
======================================================================
ERROR: datalad.customremotes.tests.test_base.test_get_contentlocation
----------------------------------------------------------------------
Traceback (most recent call last):
  File "C:\hostedtoolcache\windows\Python\3.7.6\x64\lib\site-packages\nose\case.py", line 198, in runTest
    self.test(*self.arg)
  File "C:\hostedtoolcache\windows\Python\3.7.6\x64\lib\site-packages\datalad\tests\utils.py", line 521, in newfunc
    rmtemp(d)
  File "C:\hostedtoolcache\windows\Python\3.7.6\x64\lib\site-packages\datalad\utils.py", line 521, in rmtemp
    rmtree(f, *args, **kwargs)
  File "C:\hostedtoolcache\windows\Python\3.7.6\x64\lib\site-packages\datalad\utils.py", line 434, in rmtree
    _rmtree(path, *args, **kwargs)
  File "C:\hostedtoolcache\windows\Python\3.7.6\x64\lib\site-packages\datalad\utils.py", line 1882, in wrapped
    return f(*args, **kwargs)
  File "C:\hostedtoolcache\windows\Python\3.7.6\x64\lib\site-packages\datalad\utils.py", line 1922, in _rmtree
    return shutil.rmtree(*args, **kwargs)
  File "C:\hostedtoolcache\windows\Python\3.7.6\x64\lib\shutil.py", line 516, in rmtree
    return _rmtree_unsafe(path, onerror)
  File "C:\hostedtoolcache\windows\Python\3.7.6\x64\lib\shutil.py", line 404, in _rmtree_unsafe
    onerror(os.rmdir, path, sys.exc_info())
  File "C:\hostedtoolcache\windows\Python\3.7.6\x64\lib\shutil.py", line 402, in _rmtree_unsafe
    os.rmdir(path)
PermissionError: [WinError 32] The process cannot access the file because it is being used by another process: 'C:\\Users\\RUNNER~1\\AppData\\Local\\Temp\\datalad_temp_tree_gf66hfom'
```

**Comment by mih** [comment]
These should no longer happen. The test helpers acknowledge this problem now.
