### ISSUE TITLE
Setup or modification detection issue with shortpaths

### ISSUE THREAD

**Issue by mih** [datalad/datalad#4202]
Replacing `ok_clean_git()` with `assert_repo_status()` reveals the following breakage on Windows systems that report short paths. it is unclear whether it has been there before and `ok_clean_git` didn't see it (in which case it would explain various supernatural behavior of the testrepos), or status reporting (i.e. `GitRepo._diffstatus()`) and friends are broken on such systems (unlikely, because this is the only test that fails).

```
======================================================================
FAIL: datalad.tests.test_utils_testrepos.test_BasicAnnexTestRepo
----------------------------------------------------------------------
Traceback (most recent call last):
  File "C:\hostedtoolcache\windows\Python\3.7.6\x64\lib\site-packages\nose\case.py", line 198, in runTest
    self.test(*self.arg)
  File "C:\hostedtoolcache\windows\Python\3.7.6\x64\lib\site-packages\datalad\tests\utils.py", line 691, in newfunc
    return t(*(arg + (filename,)), **kw)
  File "C:\hostedtoolcache\windows\Python\3.7.6\x64\lib\site-packages\datalad\tests\test_utils_testrepos.py", line 51, in test_BasicAnnexTestRepo
    _test_BasicAnnexTestRepo(path)
  File "C:\hostedtoolcache\windows\Python\3.7.6\x64\lib\site-packages\datalad\tests\test_utils_testrepos.py", line 29, in _test_BasicAnnexTestRepo
    assert_repo_status(trepo.path)
  File "C:\hostedtoolcache\windows\Python\3.7.6\x64\lib\site-packages\datalad\tests\utils.py", line 1575, in assert_repo_status
    % (state, state_files, oktobefound))
AssertionError: unexpected content of state "modified": [WindowsPath('C:/Users/RUNNER~1/AppData/Local/Temp/datalad_temp_bv7pwx9p/test-annex.dat')] != []
```

**Comment by mih** [comment]
Thank you for reporting this issue!

However, at this point I am closing it at a time of ~600 open issues, in an attempt to regain control over the issue tracker. This particular issue was posted more than 6 months ago, has not received a single response, and does not describe an immediate software defect. *Closing this issue does not imply that it is not relevant*. If any reader objects the closing of this issue, please feel more than free to reopen it with an update on how it is relevant for the current state of the project, and which concrete actions to address it are ongoing or planned.
