### ISSUE TITLE
datalad.core.local.tests.test_status.test_status fails with adjusted branches

### ISSUE THREAD

**Issue by mih** [datalad/datalad#4220]
On Debian, as of current master (7b8282b5d671c45a0c4ae3c42024edf27ce51230), with TMPDIR on a crippled FS.
git-annex version: 8.20200226; git version 2.24.1

```
======================================================================
FAIL: datalad.core.local.tests.test_status.test_status
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/mih/env/datalad3-dev/lib/python3.7/site-packages/nose/case.py", line 198, in runTest
    self.test(*self.arg)
  File "/home/mih/hacking/datalad/git/datalad/tests/utils.py", line 759, in newfunc
    return t(*(arg + (filename,)), **kw)
  File "/home/mih/hacking/datalad/git/datalad/tests/utils.py", line 759, in newfunc
    return t(*(arg + (filename,)), **kw)
  File "/home/mih/hacking/datalad/git/datalad/core/local/tests/test_status.py", line 121, in test_status
    assert ds.pathobj != ds.repo.pathobj
AssertionError: 
```

Likely same as #4219

**Comment by mih** [comment]
No longer an issue in latest test run on crippled FS.
