### ISSUE TITLE
datalad.core.local.tests.test_run.test_run_from_subds_gh3551 fails with adjusted branches

### ISSUE THREAD

**Issue by mih** [datalad/datalad#4221]
On Debian, as of current master (7b8282b5d671c45a0c4ae3c42024edf27ce51230), with TMPDIR on a crippled FS.
git-annex version: 8.20200226; git version 2.24.1

```
======================================================================
FAIL: datalad.core.local.tests.test_run.test_run_from_subds_gh3551
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/mih/env/datalad3-dev/lib/python3.7/site-packages/nose/case.py", line 198, in runTest
    self.test(*self.arg)
  File "/home/mih/hacking/datalad/git/datalad/tests/utils.py", line 586, in newfunc
    return t(*(arg + (d,)), **kw)
  File "/home/mih/hacking/datalad/git/datalad/core/local/tests/test_run.py", line 258, in test_run_from_subds_gh3551
    ok_(subds.repo.file_has_content("f"))
AssertionError: None
```

**Comment by mih** [comment]
No longer an issue in latest test run on crippled FS.
