### ISSUE TITLE
Inappropriate use of symlinks on crippled FS

### ISSUE THREAD

**Issue by mih** [datalad/datalad#4223]
On Debian, as of current master (7b8282b5d671c45a0c4ae3c42024edf27ce51230), with TMPDIR on a crippled FS.
git-annex version: 8.20200226; git version 2.24.1

```
======================================================================
ERROR: datalad.core.local.tests.test_create.test_gh2927
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/mih/env/datalad3-dev/lib/python3.7/site-packages/nose/case.py", line 198, in runTest
    self.test(*self.arg)
  File "/home/mih/hacking/datalad/git/datalad/tests/utils.py", line 759, in newfunc
    return t(*(arg + (filename,)), **kw)
  File "/home/mih/hacking/datalad/git/datalad/tests/utils.py", line 759, in newfunc
    return t(*(arg + (filename,)), **kw)
  File "/home/mih/hacking/datalad/git/datalad/core/local/tests/test_create.py", line 498, in test_gh2927
    Path(linkpath).symlink_to(path, target_is_directory=True)
  File "/usr/lib/python3.7/pathlib.py", line 1337, in symlink_to
    self._accessor.symlink(target, self, target_is_directory)
  File "/usr/lib/python3.7/pathlib.py", line 431, in symlink
    return os.symlink(a, b)
OSError: [Errno 38] Function not implemented: '/media/mih/Samsung_T5/tmp/datalad_temp_test_gh2927lrckpnbn' -> '/media/mih/Samsung_T5/tmp/datalad_temp_test_gh29271stursjl'

======================================================================
ERROR: datalad.core.local.tests.test_status.test_status_basics
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/mih/env/datalad3-dev/lib/python3.7/site-packages/nose/case.py", line 198, in runTest
    self.test(*self.arg)
  File "/home/mih/hacking/datalad/git/datalad/tests/utils.py", line 759, in newfunc
    return t(*(arg + (filename,)), **kw)
  File "/home/mih/hacking/datalad/git/datalad/tests/utils.py", line 759, in newfunc
    return t(*(arg + (filename,)), **kw)
  File "/home/mih/hacking/datalad/git/datalad/tests/utils.py", line 759, in newfunc
    return t(*(arg + (filename,)), **kw)
  File "/home/mih/hacking/datalad/git/datalad/core/local/tests/test_status.py", line 57, in test_status_basics
    ut.Path(linkpath).symlink_to(path, target_is_directory=True)
  File "/usr/lib/python3.7/pathlib.py", line 1337, in symlink_to
    self._accessor.symlink(target, self, target_is_directory)
  File "/usr/lib/python3.7/pathlib.py", line 431, in symlink
    return os.symlink(a, b)
OSError: [Errno 38] Function not implemented: '/media/mih/Samsung_T5/tmp/datalad_temp_test_status_basicsy02i7xdh' -> '/media/mih/Samsung_T5/tmp/datalad_temp_test_status_basicsu1kotwe_'
```

**Comment by mih** [comment]
No longer an issue in latest test run on crippled FS.
