### ISSUE TITLE
datalad.core.local.tests.test_create.test_create fails on crippled FS

### ISSUE THREAD

**Issue by mih** [datalad/datalad#4224]
On Debian, as of current master (7b8282b5d671c45a0c4ae3c42024edf27ce51230), with TMPDIR on a crippled FS.
git-annex version: 8.20200226; git version 2.24.1

```
======================================================================
ERROR: datalad.core.local.tests.test_create.test_create
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/mih/env/datalad3-dev/lib/python3.7/site-packages/nose/case.py", line 198, in runTest
    self.test(*self.arg)
  File "/home/mih/hacking/datalad/git/datalad/tests/utils.py", line 759, in newfunc
    return t(*(arg + (filename,)), **kw)
  File "/home/mih/hacking/datalad/git/datalad/core/local/tests/test_create.py", line 169, in test_create
    initopts=dict(shared='world'))
  File "/home/mih/hacking/datalad/git/datalad/distribution/dataset.py", line 501, in apply_func
    return f(**kwargs)
  File "/home/mih/hacking/datalad/git/datalad/interface/utils.py", line 492, in eval_func
    return return_func(generator_func)(*args, **kwargs)
  File "/home/mih/hacking/datalad/git/datalad/interface/utils.py", line 480, in return_func
    results = list(results)
  File "/home/mih/hacking/datalad/git/datalad/interface/utils.py", line 411, in generator_func
    allkwargs):
  File "/home/mih/hacking/datalad/git/datalad/interface/utils.py", line 527, in _process_results
    for res in results:
  File "/home/mih/hacking/datalad/git/datalad/core/local/create.py", line 374, in __call__
    fake_dates=fake_dates
  File "/home/mih/hacking/datalad/git/datalad/support/repo.py", line 151, in __call__
    instance = type.__call__(cls, *new_args, **new_kwargs)
  File "/home/mih/hacking/datalad/git/datalad/support/annexrepo.py", line 207, in __init__
    repo=repo, git_opts=git_opts, fake_dates=fake_dates)
  File "/home/mih/hacking/datalad/git/datalad/support/gitrepo.py", line 1039, in __init__
    create_sanity_checks, **git_opts)
  File "/home/mih/hacking/datalad/git/datalad/support/gitrepo.py", line 1105, in _create_empty_repo
    expect_fail=True)
  File "/home/mih/hacking/datalad/git/datalad/support/gitrepo.py", line 351, in newfunc
    result = func(self, files_new, *args, **kwargs)
  File "/home/mih/hacking/datalad/git/datalad/support/gitrepo.py", line 2219, in _git_custom_command
    expect_fail=expect_fail)
  File "/home/mih/hacking/datalad/git/datalad/cmd.py", line 143, in run_gitcommand_on_file_list_chunks
    results.append(func(cmd, *args, **kwargs))
  File "/home/mih/hacking/datalad/git/datalad/cmd.py", line 1102, in run
    *args, **kwargs)
  File "/home/mih/hacking/datalad/git/datalad/cmd.py", line 926, in run
    raise exc
datalad.support.exceptions.CommandError: CommandError: 'git init --shared=world' failed with exitcode 128 under /media/mih/Samsung_T5/tmp/datalad_temp_test_createz46tj7wa [err: 'fatal: Could not make /media/mih/Samsung_T5/tmp/datalad_temp_test_createz46tj7wa/.git/info/ writable by group
']
```

**Comment by mih** [comment]
No longer happening in latest test run on crippled FS.
