### ISSUE TITLE
datalad.core.distributed.tests.test_clone.test_ephemeral fails with adjusted branches

### ISSUE THREAD

**Issue by mih** [datalad/datalad#4225]
On Debian, as of current master (7b8282b5d671c45a0c4ae3c42024edf27ce51230), with TMPDIR on a crippled FS.
git-annex version: 8.20200226; git version 2.24.1

```
======================================================================
FAIL: datalad.core.distributed.tests.test_clone.test_ephemeral
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/mih/env/datalad3-dev/lib/python3.7/site-packages/nose/case.py", line 198, in runTest
    self.test(*self.arg)
  File "/home/mih/hacking/datalad/git/datalad/tests/utils.py", line 188, in newfunc
    return func(*args, **kwargs)
  File "/home/mih/hacking/datalad/git/datalad/tests/utils.py", line 586, in newfunc
    return t(*(arg + (d,)), **kw)
  File "/home/mih/hacking/datalad/git/datalad/tests/utils.py", line 759, in newfunc
    return t(*(arg + (filename,)), **kw)
  File "/home/mih/hacking/datalad/git/datalad/tests/utils.py", line 759, in newfunc
    return t(*(arg + (filename,)), **kw)
  File "/home/mih/hacking/datalad/git/datalad/core/distributed/tests/test_clone.py", line 835, in test_ephemeral
    eq_(res, [origin.config.get("annex.uuid")])
AssertionError: [] != ['f1b090e8-fada-4876-bf75-b51628a1a9e6']
```

**Comment by mih** [comment]
The test made no sense for repos where there are no symlinks into the annex.
