### ISSUE TITLE
ERROR: datalad.support.tests.test_annexrepo.test_files_split

### ISSUE THREAD

**Issue by mih** [datalad/datalad#4298]
```
======================================================================
ERROR: datalad.support.tests.test_annexrepo.test_files_split(<class 'datalad.support.gitrepo.GitRepo'>,)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "C:\Users\mih\Miniconda3\lib\site-packages\nose\case.py", line 198, in runTest
    self.test(*self.arg)
  File "C:\Users\mih\code\datalad\datalad\tests\utils.py", line 516, in newfunc
    create_tree(d, tree, archives_leading_dir=archives_leading_dir)
  File "C:\Users\mih\code\datalad\datalad\utils.py", line 2285, in create_tree
    remove_existing=remove_existing)
  File "C:\Users\mih\code\datalad\datalad\utils.py", line 2290, in create_tree
    with open_func(full_name, "wb") as f:
FileNotFoundError: [Errno 2] No such file or directory: 'C:\\Users\\mih\\AppData\\Local\\Temp\\datalad_temp_tree_6mgshv89\\dddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddd000\\ffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffff000'

======================================================================
ERROR: datalad.support.tests.test_annexrepo.test_files_split(<class 'datalad.support.annexrepo.AnnexRepo'>,)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "C:\Users\mih\Miniconda3\lib\site-packages\nose\case.py", line 198, in runTest
    self.test(*self.arg)
  File "C:\Users\mih\code\datalad\datalad\tests\utils.py", line 516, in newfunc
    create_tree(d, tree, archives_leading_dir=archives_leading_dir)
  File "C:\Users\mih\code\datalad\datalad\utils.py", line 2285, in create_tree
    remove_existing=remove_existing)
  File "C:\Users\mih\code\datalad\datalad\utils.py", line 2290, in create_tree
    with open_func(full_name, "wb") as f:
FileNotFoundError: [Errno 2] No such file or directory: 'C:\\Users\\mih\\AppData\\Local\\Temp\\datalad_temp_tree_ckilxc8t\\dddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddd000\\ffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffff000'
```

**Comment by mih** [comment]
This is no longer happening. Test reenabled on Windows by f11a3fea739b04857b0d7fcca322bbfca868cd77
