### ISSUE TITLE
FAIL: datalad.support.tests.test_annexrepo.test_commit_annex_commit_changed

### ISSUE THREAD

**Issue by mih** [datalad/datalad#4300]
```
======================================================================
FAIL: datalad.support.tests.test_annexrepo.test_commit_annex_commit_changed(True,)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "C:\Users\mih\Miniconda3\lib\site-packages\nose\case.py", line 198, in runTest
    self.test(*self.arg)
  File "C:\Users\mih\code\datalad\datalad\tests\utils.py", line 518, in newfunc
    return t(*(arg + (d,)), **kw)
  File "C:\Users\mih\code\datalad\datalad\support\tests\test_annexrepo.py", line 2174, in check_commit_annex_commit_changed
    assert_repo_status(path)
  File "C:\Users\mih\code\datalad\datalad\tests\utils.py", line 1575, in assert_repo_status
    % (state, state_files, oktobefound))
AssertionError: unexpected content of state "modified": [WindowsPath('C:/Users/mih/AppData/Local/Temp/datalad_temp_tree_7gtel35p/.gitattributes')] != []
-------------------- >> begin captured logging << --------------------
asyncio: DEBUG: Using proactor: IocpProactor
--------------------- >> end captured logging << ---------------------

======================================================================
FAIL: datalad.support.tests.test_annexrepo.test_commit_annex_commit_changed(False,)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "C:\Users\mih\Miniconda3\lib\site-packages\nose\case.py", line 198, in runTest
    self.test(*self.arg)
  File "C:\Users\mih\code\datalad\datalad\tests\utils.py", line 518, in newfunc
    return t(*(arg + (d,)), **kw)
  File "C:\Users\mih\code\datalad\datalad\support\tests\test_annexrepo.py", line 2174, in check_commit_annex_commit_changed
    assert_repo_status(path)
  File "C:\Users\mih\code\datalad\datalad\tests\utils.py", line 1575, in assert_repo_status
    % (state, state_files, oktobefound))
AssertionError: unexpected content of state "modified": [WindowsPath('C:/Users/mih/AppData/Local/Temp/datalad_temp_tree_ofl91kvh/.gitattributes')] != []
```

**Comment by mih** [comment]
This is legit broken. Here is the state before the `AnnexRepo.save()` call:

```
(base) C:\Users\mih\AppData\Local\Temp\datalad_temp_tree_j_lgx1hd>git status                                                 On branch adjusted/master(unlocked)                                                                                          Untracked files:                                                                                                               (use "git add <file>..." to include in what will be committed)                                                                     .gitattributes                                                                                                               alwaysbig                                                                                                                    tobechanged-annex                                                                                                            tobechanged-git                                                                                                              willgetshort                                                                                                                                                                                                                                      nothing added to commit but untracked files present (use "git add" to track)                                                  
```

And here afterwards:

```
(base) C:\Users\mih\AppData\Local\Temp\datalad_temp_tree_j_lgx1hd>git status
On branch adjusted/master(unlocked)
Changes not staged for commit:
  (use "git add <file>..." to update what will be committed)
  (use "git restore <file>..." to discard changes in working directory)
        modified:   .gitattributes

no changes added to commit (use "git add" and/or "git commit -a")

(base) C:\Users\mih\AppData\Local\Temp\datalad_temp_tree_j_lgx1hd>git diff
diff --git a/.gitattributes b/.gitattributes
index c62e2b7..a3d3e16 100644
--- a/.gitattributes
+++ b/.gitattributes
@@ -1 +1 @@
-/annex/objects/SHA256E-s35--206e8f8c2461feaf6f375ee75d9a42cd9deb91e0cb3c3a67399f8c94ff2db2f0
+** annex.largefiles=(largerthan=4b)
\ No newline at end of file
```

`.gitattributes` is annexed, as also evident in the corresponding branch after the `sync()`.
