### ISSUE TITLE
TST: datalad.core.distributed.tests.test_clone.test_clone_datasets_root

### ISSUE THREAD

**Issue by mih** [datalad/datalad#4333]
```
======================================================================
ERROR: datalad.core.distributed.tests.test_clone.test_clone_datasets_root
----------------------------------------------------------------------
Traceback (most recent call last):
  File "C:\Users\mih\Miniconda3\lib\site-packages\nose\case.py", line 198, in runTest
    self.test(*self.arg)
  File "C:\Users\mih\code\datalad\datalad\tests\utils.py", line 166, in newfunc
    return func(*args, **kwargs)
  File "C:\Users\mih\code\datalad\datalad\support\vcr_.py", line 90, in wrapper
    return t(*args, **kwargs)
  File "C:\Users\mih\code\datalad\datalad\tests\utils.py", line 518, in newfunc
    return t(*(arg + (d,)), **kw)
  File "C:\Users\mih\code\datalad\datalad\core\distributed\tests\test_clone.py", line 142, in test_clone_datasets_root
    res = clone("///", on_failure='ignore', result_xfm=None, return_type='list')
  File "C:\Users\mih\Miniconda3\lib\site-packages\wrapt\wrappers.py", line 564, in __call__
    args, kwargs)
  File "C:\Users\mih\code\datalad\datalad\interface\utils.py", line 492, in eval_func
    return return_func(generator_func)(*args, **kwargs)
  File "C:\Users\mih\Miniconda3\lib\site-packages\wrapt\wrappers.py", line 564, in __call__
    args, kwargs)
  File "C:\Users\mih\code\datalad\datalad\interface\utils.py", line 480, in return_func
    results = list(results)
  File "C:\Users\mih\code\datalad\datalad\interface\utils.py", line 411, in generator_func
    allkwargs):
  File "C:\Users\mih\code\datalad\datalad\interface\utils.py", line 527, in _process_results
    for res in results:
  File "C:\Users\mih\code\datalad\datalad\core\distributed\clone.py", line 285, in __call__
    cfg=None if ds is None else ds.config,
  File "C:\Users\mih\code\datalad\datalad\core\distributed\clone.py", line 384, in clone_dataset
    or get_local_file_url(track_url, compatibility='git') == src \
  File "C:\Users\mih\code\datalad\datalad\support\network.py", line 922, in get_local_file_url
    path = Path(fname).resolve()
  File "C:\Users\mih\Miniconda3\lib\pathlib.py", line 1144, in resolve
    s = self._flavour.resolve(self, strict=strict)
  File "C:\Users\mih\Miniconda3\lib\pathlib.py", line 201, in resolve
    s = self._ext_to_normal(_getfinalpathname(s))
OSError: [WinError 123] Die Syntax für den Dateinamen, Verzeichnisnamen oder die Datenträgerbezeichnung ist falsch: 'http:\\datasets-tests.datalad.org\\.git'
```

Legitimate URL gets butchered by replacing slashes with backslashes.

**Comment by mih** [comment]
The reason for that is `get_local_file_url()` being called with a `http://` URL, but the function only handles file paths.
