### ISSUE TITLE
ERROR: datalad.interface.tests.test_rerun.test_run_inputs_outputs

### ISSUE THREAD

**Issue by mih** [datalad/datalad#4335]
```
======================================================================
ERROR: datalad.interface.tests.test_rerun.test_run_inputs_outputs
----------------------------------------------------------------------
Traceback (most recent call last):
  File "C:\Users\mih\Miniconda3\lib\site-packages\nose\case.py", line 198, in runTest
    self.test(*self.arg)
  File "C:\Users\mih\code\datalad\datalad\tests\utils.py", line 518, in newfunc
    return t(*(arg + (d,)), **kw)
  File "C:\Users\mih\code\datalad\datalad\tests\utils.py", line 691, in newfunc
    return t(*(arg + (filename,)), **kw)
  File "C:\Users\mih\code\datalad\datalad\interface\tests\test_rerun.py", line 640, in test_run_inputs_outputs
    ds.rerun()
  File "C:\Users\mih\Miniconda3\lib\site-packages\wrapt\wrappers.py", line 603, in __call__
    args, kwargs)
  File "C:\Users\mih\code\datalad\datalad\distribution\dataset.py", line 498, in apply_func
    return f(**kwargs)
  File "C:\Users\mih\Miniconda3\lib\site-packages\wrapt\wrappers.py", line 564, in __call__
    args, kwargs)
  File "C:\Users\mih\code\datalad\datalad\interface\utils.py", line 492, in eval_func
    return return_func(generator_func)(*args, **kwargs)
  File "C:\Users\mih\Miniconda3\lib\site-packages\wrapt\wrappers.py", line 564, in __call__
    args, kwargs)
  File "C:\Users\mih\code\datalad\datalad\interface\utils.py", line 480, in return_func
    results = list(results)
  File "C:\Users\mih\code\datalad\datalad\interface\utils.py", line 467, in generator_func
    msg="Command did not complete successfully")
datalad.support.exceptions.IncompleteResultsError: Command did not complete successfully [{'action': 'run', 'path': 'C:\\Users\\mih\\AppData\\Local\\Temp\\datalad_temp_chbthxh7', 'type': 'dataset', 'status': 'impossible', 'message': ('No run commits found in range %s', 'HEAD^..HEAD')}]
```

**Comment by mih** [comment]
Here is the reason for this failure:

![image](https://user-images.githubusercontent.com/136479/104089276-da298880-526d-11eb-93e1-aab36e76bb68.png)

After the save, the adjusted branch is synced with the corresponding branch and consequently the last commit is no run commit.

I think `re-run` should (exclusively) inspect the corresponding branch for run records. What do you think @kyleam ?

I am adjusting the tags accordingly.

**Comment by kyleam** [comment]
Yeah, there's not a part of `rerun` that's aware of or compatible with adjusted branches.  Without having thought too deeply about it, I'd say

  * we probably could make simple cases (in particular `rerun` without `--onto`) work with adjusted branches
  * trying to make `--onto` work with adjusted branches probably isn't worth the headache, but we should of course clearly document that it's not supported and abort appropriately

I'll look into it.

**Comment by kyleam** [comment]
With gh-5328, `test_run_inputs_outputs` passes under `tools/eval_under_testloopfs`, so the adjusted branch aspect of the failure should be fixed.

**Comment by mih** [comment]
I can confirm that the test fails universally (now), and has nothing to do with adjusted branches. Looking a the test annotations this seems well known. So I am closing this old issue of mine.

FTR: test now lives in `datalad/local/tests/test_rerun.py`
