### ISSUE TITLE
CrippledFS: test_ria_git_remote.test_bare_git ValueError: Unknown remote 'bare-git'

### ISSUE THREAD

**Issue by yarikoptic** [datalad/datalad#4366]
There is a newish added test workflow which is currently failing with
```
======================================================================
ERROR: datalad.distributed.tests.test_ria_git_remote.test_bare_git
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/opt/hostedtoolcache/Python/3.5.9/x64/lib/python3.5/site-packages/nose/case.py", line 198, in runTest
    self.test(*self.arg)
  File "/opt/hostedtoolcache/Python/3.5.9/x64/lib/python3.5/site-packages/datalad/tests/utils.py", line 186, in newfunc
    return func(*args, **kwargs)
  File "/opt/hostedtoolcache/Python/3.5.9/x64/lib/python3.5/site-packages/datalad/distributed/tests/ria_utils.py", line 95, in newfunc
    return func(*args, **kwargs)
  File "/opt/hostedtoolcache/Python/3.5.9/x64/lib/python3.5/site-packages/datalad/tests/utils.py", line 691, in newfunc
    return t(*(arg + (filename,)), **kw)
  File "/opt/hostedtoolcache/Python/3.5.9/x64/lib/python3.5/site-packages/datalad/tests/utils.py", line 691, in newfunc
    return t(*(arg + (filename,)), **kw)
  File "/opt/hostedtoolcache/Python/3.5.9/x64/lib/python3.5/site-packages/datalad/distributed/tests/test_ria_git_remote.py", line 63, in test_bare_git
    ds.repo.copy_to('.', 'bare-git')
  File "/opt/hostedtoolcache/Python/3.5.9/x64/lib/python3.5/site-packages/datalad/support/gitrepo.py", line 329, in newfunc
    result = func(self, files_new, *args, **kwargs)
  File "/opt/hostedtoolcache/Python/3.5.9/x64/lib/python3.5/site-packages/datalad/support/annexrepo.py", line 2988, in copy_to
    raise ValueError("Unknown remote '{0}'.".format(remote))
ValueError: Unknown remote 'bare-git'.
```
and seems was [more failing than not](https://github.com/datalad/datalad/actions?query=workflow%3ACrippledFS) for a while.  It causes fatigue and wasted cycles if nobody cares -- should be either fixed up or disabled.

**Comment by bpoldrack** [comment]
This test has changed and isn't currently failing AFAIK.
