### ISSUE TITLE
Curious crippled FS test failure in #4430

### ISSUE THREAD

**Issue by mih** [datalad/datalad#4443]
```
======================================================================
FAIL: datalad.core.distributed.tests.test_clone.test_expanduser
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/opt/hostedtoolcache/Python/3.5.9/x64/lib/python3.5/site-packages/nose/case.py", line 198, in runTest
    self.test(*self.arg)
  File "/opt/hostedtoolcache/Python/3.5.9/x64/lib/python3.5/site-packages/datalad/tests/utils.py", line 691, in newfunc
    return t(*(arg + (filename,)), **kw)
  File "/opt/hostedtoolcache/Python/3.5.9/x64/lib/python3.5/site-packages/datalad/tests/utils.py", line 691, in newfunc
    return t(*(arg + (filename,)), **kw)
  File "/opt/hostedtoolcache/Python/3.5.9/x64/lib/python3.5/site-packages/datalad/core/distributed/tests/test_clone.py", line 496, in test_expanduser
    eq_(src.id, cloneds.id)
AssertionError: '7351b32a-87ee-11ea-b063-000d3a0eadeb' != '7351b32b-87ee-11ea-b063-000d3a0eadeb'
```

**Comment by yarikoptic** [comment]
took me a bit to eye ball -- it is `a` vs `b` at the end of the first component, not that I know WTF is happening ;)

**Comment by mih** [comment]
Seems to have been a glitch of some kind. I will close this now.
