### ISSUE TITLE
Running tests on NFS results in an (ignored) traceback upon exit

### ISSUE THREAD

**Issue by yarikoptic** [datalad/datalad#4495]
happens on cron master and maint, e.g. https://travis-ci.org/github/datalad/datalad/jobs/683567876#L1299 (maint), not sure for how long (may be always? found it mentioned in a WIP PR #2882 from 1.5 years ago) but is spit out upon exit so not causing overall failure:
```
Traceback (most recent call last):
  File "/opt/python/3.5.6/lib/python3.5/multiprocessing/util.py", line 262, in _run_finalizers
    finalizer()
  File "/opt/python/3.5.6/lib/python3.5/multiprocessing/util.py", line 186, in __call__
    res = self._callback(*self._args, **self._kwargs)
  File "/home/travis/virtualenv/python3.5.6/lib/python3.5/shutil.py", line 480, in rmtree
    _rmtree_safe_fd(fd, path, onerror)
  File "/home/travis/virtualenv/python3.5.6/lib/python3.5/shutil.py", line 438, in _rmtree_safe_fd
    onerror(os.unlink, fullname, sys.exc_info())
  File "/home/travis/virtualenv/python3.5.6/lib/python3.5/shutil.py", line 436, in _rmtree_safe_fd
    os.unlink(name, dir_fd=topfd)
OSError: [Errno 16] Device or resource busy: '.nfs0000000000235a2800000001'
```
something to possibly investigate and address if possible

**Comment by yarikoptic** [comment]
NFS is a bane of our existence and we learned to live with it (with periodic complains to Joey ;-))
