### ISSUE TITLE
test_decompress_file: fails on NFS on master

### ISSUE THREAD

**Issue by yarikoptic** [datalad/datalad#4496]
in master (didn't spot in maint) test fails on our cron job: https://travis-ci.org/github/datalad/datalad/jobs/682067828

```
======================================================================
ERROR: datalad.tests.test_archives.test_decompress_file('strip',)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/travis/virtualenv/python3.5.6/lib/python3.5/site-packages/nose/case.py", line 198, in runTest
    self.test(*self.arg)
  File "/home/travis/virtualenv/python3.5.6/lib/python3.5/site-packages/datalad/tests/utils.py", line 518, in newfunc
    return t(*(arg + (d,)), **kw)
  File "/home/travis/virtualenv/python3.5.6/lib/python3.5/site-packages/datalad/tests/test_archives.py", line 77, in check_decompress_file
    leading_directories=leading_directories)
  File "/home/travis/virtualenv/python3.5.6/lib/python3.5/site-packages/datalad/support/archives.py", line 99, in decompress_file
    rmdir(widow_dir)
  File "/home/travis/virtualenv/python3.5.6/lib/python3.5/site-packages/datalad/utils.py", line 471, in rmdir
    os.rmdir(path)
OSError: [Errno 39] Directory not empty: '/tmp/nfsmount/datalad-fhwhrw_1/simple-extracted/ "\';b&b&cΔЙקم๗あ `| '
```

**Comment by adswa** [comment]
I fail to find this test in the logs. Do we run this test battery under NFS currently?

**Comment by yarikoptic** [comment]
@adswa there are back references from other PRs/issues now, and 

```
(git)smaug:/mnt/datasets/datalad/ci/logs/2021[master]git
$> git submodule foreach git grep 'ERROR: datalad.tests.test_archives.test_decompress_file'
Entering '05'
26/pr/5698/d719809/travis-11973-failed/8.txt:ERROR: datalad.tests.test_archives.test_decompress_file('strip',)
Entering '06'
17/pr/5749/adc72ce/travis-12088-failed/8.txt:ERROR: datalad.tests.test_archives.test_decompress_file('strip',)
18/push/master/99bac03/travis-12090-failed/8.txt:ERROR: datalad.tests.test_archives.test_decompress_file('strip',)
29/pr/5749/19278eb/travis-12118-failed/8.txt:ERROR: datalad.tests.test_archives.test_decompress_file('strip',)
Entering '07'
07/push/maint/f779163/travis-12136-failed/8.txt:ERROR: datalad.tests.test_archives.test_decompress_file('strip',)
16/cron/20210716T190809/86a55c8/travis-12152-failed/9.txt:ERROR: datalad.tests.test_archives.test_decompress_file('strip',)
19/pr/5799/9befbf4/travis-12166-failed/8.txt:ERROR: datalad.tests.test_archives.test_decompress_file('strip',)
23/pr/5817/9449526/travis-12191-failed/8.txt:ERROR: datalad.tests.test_archives.test_decompress_file('strip',)
26/push/master/66bea22/travis-12197-failed/8.txt:ERROR: datalad.tests.test_archives.test_decompress_file('strip',)
27/push/master/258b5c5/travis-12221-failed/8.txt:ERROR: datalad.tests.test_archives.test_decompress_file('strip',)
Entering '08'
05/pr/5868/9412222/travis-12292-failed/8.txt:ERROR: datalad.tests.test_archives.test_decompress_file('strip',)
09/push/master/d926ced/travis-12316-failed/8.txt:ERROR: datalad.tests.test_archives.test_decompress_file('strip',)
10/pr/5883/c260430/travis-12324-failed/8.txt:ERROR: datalad.tests.test_archives.test_decompress_file('strip',)
19/pr/5917/0f00733/travis-12401-failed/8.txt:ERROR: datalad.tests.test_archives.test_decompress_file('strip',)
Entering '09'
01/pr/5945/8aad62e/travis-12431-failed/8.txt:ERROR: datalad.tests.test_archives.test_decompress_file('strip',)

```

**Comment by adswa** [comment]
should this have been closed with the merge of  #6064?

**Comment by yarikoptic** [comment]
not yet sure: https://github.com/datalad/datalad/pull/6137#issuecomment-961182965

**Comment by mih** [comment]
This test continues to fail on NFS with high probability. The pattern is

```
======================================================================
FAIL: datalad.tests.test_archives.test_decompress_file('strip',)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/tmp/dl-miniconda-zoboauns/lib/python3.9/site-packages/nose/case.py", line 198, in runTest
    self.test(*self.arg)
  File "/tmp/dl-miniconda-zoboauns/lib/python3.9/site-packages/datalad/tests/utils.py", line 556, in _wrap_with_tree
    return t(*(arg + (d,)), **kw)
  File "/tmp/dl-miniconda-zoboauns/lib/python3.9/site-packages/datalad/tests/test_archives.py", line 93, in check_decompress_file
    assert_true(op.exists(op.join(testpath, '3.txt')))
AssertionError: False is not true
```

From my POV this is the one most frequent cause of travis failiures. Currently on master

https://app.travis-ci.com/github/datalad/datalad/jobs/551959691/config

**Comment by yarikoptic** [comment]
FWIW, just now realized that in datalad/git-annex we run only annex'es own tests under NFS, and DataLad is not tested.  There were a good number of related to pidlocking changes recently (like a week ago) which might have related and no releases yet.  IIRC I haven't reproduced it locally to be able to figure out what is going on. 

<details>
<summary>Also interesting that it happens primarily (if not *only*) in `strip` mode
</summary> 

```shell
(git)smaug:/mnt/datasets/datalad/ci/logs[master]git
$> datalad foreach-dataset -r 'git grep -h datalad.tests.test_archives.test_decompress_file.* | cat || :' | grep -v '\.\.\. ok' | sort | uniq -c
[WARNING] Got jobs=6 but we cannot use threads with Pythons versions prior 3.8.0. Will run serially 
      1 [00:31:53] datalad.tests.test_archives.test_decompress_file(<class 'NotImplementedError'>, <function check_decompress_file at 0x0000017CC1C1C0D0>, 'unknown') ... ERROR
      1 [00:31:53] datalad.tests.test_archives.test_decompress_file(None,) ... ERROR
      1 [00:31:53] datalad.tests.test_archives.test_decompress_file('strip',) ... ERROR
      1 [00:36:28] ERROR: datalad.tests.test_archives.test_decompress_file(<class 'NotImplementedError'>, <function check_decompress_file at 0x0000017CC1C1C0D0>, 'unknown')
      1 [00:36:28] ERROR: datalad.tests.test_archives.test_decompress_file(None,)
      1 [00:36:28] ERROR: datalad.tests.test_archives.test_decompress_file('strip',)
      1 action summary:
      1 datalad.tests.test_archives.test_decompress_file(<class 'NotImplementedError'>, <function check_decompress_file at 0x7fa7adc22c10>, 'unknown') ... 2021-10-07 21:03:39,535 [Level 5] Creating a tree under /tmp/datalad-nfs-jHtN9.nfs/datalad-rwqxtrxk 
      1 datalad.tests.test_archives.test_decompress_file(None,) ... 2021-10-07 21:03:39,278 [Level 5] Creating a tree under /tmp/datalad-nfs-jHtN9.nfs/datalad-i5enj06v 
      1 datalad.tests.test_archives.test_decompress_file('strip',) ... 2021-10-07 21:03:39,405 [Level 5] Creating a tree under /tmp/datalad-nfs-jHtN9.nfs/datalad-km6ve9tb 
     25 ERROR: datalad.tests.test_archives.test_decompress_file('strip',)
     14 FAIL: datalad.tests.test_archives.test_decompress_file('strip',)
```
</details>

**Comment by mih** [comment]
Never seen it outside strip mode, indeed.
