### ISSUE TITLE
download_url(zip_link, archive=True) leads to AnnexBatchCommandError

### ISSUE THREAD

**Issue by joeyzhou98** [datalad/datalad#4525]
#### What is the problem?
When using the datalad Python API via datalad.api.Dataset.download_url(zip_link, archive=True), the command ends up with the following error:
```d.download_url("https://zenodo.org/api/files/ba88b736-95bd-492a-be83-5f16d0f38ba5/data.zip?access_token=w4M00bgKOLzWDCHdFGeXc2wzaE9ftmedZAcneqTQEO9qQK4G3A7ez7CfOS7Y", archive=True)
[INFO   ] Downloading <zip_link> into '/home/users/jzhou/test/dataset/' 
[INFO   ] Adding content of the archive /home/users/jzhou/test/dataset/data.zip into annex <AnnexRepo path=/home/users/jzhou/test/dataset (<class 'datalad.support.annexrepo.AnnexRepo'>)> 
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/users/jzhou/miniconda3/lib/python3.7/site-packages/datalad/distribution/dataset.py", line 500, in apply_func
    return f(**kwargs)
  File "/home/users/jzhou/miniconda3/lib/python3.7/site-packages/datalad/interface/utils.py", line 492, in eval_func
    return return_func(generator_func)(*args, **kwargs)
  File "/home/users/jzhou/miniconda3/lib/python3.7/site-packages/datalad/interface/utils.py", line 480, in return_func
    results = list(results)
  File "/home/users/jzhou/miniconda3/lib/python3.7/site-packages/datalad/interface/utils.py", line 411, in generator_func
    allkwargs):
  File "/home/users/jzhou/miniconda3/lib/python3.7/site-packages/datalad/interface/utils.py", line 527, in _process_results
    for res in results:
  File "/home/users/jzhou/miniconda3/lib/python3.7/site-packages/datalad/interface/download_url.py", line 247, in __call__
    add_archive_content(path, annex=ds.repo, delete=True)
  File "/home/users/jzhou/miniconda3/lib/python3.7/site-packages/datalad/interface/add_archive_content.py", line 456, in __call__
    batch=True)
  File "/home/users/jzhou/miniconda3/lib/python3.7/site-packages/datalad/support/gitrepo.py", line 230, in newfunc
    return func(self, file_new, *args, **kwargs)
  File "/home/users/jzhou/miniconda3/lib/python3.7/site-packages/datalad/support/annexrepo.py", line 1940, in add_url_to_file
    % (url, str(out_json)))
datalad.support.exceptions.AnnexBatchCommandError: AnnexBatchCommandError: command 'addurl'
Error, annex reported failure for addurl (url='dl+archive:MD5E-s195581928--c6b084b6435d4c3d51f8c7221903e366.zip#path=candidates/913174/V1/images/loris_913174_V1_fMRI_009.mnc&size=8034497'): {'command': 'addurl', 'note': 'from datalad-archives\nto candidates/913174/V1/images/loris_913174_V1_fMRI_009.mnc', 'success': False, 'error-messages': [], 'file': 'candidates/913174/V1/images/loris_913174_V1_fMRI_009.mnc'}
```
I can't share the link for the zip file publicly but if this error is new and no solution works, then I can share the link and zip file used to reproduce the problem in private
#### What steps will reproduce the problem?
```from datalad import api
d = api.Dataset("dataset")
d.create()
d.download_url(zip_link, archive=True)
```
#### What version of DataLad are you using (run `datalad --version`)? On what operating system (consider running `datalad wtf`)?
datalad 0.12.6
datalad wtf output:
```# WTF
## configuration <SENSITIVE, report disabled by configuration>
## datalad 
  - full_version: 0.12.6
  - version: 0.12.6
## dependencies 
  - appdirs: 1.4.3
  - boto: 2.49.0
  - cmd:7z: 16.02
  - cmd:annex: 8.20200309-g07fcace
  - cmd:bundled-git: 2.23.0
  - cmd:git: 2.23.0
  - cmd:system-git: 2.23.0
  - cmd:system-ssh: 7.9p1
  - git: 3.1.1
  - gitdb: 4.0.4
  - humanize: 2.4.0
  - iso8601: 0.1.12
  - keyring: 21.2.0
  - keyrings.alt: 3.4.0
  - msgpack: 1.0.0
  - requests: 2.23.0
  - wrapt: 1.12.1
## environment 
  - GIT_PYTHON_GIT_EXECUTABLE: /home/users/jzhou/miniconda3/bin/git
  - LANG: en_CA.UTF-8
  - LANGUAGE: en_CA:en
  - PATH: /home/users/jzhou/.local/bin:/home/users/jzhou/miniconda3/bin:/home/users/jzhou/miniconda3/condabin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/usr/games:/usr/local/games:/snap/bin
## extensions 
## git-annex 
  - build flags: 
    - Assistant
    - Webapp
    - Pairing
    - S3
    - WebDAV
    - Inotify
    - DBus
    - DesktopNotify
    - TorrentParser
    - MagicMime
    - Feeds
    - Testsuite
  - dependency versions: 
    - aws-0.21.1
    - bloomfilter-2.0.1.0
    - cryptonite-0.25
    - DAV-1.3.4
    - feed-1.2.0.1
    - ghc-8.6.5
    - http-client-0.6.4
    - persistent-sqlite-2.9.3
    - torrent-10000.1.1
    - uuid-1.3.13
    - yesod-1.6.0.1
  - key/value backends: 
    - SHA256E
    - SHA256
    - SHA512E
    - SHA512
    - SHA224E
    - SHA224
    - SHA384E
    - SHA384
    - SHA3_256E
    - SHA3_256
    - SHA3_512E
    - SHA3_512
    - SHA3_224E
    - SHA3_224
    - SHA3_384E
    - SHA3_384
    - SKEIN256E
    - SKEIN256
    - SKEIN512E
    - SKEIN512
    - BLAKE2B256E
    - BLAKE2B256
    - BLAKE2B512E
    - BLAKE2B512
    - BLAKE2B160E
    - BLAKE2B160
    - BLAKE2B224E
    - BLAKE2B224
    - BLAKE2B384E
    - BLAKE2B384
    - BLAKE2BP512E
    - BLAKE2BP512
    - BLAKE2S256E
    - BLAKE2S256
    - BLAKE2S160E
    - BLAKE2S160
    - BLAKE2S224E
    - BLAKE2S224
    - BLAKE2SP256E
    - BLAKE2SP256
    - BLAKE2SP224E
    - BLAKE2SP224
    - SHA1E
    - SHA1
    - MD5E
    - MD5
    - WORM
    - URL
  - operating system: linux x86_64
  - remote types: 
    - git
    - gcrypt
    - p2p
    - S3
    - bup
    - directory
    - rsync
    - web
    - bittorrent
    - webdav
    - adb
    - tahoe
    - glacier
    - ddar
    - git-lfs
    - hook
    - external
  - supported repository versions: 
    - 8
  - upgrade supported from repository versions: 
    - 0
    - 1
    - 2
    - 3
    - 4
    - 5
    - 6
    - 7
  - version: 8.20200309-g07fcace
## location 
  - path: /home/users/jzhou/test
  - type: directory
## metadata_extractors 
  - annex: 
    - load_error: None
    - module: datalad.metadata.extractors.annex
    - version: None
  - audio: 
    - load_error: No module named 'mutagen' [audio.py:<module>:17]
    - module: datalad.metadata.extractors.audio
  - datacite: 
    - load_error: None
    - module: datalad.metadata.extractors.datacite
    - version: None
  - datalad_core: 
    - load_error: None
    - module: datalad.metadata.extractors.datalad_core
    - version: None
  - datalad_rfc822: 
    - load_error: None
    - module: datalad.metadata.extractors.datalad_rfc822
    - version: None
  - exif: 
    - load_error: No module named 'exifread' [exif.py:<module>:16]
    - module: datalad.metadata.extractors.exif
  - frictionless_datapackage: 
    - load_error: None
    - module: datalad.metadata.extractors.frictionless_datapackage
    - version: None
  - image: 
    - load_error: No module named 'PIL' [image.py:<module>:16]
    - module: datalad.metadata.extractors.image
  - xmp: 
    - load_error: No module named 'libxmp' [xmp.py:<module>:20]
    - module: datalad.metadata.extractors.xmp
## python 
  - implementation: CPython
  - version: 3.6.9
## system 
  - distribution: Ubuntu/18.04/bionic
  - encoding: 
    - default: utf-8
    - filesystem: utf-8
    - locale.prefered: UTF-8
  - max_path_length: 278
  - name: Linux
  - release: 4.15.0-99-generic
  - type: posix
  - version: #100-Ubuntu SMP Wed Apr 22 20:32:56 UTC 2020
```

**Comment by yarikoptic** [comment]
I failed to replicate on a simplistic, no authentication to conp case
<details>
<summary>script test-ziprchive.py</summary> 

```python
from datalad import api
from datalad.utils import chpwd
import tempfile

zip_link = "http://www.onerussian.com/tmp/testzip.zip"
with chpwd(tempfile.mkdtemp()):
    d = api.Dataset("dataset")
    print(d.path)
    d.create()
    d.download_url(zip_link, archive=True)

```
</details>

<details>
<summary>and here is output</summary> 

```shell
$> python test-ziprchive.py
/home/yoh/.tmp/tmpza8xxp54/dataset
[INFO   ] Creating a new annex repo at /home/yoh/.tmp/tmpza8xxp54/dataset 
[INFO   ] Downloading 'http://www.onerussian.com/tmp/testzip.zip' into '/home/yoh/.tmp/tmpza8xxp54/dataset/'   
[INFO   ] Adding content of the archive /home/yoh/.tmp/tmpza8xxp54/dataset/testzip.zip into annex <AnnexRepo path=/home/yoh/.tmp/tmpza8xxp54/dataset (<class 'datalad.support.annexrepo.AnnexRepo'>)> 
[INFO   ] Initiating special remote datalad-archives 
[INFO   ] Finished adding /home/yoh/.tmp/tmpza8xxp54/dataset/testzip.zip: Files processed: 2, +annex: 2 
```
</details>
so I guess I need to find some "public" conp dataset to which I do have access and which has a .zip file.  E.g. I have access to https://openpreventad.loris.ca/ but I do not see any .zip mentioned in it.

**Comment by glatard** [comment]
After investigation, this was related to discrepancies between user IDs in the local environment and in a mounted NFS dir on which datalad was operating. I doubt this is due to a problem in datalad or git-annex but will re-open in case it is. Thanks for the help @yarikoptic and sorry for the false alarm!

**Comment by yarikoptic** [comment]
ok, no problem, let's close then for now
