### ISSUE TITLE
cookies dbm complaints (ignored exception) upon exit of `nose`

### ISSUE THREAD

**Issue by yarikoptic** [datalad/datalad#4542]
eg
```shell
$> python -m nose -s -v -x datalad/support/tests/test_cookies.py 
datalad.support.tests.test_cookies.test_no_blows ... Exception ignored in: <function _Database.close at 0x7fcdcf8b83a0>
Traceback (most recent call last):
  File "/home/yoh/anaconda-5.2.0-2.7/envs/datalad-py3.8/lib/python3.8/dbm/dumb.py", line 274, in close
    self._commit()
  File "/home/yoh/anaconda-5.2.0-2.7/envs/datalad-py3.8/lib/python3.8/dbm/dumb.py", line 129, in _commit
    with self._io.open(self._dirfile, 'w', encoding="Latin-1") as f:
FileNotFoundError: [Errno 2] No such file or directory: '/home/yoh/.tmp/datalad_temp_test_no_blowsquzk717v/mycookies.dir'
ok
Versions: appdirs=1.4.3 boto=2.49.0 cmd:7z=16.02 cmd:annex=8.20200309-g07fcace cmd:bundled-git=2.26.2 cmd:git=2.26.2 cmd:system-git=2.26.2 cmd:system-ssh=8.0p1 git=3.1.2 gitdb=4.0.5 humanize=2.4.0 iso8601=0.1.12 keyring=21.2.1 keyrings.alt=3.1 msgpack=1.0.0 requests=2.23.0 scrapy=2.1.0 wrapt=1.12.1
Obscure filename: str=b' "\';a&b&c\xce\x94\xd0\x99\xd7\xa7\xd9\x85\xe0\xb9\x97\xe3\x81\x82 `| ' repr=' "\';a&b&cΔЙקم๗あ `| '
Encodings: default='utf-8' filesystem='utf-8' locale.prefered='UTF-8'
Environment: PATH='/home/yoh/anaconda-5.2.0-2.7/envs/datalad-py3.8/bin:/home/yoh/gocode/bin:/home/yoh/gocode/bin:/home/yoh/bin:/home/yoh/.local/bin:/usr/local/bin:/usr/bin:/bin:/usr/local/games:/usr/games:/sbin:/usr/sbin:/usr/local/sbin' LANG='en_US.UTF-8' GIT_PAGER='less --no-init --quit-if-one-screen' GIT_PYTHON_GIT_EXECUTABLE='/home/yoh/anaconda-5.2.0-2.7/envs/datalad-py3.8/bin/git'

----------------------------------------------------------------------
Ran 1 test in 0.586s

OK
```
or abit differently (with our warning in addition):

```shell
$> python -m nose -s -v -x datalad/downloaders/tests/test_http.py
datalad.downloaders.tests.test_http.test_docstring ... ok
...
GIT_PYTHON_GIT_EXECUTABLE='/home/yoh/anaconda-5.2.0-2.7/envs/datalad-py3.8/bin/git'
[WARNING] Failed to save possibly updated 2 cookies (portal.nersc.gov, db.humanconnectome.org): [Errno 2] No such file or directory: '/home/yoh/.tmp/datalad_temp_t9nrj9v0/.config/datalad/cookies.dat' [dumb.py:_setval:172] 
Exception ignored in: <function _Database.close at 0x7f74fc9be040>
Traceback (most recent call last):
  File "/home/yoh/anaconda-5.2.0-2.7/envs/datalad-py3.8/lib/python3.8/dbm/dumb.py", line 274, in close
    self._commit()
  File "/home/yoh/anaconda-5.2.0-2.7/envs/datalad-py3.8/lib/python3.8/dbm/dumb.py", line 129, in _commit
    with self._io.open(self._dirfile, 'w', encoding="Latin-1") as f:
FileNotFoundError: [Errno 2] No such file or directory: '/home/yoh/.tmp/datalad_temp_t9nrj9v0/.config/datalad/cookies.dir'

----------------------------------------------------------------------
Ran 17 tests in 13.804s

OK
```

In both cases it nohow effects the exit status (good) (was done by #3611).  Even if we pacify our own warning -- I have no clue how to make the unhandled exception trace to go away... I have tried but failed in many ways ;-)

**Comment by mih** [comment]
Thank you for reporting this issue!

However, at this point I am closing it at a time of ~600 open issues, in an attempt to regain control over the issue tracker. This particular issue was posted more than 6 months ago, has not received a single response, and does not describe an immediate software defect. *Closing this issue does not imply that it is not relevant*. If any reader objects the closing of this issue, please feel more than free to reopen it with an update on how it is relevant for the current state of the project, and which concrete actions to address it are ongoing or planned.
