### ISSUE TITLE
2 test_ssh* tests failures while running under conda

### ISSUE THREAD

**Issue by yarikoptic** [datalad/datalad#4554]
```
datalad.tests.test_version.test__version__ ... ok
[WARNING] Failed to save possibly updated 2 cookies (portal.nersc.gov, db.humanconnectome.org): [Errno 2] No such file or directory: '/home/yoh/.tmp/datalad_temp_jlb083r7/.config/datalad/cookies.dat' [dumb.py:_setval:172] 
Exception ignored in: <function _Database.close at 0x7fc7d9475310>
Traceback (most recent call last):
  File "/home/yoh/anaconda-5.2.0-2.7/envs/datalad-py3.8/lib/python3.8/dbm/dumb.py", line 274, in close
    self._commit()
  File "/home/yoh/anaconda-5.2.0-2.7/envs/datalad-py3.8/lib/python3.8/dbm/dumb.py", line 129, in _commit
    with self._io.open(self._dirfile, 'w', encoding="Latin-1") as f:
FileNotFoundError: [Errno 2] No such file or directory: '/home/yoh/.tmp/datalad_temp_jlb083r7/.config/datalad/cookies.dir'

======================================================================
FAIL: datalad.support.tests.test_sshconnector.test_ssh_git_props
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/yoh/anaconda-5.2.0-2.7/envs/datalad-py3.8/lib/python3.8/site-packages/nose/case.py", line 198, in runTest
    self.test(*self.arg)
  File "/home/yoh/proj/datalad/datalad-maint/datalad/tests/utils.py", line 161, in newfunc
    return func(*args, **kwargs)
  File "/home/yoh/proj/datalad/datalad-maint/datalad/tests/utils.py", line 213, in newfunc
    return func(*args, **kwargs)
  File "/home/yoh/proj/datalad/datalad-maint/datalad/support/tests/test_sshconnector.py", line 270, in test_ssh_git_props
    eq_(ssh.get_annex_version(),
AssertionError: '8.20200501+git61-g64e081d58-1~ndall+1' != LooseVersion ('8.20200309-g07fcace')

======================================================================
FAIL: datalad.support.tests.test_sshrun.test_ssh_option
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/yoh/anaconda-5.2.0-2.7/envs/datalad-py3.8/lib/python3.8/site-packages/nose/case.py", line 198, in runTest
    self.test(*self.arg)
  File "/home/yoh/proj/datalad/datalad-maint/datalad/tests/utils.py", line 161, in newfunc
    return func(*args, **kwargs)
  File "/home/yoh/proj/datalad/datalad-maint/datalad/tests/utils.py", line 213, in newfunc
    return func(*args, **kwargs)
  File "/home/yoh/proj/datalad/datalad-maint/datalad/support/tests/test_sshrun.py", line 73, in test_ssh_option
    assert_equal(cmo.out.strip(), "hackbert")
AssertionError: '' != 'hackbert'
+ hackbert

----------------------------------------------------------------------
Ran 1101 tests in 2378.120s

FAILED (SKIP=56, failures=2)
Versions: appdirs=1.4.3 boto=2.49.0 cmd:7z=16.02 cmd:annex=8.20200309-g07fcace cmd:bundled-git=2.26.2 cmd:git=2.26.2 cmd:system-git=2.26.2 cmd:system-ssh=8.0p1 git=3.1.2 gitdb=4.0.5 humanize=2.4.0 iso8601=0.1.12 keyring=21.2.1 keyrings.alt=3.1 msgpack=1.0.0 patoolib=1.12 requests=2.23.0 scrapy=2.1.0 tqdm=4.46.0 wrapt=1.12.1
Obscure filename: str=b' "\';a&b&c\xce\x94\xd0\x99\xd7\xa7\xd9\x85\xe0\xb9\x97\xe3\x81\x82 `| ' repr=' "\';a&b&cΔЙקم๗あ `| '
Encodings: default='utf-8' filesystem='utf-8' locale.prefered='UTF-8'
Environment: PATH='/home/yoh/anaconda-5.2.0-2.7/envs/datalad-py3.8/bin:/home/yoh/gocode/bin:/home/yoh/gocode/bin:/home/yoh/bin:/home/yoh/.local/bin:/usr/local/bin:/usr/bin:/bin:/usr/local/games:/usr/games:/sbin:/usr/sbin:/usr/local/sbin' LANG='en_US.UTF-8' GIT_PAGER='less --no-init --quit-if-one-screen' GIT_PYTHON_GIT_EXECUTABLE='/home/yoh/anaconda-5.2.0-2.7/envs/datalad-py3.8/bin/git'
```

**Comment by kyleam** [comment]
Are these failures just surfacing now because SSH tests aren't usually executed when testing the datalad conda package?

> datalad.support.tests.test_sshrun.test_ssh_option

Sorry, I'm to blame for this one.  I added that test in 979f84d5c (BF: sshrun: Accept -o flag, 2019-08-22).  It looks like I wasn't quite sure it was a good idea:

https://github.com/datalad/datalad/blob/4300660f886e9272992b29e6150e35a9ca8e56de/datalad/support/tests/test_sshrun.py#L66-L68

**Comment by kyleam** [comment]
These failures should be resolved by #4557 and #4558.

**Comment by kyleam** [comment]
Those PRs have been merged (to maint and master).  I think we should be set, but please reopen if I'm mistaken.

**Comment by yarikoptic** [comment]
thank you @kyleam
