### ISSUE TITLE
git 2.27.0~rc2-1 seems to break GitPython (2.26.2-1) ok

### ISSUE THREAD

**Issue by yarikoptic** [datalad/datalad#4592]
Tried to build 0.12.7 for debian and it failed with many failures like
```
======================================================================
ERROR: datalad.distribution.tests.test_update.test_update_git_smoke
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/nose/case.py", line 197, in runTest
    self.test(*self.arg)
  File "/build/datalad-0.12.7/.pybuild/cpython3_3.8_datalad/build/datalad/tests/utils.py", line 732, in newfunc
    return t(*(arg + (filename,)), **kw)
  File "/build/datalad-0.12.7/.pybuild/cpython3_3.8_datalad/build/datalad/tests/utils.py", line 732, in newfunc
    return t(*(arg + (filename,)), **kw)
  File "/build/datalad-0.12.7/.pybuild/cpython3_3.8_datalad/build/datalad/distribution/tests/test_update.py", line 181, in test_update_git_smoke
    target.update(recursive=True, merge=True), 1,
  File "/build/datalad-0.12.7/.pybuild/cpython3_3.8_datalad/build/datalad/distribution/dataset.py", line 500, in apply_func
    return f(**kwargs)
  File "/build/datalad-0.12.7/.pybuild/cpython3_3.8_datalad/build/datalad/interface/utils.py", line 492, in eval_func
    return return_func(generator_func)(*args, **kwargs)
  File "/build/datalad-0.12.7/.pybuild/cpython3_3.8_datalad/build/datalad/interface/utils.py", line 480, in return_func
    results = list(results)
  File "/build/datalad-0.12.7/.pybuild/cpython3_3.8_datalad/build/datalad/interface/utils.py", line 399, in generator_func
    for r in _process_results(
  File "/build/datalad-0.12.7/.pybuild/cpython3_3.8_datalad/build/datalad/interface/utils.py", line 527, in _process_results
    for res in results:
  File "/build/datalad-0.12.7/.pybuild/cpython3_3.8_datalad/build/datalad/distribution/update.py", line 174, in __call__
    for fr in _update_repo(ds, sibling_, reobtain_data):
  File "/build/datalad-0.12.7/.pybuild/cpython3_3.8_datalad/build/datalad/distribution/update.py", line 240, in _update_repo
    repo.pull(remote=remote, refspec=active_branch)
  File "/build/datalad-0.12.7/.pybuild/cpython3_3.8_datalad/build/datalad/support/gitrepo.py", line 2243, in pull
    return self._call_gitpy_with_progress(
  File "/build/datalad-0.12.7/.pybuild/cpython3_3.8_datalad/build/datalad/support/gitrepo.py", line 2209, in _call_gitpy_with_progress
    ret = callable(**git_kwargs)
  File "/usr/lib/python3/dist-packages/git/remote.py", line 812, in pull
    res = self._get_fetch_info_from_stderr(proc, progress)
  File "/usr/lib/python3/dist-packages/git/remote.py", line 708, in _get_fetch_info_from_stderr
    output.extend(FetchInfo._from_line(self.repo, err_line, fetch_line)
  File "/usr/lib/python3/dist-packages/git/remote.py", line 708, in <genexpr>
    output.extend(FetchInfo._from_line(self.repo, err_line, fetch_line)
  File "/usr/lib/python3/dist-packages/git/remote.py", line 292, in _from_line
    raise ValueError("Failed to parse line: %r" % line)
ValueError: Failed to parse line: '  git config pull.rebase false  # merge (the default strategy)'
```
so I guess for now will build for everything else by recent debian sid

edit FWIW
- bug known to debian: https://bugs.debian.org/cgi-bin/bugreport.cgi?bug=961702  but I do not think was forwarded upstream, neither reassigned to git - just told that GitPython should not do that (parsing)
- I had tested current master of git -- the same trouble. bisecting now from v2.26.2

**Comment by yarikoptic** [comment]
ok, boils down to intended change in git output:

d18c950a69f3a24e1e3add3d9fc427641f53e12b is the first bad commit
commit d18c950a69f3a24e1e3add3d9fc427641f53e12b
Author: Alex Henrie <alexhenrie24@gmail.com>
Date:   Mon Mar 9 21:54:20 2020 -0600

    pull: warn if the user didn't say whether to rebase or to merge
    
    Often novice Git users forget to say "pull --rebase" and end up with an
    unnecessary merge from upstream. What they usually want is either "pull
    --rebase" in the simpler cases, or "pull --ff-only" to update the copy
    of main integration branches, and rebase their work separately. The
    pull.rebase configuration variable exists to help them in the simpler
    cases, but there is no mechanism to make these users aware of it.
    
    Issue a warning message when no --[no-]rebase option from the command
    line and no pull.rebase configuration variable is given. This will
    inconvenience those who never want to "pull --rebase", who haven't had
    to do anything special, but the cost of the inconvenience is paid only
    once per user, which should be a reasonable cost to help a number of new
    users.
    
    Signed-off-by: Alex Henrie <alexhenrie24@gmail.com>
    Signed-off-by: Junio C Hamano <gitster@pobox.com>

 builtin/pull.c               | 16 ++++++++++++++++
 t/t5521-pull-options.sh      | 22 +++++++++++-----------
 t/t7601-merge-pull-config.sh | 38 ++++++++++++++++++++++++++++++++++++++
 3 files changed, 65 insertions(+), 11 deletions(-)

submitted to GitPython: https://github.com/gitpython-developers/GitPython/issues/1014

**Comment by kyleam** [comment]
I see you already fixed this upstream and that made it into a release.  I'm assuming that's sufficient to close this (especially given the remaining uses of gitpython have been pruned in 0.13), but please reopen if I'm wrong.
