### ISSUE TITLE
diff -r: kabooms in ls-tree call

### ISSUE THREAD

**Issue by yarikoptic** [datalad/datalad#4614]
yet to dig out details, just wanted to report so I don't forget where etc

```shell
bids@rolando:/inbox/BIDS/Gobbini/Matteo/1037_budapest$ datalad diff -f c10fa46438058e49a5c886e12cc548db94bd9915 -t HEAD  -r
 modified: .heudiconv (dataset)
CommandError: 'git ls-tree e7faecfa115b683ac3d7cb1e9d293ce74b582ff7 -z -r --full-tree -l' failed with exitcode 128 under /inbox/BIDS/Gobbini/Matteo/1037_budapest/.heudiconv
fatal: not a tree object
```
and everything seems to be "clean":
```shell
bids@rolando:/inbox/BIDS/Gobbini/Matteo/1037_budapest$ git status
On branch master
nothing to commit, working tree clean

bids@rolando:/inbox/BIDS/Gobbini/Matteo/1037_budapest$ datalad status
nothing to save, working tree clean
...
```

not sure yet how that specific objectid came about, but FWIW

```shell
bids@rolando:/inbox/BIDS/Gobbini/Matteo/1037_budapest$ cd .heudiconv/
bids@rolando:/inbox/BIDS/Gobbini/Matteo/1037_budapest/.heudiconv$ git show e7faecfa115b683ac3d7cb1e9d293ce74b582ff7
fatal: bad object e7faecfa115b683ac3d7cb1e9d293ce74b582ff7
bids@rolando:/inbox/BIDS/Gobbini/Matteo/1037_budapest/.heudiconv$ git fsck
Checking object directories: 100% (256/256), done.
dangling blob e69de29bb2d1d6434b8b29ae775ad8c2e48c5391
bids@rolando:/inbox/BIDS/Gobbini/Matteo/1037_budapest/.heudiconv$ git show e7faecfa115b683ac3d7cb1e9d293ce74b582ff7
fatal: bad object e7faecfa115b683ac3d7cb1e9d293ce74b582ff7
bids@rolando:/inbox/BIDS/Gobbini/Matteo/1037_budapest/.heudiconv$ cd ..
bids@rolando:/inbox/BIDS/Gobbini/Matteo/1037_budapest$ git status
On branch master
nothing to commit, working tree clean
bids@rolando:/inbox/BIDS/Gobbini/Matteo/1037_budapest$ git fsck
Checking object directories: 100% (256/256), done.
Checking objects: 100% (6145/6145), done.
dangling blob e69de29bb2d1d6434b8b29ae775ad8c2e48c5391
dangling tree 93750247c99027f5f3023d2786d79b9f120ccd9b
bids@rolando:/inbox/BIDS/Gobbini/Matteo/1037_budapest$ datalad diff -f c10fa46438058e49a5c886e12cc548db94bd9915 -t HEAD  -r
 modified: .heudiconv (dataset)
CommandError: 'git ls-tree e7faecfa115b683ac3d7cb1e9d293ce74b582ff7 -z -r --full-tree -l' failed with exitcode 128 under /inbox/BIDS/Gobbini/Matteo/1037_budapest/.heudiconv
fatal: not a tree object
```

**Comment by yarikoptic** [comment]
well, I guess it is just a case where `.heudiconv/` submodule was hard reset at some point and later `gc`ed so that original state
```
bids@rolando:/inbox/BIDS/Gobbini/Matteo/1037_budapest$ git diff c10fa46438058e49a5c886e12cc548db94bd9915..HEAD -- .heudiconv
diff --git a/.heudiconv b/.heudiconv
index e7faecf..651c697 160000
--- a/.heudiconv
+++ b/.heudiconv
@@ -1 +1 @@
-Subproject commit e7faecfa115b683ac3d7cb1e9d293ce74b582ff7
+Subproject commit 651c6971842996b620836900c3b0a8cf1bd9a5dd
```
is no longer present. In such a case of cause `diff` cannot provide any sensible output for this subdataset. But may be instead of crashing it should just issue an "impossible" message for this subdataset path, probably also with "modified" for the dataset as a whole since it knows that it was modified (checksum changed).

BTW - one more use case here for me for `--recursion-limit 3` to overcome this issue and avoid going deeper than actually needed.

**Comment by yarikoptic** [comment]
ran into this (?) case now with 

<details>
<summary>datalad push --since</summary> 


```shell
$> datalad -l debug --dbg push --to datalad-public --since=^ -r
...
[DEBUG  ] Diff Dataset(/mnt/datasets/datalad/crawl/dandi/dandisets/000069) from '08a8d717f83ea22d5dabe0c3bcd6d66d932112f3' to '61cf9e8789fc19ac8cdcbc624f7b82971e48b0be'
[DEBUG  ] AnnexRepo(/mnt/datasets/datalad/crawl/dandi/dandisets/000069).get_content_info(...)
[DEBUG  ] Query repo: ['ls-tree', '61cf9e8789fc19ac8cdcbc624f7b82971e48b0be', '-z', '-r', '--full-tree', '-l']
[DEBUG  ] Run ['git', '-c', 'diff.ignoreSubmodules=none', '-c', 'core.quotepath=false', 'ls-tree', '61cf9e8789fc19ac8cdcbc624f7b82971e48b0be', '-z', '-r', '--full-tree', '-l'] (protocol_class=GeneratorStdOutErrCapture) (cwd=/mnt/datasets/datalad/crawl/dandi/dandisets/000069)
Traceback (most recent call last):
  File "/usr/bin/datalad", line 33, in <module>
    sys.exit(load_entry_point('datalad==1.1.4', 'console_scripts', 'datalad')())
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3/dist-packages/datalad/cli/main.py", line 143, in main
    _run(cmdlineargs)
  File "/usr/lib/python3/dist-packages/datalad/cli/main.py", line 167, in _run
    ret = _run_with_debugger(namespace) \
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3/dist-packages/datalad/cli/main.py", line 181, in _run_with_debugger
    return cmdlineargs.func(cmdlineargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3/dist-packages/datalad/cli/exec.py", line 104, in call_from_parser
    ret = list(ret)
          ^^^^^^^^^
  File "/usr/lib/python3/dist-packages/datalad/interface/base.py", line 872, in _execute_command_
    for r in _process_results(
  File "/usr/lib/python3/dist-packages/datalad/interface/utils.py", line 319, in _process_results
    for res in results:
  File "/usr/lib/python3/dist-packages/datalad/core/distributed/push.py", line 251, in __call__
    for dspath, dsrecords in ds_spec:
  File "/usr/lib/python3/dist-packages/datalad/core/distributed/push.py", line 322, in _datasets_since_
    for res in diff_dataset(
  File "/usr/lib/python3/dist-packages/datalad/core/local/diff.py", line 272, in diff_dataset
    for res in _diff_ds(
  File "/usr/lib/python3/dist-packages/datalad/core/local/diff.py", line 430, in _diff_ds
    yield from _diff_ds(*call_args, **call_kwargs)
  File "/usr/lib/python3/dist-packages/datalad/core/local/diff.py", line 430, in _diff_ds
    yield from _diff_ds(*call_args, **call_kwargs)
  File "/usr/lib/python3/dist-packages/datalad/core/local/diff.py", line 430, in _diff_ds
    yield from _diff_ds(*call_args, **call_kwargs)
  File "/usr/lib/python3/dist-packages/datalad/core/local/diff.py", line 331, in _diff_ds
    diff_state = repo.diffstatus(
                 ^^^^^^^^^^^^^^^^
  File "/usr/lib/python3/dist-packages/datalad/support/gitrepo.py", line 3128, in diffstatus
    to_state = self.get_content_info(paths=ppaths, ref=to)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3/dist-packages/datalad/support/gitrepo.py", line 2901, in get_content_info
    stdout = self.call_git(
             ^^^^^^^^^^^^^^
  File "/usr/lib/python3/dist-packages/datalad/dataset/gitrepo.py", line 460, in call_git
    return "".join(
           ^^^^^^^^
  File "/usr/lib/python3/dist-packages/datalad/dataset/gitrepo.py", line 524, in call_git_items_
    for file_no, line in self._generator_call_git(
  File "/usr/lib/python3/dist-packages/datalad/dataset/gitrepo.py", line 362, in _generator_call_git
    for file_no, content in generator:
  File "<frozen _collections_abc>", line 330, in __next__
  File "/usr/lib/python3/dist-packages/datalad/runner/nonasyncrunner.py", line 99, in send
    return self._locked_send(message)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3/dist-packages/datalad/runner/nonasyncrunner.py", line 124, in _locked_send
    self._check_result()
  File "/usr/lib/python3/dist-packages/datalad/runner/nonasyncrunner.py", line 95, in _check_result
    self.runner._check_result()
  File "/usr/lib/python3/dist-packages/datalad/runner/nonasyncrunner.py", line 297, in _check_result
    raise CommandError(
datalad.runner.exception.CommandError: CommandError: 'git -c diff.ignoreSubmodules=none -c core.quotepath=false ls-tree 61cf9e8789fc19ac8cdcbc624f7b82971e48b0be -z -r --full-tree -l' failed with exitcode 128 [err: 'fatal: not a tree object']

> /usr/lib/python3/dist-packages/datalad/runner/nonasyncrunner.py(297)_check_result()
-> raise CommandError(
(Pdb) 
```

```shell
$> git diff 000069
diff --git a/000069 b/000069
index 61cf9e8..08a8d71 160000
--- a/000069
+++ b/000069
@@ -1 +1 @@
-Subproject commit 61cf9e8789fc19ac8cdcbc624f7b82971e48b0be
+Subproject commit 08a8d717f83ea22d5dabe0c3bcd6d66d932112f3
```
</details>

so similarish case -- the original commit `61cf9e8789fc19ac8cdcbc624f7b82971e48b0be` is not present, although not clear how we got any local clone before since repo is private now and should have been from the start... I have uninstalled private subdatasets for now, redoing push
