### ISSUE TITLE
re-invocation of create-publication-target... -- API/usecase

### ISSUE THREAD

**Issue by yarikoptic** [datalad/datalad#464]
So we have published previous crawl of the openfmri repos, but then added more submodules.  I guess now I need to `create-publication-target` for new submodules.  Ideally I should be able just to point to the name of the remote (known to "super-dataset") and datalad, based on URL already known to super-dataset should just go and create new placeholders for submodules where needed.  But ATM API forces to provide URL again:

```
$> datalad create-publication-target-sshwebserver
usage: datalad create-publication-target-sshwebserver [--version] [-h]
                                                      [-l {critical,error,warning,info,debug,1,2,3,4,5,6,7,8,9}]
                                                      [-p {condor}]
                                                      [--target-dir TARGET_DIR]
                                                      [--target-url [TARGET_URL]]
                                                      [--target-pushurl TARGET_PUSHURL]
                                                      [--dataset DATASET]
                                                      [--recursive] [--force]
                                                      [--shared SHARED]
                                                      sshurl [target]
```

so `sshurl` is not optional (while target is).  I wonder if we should
1. store any of the custom options (`--shared`, `--target-url`,...) within git options for that remote (e.g. with `datalad-` prefix similarly to as annex does), so subsequent invocations could reuse them.  It would be unreasonable to require remembering them
2. make `sshurl` an optional positional argument, while `target` -- an option (`--remote` or `--target` if you want to keep moving away from git terminology).  Then I could probably just invoke smth like `datalad create-publication-target --remote datalad-public` without worrying to remember originally used option(s)

**Comment by yarikoptic** [comment]
FWIW, currently can't even make it go through existing ones (without --force which I guess would rewrite them -- undesired):
```shell
(git)smaug:/mnt/btrfs/datasets/datalad/crawl[master]git
$> datalad --dbg create-publication-target-sshwebserver -l info --recursive --shared all ssh://datasets.datalad.org/srv/datasets.datalad.org/www/ datalad-public
bind: Address already in use                                                             
channel_setup_fwd_listener_tcpip: cannot listen to port: 3389
Could not request local forwarding.
ControlSocket /var/run/user/47521/datalad/datasets.datalad.org already exists, disabling multiplexing
2016-05-23 21:22:31,469 [INFO   ] Creating target datasets ... (create_publication_target_sshwebserver.py:209)
Traceback (most recent call last):
  File "/home/yoh/proj/datalad/datalad/venv-tests/bin/datalad", line 9, in <module>
    load_entry_point('datalad==0.2.dev1', 'console_scripts', 'datalad')()
  File "/home/yoh/proj/datalad/datalad/datalad/cmdline/main.py", line 221, in main
    ret = cmdlineargs.func(cmdlineargs)
  File "/home/yoh/proj/datalad/datalad/datalad/interface/base.py", line 172, in call_from_parser
    return cls.__call__(**kwargs)
  File "/home/yoh/proj/datalad/datalad/datalad/distribution/create_publication_target_sshwebserver.py", line 241, in __call__
    path)
RuntimeError: Target directory /srv/datasets.datalad.org/www/openfmri/ds000110 already exists.
()
> /home/yoh/proj/datalad/datalad/datalad/distribution/create_publication_target_sshwebserver.py(241)__call__()
-> path)
```

**Comment by mih** [comment]
This was dealt with in various ways. Last issues seems to be #1273
