### ISSUE TITLE
datalad save on fmriprep freesurfer output fails for brainmask*.mgz files only

### ISSUE THREAD

**Issue by lnnrtwttkhn** [datalad/datalad#4668]
#### What is the problem?

I created a new DataLad dataset on the `freesurfer` output of [fMRIPrep](https://fmriprep.org/en/stable/).
A subsequent `datalad save` command was successful for *all* files *except* the `brainmask.auto.mgz` and `brainmask.mgz` files of all subjects (located in `</freesurfer/sub-XX>/mri/`).
The error message reads:

```bash
[ERROR  ] git-annex: sub-XX/mri/brainmask.mgz: rename: resource busy (Device or resource busy) [add(/path/to/freesurfer/sub-XX/mri/brainmask.mgz)]
```

#### What steps will reproduce the problem?

Unfortunately, I can't share my own data-set at this point but maybe this behavior could be reproduced with another fMRIPrep dataset's `/freesurfer` output? I used fMRIPrep version 1.2.2.

#### What version of DataLad are you using (run `datalad --version`)? On what operating system (consider running `datalad wtf`)?

```bash
datalad --version
datalad 0.13.0
```

operating system version (excerpt from `datalad wtf`):

```bash
## system
  - distribution: debian/9.12
  - encoding:
    - default: utf-8
    - filesystem: utf-8
    - locale.prefered: UTF-8
  - max_path_length: 275
  - name: Linux
  - release: 4.19.0-0.bpo.6-amd64
  - type: posix
  - version: #1 SMP Debian 4.19.67-2+deb10u2~bpo9+1 (2019-11-12)
```

BTW, when I run `datalad wtf`, I get this error but ouput is still produced:

```bash
Error initializing plugin EntryPoint(name='kwallet', value='keyrings.alt.kwallet', group='keyring.backends').
Traceback (most recent call last):
  File "/home/mpib/wittkuhn/.local/lib/python3.5/site-packages/keyring/backend.py", line 203, in _load_plugins
    init_func = ep.load()
  File "/home/mpib/wittkuhn/.local/lib/python3.5/site-packages/importlib_metadata/__init__.py", line 96, in load
    module = import_module(match.group('module'))
  File "/usr/lib/python3.5/importlib/__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 986, in _gcd_import
  File "<frozen importlib._bootstrap>", line 969, in _find_and_load
  File "<frozen importlib._bootstrap>", line 956, in _find_and_load_unlocked
ImportError: No module named 'keyrings.alt.kwallet'
-bash: #: command not found
```

#### Is there anything else that would be useful to know in this context?

nothing particular comes to mind.

#### Have you had any success using DataLad before? (to assess your expertise/prior luck.  We would welcome your testimonial additions to https://github.com/datalad/datalad/wiki/Testimonials as well)

yes, so far, DataLad has been working like a charm for me! It's a great tool, thanks!

**Comment by mih** [comment]
I am using DataLad 0.13 and fMRIprep 20.1.1 -- I do not have this issue. Are you on an NFS partition? NFS is not a friendly fellow...

**Comment by lnnrtwttkhn** [comment]
Thanks for your speedy reply @mih!

It's our cluster and I think it's BeeGFS storage.

Does that help? Thanks!
