### ISSUE TITLE
test_AnnexRepo_addurl_to_file_batched fails on crippled FS

### ISSUE THREAD

**Issue by mih** [datalad/datalad#4709]
Happened with gh-4708 running on an exFAT SSD.

```
======================================================================
ERROR: datalad.support.tests.test_annexrepo.test_AnnexRepo_addurl_to_file_batched
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/mih/env/datalad3-dev/lib/python3.7/site-packages/nose/case.py", line 198, in runTest
    self.test(*self.arg)
  File "/home/mih/hacking/datalad/git/datalad/tests/utils.py", line 542, in newfunc
    return t(*(arg + (d,)), **kw)
  File "/home/mih/hacking/datalad/git/datalad/tests/utils.py", line 654, in newfunc
    return tfunc(*(args + (path, url)), **kwargs)
  File "/home/mih/hacking/datalad/git/datalad/tests/utils.py", line 715, in newfunc
    return t(*(arg + (filename,)), **kw)
  File "/home/mih/hacking/datalad/git/datalad/support/tests/test_annexrepo.py", line 1012, in test_AnnexRepo_addurl_to_file_batched
    eq_(info['size'], 14)
TypeError: 'NoneType' object is not subscriptable
-------------------- >> begin captured logging << --------------------
asyncio: DEBUG: Using selector: EpollSelector
--------------------- >> end captured logging << ---------------------

```

**Comment by mih** [comment]
This actual issue is that the queried file is not annex'ed at all:

```
mih@meiner ...exRepo_addurl_to_file_batchedmku26qvd (git)-[adjusted/master(unlocked)] % git st
On branch adjusted/master(unlocked)
Untracked files:
  (use "git add <file>..." to include in what will be committed)
        about.txt

nothing added to commit but untracked files present (use "git add" to track)
```

**Comment by mih** [comment]
Issue is not fixed by https://github.com/datalad/datalad/pull/4736

**Comment by kyleam** [comment]
This can also be triggered with `./tools/eval_under_testloopfs`.  I'll see if I can come up with a reproducer without datalad.

**Comment by kyleam** [comment]
> I'll see if I can come up with a reproducer without datalad.

Hmm, no luck with my initial attempt.  File gets annexed as expected.

<details>
<summary>script</summary>

```sh
#!/bin/sh

set -eu

cd "$(mktemp -d $DATALAD_TESTS_TEMP_DIR/gx-XXXXXXX)"
git init
git annex init
u=https://raw.githubusercontent.com/datalad/datalad/0cb711ff5cf0683d23dc2bd32698984b9eaf6459/README.md

echo "$u f.md" | \
    git annex addurl --with-files --json --json-error-messages --batch

ls -l
git annex info f.md
```

running under DataLad's `tools/eval_under_testloopfs` helper.

git-annex version: 8.20200617

</details>

**Comment by mih** [comment]
I can confirm that I also wasn't able to trigger it with git-annex outside datalad.

**Comment by yarikoptic** [comment]
is it still the case? pasteable reproducer with datalad to run under tools/eval_under_testloopfs would be appreciated to try.  If datalad is involved -- I wonder if `alwayscommit=false` is to blame somehow.

**Comment by yarikoptic** [comment]
reproducible with `DATALAD_TESTS_TEMP_FS=exfat tools/eval_under_testloopfs python -m pytest -s -v -k test_AnnexRepo_addurl_to_file_batched datalad`

<details>
<summary>details</summary> 

```shell
> DATALAD_TESTS_TEMP_FS=exfat tools/eval_under_testloopfs python -m pytest -s -v -k test_AnnexRepo_addurl_to_file_batched datalad
I: exfat of 10:  /home/yoh/.tmp/datalad-fs-pG3RR
10+0 records in
10+0 records out
10321920 bytes (10 MB, 9.8 MiB) copied, 0.0208515 s, 495 MB/s
exfatprogs version : 1.1.3
Creating exFAT filesystem(/dev/loop0, cluster size=4096)

Writing volume boot record: done
Writing backup volume boot record: done
Fat table creation: done
Allocation bitmap creation: done
Upcase table creation: done
Writing root directory entry: done
Synchronizing...

exFAT format complete!
I: running python -m pytest -s -v -k test_AnnexRepo_addurl_to_file_batched datalad
====================================================== test session starts ======================================================
platform linux -- Python 3.9.12, pytest-7.1.2, pluggy-1.0.0 -- /home/yoh/proj/datalad/datalad-maint/venvs/dev3/bin/python
cachedir: .pytest_cache
rootdir: /home/yoh/proj/datalad/datalad-maint, configfile: tox.ini
plugins: cov-3.0.0
collected 1298 items / 1297 deselected / 1 selected                                                                             

datalad/support/tests/test_annexrepo.py::test_AnnexRepo_addurl_to_file_batched FAILEDVersions: annexremote=1.5.0 boto=2.49.0 cmd:7z=16.02 cmd:annex=10.20220624-1~ndall+1 cmd:bundled-git=2.30.2 cmd:git=2.30.2 cmd:ssh=9.0p1 cmd:system-git=2.35.1 cmd:system-ssh=9.0p1 datalad=0.17.1 exifread=2.3.2 humanize=4.0.0 iso8601=1.0.2 keyring=23.5.0 keyrings.alt=UNKNOWN msgpack=1.0.3 mutagen=1.45.1 patoolib=1.12 platformdirs=2.5.2 requests=2.27.1 tqdm=4.62.3
Obscure filename: str=b" ;&%b5{}'\xce\x94\xd0\x99\xd7\xa7\xd9\x85\xe0\xb9\x97\xe3\x81\x82 .datc " repr=" ;&%b5{}'ΔЙקم๗あ .datc "
Encodings: default='utf-8' filesystem='utf-8' locale.prefered='UTF-8'
Environment: LANG='en_US.UTF-8' GIT_PAGER='less --no-init --quit-if-one-screen' PATH='/home/yoh/proj/datalad/datalad-maint/venvs/dev3/bin:/home/yoh/gocode/bin:/home/yoh/gocode/bin:/home/yoh/bin:/home/yoh/.local/bin:/usr/local/bin:/usr/bin:/bin:/usr/local/games:/usr/games:/sbin:/usr/sbin:/usr/local/sbin' GIT_CONFIG_PARAMETERS="'init.defaultBranch=dl-test-branch' 'clone.defaultRemoteName=dl-test-remote'" GIT_ASKPASS='true'


=========================================================== FAILURES ============================================================
_____________________________________________ test_AnnexRepo_addurl_to_file_batched _____________________________________________

sitepath = '/home/yoh/.tmp/datalad-fs-pG3RR/datalad_temp_tree_test_AnnexRepo_addurl_to_file_batchedwuxwr066'
siteurl = 'http://127.0.0.1:40491/'
dst = '/home/yoh/.tmp/datalad-fs-pG3RR/datalad_temp_test_AnnexRepo_addurl_to_file_batchedl47r7k6s'

    @known_failure_windows
    @with_tree(tree=(('about.txt', 'Lots of abouts'),
                     ('about2.txt', 'more abouts'),
                     ('about2_.txt', 'more abouts_'),
                     ('d', {'sub.txt': 'more stuff'})))
    @serve_path_via_http()
    @with_tempfile
    def test_AnnexRepo_addurl_to_file_batched(sitepath=None, siteurl=None, dst=None):
    
        if dl_cfg.get('datalad.fake-dates'):
            raise SkipTest(
                "Faked dates are enabled; skipping batched addurl tests")
    
        ar = AnnexRepo(dst, create=True)
        testurl = urljoin(siteurl, 'about.txt')
        testurl2 = urljoin(siteurl, 'about2.txt')
        testurl2_ = urljoin(siteurl, 'about2_.txt')
        testurl3 = urljoin(siteurl, 'd/sub.txt')
        url_file_prefix = urlsplit(testurl).netloc.split(':')[0]
        testfile = 'about.txt'
        testfile2 = 'about2.txt'
        testfile2_ = 'about2_.txt'
        testfile3 = opj('d', 'sub.txt')
    
        # add to an existing but not committed file
        # TODO: __call__ of the BatchedAnnex must be checked to be called
        copyfile(opj(sitepath, 'about.txt'), opj(dst, testfile))
        # must crash sensibly since file exists, we shouldn't addurl to non-annexed files
        with assert_raises(AnnexBatchCommandError):
            ar.add_url_to_file(testfile, testurl, batch=True)
    
        # Remove it and re-add
        unlink(opj(dst, testfile))
        ar.add_url_to_file(testfile, testurl, batch=True)
    
        info = ar.info(testfile)
>       eq_(info['size'], 14)
E       TypeError: 'NoneType' object is not subscriptable

datalad/support/tests/test_annexrepo.py:1048: TypeError
==================================================== short test summary info ====================================================
FAILED datalad/support/tests/test_annexrepo.py::test_AnnexRepo_addurl_to_file_batched - TypeError: 'NoneType' object is not su...
============================================== 1 failed, 1297 deselected in 3.91s ===============================================
[ERROR  ] BatchedAnnex(command=['git', '-c', 'diff.ignoreSubmodules=none', 'annex', 'addurl', '--with-files', '--json', '--json-error-messages', '--batch'], encoding=UTF-8, exception_on_timeout=False, generator=<datalad.runner.nonasyncrunner._ResultGenerator object at 0x7f8ae4f8fb20>, output_proc=<function readline_json at 0x7f8ae77dc550>, path=/home/yoh/.tmp/datalad-fs-pG3RR/datalad_temp_test_AnnexRepo_addurl_to_file_batchedl47r7k6s, return_code=None, runner=<datalad.runner.runner.WitlessRunner object at 0x7f8ae4f8d440>, stderr_output=b'git-annex: getWorkingDirectory: does not exist (No such file or directory)\n', stdin_queue=<queue.Queue object at 0x7f8ae4f76c40>, timeout=None, wait_timed_out=None) subprocess failed with CommandError: 'git -c diff.ignoreSubmodules=none annex addurl --with-files --json --json-error-messages --batch' failed with exitcode 1 
I: done, unmounting

```
</details>

datalad 0.17.1 and bleedying edgish annex 10.20220624-1~ndall+1 

<details>
<summary>kyle's minimalistic directlywith annex addurl does not show the problem</summary> 

```shell
$> DATALAD_TESTS_TEMP_FS=exfat tools/eval_under_testloopfs bash /home/yoh/proj/datalad/trash/addurl-4709.sh
I: exfat of 10:  /home/yoh/.tmp/datalad-fs-QhBGo
10+0 records in
10+0 records out
10321920 bytes (10 MB, 9.8 MiB) copied, 0.0297062 s, 347 MB/s
exfatprogs version : 1.1.3
Creating exFAT filesystem(/dev/loop0, cluster size=4096)

Writing volume boot record: done
Writing backup volume boot record: done
Fat table creation: done
Allocation bitmap creation: done
Upcase table creation: done
Writing root directory entry: done
Synchronizing...

exFAT format complete!
I: running bash /home/yoh/proj/datalad/trash/addurl-4709.sh
Initialized empty Git repository in /home/yoh/.tmp/datalad-fs-QhBGo/gx-Waa4KXf/.git/
init  
  Detected a filesystem without fifo support.

  Disabling ssh connection caching.

  Detected a crippled filesystem.

  Entering an adjusted branch where files are unlocked as this filesystem does not support locked files.

Switched to branch 'adjusted/master(unlocked)'
ok
(recording state in git...)
{"command":"addurl","note":"to f.md","success":true,"input":["https://raw.githubusercontent.com/datalad/datalad/0cb711ff5cf0683d23dc2bd32698984b9eaf6459/README.md f.md"],"key":"SHA256E-s6675--b1186bc19e5d6c151056647dff05e9e13c37eaf7e87a2a7c9a57fceee5d397f3.md","error-messages":[],"file":"f.md"}
total 8
-rwx------ 1 yoh root 6675 Jul 11 17:46 f.md
file: f.md
size: 6.67 kilobytes
key: SHA256E-s6675--b1186bc19e5d6c151056647dff05e9e13c37eaf7e87a2a7c9a57fceee5d397f3.md
present: true
I: done, unmounting

```
</details>

**Comment by yarikoptic** [comment]
indeed kept failing to reproduce outside... @joeyh - what could lead to 

```shell
$> git annex info about.txt 
fatal: Not a valid object name about.txt
info about.txt (not a directory or an annexed file or a treeish or a remote or a uuid) failed
```

after that file was added via smth like 
```
 echo 'http://127.0.0.1:32849/about.txt about.txt' | /usr/lib/git-annex.linux/git  -c diff.ignoreSubmodules=none annex addurl --with-files --json --json-error-messages --batch
```
