### ISSUE TITLE
test_AnnexRepo_on_uninited_annex fails on crippled FS

### ISSUE THREAD

**Issue by mih** [datalad/datalad#4714]
Happened with gh-4708 running on an exFAT SSD.

```
======================================================================
FAIL: datalad.support.tests.test_annexrepo.test_AnnexRepo_on_uninited_annex
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/mih/env/datalad3-dev/lib/python3.7/site-packages/nose/case.py", line 198, in runTest
    self.test(*self.arg)
  File "/home/mih/hacking/datalad/git/datalad/tests/utils.py", line 1042, in newfunc
    t(*(arg + (uri,)), **kw)
  File "/home/mih/hacking/datalad/git/datalad/tests/utils.py", line 715, in newfunc
    return t(*(arg + (filename,)), **kw)
  File "/home/mih/hacking/datalad/git/datalad/support/tests/test_annexrepo.py", line 757, in test_AnnexRepo_on_uninited_annex
    ok_(annex.file_has_content('test-annex.dat'))
AssertionError: None

```

**Comment by mih** [comment]
So this seems to be breakage of `AnnexRepo.file_has_content()` which would explain a whole slew of error reports on crippled FS. Here is what I see on the same repo, right after `pdb` dropped into the test failure:

```
(Pdb) annex.path
'/media/mih/Samsung_T5/tmp/datalad_temp_test_AnnexRepo_on_uninited_annexwyp29d18'
(Pdb) annex.file_has_content('test-annex.dat')
False
```

but also

```
mih@meiner ...t_AnnexRepo_on_uninited_annexwyp29d18 (git)-[adjusted/master(unlocked)] % git annex find --not --in here
mih@meiner ...t_AnnexRepo_on_uninited_annexwyp29d18 (git)-[adjusted/master(unlocked)] % git annex find --in here                                                                    
test-annex.dat
mih@meiner ...t_AnnexRepo_on_uninited_annexwyp29d18 (git)-[adjusted/master(unlocked)] % cat test-annex.dat 
content to be annex-addurl'd%                                                                
```

which seems to be the desired content. Hence `git-annex` itself is correct in reporting the file to be available, and DataLad is wrong.

**Comment by mih** [comment]
The reason is that `AnnexRepo.file_has_content()` is ultimately performing its "quick" check which does

```
filepath.exists() and (filepath.is_symlink() and opj('annex', 'objects') in os.readlink(str(filepath))
```

on a crippled FS `filepath.is_symlink()` will be `False`, hence the test always fails, regardless of availability.

**Comment by bpoldrack** [comment]
Quickly checking the code, I'd say the problem is `allow_quick=True` for `AnnexRepo.file_has_content()`. This "quick" check is more dirty than quick and it probably shouldn't be default.

**Comment by mih** [comment]
Importantly, this family if methods is nowhere used in the actual code, but heavily used in the tests!
