### ISSUE TITLE
test_auto.test_proxying_lzma_LZMAFile fails on crippled FS

### ISSUE THREAD

**Issue by mih** [datalad/datalad#4716]
Happened with gh-4708 running on an exFAT SSD.

```
======================================================================
ERROR: datalad.tests.test_auto.test_proxying_lzma_LZMAFile(<function test_proxying_lzma_LZMAFile.<locals>.generate_dat at 0x7fd577a387b8>, <function test_proxying_lzma_LZMAFile.<locals>.verify_dat at 0x7fd577a38840>)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/mih/env/datalad3-dev/lib/python3.7/site-packages/nose/case.py", line 198, in runTest
    self.test(*self.arg)
  File "/home/mih/hacking/datalad/git/datalad/tests/utils.py", line 715, in newfunc
    return t(*(arg + (filename,)), **kw)
  File "/home/mih/hacking/datalad/git/datalad/tests/test_auto.py", line 137, in _test_proxying_open
    assert_raises(EXPECTED_EXCEPTIONS, verify_load, fpath1_2)
  File "/usr/lib/python3.7/unittest/case.py", line 756, in assertRaises
    return context.handle('assertRaises', args, kwargs)
  File "/usr/lib/python3.7/unittest/case.py", line 178, in handle
    callable_obj(*args, **kwargs)
  File "/home/mih/hacking/datalad/git/datalad/tests/test_auto.py", line 235, in verify_dat
    eq_(f.read().decode('utf-8'), "123")
  File "/usr/lib/python3.7/lzma.py", line 200, in read
    return self._buffer.read(size)
  File "/usr/lib/python3.7/_compression.py", line 103, in read
    data = self._decompressor.decompress(rawblock, size)
_lzma.LZMAError: Input format not supported by decoder

```

**Comment by mih** [comment]
Closing in favor of #4724
