### ISSUE TITLE
test_auto.test_proxying_open_nibabel fails on crippled FS

### ISSUE THREAD

**Issue by mih** [datalad/datalad#4717]
Happened with gh-4708 running on an exFAT SSD.

```
======================================================================
ERROR: datalad.tests.test_auto.test_proxying_open_nibabel(<function test_proxying_open_nibabel.<locals>.generate_nii at 0x7fd577a29d90>, <function test_proxying_open_nibabel.<locals>.verify_nii at 0x7fd577a29598>)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/mih/env/datalad3-dev/lib/python3.7/site-packages/nose/case.py", line 198, in runTest
    self.test(*self.arg)
  File "/home/mih/hacking/datalad/git/datalad/tests/utils.py", line 715, in newfunc
    return t(*(arg + (filename,)), **kw)
  File "/home/mih/hacking/datalad/git/datalad/tests/test_auto.py", line 137, in _test_proxying_open
    assert_raises(EXPECTED_EXCEPTIONS, verify_load, fpath1_2)
  File "/usr/lib/python3.7/unittest/case.py", line 756, in assertRaises
    return context.handle('assertRaises', args, kwargs)
  File "/usr/lib/python3.7/unittest/case.py", line 178, in handle
    callable_obj(*args, **kwargs)
  File "/home/mih/hacking/datalad/git/datalad/tests/test_auto.py", line 255, in verify_nii
    ni = nib.load(f)
  File "/home/mih/env/datalad3-dev/lib/python3.7/site-packages/nibabel/loadsave.py", line 56, in load
    filename)
nibabel.filebasedimages.ImageFileError: Cannot work out file type of "/media/mih/Samsung_T5/tmp/datalad_temp__test_proxying_open8494ntsy_2/test.nii.gz"

```

**Comment by mih** [comment]
Closing in favor of #4724
