### ISSUE TITLE
`rmtemp` utility is affected by test infrastructure switches

### ISSUE THREAD

**Issue by mih** [datalad/datalad#4720]
Happened with gh-4708 running on an exFAT SSD.

```
======================================================================
FAIL: datalad.tests.test_archives.test_ArchivesCache
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/mih/env/datalad3-dev/lib/python3.7/site-packages/nose/case.py", line 198, in runTest
    self.test(*self.arg)
  File "/home/mih/hacking/datalad/git/datalad/tests/test_archives.py", line 224, in test_ArchivesCache
    assert_false(op.exists(cache.path))
AssertionError: True is not false

```

**Comment by mih** [comment]
This seems to be a real bug, not a test issue.

**Comment by mih** [comment]
So the real issue is this:

`ArchiveCache.clean()` uses `rmtemp()`. Which in itself is legit. But `rmtemp()` also listens to `DATALAD_TESTS_TEMP_KEEP` making it behave like a test helper, and using that switch causes `ArchiveCache` to no longer operate as tested (and desired).

I believe that `rmtemp()` should either be a test helper, or not -- but not both.

**Comment by yarikoptic** [comment]
I have tested using our helper (presumably) under exfat and no error:
```
$> DATALAD_TESTS_TEMP_FS=exfat tools/eval_under_testloopfs python -m pytest -s -v -k test_ArchivesCache datalad    
I: exfat of 10:  /home/yoh/.tmp/datalad-fs-jrhrC
10+0 records in
10+0 records out
10321920 bytes (10 MB, 9.8 MiB) copied, 0.0239509 s, 431 MB/s
exfatprogs version : 1.1.3
Creating exFAT filesystem(/dev/loop0, cluster size=4096)

Writing volume boot record: done
Writing backup volume boot record: done
Fat table creation: done
Allocation bitmap creation: done
Upcase table creation: done
Writing root directory entry: done
Synchronizing...

exFAT format complete!
I: running python -m pytest -s -v -k test_ArchivesCache datalad
====================================================== test session starts ======================================================
platform linux -- Python 3.9.12, pytest-7.1.2, pluggy-1.0.0 -- /home/yoh/proj/datalad/datalad-maint/venvs/dev3/bin/python
cachedir: .pytest_cache
rootdir: /home/yoh/proj/datalad/datalad-maint, configfile: tox.ini
plugins: cov-3.0.0
collected 1298 items / 1297 deselected / 1 selected                                                                             

datalad/tests/test_archives.py::test_ArchivesCache PASSEDVersions: annexremote=1.5.0 boto=2.49.0 cmd:7z=16.02 cmd:annex=10.20220624-1~ndall+1 cmd:bundled-git=2.30.2 cmd:git=2.30.2 cmd:ssh=9.0p1 cmd:system-git=2.35.1 cmd:system-ssh=9.0p1 datalad=0.17.1 exifread=2.3.2 humanize=4.0.0 iso8601=1.0.2 keyring=23.5.0 keyrings.alt=UNKNOWN msgpack=1.0.3 mutagen=1.45.1 patoolib=1.12 platformdirs=2.5.2 requests=2.27.1 tqdm=4.62.3
Obscure filename: str=b" ;&%b5{}'\xce\x94\xd0\x99\xd7\xa7\xd9\x85\xe0\xb9\x97\xe3\x81\x82 .datc " repr=" ;&%b5{}'ΔЙקم๗あ .datc "
Encodings: default='utf-8' filesystem='utf-8' locale.prefered='UTF-8'
Environment: LANG='en_US.UTF-8' GIT_PAGER='less --no-init --quit-if-one-screen' PATH='/home/yoh/proj/datalad/datalad-maint/venvs/dev3/bin:/home/yoh/gocode/bin:/home/yoh/gocode/bin:/home/yoh/bin:/home/yoh/.local/bin:/usr/local/bin:/usr/bin:/bin:/usr/local/games:/usr/games:/sbin:/usr/sbin:/usr/local/sbin' GIT_CONFIG_PARAMETERS="'init.defaultBranch=dl-test-branch' 'clone.defaultRemoteName=dl-test-remote'" GIT_ASKPASS='true'


============================================== 1 passed, 1297 deselected in 2.25s ===============================================
I: done, unmounting
```
So let's consider it self-addressed
