### ISSUE TITLE
test_auto.test_proxying_open_h5py fails on crippled FS

### ISSUE THREAD

**Issue by mih** [datalad/datalad#4721]
Happened with gh-4708 running on an exFAT SSD.

```
======================================================================
FAIL: datalad.tests.test_auto.test_proxying_open_h5py(<function test_proxying_open_h5py.<locals>.generate_hdf5 at 0x7fd577aca400>, <function test_proxying_open_h5py.<locals>.verify_hdf5 at 0x7fd577aca620>)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/mih/env/datalad3-dev/lib/python3.7/site-packages/nose/case.py", line 198, in runTest
    self.test(*self.arg)
  File "/home/mih/hacking/datalad/git/datalad/tests/utils.py", line 715, in newfunc
    return t(*(arg + (filename,)), **kw)
  File "/home/mih/hacking/datalad/git/datalad/tests/test_auto.py", line 165, in _test_proxying_open
    assert_false(os.path.isfile(fpath2_2))
AssertionError: True is not false

```

**Comment by mih** [comment]
Closing in favor of #4724
