### ISSUE TITLE
test_auto.test_proxying_open_regular fails on crippled FS

### ISSUE THREAD

**Issue by mih** [datalad/datalad#4722]
Happened with gh-4708 running on an exFAT SSD.

```
======================================================================
FAIL: datalad.tests.test_auto.test_proxying_open_regular(<function test_proxying_open_regular.<locals>.generate_dat at 0x7fd577acab70>, <function test_proxying_open_regular.<locals>.verify_dat at 0x7fd577a29b70>)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/mih/env/datalad3-dev/lib/python3.7/site-packages/nose/case.py", line 198, in runTest
    self.test(*self.arg)
  File "/home/mih/hacking/datalad/git/datalad/tests/utils.py", line 715, in newfunc
    return t(*(arg + (filename,)), **kw)
  File "/home/mih/hacking/datalad/git/datalad/tests/test_auto.py", line 137, in _test_proxying_open
    assert_raises(EXPECTED_EXCEPTIONS, verify_load, fpath1_2)
AssertionError: '/annex/objects/SHA256E-s3--a665a45920422f9d417e4867efdc4fb8a04a1f3fff1fa07e998e86f7f7a27ae3\n' != '123'

```

**Comment by mih** [comment]
Closing in favor of #4724
