### ISSUE TITLE
sshrun broken on crippled FS

### ISSUE THREAD

**Issue by mih** [datalad/datalad#4725]
Happened with gh-4708 running on an exFAT SSD.

Both issues are related to the placement of the sockets on the crippled FS (which cannot have sockets). Related issues: #4198 #4075 #2696
```
======================================================================
ERROR: datalad.support.tests.test_sshrun.test_fancy_quotes
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/mih/env/datalad3-dev/lib/python3.7/site-packages/nose/case.py", line 198, in runTest
    self.test(*self.arg)
  File "/home/mih/hacking/datalad/git/datalad/tests/utils.py", line 187, in newfunc
    return func(*args, **kwargs)
  File "/home/mih/hacking/datalad/git/datalad/tests/utils.py", line 262, in newfunc
    return func(*args, **kwargs)
  File "/home/mih/hacking/datalad/git/datalad/tests/utils.py", line 715, in newfunc
    return t(*(arg + (filename,)), **kw)
  File "/home/mih/hacking/datalad/git/datalad/support/tests/test_sshrun.py", line 63, in test_fancy_quotes
    out, err = Runner().run(cmd)
  File "/home/mih/hacking/datalad/git/datalad/cmd.py", line 957, in run
    raise exc
datalad.support.exceptions.CommandError: CommandError: 'datalad sshrun localhost ''"'"'cat '"'"'"'"'"'"'"'"'/media/mih/Samsung_T5/tmp/datalad_temp_test_fancy_quotespock5f_b1 space'"'"'"'"'"'"'"'"''"'"''' failed with exitcode 255 [err: 'unix_listener: cannot bind to path /media/mih/Samsung_T5/tmp/datalad_temp_r9hp3lge/.cache/datalad/sockets/6258b3a7.JFMGsYXY2IRpvj9D: Input/output error
ConnectionOpenFailedError: ''['"'"'ssh'"'"', '"'"'-fN'"'"', '"'"'-o'"'"', '"'"'ControlMaster=auto'"'"', '"'"'-o'"'"', '"'"'ControlPersist=15m'"'"', '"'"'-o'"'"', '"'"'ControlPath=/media/mih/Samsung_T5/tmp/datalad_temp_r9hp3lge/.cache/datalad/sockets/6258b3a7'"'"', '"'"'localhost'"'"']'' failed with exitcode 255 [Failed to open SSH connection (could not start ControlMaster process)]']

======================================================================
ERROR: datalad.support.tests.test_sshrun.test_no_stdin_swallow
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/mih/env/datalad3-dev/lib/python3.7/site-packages/nose/case.py", line 198, in runTest
    self.test(*self.arg)
  File "/home/mih/hacking/datalad/git/datalad/tests/utils.py", line 187, in newfunc
    return func(*args, **kwargs)
  File "/home/mih/hacking/datalad/git/datalad/tests/utils.py", line 262, in newfunc
    return func(*args, **kwargs)
  File "/home/mih/hacking/datalad/git/datalad/tests/utils.py", line 715, in newfunc
    return t(*(arg + (filename,)), **kw)
  File "/home/mih/hacking/datalad/git/datalad/support/tests/test_sshrun.py", line 50, in test_no_stdin_swallow
    out, err = Runner().run(cmd, stdin=open(fname))
  File "/home/mih/hacking/datalad/git/datalad/cmd.py", line 957, in run
    raise exc
datalad.support.exceptions.CommandError: CommandError: 'datalad sshrun localhost cat' failed with exitcode 255 [err: 'unix_listener: cannot bind to path /media/mih/Samsung_T5/tmp/datalad_temp_r9hp3lge/.cache/datalad/sockets/6258b3a7.BZif0PNj7G42Lwl2: Input/output error
ConnectionOpenFailedError: ''['"'"'ssh'"'"', '"'"'-fN'"'"', '"'"'-o'"'"', '"'"'ControlMaster=auto'"'"', '"'"'-o'"'"', '"'"'ControlPersist=15m'"'"', '"'"'-o'"'"', '"'"'ControlPath=/media/mih/Samsung_T5/tmp/datalad_temp_r9hp3lge/.cache/datalad/sockets/6258b3a7'"'"', '"'"'localhost'"'"']'' failed with exitcode 255 [Failed to open SSH connection (could not start ControlMaster process)]']
```

**Comment by mih** [comment]
Might be possible to fix very generally by turning multiplexing off, if no sockets can be placed: https://github.com/datalad/datalad/pull/5042

**Comment by mih** [comment]
This is how this looks outside the tests:

```
# sockets created on a crippled FS
% DATALAD_LOCATIONS_SOCKETS=/media/mih/Samsung_T5/tmp datalad sshrun localhost uname       
unix_listener: cannot bind to path /media/mih/Samsung_T5/tmp/6258b3a7.om0UhwEIcBYHi6lv: Operation not permitted
ConnectionOpenFailedError: 'ssh -fN -o ControlMaster=auto -o ControlPersist=15m -o ControlPath=/media/mih/Samsung_T5/tmp/6258b3a7 localhost' failed with exitcode 255 [Failed to open SSH connection (could not start ControlMaster process)]

# non-crippled FS placement
% DATALAD_LOCATIONS_SOCKETS=/tmp/tmp datalad sshrun localhost uname
Linux
```

In both cases above, the command CWD is actually on a crippled FS, which has no effect.

Taking a step back: What is `sshrun` even used for? We configure it as `GIT_SSH_COMMAND`, such that we can use known connections for git transport via SSH. This means that bypassing this entire code layer in order to perform a straight-up SSH call invalidates the whole purpose of this command.

The next best thing would be to call `ssh.open()` manually in `sshrun`, instead of an automated call in `sshconnector.py`.  Conceptually, we seem to have been there:

```py
456             # XXX: check for open socket once
457             #      and provide roll back if fails to run and was not explicitly
458             #      checked first
459             # MIH: this would mean that we would have to distinguish failure
460             #      of a payload command from failure of SSH itself. SSH however,
461             #      only distinguishes success and failure of the entire operation
462             #      Increase in fragility from introspection makes a potential
463             #      performance benefit a questionable improvement.
464             # make sure we have an open connection, will test if action is needed
465             # by itself
466  ->         self.open()
```

**Comment by mih** [comment]
I am closing this old issue of mine. There is clearly no interest in this. Closing on windows via SSH is possible nevertheless
