### ISSUE TITLE
0.13.1-1 fails on build on nd 9.0 and 18.04 

### ISSUE THREAD

**Issue by yarikoptic** [datalad/datalad#4748]
```shell
neurodebian@smaug ~/deb/builds/datalad/0.13.1-1 % grep '^FAILED' *build
datalad_0.13.1-1~nd18.04+1_amd64.build:FAILED (SKIP=133, errors=11)
datalad_0.13.1-1~nd90+1_amd64.build:FAILED (SKIP=133, errors=11)
```
full logs at http://neuro.debian.net/_files/_buildlogs/datalad/0.13.1

summary list of fails
```
neurodebian@smaug ~/deb/builds/datalad/0.13.1-1 % grep '^ERROR: data' datalad_0.13.1-1~nd90+1_amd64.build | nl
     1	ERROR: datalad.distribution.tests.test_create_sibling.test_target_ssh_recursive(False,)
     2	ERROR: datalad.distribution.tests.test_create_sibling.test_replace_and_relative_sshpath(False,)
     3	ERROR: datalad.downloaders.tests.test_http.test_HTMLFormAuthenticator_httpretty
     4	ERROR: datalad.downloaders.tests.test_http.test_HTTPBearerTokenAuthenticator
     5	ERROR: datalad.downloaders.tests.test_http.test_HTTPLorisTokenAuthenticator
     6	ERROR: datalad.downloaders.tests.test_http.test_lorisadapter
     7	ERROR: datalad.downloaders.tests.test_http.test_scenario_2
     8	ERROR: datalad.downloaders.tests.test_http.test_authfail404_interactive
     9	ERROR: datalad.downloaders.tests.test_http.test_authfail404_noninteractive
    10	ERROR: datalad.support.tests.test_network.test_get_local_file_url
    11	ERROR: datalad.tests.test_witless_runner.test_runner
```
overall built fine only on these debians:
```
neurodebian@smaug ~/deb/builds/datalad/0.13.1-1 % grep OK summary.build
datalad_0.13.1-1~nd100+1_amd64.build	OK	47:36.37 real, 1764.31 user, 1281.61 sys, 3321928 out
datalad_0.13.1-1~nd110+1_amd64.build	OK	37:07.36 real, 1264.85 user, 999.79 sys, 3258584 out
datalad_0.13.1-1~nd+1_amd64.build	OK	37:17.01 real, 1266.94 user, 1012.11 sys, 3316264 out
```
the others are dependencies issues.. although strange for 20.04 since python3-annexremote is available, so probably something didn't update -- I will check

**Comment by yarikoptic** [comment]
20.04 also failed with `FAILED (SKIP=133, errors=12, failures=1)` and that is having git annex 8.20200226-1, installing good old standalone I got only one (obscure) failure with
```
======================================================================
FAIL: datalad.core.local.tests.test_resulthooks.test_basics
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/nose/case.py", line 197, in runTest
    self.test(*self.arg)
  File "/build/datalad-0.13.1/.pybuild/cpython3_3.8_datalad/build/datalad/tests/utils.py", line 721, in newfunc
    return t(*(arg + (filename,)), **kw)
  File "/build/datalad-0.13.1/.pybuild/cpython3_3.8_datalad/build/datalad/tests/utils.py", line 721, in newfunc
    return t(*(arg + (filename,)), **kw)
  File "/build/datalad-0.13.1/.pybuild/cpython3_3.8_datalad/build/datalad/core/local/tests/test_resulthooks.py", line 100, in test_basics
    eq_(clone_sub2.config.get('datalad.metadata.nativetype'), 'bids')
AssertionError: None != 'bids'
```
note that with 8.20200330-1 (in debian sid/buster) we did not have this and aforementioned 9.0 and 18.04 had our standalone (7.20190819+git2-g908476a9b-1~ndall+1) installed  (and no failure in `datalad.core.local.tests.test_resulthooks.test_basics`) so their failures are different...
so for debian pkg we should declare build/install conflicts with versions of git-annex probably `8.20200226 <= X < 8.20200330`). Note: datalad 0.12.4 build did succeed ok with 7.20200219-1.

**Comment by adswa** [comment]
Given that this is about the ``0.13`` series of DataLad, and ``0.14.x`` is long released (and hence I suppose the failures were fixed?), is it okay to close such issues? Or do we keep them open?

**Comment by yarikoptic** [comment]
I am trying to update debian package now and will remove the skips of the tests like these... let's see where it would bring me

**Comment by yarikoptic** [comment]
FWIW 18.04 passed the build now:
```
neurodebian@smaug ~/deb/builds/datalad/0.14.6-1 % grep test_basics *nd18.04*build
datalad.core.local.tests.test_resulthooks.test_basics ... ok
datalad.core.local.tests.test_run.test_basics ... /bin/sh: 1: 7i3amhmuch9invalid: not found
neurodebian@smaug ~/deb/builds/datalad/0.14.6-1 % grep SKIP= *nd18.04*build
OK (SKIP=148)
```
so let's consider this one done. nd 9.0 -- well -- getting stale, not sure if I would be pursuing it if would take too much

**Comment by yarikoptic** [comment]
actually we do not support python 3.5 any longer, and that is what nd90 has - so "out of question" ;)
