### ISSUE TITLE
Using --dataset ^. outside a superdataset leads to confusing error

### ISSUE THREAD

**Issue by mih** [datalad/datalad#4758]
```
# go to any directory that is not in a superdataset, and do
% datalad --dbg create -d^. --force .
Traceback (most recent call last):
  File "/home/mih/env/datalad3-dev/bin/datalad", line 8, in <module>
    main()
  File "/home/mih/hacking/datalad/git/datalad/cmdline/main.py", line 521, in main
    ret = cmdlineargs.func(cmdlineargs)
  File "/home/mih/hacking/datalad/git/datalad/interface/base.py", line 784, in call_from_parser
    ret = cls.__call__(**kwargs)
  File "/home/mih/hacking/datalad/git/datalad/interface/utils.py", line 369, in eval_func
    else Dataset(dataset_arg) if dataset_arg else None
  File "/home/mih/hacking/datalad/git/datalad/support/repo.py", line 145, in __call__
    id_, new_args, new_kwargs = cls._flyweight_id_from_args(*args, **kwargs)
  File "/home/mih/hacking/datalad/git/datalad/support/repo.py", line 223, in _flyweight_id_from_args
    localpath = RI(path_).localpath
  File "/home/mih/hacking/datalad/git/datalad/support/network.py", line 423, in __new__
    raise ValueError("Could not deduce RI type for %r" % (ri,))
ValueError: Could not deduce RI type for None

> /home/mih/hacking/datalad/git/datalad/support/network.py(423)__new__()
-> raise ValueError("Could not deduce RI type for %r" % (ri,))
```

It queries the flyweight records, fails to find something for `^.` and still proceeds.

It should error by saying that there is no such dataset.

**Comment by mih** [comment]
It seems `^.` was never a value that should reach the flyweight code. It is coming in from `eval_func` where a dataset instance is built to be able to query its config.
