### ISSUE TITLE
TST test_ria_basics.py:test_binary_data run failed on bionic

### ISSUE THREAD

**Issue by yarikoptic** [datalad/datalad#4767]
Not sure if a fluke or reproducible but should be addressed one way or another.

Ran into while running timing of tests on bionic for #4766 : [full log](https://api.travis-ci.org/v3/job/711507070/log.txt) 

```
======================================================================
ERROR: datalad.distributed.tests.test_ria_basics.test_binary_data('datalad-test',)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/travis/virtualenv/python3.5.7/lib/python3.5/site-packages/nose/case.py", line 198, in runTest
    self.test(*self.arg)
  File "/home/travis/virtualenv/python3.5.7/lib/python3.5/site-packages/datalad/tests/utils.py", line 268, in newfunc
    return func(*args, **kwargs)
  File "/home/travis/virtualenv/python3.5.7/lib/python3.5/site-packages/datalad/tests/utils.py", line 728, in newfunc
    return t(*(arg + (filename,)), **kw)
  File "/home/travis/virtualenv/python3.5.7/lib/python3.5/site-packages/datalad/tests/utils.py", line 728, in newfunc
    return t(*(arg + (filename,)), **kw)
  File "/home/travis/virtualenv/python3.5.7/lib/python3.5/site-packages/datalad/distributed/tests/test_ria_basics.py", line 465, in _test_binary_data
    ds.download_url(url, path=file, message="Add DICOM file from github")
  File "/home/travis/virtualenv/python3.5.7/lib/python3.5/site-packages/datalad/distribution/dataset.py", line 503, in apply_func
    return f(**kwargs)
  File "/home/travis/virtualenv/python3.5.7/lib/python3.5/site-packages/datalad/interface/utils.py", line 494, in eval_func
    return return_func(generator_func)(*args, **kwargs)
  File "/home/travis/virtualenv/python3.5.7/lib/python3.5/site-packages/datalad/interface/utils.py", line 482, in return_func
    results = list(results)
  File "/home/travis/virtualenv/python3.5.7/lib/python3.5/site-packages/datalad/interface/utils.py", line 469, in generator_func
    msg="Command did not complete successfully")
datalad.support.exceptions.IncompleteResultsError: Command did not complete successfully. 1 failed:
[{'action': 'download_url',
  'message': "'QuietConsoleLog' object has no attribute 'yesno' "
             '[__init__.py:__getattribute__:101]',
  'path': '/tmp/datalad_temp__test_binary_datafthxi_uu/dicomfile',
  'status': 'error',
  'type': 'file'}]
```
so it looks like it is trying to communicate something the the "user".

**Comment by yarikoptic** [comment]
oddly enough I observed the same (or very similar) failure on OSX (released only, maint somehow stalled/provided no output) of datalad/git-annex

<details>
<summary>full traceback etc</summary> 

```shell
2021-09-02T03:49:04.2079520Z ======================================================================
2021-09-02T03:49:04.2080830Z D:  "';a&b&cΔЙקﻡ๗あ `|
2021-09-02T03:49:04.2081950Z ERROR: datalad.distributed.tests.test_ria_basics.test_binary_data(None,)
2021-09-02T03:49:04.2082610Z D: /a
2021-09-02T03:49:04.2084360Z ----------------------------------------------------------------------
2021-09-02T03:49:04.2085460Z D: /a/b/c
2021-09-02T03:49:04.2086860Z Traceback (most recent call last):
2021-09-02T03:49:04.2087300Z D: /a~
2021-09-02T03:49:04.2089660Z   File "/Users/runner/hostedtoolcache/Python/3.7.11/x64/lib/python3.7/site-packages/nose/case.py", line 198, in runTest
2021-09-02T03:49:04.2090370Z D: /a b/name
2021-09-02T03:49:04.2091450Z     self.test(*self.arg)
2021-09-02T03:49:04.2091830Z testing 0
2021-09-02T03:49:04.2093960Z   File "/Users/runner/hostedtoolcache/Python/3.7.11/x64/lib/python3.7/site-packages/datalad/tests/utils.py", line 189, in _wrap_skip_if_no_network
2021-09-02T03:49:04.2094750Z testing 1
2021-09-02T03:49:04.2095800Z     return func(*args, **kwargs)
2021-09-02T03:49:04.2096490Z /var/folders/24/8k48jl6d249_n_qfxwsl6xvm0000gn/T/datalad_temp_tree_test_paths_with_forward_slashes_s59sa46
2021-09-02T03:49:04.2098900Z   File "/Users/runner/hostedtoolcache/Python/3.7.11/x64/lib/python3.7/site-packages/datalad/tests/utils.py", line 764, in _wrap_with_tempfile
2021-09-02T03:49:04.2100080Z ' |;&%b5{}\'"Δקﻡ๗あ .datc '
2021-09-02T03:49:04.2101180Z     return t(*(arg + (filename,)), **kw)
2021-09-02T03:49:04.2101590Z .: here(+) [git]
2021-09-02T03:49:04.2103820Z   File "/Users/runner/hostedtoolcache/Python/3.7.11/x64/lib/python3.7/site-packages/datalad/tests/utils.py", line 764, in _wrap_with_tempfile
2021-09-02T03:49:04.2105730Z .: dl-test-remote(+) [/private/var/folders/24/8k48jl6d249_n_qfxwsl6xvm0000gn/T/datalad_temp_test_cached_dataset01502kwp/https___github.com_datalad_testrepo--minimalds (git)]
2021-09-02T03:49:04.2109100Z     return t(*(arg + (filename,)), **kw)
2021-09-02T03:49:04.2109510Z .: here(+) [git]
2021-09-02T03:49:04.2111620Z   File "/Users/runner/hostedtoolcache/Python/3.7.11/x64/lib/python3.7/site-packages/datalad/distributed/tests/test_ria_basics.py", line 484, in _test_binary_data
2021-09-02T03:49:04.2113600Z .: dl-test-remote(+) [/private/var/folders/24/8k48jl6d249_n_qfxwsl6xvm0000gn/T/datalad_temp_test_cached_dataset01502kwp/https___github.com_datalad_testrepo--minimalds (git)]
2021-09-02T03:49:04.2115260Z     ds.download_url(url, path=file, message="Add DICOM file from github")
2021-09-02T03:49:04.2115810Z .: here(+) [git]
2021-09-02T03:49:04.2117700Z   File "/Users/runner/hostedtoolcache/Python/3.7.11/x64/lib/python3.7/site-packages/datalad/distribution/dataset.py", line 503, in apply_func
2021-09-02T03:49:04.2119580Z .: dl-test-remote(+) [/private/var/folders/24/8k48jl6d249_n_qfxwsl6xvm0000gn/T/datalad_temp_test_cached_dataset01502kwp/https___github.com_datalad_testrepo--minimalds (git)]
2021-09-02T03:49:04.2121060Z     return f(**kwargs)
2021-09-02T03:49:04.2121420Z .: here(+) [git]
2021-09-02T03:49:04.2123230Z   File "/Users/runner/hostedtoolcache/Python/3.7.11/x64/lib/python3.7/site-packages/datalad/interface/utils.py", line 481, in eval_func
2021-09-02T03:49:04.2125090Z .: dl-test-remote(+) [/private/var/folders/24/8k48jl6d249_n_qfxwsl6xvm0000gn/T/datalad_temp_test_cached_dataset01502kwp/https___github.com_datalad_testrepo--minimalds (git)]
2021-09-02T03:49:04.2126680Z     return return_func(generator_func)(*args, **kwargs)
2021-09-02T03:49:04.2128510Z Versions: annexremote=1.5.0 appdirs=1.4.4 boto=2.49.0 cmd:7z=17.04 cmd:annex=8.20210804-g7319e4a45 cmd:bundled-git=UNKNOWN cmd:git=2.32.0 cmd:system-git=2.32.0 cmd:system-ssh=8.1p1 humanize=3.11.0 iso8601=0.1.16 keyring=23.1.0 keyrings.alt=4.1.0 msgpack=1.0.2 patoolib=1.12 requests=2.26.0 tqdm=4.62.2 wrapt=1.12.1
2021-09-02T03:49:04.2131230Z   File "/Users/runner/hostedtoolcache/Python/3.7.11/x64/lib/python3.7/site-packages/datalad/interface/utils.py", line 474, in return_func
2021-09-02T03:49:04.2132730Z Obscure filename: str=b' |;&%b5{}\'"\xce\x94\xd7\xa7\xd9\x85\xe0\xb9\x97\xe3\x81\x82 .datc ' repr=' |;&%b5{}\'"Δקﻡ๗あ .datc '
2021-09-02T03:49:04.2136610Z     results = list(results)
2021-09-02T03:49:04.2137730Z Encodings: default='utf-8' filesystem='utf-8' locale.prefered='UTF-8'
2021-09-02T03:49:04.2140040Z   File "/Users/runner/hostedtoolcache/Python/3.7.11/x64/lib/python3.7/site-packages/datalad/interface/utils.py", line 461, in generator_func
2021-09-02T03:49:04.2145210Z Environment: LC_ALL='en_US.UTF-8' PATH='/Users/runner/hostedtoolcache/Python/3.7.11/x64/bin:/Users/runner/hostedtoolcache/Python/3.7.11/x64:/Applications/git-annex.app/Contents/MacOS:/usr/local/opt/pipx_bin:/Users/runner/.cargo/bin:/usr/local/lib/ruby/gems/2.7.0/bin:/usr/local/opt/ruby@2.7/bin:/usr/local/opt/curl/bin:/usr/local/bin:/usr/local/sbin:/Users/runner/bin:/Users/runner/.yarn/bin:/Users/runner/Library/Android/sdk/tools:/Users/runner/Library/Android/sdk/platform-tools:/Users/runner/Library/Android/sdk/ndk-bundle:/Library/Frameworks/Mono.framework/Versions/Current/Commands:/usr/bin:/bin:/usr/sbin:/sbin:/Users/runner/.dotnet/tools:/Users/runner/.ghcup/bin:/Users/runner/hostedtoolcache/stack/2.7.3/x64' LANG='C' LC_CTYPE='en_US.UTF-8' GIT_CONFIG_PARAMETERS="'init.defaultBranch=dl-test-branch' 'clone.defaultRemoteName=dl-test-remote'"
2021-09-02T03:49:04.2155150Z     msg="Command did not complete successfully")
2021-09-02T03:49:04.2156800Z datalad.support.exceptions.IncompleteResultsError: Command did not complete successfully. 1 failed:
2021-09-02T03:49:04.2158820Z [{'action': 'download_url',
2021-09-02T03:49:04.2160790Z   'exception_traceback': '[download_url.py:__call__:186,base.py:download:520,base.py:access:213,base.py:_handle_authentication:279,base.py:_enter_credentials:313,__init__.py:__getattribute__:101]',
2021-09-02T03:49:04.2162750Z   'message': "'QuietConsoleLog' object has no attribute 'yesno' "
2021-09-02T03:49:04.2164190Z              '[__init__.py:__getattribute__:101]',
2021-09-02T03:49:04.2165850Z   'path': '/private/var/folders/24/8k48jl6d249_n_qfxwsl6xvm0000gn/T/datalad_temp__test_binary_datar4b31m9c/dicomfile',
2021-09-02T03:49:04.2167470Z   'status': 'error',
2021-09-02T03:49:04.2168620Z   'type': 'file'}]
```
</details>

apparently it did happen before but only occasionally
```
$> git grep 'ERROR: datalad.distributed.tests.test_ria_ba'
cron-20210815/build-macos.yaml-386-69466103-failed/1_test-datalad (master).txt:2021-08-15T03:48:21.0867230Z ERROR: datalad.distributed.tests.test_ria_basics.test_binary_data(None,)
cron-20210815/build-macos.yaml-386-69466103-failed/2_test-datalad (maint).txt:2021-08-15T03:48:41.1351880Z ERROR: datalad.distributed.tests.test_ria_basics.test_binary_data(None,)
cron-20210815/build-macos.yaml-386-69466103-failed/test-datalad (maint)/11_Run datalad tests.txt:2021-08-15T03:48:41.1351870Z ERROR: datalad.distributed.tests.test_ria_basics.test_binary_data(None,)
cron-20210815/build-macos.yaml-386-69466103-failed/test-datalad (master)/11_Run datalad tests.txt:2021-08-15T03:48:21.0867210Z ERROR: datalad.distributed.tests.test_ria_basics.test_binary_data(None,)
```
so I feel that it is some generic issue causing test to be flaky, adjusting labels accordingly

**Comment by mih** [comment]
I have not see this for months. Candidate for closing.

**Comment by yarikoptic** [comment]
oh, I think we had recent reappearance of this issue in https://github.com/datalad/datalad/issues/7129 and somehow failed to find this one instead... Let's just go with more recent one since @bpoldrack said to be looking into it.
