### ISSUE TITLE
test_cached_dataset is flaky on CrippledFS

### ISSUE THREAD

**Issue by yarikoptic** [datalad/datalad#4777]
```
FAIL: datalad.tests.test_utils_cached_dataset.test_cached_dataset
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/opt/hostedtoolcache/Python/3.5.9/x64/lib/python3.5/site-packages/nose/case.py", line 198, in runTest
    self.test(*self.arg)
  File "/opt/hostedtoolcache/Python/3.5.9/x64/lib/python3.5/site-packages/datalad/tests/utils.py", line 174, in newfunc
    return func(*args, **kwargs)
  File "/opt/hostedtoolcache/Python/3.5.9/x64/lib/python3.5/site-packages/datalad/tests/utils.py", line 728, in newfunc
    return t(*(arg + (filename,)), **kw)
  File "/opt/hostedtoolcache/Python/3.5.9/x64/lib/python3.5/site-packages/datalad/tests/test_utils_cached_dataset.py", line 248, in test_cached_dataset
    decorated_test3()
  File "/opt/hostedtoolcache/Python/3.5.9/x64/lib/python3.5/site-packages/datalad/utils.py", line 1019, in intermediator
    return to_be_wrapper(*args, **kwargs)
  File "/opt/hostedtoolcache/Python/3.5.9/x64/lib/python3.5/site-packages/datalad/tests/utils.py", line 728, in newfunc
    return t(*(arg + (filename,)), **kw)
  File "/opt/hostedtoolcache/Python/3.5.9/x64/lib/python3.5/site-packages/datalad/tests/utils_cached_dataset.py", line 184, in newfunc
    return f(*(arg[:-1] + (clone_ds,)), **kw)
  File "/opt/hostedtoolcache/Python/3.5.9/x64/lib/python3.5/site-packages/datalad/tests/test_utils_cached_dataset.py", line 218, in decorated_test3
    assert_in(origin, where)
AssertionError: None not found in ['00000000-0000-0000-0000-000000000001', '6929d679-6cca-407f-8741-94ed39d35541', 'e5abd4ed-c6d2-4e11-843f-ee00faf18fa9']
```
from https://github.com/datalad/datalad/pull/4776/checks?check_run_id=918734657

**Comment by adswa** [comment]
This one is ``severity-important``, but it is a year old already. I skimmed through a few open PRs, and the test passes - does someone recall flaky behavior over the past months?

**Comment by yarikoptic** [comment]
might have been self-resolved one way or another. Found 61 oks and none of non-ok in
```
(git)smaug:/mnt/btrfs/datasets/datalad/ci/logs/2021/07[master]git
$> git grep '\.test_cached_dataset' | grep -i crippled | grep -v 'ok'
```

so let's consider it gone.

Thank you @adswa for doing bugs triage

**Comment by adswa** [comment]
Cool, thanks for checking :)

> Thank you @adswa for doing bugs triage

I had a lot of time to spend in a really messed up train journey :P
