### ISSUE TITLE
test_clone.test_reckless failures on CrippledFS build

### ISSUE THREAD

**Issue by kyleam** [datalad/datalad#4791]
`test_reckless` has failed in some [recent][0] [builds][1], though it's not failing consistently.

```
======================================================================
FAIL: datalad.core.distributed.tests.test_clone.test_reckless(True,)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/opt/hostedtoolcache/Python/3.5.9/x64/lib/python3.5/site-packages/nose/case.py", line 198, in runTest
    self.test(*self.arg)
  File "/opt/hostedtoolcache/Python/3.5.9/x64/lib/python3.5/site-packages/datalad/tests/utils.py", line 731, in newfunc
    return t(*(arg + (filename,)), **kw)
  File "/opt/hostedtoolcache/Python/3.5.9/x64/lib/python3.5/site-packages/datalad/tests/utils.py", line 731, in newfunc
    return t(*(arg + (filename,)), **kw)
  File "/opt/hostedtoolcache/Python/3.5.9/x64/lib/python3.5/site-packages/datalad/tests/utils.py", line 731, in newfunc
    return t(*(arg + (filename,)), **kw)
  File "/opt/hostedtoolcache/Python/3.5.9/x64/lib/python3.5/site-packages/datalad/core/distributed/tests/test_clone.py", line 354, in check_reckless
    eq_(sds.config.get('datalad.clone.reckless', None), 'auto')
AssertionError: None != 'auto'
```

Locally I ran it a dozen or so times under `./tools/eval_under_testloopfs` and haven't been able to trigger it.

[0]: https://github.com/datalad/datalad/runs/931031402
[1]: https://github.com/datalad/datalad/runs/932167232

**Comment by kyleam** [comment]
I have high hopes that this was fixed in gh-5276 (thanks @yarikoptic).
