### ISSUE TITLE
TST:  datalad.customremotes.tests.test_datalad.test_interactions started to fail

### ISSUE THREAD

**Issue by yarikoptic** [datalad/datalad#4818]
During tests of #4816 on travis in multiple runs (so not just flaky I guess)

https://travis-ci.org/github/datalad/datalad/jobs/717252148
https://travis-ci.org/github/datalad/datalad/jobs/717252150
https://travis-ci.org/github/datalad/datalad/jobs/717252153

```
======================================================================
ERROR: datalad.customremotes.tests.test_datalad.test_interactions
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/travis/virtualenv/python3.8.1/lib/python3.8/site-packages/datalad/customremotes/base.py", line 404, in main
    self._loop()
  File "/home/travis/virtualenv/python3.8.1/lib/python3.8/site-packages/datalad/customremotes/base.py", line 426, in _loop
    l = self.read(n=1)
  File "/home/travis/virtualenv/python3.8.1/lib/python3.8/site-packages/datalad/customremotes/base.py", line 363, in read
    l = self.fin.readline().rstrip(os.linesep)
  File "/home/travis/virtualenv/python3.8.1/lib/python3.8/site-packages/datalad/customremotes/tests/test_base.py", line 83, in readline
    return self._pop().rstrip('\n')
  File "/home/travis/virtualenv/python3.8.1/lib/python3.8/site-packages/datalad/customremotes/tests/test_base.py", line 74, in _pop
    raise IndexError("we are empty")
IndexError: we are empty
During handling of the above exception, another exception occurred:
Traceback (most recent call last):
  File "/home/travis/virtualenv/python3.8.1/lib/python3.8/site-packages/nose/case.py", line 198, in runTest
    self.test(*self.arg)
  File "/home/travis/virtualenv/python3.8.1/lib/python3.8/site-packages/datalad/tests/utils.py", line 554, in newfunc
    return t(*(arg + (d,)), **kw)
  File "/home/travis/virtualenv/python3.8.1/lib/python3.8/site-packages/datalad/customremotes/tests/test_datalad.py", line 113, in test_interactions
    check_interaction_scenario(DataladAnnexCustomRemote, tdir, scenario)
  File "/home/travis/virtualenv/python3.8.1/lib/python3.8/site-packages/datalad/customremotes/tests/test_base.py", line 100, in check_interaction_scenario
    cr.main()
  File "/home/travis/virtualenv/python3.8.1/lib/python3.8/site-packages/datalad/customremotes/base.py", line 410, in main
    self.stop(str(e))
  File "/home/travis/virtualenv/python3.8.1/lib/python3.8/site-packages/datalad/customremotes/base.py", line 417, in stop
    raise AnnexRemoteQuit(msg)
datalad.customremotes.base.AnnexRemoteQuit: we are empty
```

**Comment by yarikoptic** [comment]
probably just that PR changes (was not obvious), so false alarm, sorry
