### ISSUE TITLE
The most recent setuptools breaks installation on readthedocs

### ISSUE THREAD

**Issue by adswa** [datalad/datalad#4856]
On readthedocs, the builds for the docs currently break. I think the reason is a broken setuptools release (version 50.0.0, released August 30th), see https://github.com/pypa/setuptools/issues/2353 <details><summary>Here is the traceback for readthedocs</summary>

```
Processing /home/docs/checkouts/readthedocs.org/user_builds/datalad/checkouts/latest
  Installing build dependencies: started
  Installing build dependencies: finished with status 'done'
  Getting requirements to build wheel: started
  Getting requirements to build wheel: finished with status 'done'
ERROR: Exception:
Traceback (most recent call last):
  File "/home/docs/checkouts/readthedocs.org/user_builds/datalad/envs/latest/lib/python3.7/site-packages/pip/_internal/cli/base_command.py", line 216, in _main
    status = self.run(options, args)
  File "/home/docs/checkouts/readthedocs.org/user_builds/datalad/envs/latest/lib/python3.7/site-packages/pip/_internal/cli/req_command.py", line 182, in wrapper
    return func(self, options, args)
  File "/home/docs/checkouts/readthedocs.org/user_builds/datalad/envs/latest/lib/python3.7/site-packages/pip/_internal/commands/install.py", line 325, in run
    reqs, check_supported_wheels=not options.target_dir
  File "/home/docs/checkouts/readthedocs.org/user_builds/datalad/envs/latest/lib/python3.7/site-packages/pip/_internal/resolution/legacy/resolver.py", line 183, in resolve
    discovered_reqs.extend(self._resolve_one(requirement_set, req))
  File "/home/docs/checkouts/readthedocs.org/user_builds/datalad/envs/latest/lib/python3.7/site-packages/pip/_internal/resolution/legacy/resolver.py", line 388, in _resolve_one
    abstract_dist = self._get_abstract_dist_for(req_to_install)
  File "/home/docs/checkouts/readthedocs.org/user_builds/datalad/envs/latest/lib/python3.7/site-packages/pip/_internal/resolution/legacy/resolver.py", line 340, in _get_abstract_dist_for
    abstract_dist = self.preparer.prepare_linked_requirement(req)
  File "/home/docs/checkouts/readthedocs.org/user_builds/datalad/envs/latest/lib/python3.7/site-packages/pip/_internal/operations/prepare.py", line 483, in prepare_linked_requirement
    req, self.req_tracker, self.finder, self.build_isolation,
  File "/home/docs/checkouts/readthedocs.org/user_builds/datalad/envs/latest/lib/python3.7/site-packages/pip/_internal/operations/prepare.py", line 91, in _get_prepared_distribution
    abstract_dist.prepare_distribution_metadata(finder, build_isolation)
  File "/home/docs/checkouts/readthedocs.org/user_builds/datalad/envs/latest/lib/python3.7/site-packages/pip/_internal/distributions/sdist.py", line 38, in prepare_distribution_metadata
    self._setup_isolation(finder)
  File "/home/docs/checkouts/readthedocs.org/user_builds/datalad/envs/latest/lib/python3.7/site-packages/pip/_internal/distributions/sdist.py", line 96, in _setup_isolation
    reqs = backend.get_requires_for_build_wheel()
  File "/home/docs/checkouts/readthedocs.org/user_builds/datalad/envs/latest/lib/python3.7/site-packages/pip/_vendor/pep517/wrappers.py", line 161, in get_requires_for_build_wheel
    'config_settings': config_settings
  File "/home/docs/checkouts/readthedocs.org/user_builds/datalad/envs/latest/lib/python3.7/site-packages/pip/_vendor/pep517/wrappers.py", line 265, in _call_hook
    raise BackendUnavailable(data.get('traceback', ''))
pip._vendor.pep517.wrappers.BackendUnavailable: Traceback (most recent call last):
  File "/home/docs/checkouts/readthedocs.org/user_builds/datalad/envs/latest/lib/python3.7/site-packages/pip/_vendor/pep517/_in_process.py", line 86, in _build_backend
    obj = import_module(mod_path)
  File "/home/docs/checkouts/readthedocs.org/user_builds/datalad/envs/latest/lib/python3.7/importlib/__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1006, in _gcd_import
  File "<frozen importlib._bootstrap>", line 983, in _find_and_load
  File "<frozen importlib._bootstrap>", line 953, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "<frozen importlib._bootstrap>", line 1006, in _gcd_import
  File "<frozen importlib._bootstrap>", line 983, in _find_and_load
  File "<frozen importlib._bootstrap>", line 967, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 677, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/home/docs/.pyenv/versions/3.7.3/lib/python3.7/site-packages/setuptools/__init__.py", line 6, in <module>
    import distutils.core
  File "/home/docs/checkouts/readthedocs.org/user_builds/datalad/envs/latest/lib/python3.7/site-packages/_distutils_hack/__init__.py", line 82, in create_module
    return importlib.import_module('._distutils', 'setuptools')
  File "/home/docs/checkouts/readthedocs.org/user_builds/datalad/envs/latest/lib/python3.7/importlib/__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
ModuleNotFoundError: No module named 'setuptools._distutils'
```
</details>

I wanted to try whether this change in ``pyproject.toml`` helps

```diff
-requires = ["setuptools>=40.8.0", "wheel"]
+requires = ["setuptools>=40.8.0<50", "wheel"]
```
but the docs are tested with GitHub workflows only, so I can't test it and I don't dare to push ;-)

**Comment by tsalo** [comment]
If it helps at all, I tried that in https://github.com/neurostuff/NiMARE/pull/331 and RTD still installed 50.0.0 (see [here](https://readthedocs.org/api/v2/build/11787234.txt)).

**Comment by adswa** [comment]
Oh, it may actually be an issue with pip: https://github.com/pypa/pip/issues/6264#issuecomment-685230919

**Comment by adswa** [comment]
It appeared to have been the case that some package had a dependency on a version of setuptools incompatible with another installed setuptools version. This has resolved itself now, and the build have been passing again.
