### ISSUE TITLE
3 fresh test failures in master on a build against current git-annex snapshot

### ISSUE THREAD

**Issue by yarikoptic** [datalad/datalad#4862]
I guess the result of https://github.com/datalad/datalad/pull/4838

see https://github.com/datalad/datalad-extensions/runs/1064624383?check_suite_focus=true
<details>
<summary>FAIL: datalad.support.tests.test_gitrepo.test_GitRepo_flyweight</summary> 

```
======================================================================
FAIL: datalad.support.tests.test_gitrepo.test_GitRepo_flyweight
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/opt/hostedtoolcache/Python/3.7.9/x64/lib/python3.7/site-packages/nose/case.py", line 198, in runTest
    self.test(*self.arg)
  File "/opt/hostedtoolcache/Python/3.7.9/x64/lib/python3.7/site-packages/datalad/tests/utils.py", line 731, in _wrap_with_tempfile
    return t(*(arg + (filename,)), **kw)
  File "/opt/hostedtoolcache/Python/3.7.9/x64/lib/python3.7/site-packages/datalad/tests/utils.py", line 731, in _wrap_with_tempfile
    return t(*(arg + (filename,)), **kw)
  File "/opt/hostedtoolcache/Python/3.7.9/x64/lib/python3.7/site-packages/datalad/support/tests/test_gitrepo.py", line 1180, in test_GitRepo_flyweight
    assert_equal(1, sys.getrefcount(repo1) - 1)
AssertionError: 1 != 6
-------------------- >> begin captured logging << --------------------
asyncio: DEBUG: Using selector: EpollSelector
asyncio: DEBUG: Using selector: EpollSelector
--------------------- >> end captured logging << ---------------------
```
</details>

<details>
<summary>FAIL: datalad.support.tests.test_annexrepo.test_AnnexRepo_flyweight</summary> 

```
======================================================================
FAIL: datalad.support.tests.test_annexrepo.test_AnnexRepo_flyweight
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/opt/hostedtoolcache/Python/3.7.9/x64/lib/python3.7/site-packages/nose/case.py", line 198, in runTest
    self.test(*self.arg)
  File "/opt/hostedtoolcache/Python/3.7.9/x64/lib/python3.7/site-packages/datalad/tests/utils.py", line 731, in _wrap_with_tempfile
    return t(*(arg + (filename,)), **kw)
  File "/opt/hostedtoolcache/Python/3.7.9/x64/lib/python3.7/site-packages/datalad/tests/utils.py", line 731, in _wrap_with_tempfile
    return t(*(arg + (filename,)), **kw)
  File "/opt/hostedtoolcache/Python/3.7.9/x64/lib/python3.7/site-packages/datalad/support/tests/test_annexrepo.py", line 1678, in test_AnnexRepo_flyweight
    assert_equal(1, sys.getrefcount(repo1) - 1)
AssertionError: 1 != 4
```
</details>

<details>
<summary>???</summary> 

```
2020-09-03T03:03:32.9143089Z datalad.tests.test_witless_runner.test_runner ... ok
2020-09-03T03:03:32.9144362Z 
2020-09-03T03:03:32.9147116Z ======================================================================
2020-09-03T03:03:32.9147278Z testing 0
2020-09-03T03:03:32.9147613Z testing 1
2020-09-03T03:03:32.9147872Z /tmp/datalad_temp_tree_test_paths_with_forward_slasheswtsr90pm
2020-09-03T03:03:32.9148151Z .: here(+) [git]
2020-09-03T03:03:32.9149082Z .: origin(+) [/tmp/datalad_temp_test_cached_datasetyiga8f5n/https___github.com_datalad_testrepo--minimalds (git)]
2020-09-03T03:03:32.9149405Z .: here(+) [git]
2020-09-03T03:03:32.9149958Z .: origin(+) [/tmp/datalad_temp_test_cached_datasetyiga8f5n/https___github.com_datalad_testrepo--minimalds (git)]
2020-09-03T03:03:32.9150234Z .: here(+) [git]
2020-09-03T03:03:32.9150747Z FAIL: datalad.distribution.tests.test_dataset.test_Dataset_flyweight
2020-09-03T03:03:32.9151171Z .: origin(+) [/tmp/datalad_temp_test_cached_datasetyiga8f5n/https___github.com_datalad_testrepo--minimalds (git)]
2020-09-03T03:03:32.9151770Z ----------------------------------------------------------------------
2020-09-03T03:03:32.9151931Z .: here(+) [git]
2020-09-03T03:03:32.9153113Z Traceback (most recent call last):
2020-09-03T03:03:32.9153619Z .: origin(+) [/tmp/datalad_temp_test_cached_datasetyiga8f5n/https___github.com_datalad_testrepo--minimalds (git)]
2020-09-03T03:03:32.9155582Z   File "/opt/hostedtoolcache/Python/3.7.9/x64/lib/python3.7/site-packages/nose/case.py", line 198, in runTest
2020-09-03T03:03:32.9156321Z Versions: annexremote=1.4.3 appdirs=1.4.4 boto=2.49.0 cmd:7z=16.02 cmd:annex=8.20200810+git123-g820d4368b-1~ndall+1 cmd:bundled-git=2.24.0 cmd:git=2.24.0 cmd:system-git=2.28.0 cmd:system-ssh=7.6p1 humanize=2.6.0 iso8601=0.1.12 keyring=21.4.0 keyrings.alt=3.4.0 msgpack=1.0.0 patoolib=1.12 requests=2.24.0 tqdm=4.48.2 wrapt=1.12.1
2020-09-03T03:03:32.9157233Z     self.test(*self.arg)
2020-09-03T03:03:32.9157697Z Obscure filename: str=b' "\';a&b&c\xce\x94\xd0\x99\xd7\xa7\xd9\x85\xe0\xb9\x97\xe3\x81\x82 `| ' repr=' "\';a&b&cΔЙקم๗あ `| '
2020-09-03T03:03:32.9159043Z   File "/opt/hostedtoolcache/Python/3.7.9/x64/lib/python3.7/site-packages/datalad/tests/utils.py", line 731, in _wrap_with_tempfile
2020-09-03T03:03:32.9159452Z Encodings: default='utf-8' filesystem='utf-8' locale.prefered='UTF-8'
2020-09-03T03:03:32.9160288Z     return t(*(arg + (filename,)), **kw)
2020-09-03T03:03:32.9161172Z Environment: LANG='C' PATH='/opt/hostedtoolcache/Python/3.7.9/x64/bin:/opt/hostedtoolcache/Python/3.7.9/x64:/home/linuxbrew/.linuxbrew/bin:/home/linuxbrew/.linuxbrew/sbin:/usr/share/rust/.cargo/bin:/home/runner/.config/composer/vendor/bin:/home/runner/.dotnet/tools:/snap/bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/usr/games:/usr/local/games' LC_CTYPE='C.UTF-8' GIT_CONFIG_PARAMETERS="'init.defaultBranch=master'"
2020-09-03T03:03:32.9162139Z   File "/opt/hostedtoolcache/Python/3.7.9/x64/lib/python3.7/site-packages/datalad/tests/utils.py", line 731, in _wrap_with_tempfile
2020-09-03T03:03:32.9162457Z     return t(*(arg + (filename,)), **kw)
2020-09-03T03:03:32.9163255Z   File "/opt/hostedtoolcache/Python/3.7.9/x64/lib/python3.7/site-packages/datalad/distribution/tests/test_dataset.py", line 359, in test_Dataset_flyweight
2020-09-03T03:03:32.9165072Z     assert_equal(1, sys.getrefcount(ds1) - 1)
2020-09-03T03:03:32.9165419Z AssertionError: 1 != 4
2020-09-03T03:03:32.9166088Z -------------------- >> begin captured logging << --------------------
2020-09-03T03:03:32.9166387Z asyncio: DEBUG: Using selector: EpollSelector
2020-09-03T03:03:32.9166648Z asyncio: DEBUG: Using selector: EpollSelector
2020-09-03T03:03:32.9166918Z asyncio: DEBUG: Using selector: EpollSelector
2020-09-03T03:03:32.9167155Z asyncio: DEBUG: Using selector: EpollSelector
2020-09-03T03:03:32.9167407Z asyncio: DEBUG: Using selector: EpollSelector
2020-09-03T03:03:32.9167655Z asyncio: DEBUG: Using selector: EpollSelector
2020-09-03T03:03:32.9167901Z asyncio: DEBUG: Using selector: EpollSelector
2020-09-03T03:03:32.9168155Z asyncio: DEBUG: Using selector: EpollSelector
2020-09-03T03:03:32.9168400Z asyncio: DEBUG: Using selector: EpollSelector
2020-09-03T03:03:32.9168748Z asyncio: DEBUG: Using selector: EpollSelector
2020-09-03T03:03:32.9168998Z asyncio: DEBUG: Using selector: EpollSelector
2020-09-03T03:03:32.9169229Z asyncio: DEBUG: Using selector: EpollSelector
2020-09-03T03:03:32.9169493Z asyncio: DEBUG: Using selector: EpollSelector
2020-09-03T03:03:32.9169740Z asyncio: DEBUG: Using selector: EpollSelector
2020-09-03T03:03:32.9170000Z asyncio: DEBUG: Using selector: EpollSelector
2020-09-03T03:03:32.9170227Z asyncio: DEBUG: Using selector: EpollSelector
2020-09-03T03:03:32.9170488Z asyncio: DEBUG: Using selector: EpollSelector
2020-09-03T03:03:32.9170715Z asyncio: DEBUG: Using selector: EpollSelector
2020-09-03T03:03:32.9170973Z asyncio: DEBUG: Using selector: EpollSelector
2020-09-03T03:03:32.9171202Z asyncio: DEBUG: Using selector: EpollSelector
2020-09-03T03:03:32.9171449Z asyncio: DEBUG: Using selector: EpollSelector
2020-09-03T03:03:32.9171691Z asyncio: DEBUG: Using selector: EpollSelector
2020-09-03T03:03:32.9171925Z asyncio: DEBUG: Using selector: EpollSelector
2020-09-03T03:03:32.9172186Z asyncio: DEBUG: Using selector: EpollSelector
2020-09-03T03:03:32.9172414Z asyncio: DEBUG: Using selector: EpollSelector
2020-09-03T03:03:32.9172675Z asyncio: DEBUG: Using selector: EpollSelector
2020-09-03T03:03:32.9172906Z asyncio: DEBUG: Using selector: EpollSelector
2020-09-03T03:03:32.9173166Z asyncio: DEBUG: Using selector: EpollSelector
2020-09-03T03:03:32.9173623Z --------------------- >> end captured logging << ---------------------
```
</details>

only one human I know might see what is happening so assigning accordingly

**Comment by kyleam** [comment]
These same spots in `test_GitRepo_flyweight` and `test_AnnexRepo_flyweight` fail for me locally.  (`test_Dataset_flyweight` passes.)  Here's what I see for a new `GitRepo` instance:

<details>
<summary>gitrepo referrers</summary>

```python
import gc
from pprint import pprint as pp
import sys
import tempfile

from datalad.support.gitrepo import GitRepo

path1 = tempfile.mkdtemp(prefix="dl-")
repo1 = GitRepo(path1, create=True)

print(f"refcount: {sys.getrefcount(repo1) - 1}")
print("referrers")
pp(gc.get_referrers(repo1))

print("--- gc.collect() -----------------------------------")
gc.collect()

print(f"refcount: {sys.getrefcount(repo1) - 1}")
print("referrers")
pp(gc.get_referrers(repo1))

print(f"\n{sys.version}")
```

```
refcount: 6
referrers
[<frame at 0x2bac2a8, file '/home/kyle/src/python/datalad/datalad/support/gitrepo.py', line 2193, code _call_git>,
 <frame at 0x2baf7a8, file '/home/kyle/src/python/datalad/datalad/support/gitrepo.py', line 2199, code _call_git>,
 <frame at 0x2b09d78, file '/home/kyle/src/python/datalad/datalad/support/gitrepo.py', line 1013, code _create_empty_repo>,
 <frame at 0x2ada778, file '/home/kyle/src/python/datalad/datalad/support/gitrepo.py', line 970, code __init__>,
 <frame at 0x7fdd975919d0, file '/home/kyle/src/python/datalad/datalad/support/repo.py', line 172, code __call__>,
 {'GitRepo': <class 'datalad.support.gitrepo.GitRepo'>,
  '__annotations__': {},
  '__builtins__': <module 'builtins' (built-in)>,
  '__cached__': None,
  '__doc__': None,
  '__file__': '/tmp/scratch.py',
  '__loader__': <_frozen_importlib_external.SourceFileLoader object at 0x7fdd98238898>,
  '__name__': '__main__',
  '__package__': None,
  '__spec__': None,
  'gc': <module 'gc' (built-in)>,
  'path1': '/tmp/dl-_u07yv4y',
  'pp': <function pprint at 0x7fdd980ef488>,
  'repo1': GitRepo('/tmp/dl-_u07yv4y'),
  'sys': <module 'sys' (built-in)>,
  'tempfile': <module 'tempfile' from '/home/kyle/src/python/venvs/datalad/lib/python3.7/tempfile.py'>}]
--- gc.collect() -----------------------------------
refcount: 1
referrers
[{'GitRepo': <class 'datalad.support.gitrepo.GitRepo'>,
  '__annotations__': {},
  '__builtins__': <module 'builtins' (built-in)>,
  '__cached__': None,
  '__doc__': None,
  '__file__': '/tmp/scratch.py',
  '__loader__': <_frozen_importlib_external.SourceFileLoader object at 0x7fdd98238898>,
  '__name__': '__main__',
  '__package__': None,
  '__spec__': None,
  'gc': <module 'gc' (built-in)>,
  'path1': '/tmp/dl-_u07yv4y',
  'pp': <function pprint at 0x7fdd980ef488>,
  'repo1': GitRepo('/tmp/dl-_u07yv4y'),
  'sys': <module 'sys' (built-in)>,
  'tempfile': <module 'tempfile' from '/home/kyle/src/python/venvs/datalad/lib/python3.7/tempfile.py'>}]

3.7.3 (default, Apr  3 2019, 05:39:12) 
[GCC 8.3.0]
```

</details>

**Comment by mih** [comment]
I can also confirm that this is happening all over the place. Ping @bpoldrack

**Comment by mih** [comment]
Most recent master travis run doesn't show a failure https://travis-ci.org/github/datalad/datalad

**Comment by bpoldrack** [comment]
Hm. Someone reintroduced an issue with a traceback, I guess. Will look into it over the weekend.

**Comment by yarikoptic** [comment]
Ha ha, I was dreaming of you while you were writing this message @bpoldrack : we were going to Montreal (from Hanover). Purpose: not so clear but has to do with a hospital... Nothing about traceback though

**Comment by bpoldrack** [comment]
Oh, it's a shared dream to go to Montreal together, @yarikoptic !
Not sure about the hospital, though.

**Comment by bpoldrack** [comment]
It doesn't happen for me on master. Can you guys tell me the exact commit you're running into the issue on, @mih, @kyleam, @yarikoptic ? Just to be sure.

Otherwise, Kyle's post suggests it's the same traceback that seemed to be gone when Michael's witless-runner PR was merged (and made it pass on Travis and locally for me ever since). However, the line numbers of your referrers are off - all amidst comments on "my" master. They are just close by the call path I was talking about. So - makes me wonder who is missing what commit.

**Comment by bpoldrack** [comment]
Python version would also be nice. I have a suspicion that it is about this innocent little change (but may be only w/ particular python versions/interpreters): 445c2fd9adbe4dc73749cd072960cf0dc1aa26ac

Either way - need something to reproduce in order to fix it.

**Comment by mih** [comment]
This is the latest run that shows the failure: https://github.com/datalad/datalad-extensions/runs/1076806498

I have seen it in most (all?) PRs that I proposed today.

```
Python 3.7.5
git version 2.27.0
git-annex version: 8.20200330
```

**Comment by bpoldrack** [comment]
So, I can definitely not reproduce it on master (same commit). Running python 3.8.5, though.

> I have seen it in most (all?) PRs that I proposed today.

I have no idea what you are talking about. I can't find it in any of the Travis builds in your PRs #4887, #4883, #4882, #4891, #4889  ...

**Comment by bpoldrack** [comment]
Trying to reproduce it via Travis failed on unchanged master: #4894. So, the python version itself isn't the difference.

It's clear that this is the same `traceback` object I thought was gone (and is gone for me and Travis).  There would be an obvious way to make the test pass for you guys: Explicitly clearing the frames of their references to local variables when we catch the exception in `GitRepo._create_empty_repo`. However, that doesn't explain why it's not there for me and Travis. And for a real effect we need a general solution, otherwise any such exception causes `*Repo`s to still not be reliably killed when we `del` our last reference. In other words: Still depend on `gc.collect()`.

**Comment by bpoldrack** [comment]
So, as long as I can't reproduce and figure out when exactly it is happening and when it's not, will need to adapt the tests, I guess. See PR #4897.

**Comment by bpoldrack** [comment]
Generally, I think the issue is our exception logging/handling. From the runner(s) upwards we grep a local reference to an exception in order to log it. Then reraise. Now, even if we finally handle the exception, it has reference to a traceback object, that references all the function frames, which reference their local variables, one of which is .. the exception. And there we have a cycle. Since the functions themselves are methods of the `*Repo`s, we inherit the problem for them, thus they don't get picked up by instant, refcount based GC.
The mysterious thing is, why does it not happen for me and Travis? Frames can be cleared of their references to local variables (for that very reason). It looks to me like it's very specific to python version/interpreter whether or when then happens automatically.

**Comment by kyleam** [comment]
> Can you guys tell me the exact commit you're running into the issue on, @mih, @kyleam, @yarikoptic ?


The output I showed was on f67fc69.  But I see the same output right when your PR was brought in with 996368d32 (Merge pull request #4838 from bpoldrack/gh-4827, 2020-09-02).

<details>
<summary>output</summary>

```
refcount: 6
referrers
[<frame at 0x233b398, file '/home/kyle/src/python/datalad/datalad/support/gitrepo.py', line 2193, code _call_git>,
 <frame at 0x233e898, file '/home/kyle/src/python/datalad/datalad/support/gitrepo.py', line 2199, code _call_git>,
 <frame at 0x22991b8, file '/home/kyle/src/python/datalad/datalad/support/gitrepo.py', line 1013, code _create_empty_repo>,
 <frame at 0x2269f28, file '/home/kyle/src/python/datalad/datalad/support/gitrepo.py', line 970, code __init__>,
 <frame at 0x7f5c551899d0, file '/home/kyle/src/python/datalad/datalad/support/repo.py', line 172, code __call__>,
 {'GitRepo': <class 'datalad.support.gitrepo.GitRepo'>,
  '__annotations__': {},
  '__builtins__': <module 'builtins' (built-in)>,
  '__cached__': None,
  '__doc__': None,
  '__file__': '/tmp/scratch.py',
  '__loader__': <_frozen_importlib_external.SourceFileLoader object at 0x7f5c55e33898>,
  '__name__': '__main__',
  '__package__': None,
  '__spec__': None,
  'gc': <module 'gc' (built-in)>,
  'path1': '/tmp/dl-w_oiif4x',
  'pp': <function pprint at 0x7f5c55cea488>,
  'repo1': GitRepo('/tmp/dl-w_oiif4x'),
  'sys': <module 'sys' (built-in)>,
  'tempfile': <module 'tempfile' from '/home/kyle/src/python/venvs/datalad/lib/python3.7/tempfile.py'>}]
--- gc.collect() -----------------------------------
refcount: 1
referrers
[{'GitRepo': <class 'datalad.support.gitrepo.GitRepo'>,
  '__annotations__': {},
  '__builtins__': <module 'builtins' (built-in)>,
  '__cached__': None,
  '__doc__': None,
  '__file__': '/tmp/scratch.py',
  '__loader__': <_frozen_importlib_external.SourceFileLoader object at 0x7f5c55e33898>,
  '__name__': '__main__',
  '__package__': None,
  '__spec__': None,
  'gc': <module 'gc' (built-in)>,
  'path1': '/tmp/dl-w_oiif4x',
  'pp': <function pprint at 0x7f5c55cea488>,
  'repo1': GitRepo('/tmp/dl-w_oiif4x'),
  'sys': <module 'sys' (built-in)>,
  'tempfile': <module 'tempfile' from '/home/kyle/src/python/venvs/datalad/lib/python3.7/tempfile.py'>}]

3.7.3 (default, Apr  3 2019, 05:39:12) 
[GCC 8.3.0]
```

</details>



> Python version would also be nice.

That was included in the script's output.

**Comment by bpoldrack** [comment]
Note to future self, since it's unclear ho far in the future that might be:

IF I'm right about that, what comes to my mind ATM would be this possible solution:

 - in any `except ... as variable:`, that is part of a method of a class, `clear()` the function frame(s) of this exception's `__traceback__` to eliminate potential cycles (particularly involving the instance whose method we are in)

Anything else, I can currently think of, is even more work and requires even more shared discipline and awareness.

**Comment by bpoldrack** [comment]
> That was included in the script's output.

Yes, I noticed in the meantime. Thank you!

**Comment by kyleam** [comment]
> It looks to me like it's very specific to python version/interpreter whether or when then happens automatically.

FWIW I just tried with python 3.8 (built from db2f3114b2), and the first `sys.getrefcount(repo1) - 1` from my script outputs a count of 1.  If I try with 3.7 (built from 4c71c83073), it shows 5.

**Comment by bpoldrack** [comment]
Seems to be about PY3.7 indeed. In some sense there's progress: Using Yarik's approach to run different versions via conda, I can now see it happening with 3.7 while everything works fine with 3.6 and 3.8. Given that Travis didn't show the issue, it's python 3.7 > 3.7.1
Anyways - can reproduce finally, so I'll have another look into it.

**Comment by mih** [comment]
I haven't seen this in a while. Do we need to keep it open?

**Comment by yarikoptic** [comment]
@mih did not see it for a while, I will file dedicated ones if I see them again (may be already skipped some of those), so let's close

**Comment by kyleam** [comment]
> @mih did not see it for a while

Hmm, I don't think we would expect to see it given gh-4897 was merged.
