### ISSUE TITLE
test_push_subds_no_recursion fails on crippledFS

### ISSUE THREAD

**Issue by yarikoptic** [datalad/datalad#4870]
e.g. https://github.com/datalad/datalad/pull/4448/checks?check_run_id=1073144931#step:8:217 

<details>
<summary>cut/paste from above</summary> 

```shell
2020-09-04T17:57:21.9815659Z ======================================================================
2020-09-04T17:57:21.9815848Z FAIL: datalad.core.distributed.tests.test_push.test_push_subds_no_recursion
2020-09-04T17:57:21.9816566Z ----------------------------------------------------------------------
2020-09-04T17:57:21.9816697Z Traceback (most recent call last):
2020-09-04T17:57:21.9818321Z   File "/opt/hostedtoolcache/Python/3.5.9/x64/lib/python3.5/site-packages/nose/case.py", line 198, in runTest
2020-09-04T17:57:21.9818576Z     self.test(*self.arg)
2020-09-04T17:57:21.9819413Z   File "/opt/hostedtoolcache/Python/3.5.9/x64/lib/python3.5/site-packages/datalad/tests/utils.py", line 731, in _wrap_with_tempfile
2020-09-04T17:57:21.9819575Z     return t(*(arg + (filename,)), **kw)
2020-09-04T17:57:21.9819999Z   File "/opt/hostedtoolcache/Python/3.5.9/x64/lib/python3.5/site-packages/datalad/tests/utils.py", line 731, in _wrap_with_tempfile
2020-09-04T17:57:21.9824906Z .: store(+) [ora]
2020-09-04T17:57:21.9825221Z .: here(+) [git]
2020-09-04T17:57:21.9825447Z .: here(+) [git]
2020-09-04T17:57:21.9826106Z .: origin(+) [/crippledfs/datalad_temp_test_cached_datasetyx1uiiwu/https___github.com_datalad_testrepo--minimalds (git)]
2020-09-04T17:57:21.9826613Z .: here(+) [git]
2020-09-04T17:57:21.9827147Z .: origin(+) [/crippledfs/datalad_temp_test_cached_datasetyx1uiiwu/https___github.com_datalad_testrepo--minimalds (git)]
2020-09-04T17:57:21.9827445Z .: here(+) [git]
2020-09-04T17:57:21.9827931Z .: origin(+) [/crippledfs/datalad_temp_test_cached_datasetyx1uiiwu/https___github.com_datalad_testrepo--minimalds (git)]
2020-09-04T17:57:21.9828226Z .: here(+) [git]
2020-09-04T17:57:21.9828712Z .: origin(+) [/crippledfs/datalad_temp_test_cached_datasetyx1uiiwu/https___github.com_datalad_testrepo--minimalds (git)]
2020-09-04T17:57:21.9829955Z Versions: annexremote=1.4.3 appdirs=1.4.4 boto=2.49.0 cmd:7z=16.02 cmd:annex=8.20200810+git69-g02a35c9ce-1~ndall+1 cmd:bundled-git=2.24.0 cmd:git=2.24.0 cmd:system-git=2.28.0 cmd:system-ssh=7.6p1 exifread=2.3.1 humanize=2.6.0 iso8601=0.1.12 keyring=20.0.1 keyrings.alt=3.2.0 msgpack=1.0.0 mutagen=1.45.1 requests=2.24.0 tqdm=4.48.2 wrapt=1.12.1
2020-09-04T17:57:21.9830874Z Obscure filename: str=b' ;abc\xce\x94\xd0\x99\xd7\xa7\xd9\x85\xe0\xb9\x97\xe3\x81\x82' repr=' ;abcΔЙקم๗あ'
2020-09-04T17:57:21.9831464Z Encodings: default='utf-8' filesystem='utf-8' locale.prefered='UTF-8'
2020-09-04T17:57:21.9832313Z Environment: GIT_CONFIG_PARAMETERS="'init.defaultBranch=master'" PATH='/opt/hostedtoolcache/Python/3.5.9/x64/bin:/opt/hostedtoolcache/Python/3.5.9/x64:/home/linuxbrew/.linuxbrew/bin:/home/linuxbrew/.linuxbrew/sbin:/usr/share/rust/.cargo/bin:/home/runner/.config/composer/vendor/bin:/home/runner/.dotnet/tools:/snap/bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/usr/games:/usr/local/games' LANG='C.UTF-8'
2020-09-04T17:57:21.9874416Z     return t(*(arg + (filename,)), **kw)
2020-09-04T17:57:21.9875047Z   File "/opt/hostedtoolcache/Python/3.5.9/x64/lib/python3.5/site-packages/datalad/tests/utils.py", line 731, in _wrap_with_tempfile
2020-09-04T17:57:21.9875208Z     return t(*(arg + (filename,)), **kw)
2020-09-04T17:57:21.9875655Z   File "/opt/hostedtoolcache/Python/3.5.9/x64/lib/python3.5/site-packages/datalad/tests/utils.py", line 731, in _wrap_with_tempfile
2020-09-04T17:57:21.9875792Z     return t(*(arg + (filename,)), **kw)
2020-09-04T17:57:21.9876308Z   File "/opt/hostedtoolcache/Python/3.5.9/x64/lib/python3.5/site-packages/datalad/core/distributed/tests/test_push.py", line 400, in test_push_subds_no_recursion
2020-09-04T17:57:21.9876604Z     assert_status('ok', res)
2020-09-04T17:57:21.9877002Z   File "/opt/hostedtoolcache/Python/3.5.9/x64/lib/python3.5/site-packages/datalad/tests/utils.py", line 1292, in assert_status
2020-09-04T17:57:21.9877155Z     dumps(results, indent=1, default=lambda x: str(x))))
2020-09-04T17:57:21.9877446Z AssertionError: Test 3/5: expected status ['ok'] not found in:
2020-09-04T17:57:21.9877559Z [
2020-09-04T17:57:21.9877658Z  {
2020-09-04T17:57:21.9877764Z   "action": "publish",
2020-09-04T17:57:21.9877873Z   "type": "dataset",
2020-09-04T17:57:21.9877979Z   "target": "target",
2020-09-04T17:57:21.9878239Z   "refspec": "refs/heads/git-annex:refs/heads/git-annex",
2020-09-04T17:57:21.9878477Z   "status": "ok",
2020-09-04T17:57:21.9879082Z   "refds": "/crippledfs/datalad_temp_test_push_subds_no_recursionauhdo5sj",
2020-09-04T17:57:21.9879474Z   "path": "/crippledfs/datalad_temp_test_push_subds_no_recursionauhdo5sj",
2020-09-04T17:57:21.9879611Z   "operations": [
2020-09-04T17:57:21.9879935Z    "fast-forward"
2020-09-04T17:57:21.9880247Z   ],
2020-09-04T17:57:21.9880617Z   "message": "refs/heads/git-annex->target:refs/heads/git-annex 6f9a4f6..8e931bc",
2020-09-04T17:57:21.9880742Z   "hints": null
2020-09-04T17:57:21.9880856Z  },
2020-09-04T17:57:21.9880967Z  {
2020-09-04T17:57:21.9881081Z   "action": "publish",
2020-09-04T17:57:21.9881199Z   "type": "dataset",
2020-09-04T17:57:21.9881316Z   "target": "target",
2020-09-04T17:57:21.9881443Z   "refspec": "refs/heads/master:refs/heads/master",
2020-09-04T17:57:21.9881554Z   "status": "ok",
2020-09-04T17:57:21.9881686Z   "refds": "/crippledfs/datalad_temp_test_push_subds_no_recursionauhdo5sj",
2020-09-04T17:57:21.9881843Z   "path": "/crippledfs/datalad_temp_test_push_subds_no_recursionauhdo5sj",
2020-09-04T17:57:21.9881980Z   "operations": [
2020-09-04T17:57:21.9882241Z    "new-branch"
2020-09-04T17:57:21.9882359Z   ],
2020-09-04T17:57:21.9882783Z   "message": "refs/heads/master->target:refs/heads/master [new branch]",
2020-09-04T17:57:21.9882908Z   "hints": null
2020-09-04T17:57:21.9882999Z  },
2020-09-04T17:57:21.9883110Z  {
2020-09-04T17:57:21.9883227Z   "refds": "/crippledfs/datalad_temp_test_push_subds_no_recursionauhdo5sj",
2020-09-04T17:57:21.9899437Z   "action": "copy",
2020-09-04T17:57:21.9899574Z   "path": "/crippledfs/datalad_temp_test_push_subds_no_recursionauhdo5sj/sub m",
2020-09-04T17:57:21.9899699Z   "target": "target",
2020-09-04T17:57:21.9899806Z   "message": [
2020-09-04T17:57:21.9900199Z    "Target '%s' does not appear to be an annex remote",
2020-09-04T17:57:21.9900319Z    "target"
2020-09-04T17:57:21.9900406Z   ],
2020-09-04T17:57:21.9900512Z   "status": "notneeded",
2020-09-04T17:57:21.9900765Z   "type": "dataset"
2020-09-04T17:57:21.9900884Z  },
2020-09-04T17:57:21.9900984Z  {
2020-09-04T17:57:21.9901089Z   "action": "publish",
2020-09-04T17:57:21.9901195Z   "type": "dataset",
2020-09-04T17:57:21.9901283Z   "target": "target",
2020-09-04T17:57:21.9901593Z   "refspec": "refs/heads/git-annex:refs/heads/git-annex",
2020-09-04T17:57:21.9901711Z   "status": "ok",
2020-09-04T17:57:21.9901837Z   "refds": "/crippledfs/datalad_temp_test_push_subds_no_recursionauhdo5sj",
2020-09-04T17:57:21.9901973Z   "path": "/crippledfs/datalad_temp_test_push_subds_no_recursionauhdo5sj/sub m",
2020-09-04T17:57:21.9902093Z   "operations": [
2020-09-04T17:57:21.9902325Z    "fast-forward"
2020-09-04T17:57:21.9902429Z   ],
2020-09-04T17:57:21.9902778Z   "message": "refs/heads/git-annex->target:refs/heads/git-annex 019a44c..4e083ca",
2020-09-04T17:57:21.9902905Z   "hints": null
2020-09-04T17:57:21.9903007Z  },
2020-09-04T17:57:21.9903105Z  {
2020-09-04T17:57:21.9903208Z   "action": "publish",
2020-09-04T17:57:21.9903319Z   "type": "dataset",
2020-09-04T17:57:21.9903424Z   "target": "target",
2020-09-04T17:57:21.9903522Z   "refspec": "refs/heads/master:refs/heads/master",
2020-09-04T17:57:21.9903631Z   "status": "ok",
2020-09-04T17:57:21.9903749Z   "refds": "/crippledfs/datalad_temp_test_push_subds_no_recursionauhdo5sj",
2020-09-04T17:57:21.9903884Z   "path": "/crippledfs/datalad_temp_test_push_subds_no_recursionauhdo5sj/sub m",
2020-09-04T17:57:21.9904011Z   "operations": [
2020-09-04T17:57:21.9904246Z    "new-branch"
2020-09-04T17:57:21.9904353Z   ],
2020-09-04T17:57:21.9904621Z   "message": "refs/heads/master->target:refs/heads/master [new branch]",
2020-09-04T17:57:21.9904727Z   "hints": null
2020-09-04T17:57:21.9904827Z  }
2020-09-04T17:57:21.9904927Z ]
```
</details>

**Comment by mih** [comment]
The tests seems fine on windows and in that github action now:
- https://ci.appveyor.com/project/mih/datalad/builds/37297560/job/7th4w1w81okevvuv#L645
- https://github.com/datalad/datalad/runs/1713584550?check_suite_focus=true#step:8:99
