### ISSUE TITLE
Failing test_annexrepo.test_AnnexRepo_instance_from_clone with newer GitPython

### ISSUE THREAD

**Issue by yarikoptic** [datalad/datalad#489]
across all environments, see e.g. travis build https://travis-ci.org/datalad/datalad/jobs/134166919:
(pasted actually from OSX env)
```

======================================================================
FAIL: datalad.tests.test_annexrepo.test_AnnexRepo_instance_from_clone
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/Users/datalad/buildslave/datalad-pr-dl-osx-64/build/venv-ci/lib/python2.7/site-packages/nose/case.py", line 197, in runTest
    self.test(*self.arg)
  File "/Users/datalad/buildslave/datalad-pr-dl-osx-64/build/datalad/tests/utils.py", line 835, in newfunc
    func(*args, **kwargs)
  File "/Users/datalad/buildslave/datalad-pr-dl-osx-64/build/datalad/tests/utils.py", line 781, in newfunc
    reraise(*exc_info)
  File "/Users/datalad/buildslave/datalad-pr-dl-osx-64/build/datalad/tests/utils.py", line 757, in newfunc
    func(*args, **kwargs)
  File "/Users/datalad/buildslave/datalad-pr-dl-osx-64/build/datalad/tests/utils.py", line 674, in newfunc
    t(*(arg + (uri,)), **kw)
  File "/Users/datalad/buildslave/datalad-pr-dl-osx-64/build/datalad/tests/utils.py", line 486, in newfunc
    return t(*(arg + (filename,)), **kw)
  File "/Users/datalad/buildslave/datalad-pr-dl-osx-64/build/datalad/tests/test_annexrepo.py", line 45, in test_AnnexRepo_instance_from_clone
    assert("already exists" in cm.out)
AssertionError: 
```

**Comment by yarikoptic** [comment]
ideally -- use `assert_in` helper, so it would look like `assert_in("already exists", cm.out)` because then it will also printout cm.out so you can see what was actual value

**Comment by bpoldrack** [comment]
Nope. It's not the merge, that causes this. It's GitPython 2.0.5
Fixed in #435

**Comment by yarikoptic** [comment]
Ah -- great!  sorry for me incorrectly associating with the cause.
#435 concerns primarily with ssh interface -- not yet ready for merging AFAIK.  Could you extract that fix and submit as a separate PR please?  that would allow for tests for new/outstanding PRs to pass again, and we need such a fix asap.
Also, it is preferable to have issues closed by commits/pull requests so we have clear idea that they are indeed fixed in master.  ATM this issue is not fixed, thus reopening, and if new PR would resolve it, add `Closes #489` into its description or better into a corresponding commit msg

**Comment by hanke** [comment]
So I will retitle the issue....

**Comment by hanke** [comment]
#477 also affected.

**Comment by hanke** [comment]
Fix: https://github.com/datalad/datalad/pull/477/commits/b5980d36862b553d67b4ea739c65bc4fb69162d3

will come in with merge of #477 in a few minutes.

**Comment by hanke** [comment]
Fix is present in master. Please adjust your PRs accordingly (if desired).

**Comment by yarikoptic** [comment]
Thanks!

**Comment by glalteva** [comment]
I adjusted my PR #480. Travis builds but I am still receiving a failed test:

`======================================================================
FAIL: datalad.tests.test_annexrepo.test_AnnexRepo_instance_from_clone
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/Users/datalad/buildslave/datalad-pr-dl-osx-64/build/venv-ci/lib/python2.7/site-packages/nose/case.py", line 197, in runTest
    self.test(*self.arg)
  File "/Users/datalad/buildslave/datalad-pr-dl-osx-64/build/datalad/tests/utils.py", line 835, in newfunc
    func(*args, **kwargs)
  File "/Users/datalad/buildslave/datalad-pr-dl-osx-64/build/datalad/tests/utils.py", line 781, in newfunc
    reraise(*exc_info)
  File "/Users/datalad/buildslave/datalad-pr-dl-osx-64/build/datalad/tests/utils.py", line 757, in newfunc
    func(*args, **kwargs)
  File "/Users/datalad/buildslave/datalad-pr-dl-osx-64/build/datalad/tests/utils.py", line 674, in newfunc
    t(*(arg + (uri,)), **kw)
  File "/Users/datalad/buildslave/datalad-pr-dl-osx-64/build/datalad/tests/utils.py", line 486, in newfunc
    return t(*(arg + (filename,)), **kw)
  File "/Users/datalad/buildslave/datalad-pr-dl-osx-64/build/datalad/tests/test_annexrepo.py", line 45, in test_AnnexRepo_instance_from_clone
    assert("already exists" in cm.out)`

**Comment by bpoldrack** [comment]
Interesting. What gitpython version are you using?
(see git.__version__ in python)

2016-06-01 15:20 GMT+02:00 Gergana Alteva <notifications@github.com>:

**Comment by bpoldrack** [comment]
Hold on. Stupid me. It's travis not your local tests failing, right?

2016-06-01 16:48 GMT+02:00 Benjamin Poldrack <benjaminpoldrack@gmail.com>:

**Comment by yarikoptic** [comment]
I guess it was somehow due to buildbot not merging master for testing (smth to keep in mind)... I believe that @glalteva merged origin/master and pushed now and test passed (see #480)
