### ISSUE TITLE
addurls -> AnnexRepo.add_url_to_file: KeyError: 'command'

### ISSUE THREAD

**Issue by yarikoptic** [datalad/datalad#4913]
Trying to establish generation and update of datasets from NDA.  Invocation of `addurls` is at https://github.com/yarikoptic/datalad-nda/blob/9885445e510e09183d2068264e8cded3b0bd75e7/scripts/datalad-nda#L226 .  I am using datalad master 0.13.3-230-g4f8fe6e4a with https://github.com/datalad/datalad/pull/4803 merged so I could use procedure in superdataset to setup subdatasets (`addurls` already does `superdataset.create(subdspath, ...)` so all good on that). 
<details>
<summary>the log</summary> 

```shell
INFO:datalad-nda:Processing for submission 21948
INFO:datalad-nda:Getting records only for submission_id=21948
INFO:datalad-nda:Got 331758 records
INFO:datalad-nda:Processed entire file: got 331758 files, 2 subdatasets with 7 files having multiple URLs to possibly reach them
INFO:datalad-nda:Saved output to <_io.TextIOWrapper name='/mnt/scrap/tmp/abcd/testds-fast-full/sourcedata/submission-21948.csv' mode='w' encoding='UTF-8'>
[WARNING] Not creating subdataset at existing path: sourcedata
WARNING:datalad.plugin.addurls:Not creating subdataset at existing path: sourcedata
initremote datalad ok
(recording state in git...)
[WARNING] Caught Command '['git', 'annex', 'addurl', '--fast', '--with-files', '--json', '--json-error-messages', '--batch']' timed out after 3.0 seconds [subprocess.py:_wait:1616] on trial #1. Sleeping 1.000000 and retrying
WARNING:datalad.utils:Caught Command '['git', 'annex', 'addurl', '--fast', '--with-files', '--json', '--json-error-messages', '--batch']' timed out after 3.0 seconds [subprocess.py:_wait:1616] on trial #1. Sleeping 1.000000 and retrying
[WARNING] Caught Command '['git', 'annex', 'addurl', '--fast', '--with-files', '--json', '--json-error-messages', '--batch']' timed out after 3.0 seconds [subprocess.py:_wait:1616] on trial #2. Sleeping 1.000000 and retrying  
WARNING:datalad.utils:Caught Command '['git', 'annex', 'addurl', '--fast', '--with-files', '--json', '--json-error-messages', '--batch']' timed out after 3.0 seconds [subprocess.py:_wait:1616] on trial #2. Sleeping 1.000000 and retrying
[WARNING] Caught Command '['git', 'annex', 'addurl', '--fast', '--with-files', '--json', '--json-error-messages', '--batch']' timed out after 3.0 seconds [subprocess.py:_wait:1616] on trial #1. Sleeping 1.000000 and retrying  
WARNING:datalad.utils:Caught Command '['git', 'annex', 'addurl', '--fast', '--with-files', '--json', '--json-error-messages', '--batch']' timed out after 3.0 seconds [subprocess.py:_wait:1616] on trial #1. Sleeping 1.000000 and retrying
[WARNING] Caught Command '['git', 'annex', 'addurl', '--fast', '--with-files', '--json', '--json-error-messages', '--batch']' timed out after 3.0 seconds [subprocess.py:_wait:1616] on trial #2. Sleeping 1.000000 and retrying  
WARNING:datalad.utils:Caught Command '['git', 'annex', 'addurl', '--fast', '--with-files', '--json', '--json-error-messages', '--batch']' timed out after 3.0 seconds [subprocess.py:_wait:1616] on trial #2. Sleeping 1.000000 and retrying
[WARNING] Batched process <subprocess.Popen object at 0x7f0d2fd5eb38> did not finish, abandoning it without killing it
WARNING:datalad.cmd:Batched process <subprocess.Popen object at 0x7f0d2fd5eb38> did not finish, abandoning it without killing it
[WARNING] Caught Command '['git', 'annex', 'addurl', '--fast', '--with-files', '--json', '--json-error-messages', '--batch']' timed out after 3.0 seconds [subprocess.py:_wait:1616] on trial #1. Sleeping 1.000000 and retrying
WARNING:datalad.utils:Caught Command '['git', 'annex', 'addurl', '--fast', '--with-files', '--json', '--json-error-messages', '--batch']' timed out after 3.0 seconds [subprocess.py:_wait:1616] on trial #1. Sleeping 1.000000 and retrying
[WARNING] Caught Command '['git', 'annex', 'addurl', '--fast', '--with-files', '--json', '--json-error-messages', '--batch']' timed out after 3.0 seconds [subprocess.py:_wait:1616] on trial #2. Sleeping 1.000000 and retrying
WARNING:datalad.utils:Caught Command '['git', 'annex', 'addurl', '--fast', '--with-files', '--json', '--json-error-messages', '--batch']' timed out after 3.0 seconds [subprocess.py:_wait:1616] on trial #2. Sleeping 1.000000 and retrying
[WARNING] Batched process <subprocess.Popen object at 0x7f0d34c5beb8> did not finish, abandoning it without killing it
WARNING:datalad.cmd:Batched process <subprocess.Popen object at 0x7f0d34c5beb8> did not finish, abandoning it without killing it
INFO:datalad-nda:Processing for submission 22640
INFO:datalad-nda:Getting records only for submission_id=22640
INFO:datalad-nda:Got 300402 records
INFO:datalad-nda:Processed entire file: got 300402 files, 1 subdatasets with 3 files having multiple URLs to possibly reach them
INFO:datalad-nda:Saved output to <_io.TextIOWrapper name='/mnt/scrap/tmp/abcd/testds-fast-full/sourcedata/submission-22640.csv' mode='w' encoding='UTF-8'>
[WARNING] Not creating subdataset at existing path: derivatives/abcd-hcp-pipeline
WARNING:datalad.plugin.addurls:Not creating subdataset at existing path: derivatives/abcd-hcp-pipeline
[ERROR] Adding URLs: processed result for /mnt/scrap/tmp/abcd/testds-fast-full/derivatives/abcd-hcp-pipeline/sub-XXX/ses-baselineYear1Arm1/img/XXX_task-nback02_in_t1.gif
ERROR:datalad:Adding URLs: processed result for /mnt/scrap/tmp/abcd/testds-fast-full/derivatives/abcd-hcp-pipeline/sub-XXX/ses-baselineYear1Arm1/img/XXX_task-nback02_in_t1.gif
Traceback (most recent call last):
  File "datalad-nda/scripts/datalad-nda", line 409, in <module>
    main()
  File "/usr/lib/python3/dist-packages/click/core.py", line 764, in __call__
    return self.main(*args, **kwargs)
  File "/usr/lib/python3/dist-packages/click/core.py", line 717, in main
    rv = self.invoke(ctx)
  File "/usr/lib/python3/dist-packages/click/core.py", line 1137, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/usr/lib/python3/dist-packages/click/core.py", line 956, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/usr/lib/python3/dist-packages/click/core.py", line 555, in invoke
    return callback(*args, **kwargs)
  File "datalad-nda/scripts/datalad-nda", line 232, in add2datalad
    on_failure="stop",
  File "/mnt/scrap/tmp/abcd/datalad/datalad/distribution/dataset.py", line 503, in apply_func
    return f(**kwargs)
  File "/mnt/scrap/tmp/abcd/datalad/datalad/interface/utils.py", line 481, in eval_func
    return return_func(generator_func)(*args, **kwargs)
  File "/mnt/scrap/tmp/abcd/datalad/datalad/interface/utils.py", line 469, in return_func
    results = list(results)
  File "/mnt/scrap/tmp/abcd/datalad/datalad/interface/utils.py", line 400, in generator_func
    allkwargs):
  File "/mnt/scrap/tmp/abcd/datalad/datalad/interface/utils.py", line 539, in _process_results
    for res in results:
  File "/mnt/scrap/tmp/abcd/datalad/datalad/plugin/addurls.py", line 917, in __call__
    for r in add_urls(rows, ifexists=ifexists, options=annex_options):
  File "/mnt/scrap/tmp/abcd/datalad/datalad/log.py", line 353, in wrapped
    for res in fn(items, **kwargs):
  File "/mnt/scrap/tmp/abcd/datalad/datalad/plugin/addurls.py", line 535, in add_urls
    batch=True, options=options)
  File "/mnt/scrap/tmp/abcd/datalad/datalad/support/gitrepo.py", line 241, in _wrap_normalize_path
    return func(self, file_new, *args, **kwargs)
  File "/mnt/scrap/tmp/abcd/datalad/datalad/support/annexrepo.py", line 1872, in add_url_to_file
    assert(out_json['command'] == 'addurl')
KeyError: 'command'
[WARNING] Caught Command '['git', 'annex', 'addurl', '--fast', '--with-files', '--json', '--json-error-messages', '--batch']' timed out after 3.0 seconds [subprocess.py:_wait:1616] on trial #1. Sleeping 1.000000 and retrying
WARNING:datalad.utils:Caught Command '['git', 'annex', 'addurl', '--fast', '--with-files', '--json', '--json-error-messages', '--batch']' timed out after 3.0 seconds [subprocess.py:_wait:1616] on trial #1. Sleeping 1.000000 and retrying
[WARNING] Caught Command '['git', 'annex', 'addurl', '--fast', '--with-files', '--json', '--json-error-messages', '--batch']' timed out after 3.0 seconds [subprocess.py:_wait:1616] on trial #2. Sleeping 1.000000 and retrying
WARNING:datalad.utils:Caught Command '['git', 'annex', 'addurl', '--fast', '--with-files', '--json', '--json-error-messages', '--batch']' timed out after 3.0 seconds [subprocess.py:_wait:1616] on trial #2. Sleeping 1.000000 and retrying
[WARNING] Batched process <subprocess.Popen object at 0x7f0d1fc4d9e8> did not finish, abandoning it without killing it
WARNING:datalad.cmd:Batched process <subprocess.Popen object at 0x7f0d1fc4d9e8> did not finish, abandoning it without killing it

```
</details>

Notes:
- it is again batched annexed processes time out to quit.
- I guess we better avoid plain `assert`s in the code without providing in the message details (e.g. here - the `out_json`)

<details><summary>DataLad 0.13.2 WTF (configuration, datalad, dataset, dependencies, environment, extensions, git-annex, location, metadata_extractors, python, system)</summary>

# WTF
## datalad 
  - full_version: 0.13.2
  - version: 0.13.2
## dataset 
  - id: None
  - metadata: <SENSITIVE, report disabled by configuration>
  - path: /mnt/scrap/tmp/abcd/datalad
  - repo: GitRepo
## dependencies 
  - annexremote: 1.4.3
  - appdirs: 1.4.3
  - boto: 2.44.0
  - cmd:7z: 16.02
  - cmd:annex: 7.20190819+git2-g908476a9b-1~ndall+1
  - cmd:bundled-git: 2.20.1
  - cmd:git: 2.20.1
  - cmd:system-git: 2.24.0
  - cmd:system-ssh: 7.9p1
  - exifread: 2.1.2
  - git: 3.0.5
  - gitdb: 2.0.5
  - humanize: 0.5.1
  - iso8601: 0.1.11
  - keyring: 17.1.1
  - keyrings.alt: 3.1.1
  - msgpack: 0.5.6
  - mutagen: 1.40.0
  - requests: 2.21.0
  - tqdm: 4.28.1
  - wrapt: 1.10.11
## environment 
  - GIT_PAGER: less --no-init --quit-if-one-screen
  - LANG: en_US
  - LANGUAGE: en_US:en
  - LC_ADDRESS: en_US.UTF-8
  - LC_COLLATE: en_US.UTF-8
  - LC_CTYPE: en_US.UTF-8
  - LC_IDENTIFICATION: en_US.UTF-8
  - LC_MEASUREMENT: en_US.UTF-8
  - LC_MESSAGES: en_US.UTF-8
  - LC_MONETARY: en_US.UTF-8
  - LC_NAME: en_US.UTF-8
  - LC_NUMERIC: en_US.UTF-8
  - LC_PAPER: en_US.UTF-8
  - LC_TELEPHONE: en_US.UTF-8
  - LC_TIME: en_US.UTF-8
  - PATH: /mnt/scrap/tmp/abcd/datalad/venvs/dev3/bin:/home/yoh/gocode/bin:/home/yoh/gocode/bin:/home/yoh/gocode/bin:/home/yoh/bin:/home/yoh/.local/bin:/usr/local/bin:/usr/bin:/bin:/usr/games:/sbin:/usr/sbin:/usr/local/sbin
## git-annex 
  - build flags: 
    - Assistant
    - Webapp
    - Pairing
    - S3
    - WebDAV
    - Inotify
    - DBus
    - DesktopNotify
    - TorrentParser
    - MagicMime
    - Feeds
    - Testsuite
  - dependency versions: 
    - aws-0.20
    - bloomfilter-2.0.1.0
    - cryptonite-0.25
    - DAV-1.3.3
    - feed-1.0.0.0
    - ghc-8.4.4
    - http-client-0.5.13.1
    - persistent-sqlite-2.8.2
    - torrent-10000.1.1
    - uuid-1.3.13
    - yesod-1.6.0
  - key/value backends: 
    - SHA256E
    - SHA256
    - SHA512E
    - SHA512
    - SHA224E
    - SHA224
    - SHA384E
    - SHA384
    - SHA3_256E
    - SHA3_256
    - SHA3_512E
    - SHA3_512
    - SHA3_224E
    - SHA3_224
    - SHA3_384E
    - SHA3_384
    - SKEIN256E
    - SKEIN256
    - SKEIN512E
    - SKEIN512
    - BLAKE2B256E
    - BLAKE2B256
    - BLAKE2B512E
    - BLAKE2B512
    - BLAKE2B160E
    - BLAKE2B160
    - BLAKE2B224E
    - BLAKE2B224
    - BLAKE2B384E
    - BLAKE2B384
    - BLAKE2BP512E
    - BLAKE2BP512
    - BLAKE2S256E
    - BLAKE2S256
    - BLAKE2S160E
    - BLAKE2S160
    - BLAKE2S224E
    - BLAKE2S224
    - BLAKE2SP256E
    - BLAKE2SP256
    - BLAKE2SP224E
    - BLAKE2SP224
    - SHA1E
    - SHA1
    - MD5E
    - MD5
    - WORM
    - URL
  - operating system: linux x86_64
  - remote types: 
    - git
    - gcrypt
    - p2p
    - S3
    - bup
    - directory
    - rsync
    - web
    - bittorrent
    - webdav
    - adb
    - tahoe
    - glacier
    - ddar
    - git-lfs
    - hook
    - external
  - supported repository versions: 
    - 5
    - 7
  - upgrade supported from repository versions: 
    - 0
    - 1
    - 2
    - 3
    - 4
    - 5
    - 6
  - version: 7.20190819+git2-g908476a9b-1~ndall+1
## location 
  - path: /mnt/scrap/tmp/abcd/datalad
  - type: dataset
## metadata_extractors 
  - annex: 
    - load_error: None
    - module: datalad.metadata.extractors.annex
    - version: None
  - audio: 
    - load_error: None
    - module: datalad.metadata.extractors.audio
    - version: None
  - datacite: 
    - load_error: None
    - module: datalad.metadata.extractors.datacite
    - version: None
  - datalad_core: 
    - load_error: None
    - module: datalad.metadata.extractors.datalad_core
    - version: None
  - datalad_rfc822: 
    - load_error: None
    - module: datalad.metadata.extractors.datalad_rfc822
    - version: None
  - exif: 
    - load_error: None
    - module: datalad.metadata.extractors.exif
    - version: None
  - frictionless_datapackage: 
    - load_error: None
    - module: datalad.metadata.extractors.frictionless_datapackage
    - version: None
  - image: 
    - load_error: None
    - module: datalad.metadata.extractors.image
    - version: None
  - xmp: 
    - load_error: None
    - module: datalad.metadata.extractors.xmp
    - version: None
## python 
  - implementation: CPython
  - version: 3.7.3
## system 
  - distribution: debian/10.0
  - encoding: 
    - default: utf-8
    - filesystem: utf-8
    - locale.prefered: UTF-8
  - max_path_length: 283
  - name: Linux
  - release: 4.19.0-5-amd64
  - type: posix
  - version: #1 SMP Debian 4.19.37-5+deb10u1 (2019-07-19)
</details>
        
I guess next step would be do redo while adding more information to assert and trying a recent git-annex.

**Comment by yarikoptic** [comment]
I believe it is a duplicate of #4854
