### ISSUE TITLE
ConfigManager.get() not aligned with `git config <var>` behavior

### ISSUE THREAD

**Issue by mih** [datalad/datalad#4919]
Problem: A dataset has two (identical) pushurls configured (for no good reason).

```
% cat /ds/hcp/super/HCP1200/108121/MNINonLinear/.git/config 
...
[remote "origin"]
        url = http://store.datalad.org/ceb/604be-2baf-11ea-ae67-002590496000
        fetch = +refs/heads/*:refs/remotes/origin/*
        annex-ignore = true
        pushurl = falkor.dartmouth.edu:/srv/store.datalad.org/www/ceb/604be-2baf-11ea-ae67-002590496000
        pushurl = falkor.dartmouth.edu:/srv/store.datalad.org/www/ceb/604be-2baf-11ea-ae67-002590496000
...
```

However, Git is unimpaired by that, because it reports the last values by default, whereas our `get()` always reports all values:

```
% git -C /ds/hcp/super/HCP1200/108121/MNINonLinear config remote.origin.pushurl 
falkor.dartmouth.edu:/srv/store.datalad.org/www/ceb/604be-2baf-11ea-ae67-002590496000
```

I cannot show that, because it crashes DataLad:

```
% python -c 'from datalad.api import Dataset; Dataset("/ds/hcp/super/HCP1200/108121/MNINonLinear").config'
Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "/home/mih/code/datalad/datalad/distribution/dataset.py", line 343, in config
    repo = self.repo
  File "/home/mih/code/datalad/datalad/distribution/dataset.py", line 289, in repo
    self._repo = repo_from_path(self._path)
  File "/home/mih/code/datalad/datalad/core/local/repo.py", line 61, in repo_from_path
    repo = cls(path, create=False, **kw)
  File "/home/mih/code/datalad/datalad/support/repo.py", line 151, in __call__
    instance = type.__call__(cls, *new_args, **new_kwargs)
  File "/home/mih/code/datalad/datalad/support/annexrepo.py", line 260, in __init__
    self._set_shared_connection(r, url)
  File "/home/mih/code/datalad/datalad/support/annexrepo.py", line 428, in _set_shared_connection
    if is_ssh(url):
  File "/home/mih/code/datalad/datalad/support/network.py", line 923, in is_ssh
    _ri = RI(ri) if not isinstance(ri, RI) else ri
  File "/home/mih/code/datalad/datalad/support/network.py", line 419, in __new__
    cls = _guess_ri_cls(ri)
  File "/home/mih/code/datalad/datalad/support/network.py", line 329, in _guess_ri_cls
    if is_windows_path(ri):
  File "/home/mih/code/datalad/datalad/support/network.py", line 72, in is_windows_path
    win_split = win_splitdrive(path)
  File "/home/mih/venvs/datalad/lib/python3.7/ntpath.py", line 141, in splitdrive
    p = os.fspath(p)
TypeError: expected str, bytes or os.PathLike object, not tuple
```

`not tuple` is because both values are reported in a tuple.

Investigating why SSH-related code needs to run in this context is another side issue that like also has performance impact.

I think `ConfigManager` should offer a way to make client-code not worry about single or multiple values coming out, when only a single one is expected and only a single one can be handled.

**Comment by kyleam** [comment]
> I think `ConfigManager` should offer a way to make client-code not worry about single or multiple values coming out, when only a single one is expected and only a single one can be handled.

I agree.

Related:

  * https://github.com/datalad/datalad/pull/2905#discussion_r224834963
  * gh-2628
