### ISSUE TITLE
test_get_flexible_source_candidates_for_submodule test failing on conda

### ISSUE THREAD

**Issue by yarikoptic** [datalad/datalad#4932]
linux_64_nodepTrue downstream testing of git annex build of datalad 0.13.3 fails on conda-forge https://github.com/conda-forge/git-annex-feedstock/pull/101 in test_get.test_get_flexible_source_candidates_for_submodule:

```
2020-09-18T03:50:48.4226470Z ======================================================================
2020-09-18T03:50:48.4226924Z FAIL: datalad.distribution.tests.test_get.test_get_flexible_source_candidates_for_submodule
2020-09-18T03:50:48.4227600Z ----------------------------------------------------------------------
2020-09-18T03:50:48.4228004Z Traceback (most recent call last):
2020-09-18T03:50:48.4229198Z   File "/home/conda/feedstock_root/build_artifacts/git-annex_1600392873041/_test_env_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placeh/lib/python3.8/site-packages/nose/case.py", line 197, in runTest
2020-09-18T03:50:48.4229994Z     self.test(*self.arg)
2020-09-18T03:50:48.4231200Z   File "/home/conda/feedstock_root/build_artifacts/git-annex_1600392873041/_test_env_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placeh/lib/python3.8/site-packages/datalad/tests/utils.py", line 731, in _wrap_with_tempfile
2020-09-18T03:50:48.4232066Z     return t(*(arg + (filename,)), **kw)
2020-09-18T03:50:48.4233310Z   File "/home/conda/feedstock_root/build_artifacts/git-annex_1600392873041/_test_env_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placeh/lib/python3.8/site-packages/datalad/tests/utils.py", line 731, in _wrap_with_tempfile
2020-09-18T03:50:48.4235528Z     return t(*(arg + (filename,)), **kw)
2020-09-18T03:50:48.4236850Z   File "/home/conda/feedstock_root/build_artifacts/git-annex_1600392873041/_test_env_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placeh/lib/python3.8/site-packages/datalad/tests/utils.py", line 731, in _wrap_with_tempfile
2020-09-18T03:50:48.4237697Z     return t(*(arg + (filename,)), **kw)
2020-09-18T03:50:48.4239042Z   File "/home/conda/feedstock_root/build_artifacts/git-annex_1600392873041/_test_env_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placeh/lib/python3.8/site-packages/datalad/distribution/tests/test_get.py", line 145, in test_get_flexible_source_candidates_for_submodule
2020-09-18T03:50:48.4240270Z     eq_(f(clone, clone.subdatasets(return_type='item-or-list')),
2020-09-18T03:50:48.4242284Z AssertionError: [{'cost': 400, 'name': 'bang', 'url': 'youredead', 'from_config': True}, {'cost': 500, 'name': 'origin', 'url': '/tmp/datalad_temp_test_get_flexible_source_candidates_for_submoduleso013kl9/sub'}, {'cost': 700, 'name': 'bang', 'url': 'pre-a2f21833-32ac-4372-b0dc-5577a931b4a3-post', 'from_config': True}] != [{'cost': 500, 'name': 'origin', 'url': '/tmp/datalad_temp_test_get_flexible_source_candidates_for_submoduleso013kl9/sub'}, {'cost': 700, 'name': 'bang', 'url': 'pre-a2f21833-32ac-4372-b0dc-5577a931b4a3-post', 'from_config': True}]
2020-09-18T03:50:48.4244024Z -------------------- >> begin captured logging << --------------------
2020-09-18T03:50:48.4244489Z asyncio: DEBUG: Using selector: EpollSelector
2020-09-18T03:50:48.4245078Z asyncio: DEBUG: Using selector: EpollSelector
2020-09-18T03:50:48.4245495Z asyncio: DEBUG: Using selector: EpollSelector
2020-09-18T03:50:48.4245904Z asyncio: DEBUG: Using selector: EpollSelector
2020-09-18T03:50:48.4246316Z asyncio: DEBUG: Using selector: EpollSelector
2020-09-18T03:50:48.4246824Z asyncio: DEBUG: Using selector: EpollSelector
2020-09-18T03:50:48.4247311Z asyncio: DEBUG: Using selector: EpollSelector
2020-09-18T03:50:48.4247730Z asyncio: DEBUG: Using selector: EpollSelector
2020-09-18T03:50:48.4248382Z --------------------- >> end captured logging << ---------------------
2020-09-18T03:50:48.4248742Z
2020-09-18T03:50:48.4249296Z ----------------------------------------------------------------------
```
i don't think we saw this one yet

**Comment by yarikoptic** [comment]
happened on windows too : #5125

**Comment by yarikoptic** [comment]
<details>
<summary>reproduced on windows as  being specific to having DATALAD_REPO_VERSION=6 -- so is something about autoupgrade?</summary> 

```shell
DataLad@DESKTOP-1FTT289 MINGW64 ~/PycharmProjects/datalad (enh-appveyor)
$ DATALAD_REPO_VERSION=6 python -m nose -s -v --traverse-namespace datalad/distribution/tests/test_get.py:test_get_flexible_source_candidates_for_submodule
datalad.distribution.tests.test_get.test_get_flexible_source_candidates_for_submodule ... Versions: annexremote=1.2.1 appdirs=1.4.4 boto=2.49.0 cmd:7z=19.00 cmd:annex=8.20201008-g7e24b2587 cmd:bundled-git=UNKNOWN cmd:git=2.29.0.windows.1 cmd:system-git=2.29.0.windows.1 cmd:system-ssh=8.4p1 exifread=2.1.2 humanize=3.1.0 iso8601=0.1.13 keyring=21.4.0 keyrings.alt=3.1 msgpack=1.0.0 mutagen=1.41.1 requests=2.24.0 tqdm=4.51.0 wrapt=1.12.1
Obscure filename: str=b";&%b5{}'.datc" repr=";&%b5{}'.datc"
Encodings: default='utf-8' filesystem='utf-8' locale.prefered='cp1252'
Environment: LANG='en_US.UTF-8' PATH='C:\\Users\\DataLad\\miniconda3\\envs\\datalad-3;C:\\Users\\DataLad\\miniconda3\\envs\\datalad-3\\Library\\mingw-w64\\bin;C:\\Users\\DataLad\\miniconda3\\envs\\datalad-3\\Library\\usr\\bin;C:\\Users\\DataLad\\miniconda3\\envs\\datalad-3\\Library\\bin;C:\\Users\\DataLad\\miniconda3\\envs\\datalad-3\\Scripts;C:\\Users\\DataLad\\miniconda3\\envs\\datalad-3\\bin;C:\\Users\\DataLad\\miniconda3\\Scripts\\condabin;C:\\Users\\DataLad\\bin;C:\\Program Files\\Git\\mingw64\\bin;C:\\Program Files\\Git\\usr\\local\\bin;C:\\Program Files\\Git\\usr\\bin;C:\\Program Files\\Git\\usr\\bin;C:\\Program Files\\Git\\mingw64\\bin;C:\\Program Files\\Git\\usr\\bin;C:\\Users\\DataLad\\bin;C:\\Windows\\system32;C:\\Windows;C:\\Windows\\System32\\Wbem;C:\\Windows\\System32\\WindowsPowerShell\\v1.0;C:\\Windows\\System32\\OpenSSH;C:\\Program Files\\Git\\cmd;C:\\Users\\DataLad\\AppData\\Local\\Microsoft\\WindowsApps;C:\\Program Files\\Git\\usr\\bin\\vendor_perl;C:\\Program Files\\Git\\usr\\bin\\core_perl' GIT_CONFIG_PARAMETERS="'init.defaultBranch=dl-test-branch'"
FAIL

======================================================================
FAIL: datalad.distribution.tests.test_get.test_get_flexible_source_candidates_for_submodule
----------------------------------------------------------------------
Traceback (most recent call last):
  File "C:\Users\DataLad\miniconda3\envs\datalad-3\lib\site-packages\nose\case.py", line 197, in runTest
    self.test(*self.arg)
  File "C:\Users\DataLad\PycharmProjects\datalad\datalad\tests\utils.py", line 750, in _wrap_with_tempfile
    return t(*(arg + (filename,)), **kw)
  File "C:\Users\DataLad\PycharmProjects\datalad\datalad\tests\utils.py", line 750, in _wrap_with_tempfile
    return t(*(arg + (filename,)), **kw)
  File "C:\Users\DataLad\PycharmProjects\datalad\datalad\tests\utils.py", line 750, in _wrap_with_tempfile
    return t(*(arg + (filename,)), **kw)
  File "C:\Users\DataLad\PycharmProjects\datalad\datalad\distribution\tests\test_get.py", line 145, in test_get_flexible_source_candidates_for_submodule
    eq_(f(clone, clone.subdatasets(return_type='item-or-list')),
AssertionError: [{'cost': 400, 'name': 'bang', 'url': 'youredead', 'from_config': True}, {'cost': 500, 'name': 'origin', 'url': 'C:\\Users\\DataLad\\AppData\\Local\\Temp\\datalad_temp_f7au3xs3\\sub'}, {'cost': 700, 'name': 'bang', 'url': 'pre-140200d6-0c5d-4eb6-a451-d549b8c5e477-post', 'from_config': True}] != [{'cost': 500, 'name': 'origin', 'url': 'C:\\Users\\DataLad\\AppData\\Local\\Temp\\datalad_temp_f7au3xs3\\sub'}, {'cost': 700, 'name': 'bang', 'url': 'pre-140200d6-0c5d-4eb6-a451-d549b8c5e477-post', 'from_config': True}]
-------------------- >> begin captured logging << --------------------
datalad.utils: Level 5: Importing datalad.utils
datalad.utils: DEBUG: Failed to query or got useless SC_ARG_MAX sysconf, will use hardcoded value: module 'os' has no attribute 'sysconf'
datalad.utils: DEBUG: Maximal length of cmdline string (adjusted for safety margin): 16383
datalad.utils: Level 5: Done importing datalad.utils
datalad.cmd: Level 9: Will use git under '' (no adjustments to PATH if empty string)
datalad.cmd: Level 5: Running: ['git', 'version']
datalad.cmd: Level 8: Finished running ['git', 'version'] with status 0
datalad.cmd: Level 5: Running: ['git', '--git-dir=', 'config', '-z', '-l', '--show-origin']
datalad.cmd: Level 8: Finished running ['git', '--git-dir=', 'config', '-z', '-l', '--show-origin'] with status 0
datalad.ui: Level 5: Starting importing ui
datalad.ui.dialog: Level 5: Starting importing ui.dialog
datalad.ui.dialog: Level 5: Done importing ui.dialog
datalad.ui: Level 5: Initiating UI switcher
datalad.ui: DEBUG: UI set to SilentConsoleLog(out=<StreamWrapper>)
datalad.ui: Level 5: Done importing ui
asyncio: DEBUG: Using proactor: IocpProactor
asyncio: DEBUG: Using proactor: IocpProactor
asyncio: DEBUG: Using proactor: IocpProactor
asyncio: DEBUG: Using proactor: IocpProactor
asyncio: DEBUG: Using proactor: IocpProactor
asyncio: DEBUG: Using proactor: IocpProactor
asyncio: DEBUG: Using proactor: IocpProactor
asyncio: DEBUG: Using proactor: IocpProactor
--------------------- >> end captured logging << ---------------------

----------------------------------------------------------------------
Ran 1 test in 16.625s

FAILED (failures=1)
(datalad-3)
```
</details>

**Comment by yarikoptic** [comment]
oh fun -- the test passed when I prepended `DATALAD_LOG_LEVEL=2 DATALAD_LOG_OUTPUTS=1 ` - so might be some race somewhere slowed down by logging

**Comment by yarikoptic** [comment]
it is a flaky one indeed. It seems to fail with INFO level logging, with WARNING level it does spit out a warning (why not on INFO?) and some times fails some times not

<details>
<summary>details</summary> 

```shell
$ DATALAD_LOG_LEVEL=INFO DATALAD_REPO_VERSION=6 python -m nose -s -v --traverse-namespace datalad/distribution/tests/test_get.py:test_get_flexible_source_candidates_for_submodule
datalad.distribution.tests.test_get.test_get_flexible_source_candidates_for_submodule ... [INFO] Creating a new annex repo at C:\Users\DataLad\AppData\Local\Temp\datalad_temp_2jlohkoa
[INFO] Detected a filesystem without fifo support.
[INFO] Disabling ssh connection caching.
[INFO] Detected a crippled filesystem.
[INFO] Scanning for unlocked files (this may take some time)
[INFO] Entering an adjusted branch where files are unlocked as this filesystem does not support locked files.
[INFO] Switched to branch 'adjusted/dl-test-branch(unlocked)'
[INFO] Creating a new annex repo at C:\Users\DataLad\AppData\Local\Temp\datalad_temp_2jlohkoa\sub
[INFO] Detected a filesystem without fifo support.
[INFO] Disabling ssh connection caching.
[INFO] Detected a crippled filesystem.
[INFO] Scanning for unlocked files (this may take some time)
[INFO] Entering an adjusted branch where files are unlocked as this filesystem does not support locked files.
[INFO] Switched to branch 'adjusted/dl-test-branch(unlocked)'
[INFO] Cloning dataset to Dataset("C:\Users\DataLad\AppData\Local\Temp\datalad_temp_ezv80n21")
[INFO] Attempting to clone from C:\Users\DataLad\AppData\Local\Temp\datalad_temp_2jlohkoa to C:\Users\DataLad\AppData\Local\Temp\datalad_temp_ezv80n21
[INFO] Completed clone attempts for Dataset("C:\Users\DataLad\AppData\Local\Temp\datalad_temp_ezv80n21")
[INFO] Detected a filesystem without fifo support.
[INFO] Disabling ssh connection caching.
[INFO] Detected a crippled filesystem.
[INFO] Scanning for unlocked files (this may take some time)
[INFO] Could not enable annex remote myremote. This is expected if myremote is a pure Git remote, or happens if it is not accessible.
[WARNING] Could not detect whether myremote carries an annex. If myremote is a pure Git remote, this is expected. Remote was marked by annex as annex-ignore. Edit .git/config to reset if you think that was done by mistake due to absent connection etc
[INFO] Cloning dataset to Dataset("C:\Users\DataLad\AppData\Local\Temp\datalad_temp_7edx27zf")
[INFO] Attempting to clone from C:\Users\DataLad\AppData\Local\Temp\datalad_temp_ezv80n21 to C:\Users\DataLad\AppData\Local\Temp\datalad_temp_7edx27zf
[INFO] Completed clone attempts for Dataset("C:\Users\DataLad\AppData\Local\Temp\datalad_temp_7edx27zf")
[INFO] Detected a filesystem without fifo support.
[INFO] Disabling ssh connection caching.
[INFO] Detected a crippled filesystem.
[INFO] Scanning for unlocked files (this may take some time)
[INFO] Fetching updates for Dataset("C:\Users\DataLad\AppData\Local\Temp\datalad_temp_7edx27zf")
[INFO] Fetching updates for Dataset("C:\Users\DataLad\AppData\Local\Temp\datalad_temp_7edx27zf")
Versions: annexremote=1.2.1 appdirs=1.4.4 boto=2.49.0 cmd:7z=19.00 cmd:annex=8.20201008-g7e24b2587 cmd:bundled-git=UNKNOWN cmd:git=2.29.0.windows.1 cmd:system-git=2.29.0.windows.1 cmd:system-ssh=8.4p1 exifread=2.1.2 humanize=3.1.0 iso8601=0.1.13 keyring=21.4.0 keyrings.alt=3.1 msgpack=1.0.0 mutagen=1.41.1 requests=2.24.0 tqdm=4.51.0 wrapt=1.12.1
Obscure filename: str=b";&%b5{}'.datc" repr=";&%b5{}'.datc"
Encodings: default='utf-8' filesystem='utf-8' locale.prefered='cp1252'
Environment: LANG='en_US.UTF-8' PATH='C:\\Users\\DataLad\\miniconda3\\envs\\datalad-3;C:\\Users\\DataLad\\miniconda3\\envs\\datalad-3\\Library\\mingw-w64\\bin;C:\\Users\\DataLad\\miniconda3\\envs\\datalad-3\\Library\\usr\\bin;C:\\Users\\DataLad\\miniconda3\\envs\\datalad-3\\Library\\bin;C:\\Users\\DataLad\\miniconda3\\envs\\datalad-3\\Scripts;C:\\Users\\DataLad\\miniconda3\\envs\\datalad-3\\bin;C:\\Users\\DataLad\\miniconda3\\Scripts\\condabin;C:\\Users\\DataLad\\bin;C:\\Program Files\\Git\\mingw64\\bin;C:\\Program Files\\Git\\usr\\local\\bin;C:\\Program Files\\Git\\usr\\bin;C:\\Program Files\\Git\\usr\\bin;C:\\Program Files\\Git\\mingw64\\bin;C:\\Program Files\\Git\\usr\\bin;C:\\Users\\DataLad\\bin;C:\\Windows\\system32;C:\\Windows;C:\\Windows\\System32\\Wbem;C:\\Windows\\System32\\WindowsPowerShell\\v1.0;C:\\Windows\\System32\\OpenSSH;C:\\Program Files\\Git\\cmd;C:\\Users\\DataLad\\AppData\\Local\\Microsoft\\WindowsApps;C:\\Program Files\\Git\\usr\\bin\\vendor_perl;C:\\Program Files\\Git\\usr\\bin\\core_perl' GIT_CONFIG_PARAMETERS="'init.defaultBranch=dl-test-branch'"
ok

----------------------------------------------------------------------
Ran 1 test in 23.062s

OK
(datalad-3)
DataLad@DESKTOP-1FTT289 MINGW64 ~/PycharmProjects/datalad (enh-appveyor)
$ DATALAD_LOG_LEVEL=WARNING DATALAD_REPO_VERSION=6 python -m nose -s -v --traverse-namespace datalad/distribution/tests/test_get.py:test_get_flexible_source_candidates_for_submodule
datalad.distribution.tests.test_get.test_get_flexible_source_candidates_for_submodule ... [WARNING] Could not detect whether myremote carries an annex. If myremote is a pure Git remote, this is expected. Remote was marked by annex as annex-ignore. Edit .git/config to reset if you think that was done by mistake due to absent connection etc
Versions: annexremote=1.2.1 appdirs=1.4.4 boto=2.49.0 cmd:7z=19.00 cmd:annex=8.20201008-g7e24b2587 cmd:bundled-git=UNKNOWN cmd:git=2.29.0.windows.1 cmd:system-git=2.29.0.windows.1 cmd:system-ssh=8.4p1 exifread=2.1.2 humanize=3.1.0 iso8601=0.1.13 keyring=21.4.0 keyrings.alt=3.1 msgpack=1.0.0 mutagen=1.41.1 requests=2.24.0 tqdm=4.51.0 wrapt=1.12.1
Obscure filename: str=b";&%b5{}'.datc" repr=";&%b5{}'.datc"
Encodings: default='utf-8' filesystem='utf-8' locale.prefered='cp1252'
Environment: LANG='en_US.UTF-8' PATH='C:\\Users\\DataLad\\miniconda3\\envs\\datalad-3;C:\\Users\\DataLad\\miniconda3\\envs\\datalad-3\\Library\\mingw-w64\\bin;C:\\Users\\DataLad\\miniconda3\\envs\\datalad-3\\Library\\usr\\bin;C:\\Users\\DataLad\\miniconda3\\envs\\datalad-3\\Library\\bin;C:\\Users\\DataLad\\miniconda3\\envs\\datalad-3\\Scripts;C:\\Users\\DataLad\\miniconda3\\envs\\datalad-3\\bin;C:\\Users\\DataLad\\miniconda3\\Scripts\\condabin;C:\\Users\\DataLad\\bin;C:\\Program Files\\Git\\mingw64\\bin;C:\\Program Files\\Git\\usr\\local\\bin;C:\\Program Files\\Git\\usr\\bin;C:\\Program Files\\Git\\usr\\bin;C:\\Program Files\\Git\\mingw64\\bin;C:\\Program Files\\Git\\usr\\bin;C:\\Users\\DataLad\\bin;C:\\Windows\\system32;C:\\Windows;C:\\Windows\\System32\\Wbem;C:\\Windows\\System32\\WindowsPowerShell\\v1.0;C:\\Windows\\System32\\OpenSSH;C:\\Program Files\\Git\\cmd;C:\\Users\\DataLad\\AppData\\Local\\Microsoft\\WindowsApps;C:\\Program Files\\Git\\usr\\bin\\vendor_perl;C:\\Program Files\\Git\\usr\\bin\\core_perl' GIT_CONFIG_PARAMETERS="'init.defaultBranch=dl-test-branch'"
FAIL

======================================================================
FAIL: datalad.distribution.tests.test_get.test_get_flexible_source_candidates_for_submodule
----------------------------------------------------------------------
Traceback (most recent call last):
  File "C:\Users\DataLad\miniconda3\envs\datalad-3\lib\site-packages\nose\case.py", line 197, in runTest
    self.test(*self.arg)
  File "C:\Users\DataLad\PycharmProjects\datalad\datalad\tests\utils.py", line 750, in _wrap_with_tempfile
    return t(*(arg + (filename,)), **kw)
  File "C:\Users\DataLad\PycharmProjects\datalad\datalad\tests\utils.py", line 750, in _wrap_with_tempfile
    return t(*(arg + (filename,)), **kw)
  File "C:\Users\DataLad\PycharmProjects\datalad\datalad\tests\utils.py", line 750, in _wrap_with_tempfile
    return t(*(arg + (filename,)), **kw)
  File "C:\Users\DataLad\PycharmProjects\datalad\datalad\distribution\tests\test_get.py", line 145, in test_get_flexible_source_candidates_for_submodule
    eq_(f(clone, clone.subdatasets(return_type='item-or-list')),
AssertionError: [{'cost': 400, 'name': 'bang', 'url': 'youredead', 'from_config': True}, {'cost': 500, 'name': 'origin', 'url': 'C:\\Users\\DataLad\\AppData\\Local\\Temp\\datalad_temp_n53vu1n4\\sub'}, {'cost': 700, 'name': 'bang', 'url': 'pre-11f3344a-631e-4f53-b4d2-e0d3c4c3251f-post', 'from_config': True}] != [{'cost': 500, 'name': 'origin', 'url': 'C:\\Users\\DataLad\\AppData\\Local\\Temp\\datalad_temp_n53vu1n4\\sub'}, {'cost': 700, 'name': 'bang', 'url': 'pre-11f3344a-631e-4f53-b4d2-e0d3c4c3251f-post', 'from_config': True}]
-------------------- >> begin captured logging << --------------------
datalad.utils: Level 5: Importing datalad.utils
datalad.utils: DEBUG: Failed to query or got useless SC_ARG_MAX sysconf, will use hardcoded value: module 'os' has no attribute 'sysconf'
datalad.utils: DEBUG: Maximal length of cmdline string (adjusted for safety margin): 16383
datalad.utils: Level 5: Done importing datalad.utils
datalad.cmd: Level 9: Will use git under '' (no adjustments to PATH if empty string)
datalad.cmd: Level 5: Running: ['git', 'version']
datalad.cmd: Level 8: Finished running ['git', 'version'] with status 0
datalad.cmd: Level 5: Running: ['git', '--git-dir=', 'config', '-z', '-l', '--show-origin']
datalad.cmd: Level 8: Finished running ['git', '--git-dir=', 'config', '-z', '-l', '--show-origin'] with status 0
datalad.ui: Level 5: Starting importing ui
datalad.ui.dialog: Level 5: Starting importing ui.dialog
datalad.ui.dialog: Level 5: Done importing ui.dialog
datalad.ui: Level 5: Initiating UI switcher
datalad.ui: DEBUG: UI set to SilentConsoleLog(out=<StreamWrapper>)
datalad.ui: Level 5: Done importing ui
asyncio: DEBUG: Using proactor: IocpProactor
asyncio: DEBUG: Using proactor: IocpProactor
asyncio: DEBUG: Using proactor: IocpProactor
asyncio: DEBUG: Using proactor: IocpProactor
asyncio: DEBUG: Using proactor: IocpProactor
asyncio: DEBUG: Using proactor: IocpProactor
asyncio: DEBUG: Using proactor: IocpProactor
asyncio: DEBUG: Using proactor: IocpProactor
datalad.distribution.siblings: WARNING: Could not detect whether myremote carries an annex. If myremote is a pure Git remote, this is expected. Remote was marked by annex as annex-ignore. Edit .git/config to reset if you think that was done by mistake due to absent connection etc
--------------------- >> end captured logging << ---------------------

----------------------------------------------------------------------
Ran 1 test in 17.061s

FAILED (failures=1)
(datalad-3)
DataLad@DESKTOP-1FTT289 MINGW64 ~/PycharmProjects/datalad (enh-appveyor)
$ DATALAD_LOG_LEVEL=WARNING DATALAD_REPO_VERSION=6 python -m nose -s -v --traverse-namespace datalad/distribution/tests/test_get.py:test_get_flexible_source_candidates_for_submodule
datalad.distribution.tests.test_get.test_get_flexible_source_candidates_for_submodule ... [WARNING] Could not detect whether myremote carries an annex. If myremote is a pure Git remote, this is expected. Remote was marked by annex as annex-ignore. Edit .git/config to reset if you think that was done by mistake due to absent connection etc
Versions: annexremote=1.2.1 appdirs=1.4.4 boto=2.49.0 cmd:7z=19.00 cmd:annex=8.20201008-g7e24b2587 cmd:bundled-git=UNKNOWN cmd:git=2.29.0.windows.1 cmd:system-git=2.29.0.windows.1 cmd:system-ssh=8.4p1 exifread=2.1.2 humanize=3.1.0 iso8601=0.1.13 keyring=21.4.0 keyrings.alt=3.1 msgpack=1.0.0 mutagen=1.41.1 requests=2.24.0 tqdm=4.51.0 wrapt=1.12.1
Obscure filename: str=b";&%b5{}'.datc" repr=";&%b5{}'.datc"
Encodings: default='utf-8' filesystem='utf-8' locale.prefered='cp1252'
Environment: LANG='en_US.UTF-8' PATH='C:\\Users\\DataLad\\miniconda3\\envs\\datalad-3;C:\\Users\\DataLad\\miniconda3\\envs\\datalad-3\\Library\\mingw-w64\\bin;C:\\Users\\DataLad\\miniconda3\\envs\\datalad-3\\Library\\usr\\bin;C:\\Users\\DataLad\\miniconda3\\envs\\datalad-3\\Library\\bin;C:\\Users\\DataLad\\miniconda3\\envs\\datalad-3\\Scripts;C:\\Users\\DataLad\\miniconda3\\envs\\datalad-3\\bin;C:\\Users\\DataLad\\miniconda3\\Scripts\\condabin;C:\\Users\\DataLad\\bin;C:\\Program Files\\Git\\mingw64\\bin;C:\\Program Files\\Git\\usr\\local\\bin;C:\\Program Files\\Git\\usr\\bin;C:\\Program Files\\Git\\usr\\bin;C:\\Program Files\\Git\\mingw64\\bin;C:\\Program Files\\Git\\usr\\bin;C:\\Users\\DataLad\\bin;C:\\Windows\\system32;C:\\Windows;C:\\Windows\\System32\\Wbem;C:\\Windows\\System32\\WindowsPowerShell\\v1.0;C:\\Windows\\System32\\OpenSSH;C:\\Program Files\\Git\\cmd;C:\\Users\\DataLad\\AppData\\Local\\Microsoft\\WindowsApps;C:\\Program Files\\Git\\usr\\bin\\vendor_perl;C:\\Program Files\\Git\\usr\\bin\\core_perl' GIT_CONFIG_PARAMETERS="'init.defaultBranch=dl-test-branch'"
ok

----------------------------------------------------------------------
Ran 1 test in 18.125s

OK
(datalad-3)

```
</details>

**Comment by mih** [comment]
I will look into this. It better not fail.

**Comment by mih** [comment]
I have no seen any such failure in several weeks. I have no idea what the cause was, but until we see it again, I think this is save to close.
