### ISSUE TITLE
2 datalad-archives tests fail on conda

### ISSUE THREAD

**Issue by yarikoptic** [datalad/datalad#4933]
linux_64_nodepTrue downstream testing of git annex build of datalad 0.13.3 fails on conda-forge https://github.com/conda-forge/git-annex-feedstock/pull/101 leads to two datalad-archives remote related tests:

```
2020-09-18T03:50:48.4181911Z ======================================================================
2020-09-18T03:50:48.4182393Z ERROR: datalad.customremotes.tests.test_archives.test_annex_get_from_subdir
2020-09-18T03:50:48.4183170Z ----------------------------------------------------------------------
2020-09-18T03:50:48.4183612Z Traceback (most recent call last):
2020-09-18T03:50:48.4184924Z   File "/home/conda/feedstock_root/build_artifacts/git-annex_1600392873041/_test_env_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placeh/lib/python3.8/site-packages/nose/case.py", line 197, in runTest
2020-09-18T03:50:48.4185885Z     self.test(*self.arg)
2020-09-18T03:50:48.4187203Z   File "/home/conda/feedstock_root/build_artifacts/git-annex_1600392873041/_test_env_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placeh/lib/python3.8/site-packages/datalad/tests/utils.py", line 554, in _wrap_with_tree
2020-09-18T03:50:48.4188120Z     return t(*(arg + (d,)), **kw)
2020-09-18T03:50:48.4189536Z   File "/home/conda/feedstock_root/build_artifacts/git-annex_1600392873041/_test_env_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placeh/lib/python3.8/site-packages/datalad/customremotes/tests/test_archives.py", line 178, in test_annex_get_from_subdir
2020-09-18T03:50:48.4190841Z     runner(['git', 'annex', 'get', '--', fn_in_archive_obscure])   # run git annex get
2020-09-18T03:50:48.4192225Z   File "/home/conda/feedstock_root/build_artifacts/git-annex_1600392873041/_test_env_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placeh/lib/python3.8/site-packages/datalad/cmd.py", line 599, in __call__
2020-09-18T03:50:48.4193116Z     return self.run(cmd, *args, **kwargs)
2020-09-18T03:50:48.4194418Z   File "/home/conda/feedstock_root/build_artifacts/git-annex_1600392873041/_test_env_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placeh/lib/python3.8/site-packages/datalad/cmd.py", line 961, in run
2020-09-18T03:50:48.4195255Z     raise exc
2020-09-18T03:50:48.4196205Z datalad.support.exceptions.CommandError: CommandError: 'git annex get -- ' "'"'"';a&b&cΔЙקﻡ๗あ `| '' failed with exitcode 1 [out: 'get  "';a&b&cΔЙקﻡ๗あ `|  (from datalad-archives...)
2020-09-18T03:50:48.4196862Z
2020-09-18T03:50:48.4197076Z
2020-09-18T03:50:48.4197609Z   Unable to access these remotes: datalad-archives
2020-09-18T03:50:48.4197958Z
2020-09-18T03:50:48.4198297Z   Try making some of these repositories available:
2020-09-18T03:50:48.4198967Z    c04eb54b-4b4e-5755-8436-866b043170fa -- [datalad-archives]
2020-09-18T03:50:48.4200450Z failed'] [err: 'Failed to fetch any archive containing SHA256E-s3--a665a45920422f9d417e4867efdc4fb8a04a1f3fff1fa07e998e86f7f7a27ae3. Tried: ['SHA256E-s166--44e4c670086709cf7aadd3a7618ca77f5f1d5934305a3e792cf671e7bbe1d20b.tar.gz'] [archives.py:_transfer:405]
2020-09-18T03:50:48.4201611Z git-annex: get: 1 failed']
2020-09-18T03:50:48.4202260Z -------------------- >> begin captured logging << --------------------
2020-09-18T03:50:48.4202718Z asyncio: DEBUG: Using selector: EpollSelector
2020-09-18T03:50:48.4203409Z asyncio: DEBUG: Using selector: EpollSelector
2020-09-18T03:50:48.4204670Z asyncio: DEBUG: Using selector: EpollSelector
2020-09-18T03:50:48.4205176Z asyncio: DEBUG: Using selector: EpollSelector
2020-09-18T03:50:48.4205605Z asyncio: DEBUG: Using selector: EpollSelector
2020-09-18T03:50:48.4206694Z fasteners.process_lock: Level 5: Acquired file lock `/tmp/datalad_temp_tree_test_annex_get_from_subdirxu27uco6/.git/datalad/tmp/archives/69dc725608.extract-lck` after waiting 0.000s [1 attempts were required]
2020-09-18T03:50:48.4207955Z fasteners.process_lock: Level 5: Unlocked and closed file lock open on `/tmp/datalad_temp_tree_test_annex_get_from_subdirxu27uco6/.git/datalad/tmp/archives/69dc725608.extract-lck`
2020-09-18T03:50:48.4208632Z asyncio: DEBUG: Using selector: EpollSelector
2020-09-18T03:50:48.4209036Z asyncio: DEBUG: Using selector: EpollSelector
2020-09-18T03:50:48.4209688Z --------------------- >> end captured logging << ---------------------
```

```
2020-09-18T03:50:48.4210377Z ======================================================================
2020-09-18T03:50:48.4210847Z FAIL: datalad.customremotes.tests.test_archives.test_basic_scenario
2020-09-18T03:50:48.4211510Z ----------------------------------------------------------------------
2020-09-18T03:50:48.4211960Z Traceback (most recent call last):
2020-09-18T03:50:48.4213242Z   File "/home/conda/feedstock_root/build_artifacts/git-annex_1600392873041/_test_env_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placeh/lib/python3.8/site-packages/nose/case.py", line 197, in runTest
2020-09-18T03:50:48.4214109Z     self.test(*self.arg)
2020-09-18T03:50:48.4215432Z   File "/home/conda/feedstock_root/build_artifacts/git-annex_1600392873041/_test_env_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placeh/lib/python3.8/site-packages/datalad/tests/utils.py", line 554, in _wrap_with_tree
2020-09-18T03:50:48.4216318Z     return t(*(arg + (d,)), **kw)
2020-09-18T03:50:48.4217634Z   File "/home/conda/feedstock_root/build_artifacts/git-annex_1600392873041/_test_env_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placeh/lib/python3.8/site-packages/datalad/tests/utils.py", line 731, in _wrap_with_tempfile
2020-09-18T03:50:48.4218554Z     return t(*(arg + (filename,)), **kw)
2020-09-18T03:50:48.4219966Z   File "/home/conda/feedstock_root/build_artifacts/git-annex_1600392873041/_test_env_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placeh/lib/python3.8/site-packages/datalad/customremotes/tests/test_archives.py", line 124, in test_basic_scenario
2020-09-18T03:50:48.4220955Z     assert_true(annex.file_has_content(fn_extracted))
2020-09-18T03:50:48.4221338Z AssertionError: False is not true
2020-09-18T03:50:48.4221966Z -------------------- >> begin captured logging << --------------------
2020-09-18T03:50:48.4222420Z asyncio: DEBUG: Using selector: EpollSelector
2020-09-18T03:50:48.4222824Z asyncio: DEBUG: Using selector: EpollSelector
2020-09-18T03:50:48.4223240Z asyncio: DEBUG: Using selector: EpollSelector
2020-09-18T03:50:48.4223735Z asyncio: DEBUG: Using selector: EpollSelector
2020-09-18T03:50:48.4224154Z asyncio: DEBUG: Using selector: EpollSelector
2020-09-18T03:50:48.4224625Z asyncio: DEBUG: Using selector: EpollSelector
2020-09-18T03:50:48.4225039Z asyncio: DEBUG: Using selector: EpollSelector
2020-09-18T03:50:48.4225825Z --------------------- >> end captured logging << ---------------------
```

**Comment by kyleam** [comment]
Both of these failures were reported in gh-5203, and things were green by the end, so I think it's safe to close this.  Please reopen if I'm mistaken.
