### ISSUE TITLE
save: Modifications remain after 'git mv' of annex file

### ISSUE THREAD

**Issue by kyleam** [datalad/datalad#4967]
This is a follow-up to gh-3686.  As @loj reported over there, there's an unresolved aspect of that issue.  If a symbolic link is moved with `git mv` and the depth of the link changes, `save` commits the staged changes as is (i.e., no adjustment in the link path) and then git-annex fixes up the path afterwards, leaving the dataset dirty and requiring a second `save` call.  Here's the failing test case linked to from that issue:

```diff
diff --git a/datalad/core/local/tests/test_save.py b/datalad/core/local/tests/test_save.py
index 08b706b857..7384ab0ee7 100644
--- a/datalad/core/local/tests/test_save.py
+++ b/datalad/core/local/tests/test_save.py
@@ -11,6 +11,7 @@
 import os
 import os.path as op
 
+from datalad.cmd import Runner
 from datalad.utils import (
     assure_list,
     Path,
@@ -834,3 +835,17 @@ def test_save_dotfiles():
     for git in [True, False, None]:
         for save_path in [None, "nodot-subdir"]:
             yield check_save_dotfiles, git, save_path
+
+
+@with_tree({"subdir": {"foo": "foocontent"}})
+def test_save_git_mv_fixup(path):
+    ds = Dataset(path).create(force=True)
+    ds.save()
+    assert_repo_status(ds.path)
+    ds.repo.call_git(["mv", op.join("subdir", "foo"), "foo"])
+    ds.save()
+    # Was link adjusted properly?  (gh-3686)
+    eq_(Runner(cwd=ds.path).run(["cat", "foo"])[0],
+        "foocontent")
+    # FIXME: But only the deletion was saved.
+    assert_repo_status(ds.path)
```

<details>
<summary>output</summary>

```
======================================================================
FAIL: datalad.core.local.tests.test_save.test_save_git_mv_fixup
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/kyle/src/python/venvs/datalad/lib/python3.7/site-packages/nose/case.py", line 198, in runTest
    self.test(*self.arg)
  File "/home/kyle/src/python/datalad/datalad/tests/utils.py", line 554, in _wrap_with_tree
    return t(*(arg + (d,)), **kw)
  File "/home/kyle/src/python/datalad/datalad/core/local/tests/test_save.py", line 851, in test_save_git_mv_fixup
    assert_repo_status(ds.path)
  File "/home/kyle/src/python/datalad/datalad/tests/utils.py", line 1658, in assert_repo_status
    % (state, state_files, oktobefound))
AssertionError: unexpected content of state "modified": [PosixPath('/tmp/datalad_temp_tree_test_save_git_mv_fixupvj1ers51/foo')] != []
```

</details>

**Comment by mih** [comment]
Looking into this issue, I think a possible mitigation strategy would be to specifically unstage such a change before save runs in full.

After running `._save_pre()` the situation would present itself like this in the status report:

```
(PosixPath('/dspath/foo'), {'state': 'added', 'type': 'file', 'gitshasum': '8eaa386383dc19b441b666ed1ed83a9e2f468715'}),
(PosixPath('/dspath/subdir/foo'), {'state': 'deleted', 'type': 'file', 'gitshasum': '8eaa386383dc19b441b666ed1ed83a9e2f468715'})
```

One and the same file content, once deleted, once added.

If running `git restore --staged foo` at this point, the rest of `save()` will do the right thing and leave the dataset in a clean state. The helper `self.get_staged_paths()` that runs immediately after `_save_pre()`, also reports `"foo"`.

Maybe it would be sufficient to unstage any path that is already known to be "added". This would be cheap to test, with no additional git calls. And it might avoid some cases where we presently would perform partial commits.

**Comment by yarikoptic** [comment]
Just ran into this with `datalad run` which ended up with a dirty state.

Shouldn't we just run `.git/hooks/pre-commit` hook before even assessing the status for `save`? or may be run it right before the commit and reassessing the `status` if we could somehow quickly detect that something changed?

**Comment by yarikoptic** [comment]
in my case it is even more fun.  I think `run` did commit the corrected path (and tree has it fixed up), but then index still had modified one, so git status shows changes, but `git commit -a` fails since it is all the same between the tree and HEAD.

<details>
<summary>FWIW: reproducer</summary> 

```shell
#!/bin/bash

export PS4='> '

set -eux
cd "$(mktemp -d ${TMPDIR:-/tmp}/dl-XXXXXXX)"
topd=`pwd`

datalad create .

touch 123
datalad save 

datalad run 'mkdir sub; git mv 123 sub'

git status
git diff

git commit -m 'committing dirty' -a 

```
</details>

<details>
<summary>and its output</summary> 

```shell
$> bash git-mv-run.sh
>> mktemp -d /home/yoh/.tmp/dl-XXXXXXX
> cd /home/yoh/.tmp/dl-Fi87cYw
>> pwd
> topd=/home/yoh/.tmp/dl-Fi87cYw
> datalad create .
[INFO   ] Creating a new annex repo at /home/yoh/.tmp/dl-Fi87cYw 
[INFO   ] Scanning for unlocked files (this may take some time) 
create(ok): /home/yoh/.tmp/dl-Fi87cYw (dataset)
> touch 123
> datalad save
add(ok): 123 (file)                                                                                                                                                                                                  
save(ok): . (dataset)                                                                                                                                                                                                
action summary:                                                                                                                                                                                                      
  add (ok: 1)
  save (ok: 1)
> datalad run 'mkdir sub; git mv 123 sub'
[INFO   ] == Command start (output follows) ===== 
[INFO   ] == Command exit (modification check follows) ===== 
save(ok): . (dataset)                                                                                                                                                                                                
> git status                                                                                                                                                                                                         
On branch master
Changes to be committed:
  (use "git restore --staged <file>..." to unstage)
	modified:   sub/123

Changes not staged for commit:
  (use "git add <file>..." to update what will be committed)
  (use "git restore <file>..." to discard changes in working directory)
	modified:   sub/123

> git diff
diff --git a/sub/123 b/sub/123
index ce38032..b483e92 120000
--- a/sub/123
+++ b/sub/123
@@ -1 +1 @@
-.git/annex/objects/2W/kW/MD5E-s0--d41d8cd98f00b204e9800998ecf8427e/MD5E-s0--d41d8cd98f00b204e9800998ecf8427e
\ No newline at end of file
+../.git/annex/objects/2W/kW/MD5E-s0--d41d8cd98f00b204e9800998ecf8427e/MD5E-s0--d41d8cd98f00b204e9800998ecf8427e
\ No newline at end of file
> git commit -m 'committing dirty' -a
On branch master
nothing to commit, working tree clean
(dev3) 1 75575 ->1
```
</details>

**Comment by kyleam** [comment]
> Just ran into this with `datalad run` which ended up with a dirty state.

It looks like both of the proposed fixes in gh-5016 would fix this case too.

> Shouldn't we just run `.git/hooks/pre-commit` hook before even assessing the status for `save`? or may be run it right before the commit and reassessing the `status` if we could somehow quickly detect that something changed?

The alternative fix proposed in gh-5016 is to (selectively) run `git annex fix`, which is one of the actions done by `git annex pre-commit`.  I'm not sure if a blanket run of `.git/hooks/pre-commit` would be better, but perhaps it's worth proposing in gh-5016?
