### ISSUE TITLE
locale-dependent create-sibling failure

### ISSUE THREAD

**Issue by kyleam** [datalad/datalad#4969]
`create_sibling._ls_remote_path` assumes English output.

```console
$ export LANG=bg_BG.UTF-8
$ python -m nose datalad.distribution.tests.test_create_sibling:test_replace_and_relative_sshpath
SE
======================================================================
ERROR: datalad.distribution.tests.test_create_sibling.test_replace_and_relative_sshpath(False,)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/kyle/src/python/venvs/datalad/lib/python3.7/site-packages/nose/case.py", line 198, in runTest
    self.test(*self.arg)
  File "/home/kyle/src/python/datalad/datalad/tests/utils.py", line 731, in _wrap_with_tempfile
    return t(*(arg + (filename,)), **kw)
  File "/home/kyle/src/python/datalad/datalad/tests/utils.py", line 731, in _wrap_with_tempfile
    return t(*(arg + (filename,)), **kw)
  File "/home/kyle/src/python/datalad/datalad/distribution/tests/test_create_sibling.py", line 537, in check_replace_and_relative_sshpath
    ds.create_sibling(url, ui=True)
  File "/home/kyle/src/python/datalad/datalad/distribution/dataset.py", line 503, in apply_func
    return f(**kwargs)
  File "/home/kyle/src/python/datalad/datalad/interface/utils.py", line 481, in eval_func
    return return_func(generator_func)(*args, **kwargs)
  File "/home/kyle/src/python/datalad/datalad/interface/utils.py", line 469, in return_func
    results = list(results)
  File "/home/kyle/src/python/datalad/datalad/interface/utils.py", line 400, in generator_func
    allkwargs):
  File "/home/kyle/src/python/datalad/datalad/interface/utils.py", line 539, in _process_results
    for res in results:
  File "/home/kyle/src/python/datalad/datalad/distribution/create_sibling.py", line 761, in __call__
    inherit
  File "/home/kyle/src/python/datalad/datalad/distribution/create_sibling.py", line 196, in _create_dataset_sibling
    path_children = _ls_remote_path(shell, remoteds_path)
  File "/home/kyle/src/python/datalad/datalad/distribution/create_sibling.py", line 392, in _ls_remote_path
    out, err = ssh("ls -A1 {}".format(sh_quote(path)))
  File "/home/kyle/src/python/datalad/datalad/cmd.py", line 608, in __call__
    return self.run(cmd, *args, **kwargs)
  File "/home/kyle/src/python/datalad/datalad/cmd.py", line 970, in run
    raise exc
datalad.support.exceptions.CommandError: CommandError: ''ls -A1 /tmp/datalad_temp_check_replace_and_relative_sshpath95el87a5'' failed with exitcode 2 [err: 'ls: няма достъп до '/tmp/datalad_temp_check_replace_and_relative_sshpath95el87a5': Няма такъв файл или директория']
```

Note that we set `LANG` and `LC_ALL` on some Travis runs, but, as noted in the .travis.yml comments, that doesn't actually have an effect.

**Comment by mih** [comment]
This issue is describing one of many aspects that require a general overhaul of the `create-sibling` command. This overhaul effort is being tracked by the meta-issue #6149. I am closing this issue here, after having added it to that TODO list.
