### ISSUE TITLE
get_versioned_url fails without a dedicated provider/authenticator

### ISSUE THREAD

**Issue by yarikoptic** [datalad/datalad#4984]
```shell
$> python -c 'from datalad.support.s3 import get_versioned_url; print(get_versioned_url("https://dandiarchive.s3.amazonaws.com/girder-assetstore/74/0f/740feade0d784acc8ec76bb7834d80dc"))'
Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "/home/yoh/proj/datalad/datalad-maint/datalad/support/s3.py", line 486, in get_versioned_url
    if s3provider.authenticator.bucket is not None and s3provider.authenticator.bucket.name == s3_bucket:
AttributeError: 'NoneType' object has no attribute 'bucket'
```

**Comment by yarikoptic** [comment]
ha -- forgot Closes statement, fixed by #4985 into maint
