### ISSUE TITLE
Windows track URL handling broken in clone

### ISSUE THREAD

**Issue by mih** [datalad/datalad#4988]
Disclaimer: this had something to do with a specific collection of dataset clones pre-existing on my machine. Once removed, the issue doesn't replicate, but I am sure it is a bug.

```
(base) C:\Users\mih>datalad clone juseless.inm7.de:dummyds h2
[ERROR] [WinError 123] Die Syntax für den Dateinamen, Verzeichnisnamen oder die Datenträgerbezeichnung ist falsch: 'file:\\C\\Users\\mih\\AppData\\Local\\Temp\\datalad_temp_5bvib8h0\\ds2' [pathlib.py:resolve:201] (OSError)
```

Note how the URL is not a URL, and the path has nothing to do with the inputs. The German error says: this path is bullshit.

This is the traceback

```
(base) C:\Users\mih>datalad --dbg clone juseless.inm7.de:dummyds h2
Traceback (most recent call last):
  File "C:\Users\mih\Miniconda3\Scripts\datalad-script.py", line 11, in <module>
    load_entry_point('datalad', 'console_scripts', 'datalad')()
  File "c:\users\mih\code\datalad\datalad\cmdline\main.py", line 521, in main
    ret = cmdlineargs.func(cmdlineargs)
  File "c:\users\mih\code\datalad\datalad\interface\base.py", line 786, in call_from_parser
    ret = list(ret)
  File "c:\users\mih\code\datalad\datalad\interface\utils.py", line 400, in generator_func
    allkwargs):
  File "c:\users\mih\code\datalad\datalad\interface\utils.py", line 539, in _process_results
    for res in results:
  File "c:\users\mih\code\datalad\datalad\core\distributed\clone.py", line 291, in __call__
    cfg=None if ds is None else ds.config,
  File "c:\users\mih\code\datalad\datalad\core\distributed\clone.py", line 396, in clone_dataset
    or get_local_file_url(track_url, compatibility='git') == src \
  File "c:\users\mih\code\datalad\datalad\support\network.py", line 947, in get_local_file_url
    path = Path(fname).resolve()
  File "C:\Users\mih\Miniconda3\lib\pathlib.py", line 1144, in resolve
    s = self._flavour.resolve(self, strict=strict)
  File "C:\Users\mih\Miniconda3\lib\pathlib.py", line 201, in resolve
    s = self._ext_to_normal(_getfinalpathname(s))
OSError: [WinError 123] Die Syntax für den Dateinamen, Verzeichnisnamen oder die Datenträgerbezeichnung ist falsch: 'file:\\C\\Users\\mih\\AppData\\Local\\Temp\\datalad_temp_5bvib8h0\\ds2'
```

The issue is rooted at https://github.com/datalad/datalad/blob/fe090ff2bd157a42a6633f58c02eec62a3183efe/datalad/core/distributed/clone.py#L380

Where `track_url` is 

```
(Pdb) track_url
'file:///C/Users/mih/AppData/Local/Temp/datalad_temp_5bvib8h0/ds2'
```

I can no longer replicate the error, but the handling is wrong nevertheless. This URL is put through `get_local_file_url()` although it is not a path, and that function cannot handle this kind of input.

So it seems that https://github.com/datalad/datalad/blob/fe090ff2bd157a42a6633f58c02eec62a3183efe/datalad/core/distributed/clone.py#L395 needs a fix to the, already complex, conditional.

**Comment by mih** [comment]
Same as #4333, which is fixed now.
