### ISSUE TITLE
asyncio-related competition->crash

### ISSUE THREAD

**Issue by mih** [datalad/datalad#5064]
With present master

```
% ipython3
Python 3.7.3 (default, Apr  3 2019, 05:39:12) 
Type 'copyright', 'credits' or 'license' for more information
IPython 7.18.1 -- An enhanced Interactive Python. Type '?' for help.

In [1]: import datalad.api as dl

In [2]: dl.__version__
Traceback (most recent call last):
  File "/home/mih/venvs/datalad/bin/ipython3", line 8, in <module>
    sys.exit(start_ipython())
  File "/home/mih/venvs/datalad/lib/python3.7/site-packages/IPython/__init__.py", line 126, in start_ipython
    return launch_new_instance(argv=argv, **kwargs)
  File "/home/mih/venvs/datalad/lib/python3.7/site-packages/traitlets/config/application.py", line 837, in launch_instance
    app.start()
  File "/home/mih/venvs/datalad/lib/python3.7/site-packages/IPython/terminal/ipapp.py", line 356, in start
    self.shell.mainloop()
  File "/home/mih/venvs/datalad/lib/python3.7/site-packages/IPython/terminal/interactiveshell.py", line 564, in mainloop
    self.interact()
  File "/home/mih/venvs/datalad/lib/python3.7/site-packages/IPython/terminal/interactiveshell.py", line 547, in interact
    code = self.prompt_for_code()
  File "/home/mih/venvs/datalad/lib/python3.7/site-packages/IPython/terminal/interactiveshell.py", line 478, in prompt_for_code
    asyncio.set_event_loop(old_loop)
  File "/usr/lib/python3.7/asyncio/events.py", line 757, in set_event_loop
    get_event_loop_policy().set_event_loop(loop)
  File "/usr/lib/python3.7/asyncio/unix_events.py", line 1117, in set_event_loop
    self._watcher.attach_loop(loop)
  File "/usr/lib/python3.7/asyncio/unix_events.py", line 868, in attach_loop
    loop.add_signal_handler(signal.SIGCHLD, self._sig_chld)
  File "/usr/lib/python3.7/asyncio/unix_events.py", line 86, in add_signal_handler
    self._check_closed()
  File "/usr/lib/python3.7/asyncio/base_events.py", line 480, in _check_closed
    raise RuntimeError('Event loop is closed')
RuntimeError: Event loop is closed

If you suspect this is an IPython 7.18.1 bug, please report it at:
    https://github.com/ipython/ipython/issues
or send an email to the mailing list at ipython-dev@python.org

You can print a more detailed traceback right now with "%tb", or use "%debug"
to interactively debug it.

Extra-detailed tracebacks for bug-reporting purposes can be enabled via:
    %config Application.verbose_crash=True
```

That is bad.

I wonder if that traceback line in `IPython/terminal/interactiveshell.py` can provide inspiration. It seems as if one could "manage" a dedicated event loop, and we could close that one, instead of closing THE one. Just speculation at this point...didn't look.

**Comment by yarikoptic** [comment]
what I see in conda
```
(datalad-py3.7.9) 1 32311.....................................:Wed 21 Oct 2020 11:54:21 AM EDT:.
(git)lena:~datalad/datalad-maint[enh-iter-progress]git
$> ipython              
Python 3.7.9 (default, Aug 31 2020, 12:42:55) 
Type 'copyright', 'credits' or 'license' for more information
IPython 7.18.1 -- An enhanced Interactive Python. Type '?' for help.

In [1]: import datalad.api as dl; dl.__version__ 
---------------------------------------------------------------------------
AttributeError                            Traceback (most recent call last)
<ipython-input-1-e5c482883622> in <module>
----> 1 import datalad.api as dl; dl.__version__

AttributeError: module 'datalad.api' has no attribute '__version__'
```

and the same in a virtualenv with python 3.8.

**Comment by yarikoptic** [comment]
there was a good number of fixes to async in 3.7 -- try something newer than 3.7.3

**Comment by yarikoptic** [comment]
ha -- posted, and then  by mistake ran the same `import datalad.api as dl; dl.__version__ ` -- it did crash similarly in 3.7.9 conda... it doesn't crash 3.8.5

**Comment by yarikoptic** [comment]
<details>
<summary>Failed to reproduce using 3.8.0a1 build</summary> 

```shell
> ( export PATH=~/proj/misc/cpython-builds/v3.8.0a1/usr/local/bin:$PATH; PYTHONPATH=/usr/lib/python3/dist-packages/ python3 /usr/bin/ipython3; ) 
Python 3.8.0a1 (tags/v3.8.0a1:e75eeb00b56, Oct 14 2020, 16:54:43) 
Type 'copyright', 'credits' or 'license' for more information
IPython 7.13.0 -- An enhanced Interactive Python. Type '?' for help.

In [1]: import datalad.api as dl; dl.__version__                                                   
/usr/lib/python3/dist-packages/duecredit/entries.py:69: SyntaxWarning: invalid escape sequence \s
  reg = re.match("\s*@(?P<type>\S*)\s*\{\s*(?P<key>\S*)\s*,.*",
^[[A/usr/lib/python3/dist-packages/datalad/metadata/search.py:983: SyntaxWarning: invalid escape sequence \.
  """Search dataset metadata
/usr/lib/python3/dist-packages/boto/__init__.py:1105: SyntaxWarning: invalid escape sequence \c
  """
/usr/lib/python3/dist-packages/boto/pyami/config.py:98: SyntaxWarning: invalid escape sequence \s
  match = re.match("^#import[\s\t]*([^\s^\t]*)[\s\t]*$", line)
/usr/lib/python3/dist-packages/boto/connection.py:672: SyntaxWarning: invalid escape sequence \w
  '(?:(?P<user>[\w\-\.]+):(?P<pass>.*)@)?'
/usr/lib/python3/dist-packages/boto/connection.py:673: SyntaxWarning: invalid escape sequence \w
  '(?P<host>[\w\-\.]+)'
/usr/lib/python3/dist-packages/boto/connection.py:674: SyntaxWarning: invalid escape sequence \d
  '(?::(?P<port>\d+))?'
/usr/lib/python3/dist-packages/boto/https_connection.py:80: SyntaxWarning: invalid escape sequence \.
  host_re = host.replace('.', '\.').replace('*', '[^.]*')
---------------------------------------------------------------------------
AttributeError                            Traceback (most recent call last)
<ipython-input-1-cfe7245712ba> in <module>
----> 1 import datalad.api as dl; dl.__version__

AttributeError: module 'datalad.api' has no attribute '__version__'

In [2]: import datalad.api as dl; dl.__version__                                                   
---------------------------------------------------------------------------
AttributeError                            Traceback (most recent call last)
<ipython-input-2-cfe7245712ba> in <module>
----> 1 import datalad.api as dl; dl.__version__

AttributeError: module 'datalad.api' has no attribute '__version__'

In [3]: import datalad.api as dl; dl.__version__                                                   
---------------------------------------------------------------------------
AttributeError                            Traceback (most recent call last)
<ipython-input-3-cfe7245712ba> in <module>
----> 1 import datalad.api as dl; dl.__version__

AttributeError: module 'datalad.api' has no attribute '__version__'

In [4]: import datalad.api as dl; dl.__version__                                                   
---------------------------------------------------------------------------
AttributeError                            Traceback (most recent call last)
<ipython-input-4-cfe7245712ba> in <module>
----> 1 import datalad.api as dl; dl.__version__

AttributeError: module 'datalad.api' has no attribute '__version__'
```
</details>

Someone interested to bisect, see https://github.com/datalad/datalad/pull/5022/files#diff-0b778652845a62913dc28bf9ff5109c351f667c5a62f86b01373bf38c9b2a76b which could be of help ;)  I will built/test 3.7.9 just to be sure that it wasn't conda effect for me

**Comment by yarikoptic** [comment]
<details>
<summary>FWIW - in my case it is important to have 2nd line execution (regardless what it is) (still conda)</summary> 

```shell
$> ipython             
Python 3.7.9 (default, Aug 31 2020, 12:42:55) 
Type 'copyright', 'credits' or 'license' for more information
IPython 7.18.1 -- An enhanced Interactive Python. Type '?' for help.

In [1]: import datalad.api as dl

In [2]: print(1)
Traceback (most recent call last):
  File "/home/yoh/anaconda-5.2.0-2.7/envs/datalad-py3.7.9/bin/ipython", line 11, in <module>
    sys.exit(start_ipython())
  File "/home/yoh/anaconda-5.2.0-2.7/envs/datalad-py3.7.9/lib/python3.7/site-packages/IPython/__init__.py", line 126, in start_ipython
    return launch_new_instance(argv=argv, **kwargs)
  File "/home/yoh/anaconda-5.2.0-2.7/envs/datalad-py3.7.9/lib/python3.7/site-packages/traitlets/config/application.py", line 845, in launch_instance
    app.start()
  File "/home/yoh/anaconda-5.2.0-2.7/envs/datalad-py3.7.9/lib/python3.7/site-packages/IPython/terminal/ipapp.py", line 356, in start
    self.shell.mainloop()
  File "/home/yoh/anaconda-5.2.0-2.7/envs/datalad-py3.7.9/lib/python3.7/site-packages/IPython/terminal/interactiveshell.py", line 564, in mainloop
    self.interact()
  File "/home/yoh/anaconda-5.2.0-2.7/envs/datalad-py3.7.9/lib/python3.7/site-packages/IPython/terminal/interactiveshell.py", line 547, in interact
    code = self.prompt_for_code()
  File "/home/yoh/anaconda-5.2.0-2.7/envs/datalad-py3.7.9/lib/python3.7/site-packages/IPython/terminal/interactiveshell.py", line 478, in prompt_for_code
    asyncio.set_event_loop(old_loop)
  File "/home/yoh/anaconda-5.2.0-2.7/envs/datalad-py3.7.9/lib/python3.7/asyncio/events.py", line 757, in set_event_loop
    get_event_loop_policy().set_event_loop(loop)
  File "/home/yoh/anaconda-5.2.0-2.7/envs/datalad-py3.7.9/lib/python3.7/asyncio/unix_events.py", line 1134, in set_event_loop
    self._watcher.attach_loop(loop)
  File "/home/yoh/anaconda-5.2.0-2.7/envs/datalad-py3.7.9/lib/python3.7/asyncio/unix_events.py", line 885, in attach_loop
    loop.add_signal_handler(signal.SIGCHLD, self._sig_chld)
  File "/home/yoh/anaconda-5.2.0-2.7/envs/datalad-py3.7.9/lib/python3.7/asyncio/unix_events.py", line 86, in add_signal_handler
    self._check_closed()
  File "/home/yoh/anaconda-5.2.0-2.7/envs/datalad-py3.7.9/lib/python3.7/asyncio/base_events.py", line 479, in _check_closed
    raise RuntimeError('Event loop is closed')
RuntimeError: Event loop is closed

If you suspect this is an IPython 7.18.1 bug, please report it at:
    https://github.com/ipython/ipython/issues
or send an email to the mailing list at ipython-dev@python.org

You can print a more detailed traceback right now with "%tb", or use "%debug"
to interactively debug it.

Extra-detailed tracebacks for bug-reporting purposes can be enabled via:
    %config Application.verbose_crash=True

```
</details>

**Comment by yarikoptic** [comment]
<details>
<summary>and failed to reproduce with python 3.7.9 locally built and system wide ipython</summary> 

```shell
$> ( export PATH=~/proj/misc/cpython-builds/v3.7.9/usr/local/bin:$PATH; PYTHONPATH=/usr/lib/python3/dist-packages/ python3 /usr/bin/ipython3; ) 
Python 3.7.9 (tags/v3.7.9:13c94747c74, Oct 21 2020, 12:11:23) 
Type 'copyright', 'credits' or 'license' for more information
IPython 7.13.0 -- An enhanced Interactive Python. Type '?' for help.

In [1]: import datalad.api as dl                                                                   

In [2]: print(1)                                                                                   
1

In [3]: import datalad.api as dl                                                                   

In [4]: dl.__version__                                                                             
---------------------------------------------------------------------------
AttributeError                            Traceback (most recent call last)
<ipython-input-4-d3eff33a724a> in <module>
----> 1 dl.__version__

AttributeError: module 'datalad.api' has no attribute '__version__'

In [5]: dl.__version__                                                                             
---------------------------------------------------------------------------
AttributeError                            Traceback (most recent call last)
<ipython-input-5-d3eff33a724a> in <module>
----> 1 dl.__version__

AttributeError: module 'datalad.api' has no attribute '__version__'

In [6]: print(1)                                                                                   
1

In [7]:                                                                                            
Do you really want to exit ([y]/n)? 
```
</details>
so it might be related to ipython as in conda.  stopping my explorations here

**Comment by mih** [comment]
Thanks for the insight! I can confirm that a system-wide ipython doesn't show the problem:

```
% apt-cache policy ipython3
ipython3:
  Installed: 5.8.0-1
  Candidate: 5.8.0-1
  Version table:
 *** 5.8.0-1 500
```

while the most recent version from pip (in a virtualenv) does -- using the same Python 3.7.3.

```
% pip list | grep ipython
ipython            7.18.1                
ipython-genutils   0.2.0                 
```

**Comment by mih** [comment]
But getting back to my original point. Here is how ipython handles the event loop:

```py
       # In order to make sure that asyncio code written in the
        # interactive shell doesn't interfere with the prompt, we run the
        # prompt in a different event loop.
        # If we don't do this, people could spawn coroutine with a
        # while/true inside which will freeze the prompt.

        try:
            old_loop = asyncio.get_event_loop()
        except RuntimeError:
            # This happens when the user used `asyncio.run()`.
            old_loop = None

        asyncio.set_event_loop(self.pt_loop)
        try:
            with patch_stdout(raw=True):
                text = self.pt_app.prompt(
                    default=default,
                    **self._extra_prompt_options())
        finally:
            # Restore the original event loop.
            asyncio.set_event_loop(old_loop)
```

whereas we do:

```py
       if sys.platform == "win32":
            # use special event loop that supports subprocesses on windows
            event_loop = asyncio.ProactorEventLoop()
        else:
            event_loop = asyncio.SelectorEventLoop()
        asyncio.set_event_loop(event_loop)
        # include the subprocess manager in the asyncio event loop
        results = event_loop.run_until_complete(
            run_async_cmd(
                event_loop,
                cmd,
                protocol,
                stdin,
                protocol_kwargs=kwargs,
                cwd=cwd,
                env=env,
            )
        )
        # terminate the event loop, cannot be undone, hence we start a fresh
        # one each time (see BlockingIOError notes above)
        event_loop.close()
```

maybe we should also explicitly query for, save, and restore any present event loop.

**Comment by mih** [comment]
Another piece of evidence from the DataLad matrix room:

> It turned out that python 3.8.0 did not fix the issue. I turned to the questionary developers and someone hinted at using
"asyncio.set_event_loop(asyncio.new_event_loop())" after or before each interaction.
That solved the issue and I could using the datalad.api
