### ISSUE TITLE
Dataset caching broken on windows (or tests)

### ISSUE THREAD

**Issue by mih** [datalad/datalad#5074]
This functionality is a fairly recent addition: https://github.com/datalad/datalad/pull/4608

However, its tests are broken on windows, hence we should assume that the actual functionality is also not function on windows.

```
======================================================================
FAIL: datalad.tests.test_utils_cached_dataset.test_cached_dataset
----------------------------------------------------------------------
Traceback (most recent call last):
  File "C:\Users\mih\miniconda3\lib\site-packages\nose\case.py", line 198, in runTest
    self.test(*self.arg)
  File "C:\Users\mih\code\datalad\datalad\tests\utils.py", line 180, in _wrap_skip_if_no_network
    return func(*args, **kwargs)
  File "C:\Users\mih\code\datalad\datalad\tests\utils.py", line 755, in _wrap_with_tempfile
    return t(*(arg + (filename,)), **kw)
  File "C:\Users\mih\code\datalad\datalad\tests\test_utils_cached_dataset.py", line 247, in test_cached_dataset
    second_dspath, second_repopath = decorated_test2()
  File "C:\Users\mih\miniconda3\lib\site-packages\wrapt\wrappers.py", line 566, in __call__
    return self._self_wrapper(self.__wrapped__, self._self_instance,
  File "C:\Users\mih\code\datalad\datalad\utils.py", line 996, in intermediator
    return to_be_wrapper(*args, **kwargs)
  File "C:\Users\mih\code\datalad\datalad\tests\utils.py", line 755, in _wrap_with_tempfile
    return t(*(arg + (filename,)), **kw)
  File "C:\Users\mih\code\datalad\datalad\tests\utils_cached_dataset.py", line 184, in _wrap_cached_dataset
    return f(*(arg[:-1] + (clone_ds,)), **kw)
  File "C:\Users\mih\code\datalad\datalad\tests\test_utils_cached_dataset.py", line 197, in decorated_test2
    assert_in(here, where)
AssertionError: '40334d1c-d520-4b33-a620-4f7daf8a1d23' not found in []

======================================================================
FAIL: datalad.tests.test_utils_cached_dataset.test_cached_url
----------------------------------------------------------------------
Traceback (most recent call last):
  File "C:\Users\mih\miniconda3\lib\site-packages\nose\case.py", line 198, in runTest
    self.test(*self.arg)
  File "C:\Users\mih\code\datalad\datalad\tests\utils.py", line 180, in _wrap_skip_if_no_network
    return func(*args, **kwargs)
  File "C:\Users\mih\code\datalad\datalad\tests\utils.py", line 755, in _wrap_with_tempfile
    return t(*(arg + (filename,)), **kw)
  File "C:\Users\mih\code\datalad\datalad\tests\test_utils_cached_dataset.py", line 294, in test_cached_url
    decorated_test2()
  File "C:\Users\mih\miniconda3\lib\site-packages\wrapt\wrappers.py", line 566, in __call__
    return self._self_wrapper(self.__wrapped__, self._self_instance,
  File "C:\Users\mih\code\datalad\datalad\utils.py", line 996, in intermediator
    return to_be_wrapper(*args, **kwargs)
  File "C:\Users\mih\code\datalad\datalad\tests\utils_cached_dataset.py", line 236, in _wrap_cached_url
    return f(*(arg + (new_url,)), **kw)
  File "C:\Users\mih\code\datalad\datalad\tests\test_utils_cached_dataset.py", line 292, in decorated_test2
    assert_true(origin.repo.file_has_content(str(annexed_file)))
AssertionError: False is not true
```

**Comment by mih** [comment]
Ping for awareness @bpoldrack

**Comment by jsheunis** [comment]
Update on this issue: looks like the tests pass on windows locally and on Appveyor. I did the following:

- `python -m nose -s -v --traverse-namespace datalad/tests/test_utils_cached_dataset.py` ==> resulted in successfull tests on windows locally
- checked in https://github.com/datalad/datalad/blob/master/datalad/tests/test_utils_cached_dataset.py whether the tests have any skip decorators ==> none for these specific tests
- checked the apveyor config to see if the tests are supposed to run ==> they should: https://github.com/datalad/datalad/blob/9bee7ee08305ab0fa13136c96884df7f4a1327fa/.appveyor.yml#L104-L114
- checked a recent apveyor run to see if the tests run and succeed ==> they do: https://ci.appveyor.com/project/mih/datalad/branch/master/job/bud51c3rcy7calob#L3520

So it seems like all is well. @mih does this sufficiently address the issue?

**Comment by mih** [comment]
Thanks for the investigation. Let's close it!
