### ISSUE TITLE
Broken URL/root path handling for main service dataset

### ISSUE THREAD

**Issue by mih** [datalad/datalad#5084]
Revealed by #5080 

```
======================================================================
1464ERROR: datalad.core.distributed.tests.test_clone.test_clone_datasets_root
1465----------------------------------------------------------------------
1466Traceback (most recent call last):
1467  File "C:\Miniconda35\envs\test-environment\lib\site-packages\nose\case.py", line 198, in runTest
1468    self.test(*self.arg)
1469  File "C:\Miniconda35\envs\test-environment\lib\site-packages\datalad\tests\utils.py", line 177, in _wrap_skip_if_no_network
1470    return func(*args, **kwargs)
1471  File "C:\Miniconda35\envs\test-environment\lib\site-packages\vcr\cassette.py", line 100, in __call__
1472    return type(self)(self.cls, args_getter)._execute_function(function, args, kwargs)
1473  File "C:\Miniconda35\envs\test-environment\lib\site-packages\vcr\cassette.py", line 114, in _execute_function
1474    return self._handle_function(fn=handle_function)
1475  File "C:\Miniconda35\envs\test-environment\lib\site-packages\vcr\cassette.py", line 138, in _handle_function
1476    return fn(cassette)
1477  File "C:\Miniconda35\envs\test-environment\lib\site-packages\vcr\cassette.py", line 107, in handle_function
1478    return function(*args, **kwargs)
1479  File "C:\Miniconda35\envs\test-environment\lib\site-packages\datalad\tests\utils.py", line 573, in _wrap_with_tree
1480    return t(*(arg + (d,)), **kw)
1481  File "C:\Miniconda35\envs\test-environment\lib\site-packages\datalad\core\distributed\tests\test_clone.py", line 145, in test_clone_datasets_root
1482    res = clone("///", on_failure='ignore', result_xfm=None, return_type='list')
1483  File "C:\Miniconda35\envs\test-environment\lib\site-packages\datalad\interface\utils.py", line 495, in eval_func
1484    return return_func(generator_func)(*args, **kwargs)
1485  File "C:\Miniconda35\envs\test-environment\lib\site-packages\datalad\interface\utils.py", line 483, in return_func
1486    results = list(results)
1487  File "C:\Miniconda35\envs\test-environment\lib\site-packages\datalad\interface\utils.py", line 414, in generator_func
1488    allkwargs):
1489  File "C:\Miniconda35\envs\test-environment\lib\site-packages\datalad\interface\utils.py", line 562, in _process_results
1490    for res in results:
1491  File "C:\Miniconda35\envs\test-environment\lib\site-packages\datalad\core\distributed\clone.py", line 293, in __call__
1492    cfg=None if ds is None else ds.config,
1493  File "C:\Miniconda35\envs\test-environment\lib\site-packages\datalad\core\distributed\clone.py", line 398, in clone_dataset
1494    or get_local_file_url(track_url, compatibility='git') == src \
1495  File "C:\Miniconda35\envs\test-environment\lib\site-packages\datalad\support\network.py", line 947, in get_local_file_url
1496    path = Path(fname).resolve()
1497  File "C:\Miniconda35\envs\test-environment\lib\site-packages\datalad\utils.py", line 380, in _resolve_without_strict
1498    if strict or self.exists():
1499  File "C:\Miniconda35\envs\test-environment\lib\pathlib.py", line 1291, in exists
1500    self.stat()
1501  File "C:\Miniconda35\envs\test-environment\lib\pathlib.py", line 1111, in stat
1502    return self._accessor.stat(self)
1503  File "C:\Miniconda35\envs\test-environment\lib\pathlib.py", line 371, in wrapped
1504    return strfunc(str(pathobj), *args)
1505OSError: [WinError 123] The filename, directory name, or volume label syntax is incorrect: 'http:\\datasets-tests.datalad.org\\.git'

======================================================================
1597ERROR: datalad.distribution.tests.test_install.test_install_datasets_root
1598----------------------------------------------------------------------
1599Traceback (most recent call last):
1600  File "C:\Miniconda35\envs\test-environment\lib\site-packages\nose\case.py", line 198, in runTest
1601    self.test(*self.arg)
1602  File "C:\Miniconda35\envs\test-environment\lib\site-packages\datalad\tests\utils.py", line 177, in _wrap_skip_if_no_network
1603    return func(*args, **kwargs)
1604  File "C:\Miniconda35\envs\test-environment\lib\site-packages\vcr\cassette.py", line 100, in __call__
1605    return type(self)(self.cls, args_getter)._execute_function(function, args, kwargs)
1606  File "C:\Miniconda35\envs\test-environment\lib\site-packages\vcr\cassette.py", line 114, in _execute_function
1607    return self._handle_function(fn=handle_function)
1608  File "C:\Miniconda35\envs\test-environment\lib\site-packages\vcr\cassette.py", line 138, in _handle_function
1609    return fn(cassette)
1610  File "C:\Miniconda35\envs\test-environment\lib\site-packages\vcr\cassette.py", line 107, in handle_function
1611    return function(*args, **kwargs)
1612  File "C:\Miniconda35\envs\test-environment\lib\site-packages\datalad\tests\utils.py", line 573, in _wrap_with_tree
1613    return t(*(arg + (d,)), **kw)
1614  File "C:\Miniconda35\envs\test-environment\lib\site-packages\datalad\distribution\tests\test_install.py", line 188, in test_install_datasets_root
1615    result = install("///", result_xfm=None, return_type='list')
1616  File "C:\Miniconda35\envs\test-environment\lib\site-packages\datalad\interface\utils.py", line 495, in eval_func
1617    return return_func(generator_func)(*args, **kwargs)
1618  File "C:\Miniconda35\envs\test-environment\lib\site-packages\datalad\interface\utils.py", line 483, in return_func
1619    results = list(results)
1620  File "C:\Miniconda35\envs\test-environment\lib\site-packages\datalad\interface\utils.py", line 414, in generator_func
1621    allkwargs):
1622  File "C:\Miniconda35\envs\test-environment\lib\site-packages\datalad\interface\utils.py", line 562, in _process_results
1623    for res in results:
1624  File "C:\Miniconda35\envs\test-environment\lib\site-packages\datalad\distribution\install.py", line 249, in __call__
1625    **common_kwargs):
1626  File "C:\Miniconda35\envs\test-environment\lib\site-packages\datalad\interface\utils.py", line 414, in generator_func
1627    allkwargs):
1628  File "C:\Miniconda35\envs\test-environment\lib\site-packages\datalad\interface\utils.py", line 562, in _process_results
1629    for res in results:
1630  File "C:\Miniconda35\envs\test-environment\lib\site-packages\datalad\distribution\install.py", line 369, in __call__
1631    for r in res:
1632  File "C:\Miniconda35\envs\test-environment\lib\site-packages\datalad\interface\utils.py", line 414, in generator_func
1633    allkwargs):
1634  File "C:\Miniconda35\envs\test-environment\lib\site-packages\datalad\interface\utils.py", line 562, in _process_results
1635    for res in results:
1636  File "C:\Miniconda35\envs\test-environment\lib\site-packages\datalad\core\distributed\clone.py", line 293, in __call__
1637    cfg=None if ds is None else ds.config,
1638  File "C:\Miniconda35\envs\test-environment\lib\site-packages\datalad\core\distributed\clone.py", line 398, in clone_dataset
1639    or get_local_file_url(track_url, compatibility='git') == src \
1640  File "C:\Miniconda35\envs\test-environment\lib\site-packages\datalad\support\network.py", line 947, in get_local_file_url
1641    path = Path(fname).resolve()
1642  File "C:\Miniconda35\envs\test-environment\lib\site-packages\datalad\utils.py", line 380, in _resolve_without_strict
1643    if strict or self.exists():
1644  File "C:\Miniconda35\envs\test-environment\lib\pathlib.py", line 1291, in exists
1645    self.stat()
1646  File "C:\Miniconda35\envs\test-environment\lib\pathlib.py", line 1111, in stat
1647    return self._accessor.stat(self)
1648  File "C:\Miniconda35\envs\test-environment\lib\pathlib.py", line 371, in wrapped
1649    return strfunc(str(pathobj), *args)
1650OSError: [WinError 123] The filename, directory name, or volume label syntax is incorrect: 'http:\\datasets-tests.datalad.org\\.git'
1651
```

Replicates on `maint` and `master` on a real win10 box.

**Comment by mih** [comment]
Same as #4333, which is fixed now.
