### ISSUE TITLE
test_AnnexRepo_addurl_to_file_batched broken

### ISSUE THREAD

**Issue by mih** [datalad/datalad#5088]
Revealed by #5080 

```
======================================================================
1766ERROR: datalad.support.tests.test_annexrepo.test_AnnexRepo_addurl_to_file_batched
1767----------------------------------------------------------------------
1768Traceback (most recent call last):
1769  File "C:\Miniconda35\envs\test-environment\lib\site-packages\nose\case.py", line 198, in runTest
1770    self.test(*self.arg)
1771  File "C:\Miniconda35\envs\test-environment\lib\site-packages\datalad\tests\utils.py", line 573, in _wrap_with_tree
1772    return t(*(arg + (d,)), **kw)
1773  File "C:\Miniconda35\envs\test-environment\lib\site-packages\datalad\tests\utils.py", line 685, in _wrap_serve_path_via_http
1774    return tfunc(*(args + (path, url)), **kwargs)
1775  File "C:\Miniconda35\envs\test-environment\lib\site-packages\datalad\tests\utils.py", line 750, in _wrap_with_tempfile
1776    return t(*(arg + (filename,)), **kw)
1777  File "C:\Miniconda35\envs\test-environment\lib\site-packages\datalad\support\tests\test_annexrepo.py", line 1015, in test_AnnexRepo_addurl_to_file_batched
1778    eq_(info['size'], 14)
1779TypeError: 'NoneType' object is not subscriptable
1780
```

**Comment by yarikoptic** [comment]
file is marked as known fail on windows
```
datalad/support/tests/test_annexrepo.py-@known_failure_windows
datalad/support/tests/test_annexrepo.py-@with_tree(tree=(('about.txt', 'Lots of abouts'),
datalad/support/tests/test_annexrepo.py-                 ('about2.txt', 'more abouts'),
datalad/support/tests/test_annexrepo.py-                 ('about2_.txt', 'more abouts_'),
datalad/support/tests/test_annexrepo.py-                 ('d', {'sub.txt': 'more stuff'})))
datalad/support/tests/test_annexrepo.py-@serve_path_via_http()
datalad/support/tests/test_annexrepo.py-@with_tempfile
datalad/support/tests/test_annexrepo.py:def test_AnnexRepo_addurl_to_file_batched(sitepath=None, siteurl=None, dst=None):
```
among other dozens... should we keep it open?
