### ISSUE TITLE
test_serve_path_via_http fails on appveyor (master-specific)

### ISSUE THREAD

**Issue by kyleam** [datalad/datalad#5095]
``test_serve_path_via_http`` wasn't being triggered on appveyor due to gh-5080.  It passes on the maint-based run for gh-5080, but fails with the merge to master (gh-5092).  The test itself hasn't changed on master, so failing on master but not maint seems likely due to changes in the obscure file name generation on master.

```
======================================================================
1784FAIL: datalad.tests.test_tests_utils.test_serve_path_via_http(";&%b5{}'.datc",)
1785----------------------------------------------------------------------
1786Traceback (most recent call last):
1787  File "C:\Miniconda36\envs\test-environment\lib\site-packages\nose\case.py", line 198, in runTest
1788    self.test(*self.arg)
1789  File "C:\Miniconda36\envs\test-environment\lib\site-packages\datalad\tests\utils.py", line 755, in _wrap_with_tempfile
1790    return t(*(arg + (filename,)), **kw)
1791  File "C:\Miniconda36\envs\test-environment\lib\site-packages\datalad\tests\test_tests_utils.py", line 436, in _test_serve_path_via_http
1792    test_path_and_url()
1793  File "C:\Miniconda36\envs\test-environment\lib\site-packages\datalad\tests\utils.py", line 688, in _wrap_serve_path_via_http
1794    return tfunc(*(args + (path, url)), **kwargs)
1795  File "C:\Miniconda36\envs\test-environment\lib\site-packages\datalad\tests\test_tests_utils.py", line 419, in test_path_and_url
1796    assert_false('http_proxy' in os.environ)
1797AssertionError: True is not false
1798
```

https://github.com/datalad/datalad/pull/5092#issuecomment-716561056

**Comment by kyleam** [comment]
This is marked with as a known failure.  We don't have dedicated issues for most `known_failure_windows` tests, so I think this is okay to close.

https://github.com/datalad/datalad/blob/f63ed567dbc79cc8b22a51b7e00f9fb2419dcb66/datalad/tests/test_tests_utils.py#L440-L442
