### ISSUE TITLE
"Cannot run the event loop while another loop is running" if imported from within another async process

### ISSUE THREAD

**Issue by yarikoptic** [datalad/datalad#5100]
possibly relates to #5064 although manifests slightly differently (thus filed separately).

I am "exploring" pycrunch , see https://github.com/gleb-sevruk/pycrunch-engine/pull/29 -- it would be nice to be able to tell which parts of code any particular test is affecting, and thus when fixing a bug also run locally only tests possibly affected by that particular code path, and actually have those tests automagically reran.

But immediate fiasco is inability to import datalad's modules (that is how pycrunch discovers tests ATM, see related https://github.com/gleb-sevruk/pycrunch-engine/pull/29) from within pycrunch:
```
[1076264] 2020-10-27 13:00:17,905 - pycrunch.discovery.simple - WARNING - importing datalad.distributed.tests.test_ria_basics
[1076264] 2020-10-27 13:00:17,905 - pycrunch.discovery.simple - ERROR - Failed to load `datalad/distributed/tests/test_ria_basics.py`
[1076264] 2020-10-27 13:00:17,905 - pycrunch.discovery.simple - ERROR - importing datalad.distributed.tests.test_ria_basics failed with exception: Cannot run the event loop while another loop is running
Traceback (most recent call last):
  File "/home/yoh/proj/misc/pycrunch-engine/pycrunch/discovery/simple.py", line 104, in find_tests_in_folder
    module = importlib.import_module(module_name)
  File "/usr/lib/python3.8/importlib/__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1014, in _gcd_import
  File "<frozen importlib._bootstrap>", line 991, in _find_and_load
  File "<frozen importlib._bootstrap>", line 961, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "<frozen importlib._bootstrap>", line 1014, in _gcd_import
  File "<frozen importlib._bootstrap>", line 991, in _find_and_load
  File "<frozen importlib._bootstrap>", line 961, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "<frozen importlib._bootstrap>", line 1014, in _gcd_import
  File "<frozen importlib._bootstrap>", line 991, in _find_and_load
  File "<frozen importlib._bootstrap>", line 961, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "<frozen importlib._bootstrap>", line 1014, in _gcd_import
  File "<frozen importlib._bootstrap>", line 991, in _find_and_load
  File "<frozen importlib._bootstrap>", line 975, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 671, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 783, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/home/yoh/proj/datalad/datalad-master/datalad/__init__.py", line 47, in <module>
    cfg = ConfigManager()
  File "/home/yoh/proj/datalad/datalad-master/datalad/config.py", line 247, in __init__
    self.reload(force=True)
  File "/home/yoh/proj/datalad/datalad-master/datalad/config.py", line 300, in reload
    self._stores[store_id] = self._reload(runargs)
  File "/home/yoh/proj/datalad/datalad-master/datalad/config.py", line 333, in _reload
    stdout, stderr = self._run(
  File "/home/yoh/proj/datalad/datalad-master/datalad/config.py", line 684, in _run
    out = self._runner.run(self._config_cmd + args, **kwargs)
  File "/home/yoh/proj/datalad/datalad-master/datalad/cmd.py", line 489, in run
    results = event_loop.run_until_complete(
  File "/usr/lib/python3.8/asyncio/base_events.py", line 592, in run_until_complete
    self._check_running()
  File "/usr/lib/python3.8/asyncio/base_events.py", line 554, in _check_running
    raise RuntimeError(
RuntimeError: Cannot run the event loop while another loop is running
```
(nothing ria specific here -- this is just a sample of bunch of those being dumped to the log)

**Comment by christian-monch** [comment]
I see an error on python3.6 with the asyncio-based runner. This error vanishes with the nonasyncrunner.

**Comment by kyleam** [comment]
Closed by gh-5667 (but wasn't automatically closed due to markup issue)
