### ISSUE TITLE
python datalad/install.py datalad-extensions-build  looks for datalad/tools/ci/download-latest-artifact

### ISSUE THREAD

**Issue by yarikoptic** [datalad/datalad#5191]
instead of `tools/ci/download-latest-artifact` and should not use that script anyways -- `install.py` should be sufficient standalone

probably  better be "fixed" as a part of the large RF discussed in #5181 

```shell
$> python datalad/install.py datalad-extensions-build
Traceback (most recent call last):
  File "datalad/install.py", line 432, in <module>
    main()
  File "datalad/install.py", line 96, in main
    installer.install_via_datalad_extensions_build()
  File "datalad/install.py", line 369, in install_via_datalad_extensions_build
    subprocess.run(
  File "/usr/lib/python3.8/subprocess.py", line 489, in run
    with Popen(*popenargs, **kwargs) as process:
  File "/usr/lib/python3.8/subprocess.py", line 854, in __init__
    self._execute_child(args, executable, preexec_fn, close_fds,
  File "/usr/lib/python3.8/subprocess.py", line 1702, in _execute_child
    raise child_exception_type(errno_num, err_msg, err_filename)
FileNotFoundError: [Errno 2] No such file or directory: 'datalad/tools/ci/download-latest-artifact'
```

**Comment by yarikoptic** [comment]
note: due to move of git-annex builds to datalad/git-annex and adding version into produced artifact zipball name, that script is not working after minimal patch
```
$> git diff
diff --git a/tools/ci/download-latest-artifact b/tools/ci/download-latest-artifact
index ab8a6553b..44f2bacee 100755
--- a/tools/ci/download-latest-artifact
+++ b/tools/ci/download-latest-artifact
@@ -3,9 +3,9 @@
 # Apache 2.0 license 
 set -eu
 
-: "${TARGET_REPO:=datalad/datalad-extensions}"
+: "${TARGET_REPO:=datalad/git-annex}"
 : "${TARGET_BRANCH:=master}"
-: "${TARGET_WORKFLOW:=build-git-annex.yaml}"
+: "${TARGET_WORKFLOW:=build-ubuntu.yaml}"
 : "${TARGET_PATH:=download}"  # Directory which will be created if doesn't exist
 : "${TARGET_ARTIFACT:=git-annex-debianstandalone-packages}"
 : "${GITHUB_TOKEN:=}" # will be taken from git config hub.oauthtoken or needs to be defined
```

fix to install.py should reflect that, and most likely we should rename that "schema" to `datalad/git-annex` or alike to reflect that it is no longer part of `datalad-extensions`
