### ISSUE TITLE
test_reckless (on maint) with git-annex-8.20201007

### ISSUE THREAD

**Issue by yarikoptic** [datalad/datalad#5206]
In a test build against most recent git-annex on conda-forge (one of those runs stalled in previous run before tune up of .ssh/config permissions which were r for everyone)
https://travis-ci.com/github/datalad/datalad/jobs/454325181
https://travis-ci.com/github/datalad/datalad/jobs/454325180

```
======================================================================
FAIL: datalad.core.distributed.tests.test_clone.test_reckless(True,)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/travis/virtualenv/python3.7.1/lib/python3.7/site-packages/nose/case.py", line 198, in runTest
    self.test(*self.arg)
  File "/home/travis/virtualenv/python3.7.1/lib/python3.7/site-packages/datalad/tests/utils.py", line 750, in _wrap_with_tempfile
    return t(*(arg + (filename,)), **kw)
  File "/home/travis/virtualenv/python3.7.1/lib/python3.7/site-packages/datalad/tests/utils.py", line 750, in _wrap_with_tempfile
    return t(*(arg + (filename,)), **kw)
  File "/home/travis/virtualenv/python3.7.1/lib/python3.7/site-packages/datalad/tests/utils.py", line 750, in _wrap_with_tempfile
    return t(*(arg + (filename,)), **kw)
  File "/home/travis/virtualenv/python3.7.1/lib/python3.7/site-packages/datalad/core/distributed/tests/test_clone.py", line 367, in check_reckless
    & stat.S_IWGRP)
AssertionError: 16 is not false
```

this seems to be the only one failing ATM.
While submitting a fix, please include https://github.com/datalad/datalad/pull/5203/commits/255709b55f93430d64fe10822c589295d63bc34f in some form

**Comment by yarikoptic** [comment]
insofar I (and I believe @kyleam tried as well) to reproduce this issue locally.  I have tried with matched `git` version 2.29.2-1 and recent git-annex from debian, and set umask to 022... setting to 002 did the trick, so pushed 486121125

```show
$> git show 486121125
commit 48612112570c5445bc6b5fa903bfb834a748af88
Author: Yaroslav Halchenko <debian@onerussian.com>
Date:   Sun Dec 6 10:08:09 2020 -0500

    BF(TST): do not assume default umask settings to not inherit group writeability
    
    It might be incomplete or not a fix for https://github.com/datalad/datalad/issues/5206 but
    that is how I replicated the issue on my laptop

diff --git a/datalad/core/distributed/tests/test_clone.py b/datalad/core/distributed/tests/test_clone.py
index 1b87662ca..1ec14a842 100644
--- a/datalad/core/distributed/tests/test_clone.py
+++ b/datalad/core/distributed/tests/test_clone.py
@@ -362,9 +362,15 @@ def check_reckless(annex, src_path, top_path, sharedpath):
         raise SkipTest("Remainder of test needs proper filesystem permissions")
 
     if annex:
-        # the standard setup keeps the annex locks accessible to the user only
-        nok_((ds.pathobj / '.git' / 'annex' / 'index.lck').stat().st_mode \
-             & stat.S_IWGRP)
+        # umask might be such (e.g. 002) that group write permissions are inherited, so
+        # for the next test we should check if that is the case on some sample file
+        dltmp_path = ds.pathobj / '.git' / "dltmp"
+        dltmp_path.write_text('')
+        default_grp_write_perms = dltmp_path.stat().st_mode & stat.S_IWGRP
+        dltmp_path.unlink()
+        # the standard setup keeps the annex locks following umask inheritance
+        eq_((ds.pathobj / '.git' / 'annex' / 'index.lck').stat().st_mode \
+             & stat.S_IWGRP, default_grp_write_perms)
         # but we can set it up for group-shared access too
         sharedds = clone(
             src, sharedpath,
```
into #5203 and also reporting `umask` along with WTF (filed #5209 so we just have it reported as part of WTF)

**Comment by yarikoptic** [comment]
yep, testing in #5203 showed that umask on travis is 0002, thus the fix above is the correct one (and worked on travis), I will extract those commits and submit as a separate PR to close this issue

**Comment by kyleam** [comment]
gh-5212 has been merged.
