### ISSUE TITLE
test_gitrepo.test_protocols('https',) failing intermittently

### ISSUE THREAD

**Issue by kyleam** [datalad/datalad#5207]
In gh-5204, @adswa reported that `datalad.support.tests.test_gitrepo.test_protocols('https',)` failed.  Looking through recent builds, I spotted it in another one.

```
======================================================================
ERROR: datalad.support.tests.test_gitrepo.test_protocols('https',)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/travis/virtualenv/python3.5.6/lib/python3.5/site-packages/nose/case.py", line 198, in runTest
    self.test(*self.arg)
  File "/home/travis/virtualenv/python3.5.6/lib/python3.5/site-packages/datalad/tests/utils.py", line 177, in _wrap_skip_if_no_network
    return func(*args, **kwargs)
  File "/home/travis/virtualenv/python3.5.6/lib/python3.5/site-packages/datalad/tests/utils.py", line 750, in _wrap_with_tempfile
    return t(*(arg + (filename,)), **kw)
  File "/home/travis/virtualenv/python3.5.6/lib/python3.5/site-packages/datalad/support/tests/test_gitrepo.py", line 1580, in _test_protocols
    GitRepo.clone('%s://github.com/datalad-tester/testtt' % proto, destdir)
  File "/home/travis/virtualenv/python3.5.6/lib/python3.5/site-packages/datalad/support/gitrepo.py", line 1108, in clone
    protocol=GitProgress,
  File "/home/travis/virtualenv/python3.5.6/lib/python3.5/site-packages/datalad/cmd.py", line 509, in run
    **results,
datalad.support.exceptions.CommandError: CommandError: 'git clone --progress https://github.com/datalad-tester/testtt /tmp/datalad_temp__test_protocolspk4hbb4q' failed with exitcode 128 [err: 'Cloning into '/tmp/datalad_temp__test_protocolspk4hbb4q'...
error: RPC failed; curl 18 transfer closed with outstanding read data remaining
fatal: expected flush after ref listing']

```

https://travis-ci.com/github/datalad/datalad/jobs/454195238
https://travis-ci.com/github/datalad/datalad/jobs/454430836

**Comment by yarikoptic** [comment]
well, connection/rate-limiting/etc issues... I guess the only thing we could do is to handle some of those "known" issues worth retrying a few times... and we already have code there for it
```shell
            except CommandError as e:
                # log here but let caller decide what to do
                e_str = exc_str(e)
                # see https://github.com/datalad/datalad/issues/785
                if re.search("Request for .*aborted.*Unable to find", str(e),
                             re.DOTALL) \
                        and trial < ntries - 1:
                    lgr.info(
                        "Hit a known issue with Git (see GH#785). Trial #%d, "
                        "retrying",
                        trial)
                    continue
```
so we just need to enhance regex ;-) , or you is there some better way?

**Comment by kyleam** [comment]
It looks like this is very rare, so I don't think this failure is worth doing anything about or keeping an open issue for.
