### ISSUE TITLE
Windows: create-sibling is dysfunctional

### ISSUE THREAD

**Issue by adswa** [datalad/datalad#5211]
When taking a closer look at the test failure of ``datalad.distribution.tests.test_publish.test_since_empty_and_unsupported`` in #5210 I noticed that there are ``mkdir -p`` calls in the code base of "create sibling". Windows, unfortunately, has [its own mkdir command](https://docs.microsoft.com/de-de/windows-server/administration/windows-commands/mkdir) that does not take any flags. Consequently, when calling ``create sibling`` in a dataset, the command fails and leaves behind an empty ``-p/`` directory:

```
(base) C:\Users\mih\adinatests>datalad create blabla
[INFO] Creating a new annex repo at C:\Users\mih\adinatests\blabla
[INFO] Detected a filesystem without fifo support.
[INFO] Disabling ssh connection caching.
[INFO] Detected a crippled filesystem.
[INFO] Scanning for unlocked files (this may take some time)
[INFO] Entering an adjusted branch where files are unlocked as this filesystem does not support locked files.
[INFO] Switched to branch 'adjusted/master(unlocked)'
create(ok): C:\Users\mih\adinatests\blabla (dataset)

(base) C:\Users\mih\adinatests>cd blabla

(base) C:\Users\mih\adinatests\blabla>datalad create-sibling ../onebla
[INFO] Considering to create a target dataset C:\Users\mih\adinatests\blabla at C:\Users\mih\adinatests\onebla of localhost
[INFO] Fetching updates for Dataset("C:\Users\mih\adinatests\blabla")
[INFO] Adjusting remote git configuration
[INFO] Running post-update hooks in all created siblings
create_sibling(error): C:\Users\mih\adinatests\blabla (dataset) [failed to run post-update hook under remote path C:\Users\mih\adinatests\onebla (CommandError: 'cd "C:\Users\mih\adinatests\onebla\.git" && ( [ -x hooks/post-update ] && hooks/post-update || : )' failed with exitcode 1 [err: 'Der Befehl ":" ist entweder falsch geschrieben oder
konnte nicht gefunden werden.'] [cmd.py:run:514])]

(base) C:\Users\mih\adinatests\blabla>ls
-p
```

**Comment by adswa** [comment]
oh there is so much on windows that makes "create sibling" doomed to fail :(

**Comment by adswa** [comment]
There are several things that do not work on windows. One is this part of the code:
https://github.com/datalad/datalad/blob/d062f6f39315d6b82c287796e1c4c70ff4df6317/datalad/distribution/create_sibling.py#L815-L818


This one fails to recognize ``:`` as a command, and I can only suspect that the Anaconda prompt that @mih and I use on Windows does not know this syntax (bash can deal with it just fine, though).

I see two ways out, but I'm not sure how well suited they are, or if there are better ways:
- if I understand it correctly, `` || : `` is the same as `` || true`` - or is ``|| :`` better in some way? The anaconda prompt can deal with "true", so if equivalent, we could replace ``:`` with ``true``.
- I know that other external commands are sometimes explicitly given to ``sh`` in a runner (which deals fine with ``:``). Could that be a suitable solution?

**Comment by adswa** [comment]
If I fix ``mkdir -p`` and ``|| : `` to stuff that works under Windows publishing fails under Windows because of a rejected non-fast-forward push:

```
======================================================================
ERROR: datalad.distribution.tests.test_publish.test_since_empty_and_unsupported
----------------------------------------------------------------------
Traceback (most recent call last):
  File "C:\Users\datalad\miniconda3\lib\site-packages\nose\case.py", line 198, in runTest
    self.test(*self.arg)
  File "C:\Users\datalad\repos\datalad\datalad\tests\utils.py", line 750, in _wrap_with_tempfile
    return t(*(arg + (filename,)), **kw)
  File "C:\Users\datalad\repos\datalad\datalad\tests\utils.py", line 750, in _wrap_with_tempfile
    return t(*(arg + (filename,)), **kw)
  File "C:\Users\datalad\repos\datalad\datalad\distribution\tests\test_publish.py", line 110, in test_since_empty_and_unsupported
    source.publish(to='target1', since='')
  File "C:\Users\datalad\repos\datalad\datalad\distribution\dataset.py", line 503, in apply_func
    return f(**kwargs)
  File "C:\Users\datalad\repos\datalad\datalad\interface\utils.py", line 495, in eval_func
    return return_func(generator_func)(*args, **kwargs)
  File "C:\Users\datalad\repos\datalad\datalad\interface\utils.py", line 483, in return_func
    results = list(results)
  File "C:\Users\datalad\repos\datalad\datalad\interface\utils.py", line 468, in generator_func
    raise IncompleteResultsError(
datalad.support.exceptions.IncompleteResultsError: Command did not complete successfully. 1 failed:
[{'action': 'publish',
  'message': ('failed to push to %s: %s;%s',
              'target1',
              'refs/heads/dl-test-branch -> refs/heads/dl-test-branch '
              '[rejected] (non-fast-forward)',
              " pushed: ['e7bf765..cd9a622']"),
  'path': 'C:\\Users\\datalad\\AppData\\Local\\Temp\\datalad_temp_f4k74oba',
  'refds': 'C:\\Users\\datalad\\AppData\\Local\\Temp\\datalad_temp_f4k74oba',
  'status': 'error',
  'type': 'dataset'}]
```

I believe that this is due to a different commit history due to the separate, automatic "commit before entering adjusted branch" commits.

```
# source ds
(base) C:\Users\datalad\AppData\Local\Temp\datalad_temp_zyksjiox>git log --oneline
a65ef92 (HEAD -> dl-test-branch, refs/basis/adjusted/dl-test-branch(unlocked)) [DATALAD] new dataset
0dfdf7f commit before entering adjusted branch

# target ds:
(base) C:\Users\datalad\AppData\Local\Temp\datalad_temp_5az2x88g>git log --oneline
63e29f7 (HEAD -> dl-test-branch, refs/basis/adjusted/dl-test-branch(unlocked)) commit before entering adjusted branch
```

**Comment by yarikoptic** [comment]
> if I understand it correctly, || : is the same as || true - or is || : better in some way? 

I believe that the answer is "yes".  `:` is just a "no operation, which returns successfully", so pretty much what `true` does AFAIK.

**Comment by yarikoptic** [comment]
I guess #5214 fixed this issue but it was not closed:  it works fine for me ATM ("trust me - I am a doctor", copy/paste from VM failed for some reason)
