### ISSUE TITLE
`python -m datalad.install neurodebian-devel` crashes on master

### ISSUE THREAD

**Issue by mih** [datalad/datalad#5231]
```
(datalad3-dev) 1 mih@meiner /tmp % python -m datalad.install neurodebian-devel
Traceback (most recent call last):
  File "/usr/lib/python3.8/runpy.py", line 194, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "/usr/lib/python3.8/runpy.py", line 87, in _run_code
    exec(code, run_globals)
  File "/home/mih/hacking/datalad/git/datalad/install.py", line 432, in <module>
    main()
  File "/home/mih/hacking/datalad/git/datalad/install.py", line 102, in main
    installer.install_via_neurodebian_devel()
  File "/home/mih/hacking/datalad/git/datalad/install.py", line 196, in install_via_neurodebian_devel
    assert current_annex_version is not None, "Could not find current annex version"
AssertionError: Could not find current annex version

```

**Comment by jwodder** [comment]
The UX could certainly stand to be improved, but I believe this matches the behavior of `install-annex.sh`.  Both scripts appear to assume that the "neurodebian-devel" scheme is for use in an environment in which `git-annex-standalone` is already installed; the script thus tries to determine the version of the currently-installed version to see if it needs an update, and when there is no installed version, you get the error seen here.

@yarikoptic Should anything be done for this?

**Comment by yarikoptic** [comment]
if none installed, we should continue and install from neurodebian-devel.  I guess that bash script was under-tested ;)
