### ISSUE TITLE
SSH ControlPath too long

### ISSUE THREAD

**Issue by mih** [datalad/datalad#5232]
Discovered when playing with Appveyor: https://ci.appveyor.com/project/mih/appveyor-datalad/build/job/smhtn8ewrnjrskjy

```
======================================================================
ERROR: datalad.support.tests.test_gitrepo.test_GitRepo_ssh_push
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/Users/appveyor/venv3.8.3/lib/python3.8/site-packages/nose/case.py", line 198, in runTest
    self.test(*self.arg)
  File "/Users/appveyor/venv3.8.3/lib/python3.8/site-packages/datalad/tests/utils.py", line 200, in _wrap_skip_if_on_windows
    return func(*args, **kwargs)
  File "/Users/appveyor/venv3.8.3/lib/python3.8/site-packages/datalad/tests/utils.py", line 274, in _wrap_skip_ssh
    return func(*args, **kwargs)
  File "/Users/appveyor/venv3.8.3/lib/python3.8/site-packages/datalad/tests/utils.py", line 293, in _wrap_skip_nomultiplex_ssh
    return func(*args, **kwargs)
  File "/Users/appveyor/venv3.8.3/lib/python3.8/site-packages/datalad/tests/utils.py", line 755, in _wrap_with_tempfile
    return t(*(arg + (filename,)), **kw)
  File "/Users/appveyor/venv3.8.3/lib/python3.8/site-packages/datalad/tests/utils.py", line 755, in _wrap_with_tempfile
    return t(*(arg + (filename,)), **kw)
  File "/Users/appveyor/venv3.8.3/lib/python3.8/site-packages/datalad/support/tests/test_gitrepo.py", line 690, in test_GitRepo_ssh_push
    pushed = list(repo.push(remote="ssh-remote", refspec="ssh-test"))
  File "/Users/appveyor/venv3.8.3/lib/python3.8/site-packages/datalad/support/gitrepo.py", line 2560, in push
    return list(
  File "/Users/appveyor/venv3.8.3/lib/python3.8/site-packages/datalad/support/gitrepo.py", line 2571, in push_
    yield from self._fetch_push_helper(
  File "/Users/appveyor/venv3.8.3/lib/python3.8/site-packages/datalad/support/gitrepo.py", line 2669, in _fetch_push_helper
    out = self._git_runner.run(
  File "/Users/appveyor/venv3.8.3/lib/python3.8/site-packages/datalad/cmd.py", line 518, in run
    raise CommandError(
datalad.support.exceptions.CommandError: CommandError: 'git push --progress --porcelain ssh-remote ssh-test' failed with exitcode 128 under /private/var/folders/5s/g225f6nd6jl4g8tshbh1ltk40000gn/T/datalad_temp_test_GitRepo_ssh_pushxagk__s8 [err: 'ControlPath too long ('/private/var/folders/5s/g225f6nd6jl4g8tshbh1ltk40000gn/T/datalad_temp_9fkrct8p/Library/Caches/datalad/sockets/e7d0c91d' >= 104 bytes)
ConnectionOpenFailedError: 'ssh -fN -o ControlMaster=auto -o ControlPersist=15m -o ControlPath=/private/var/folders/5s/g225f6nd6jl4g8tshbh1ltk40000gn/T/datalad_temp_9fkrct8p/Library/Caches/datalad/sockets/e7d0c91d datalad-test' failed with exitcode 255 [Failed to open SSH connection (could not start ControlMaster process)]
fatal: Could not read from remote repository.
Please make sure you have the correct access rights
and the repository exists.']
```

**Comment by yarikoptic** [comment]
`/private/var/folders/5s/g225f6nd6jl4g8tshbh1ltk40000gn/T/datalad_temp_9fkrct8p/Library/Caches/datalad/sockets/e7d0c91d`

so we are creating them in cache directory...   
```
datalad/support/sshconnector.py:            Path(cfg.obtain('datalad.locations.cache')) / 'sockets'
```
so you could tune caches to reside somewhere in `/tmp/` on CIs.  We might (or not) want to have a dedicated config variable for a path of control paths, and in case if not defined -- resort to cache path.

**Comment by mih** [comment]
Ping https://github.com/datalad/datalad/issues/4198 https://github.com/datalad/datalad/issues/4075

**Comment by mih** [comment]
Closing this, as we now have the ability to place the sockets in a different path.
