### ISSUE TITLE
test_bare_git_version_{1,2} fails on datalad/git-annex  maint (and may be others)

### ISSUE THREAD

**Issue by yarikoptic** [datalad/datalad#5253]
```
======================================================================
ERROR: datalad.distributed.tests.test_ria_git_remote.test_bare_git_version_1(None,)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/opt/hostedtoolcache/Python/3.7.9/x64/lib/python3.7/site-packages/nose/case.py", line 198, in runTest
    self.test(*self.arg)
  File "/opt/hostedtoolcache/Python/3.7.9/x64/lib/python3.7/site-packages/datalad/tests/utils.py", line 750, in _wrap_with_tempfile
    return t(*(arg + (filename,)), **kw)
  File "/opt/hostedtoolcache/Python/3.7.9/x64/lib/python3.7/site-packages/datalad/tests/utils.py", line 750, in _wrap_with_tempfile
    return t(*(arg + (filename,)), **kw)
  File "/opt/hostedtoolcache/Python/3.7.9/x64/lib/python3.7/site-packages/datalad/distributed/tests/test_ria_git_remote.py", line 92, in _test_bare_git_version_1
    ds.repo.enable_remote('bare-git')
  File "/opt/hostedtoolcache/Python/3.7.9/x64/lib/python3.7/site-packages/datalad/support/annexrepo.py", line 1851, in enable_remote
    raise e
  File "/opt/hostedtoolcache/Python/3.7.9/x64/lib/python3.7/site-packages/datalad/support/annexrepo.py", line 1844, in enable_remote
    env=env)
  File "/opt/hostedtoolcache/Python/3.7.9/x64/lib/python3.7/site-packages/datalad/support/annexrepo.py", line 1104, in _run_annex_command
    **kwargs)
  File "/opt/hostedtoolcache/Python/3.7.9/x64/lib/python3.7/site-packages/datalad/cmd.py", line 144, in run_gitcommand_on_file_list_chunks
    results.append(func(cmd, *args, **kwargs))
  File "/opt/hostedtoolcache/Python/3.7.9/x64/lib/python3.7/site-packages/datalad/cmd.py", line 513, in run
    **results,
datalad.support.exceptions.CommandError: CommandError: 'git annex enableremote -c annex.dotfiles=true -c annex.retry=3 bare-git' failed with exitcode 1 under /tmp/datalad_temp__test_bare_git_version_15m7abgnw [out: 'enableremote bare-git 
failed'] [err: 'remote bare-git:This repository is not initialized for use by git-annex, but ../datalad_temp__test_bare_git_version_1n42gm4dp/1c5/75c64-67b2-4435-bd8b-52982b6e0663/annex/objects/ exists, which indicates this repository was used by git-annex before, and may have lost its annex.uuid and annex.version configs. Either set back missing configs, or run git-annex init to initialize with a new uuid.
  remote bare-git:This repository is not initialized for use by git-annex, but ../datalad_temp__test_bare_git_version_1n42gm4dp/1c5/75c64-67b2-4435-bd8b-52982b6e0663/annex/objects/ exists, which indicates this repository was used by git-annex before, and may have lost its annex.uuid and annex.version configs. Either set back missing configs, or run git-annex init to initialize with a new uuid.
git-annex: enableremote: 1 failed']
-------------------- >> begin captured logging << --------------------
asyncio: DEBUG: Using selector: EpollSelector
asyncio: DEBUG: Using selector: EpollSelector
asyncio: DEBUG: Using selector: EpollSelector
asyncio: DEBUG: Using selector: EpollSelector
--------------------- >> end captured logging << ---------------------

======================================================================
ERROR: datalad.distributed.tests.test_ria_git_remote.test_bare_git_version_2(None,)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/opt/hostedtoolcache/Python/3.7.9/x64/lib/python3.7/site-packages/nose/case.py", line 198, in runTest
    self.test(*self.arg)
  File "/opt/hostedtoolcache/Python/3.7.9/x64/lib/python3.7/site-packages/datalad/tests/utils.py", line 750, in _wrap_with_tempfile
    return t(*(arg + (filename,)), **kw)
  File "/opt/hostedtoolcache/Python/3.7.9/x64/lib/python3.7/site-packages/datalad/tests/utils.py", line 750, in _wrap_with_tempfile
    return t(*(arg + (filename,)), **kw)
  File "/opt/hostedtoolcache/Python/3.7.9/x64/lib/python3.7/site-packages/datalad/distributed/tests/test_ria_git_remote.py", line 197, in _test_bare_git_version_2
    ds.repo.enable_remote('bare-git')
  File "/opt/hostedtoolcache/Python/3.7.9/x64/lib/python3.7/site-packages/datalad/support/annexrepo.py", line 1851, in enable_remote
    raise e
  File "/opt/hostedtoolcache/Python/3.7.9/x64/lib/python3.7/site-packages/datalad/support/annexrepo.py", line 1844, in enable_remote
    env=env)
  File "/opt/hostedtoolcache/Python/3.7.9/x64/lib/python3.7/site-packages/datalad/support/annexrepo.py", line 1104, in _run_annex_command
    **kwargs)
  File "/opt/hostedtoolcache/Python/3.7.9/x64/lib/python3.7/site-packages/datalad/cmd.py", line 144, in run_gitcommand_on_file_list_chunks
    results.append(func(cmd, *args, **kwargs))
  File "/opt/hostedtoolcache/Python/3.7.9/x64/lib/python3.7/site-packages/datalad/cmd.py", line 513, in run
    **results,
datalad.support.exceptions.CommandError: CommandError: 'git annex enableremote -c annex.dotfiles=true -c annex.retry=3 bare-git' failed with exitcode 1 under /tmp/datalad_temp__test_bare_git_version_2s6zirwhe [out: 'enableremote bare-git 
failed'] [err: 'remote bare-git:This repository is not initialized for use by git-annex, but ../datalad_temp__test_bare_git_version_29wdvdgx9/cb3/fd246-0097-43d4-b135-f2f6b11e0c15/annex/objects/ exists, which indicates this repository was used by git-annex before, and may have lost its annex.uuid and annex.version configs. Either set back missing configs, or run git-annex init to initialize with a new uuid.
  remote bare-git:This repository is not initialized for use by git-annex, but ../datalad_temp__test_bare_git_version_29wdvdgx9/cb3/fd246-0097-43d4-b135-f2f6b11e0c15/annex/objects/ exists, which indicates this repository was used by git-annex before, and may have lost its annex.uuid and annex.version configs. Either set back missing configs, or run git-annex init to initialize with a new uuid.
git-annex: enableremote: 1 failed']
-------------------- >> begin captured logging << --------------------
asyncio: DEBUG: Using selector: EpollSelector
asyncio: DEBUG: Using selector: EpollSelector
asyncio: DEBUG: Using selector: EpollSelector
asyncio: DEBUG: Using selector: EpollSelector
--------------------- >> end captured logging << ---------------------

----------------------------------------------------------------------
Ran 1193 tests in 4411.102s

FAILED (SKIP=88, errors=2)
```

@bpoldrack could you have a look?

**Comment by kyleam** [comment]
I can trigger these locally with the current git-annex master (8.20201127-164-gc2a5f3c44).  While I didn't confirm, these almost certainly come from 8.20201127-132-g75acf5f44 (improve some edge cases around partial initialization, 2020-12-14).  I haven't looked closer yet.

**Comment by yarikoptic** [comment]
attn @joeyh just in case ;)

**Comment by kyleam** [comment]
The bare git repos in ria store layout are conflicting with this new check from git-annex:

```
  * Avoid autoinit when a repo does not have annex.version or annex.uuid
    set, but has a git-annex objects directory, suggesting it was used
    by git-annex before.
```

`ria_utils.create_ds_in_store` sets up an "annex/objects" directory.  Just to confirm, these tests pass with this change:

```diff
diff --git a/datalad/customremotes/ria_utils.py b/datalad/customremotes/ria_utils.py
index 647b99bfb5..d0a525453d 100644
--- a/datalad/customremotes/ria_utils.py
+++ b/datalad/customremotes/ria_utils.py
@@ -202,5 +202,5 @@ def create_ds_in_store(io, base_path, dsid, obj_version, store_version):
                              "target: {}".format(existing_version))
 
     io.mkdir(archive_dir)
-    io.mkdir(dsobj_dir)
+    # io.mkdir(dsobj_dir)
     io.write_file(version_file, obj_version)
```

I'm trying to assess whether this scenario (objects directory with no annex.uuid or annex.version) might just be an artificial aspect of the test, rather than a real concern with the ora special remote.  Given we don't see more ora/ria-related test failures, I'm guessing it might be the former, but it'd be good to hear from @bpoldrack or @mih.

**Comment by mih** [comment]
Is this maybe connected to #5186? It attempts to use it as an annex, although it should not?

**Comment by kyleam** [comment]
> Is this maybe connected to #5186?

I could be missing something, but I don't think it's directly related.  `test_bare_git_version_{1,2}` intentionally use git-annex with the git remote.

**Comment by kyleam** [comment]
Test-specific solution proposed in gh-5254.

**Comment by mih** [comment]
> > Is this maybe connected to #5186?
> 
> I could be missing something, but I don't think it's directly related. `test_bare_git_version_{1,2}` intentionally use git-annex with the git remote.

True. Had another look after some sleep and your are correct. This would then also not be an intended use case, but an artifical complicated introduced for testing purposed. Correct @bpoldrack ?

**Comment by bpoldrack** [comment]
Correct. It simply has been a convenient way for the test to use the in-store repo directly as well as via special remote. That `enableremote` wouldn't be necessary in real world.
As a sidenote: While I want RIA stores to be able to hold simple, non-ORA, standard annexes, even then it's one or another - special remote XOR annex.
So - all good in theory, looking into @kyleam 's solution.

**Comment by bpoldrack** [comment]
FTR: Looked through `clone` to see whether we need to change handling of ephemeral clones from RIA stores. I think the only issue with that is the combination with #5186, which I'll push a fix for today anyway.
