### ISSUE TITLE
fatal: repository 'https://github.com/OpenNeuroDatasets/ds002946.git/analysis/' not found

### ISSUE THREAD

**Issue by soichih** [datalad/datalad#5263]
Hello! I am using datalad 0.13.6 on Ubuntu 18.04.5 server. Today I am trying to troubleshoot the following error message.

```
$ datalad install -r https://github.com/OpenNeuroDatasets/ds002946.git
[INFO] Installing Dataset(/mnt/datalad/OpenNeuroDatasets/ds002946) to get /mnt/datalad/OpenNeuroDatasets/ds002946 recursively 
[INFO] Cloning dataset to Dataset(/mnt/datalad/OpenNeuroDatasets/ds002946/analysis) 
[INFO] Attempting to clone from https://github.com/OpenNeuroDatasets/ds002946.git/analysis to /mnt/datalad/OpenNeuroDatasets/ds002946/analysis 
[INFO] Attempting to clone from https://github.com/OpenNeuroDatasets/ds002946.git/analysis/.git to /mnt/datalad/OpenNeuroDatasets/ds002946/analysis 
[INFO] Completed clone attempts for Dataset(/mnt/datalad/OpenNeuroDatasets/ds002946/analysis) 
[ERROR] Failed to clone from any candidate source URL. Encountered errors per each url were:
| - https://github.com/OpenNeuroDatasets/ds002946.git/analysis
  CommandError: 'git clone --progress https://github.com/OpenNeuroDatasets/ds002946.git/analysis /mnt/datalad/OpenNeuroDatasets/ds002946/analysis' failed with exitcode 128 [err: 'Cloning into '/mnt/datalad/OpenNeuroDatasets/ds002946/analysis'...
remote: Not Found
fatal: repository 'https://github.com/OpenNeuroDatasets/ds002946.git/analysis/' not found']
- https://github.com/OpenNeuroDatasets/ds002946.git/analysis/.git
  CommandError: 'git clone --progress https://github.com/OpenNeuroDatasets/ds002946.git/analysis/.git /mnt/datalad/OpenNeuroDatasets/ds002946/analysis' failed with exitcode 128 [err: 'Cloning into '/mnt/datalad/OpenNeuroDatasets/ds002946/analysis'...
remote: Not Found
fatal: repository 'https://github.com/OpenNeuroDatasets/ds002946.git/analysis/.git/' not found'] [install(/mnt/datalad/OpenNeuroDatasets/ds002946/analysis)] 
{ Error: Command failed: datalad install -r https://github.com/OpenNeuroDatasets/ds002946.git
[INFO] Installing Dataset(/mnt/datalad/OpenNeuroDatasets/ds002946) to get /mnt/datalad/OpenNeuroDatasets/ds002946 recursively 
[INFO] Cloning dataset to Dataset(/mnt/datalad/OpenNeuroDatasets/ds002946/analysis) 
[INFO] Attempting to clone from https://github.com/OpenNeuroDatasets/ds002946.git/analysis to /mnt/datalad/OpenNeuroDatasets/ds002946/analysis 
[INFO] Attempting to clone from https://github.com/OpenNeuroDatasets/ds002946.git/analysis/.git to /mnt/datalad/OpenNeuroDatasets/ds002946/analysis 
[INFO] Completed clone attempts for Dataset(/mnt/datalad/OpenNeuroDatasets/ds002946/analysis) 
[ERROR] Failed to clone from any candidate source URL. Encountered errors per each url were:
| - https://github.com/OpenNeuroDatasets/ds002946.git/analysis
  CommandError: 'git clone --progress https://github.com/OpenNeuroDatasets/ds002946.git/analysis /mnt/datalad/OpenNeuroDatasets/ds002946/analysis' failed with exitcode 128 [err: 'Cloning into '/mnt/datalad/OpenNeuroDatasets/ds002946/analysis'...
remote: Not Found
fatal: repository 'https://github.com/OpenNeuroDatasets/ds002946.git/analysis/' not found']
- https://github.com/OpenNeuroDatasets/ds002946.git/analysis/.git
  CommandError: 'git clone --progress https://github.com/OpenNeuroDatasets/ds002946.git/analysis/.git /mnt/datalad/OpenNeuroDatasets/ds002946/analysis' failed with exitcode 128 [err: 'Cloning into '/mnt/datalad/OpenNeuroDatasets/ds002946/analysis'...
remote: Not Found
fatal: repository 'https://github.com/OpenNeuroDatasets/ds002946.git/analysis/.git/' not found'] [install(/mnt/datalad/OpenNeuroDatasets/ds002946/analysis)] 

    at checkExecSyncError (child_process.js:601:13)
    at Object.execSync (child_process.js:641:13)
    at repos.forEach.repo (/mnt/datalad/OpenNeuroDatasets/clone.js:60:8)
    at Array.forEach (<anonymous>)
    at clone_repos (/mnt/datalad/OpenNeuroDatasets/clone.js:22:9)
    at <anonymous>
    at process._tickCallback (internal/process/next_tick.js:188:7)
  error: null,
  cmd: 'datalad install -r https://github.com/OpenNeuroDatasets/ds002946.git',
  file: '/bin/sh',
  args: 
   [ '/bin/sh',
     '-c',
     'datalad install -r https://github.com/OpenNeuroDatasets/ds002946.git' ],
  options: 
   { shell: true,
     file: '/bin/sh',
     args: 
      [ '/bin/sh',
        '-c',
        'datalad install -r https://github.com/OpenNeuroDatasets/ds002946.git' ],
     envPairs: 
      [ 'LS_COLORS=rs=0:di=01;34:ln=01;36:mh=00:pi=40;33:so=01;35:do=01;35:bd=40;33;01:cd=40;33;01:or=40;31;01:mi=00:su=37;41:sg=30;43:ca=30;41:tw=30;42:ow=34;42:st=37;44:ex=01;32:*.tar=01;31:*.tgz=01;31:*.arc=01;31:*.arj=01;31:*.taz=01;31:*.lha=01;31:*.lz4=01;31:*.lzh=01;31:*.lzma=01;31:*.tlz=01;31:*.txz=01;31:*.tzo=01;31:*.t7z=01;31:*.zip=01;31:*.z=01;31:*.Z=01;31:*.dz=01;31:*.gz=01;31:*.lrz=01;31:*.lz=01;31:*.lzo=01;31:*.xz=01;31:*.zst=01;31:*.tzst=01;31:*.bz2=01;31:*.bz=01;31:*.tbz=01;31:*.tbz2=01;31:*.tz=01;31:*.deb=01;31:*.rpm=01;31:*.jar=01;31:*.war=01;31:*.ear=01;31:*.sar=01;31:*.rar=01;31:*.alz=01;31:*.ace=01;31:*.zoo=01;31:*.cpio=01;31:*.7z=01;31:*.rz=01;31:*.cab=01;31:*.wim=01;31:*.swm=01;31:*.dwm=01;31:*.esd=01;31:*.jpg=01;35:*.jpeg=01;35:*.mjpg=01;35:*.mjpeg=01;35:*.gif=01;35:*.bmp=01;35:*.pbm=01;35:*.pgm=01;35:*.ppm=01;35:*.tga=01;35:*.xbm=01;35:*.xpm=01;35:*.tif=01;35:*.tiff=01;35:*.png=01;35:*.svg=01;35:*.svgz=01;35:*.mng=01;35:*.pcx=01;35:*.mov=01;35:*.mpg=01;35:*.mpeg=01;35:*.m2v=01;35:*.mkv=01;35:*.webm=01;35:*.ogm=01;35:*.mp4=01;35:*.m4v=01;35:*.mp4v=01;35:*.vob=01;35:*.qt=01;35:*.nuv=01;35:*.wmv=01;35:*.asf=01;35:*.rm=01;35:*.rmvb=01;35:*.flc=01;35:*.avi=01;35:*.fli=01;35:*.flv=01;35:*.gl=01;35:*.dl=01;35:*.xcf=01;35:*.xwd=01;35:*.yuv=01;35:*.cgm=01;35:*.emf=01;35:*.ogv=01;35:*.ogx=01;35:*.aac=00;36:*.au=00;36:*.flac=00;36:*.m4a=00;36:*.mid=00;36:*.midi=00;36:*.mka=00;36:*.mp3=00;36:*.mpc=00;36:*.ogg=00;36:*.ra=00;36:*.wav=00;36:*.oga=00;36:*.opus=00;36:*.spx=00;36:*.xspf=00;36:',
        'LESSCLOSE=/usr/bin/lesspipe %s %s',
        'LANG=C.UTF-8',
        'GIT_DISCOVERY_ACROSS_FILESYSTEM=1',
        'SINGULARITY_DOCKER_USERNAME=brainlifesing',
        'S_COLORS=auto',
        'USER=brlife',
        'PWD=/mnt/datalad/OpenNeuroDatasets',
        'HOME=/home/brlife',
        'XDG_DATA_DIRS=/usr/local/share:/usr/share:/var/lib/snapd/desktop',
        'MAIL=/var/mail/brlife',
        'SHELL=/bin/bash',
        'TERM=xterm-256color',
        'SHLVL=1',
        'SINGULARITY_DOCKER_PASSWORD=gobrainlife',
        'LOGNAME=brlife',
        'PATH=/home/brlife/abcd-spec/hooks/direct:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/usr/games:/usr/local/games:/snap/bin',
        'LESSOPEN=| /usr/bin/lesspipe %s',
        'OLDPWD=/mnt/datalad',
        '_=./clone.js' ],
     killSignal: undefined,
     stdio: [ [Object], [Object], [Object] ] },
  envPairs: 
   [ 'LS_COLORS=rs=0:di=01;34:ln=01;36:mh=00:pi=40;33:so=01;35:do=01;35:bd=40;33;01:cd=40;33;01:or=40;31;01:mi=00:su=37;41:sg=30;43:ca=30;41:tw=30;42:ow=34;42:st=37;44:ex=01;32:*.tar=01;31:*.tgz=01;31:*.arc=01;31:*.arj=01;31:*.taz=01;31:*.lha=01;31:*.lz4=01;31:*.lzh=01;31:*.lzma=01;31:*.tlz=01;31:*.txz=01;31:*.tzo=01;31:*.t7z=01;31:*.zip=01;31:*.z=01;31:*.Z=01;31:*.dz=01;31:*.gz=01;31:*.lrz=01;31:*.lz=01;31:*.lzo=01;31:*.xz=01;31:*.zst=01;31:*.tzst=01;31:*.bz2=01;31:*.bz=01;31:*.tbz=01;31:*.tbz2=01;31:*.tz=01;31:*.deb=01;31:*.rpm=01;31:*.jar=01;31:*.war=01;31:*.ear=01;31:*.sar=01;31:*.rar=01;31:*.alz=01;31:*.ace=01;31:*.zoo=01;31:*.cpio=01;31:*.7z=01;31:*.rz=01;31:*.cab=01;31:*.wim=01;31:*.swm=01;31:*.dwm=01;31:*.esd=01;31:*.jpg=01;35:*.jpeg=01;35:*.mjpg=01;35:*.mjpeg=01;35:*.gif=01;35:*.bmp=01;35:*.pbm=01;35:*.pgm=01;35:*.ppm=01;35:*.tga=01;35:*.xbm=01;35:*.xpm=01;35:*.tif=01;35:*.tiff=01;35:*.png=01;35:*.svg=01;35:*.svgz=01;35:*.mng=01;35:*.pcx=01;35:*.mov=01;35:*.mpg=01;35:*.mpeg=01;35:*.m2v=01;35:*.mkv=01;35:*.webm=01;35:*.ogm=01;35:*.mp4=01;35:*.m4v=01;35:*.mp4v=01;35:*.vob=01;35:*.qt=01;35:*.nuv=01;35:*.wmv=01;35:*.asf=01;35:*.rm=01;35:*.rmvb=01;35:*.flc=01;35:*.avi=01;35:*.fli=01;35:*.flv=01;35:*.gl=01;35:*.dl=01;35:*.xcf=01;35:*.xwd=01;35:*.yuv=01;35:*.cgm=01;35:*.emf=01;35:*.ogv=01;35:*.ogx=01;35:*.aac=00;36:*.au=00;36:*.flac=00;36:*.m4a=00;36:*.mid=00;36:*.midi=00;36:*.mka=00;36:*.mp3=00;36:*.mpc=00;36:*.ogg=00;36:*.ra=00;36:*.wav=00;36:*.oga=00;36:*.opus=00;36:*.spx=00;36:*.xspf=00;36:',
     'LESSCLOSE=/usr/bin/lesspipe %s %s',
     'LANG=C.UTF-8',
     'GIT_DISCOVERY_ACROSS_FILESYSTEM=1',
     'SINGULARITY_DOCKER_USERNAME=brainlifesing',
     'S_COLORS=auto',
     'USER=brlife',
     'PWD=/mnt/datalad/OpenNeuroDatasets',
     'HOME=/home/brlife',
     'XDG_DATA_DIRS=/usr/local/share:/usr/share:/var/lib/snapd/desktop',
     'MAIL=/var/mail/brlife',
     'SHELL=/bin/bash',
     'TERM=xterm-256color',
     'SHLVL=1',
     'SINGULARITY_DOCKER_PASSWORD=gobrainlife',
     'LOGNAME=brlife',
     'PATH=/home/brlife/abcd-spec/hooks/direct:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/usr/games:/usr/local/games:/snap/bin',
     'LESSOPEN=| /usr/bin/lesspipe %s',
     'OLDPWD=/mnt/datalad',
     '_=./clone.js' ],
  stderr: <Buffer 5b 49 4e 46 4f 5d 20 49 6e 73 74 61 6c 6c 69 6e 67 20 44 61 74 61 73 65 74 28 2f 6d 6e 74 2f 64 61 74 61 6c 61 64 2f 4f 70 65 6e 4e 65 75 72 6f 44 61 ... >,
  stdout: <Buffer 69 6e 73 74 61 6c 6c 28 65 72 72 6f 72 29 3a 20 2f 6d 6e 74 2f 64 61 74 61 6c 61 64 2f 4f 70 65 6e 4e 65 75 72 6f 44 61 74 61 73 65 74 73 2f 64 73 30 ... >,
  pid: 15066,
  output: 
   [ null,
     <Buffer 69 6e 73 74 61 6c 6c 28 65 72 72 6f 72 29 3a 20 2f 6d 6e 74 2f 64 61 74 61 6c 61 64 2f 4f 70 65 6e 4e 65 75 72 6f 44 61 74 61 73 65 74 73 2f 64 73 30 ... >,
     <Buffer 5b 49 4e 46 4f 5d 20 49 6e 73 74 61 6c 6c 69 6e 67 20 44 61 74 61 73 65 74 28 2f 6d 6e 74 2f 64 61 74 61 6c 61 64 2f 4f 70 65 6e 4e 65 75 72 6f 44 61 ... > ],
  signal: null,
  status: 1 }

```

It looks like ./analysis is a broken link of some kind.. but I don't know if this is an OpenNeuro issue, or github issue, or datalad issue. If could you assist me on who to contact, I'd greatly apprecaite it!

**Comment by yarikoptic** [comment]
I guess just don't do `-r` on any of  OpenNeuroDatasets since AFAIK binding derivatives etc was not yet worked out.  @effigies could correct me if I am wrong.  IMHO it is also a bit broken (and worthwhile to possibly forward it against openneuro) since it also includes another dataset as subdataset:
```
$> cd ds002946 
CHANGES    dataset_description.json  participants.json  sample/        sub-glen/
analysis/  ds002912/                 participants.tsv   sub-chiba750/

$> git submodule
-50fe7fdabbe5f12d530d12cdd640d915d98234a3 analysis
-592064f0dfd8227e399944437a226367a58a8531 ds002912

$> cat .gitmodules 
[submodule "analysis"]
	path = analysis
	url = ./analysis
[submodule "ds002912"]
	path = ds002912
	url = https://github.com/OpenNeuroDatasets/ds002912.git
	datalad-id = 2126e97e-b4f0-11ea-91db-4a4a685bb0cd
```

both were added as part of the 
```
$> git show --stat 8e4b8fde3ff44f23200c01dae2d590c898c595cd
commit 8e4b8fde3ff44f23200c01dae2d590c898c595cd (HEAD -> master, tag: 1.0.0, origin/master, origin/HEAD)
Author: Git Worker <git@openneuro.org>
Date:   Fri Jun 26 19:49:21 2020 +0000

    [DATALAD] Recorded changes

 analysis | 1 +
 ds002912 | 1 +
```

both have the same name but different authors:
```
$> cat ds002912/dataset_description.json 
{
    "Name": "_test_julien",
    "BIDSVersion": "1.2.0",
    "Authors": [
        "Julien Cohen-Adad"
    ],
    "DatasetDOI": "10.18112/openneuro.ds002912.v1.0.2",
    "License": "CC0",
    "Acknowledgements": "openneuro"
}%                                                                                                                      1 46509.....................................:Wed 23 Dec 2020 07:46:36 PM EST:.
(git-annex)lena:/tmp/ds002946[master]
$> cat dataset_description.json 
{
    "Name": "_test_julien",
    "BIDSVersion": "1.2.0",
    "Authors": [
        "Django Reinhardt"
    ],
    "DatasetDOI": "10.18112/openneuro.ds002946.v1.0.0",
    "License": "CC0",
    "Acknowledgements": "openneuro"
}%               
```

so it seems that something odd happened on openneuro side

**Comment by effigies** [comment]
I don't think we sanitize incoming datasets to prevent inaccessible submodules. I'm not sure what we should do if someone only has a local URL for a subdataset.

**Comment by adswa** [comment]
I'm closing this issue as it seems that there is nothing we can do on our end about this dataset, apart from maybe erroring out less ugly, but as far as I know, the current state of things is at least slightly more pretty. Please reopen if I am mistaken in closing this.
