### ISSUE TITLE
test_nested_pushclone_cycle_allplatforms fail on windows

### ISSUE THREAD

**Issue by yarikoptic** [datalad/datalad#5271]
https://github.com/datalad/git-annex/runs/1638513807?check_suite_focus=true#step:21:1544

```
======================================================================
FAIL: datalad.core.distributed.tests.test_push.test_nested_pushclone_cycle_allplatforms
----------------------------------------------------------------------
Traceback (most recent call last):
  File "C:\hostedtoolcache\windows\Python\3.7.9\x64\lib\site-packages\nose\case.py", line 198, in runTest
    self.test(*self.arg)
  File "C:\hostedtoolcache\windows\Python\3.7.9\x64\lib\site-packages\datalad\tests\utils.py", line 757, in _wrap_with_tempfile
    return t(*(arg + (filename,)), **kw)
  File "C:\hostedtoolcache\windows\Python\3.7.9\x64\lib\site-packages\datalad\tests\utils.py", line 757, in _wrap_with_tempfile
    return t(*(arg + (filename,)), **kw)
  File "C:\hostedtoolcache\windows\Python\3.7.9\x64\lib\site-packages\datalad\tests\utils.py", line 757, in _wrap_with_tempfile
    return t(*(arg + (filename,)), **kw)
  File "C:\hostedtoolcache\windows\Python\3.7.9\x64\lib\site-packages\datalad\core\distributed\tests\test_push.py", line 917, in test_nested_pushclone_cycle_allplatforms
    eq_(set(r.get_branches()), set([orig_sub_corr_branch, 'git-annex']))
AssertionError: {'git-annex', 'adjusted/dl-test-branch(unlocked)', 'dl-test-branch'} != {'git-annex', 'dl-test-branch'}
```

**Comment by mih** [comment]
Does not show in #5303 (anymore): https://ci.appveyor.com/project/mih/datalad/build/job/o0yixndrca6jh0pu#L587

**Comment by yarikoptic** [comment]
FTR: blind verdict was made that it is likely python `<3.8` and that we do not care about those on windows.  I am boosting python in datalad/git-annex to 3.8 -- will close for now, and will reopen if resurfaces
