### ISSUE TITLE
AnnexRepo.add_submodule: unused and broken for adjusted mode repos

### ISSUE THREAD

**Issue by yarikoptic** [datalad/datalad#5272]
https://github.com/datalad/git-annex/runs/1638513807?check_suite_focus=true#step:21:1469

```
======================================================================
ERROR: datalad.support.tests.test_annexrepo.test_AnnexRepo_add_submodule
----------------------------------------------------------------------
Traceback (most recent call last):
  File "C:\hostedtoolcache\windows\Python\3.7.9\x64\lib\site-packages\nose\case.py", line 198, in runTest
    self.test(*self.arg)
  File "C:\hostedtoolcache\windows\Python\3.7.9\x64\lib\site-packages\datalad\tests\utils.py", line 1092, in _wrap_with_testrepos
    t(*(arg + (uri,)), **kw)
  File "C:\hostedtoolcache\windows\Python\3.7.9\x64\lib\site-packages\datalad\tests\utils.py", line 757, in _wrap_with_tempfile
    return t(*(arg + (filename,)), **kw)
  File "C:\hostedtoolcache\windows\Python\3.7.9\x64\lib\site-packages\datalad\support\tests\test_annexrepo.py", line 1756, in test_AnnexRepo_add_submodule
    assert_repo_status(top_repo, annex=True)
  File "C:\hostedtoolcache\windows\Python\3.7.9\x64\lib\site-packages\datalad\tests\utils.py", line 1664, in assert_repo_status
    status = r.status(untracked=untracked_mode)
  File "C:\hostedtoolcache\windows\Python\3.7.9\x64\lib\site-packages\datalad\support\gitrepo.py", line 3611, in status
    eval_submodule_state=eval_submodule_state)
  File "C:\hostedtoolcache\windows\Python\3.7.9\x64\lib\site-packages\datalad\support\gitrepo.py", line 3800, in diffstatus
    subrepo_commit = subrepo.get_hexsha(subrepo.get_corresponding_branch())
  File "C:\hostedtoolcache\windows\Python\3.7.9\x64\lib\site-packages\datalad\support\gitrepo.py", line 1856, in get_hexsha
    raise ValueError("Unknown commit identifier: %s" % commitish)
ValueError: Unknown commit identifier: dl-test-branch
```

**Comment by mih** [comment]
As part of my work on appveyor, I have disabled this test on windows. `AnnexRepo.add_submodule()` has never worked properly on Windows, and is not needed for any normal functioning of DataLad.

I did propose to kill it completely in full in the past. But it certainly should not hold up 0.14.

**Comment by yarikoptic** [comment]
ok, I will submit a total skip on windows for this test. want to get datalad/git-annex green

**Comment by mih** [comment]
FTR: #5303 will change that again. The method is broken with any adjusted branch repo (hence this is the skip condition). The test is just not written in a way that it would discover the non-portable submodule addition.

A proper fix is likely to raise `NotImplementedError` whenever this method runs in an adjusted-mode repo.

But as a reminder: This method is not used outside the tests. It should be removed.

**Comment by mih** [comment]
Such a function no longer exists in datalad-core.
