### ISSUE TITLE
RIA test fails on MacOS

### ISSUE THREAD

**Issue by mih** [datalad/datalad#5293]
```
======================================================================
1387FAIL: datalad.distributed.tests.test_ria_basics.test_remote_layout('datalad-test',)
1388----------------------------------------------------------------------
1389Traceback (most recent call last):
1390  File "/Users/appveyor/venv3.8.6/lib/python3.8/site-packages/nose/case.py", line 198, in runTest
1391    self.test(*self.arg)
1392  File "/Users/appveyor/venv3.8.6/lib/python3.8/site-packages/datalad/tests/utils.py", line 291, in _wrap_skip_ssh
1393    return func(*args, **kwargs)
1394  File "/Users/appveyor/venv3.8.6/lib/python3.8/site-packages/datalad/tests/utils.py", line 263, in _wrap_skip_if
1395    return func(*args, **kwargs)
1396  File "/Users/appveyor/venv3.8.6/lib/python3.8/site-packages/datalad/tests/utils.py", line 772, in _wrap_with_tempfile
1397    return t(*(arg + (filename,)), **kw)
1398  File "/Users/appveyor/venv3.8.6/lib/python3.8/site-packages/datalad/tests/utils.py", line 772, in _wrap_with_tempfile
1399    return t(*(arg + (filename,)), **kw)
1400  File "/Users/appveyor/venv3.8.6/lib/python3.8/site-packages/datalad/tests/utils.py", line 772, in _wrap_with_tempfile
1401    return t(*(arg + (filename,)), **kw)
1402  File "/Users/appveyor/venv3.8.6/lib/python3.8/site-packages/datalad/distributed/tests/test_ria_basics.py", line 289, in _test_remote_layout
1403    assert_equal(len(ds.repo.whereis('one.txt')), len(whereis) + 1)
1404AssertionError: 2 != 3
1405
```

**Comment by mih** [comment]
Duplicate of #5302
