### ISSUE TITLE
FAIL: datalad.distribution.tests.test_create_sibling.test_target_ssh_simple

### ISSUE THREAD

**Issue by mih** [datalad/datalad#5298]
```
Traceback (most recent call last):
1506  File "/home/appveyor/dlvenv/lib/python3.8/site-packages/nose/case.py", line 198, in runTest
1507    self.test(*self.arg)
1508  File "/home/appveyor/dlvenv/lib/python3.8/site-packages/datalad/tests/utils.py", line 206, in _wrap_skip_if_on_windows
1509    return func(*args, **kwargs)
1510  File "/home/appveyor/dlvenv/lib/python3.8/site-packages/datalad/tests/utils.py", line 291, in _wrap_skip_ssh
1511    return func(*args, **kwargs)
1512  File "/home/appveyor/dlvenv/lib/python3.8/site-packages/datalad/tests/utils.py", line 1103, in _wrap_with_testrepos
1513    t(*(arg + (uri,)), **kw)
1514  File "/home/appveyor/dlvenv/lib/python3.8/site-packages/datalad/tests/utils.py", line 772, in _wrap_with_tempfile
1515    return t(*(arg + (filename,)), **kw)
1516  File "/home/appveyor/dlvenv/lib/python3.8/site-packages/datalad/tests/utils.py", line 772, in _wrap_with_tempfile
1517    return t(*(arg + (filename,)), **kw)
1518  File "/home/appveyor/dlvenv/lib/python3.8/site-packages/datalad/distribution/tests/test_create_sibling.py", line 332, in test_target_ssh_simple
1519    assert_dict_equal(orig_digests, digests)  # nothing should change in terms of content
1520  File "/home/appveyor/dlvenv/lib/python3.8/site-packages/datalad/tests/utils.py", line 1375, in assert_dict_equal
1521    raise AssertionError("dicts differ:\n%s" % "\n".join(msgs))
1522AssertionError: dicts differ:
1523 ['.git/logs/HEAD'] differs: {'md5': '0bf92a551cc258c32cf21f784beaf7f2'} != {'md5': '3cc84ba60fc9b7d1d550c5bc89f314ba'}
```

https://ci.appveyor.com/project/mih/appveyor-datalad/build/job/cq8t16bcpw02lw4d

**Comment by mih** [comment]
This is the offending change in `.git/logs/HEAD` before and after reconfiguring the sibling:

```
appveyor@appveyor-vm:/tmp/datalad_temp_test_target_ssh_simple6sdprdao/basic$ cat .git/logs/HEAD
0000000000000000000000000000000000000000 153b867a26c56615e9ac16ac963cc865dbd1220b Appveyor Almighty <test@appveyor.land> 1610273451 +0000 push
appveyor@appveyor-vm:/tmp/datalad_temp_test_target_ssh_simple6sdprdao/basic$ cat .git/logs/HEAD 
0000000000000000000000000000000000000000 153b867a26c56615e9ac16ac963cc865dbd1220b Appveyor Almighty <test@appveyor.land> 1610273451 +0000 push
153b867a26c56615e9ac16ac963cc865dbd1220b 153b867a26c56615e9ac16ac963cc865dbd1220b Appveyor Almighty <test@appveyor.land> 1610273486 +0000
```
