### ISSUE TITLE
FAIL: datalad.cmdline.tests.test_main.test_help_np

### ISSUE THREAD

**Issue by mih** [datalad/datalad#5299]
```
Traceback (most recent call last):
1483  File "/home/appveyor/dlvenv/lib/python3.8/site-packages/nose/case.py", line 198, in runTest
1484    self.test(*self.arg)
1485  File "/home/appveyor/dlvenv/lib/python3.8/site-packages/datalad/cmdline/tests/test_main.py", line 127, in test_help_np
1486    raise AssertionError(
1487AssertionError: Following lines in --help output were longer than 80 chars:
1488183                         set logging verbosity level. Choose among critical, error, warning, info, debug. Also you can specify an integer <10 to provide even more debugging information
1489119                         execute command by scheduling it via available PBS. For settings, config file will be consulted
1490237   -C PATH               run as if datalad was started in <path> instead of the current working directory. When multiple -C options are given, each subsequent non-absolute -C <path> is interpreted relative to the preceding -C <path>. This
...
```
Linux: https://ci.appveyor.com/project/mih/appveyor-datalad/build/job/cq8t16bcpw02lw4d

Mac: https://ci.appveyor.com/project/mih/appveyor-datalad/build/job/nyba8paqts086vsv

**Comment by mih** [comment]
The failure needs a disconnected `/dev/stdin` to surface, plus a wide terminal session ;-)

It passes on a small terminal, or in an interactive session.
