### ISSUE TITLE
FAIL: datalad.plugin.tests.test_plugins.test_no_annex

### ISSUE THREAD

**Issue by mih** [datalad/datalad#5300]
```
Traceback (most recent call last):
786  File "C:\Python38-x64\lib\site-packages\nose\case.py", line 198, in runTest
787    self.test(*self.arg)
788  File "C:\Python38-x64\lib\site-packages\datalad\tests\utils.py", line 772, in _wrap_with_tempfile
789    return t(*(arg + (filename,)), **kw)
790  File "C:\Python38-x64\lib\site-packages\datalad\plugin\tests\test_plugins.py", line 196, in test_no_annex
791    assert_repo_status(ds.path)
792  File "C:\Python38-x64\lib\site-packages\datalad\tests\utils.py", line 1747, in assert_repo_status
793    eq_(state_files, oktobefound,
794AssertionError: unexpected content of state "modified": [WindowsPath('C:/DLTMP/datalad_temp_11in84lz/code/inannex')] != []
```

https://ci.appveyor.com/project/mih/appveyor-datalad/builds/37166446/job/5spymsp3vosq3cvf

I cannot replicate this failure on another windows box. And the test passes on a re-run.

Smells like a race-condition of the git filters.

**Comment by mih** [comment]
I tried various way to reproduce this failure inside and outside of appveyor. So far I failed.

Given there is nothing that really can be done about this, I will close this issue, merely leaving a record that it has happened before.

**Comment by yarikoptic** [comment]
it resurfaced again in https://github.com/datalad/datalad/pull/5010 for windows run  : ID=WinP39a2, DTS=datalad.downloaders datalad.interface datalad.plugin , APPVEYOR_BUILD_WORKER_IMAGE=Visual Studio 2019, PY=39-x64 https://ci.appveyor.com/project/mih/datalad/builds/38344401/job/783s60nrfellnkak
```
======================================================================
FAIL: datalad.plugin.tests.test_plugins.test_no_annex
----------------------------------------------------------------------
Traceback (most recent call last):
  File "C:\Python39-x64\lib\site-packages\nose\case.py", line 198, in runTest
    self.test(*self.arg)
  File "C:\Python39-x64\lib\site-packages\datalad\tests\utils.py", line 757, in _wrap_with_tempfile
    return t(*(arg + (filename,)), **kw)
  File "C:\Python39-x64\lib\site-packages\datalad\plugin\tests\test_plugins.py", line 196, in test_no_annex
    assert_repo_status(ds.path)
  File "C:\Python39-x64\lib\site-packages\datalad\tests\utils.py", line 1691, in assert_repo_status
    eq_(state_files, oktobefound,
AssertionError: unexpected content of state "modified": [WindowsPath('C:/DLTMP/datalad_temp_4ewcgzma/code/inannex')] != []
```
so seems to be still there just a very flaky one

**Comment by kyleam** [comment]
With this failure popping up recently in gh-5554, I tried to trigger it with `eval_under_testloopfs` and was able to around half of the time.  Extracting that test to a separate script, `GIT_TRACE=1` output suggests that the clean filter being executed for the failing run is the difference.  I think the race is probably reachable only from the python API, not the command-line interface.

<details>
<summary>script</summary>

```
$ /path/to/datalad/tools/eval_under_testloopfs sh /path/to/script/below
```


```sh
#!/bin/sh

set -eu

cd "$(mktemp -d "${TMPDIR:-/tmp}"/dl-XXXXXXX)"

cat >check.py <<'EOF'
import subprocess as sp
import sys
import tempfile

import datalad.api as dl

ds = dl.Dataset(f"ds-{sys.argv[1]}").create()
code = (ds.pathobj / "code")
code.mkdir()
(code / "inannex").write_text("content")
(code / "notinannex").write_text("othercontent")
(ds.pathobj / "README").write_text("please")

ds.save(str(code / "inannex"))
ds.no_annex(pattern=["code/**", "README"])
ds.save([str(code / "notinannex"), "README"])

sp.run(["git", "status"], cwd=ds.path)
sp.run(["git", "diff-files"], cwd=ds.path)
sp.run(["git", "diff-files", "--quiet"], cwd=ds.path, check=True)
EOF

export GIT_TRACE=1

bad=
good=
for i in $(seq 1 10)
do
    printf "Run %s..." "$i"
    if python check.py "$i" >out 2>&1
    then
        echo "good"
        if test -z "$good"
        then
            cp out out.good
        fi
        good=1
    else
        echo "bad"
        if test -z "$bad"
        then
            cp out out.bad
        fi
        bad=1
    fi

    if test -n "$bad" && test -n "$good"
    then
        echo "Stopping"
        break
    fi
done

if test -z "$bad" || test -z "$good"
then
    echo "Failed to get good and bad case"
    exit 1
fi

grep smudge out.good out.bad
```

</details>

Here's a excerpt of the relevant output:

```
[...a]
Run 6...bad
Stopping
out.good:[INFO] 16:17:23.083313 git.c:447               trace: built-in: git config filter.annex.smudge 'git-annex smudge -- %f' 
out.good:[INFO] 16:17:23.088384 git.c:447               trace: built-in: git config filter.annex.clean 'git-annex smudge --clean -- %f' 
out.good:[INFO] 16:17:23.298174 git.c:733               trace: exec: git-annex smudge --update
out.good:| 16:17:23.298200 run-command.c:667       trace: run_command: git-annex smudge --update 
out.bad:[INFO] 16:17:47.818581 git.c:447               trace: built-in: git config filter.annex.smudge 'git-annex smudge -- %f' 
out.bad:[INFO] 16:17:47.823389 git.c:447               trace: built-in: git config filter.annex.clean 'git-annex smudge --clean -- %f' 
out.bad:[INFO] 16:17:48.024175 git.c:733               trace: exec: git-annex smudge --update
out.bad:| 16:17:48.024200 run-command.c:667       trace: run_command: git-annex smudge --update 
out.bad:16:17:52.851629 run-command.c:667       trace: run_command: 'git-annex smudge --clean -- '\''code/inannex'\'''
```

Notice that `out.bad` has an extra line that with a `git annex smudge --clean` call on the file that's triggering the unexpectedly dirty state.

**Comment by kyleam** [comment]
It just occurred to me that this should be triggered by entering an adjusted branch directly, taking `eval_under_testloopfs` out of the equation so that the end result is easier to inspect/debug.  Here's a slightly tweaked script.

<details>
<summary>script</summary>

```
#!/bin/sh

set -eu

cd "$(mktemp -d "${TMPDIR:-/tmp}"/dl-XXXXXXX)"

cat >check.py <<'EOF'
import subprocess as sp
import sys
import tempfile

import datalad.api as dl

ds = dl.Dataset(f"ds-{sys.argv[1]}").create()
ds.repo.adjust()
code = (ds.pathobj / "code")
code.mkdir()
(code / "inannex").write_text("content")
(code / "notinannex").write_text("othercontent")
(ds.pathobj / "README").write_text("please")

ds.save(str(code / "inannex"))
ds.no_annex(pattern=["code/**", "README"])
ds.save([str(code / "notinannex"), "README"])

sp.run(["git", "status"], cwd=ds.path)
sp.run(["git", "diff-files", "-p"], cwd=ds.path)
sp.run(["git", "diff-files", "--quiet"], cwd=ds.path, check=True)
EOF

git version
export GIT_TRACE=1

bad=
good=
for i in $(seq 1 10)
do
    printf "Run %s..." "$i"
    if python check.py "$i" >out 2>&1
    then
        echo "good"
        if test -z "$good"
        then
            cp out out.good
        fi
        good=1
    else
        echo "bad"
        if test -z "$bad"
        then
            cp out out.bad
        fi
        bad=1
    fi

    if test -n "$bad" && test -n "$good"
    then
        echo "Stopping"
        break
    fi
done

if test -z "$bad" || test -z "$good"
then
    echo "Failed to get good and bad case"
    exit 1
fi

grep smudge out.good out.bad
```

</details>

```
$ sh /tmp/scratch.sh
git version 2.31.1
Run 1...good
Run 2...bad
Stopping
out.good:[INFO] 17:19:37.005650 git.c:447               trace: built-in: git config filter.annex.smudge 'git-annex smudge -- %f' 
out.good:[INFO] 17:19:37.010630 git.c:447               trace: built-in: git config filter.annex.clean 'git-annex smudge --clean -- %f' 
out.bad:[INFO] 17:19:41.840757 git.c:447               trace: built-in: git config filter.annex.smudge 'git-annex smudge -- %f' 
out.bad:[INFO] 17:19:41.845471 git.c:447               trace: built-in: git config filter.annex.clean 'git-annex smudge --clean -- %f' 
out.bad:17:19:47.550949 run-command.c:667       trace: run_command: 'git-annex smudge --clean -- '\''code/inannex'\'''
out.bad:17:19:47.706685 run-command.c:667       trace: run_command: 'git-annex smudge --clean -- '\''code/inannex'\'''
out.bad:17:19:47.858983 run-command.c:667       trace: run_command: 'git-annex smudge --clean -- '\''code/inannex'\'''
```

**Comment by kyleam** [comment]
And here's a script that triggers it without DataLad.  I think this is probably worth asking Joey about, if only to learn more about filter limitations.  I've opened at least one git-annex issue dealing with a similar topic, and I should refresh on that before posting.

<details>
<summary>script</summary>

```sh
#!/bin/sh

set -eu
cd "$(mktemp -d "${TMPDIR:-/tmp}"/clean-race-XXXXXXX)"

cat >check.sh <<'EOF'
set -eu

d=repo-$1
git init "$d"
cd "$d"

git commit --allow-empty -mc0

git annex init
git annex adjust --unlock

mkdir subdir
echo a >subdir/foo
echo b >subdir/bar
git annex add subdir/foo
git commit -m'add subdir/foo'
printf 'subdir/* annex.largefiles=nothing' >>.gitattributes
git add .gitattributes
git commit -m'configure annex.largefiles'

git annex add subdir/bar
git commit -m'add subdir/bar'

git status
git diff-files -p
git diff-files --quiet
EOF

git version
git annex version
export GIT_TRACE=1

bad=
good=
for i in $(seq 1 20)
do
    printf "Run %s..." "$i"
    if sh check.sh "$i" >out 2>&1
    then
        echo "good"
        if test -z "$good"
        then
            cp out out.good
        fi
        good=1
    else
        echo "bad"
        if test -z "$bad"
        then
            cp out out.bad
        fi
        bad=1
    fi

    if test -n "$bad" && test -n "$good"
    then
        echo "Stopping"
        break
    fi
done

if test -z "$bad" || test -z "$good"
then
    echo "Failed to get good and bad case"
    exit 1
fi

grep smudge out.good out.bad
```

</details>

```
git version 2.31.1
git-annex version: 8.20210330
[...]
Run 4...good
Stopping
out.good:17:52:58.634833 git.c:447               trace: built-in: git config filter.annex.smudge 'git-annex smudge -- %f'
out.good:17:52:58.639395 git.c:447               trace: built-in: git config filter.annex.clean 'git-annex smudge --clean -- %f'
out.good:17:52:58.831581 git.c:733               trace: exec: git-annex smudge --update
out.good:17:52:58.831604 run-command.c:667       trace: run_command: git-annex smudge --update
out.good:17:52:59.168049 run-command.c:667       trace: run_command: 'git-annex smudge --clean -- '\''subdir/foo'\'''
out.good:17:52:59.470526 run-command.c:667       trace: run_command: 'git-annex smudge --clean -- '\''.gitattributes'\'''
out.good:17:52:59.625461 run-command.c:667       trace: run_command: 'git-annex smudge --clean -- '\''.gitattributes'\'''
out.bad:17:52:50.312857 git.c:447               trace: built-in: git config filter.annex.smudge 'git-annex smudge -- %f'
out.bad:17:52:50.317228 git.c:447               trace: built-in: git config filter.annex.clean 'git-annex smudge --clean -- %f'
out.bad:17:52:50.511390 git.c:733               trace: exec: git-annex smudge --update
out.bad:17:52:50.511415 run-command.c:667       trace: run_command: git-annex smudge --update
out.bad:17:52:50.847271 run-command.c:667       trace: run_command: 'git-annex smudge --clean -- '\''subdir/foo'\'''
out.bad:17:52:51.147241 run-command.c:667       trace: run_command: 'git-annex smudge --clean -- '\''.gitattributes'\'''
out.bad:17:52:51.297599 run-command.c:667       trace: run_command: 'git-annex smudge --clean -- '\''subdir/foo'\'''
out.bad:17:52:51.451793 run-command.c:667       trace: run_command: 'git-annex smudge --clean -- '\''.gitattributes'\'''
out.bad:17:52:51.592570 run-command.c:667       trace: run_command: 'git-annex smudge --clean -- '\''subdir/foo'\'''
out.bad:17:52:52.033549 run-command.c:667       trace: run_command: 'git-annex smudge --clean -- '\''subdir/foo'\'''
out.bad:17:52:52.202864 run-command.c:667       trace: run_command: 'git-annex smudge --clean -- '\''subdir/foo'\'''
out.bad:17:52:52.510142 run-command.c:667       trace: run_command: 'git-annex smudge --clean -- '\''subdir/foo'\'''
out.bad:17:52:52.667097 run-command.c:667       trace: run_command: 'git-annex smudge --clean -- '\''subdir/foo'\'''
out.bad:17:52:52.818933 run-command.c:667       trace: run_command: 'git-annex smudge --clean -- '\''subdir/foo'\'''
```

**Comment by kyleam** [comment]
I've posted on the git-annex site about what I think is the core issue here: https://git-annex.branchable.com/forum/one-off_unlocked_annex_files_that_go_against_large/

**Comment by kyleam** [comment]
I think it makes sense to close this given the adjustments in gh-5579.  As mentioned there, the test should now behave reliably on an adjusted branch and will start to fail if the behavior changes on git-annex's end.
