### ISSUE TITLE
ERROR: datalad.customremotes.tests.test_archives.test_basic_scenario

### ISSUE THREAD

**Issue by mih** [datalad/datalad#5301]
```
Traceback (most recent call last):
848  File "/Users/appveyor/venv3.8.6/lib/python3.8/site-packages/nose/case.py", line 198, in runTest
849    self.test(*self.arg)
850  File "/Users/appveyor/venv3.8.6/lib/python3.8/site-packages/datalad/tests/utils.py", line 593, in _wrap_with_tree
851    return t(*(arg + (d,)), **kw)
852  File "/Users/appveyor/venv3.8.6/lib/python3.8/site-packages/datalad/tests/utils.py", line 772, in _wrap_with_tempfile
853    return t(*(arg + (filename,)), **kw)
854  File "/Users/appveyor/venv3.8.6/lib/python3.8/site-packages/datalad/customremotes/tests/test_archives.py", line 143, in test_basic_scenario
855    cloned_annex.get(fn_extracted)
856  File "/Users/appveyor/venv3.8.6/lib/python3.8/site-packages/datalad/support/gitrepo.py", line 325, in _wrap_normalize_paths
857    result = func(self, files_new, *args, **kwargs)
858  File "/Users/appveyor/venv3.8.6/lib/python3.8/site-packages/datalad/support/annexrepo.py", line 1485, in get
859    results = self._call_annex_records(
860  File "/Users/appveyor/venv3.8.6/lib/python3.8/site-packages/datalad/support/annexrepo.py", line 1139, in _call_annex_records
861    raise e
862  File "/Users/appveyor/venv3.8.6/lib/python3.8/site-packages/datalad/support/annexrepo.py", line 1091, in _call_annex_records
863    out = self._call_annex(
864  File "/Users/appveyor/venv3.8.6/lib/python3.8/site-packages/datalad/support/annexrepo.py", line 987, in _call_annex
865    return runner.run_on_filelist_chunks(
866  File "/Users/appveyor/venv3.8.6/lib/python3.8/site-packages/datalad/cmd.py", line 570, in run_on_filelist_chunks
867    res = self.run(
868  File "/Users/appveyor/venv3.8.6/lib/python3.8/site-packages/datalad/cmd.py", line 400, in run
869    raise CommandError(
870datalad.support.exceptions.CommandError: CommandError: 'git annex get --json --json-error-messages --json-progress -c annex.dotfiles=true -c annex.retry=3 -- ' |;&%b5{}'"'"'"Δקم๗あ .dbtc '' failed with exitcode 1 under /private/tmp/DL/datalad_temp_test_basic_scenario8c6mutr2 [err: 'git-annex: get: 1 failed'] [errors from JSON records: [["  Failed to fetch any archive containing MD5E-s3--202cb962ac59075b964b07152d234b70. Tried: ['MD5E-s174--6d238d2f9908c8643c0a5457fbc61b5e.tar.gz'] [archives.py:_transfer:407]", "  Failed to fetch any archive containing MD5E-s3--202cb962ac59075b964b07152d234b70. Tried: ['MD5E-s174--6d238d2f9908c8643c0a5457fbc61b5e.tar.gz'] [archives.py:_transfer:407]", "  Failed to fetch any archive containing MD5E-s3--202cb962ac59075b964b07152d234b70. Tried: ['MD5E-s174--6d238d2f9908c8643c0a5457fbc61b5e.tar.gz'] [archives.py:_transfer:407]"]]] [info keys: stdout_json]
```
https://ci.appveyor.com/project/mih/datalad/build/job/k5u263619e6erk8t

**Comment by mih** [comment]
This failure seems to be legit and I can reproduce it:

```
# in `cloned_annex` on the line before the failing `get()`
(venv3.8.6) worker-629-003:datalad_temp_test_basic_scenariocm66i4fm appveyor$ git annex whereis 
 |;&%b5{}'"Δקم๗あ .dbtc           |;&%b5{}'"Δקم๗あ .dbtc .tar.gz  .git/                            .gitattributes
(venv3.8.6) worker-629-003:datalad_temp_test_basic_scenariocm66i4fm appveyor$ git annex whereis \ \|\;\&%b5\{\}\'\"Δקم๗あ\ .dbtc\ 
whereis  |;&%b5{}'"Δקم๗あ .dbtc  (1 copy) 
        08561905-d84a-4aa5-8a4f-c0222f0dc0da -- [datalad-archives]

  datalad-archives: dl+archive:MD5E-s174--d0a934ed16ef82f67c971a679f4268f7.tar.gz#path=+%7C%3B%26%25b5%7B%7D%27%22%CE%94%D7%A7%D9%85%E0%B9%97%E3%81%82+.dbtc+/d/+%7C%3B%26%25b5%7B%7D%27%22%CE%94%D7%A7%D9%85%E0%B9%97%E3%81%82+.datc+
ok
(venv3.8.6) worker-629-003:datalad_temp_test_basic_scenariocm66i4fm appveyor$ git annex get \ \|\;\&%b5\{\}\'\"Δקم๗あ\ .dbtc\ 
get  |;&%b5{}'"Δקم๗あ .dbtc  (from datalad-archives...) 
[INFO] To obtain some keys we need to fetch an archive of size 174 Bytes 

  To obtain some keys we need to fetch an archive of size 174 Bytes

  Failed to fetch any archive containing MD5E-s3--202cb962ac59075b964b07152d234b70. Tried: ['MD5E-s174--d0a934ed16ef82f67c971a679f4268f7.tar.gz'] [archives.py:_transfer:407]

  Unable to access these remotes: datalad-archives

  Try making some of these remotes available:
        08561905-d84a-4aa5-8a4f-c0222f0dc0da -- [datalad-archives]
failed
git-annex: get: 1 failed
```

So the error replicates. But the archive seems to be registered properly

```
(venv3.8.6) worker-629-003:datalad_temp_test_basic_scenariocm66i4fm appveyor$ git annex info
trusted repositories: 0
semitrusted repositories: 5
        00000000-0000-0000-0000-000000000001 -- web
        00000000-0000-0000-0000-000000000002 -- bittorrent
        08561905-d84a-4aa5-8a4f-c0222f0dc0da -- [datalad-archives]
        452477d6-bdb3-4da2-9714-09bfd9d69dcc -- appveyor@worker-629-003.shared:/private/var/folders/5s/g225f6nd6jl4g8tshbh1ltk40000gn/T/datalad_temp_tree_test_basic_scenariodi3ady04 [origin]
        e9396d58-3818-4958-a76c-9bcd7a0269ae -- appveyor@worker-629-003.shared:/private/var/folders/5s/g225f6nd6jl4g8tshbh1ltk40000gn/T/datalad_temp_test_basic_scenariocm66i4fm [here]
untrusted repositories: 0
transfers in progress: none
available local disk space: 65.03 gigabytes (+1 megabyte reserved)
local annex keys: 0
local annex size: 0 bytes
annexed files in working tree: 2
size of annexed files in working tree: 177 bytes
bloom filter size: 32 mebibytes (0% full)
backend usage: 
        MD5E: 2

(venv3.8.6) worker-629-003:datalad_temp_test_basic_scenariocm66i4fm appveyor$ git annex whereis --key MD5E-s174--d0a934ed16ef82f67c971a679f4268f7.tar.gz
whereis MD5E-s174--d0a934ed16ef82f67c971a679f4268f7.tar.gz (1 copy) 
        452477d6-bdb3-4da2-9714-09bfd9d69dcc -- appveyor@worker-629-003.shared:/private/var/folders/5s/g225f6nd6jl4g8tshbh1ltk40000gn/T/datalad_temp_tree_test_basic_scenariodi3ady04 [origin]
ok
```
Looking into origin all seems fine too.
```
(venv3.8.6) worker-629-003:datalad_temp_test_basic_scenariocm66i4fm appveyor$ git remote -v
datalad-archives
origin  /var/folders/5s/g225f6nd6jl4g8tshbh1ltk40000gn/T/datalad_temp_tree_test_basic_scenariodi3ady04 (fetch)
origin  /var/folders/5s/g225f6nd6jl4g8tshbh1ltk40000gn/T/datalad_temp_tree_test_basic_scenariodi3ady04 (push)
(venv3.8.6) worker-629-003:datalad_temp_tree_test_basic_scenariodi3ady04 appveyor$ git annex whereis --key MD5E-s174--d0a934ed16ef82f67c971a679f4268f7.tar.gz
whereis MD5E-s174--d0a934ed16ef82f67c971a679f4268f7.tar.gz (1 copy) 
        452477d6-bdb3-4da2-9714-09bfd9d69dcc -- appveyor@worker-629-003.shared:/private/var/folders/5s/g225f6nd6jl4g8tshbh1ltk40000gn/T/datalad_temp_tree_test_basic_scenariodi3ady04 [here]
ok
(venv3.8.6) worker-629-003:datalad_temp_tree_test_basic_scenariodi3ady04 appveyor$ file .git/annex/objects/00/Jk/MD5E-s174--d0a934ed16ef82f67c971a679f4268f7.tar.gz/MD5E-s174--d0a934ed16ef82f67c971a679f4268f7.tar.gz 
.git/annex/objects/00/Jk/MD5E-s174--d0a934ed16ef82f67c971a679f4268f7.tar.gz/MD5E-s174--d0a934ed16ef82f67c971a679f4268f7.tar.gz: gzip compressed data, last modified: Sun Jan 10 11:53:59 2021, max speed, from Unix, original size modulo 2^32 3072

(venv3.8.6) worker-629-003:datalad_temp_tree_test_basic_scenariodi3ady04 appveyor$ git annex fsck --key MD5E-s174--d0a934ed16ef82f67c971a679f4268f7.tar.gz
fsck MD5E-s174--d0a934ed16ef82f67c971a679f4268f7.tar.gz (checksum...) ok
```

Back to the failing `get`. Let's see if it has to do with path handling, or sits deeper:

```
(venv3.8.6) worker-629-003:datalad_temp_tree_test_basic_scenariodi3ady04 appveyor$ git annex fsck --key MD5E-s174--d0a934ed16ef82f67c971a679f4268f7.tar.gz
fsck MD5E-s174--d0a934ed16ef82f67c971a679f4268f7.tar.gz (checksum...) ok
(recording state in git...)
(venv3.8.6) worker-629-003:datalad_temp_tree_test_basic_scenariodi3ady04 appveyor$ cd -
/private/var/folders/5s/g225f6nd6jl4g8tshbh1ltk40000gn/T/datalad_temp_test_basic_scenariocm66i4fm
(venv3.8.6) worker-629-003:datalad_temp_test_basic_scenariocm66i4fm appveyor$ git annex get --key MD5E-s174--d0a934ed16ef82f67c971a679f4268f7.tar.gz
get MD5E-s174--d0a934ed16ef82f67c971a679f4268f7.tar.gz (from origin...) 
  ../../../../../../../var/folders/5s/g225f6nd6jl4g8tshbh1ltk40000gn/T/datalad_temp_tree_test_basic_scenariodi3ady04/.git/annex: createDirectory: does not exist (No such file or directory)

  Unable to access these remotes: origin

  Try making some of these remotes available:
        452477d6-bdb3-4da2-9714-09bfd9d69dcc -- appveyor@worker-629-003.shared:/private/var/folders/5s/g225f6nd6jl4g8tshbh1ltk40000gn/T/datalad_temp_tree_test_basic_scenariodi3ady04 [origin]
failed
git-annex: get: 1 failed
```

Ok, that looks just like #5291. And it seems as if there is no datalad code running before the failure:

```
(venv3.8.6) worker-629-003:datalad_temp_test_basic_scenariocm66i4fm appveyor$ DATALAD_LOG_LEVEL=1 git annex get --key MD5E-s174--d0a934ed16ef82f67c971a679f4268f7.tar.gz
get MD5E-s174--d0a934ed16ef82f67c971a679f4268f7.tar.gz (from origin...) 
  ../../../../../../../var/folders/5s/g225f6nd6jl4g8tshbh1ltk40000gn/T/datalad_temp_tree_test_basic_scenariodi3ady04/.git/annex: createDirectory: does not exist (No such file or directory)

  Unable to access these remotes: origin

  Try making some of these remotes available:
        452477d6-bdb3-4da2-9714-09bfd9d69dcc -- appveyor@worker-629-003.shared:/private/var/folders/5s/g225f6nd6jl4g8tshbh1ltk40000gn/T/datalad_temp_tree_test_basic_scenariodi3ady04 [origin]
failed
git-annex: get: 1 failed
```

`git-annex --debug` reveals nothing in addition:

```
(venv3.8.6) worker-629-003:datalad_temp_test_basic_scenariocm66i4fm appveyor$ DATALAD_LOG_LEVEL=1 git annex --debug get --key MD5E-s174--d0a934ed16ef82f67c971a679f4268f7.tar.gz
[2021-01-10 06:04:50.094798] process [18639] read: git ["--git-dir=.git","--work-tree=.","--literal-pathspecs","symbolic-ref","-q","HEAD"]
[2021-01-10 06:04:50.098135] process [18639] done ExitSuccess
[2021-01-10 06:04:50.098801] process [18640] read: git ["--git-dir=.git","--work-tree=.","--literal-pathspecs","show-ref","refs/heads/dl-test-branch"]
[2021-01-10 06:04:50.101815] process [18640] done ExitSuccess
get MD5E-s174--d0a934ed16ef82f67c971a679f4268f7.tar.gz [2021-01-10 06:04:50.103059] process [18641] read: git ["--git-dir=.git","--work-tree=.","--literal-pathspecs","show-ref","git-annex"]
[2021-01-10 06:04:50.106152] process [18641] done ExitSuccess
[2021-01-10 06:04:50.106833] process [18642] read: git ["--git-dir=.git","--work-tree=.","--literal-pathspecs","show-ref","--hash","refs/heads/git-annex"]
[2021-01-10 06:04:50.109862] process [18642] done ExitSuccess
[2021-01-10 06:04:50.11083] process [18644] read: git ["--git-dir=.git","--work-tree=.","--literal-pathspecs","log","refs/heads/git-annex..9259523c2a1b810da47bc45697d9951d7d52d807","--pretty=%H","-n1"]
[2021-01-10 06:04:50.114258] process [18644] done ExitSuccess
[2021-01-10 06:04:50.115314] process [18645] chat: git ["--git-dir=.git","--work-tree=.","--literal-pathspecs","cat-file","--batch"]
[2021-01-10 06:04:50.122212] process [18646] chat: git ["--git-dir=.git","--work-tree=.","--literal-pathspecs","cat-file","--batch-check=%(objectname) %(objecttype) %(objectsize)"]
[2021-01-10 06:04:50.124306] process [18647] read: git ["config","--null","--list"]
[2021-01-10 06:04:50.126965] process [18647] done ExitSuccess
(from origin...) 
  ../../../../../../../var/folders/5s/g225f6nd6jl4g8tshbh1ltk40000gn/T/datalad_temp_tree_test_basic_scenariodi3ady04/.git/annex: createDirectory: does not exist (No such file or directory)

  Unable to access these remotes: origin

  Try making some of these remotes available:
        452477d6-bdb3-4da2-9714-09bfd9d69dcc -- appveyor@worker-629-003.shared:/private/var/folders/5s/g225f6nd6jl4g8tshbh1ltk40000gn/T/datalad_temp_tree_test_basic_scenariodi3ady04 [origin]
failed
[2021-01-10 06:04:50.131103] process [18645] done ExitSuccess
[2021-01-10 06:04:50.13159] process [18646] done ExitSuccess
git-annex: get: 1 failed
```

I can replicate the `mkdir` error:

```
(venv3.8.6) worker-629-003:datalad_temp_test_basic_scenariocm66i4fm appveyor$ mkdir ../../../../../../../var/folders/5s/g225f6nd6jl4g8tshbh1ltk40000gn/T/datalad_temp_tree_test_basic_scenariodi3ady04/.git/annex/testdummy
mkdir: ../../../../../../../var/folders/5s/g225f6nd6jl4g8tshbh1ltk40000gn/T/datalad_temp_tree_test_basic_scenariodi3ady04/.git/annex: No such file or directory
```

However, the path is needlessly complicated:

```
(venv3.8.6) worker-629-003:datalad_temp_test_basic_scenariocm66i4fm appveyor$ ls -id ../../../../../../../var/folders/5s/g225f6nd6jl4g8tshbh1ltk40000gn/T/datalad_temp_tree_test_basic_scenariodi3ady04/.git/annex /var/folders/5s/g225f6nd6jl4g8tshbh1ltk40000gn/T/datalad_temp_tree_test_basic_scenariodi3ady04/.git/annex
12889649026 ../../../../../../../var/folders/5s/g225f6nd6jl4g8tshbh1ltk40000gn/T/datalad_temp_tree_test_basic_scenariodi3ady04/.git/annex
12889649026 /var/folders/5s/g225f6nd6jl4g8tshbh1ltk40000gn/T/datalad_temp_tree_test_basic_scenariodi3ady04/.git/annex
```

Using the simpler path, I can create a directory

```
(venv3.8.6) worker-629-003:datalad_temp_test_basic_scenariocm66i4fm appveyor$ mkdir /var/folders/5s/g225f6nd6jl4g8tshbh1ltk40000gn/T/datalad_temp_tree_test_basic_scenariodi3ady04/.git/annex/testdummy
(venv3.8.6) worker-629-003:datalad_temp_test_basic_scenariocm66i4fm appveyor$ ls -1 ../../../../../../../var/folders/5s/g225f6nd6jl4g8tshbh1ltk40000gn/T/datalad_temp_tree_test_basic_scenariodi3ady04/.git/annex/
...
smudge.lck
testdummy
tmp
transfer
```

I am not sure what the exact name of the to-be-created directory is, but the basename please twice the length of an MD5 keys gives 227 chars. The machine reports:

```
(venv3.8.6) appveyor@worker-629-003 ~ % datalad wtf | grep length
  - max_path_length: 271
```

That is already close.

However, relocating the tempdir to something simpler, does not resolve the issue:

```
(venv3.8.6) worker-629-003:datalad_temp_test_basic_scenarioaqcmb0rn appveyor$ git annex get --key MD5E-s174--e068f395e44a47333d6e43a89f142cf7.tar.gz
get MD5E-s174--e068f395e44a47333d6e43a89f142cf7.tar.gz (from origin...) 
  ../../../tmp/datalad_temp_tree_test_basic_scenariozzb5zand/.git/annex: createDirectory: does not exist (No such file or directory)

  Unable to access these remotes: origin

  Try making some of these remotes available:
        5a0dfb80-dd92-40ee-9a9b-c260f18204c5 -- appveyor@worker-629-003.shared:/private/tmp/datalad_temp_tree_test_basic_scenariozzb5zand [origin]
failed
git-annex: get: 1 failed
```

It seems to be specifically the use of the relative path as an argument to create the directory:

```
(venv3.8.6) worker-629-003:datalad_temp_test_basic_scenarioaqcmb0rn appveyor$ mkdir ../../../tmp/datalad_temp_tree_test_basic_scenariozzb5zand/.git/annex/testdummy
mkdir: ../../../tmp/datalad_temp_tree_test_basic_scenariozzb5zand/.git/annex: No such file or directory
(venv3.8.6) worker-629-003:datalad_temp_test_basic_scenarioaqcmb0rn appveyor$ mkdir /tmp/datalad_temp_tree_test_basic_scenariozzb5zand/.git/annex/testdummy
```

I think there is little we can do about this on the datalad end.

**Comment by mih** [comment]
Confirmed to be same-as #5291 and fixed by placing the TMPDIR outside `/private` into the user's HOME dir. Also needs #5307.

**Comment by yarikoptic** [comment]
Augmenting environment to get tests pass moves is away from a typical environment users would have. Should we may be absolutify paths for those calls (if absolute version is shorter)?

**Comment by mih** [comment]
It has nothing to do with the length. It is the location itself.

**Comment by mih** [comment]
There is no point in keeping this open. The general issue is #5291
