### ISSUE TITLE
ERROR: datalad.support.tests.test_parallel.test_creatsubdatasets

### ISSUE THREAD

**Issue by mih** [datalad/datalad#5308]
```
Traceback (most recent call last):
1199  File "C:\Python38-x64\lib\site-packages\nose\case.py", line 198, in runTest
1200    self.test(*self.arg)
1201  File "C:\Python38-x64\lib\site-packages\datalad\tests\utils.py", line 772, in _wrap_with_tempfile
1202    return t(*(arg + (filename,)), **kw)
1203  File "C:\Python38-x64\lib\site-packages\datalad\support\tests\test_parallel.py", line 126, in test_creatsubdatasets
1204    assert_raises(IncompleteResultsError, list, ProducerConsumer(paths[::-1], create_, jobs=5))
1205  File "C:\Python38-x64\lib\unittest\case.py", line 816, in assertRaises
1206    return context.handle('assertRaises', args, kwargs)
1207  File "C:\Python38-x64\lib\unittest\case.py", line 202, in handle
1208    callable_obj(*args, **kwargs)
1209  File "C:\Python38-x64\lib\site-packages\datalad\support\parallel.py", line 272, in __iter__
1210    yield from self._iter_threads(jobs)
1211  File "C:\Python38-x64\lib\site-packages\datalad\support\parallel.py", line 424, in _iter_threads
1212    self.shutdown(force=True, exception=self._producer_exception or interrupted_by_exception)
1213  File "C:\Python38-x64\lib\site-packages\datalad\support\parallel.py", line 237, in shutdown
1214    raise exception
1215  File "C:\Python38-x64\lib\site-packages\datalad\support\parallel.py", line 408, in _iter_threads
1216    done_useful |= self._pop_done_futures(lgr)
1217  File "C:\Python38-x64\lib\site-packages\datalad\support\parallel.py", line 465, in _pop_done_futures
1218    raise exception
1219  File "C:\Python38-x64\lib\concurrent\futures\thread.py", line 57, in run
1220    result = self.fn(*self.args, **self.kwargs)
1221  File "C:\Python38-x64\lib\site-packages\datalad\support\parallel.py", line 336, in consumer_worker
1222    for r in res:
1223  File "C:\Python38-x64\lib\site-packages\datalad\interface\utils.py", line 389, in generator_func
1224    for r in _process_results(
1225  File "C:\Python38-x64\lib\site-packages\datalad\interface\utils.py", line 557, in _process_results
1226    for res in results:
1227  File "C:\Python38-x64\lib\site-packages\datalad\core\local\create.py", line 397, in __call__
1228    tbrepo = AnnexRepo(
1229  File "C:\Python38-x64\lib\site-packages\datalad\support\repo.py", line 154, in __call__
1230    instance = type.__call__(cls, *new_args, **new_kwargs)
1231  File "C:\Python38-x64\lib\site-packages\datalad\support\annexrepo.py", line 196, in __init__
1232    super(AnnexRepo, self).__init__(
1233  File "C:\Python38-x64\lib\site-packages\datalad\support\gitrepo.py", line 953, in __init__
1234    self._create_empty_repo(path, create_sanity_checks, **git_opts)
1235  File "C:\Python38-x64\lib\site-packages\datalad\support\gitrepo.py", line 992, in _create_empty_repo
1236    os.makedirs(path)
1237  File "C:\Python38-x64\lib\os.py", line 223, in makedirs
1238    mkdir(name, mode)
1239FileExistsError: [WinError 183] Cannot create a file when that file already exists: 'C:\\DLTMP\\datalad_temp_2q0qo2jp\\subds1'
```

- https://ci.appveyor.com/project/mih/datalad/build/job/lums3gaw5wj5wgr6
- https://ci.appveyor.com/project/mih/datalad/build/job/hfkdh7m3ig1a7o52#L1201
- https://ci.appveyor.com/project/mih/datalad/builds/37307556/job/op592q4j4gi5204c#L1201

**Comment by mih** [comment]
I have not seen this in months. Good to close.
