### ISSUE TITLE
ERROR: datalad.customremotes.tests.test_archives.test_get_git_environ_adjusted

### ISSUE THREAD

**Issue by mih** [datalad/datalad#5315]
```
Traceback (most recent call last):
573  File "C:\Python38-x64\lib\site-packages\nose\case.py", line 198, in runTest
574    self.test(*self.arg)
575  File "C:\Python38-x64\lib\site-packages\datalad\customremotes\tests\test_archives.py", line 192, in test_get_git_environ_adjusted
576    assert_equal(sys_env["PWD"], os.environ.get("PWD"))
577KeyError: 'PWD'
```

https://ci.appveyor.com/project/mih/datalad/builds/37223213/job/1qfy2dxj6bihru2i#L569

**Comment by mih** [comment]
It is unclear what this test is trying to achieve. If it wants to test that the system environment is used, it should probably test for a specific modification of that system environment within the test. ATM it tests for a PWD, which simply does not exist on Windows.

The test is already marked as `known_failure_githubci_win`, but it is probably just wrong.
