### ISSUE TITLE
config dir is unnecessarily created during manpages generation

### ISSUE THREAD

**Issue by yarikoptic** [datalad/datalad#532]
There is some obscure failure while building the package 

```
mv debian/python-datalad/usr/bin/* debian/datalad/usr/bin
python setup.py build_manpage
running build_manpage
error: [Errno 13] Permission denied: '/nonexistent'
debian/rules:42: recipe for target 'override_dh_auto_install' failed
make[1]: *** [override_dh_auto_install] Error 1
make[1]: Leaving directory '/build/datalad-0.2.1'
debian/rules:19: recipe for target 'binary' failed
make: *** [binary] Error 2
```

after pbuidler falls into interactive shell rerunning proceeds normal

actually I think I got it:

```
root@smaug:/tmp/buildd/datalad-0.2.1# rm -rf /nonexistent/
root@smaug:/tmp/buildd/datalad-0.2.1# HOME=/nonexistent python setup.py build_manpage
running build_manpage
root@smaug:/tmp/buildd/datalad-0.2.1# ls -ld /nonexistent/.config/datalad/
drwxr-xr-x 2 root root 4096 Jun 11 03:10 /nonexistent/.config/datalad/
```

someone again is just eager to brew some configs

**Comment by yarikoptic** [comment]
could well be some appdirs malaction

**Comment by hanke** [comment]
There should be no custom code (i.e. contributed by me) that explicitly creates the directory. I have little to know experience with appdirs. Any thoughts on where to start looking? @bpoldrack Did you encounter such issue before?

**Comment by mih** [comment]
Looks like this is safe to close.

**Comment by yarikoptic** [comment]
I think the issue was not really addressed, just worked around.  I ran into it again while trying to build datalad-container pkg:
```shell
======================================================================
ERROR: datalad_container.tests.test_containers.test_add_local_path
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/nose/case.py", line 197, in runTest
    self.test(*self.arg)
  File "/usr/lib/python3/dist-packages/datalad/tests/utils.py", line 596, in newfunc
    return t(*(arg + (filename,)), **kw)
  File "/usr/lib/python3/dist-packages/datalad/tests/utils.py", line 423, in newfunc
    return t(*(arg + (d,)), **kw)
  File "/build/datalad-container-0.2.2/debian/datalad-container/usr/lib/python3.7/dist-packages/datalad_container/tests/test_containers.py", line 49, in test_add_local_path
    ds = Dataset(path).create()
  File "/usr/lib/python3/dist-packages/datalad/distribution/dataset.py", line 494, in apply_func
    return f(**kwargs)
  File "/usr/lib/python3/dist-packages/datalad/interface/utils.py", line 479, in eval_func
    return return_func(generator_func)(*args, **kwargs)
  File "/usr/lib/python3/dist-packages/datalad/interface/utils.py", line 467, in return_func
    results = list(results)
  File "/usr/lib/python3/dist-packages/datalad/interface/utils.py", line 422, in generator_func
    result_renderer, result_xfm, _result_filter, **_kwargs):
  File "/usr/lib/python3/dist-packages/datalad/interface/utils.py", line 509, in _process_results
    for res in results:
  File "/usr/lib/python3/dist-packages/datalad/distribution/create.py", line 342, in __call__
    fake_dates=fake_dates
  File "/usr/lib/python3/dist-packages/datalad/support/repo.py", line 146, in __call__
    instance = type.__call__(cls, *new_args, **new_kwargs)
  File "/usr/lib/python3/dist-packages/datalad/support/annexrepo.py", line 197, in __init__
    fake_dates=fake_dates)
  File "/usr/lib/python3/dist-packages/datalad/support/gitrepo.py", line 655, in __init__
    ssh_manager.assure_initialized()
  File "/usr/lib/python3/dist-packages/datalad/support/sshconnector.py", line 376, in assure_initialized
    assure_dir(self._socket_dir)
  File "/usr/lib/python3/dist-packages/datalad/utils.py", line 1246, in assure_dir
    os.makedirs(dirname)
  File "/usr/lib/python3.7/os.py", line 211, in makedirs
    makedirs(head, exist_ok=exist_ok)
  File "/usr/lib/python3.7/os.py", line 211, in makedirs
    makedirs(head, exist_ok=exist_ok)
  File "/usr/lib/python3.7/os.py", line 211, in makedirs
    makedirs(head, exist_ok=exist_ok)
  File "/usr/lib/python3.7/os.py", line 221, in makedirs
    mkdir(name, mode)
PermissionError: [Errno 13] Permission denied: '/nonexistent'
```
so will just need to breed the workaround in `debian/rules` until it is properly fixed

**Comment by bpoldrack** [comment]
That traceback is weird. Something is missing here.
```
File "/usr/lib/python3/dist-packages/datalad/support/sshconnector.py", line 376, in assure_initialized
    assure_dir(self._socket_dir)
```
That `_socket_dir` can never be something like '/nonexistent'. How do you trigger that? That test is passing on our builds. Where and how do you run it?

**Comment by yarikoptic** [comment]
happens during debian package build time.
I think HOME is set to /nonexisting by debhelper or alike.
Strange fact is that whenever I fall into debugging interactive session, build proceeds fine even with dpkg-buildpackage -uc -us

**Comment by mih** [comment]
I cannot replicate the original issue:

```
% python setup.py build_manpage
running build_manpage
% tree ~/.config/datalad
/home/mih/.config/datalad [error opening dir]

0 directories, 0 files
```

I also cannot see inappropriate directory use in the test report above.

```
% rm -rf  ~/.config/datalad
% chmod ugo-w ~/.config
% python -m nose -s -v datalad_container.tests.test_containers:test_add_local_path
datalad_container.tests.test_containers.test_add_local_path ... ok
Versions: appdirs=1.4.3 boto=2.49.0 cmd:annex=7.20190708+git36-g32d526164-1~ndall+1 cmd:bundled-git=2.20.1 cmd:git=2.20.1 cmd:system-git=2.20.1 cmd:system-ssh=7.9p1 git=2.1.12 gitdb=0.6.4 humanize=0.5.1 iso8601=0.1.12 keyring=19.0.2 keyrings.alt=3.1.1 msgpack=0.6.1 requests=2.22.0 scrapy=1.7.3 tqdm=4.32.2 wrapt=1.11.2
Obscure filename: str=b' "\';a&b&c\xce\x94\xd0\x99\xd7\xa7\xd9\x85\xe0\xb9\x97\xe3\x81\x82 `| ' repr=' "\';a&b&cΔЙקم๗あ `| '
Encodings: default='utf-8' filesystem='utf-8' locale.prefered='UTF-8'
Environment: LANG='en_US.UTF-8' LANGUAGE='en_US:en' PATH='/home/mih/env/datalad3-dev/bin:/usr/local/bin:/usr/bin:/bin:/usr/games:/home/mih/bin:/home/mih/bin/pycharm/bin' GIT_EDITOR='vim' LC_CTYPE='en_US.UTF-8' GIT_PYTHON_GIT_EXECUTABLE='/usr/lib/git-annex.linux/git'

----------------------------------------------------------------------
Ran 1 test in 1.573s

OK
% tree ~/.config/datalad
/home/mih/.config/datalad [error opening dir]

0 directories, 0 files
```

Closing...
