### ISSUE TITLE
FOI: wtf blow on windows / master / appveyor / python 3.7

### ISSUE THREAD

**Issue by yarikoptic** [datalad/datalad#5362]
since we unofficially do not care about 3.7 for windows, not considering it a bug but wanted to record:  while trying to figure out new appveyor + codecov gotcha in #5352 and temporarily adding 3.7 on windows got a failed run due to

```
datalad wtf
Traceback (most recent call last):
  File "C:\Python37-x64\Scripts\datalad-script.py", line 33, in <module>
    sys.exit(load_entry_point('datalad', 'console_scripts', 'datalad')())
  File "C:\Python37-x64\Scripts\datalad-script.py", line 25, in importlib_load_entry_point
    return next(matches).load()
  File "c:\python37-x64\lib\site-packages\importlib_metadata\__init__.py", line 96, in load
    module = import_module(match.group('module'))
  File "c:\python37-x64\lib\importlib\__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1006, in _gcd_import
  File "<frozen importlib._bootstrap>", line 983, in _find_and_load
  File "<frozen importlib._bootstrap>", line 953, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "<frozen importlib._bootstrap>", line 1006, in _gcd_import
  File "<frozen importlib._bootstrap>", line 983, in _find_and_load
  File "<frozen importlib._bootstrap>", line 953, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "<frozen importlib._bootstrap>", line 1006, in _gcd_import
  File "<frozen importlib._bootstrap>", line 983, in _find_and_load
  File "<frozen importlib._bootstrap>", line 967, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 677, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "c:\projects\datalad\datalad\__init__.py", line 47, in <module>
    cfg = ConfigManager()
  File "c:\projects\datalad\datalad\config.py", line 274, in __init__
    self.reload(force=True)
  File "c:\projects\datalad\datalad\config.py", line 327, in reload
    self._stores[store_id] = self._reload(runargs)
  File "c:\projects\datalad\datalad\config.py", line 359, in _reload
    encoding='utf-8',
  File "c:\projects\datalad\datalad\config.py", line 717, in _run
    out = self._runner.run(self._config_cmd + args, **kwargs)
  File "c:\projects\datalad\datalad\cmd.py", line 390, in run
    env=env,
  File "c:\python37-x64\lib\asyncio\base_events.py", line 587, in run_until_complete
    return future.result()
  File "c:\projects\datalad\datalad\cmd.py", line 103, in run_async_cmd
    transport, protocol = await proc
  File "c:\python37-x64\lib\asyncio\base_events.py", line 1544, in subprocess_exec
    bufsize, **kwargs)
  File "c:\python37-x64\lib\asyncio\base_events.py", line 462, in _make_subprocess_transport
    raise NotImplementedError
NotImplementedError
Command exited with code 1
```
which could also be due to very recent change #5350 (heh)

**Comment by yarikoptic** [comment]
I have not tested but https://github.com/datalad/datalad/pull/5367  might help since we would first check if we can run... but there we catch only OSError and not NotImplementedError, so might need a tune up...
