### ISSUE TITLE
ERROR: datalad.tests.test_install.test_install_miniconda

### ISSUE THREAD

**Issue by mih** [datalad/datalad#5385]
Fails in build of Debian package on bullseye

```
======================================================================
ERROR: datalad.tests.test_install.test_install_miniconda
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/nose/case.py", line 197, in runTest
    self.test(*self.arg)
  File "/build/datalad-0.14.0~rc1/.pybuild/cpython3_3.9_datalad/build/datalad/tests/utils.py", line 202, in _wrap_skip_if_on_windows
    return func(*args, **kwargs)
  File "/build/datalad-0.14.0~rc1/.pybuild/cpython3_3.9_datalad/build/datalad/tests/utils.py", line 752, in _wrap_with_tempfile
    return t(*(arg + (filename,)), **kw)
  File "/build/datalad-0.14.0~rc1/.pybuild/cpython3_3.9_datalad/build/datalad/tests/test_install.py", line 18, in test_install_miniconda
    subprocess.run(
  File "/usr/lib/python3.9/subprocess.py", line 528, in run
    raise CalledProcessError(retcode, process.args,
subprocess.CalledProcessError: Command '['/usr/bin/python3.9', 'datalad/install.py', 'miniconda', '--batch', '--path-miniconda', '/tmp/datalad_temp_test_install_minicondaobu2lbj1/conda']' returned non-zero exit status 1.
```

**Comment by kyleam** [comment]
This test is gone with ecf074dddb (gh-5243), so I don't think there's anything to do here.
