### ISSUE TITLE
fresh test_docker_registry errors probably due to rate limiting

### ISSUE THREAD

**Issue by yarikoptic** [datalad/datalad#5405]
while testing #5404 kept running into failures like the following

https://ci.appveyor.com/project/mih/datalad/builds/37593613/job/gdfeff8jvwr49252
```
======================================================================
ERROR: datalad.downloaders.tests.test_docker_registry.test_download_docker_blob
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/appveyor/dlvenv/lib/python3.8/site-packages/nose/case.py", line 198, in runTest
    self.test(*self.arg)
  File "/home/appveyor/dlvenv/lib/python3.8/site-packages/datalad/tests/utils.py", line 182, in _wrap_skip_if_no_network
    return func(*args, **kwargs)
  File "/home/appveyor/dlvenv/lib/python3.8/site-packages/datalad/tests/utils.py", line 757, in _wrap_with_tempfile
    return t(*(arg + (filename,)), **kw)
  File "/home/appveyor/dlvenv/lib/python3.8/site-packages/datalad/downloaders/tests/test_docker_registry.py", line 42, in test_download_docker_blob
    ds.download_url(urls=[url], path=str(outfile))
  File "/home/appveyor/dlvenv/lib/python3.8/site-packages/wrapt/wrappers.py", line 605, in __call__
    return self._self_wrapper(self.__wrapped__, self._self_instance,
  File "/home/appveyor/dlvenv/lib/python3.8/site-packages/datalad/distribution/dataset.py", line 503, in apply_func
    return f(**kwargs)
  File "/home/appveyor/dlvenv/lib/python3.8/site-packages/wrapt/wrappers.py", line 566, in __call__
    return self._self_wrapper(self.__wrapped__, self._self_instance,
  File "/home/appveyor/dlvenv/lib/python3.8/site-packages/datalad/interface/utils.py", line 482, in eval_func
    return return_func(generator_func)(*args, **kwargs)
  File "/home/appveyor/dlvenv/lib/python3.8/site-packages/wrapt/wrappers.py", line 566, in __call__
    return self._self_wrapper(self.__wrapped__, self._self_instance,
  File "/home/appveyor/dlvenv/lib/python3.8/site-packages/datalad/interface/utils.py", line 470, in return_func
    results = list(results)
  File "/home/appveyor/dlvenv/lib/python3.8/site-packages/datalad/interface/utils.py", line 455, in generator_func
    raise IncompleteResultsError(
datalad.support.exceptions.IncompleteResultsError: Command did not complete successfully. 1 failed:
[{'action': 'download_url',
  'exception_traceback': '[download_url.py:__call__:178,providers.py:download:482,base.py:download:521,base.py:access:210,base.py:_handle_authentication:254,base.py:access:169,base.py:_download:419,http.py:get_downloader_session:573,http.py:check_response_status:106]',
  'message': 'Access to '
             'https://registry-1.docker.io/v2/library/busybox/blobs/sha256:f0b02e9d092d905d0d87a8455a1ae3e9bb47b4aa3dc125125ca5cd10d6441c9f '
             'has failed: status code 401 [http.py:check_response_status:106]',
  'path': '/home/appveyor/DLTMP/datalad_temp_test_download_docker_blobwiv8htli/blob',
  'status': 'error',
  'type': 'file'}]
-------------------- >> begin captured logging << --------------------
```

Similar https://travis-ci.com/github/datalad/datalad/jobs/480074616 .  I guess we are hitting the rate limiting and since we are not authenticating using docker hub token (or do we?) we get 401.  I think we should just make those tests run on cron and not for each PR?

**Comment by kyleam** [comment]
>  I guess we are hitting the rate limiting

I think so to, given it fails only in a small subset and it's still working for me locally.

> and since we are not authenticating using docker hub token (or do we?) we get 401

It's just doing an anonymous `HEAD url => 401 => add token to header => GET url` sequence (`HTTPAnonBearerTokenAuthenticator`)

>  think we should just make those tests run on cron and not for each PR?

Sounds good:  gh-5406
