### ISSUE TITLE
Jupyter lab error

### ISSUE THREAD

**Issue by k-sap** [datalad/datalad#5409]
#### What is the problem?
I try to import datalad package in Jupyter Lab Notebook. And this results in `RuntimeError: Cannot run the event loop while another loop is running`.
#### What steps will reproduce the problem?
Create new Python Jupyter Lab Notebook and try to import datalad.
#### What version of DataLad are you using (run `datalad --version`)? On what operating system (consider running `datalad wtf`)?
datalad 0.14.0
Ubuntu 20.04
#### Is there anything else that would be useful to know in this context?
This happened to me after update to Datalad 0.14. Before, everything was ok.
#### Have you had any success using DataLad before? (to assess your expertise/prior luck.  We would welcome your testimonial additions to https://github.com/datalad/datalad/wiki/Testimonials as well)
I'm figuring it out.

**Comment by kyleam** [comment]
Thanks for reporting.  We've been fumbling around with asyncio stuff.  gh-5106 (0.13.6) prevented an "Event loop is closed" issue when running from IPython.  In 0.14, the two asyncio related changes were gh-5350 and gh-5367.

> This happened to me after update to Datalad 0.14. Before, everything was ok.

Do you recall what version of DataLad you were on before?  0.13.7?

Also, what version of Python and Jupyter are you using?  And do you see a traceback?  That could help pinpoint where this is happening.

**Comment by k-sap** [comment]
Thanks for response.

Python 3.8.5.
JupyterLab 3.0.7

'
/home/user/.local/lib/python3.8/site-packages/datalad/cmd.py:377: RuntimeWarning: coroutine 'run_async_cmd' was never awaited
  new_loop = True
RuntimeWarning: Enable tracemalloc to get the object allocation traceback

---------------------------------------------------------------------------
RuntimeError                              Traceback (most recent call last)
<ipython-input-1-2677c3f1f0d7> in <module>
----> 1 import datalad

~/.local/lib/python3.8/site-packages/datalad/__init__.py in <module>
     45 
     46 from .config import ConfigManager
---> 47 cfg = ConfigManager()
     48 
     49 from .log import lgr

~/.local/lib/python3.8/site-packages/datalad/config.py in __init__(self, dataset, overrides, source)
    272             self._runner = GitWitlessRunner(**run_kwargs)
    273 
--> 274         self.reload(force=True)
    275 
    276         if not ConfigManager._checked_git_identity:

~/.local/lib/python3.8/site-packages/datalad/config.py in reload(self, force)
    325         while to_run:
    326             store_id, runargs = to_run.popitem()
--> 327             self._stores[store_id] = self._reload(runargs)
    328 
    329         # always update the merged representation, even if we did not reload

~/.local/lib/python3.8/site-packages/datalad/config.py in _reload(self, run_args)
    353     def _reload(self, run_args):
    354         # query git-config
--> 355         stdout, stderr = self._run(
    356             run_args,
    357             protocol=StdOutErrCapture,

~/.local/lib/python3.8/site-packages/datalad/config.py in _run(self, args, where, reload, **kwargs)
    715         if '-l' in args:
    716             # we are just reading, no need to reload, no need to lock
--> 717             out = self._runner.run(self._config_cmd + args, **kwargs)
    718             return out['stdout'], out['stderr']
    719 

~/.local/lib/python3.8/site-packages/datalad/cmd.py in run(self, cmd, protocol, stdin, cwd, env, **kwargs)
    378         try:
    379             # include the subprocess manager in the asyncio event loop
--> 380             results = event_loop.run_until_complete(
    381                 run_async_cmd(
    382                     event_loop,

/usr/lib/python3.8/asyncio/base_events.py in run_until_complete(self, future)
    590         """
    591         self._check_closed()
--> 592         self._check_running()
    593 
    594         new_task = not futures.isfuture(future)

/usr/lib/python3.8/asyncio/base_events.py in _check_running(self)
    552             raise RuntimeError('This event loop is already running')
    553         if events._get_running_loop() is not None:
--> 554             raise RuntimeError(
    555                 'Cannot run the event loop while another loop is running')
    556 

RuntimeError: Cannot run the event loop while another loop is running
'

**Comment by kyleam** [comment]
With jupyterlab 3.0.7 and Python 3.7.3, I can trigger this with 0.14.  Below is the traceback.

<details>
<summary>traceback</summary>

```
---------------------------------------------------------------------------
RuntimeError                              Traceback (most recent call last)
<ipython-input-1-2677c3f1f0d7> in <module>
----> 1 import datalad

~/src/python/datalad/datalad/__init__.py in <module>
     45 
     46 from .config import ConfigManager
---> 47 cfg = ConfigManager()
     48 
     49 from .log import lgr

~/src/python/datalad/datalad/config.py in __init__(self, dataset, overrides, source)
    272             self._runner = GitWitlessRunner(**run_kwargs)
    273 
--> 274         self.reload(force=True)
    275 
    276         if not ConfigManager._checked_git_identity:

~/src/python/datalad/datalad/config.py in reload(self, force)
    325         while to_run:
    326             store_id, runargs = to_run.popitem()
--> 327             self._stores[store_id] = self._reload(runargs)
    328 
    329         # always update the merged representation, even if we did not reload

~/src/python/datalad/datalad/config.py in _reload(self, run_args)
    357             protocol=StdOutErrCapture,
    358             # always expect git-config to output utf-8
--> 359             encoding='utf-8',
    360         )
    361         store = {}

~/src/python/datalad/datalad/config.py in _run(self, args, where, reload, **kwargs)
    715         if '-l' in args:
    716             # we are just reading, no need to reload, no need to lock
--> 717             out = self._runner.run(self._config_cmd + args, **kwargs)
    718             return out['stdout'], out['stderr']
    719 

~/src/python/datalad/datalad/cmd.py in run(self, cmd, protocol, stdin, cwd, env, **kwargs)
    386                     protocol_kwargs=kwargs,
    387                     cwd=cwd,
--> 388                     env=env,
    389                 )
    390             )

/usr/lib/python3.7/asyncio/base_events.py in run_until_complete(self, future)
    569         future.add_done_callback(_run_until_complete_cb)
    570         try:
--> 571             self.run_forever()
    572         except:
    573             if new_task and future.done() and not future.cancelled():

/usr/lib/python3.7/asyncio/base_events.py in run_forever(self)
    527         if events._get_running_loop() is not None:
    528             raise RuntimeError(
--> 529                 'Cannot run the event loop while another loop is running')
    530         self._set_coroutine_origin_tracking(self._debug)
    531         self._thread_id = threading.get_ident()

RuntimeError: Cannot run the event loop while another loop is running

Task exception was never retrieved
future: <Task finished coro=<run_async_cmd() done, defined at /home/kyle/src/python/datalad/datalad/cmd.py:53> exception=RuntimeError('Cannot add child handler, the child watcher does not have a loop attached')>
Traceback (most recent call last):
  File "/home/kyle/src/python/datalad/datalad/cmd.py", line 104, in run_async_cmd
    transport, protocol = await proc
  File "/usr/lib/python3.7/asyncio/base_events.py", line 1533, in subprocess_exec
    bufsize, **kwargs)
  File "/usr/lib/python3.7/asyncio/unix_events.py", line 193, in _make_subprocess_transport
    self._child_watcher_callback, transp)
  File "/usr/lib/python3.7/asyncio/unix_events.py", line 924, in add_child_handler
    "Cannot add child handler, "
RuntimeError: Cannot add child handler, the child watcher does not have a loop attached
```

</details>

**Comment by kyleam** [comment]
On my end, that error first started with 21cc64ff34 (RF: Use WitlessRunner for config manager, 2020-07-13, gh-4699), which was a part of the 0.14 release.

**Comment by kyleam** [comment]
Searching around a bit, I came across <https://github.com/jupyter/notebook/issues/3397>.  A few times, this was mentioned as a workaround:

```python
import nest_asyncio
nest_asyncio.apply()

import datalad
```

Not a proper fix, but that seems to do the trick on my end.

**Comment by k-sap** [comment]
That works. For me it's enough. Thanks!

**Comment by kyleam** [comment]
@adswa Do you think there's a good spot in the handbook where the `nest_asyncio` workaround could be mentioned?

**Comment by adswa** [comment]
Yes, thanks for pinging me!

**Comment by kyleam** [comment]
Closed by gh-5667 (but wasn't automatically closed due to markup issue)
