### ISSUE TITLE
test_repo_save fails on windows build

### ISSUE THREAD

**Issue by bpoldrack** [datalad/datalad#5462]
Failure discovered in PR #5440. Windows build only and apparently unrelated to adjusted branches. Might be that there's something wrong with `get_convoluted_situation` on Windows.

```
======================================================================
FAIL: datalad.support.tests.test_repo_save.test_gitrepo_save_all
----------------------------------------------------------------------
Traceback (most recent call last):
  File "C:\Python39-x64\lib\site-packages\nose\case.py", line 198, in runTest
    self.test(*self.arg)
  File "C:\Python39-x64\lib\site-packages\datalad\tests\utils.py", line 757, in _wrap_with_tempfile
    return t(*(arg + (filename,)), **kw)
  File "C:\Python39-x64\lib\site-packages\datalad\support\tests\test_repo_save.py", line 72, in test_gitrepo_save_all
    _test_save_all(path, GitRepo)
  File "C:\Python39-x64\lib\site-packages\datalad\support\tests\test_repo_save.py", line 64, in _test_save_all
    assert f.match('subds_modified'), f
AssertionError: C:\DLTMP\datalad_temp_ui79yjzi\subdir\subds_added
```

```
======================================================================
FAIL: datalad.support.tests.test_repo_save.test_annexrepo_save_all
----------------------------------------------------------------------
Traceback (most recent call last):
  File "C:\Python39-x64\lib\site-packages\nose\case.py", line 198, in runTest
    self.test(*self.arg)
  File "C:\Python39-x64\lib\site-packages\datalad\tests\utils.py", line 757, in _wrap_with_tempfile
    return t(*(arg + (filename,)), **kw)
  File "C:\Python39-x64\lib\site-packages\datalad\support\tests\test_repo_save.py", line 79, in test_annexrepo_save_all
    _test_save_all(path, AnnexRepo)
  File "C:\Python39-x64\lib\site-packages\datalad\support\tests\test_repo_save.py", line 64, in _test_save_all
    assert f.match('subds_modified'), f
AssertionError: C:\DLTMP\datalad_temp_w22aspuy\subdir\subds_added
```

**Comment by mih** [comment]
This issue is categorized, and the resulting test disabling wrong. The failure can also be triggered when running the test on a crippled FS (`tools/eval_under_testloopfs`).

Here is the result when running on 0.17.2 and Debian:

```sh
[0.17.2] % tools/eval_under_testloopfs python -m pytest -s -v --pyargs datalad/support/tests/test_repo_save.py::test_gitrepo_save_all
...
=================================================== FAILURES ====================================================
_____________________________________________ test_gitrepo_save_all _____________________________________________

path = '/tmp/datalad-fs-3eU6f/datalad_temp_test_gitrepo_save_allyi3nigi1'

    @slow  # 11sec on travis
    @known_failure_windows  # see gh-5462
    @with_tempfile
    def test_gitrepo_save_all(path=None):
>       _test_save_all(path, GitRepo)

datalad/support/tests/test_repo_save.py:70: 
_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _

path = '/tmp/datalad-fs-3eU6f/datalad_temp_test_gitrepo_save_allyi3nigi1'
repocls = <class 'datalad.support.gitrepo.GitRepo'>

    def _test_save_all(path, repocls):
        ds = get_convoluted_situation(path, GitRepo)
        orig_status = ds.repo.status(untracked='all')
        # TODO test the results when the are crafted
        res = ds.repo.save()
        # make sure we get a 'delete' result for each deleted file
        eq_(
            set(r['path'] for r in res if r['action'] == 'delete'),
            {k for k, v in orig_status.items() if k.name == 'file_deleted'}
        )
        saved_status = ds.repo.status(untracked='all')
        # we still have an entry for everything that did not get deleted
        # intentionally
        eq_(
            len([f for f, p in orig_status.items()
                 if not f.match('*_deleted')]),
            len(saved_status))
        # everything but subdataset entries that contain untracked content,
        # or modified subsubdatasets is now clean, a repo simply doesn touch
        # other repos' private parts
        for f, p in saved_status.items():
            if p.get('state', None) != 'clean':
>               assert f.match('subds_modified'), f
E               AssertionError: PosixPath('/tmp/datalad-fs-3eU6f/datalad_temp_test_gitrepo_save_allyi3nigi1/subdir/subds_added')
E               assert False
E                +  where False = <bound method PurePath.match of PosixPath('/tmp/datalad-fs-3eU6f/datalad_temp_test_gitrepo_save_allyi3nigi1/subdir/subds_added')>('subds_modified')
E                +    where <bound method PurePath.match of PosixPath('/tmp/datalad-fs-3eU6f/datalad_temp_test_gitrepo_save_allyi3nigi1/subdir/subds_added')> = PosixPath('/tmp/datalad-fs-3eU6f/datalad_temp_test_gitrepo_save_allyi3nigi1/subdir/subds_added').match

datalad/support/tests/test_repo_save.py:62: AssertionError
============================================ short test summary info ============================================
FAILED datalad/support/tests/test_repo_save.py::test_gitrepo_save_all - AssertionError: PosixPath('/tmp/datala...
============================================== 1 failed in 21.45s ===============================================
```

Same behavior on `master` as of `1c8944cfc9f360057db9c9bc693be7238edfec06`
