### ISSUE TITLE
datalad on readthedoc

### ISSUE THREAD

**Issue by samuelgarcia** [datalad/datalad#5615]
For spikeinterface project I try to build the new documentation on readthedoc.
This new doc use datalad internaly (with python api) to retreieve some dataset and make example with sphinx-gallery.
The dataset is on [gin ](https://gin.g-node.org/NeuralEnsemble/ephy_testing_data)
On a local machin everything is OK.

Configuring readthedoc is hard with pip.
So I manage to unistall everything with conda.
For instance git-annex is from anaconda.

On read the doc I have this:

```python
datalad.support.exceptions.CommandError: CommandError: 'git -c diff.ignoreSubmodules=none -c annex.merge-annex-branches=false annex find --not --in . --json --json-error-messages -c annex.dotfiles=true -c annex.retry=3 -- mearec/mearec_test_10s.h5' failed with exitcode 1 under /home/docs/spikeinterface_datasets/ephy_testing_data [err: 'git-annex: This repository has annex.uuid set, but annex.version is not set. Perhaps that git config was lost. Cannot use the repository in this state; set back annex.version to fix this.'] [info keys: stdout_json]
```
Any idea how I could fix this ?

**Comment by yarikoptic** [comment]
Could you point to a complete log?

Note that you might need to have a proper full clone of the original doc repo. CI by default might do just a checkout of the tree

**Comment by samuelgarcia** [comment]
Hi.
thank for wuick anwser
here the doc build fail
https://readthedocs.org/projects/spikeinterface/builds/13636538/
I don't known if you can see it without login.

The conda env is this one
https://github.com/SpikeInterface/spikeinterface/blob/master/environment_rtd.yml

Otherwise I copy/paste this
```
WARNING: /home/docs/checkouts/readthedocs.org/user_builds/spikeinterface/checkouts/latest/examples/modules/core/plot_4_waveform_extractor.py failed to execute correctly: Traceback (most recent call last):
  File "/home/docs/checkouts/readthedocs.org/user_builds/spikeinterface/checkouts/latest/examples/modules/core/plot_4_waveform_extractor.py", line 33, in <module>
    local_path = download_dataset(repo=repo, remote_path=remote_path, local_folder=None)
  File "/home/docs/checkouts/readthedocs.org/user_builds/spikeinterface/conda/latest/lib/python3.8/site-packages/spikeinterface/core/datasets.py", line 37, in download_dataset
    dataset.get(remote_path)
  File "/home/docs/checkouts/readthedocs.org/user_builds/spikeinterface/conda/latest/lib/python3.8/site-packages/datalad/distribution/dataset.py", line 503, in apply_func
    return f(**kwargs)
  File "/home/docs/checkouts/readthedocs.org/user_builds/spikeinterface/conda/latest/lib/python3.8/site-packages/datalad/interface/utils.py", line 486, in eval_func
    return return_func(generator_func)(*args, **kwargs)
  File "/home/docs/checkouts/readthedocs.org/user_builds/spikeinterface/conda/latest/lib/python3.8/site-packages/datalad/interface/utils.py", line 474, in return_func
    results = list(results)
  File "/home/docs/checkouts/readthedocs.org/user_builds/spikeinterface/conda/latest/lib/python3.8/site-packages/datalad/interface/utils.py", line 393, in generator_func
    for r in _process_results(
  File "/home/docs/checkouts/readthedocs.org/user_builds/spikeinterface/conda/latest/lib/python3.8/site-packages/datalad/interface/utils.py", line 561, in _process_results
    for res in results:
  File "/home/docs/checkouts/readthedocs.org/user_builds/spikeinterface/conda/latest/lib/python3.8/site-packages/datalad/distribution/get.py", line 947, in __call__
    for res in _get_targetpaths(
  File "/home/docs/checkouts/readthedocs.org/user_builds/spikeinterface/conda/latest/lib/python3.8/site-packages/datalad/distribution/get.py", line 652, in _get_targetpaths
    results = ds_repo.get(
  File "/home/docs/checkouts/readthedocs.org/user_builds/spikeinterface/conda/latest/lib/python3.8/site-packages/datalad/support/gitrepo.py", line 324, in _wrap_normalize_paths
    result = func(self, files_new, *args, **kwargs)
  File "/home/docs/checkouts/readthedocs.org/user_builds/spikeinterface/conda/latest/lib/python3.8/site-packages/datalad/support/annexrepo.py", line 1446, in get
    expected_downloads, fetch_files = self._get_expected_files(
  File "/home/docs/checkouts/readthedocs.org/user_builds/spikeinterface/conda/latest/lib/python3.8/site-packages/datalad/support/annexrepo.py", line 1510, in _get_expected_files
    for j in self._call_annex_records(
  File "/home/docs/checkouts/readthedocs.org/user_builds/spikeinterface/conda/latest/lib/python3.8/site-packages/datalad/support/annexrepo.py", line 1127, in _call_annex_records
    raise e
  File "/home/docs/checkouts/readthedocs.org/user_builds/spikeinterface/conda/latest/lib/python3.8/site-packages/datalad/support/annexrepo.py", line 1079, in _call_annex_records
    out = self._call_annex(
  File "/home/docs/checkouts/readthedocs.org/user_builds/spikeinterface/conda/latest/lib/python3.8/site-packages/datalad/support/annexrepo.py", line 975, in _call_annex
    return runner.run_on_filelist_chunks(
  File "/home/docs/checkouts/readthedocs.org/user_builds/spikeinterface/conda/latest/lib/python3.8/site-packages/datalad/cmd.py", line 658, in run_on_filelist_chunks
    res = self.run(
  File "/home/docs/checkouts/readthedocs.org/user_builds/spikeinterface/conda/latest/lib/python3.8/site-packages/datalad/cmd.py", line 408, in run
    raise CommandError(
datalad.support.exceptions.CommandError: CommandError: 'git -c diff.ignoreSubmodules=none -c annex.merge-annex-branches=false annex find --not --in . --json --json-error-messages -c annex.dotfiles=true -c annex.retry=3 -- mearec/mearec_test_10s.h5' failed with exitcode 1 under /home/docs/spikeinterface_datasets/ephy_testing_data [err: 'git-annex: This repository has annex.uuid set, but annex.version is not set. Perhaps that git config was lost. Cannot use the repository in this state; set back annex.version to fix this.'] [info keys: stdout_json]
```

**Comment by yarikoptic** [comment]
BTW, I also see multiple
```
It is highly recommended to configure Git before using DataLad. Set both 'user.name' and 'user.email' configuration variables.
```
so might be related to the same issue we fixed recently and "discussion" on which is in https://github.com/datalad/datalad/issues/5596 to be addressed on datalad side.

May be first fix for that and then if persists I will look deeper.

**Comment by yarikoptic** [comment]
also re conda recipe -- datalad is available from conda-forge as well, so no need for having it done via `pip`

**Comment by samuelgarcia** [comment]
I known from this discussion that email and nam must be configured.
I do this on github actions for test already.
But here in the context of readthedoc the config is super limited.
In short, we can't run command line, only conda or pip config.
So git config is not possible in read the doc.
Maybe I can try something on sphinx conf.py to do it.
Here the error seams to be related a annex.version which i don't known what it is.
thanks for help.

**Comment by yarikoptic** [comment]
> Maybe I can try something on sphinx conf.py to do it.

you sure can since it is a python script. Something like

```python
from datalad import cfg
if not cfg.get('user.name', None):
   print("Setting global configs for git")
   cfg.set('user.name', 'DataLad User', where='global')
   cfg.set('user.email', 'datalad-user@example.com', where='global')
```

<details>
<summary>here is demo of it in action:</summary> 

```shell
$> rm -rf /tmp/HOME; mkdir -p /tmp/HOME; HOME=/tmp/HOME python /tmp/setcfg.py
It is highly recommended to configure Git before using DataLad. Set both 'user.name' and 'user.email' configuration variables.
It is highly recommended to configure Git before using DataLad. Set both 'user.name' and 'user.email' configuration variables.
Setting global configs for git
(dev3) 1 77021.....................................:Thu 29 Apr 2021 09:22:07 AM EDT:.
(git)lena:~datalad/datalad-handbook/book[enh-redirect-cheatsheet]git
$> HOME=/tmp/HOME python /tmp/setcfg.py      
(dev3) 1 77022.....................................:Thu 29 Apr 2021 09:22:15 AM EDT:.
(git)lena:~datalad/datalad-handbook/book[enh-redirect-cheatsheet]git
$> cat /tmp/HOME/.gitconfig 
[user]
	name = DataLad User
	email = datalad-user@example.com
```
</details>

note: if just as is -- it would set it also on some naive user without git configured running a doc build... not sure how that is likely ;-)

> Here the error seams to be related a annex.version which i don't known what it is.

it should just be present in the `.git/config` for that repo, e.g.
```
$> git -C ~/datalad config annex.version
8
```
and usually is done by `git annex` whenever it `annex init` a repo.

**Comment by samuelgarcia** [comment]
I am just reading your anwser.
I just did this:
```
on_rtd = os.environ.get('READTHEDOCS') == 'True'
if on_rtd:
    # need a git config
    os.system('git config --global user.email "rtd@example.com"')
    os.system('git config --global user.name "RTD Almighty"')
```
and it seams to fix the stuff.
I will use your solution.

Thank you very very much for this strong support.
If you come to France (Lyon) you will get a glass of wine.

**Comment by yarikoptic** [comment]
great, making it RTD specific would indeed be wise.
Now I am looking forward to my future Tour-de-France (if ever to happen ;-) ) even more ;-)

I will close this issue, feel free to reopen if more to be done.  But thanks for raising it -- one more bit of information to make decision on #5596
