### ISSUE TITLE
A successful `datalad get` can still look quite sad

### ISSUE THREAD

**Issue by mih** [datalad/datalad#5617]
Here is the raw `git-annex get` call:

```
% git -C derivative/aggregate_fmri_timeseries annex get .
get sub-10/atlases/bold3Tp2/shen_fconn_atlas_150.nii.gz (from psydata...) 

  download failed: Not Found

  failed to download content
(from inm7-storage...) 
[INFO] Downloading 'https://datapub.fz-juelich.de/studyforrest/studyforrest.ria/7fc/d8812-d0fe-11e7-8db2-a0369f7c647e/annex/objects/2G/0J/MD5E-s32338--3cb12b68abd59160dffdf4830e1de8bb.nii.gz/MD5E-s32338--3cb12b68abd59160dffdf4830e1de8bb.nii.gz' into '.git/annex/tmp/MD5E-s32338--3cb12b68abd59160dffdf4830e1de8bb.nii.gz' 
(checksum...) ok
(recording state in git...)
```

So it tried one thing, failed, and then succeeded. Here is datalad:

```
% datalad get derivative/aggregate_fmri_timeseries/sub-10/atlases/bold3Tp2/shen_fconn_atlas_150.nii.gz
get(ok): derivative/aggregate_fmri_timeseries/sub-10/atlases/bold3Tp2/shen_fconn_atlas_150.nii.gz (file) [download failed: Not Found
failed to download content
download failed: Not Found
failed to download content
download failed: Not Found
failed to download content]
action summary:
  get (notneeded: 1, ok: 1)
```

So all worked, but the number of "failed" statements has doubled, and they shadow the happy core message quite effectively.

Due to the particular circumstances in my original run I  did not notice that each failing download attempt is also accompanied by ERROR log messages. So it is even worse.

**Comment by mih** [comment]
Oh, and depending where the error is happening and how exactly it looks like, this can be REALLY ugly (thx @adswa):

```
adina@head1:~$ datalad clone https://github.com/psychoinformatics-de/studyforrest-data-retinotopy.git
[INFO   ] Remote origin not usable by git-annex; setting annex-ignore           
[INFO   ] ssh: Could not resolve hostname bulk1.htc.inm7.de: Name or service not known 
[INFO   ] ssh: Could not resolve hostname bulk1.htc.inm7.de: Name or service not known 
[INFO   ] Traceback (most recent call last):
|   File "/usr/lib/python3/dist-packages/datalad/distributed/ora_remote.py", line 632, in _wrap_handle_errors
|     return func(self, *args, **kwargs)
|   File "/usr/lib/python3/dist-packages/datalad/distributed/ora_remote.py", line 976, in initremote
|     if not isinstance(self.io, HTTPRemoteIO):
|   File "/usr/lib/python3/dist-packages/datalad/distributed/ora_remote.py", line 1037, in io
|     self._io = SSHRemoteIO(self.storage_host, self.buffer_size) 
[INFO   ] File "/usr/lib/python3/dist-packages/datalad/distributed/ora_remote.py", line 295, in __init__
|     self.ssh.open()
|   File "/usr/lib/python3/dist-packages/fasteners/lock.py", line 306, in wrapper
|     return f(self, *args, **kwargs)
|   File "/usr/lib/python3/dist-packages/datalad/support/sshconnector.py", line 551, in open
|     stderr,
| datalad.support.exceptions.ConnectionOpenFailedError: ConnectionOpenFailedError: 'ssh -fN -o ControlMaster=auto -o ControlPersist=15m -o ControlPath=/home/adina/.cache/datalad/sockets/d0e2d0ae bulk1.htc.inm7.de' failed with exitcode 255 [Failed to open SSH connection (could not start ControlMaster process)]
| 
| During handling of the above exception, another exception occurred:
| 
| Traceback (most recent call last):
|   File "/usr/bin/git-annex-remote-ora", line 11, in <module>
|     load_entry_point('datalad==0.14.0', 'console_scripts', 'git-annex-remote-ora')()
|   File "/usr/lib/python3/dist-packages/datalad/distributed/ora_remote.py", line 1223, in main
|     master.Listen()
|   File "/usr/lib/python3/dist-packages/annexremote/annexremote.py", line 860, in Listen
|     reply = self.protocol.command(line)
|   File "/usr/lib/python3/dist-packages/annexremote/annexremote.py", line 549, in command
|     reply = method()
|   File "/usr/lib/python3/dist-packages/annexremote/annexremote.py", line 571, in do_INITREMOTE
|     self.remote.initremote()
|   File "/usr/lib/python3/dist-packages/datalad/distributed/ora_remote.py", line 652, in _wrap_handle_errors
|     self.io.close()
|   File "/usr/lib/python3/dist-packages/datalad/distributed/ora_remote.py", line 1037, in io
|     self._io = SSHRemoteIO(self.storage_host, self.buffer_size)
|   File "/usr/lib/python3/dist-packages/datalad/distributed/ora_remote.py", line 295, in __init__ 
[INFO   ] self.ssh.open()
|   File "/usr/lib/python3/dist-packages/fasteners/lock.py", line 306, in wrapper
|     return f(self, *args, **kwargs)
|   File "/usr/lib/python3/dist-packages/datalad/support/sshconnector.py", line 551, in open
|     stderr,
| datalad.support.exceptions.ConnectionOpenFailedError: ConnectionOpenFailedError: 'ssh -fN -o ControlMaster=auto -o ControlPersist=15m -o ControlPath=/home/adina/.cache/datalad/sockets/d0e2d0ae bulk1.htc.inm7.de' failed with exitcode 255 [Failed to open SSH connection (could not start ControlMaster process)] 
[INFO   ] external special remote protocol error, unexpectedly received "" (unable to parse command) 
install(ok): /home/adina/studyforrest-data-retinotopy (dataset)
adina@head1:~$ datalad -C studyforrest-data-retinotopy get .
get(ok): qa/pyretmap_subjQuali.ods (file) [from mddatasrc...]                                                      
get(ok): sub-01/post_processing/combined_pipeline_eccentricity.nii.gz (file) [from mddatasrc...]                   
get(ok): sub-01/post_processing/combined_pipeline_polar.nii.gz (file) [from mddatasrc...]
get(ok): sub-01/surface_maps/combined_pipeline_eccentricity_lh.mgh (file) [from mddatasrc...]
get(ok): sub-01/surface_maps/combined_pipeline_eccentricity_rh.mgh (file) [from mddatasrc...]
get(ok): sub-01/surface_maps/combined_pipeline_polar_lh.mgh (file) [from mddatasrc...]
get(ok): sub-01/surface_maps/combined_pipeline_polar_rh.mgh (file) [from mddatasrc...]
get(ok): sub-02/post_processing/combined_pipeline_eccentricity.nii.gz (file) [from mddatasrc...]
get(ok): sub-02/post_processing/combined_pipeline_polar.nii.gz (file) [from mddatasrc...]
get(ok): sub-02/surface_maps/combined_pipeline_eccentricity_lh.mgh (file) [from mddatasrc...]
  [81 similar messages have been suppressed]
action summary:
  get (ok: 91)
```

**Comment by mih** [comment]
This is now much better with #6070. Thx!
