### ISSUE TITLE
datalad create   booms

### ISSUE THREAD

**Issue by yarikoptic** [datalad/datalad#562]
```shell

(git)smaug:/mnt/btrfs/datasets/datalad/crawl[master]git
$> datalad create --no-annex -d . labs
2016-06-17 09:19:02,733 [INFO   ] Creating a new annex repo at labs (create.py:81)
2016-06-17 09:19:02,792 [ERROR  ] Failed to start ['git', '-c', 'receive.autogc=0', '-c', 'gc.auto=0', 'annex', 'init', ['.']]'': coercing to Unicode: need string or buffer, list found [subprocess.py:_execute_child:1335] (cmd.py:261)
2016-06-17 09:19:02,793 [ERROR  ] coercing to Unicode: need string or buffer, list found [subprocess.py:_execute_child:1335] (TypeError) (main.py:243)

(git)smaug:/mnt/btrfs/datasets/datalad/crawl[master]git
$> ls -lta
total 4
drwx--S--- 1 yoh datalad   8 Jun 17 09:19 labs/
drwxr-sr-x 1 yoh datalad  84 Jun 17 09:19 ./
drwxrwsr-x 1 yoh datalad 216 Jun 17 09:18 .git/
drwx--S--- 1 yoh datalad  48 Jun 13 00:09 neurovault/
drwxrwsr-x 1 yoh datalad  56 Jun 13 00:06 ../
-rw-rw-r-- 1 yoh datalad 171 Jun 13 00:05 .gitmodules
drwxr-s--- 1 yoh datalad 836 Jun  9 10:07 openfmri/
drwx--S--- 1 yoh datalad 548 May 24 17:12 crcns/

(git)smaug:/mnt/btrfs/datasets/datalad/crawl[master]git
$> ls labs -a
./  ../  .git/
changes on filesystem:                                                                                                                                  
 crcns      | 0
 neurovault | 2 +-

(git)smaug:/mnt/btrfs/datasets/datalad/crawl[master]git
$> cat .gitmodules 
[submodule "openfmri"]
	path = openfmri
	url = ./openfmri
[submodule "neurovault"]
	path = neurovault
	url = ./neurovault
[submodule "crcns"]
	path = crcns
	url = ./crcns
changes on filesystem:                                                                                                                                  
 crcns      | 0
 neurovault | 2 +-

(git)smaug:/mnt/btrfs/datasets/datalad/crawl[master]git
$> datalad --version
datalad 0.2.1.dev108

```

Strangely `git status` doesn't report that created labs directory as not tracked (as it did before for me)

**Comment by yarikoptic** [comment]
ok -- I see the reason -- -d apparently is for 'description' but also not handled correctly -- passed as a list to git-annex init call.  So that is issue number 1 - and I will keep it this here and file a new one about -d

```
$> datalad --dbg create -l 2 --no-annex -d . mitchell      
2016-06-17 09:27:09,875 [INFO   ] Creating a new annex repo at mitchell (create.py:81)
2016-06-17 09:27:09,875 [DEBUG  ] Initialize empty Git repository at mitchell (gitrepo.py:383)
2016-06-17 09:27:09,886 [DEBUG  ] Initializing annex repository at /mnt/btrfs/datasets/datalad/crawl/labs/mitchell... (annexrepo.py:193)
2016-06-17 09:27:09,886 [DEBUG  ] Running: ['git', '-c', 'receive.autogc=0', '-c', 'gc.auto=0', 'annex', 'init', '--debug', ['.']] (cmd.py:352)
2016-06-17 09:27:09,892 [ERROR  ] Failed to start ['git', '-c', 'receive.autogc=0', '-c', 'gc.auto=0', 'annex', 'init', '--debug', ['.']]'': coercing to Unicode: need string or buffer, list found [subprocess.py:_execute_child:1335] (cmd.py:261)
Traceback (most recent call last):
  File "/home/yoh/proj/datalad/datalad/venv-tests/bin/datalad", line 9, in <module>
    load_entry_point('datalad==0.2.1.dev1', 'console_scripts', 'datalad')()
  File "/home/yoh/proj/datalad/datalad/datalad/cmdline/main.py", line 231, in main
    ret = cmdlineargs.func(cmdlineargs)
  File "/home/yoh/proj/datalad/datalad/datalad/interface/base.py", line 241, in call_from_parser
    return cls.__call__(**kwargs)
  File "/home/yoh/proj/datalad/datalad/datalad/distribution/create.py", line 84, in __call__
    version=annex_version, description=description)
  File "/home/yoh/proj/datalad/datalad/datalad/support/annexrepo.py", line 194, in __init__
    self._init(version=version, description=description)
  File "/home/yoh/proj/datalad/datalad/datalad/support/annexrepo.py", line 375, in _init
    self._run_annex_command('init', annex_options=opts)
  File "/home/yoh/proj/datalad/datalad/datalad/support/annexrepo.py", line 277, in _run_annex_command
    return self.cmd_call_wrapper.run(cmd_list, **kwargs)
  File "/home/yoh/proj/datalad/datalad/datalad/cmd.py", line 384, in run
    cmd, env=self.get_git_environ_adjusted(), *args, **kwargs)
  File "/home/yoh/proj/datalad/datalad/datalad/cmd.py", line 256, in run
    env=env or self.env)
  File "/usr/lib/python2.7/subprocess.py", line 710, in __init__
    errread, errwrite)
  File "/usr/lib/python2.7/subprocess.py", line 1335, in _execute_child
    raise child_exception
TypeError: coercing to Unicode: need string or buffer, list found
()
> /usr/lib/python2.7/subprocess.py(1335)_execute_child()
-> raise child_exception
(Pdb) up
> /usr/lib/python2.7/subprocess.py(710)__init__()
-> errread, errwrite)
(Pdb) 
> /home/yoh/proj/datalad/datalad/datalad/cmd.py(256)run()
-> env=env or self.env)
(Pdb) 
> /home/yoh/proj/datalad/datalad/datalad/cmd.py(384)run()
-> cmd, env=self.get_git_environ_adjusted(), *args, **kwargs)
(Pdb) l
379  	
380  	        return git_env
381  	
382  	    def run(self, cmd, env=None, *args, **kwargs):
383  	        return super(GitRunner, self).run(
384  ->	            cmd, env=self.get_git_environ_adjusted(), *args, **kwargs)
385  	
386  	# ####
387  	# Preserve from previous version
388  	# TODO: document intention
389  	# ####
(Pdb) p cmd
['git', '-c', 'receive.autogc=0', '-c', 'gc.auto=0', 'annex', 'init', '--debug', ['.']]
```

**Comment by hanke** [comment]
Likely wrong `nargs` setting.

On Fri, Jun 17, 2016 at 3:23 PM, Yaroslav Halchenko <
notifications@github.com> wrote:

> Assigned #562 <https://github.com/datalad/datalad/issues/562> to @hanke
> <https://github.com/hanke>.
>
> —
> You are receiving this because you were mentioned.
> Reply to this email directly, view it on GitHub
> <https://github.com/datalad/datalad/issues/562#event-695940507>, or mute
> the thread
> <https://github.com/notifications/unsubscribe/AAIVH26yWyNKQNmR4pPfW0O5OhRJ0h0Rks5qMp_egaJpZM4I4Wk5>
> .
>



-- 
Michael Hanke
http://mih.voxindeserto.de

**Comment by yarikoptic** [comment]
And likely a missing test

**Comment by hanke** [comment]
Same as wait #563 -- reimplementation of `create` is necessary -- not fixing individual bits.

**Comment by hanke** [comment]
Superseded by #563
