### ISSUE TITLE
failed test_parial_unlocked with fresh git-annex

### ISSUE THREAD

**Issue by yarikoptic** [datalad/datalad#5637]
from daily builds of git-annex: e.g. https://github.com/datalad/git-annex/runs/2497189685?check_suite_focus=true

```
======================================================================
testing 0
FAIL: datalad.core.local.tests.test_save.test_partial_unlocked
testing 1
----------------------------------------------------------------------
/var/folders/24/8k48jl6d249_n_qfxwsl6xvm0000gn/T/datalad_temp_tree_test_paths_with_forward_slashes6a4twljy
Traceback (most recent call last):
' |;&%b5{}\'"Δקم๗あ .datc '
  File "/Users/runner/hostedtoolcache/Python/3.7.10/x64/lib/python3.7/site-packages/nose/case.py", line 198, in runTest
.: here(+) [git]
    self.test(*self.arg)
.: dl-test-remote(+) [/private/var/folders/24/8k48jl6d249_n_qfxwsl6xvm0000gn/T/datalad_temp_test_cached_dataset72gx2h8j/https___github.com_datalad_testrepo--minimalds (git)]
  File "/Users/runner/hostedtoolcache/Python/3.7.10/x64/lib/python3.7/site-packages/datalad/tests/utils.py", line 764, in _wrap_with_tempfile
.: here(+) [git]
    return t(*(arg + (filename,)), **kw)
.: dl-test-remote(+) [/private/var/folders/24/8k48jl6d249_n_qfxwsl6xvm0000gn/T/datalad_temp_test_cached_dataset72gx2h8j/https___github.com_datalad_testrepo--minimalds (git)]
  File "/Users/runner/hostedtoolcache/Python/3.7.10/x64/lib/python3.7/site-packages/datalad/core/local/tests/test_save.py", line 654, in test_partial_unlocked
.: here(+) [git]
    assert_repo_status(ds.path)
.: dl-test-remote(+) [/private/var/folders/24/8k48jl6d249_n_qfxwsl6xvm0000gn/T/datalad_temp_test_cached_dataset72gx2h8j/https___github.com_datalad_testrepo--minimalds (git)]
  File "/Users/runner/hostedtoolcache/Python/3.7.10/x64/lib/python3.7/site-packages/datalad/tests/utils.py", line 1700, in assert_repo_status
.: here(+) [git]
    % (state, state_files, oktobefound))
.: dl-test-remote(+) [/private/var/folders/24/8k48jl6d249_n_qfxwsl6xvm0000gn/T/datalad_temp_test_cached_dataset72gx2h8j/https___github.com_datalad_testrepo--minimalds (git)]
AssertionError: unexpected content of state "modified": [PosixPath('/private/var/folders/24/8k48jl6d249_n_qfxwsl6xvm0000gn/T/datalad_temp_test_partial_unlocked1hjruwg5/culprit.txt')] != []
Versions: annexremote=1.5.0 appdirs=1.4.4 boto=2.49.0 cmd:7z=17.04 cmd:annex=8.20210429-ge811a50e2 cmd:bundled-git=UNKNOWN cmd:git=2.31.1 cmd:system-git=2.31.1 cmd:system-ssh=8.1p1 humanize=3.5.0 iso8601=0.1.14 keyring=23.0.1 keyrings.alt=4.0.2 msgpack=1.0.2 patoolib=1.12 requests=2.25.1 tqdm=4.60.0 wrapt=1.12.1

Obscure filename: str=b' |;&%b5{}\'"\xce\x94\xd7\xa7\xd9\x85\xe0\xb9\x97\xe3\x81\x82 .datc ' repr=' |;&%b5{}\'"Δקم๗あ .datc '
```

**Comment by kyleam** [comment]
I can trigger the failure (intermittently).  The associated change on git-annex's end is 424bef6b6 (smudge: check for known annexed inodes before checking annex.largefiles, 2021-05-03).
