### ISSUE TITLE
test_copy_file_recursion on master fails on windows for fresh git-annex

### ISSUE THREAD

**Issue by yarikoptic** [datalad/datalad#5645]
https://github.com/datalad/git-annex/runs/2515069755?check_suite_focus=true
```
======================================================================
ERROR: datalad.local.tests.test_copy_file.test_copy_file_recursion
----------------------------------------------------------------------
Traceback (most recent call last):
  File "C:\hostedtoolcache\windows\Python\3.7.9\x64\lib\site-packages\nose\case.py", line 198, in runTest
    self.test(*self.arg)
  File "C:\hostedtoolcache\windows\Python\3.7.9\x64\lib\site-packages\datalad\tests\utils.py", line 585, in _wrap_with_tree
    return t(*(arg + (d,)), **kw)
  File "C:\hostedtoolcache\windows\Python\3.7.9\x64\lib\site-packages\datalad\tests\utils.py", line 764, in _wrap_with_tempfile
    return t(*(arg + (filename,)), **kw)
  File "C:\hostedtoolcache\windows\Python\3.7.9\x64\lib\site-packages\datalad\local\tests\test_copy_file.py", line 218, in test_copy_file_recursion
    copy_file([src_ds.pathobj / 'subdir', dest_ds.pathobj], recursive=True)
  File "C:\hostedtoolcache\windows\Python\3.7.9\x64\lib\site-packages\datalad\interface\utils.py", line 486, in eval_func
    return return_func(generator_func)(*args, **kwargs)
  File "C:\hostedtoolcache\windows\Python\3.7.9\x64\lib\site-packages\datalad\interface\utils.py", line 474, in return_func
    results = list(results)
  File "C:\hostedtoolcache\windows\Python\3.7.9\x64\lib\site-packages\datalad\interface\utils.py", line 405, in generator_func
    allkwargs):
  File "C:\hostedtoolcache\windows\Python\3.7.9\x64\lib\site-packages\datalad\interface\utils.py", line 563, in _process_results
    for res in results:
  File "C:\hostedtoolcache\windows\Python\3.7.9\x64\lib\site-packages\datalad\local\copy_file.py", line 299, in __call__
    for res in _copy_file(src_file, dest_file, cache=repo_cache):
  File "C:\hostedtoolcache\windows\Python\3.7.9\x64\lib\site-packages\datalad\local\copy_file.py", line 525, in _copy_file
    finfo, str_src, dest, str_dest, dest_repo_rec)
  File "C:\hostedtoolcache\windows\Python\3.7.9\x64\lib\site-packages\datalad\local\copy_file.py", line 635, in _place_filekey
    ['fromkey', dest_key, str_dest, '--force'],
  File "C:\hostedtoolcache\windows\Python\3.7.9\x64\lib\site-packages\datalad\support\annexrepo.py", line 1056, in _call_annex_records
    raise e
  File "C:\hostedtoolcache\windows\Python\3.7.9\x64\lib\site-packages\datalad\support\annexrepo.py", line 1016, in _call_annex_records
    **kwargs,
  File "C:\hostedtoolcache\windows\Python\3.7.9\x64\lib\site-packages\datalad\support\annexrepo.py", line 916, in _call_annex
    **kwargs)
  File "C:\hostedtoolcache\windows\Python\3.7.9\x64\lib\site-packages\datalad\cmd.py", line 412, in run
    **results,
datalad.support.exceptions.CommandError: CommandError: '"git" "-c" "diff.ignoreSubmodules=none" "annex" "fromkey" "SHA256E-s3--a665a45920422f9d417e4867efdc4fb8a04a1f3fff1fa07e998e86f7f7a27ae3" "C:\Users\runneradmin\AppData\Local\Temp\datalad_temp_dxun39bn\subdir\file1" "--force" "--json" "--json-error-messages" "-c" "annex.dotfiles=true" "-c" "annex.retry=3"' failed with exitcode 1 under C:\Users\runneradmin\AppData\Local\Temp\datalad_temp_dxun39bn [err: 'git-annex: fromkey: 1 failed'] [errors from JSON records: ["['git-annex: C:\\\\Users\\\\runneradmin\\\\AppData\\\\Local\\\\Temp\\\\datalad_temp_dxun39bn\\\\subdir\\\\file1: openBinaryFile: does not exist (No such file or directory)']"]] [info keys: stdout_json]
-------------------- >> begin captured logging << --------------------
asyncio: DEBUG: Using proactor: IocpProactor
asyncio: DEBUG: Using proactor: IocpProactor
asyncio: DEBUG: Using proactor: IocpProactor
...
```
```
 - cmd:annex: 8.20210429-gdab203070
```

**Comment by kyleam** [comment]
This is presumably related to the switch to using `fromkey` in gh-5630.  I'll upgrade to the latest git-annex and verify that the test still passes for me with tools/eval_under_testloopfs`, but I'm guessing this comes down to mishandling windows paths (on either our side or git-annex's).

**Comment by kyleam** [comment]
The immediate failure is because `fromkey` does not create leading directories for pointer files.  I've reported that on the git-annex site, along with a patch:

https://git-annex.branchable.com/bugs/fromkey__58___create_directories_for_pointer_files__63__/

We could work around that easily on our end, but given that the original git-annex commit (4588668a1, 2021-05-03) hasn't yet made it into a release, it may make sense to wait a bit to see if this is addressed quickly on git-annex's end.

Once the above issue is resolved, there's a downstream failure.  I haven't examined it closely yet, but it looks like `annex reinject` may not be working for pointer files.
