### ISSUE TITLE
create-sibling-ria with --shared=group option fails

### ISSUE THREAD

**Issue by loj** [datalad/datalad#5679]
#### What is the problem?

Creating a ria sibling using the `--shared=group` option fails with 
```
[ERROR  ] [Errno 2] No such file or directory: 'chgrp -R ukb /data/project/rehab_biobank/dsstore/8bd/115ec-1bf4-4414-a74e-20f5d272a416': 'chgrp -R ukb /data/project/rehab_biobank/dsstore/8bd/115ec-1bf4-4414-a74e-20f5d272a416' [subprocess.py:_execute_child:1522] (FileNotFoundError)
```
#### What steps will reproduce the problem?
```
mkdir dsstore
datalad create testds && cd testds
datalad create-sibling-ria -s test --shared=group --group ukb "ria+file:///data/project/rehab_biobank/dsstore"
```
<details><summary>with --dbg</summary>
<p>

```
❱ datalad --dbg create-sibling-ria -s test --shared=group --group ukb "ria+file:///data/project/rehab_biobank/dsstore"
[INFO   ] create siblings 'test' and 'test-storage' ... 
Traceback (most recent call last):
  File "/home/loj/.venvs/dl_test/bin/datalad", line 33, in <module>
    sys.exit(load_entry_point('datalad', 'console_scripts', 'datalad')())
  File "/data/project/rehab_biobank/git/datalad/datalad/cmdline/main.py", line 440, in main
    ret = cmdlineargs.func(cmdlineargs)
  File "/data/project/rehab_biobank/git/datalad/datalad/interface/base.py", line 783, in call_from_parser
    ret = list(ret)
  File "/data/project/rehab_biobank/git/datalad/datalad/interface/utils.py", line 393, in generator_func
    for r in _process_results(
  File "/data/project/rehab_biobank/git/datalad/datalad/interface/utils.py", line 563, in _process_results
    for res in results:
  File "/data/project/rehab_biobank/git/datalad/datalad/distributed/create_sibling_ria.py", line 401, in __call__
    yield from _create_sibling_ria(
  File "/data/project/rehab_biobank/git/datalad/datalad/distributed/create_sibling_ria.py", line 683, in _create_sibling_ria
    subprocess.run(chgrp_cmd, cwd=ds.path)
  File "/home/loj/miniconda3/lib/python3.8/subprocess.py", line 489, in run
    with Popen(*popenargs, **kwargs) as process:
  File "/home/loj/miniconda3/lib/python3.8/subprocess.py", line 854, in __init__
    self._execute_child(args, executable, preexec_fn, close_fds,
  File "/home/loj/miniconda3/lib/python3.8/subprocess.py", line 1702, in _execute_child
    raise child_exception_type(errno_num, err_msg, err_filename)
FileNotFoundError: [Errno 2] No such file or directory: 'chgrp -R ukb /data/project/rehab_biobank/dsstore/458/4e035-2925-4063-ba07-f70a9fd59b9c'

> /home/loj/miniconda3/lib/python3.8/subprocess.py(1702)_execute_child()
-> raise child_exception_type(errno_num, err_msg, err_filename)

```
</p>
</details>

#### What version of DataLad are you using?
```
❱ datalad --version
datalad 0.14.4.dev309
```

**Comment by bpoldrack** [comment]
Reproduced. Weird. It's not the path in the actual command call, that doesn't exist.
