### ISSUE TITLE
`get` on a submodule without datalad-id might still lead to KeyError on `id`

### ISSUE THREAD

**Issue by yarikoptic** [datalad/datalad#5710]
```
$> datalad --version
datalad 0.14.4.dev391
```
funny enough - have failed to reproduce the situation/crash on independent runs so might still be something peculiar on how I got into this ;-)

```
(git-annex)lena:/tmp/testds/hcp-100206[master]git-annex
$> datalad get -n hcp-100206-git-annex2
[ERROR  ] 'id' [get.py:_get_flexible_source_candidates_for_submodule:246] (KeyError) 
```

<details>
<summary>full traceback</summary> 

```shell
$> datalad --dbg get -n hcp-100206-git-annex2
Traceback (most recent call last):
  File "/home/yoh/proj/datalad/datalad-master/venvs/dev3/bin/datalad", line 33, in <module>
    sys.exit(load_entry_point('datalad', 'console_scripts', 'datalad')())
  File "/home/yoh/proj/datalad/datalad-master/datalad/cmdline/main.py", line 440, in main
    ret = cmdlineargs.func(cmdlineargs)
  File "/home/yoh/proj/datalad/datalad-master/datalad/interface/base.py", line 783, in call_from_parser
    ret = list(ret)
  File "/home/yoh/proj/datalad/datalad-master/datalad/interface/utils.py", line 396, in generator_func
    for r in _process_results(
  File "/home/yoh/proj/datalad/datalad-master/datalad/interface/utils.py", line 574, in _process_results
    for res in results:
  File "/home/yoh/proj/datalad/datalad-master/datalad/distribution/get.py", line 919, in __call__
    for res in _install_targetpath(
  File "/home/yoh/proj/datalad/datalad-master/datalad/distribution/get.py", line 565, in _install_targetpath
    for res in _install_necessary_subdatasets(
  File "/home/yoh/proj/datalad/datalad-master/datalad/distribution/get.py", line 415, in _install_necessary_subdatasets
    for res in _install_subds_from_flexible_source(
  File "/home/yoh/proj/datalad/datalad-master/datalad/distribution/get.py", line 304, in _install_subds_from_flexible_source
    clone_urls = _get_flexible_source_candidates_for_submodule(ds, sm)
  File "/home/yoh/proj/datalad/datalad-master/datalad/distribution/get.py", line 246, in _get_flexible_source_candidates_for_submodule
    url = tmpl.format(**sm_candidate_props)
KeyError: 'id'

> /home/yoh/proj/datalad/datalad-master/datalad/distribution/get.py(246)_get_flexible_source_candidates_for_submodule()
-> url = tmpl.format(**sm_candidate_props)

```
</details>

and my guess it is so because
```
$> tail -n5 .gitmodules
	datalad-url = "ria+http://store.datalad.org#346a3ae0-2c2e-11ea-a27d-002590496000@git-annex"
[submodule "hcp-100206-git-annex2"]
	path = hcp-100206-git-annex2
	url = http://store.datalad.org/346/a3ae0-2c2e-11ea-a27d-002590496000
	datalad-url = "ria+http://store.datalad.org#346a3ae0-2c2e-11ea-a27d-002590496000@git-annex"
```

so it lacks `datalad-id` because git-annex branch doesn't have it.

but here is a reproducer on the state of that dataset
```
lena:/tmp
$> tar -xzf <(curl --silent http://www.onerussian.com/tmp/hcp-100206-tricky.tgz)
$> cd hcp-100206 
$> datalad get -n hcp-100206-git-annex2                                   
[ERROR  ] 'id' [get.py:_get_flexible_source_candidates_for_submodule:246] (KeyError) 
```

I guess if there is no `datalad-id` - that `_get_flexible_source_candidates_for_submodule` should just skip that candidate.

**Comment by adswa** [comment]
I have only pushed a sketch that probably misses many relevant places, but would #5644 provide a fix for this?

**Comment by adswa** [comment]
I think this issue is the same as #5631, but #5631 has more input, so I'm closing this in favour of #5631 and will adjust the description of that issue
