### ISSUE TITLE
test_rerun_explicit: annex add results in ... and 'foo' are the same file

### ISSUE THREAD

**Issue by yarikoptic** [datalad/datalad#5741]
Triggered while testing a perspective PR #5735  making some annex operations use multiple jobs by default (we stopped doing that awhile back).  Travis in one of the runs failed with
https://travis-ci.com/github/datalad/datalad/jobs/512860710

```
======================================================================
ERROR: datalad.interface.tests.test_rerun.test_rerun_explicit
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/tmp/dl-miniconda-3ofx6_cj/lib/python3.8/site-packages/datalad/support/parallel.py", line 375, in _iter_threads
    raise _FinalShutdown()
datalad.support.parallel._FinalShutdown
During handling of the above exception, another exception occurred:
Traceback (most recent call last):
  File "/tmp/dl-miniconda-3ofx6_cj/lib/python3.8/site-packages/nose/case.py", line 198, in runTest
    self.test(*self.arg)
  File "/tmp/dl-miniconda-3ofx6_cj/lib/python3.8/site-packages/datalad/tests/utils.py", line 1979, in _wrap_skip_if_adjusted_branch
    return func(*args, **kwargs)
  File "/tmp/dl-miniconda-3ofx6_cj/lib/python3.8/site-packages/datalad/tests/utils.py", line 585, in _wrap_with_tree
    return t(*(arg + (d,)), **kw)
  File "/tmp/dl-miniconda-3ofx6_cj/lib/python3.8/site-packages/datalad/interface/tests/test_rerun.py", line 795, in test_rerun_explicit
    ds.rerun(since="", explicit=True)
  File "/tmp/dl-miniconda-3ofx6_cj/lib/python3.8/site-packages/datalad/distribution/dataset.py", line 503, in apply_func
    return f(**kwargs)
  File "/tmp/dl-miniconda-3ofx6_cj/lib/python3.8/site-packages/datalad/interface/utils.py", line 481, in eval_func
    return return_func(generator_func)(*args, **kwargs)
  File "/tmp/dl-miniconda-3ofx6_cj/lib/python3.8/site-packages/datalad/interface/utils.py", line 474, in return_func
    results = list(results)
  File "/tmp/dl-miniconda-3ofx6_cj/lib/python3.8/site-packages/datalad/interface/utils.py", line 393, in generator_func
    for r in _process_results(
  File "/tmp/dl-miniconda-3ofx6_cj/lib/python3.8/site-packages/datalad/interface/utils.py", line 556, in _process_results
    for res in results:
  File "/tmp/dl-miniconda-3ofx6_cj/lib/python3.8/site-packages/datalad/interface/rerun.py", line 257, in __call__
    for res in handler(ds, results):
  File "/tmp/dl-miniconda-3ofx6_cj/lib/python3.8/site-packages/datalad/interface/rerun.py", line 493, in _rerun
    for r in run_command(run_info['cmd'],
  File "/tmp/dl-miniconda-3ofx6_cj/lib/python3.8/site-packages/datalad/core/local/run.py", line 698, in run_command
    for r in Save.__call__(
  File "/tmp/dl-miniconda-3ofx6_cj/lib/python3.8/site-packages/datalad/interface/utils.py", line 393, in generator_func
    for r in _process_results(
  File "/tmp/dl-miniconda-3ofx6_cj/lib/python3.8/site-packages/datalad/interface/utils.py", line 556, in _process_results
    for res in results:
  File "/tmp/dl-miniconda-3ofx6_cj/lib/python3.8/site-packages/datalad/core/local/save.py", line 349, in __call__
    yield from ProducerConsumerProgressLog(
  File "/tmp/dl-miniconda-3ofx6_cj/lib/python3.8/site-packages/datalad/support/parallel.py", line 537, in __iter__
    for res in super().__iter__():
  File "/tmp/dl-miniconda-3ofx6_cj/lib/python3.8/site-packages/datalad/support/parallel.py", line 272, in __iter__
    yield from self._iter_threads(jobs)
  File "/tmp/dl-miniconda-3ofx6_cj/lib/python3.8/site-packages/datalad/support/parallel.py", line 424, in _iter_threads
    self.shutdown(force=True, exception=self._producer_exception or interrupted_by_exception)
  File "/tmp/dl-miniconda-3ofx6_cj/lib/python3.8/site-packages/datalad/support/parallel.py", line 237, in shutdown
    raise exception
  File "/tmp/dl-miniconda-3ofx6_cj/lib/python3.8/site-packages/datalad/support/parallel.py", line 408, in _iter_threads
    done_useful |= self._pop_done_futures(lgr)
  File "/tmp/dl-miniconda-3ofx6_cj/lib/python3.8/site-packages/datalad/support/parallel.py", line 465, in _pop_done_futures
    raise exception
  File "/tmp/dl-miniconda-3ofx6_cj/lib/python3.8/concurrent/futures/thread.py", line 57, in run
    result = self.fn(*self.args, **self.kwargs)
  File "/tmp/dl-miniconda-3ofx6_cj/lib/python3.8/site-packages/datalad/support/parallel.py", line 336, in consumer_worker
    for r in res:
  File "/tmp/dl-miniconda-3ofx6_cj/lib/python3.8/site-packages/datalad/core/local/save.py", line 285, in save_ds
    for res in pds_repo.save_(
  File "/tmp/dl-miniconda-3ofx6_cj/lib/python3.8/site-packages/datalad/support/gitrepo.py", line 4134, in save_
    for r in self._save_add(
  File "/tmp/dl-miniconda-3ofx6_cj/lib/python3.8/site-packages/datalad/support/annexrepo.py", line 3307, in _save_add
    for r in self._call_annex_records(
  File "/tmp/dl-miniconda-3ofx6_cj/lib/python3.8/site-packages/datalad/support/annexrepo.py", line 1122, in _call_annex_records
    raise e
  File "/tmp/dl-miniconda-3ofx6_cj/lib/python3.8/site-packages/datalad/support/annexrepo.py", line 1074, in _call_annex_records
    out = self._call_annex(
  File "/tmp/dl-miniconda-3ofx6_cj/lib/python3.8/site-packages/datalad/support/annexrepo.py", line 970, in _call_annex
    return runner.run_on_filelist_chunks(
  File "/tmp/dl-miniconda-3ofx6_cj/lib/python3.8/site-packages/datalad/cmd.py", line 658, in run_on_filelist_chunks
    res = self.run(
  File "/tmp/dl-miniconda-3ofx6_cj/lib/python3.8/site-packages/datalad/cmd.py", line 408, in run
    raise CommandError(
datalad.support.exceptions.CommandError: CommandError: 'git -c diff.ignoreSubmodules=none annex add --include-dotfiles --json --json-error-messages -c annex.dotfiles=true -c annex.retry=3 -J5 -- foo' failed with exitcode 1 under /tmp/datalad_temp_tree_test_rerun_explicit8i0672ym [err: 'cp: '.git/annex/objects/57/fp/MD5E-s8--97b9b2480e596e0bd0fb2bfe82068538/MD5E-s8--97b9b2480e596e0bd0fb2bfe82068538' and 'foo' are the same file
git-annex: add: 1 failed'] [errors from JSON records: ["['  Unable to restore content of foo; it should be located in .git/annex/objects/57/fp/MD5E-s8--97b9b2480e596e0bd0fb2bfe82068538/MD5E-s8--97b9b2480e596e0bd0fb2bfe82068538', 'git-annex: foo: setSymbolicLinkTimesHiRes: does not exist (No such file or directory)']"]] [info keys: stdout_json]
```

git-annex was quite elderly though: cmd:annex: 7.20190819-ge4cecf8 and DATALAD_RUNTIME_MAX__ANNEX__JOBS=5 so may be a non-issue any longer, just making a note.

**Comment by adswa** [comment]
When I checkout your old branch and rerun this test locally using git annex 8.20211123 I can't trigger this error, both with and without the ``MAX__ANNEX__JOBS`` environment variable. Thus, I'm closing this issue, but please reopen if I am mistaken.
