### ISSUE TITLE
annex add -J5: openFile: resource busy (file is locked)']"]] [info keys: stdout_json]

### ISSUE THREAD

**Issue by yarikoptic** [datalad/datalad#5742]
Triggered in the last run of the travis for #5735 with cmd:annex: 8.20201007-g903b2f1 for multiple tests
https://travis-ci.com/github/datalad/datalad/jobs/512860715

```
======================================================================
ERROR: datalad.tests.test_auto.test_proxying_open_regular(<function test_proxying_open_regular.<locals>.generate_dat at 0x7f2d4c9575e0>, <function test_proxying_open_regular.<locals>.verify_dat at 0x7f2d4c8c3a60>)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/tmp/dl-miniconda-1rlt6bqy/lib/python3.8/site-packages/nose/case.py", line 198, in runTest
    self.test(*self.arg)
  File "/tmp/dl-miniconda-1rlt6bqy/lib/python3.8/site-packages/datalad/tests/utils.py", line 764, in _wrap_with_tempfile
    return t(*(arg + (filename,)), **kw)
  File "/tmp/dl-miniconda-1rlt6bqy/lib/python3.8/site-packages/datalad/tests/test_auto.py", line 125, in _test_proxying_open
    annex.add([fpath1, fpath2])
  File "/tmp/dl-miniconda-1rlt6bqy/lib/python3.8/site-packages/datalad/support/gitrepo.py", line 324, in _wrap_normalize_paths
    result = func(self, files_new, *args, **kwargs)
  File "/tmp/dl-miniconda-1rlt6bqy/lib/python3.8/site-packages/datalad/support/annexrepo.py", line 1564, in add
    return list(self.add_(
  File "/tmp/dl-miniconda-1rlt6bqy/lib/python3.8/site-packages/datalad/support/annexrepo.py", line 1648, in add_
    for r in self._call_annex_records(
  File "/tmp/dl-miniconda-1rlt6bqy/lib/python3.8/site-packages/datalad/support/annexrepo.py", line 1122, in _call_annex_records
    raise e
  File "/tmp/dl-miniconda-1rlt6bqy/lib/python3.8/site-packages/datalad/support/annexrepo.py", line 1074, in _call_annex_records
    out = self._call_annex(
  File "/tmp/dl-miniconda-1rlt6bqy/lib/python3.8/site-packages/datalad/support/annexrepo.py", line 970, in _call_annex
    return runner.run_on_filelist_chunks(
  File "/tmp/dl-miniconda-1rlt6bqy/lib/python3.8/site-packages/datalad/cmd.py", line 658, in run_on_filelist_chunks
    res = self.run(
  File "/tmp/dl-miniconda-1rlt6bqy/lib/python3.8/site-packages/datalad/cmd.py", line 408, in run
    raise CommandError(
datalad.support.exceptions.CommandError: CommandError: 'git -c diff.ignoreSubmodules=none annex add --json --json-error-messages -c annex.dotfiles=true -c annex.retry=3 -J5 -- test d1/d2/test2' failed with exitcode 1 under /tmp/nfsmount/datalad_temp__test_proxying_openb7755nk1 [err: 'git-annex: add: 1 failed'] [errors from JSON records: ["['git-annex: .git/annex/othertmp/5b7_d0f_SHA256E-s3--a665a45920422f9d417e4867efdc4fb8a04a1f3fff1fa07e998e86f7f7a27ae3.log: openFile: resource busy (file is locked)']"]] [info keys: stdout_json]
======================================================================
ERROR: datalad.tests.test_auto.test_proxying_io_open_regular(<function test_proxying_io_open_regular.<locals>.generate_dat at 0x7f2d4c8e03a0>, <function test_proxying_io_open_regular.<locals>.verify_dat at 0x7f2d4c8b85e0>)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/tmp/dl-miniconda-1rlt6bqy/lib/python3.8/site-packages/nose/case.py", line 198, in runTest
    self.test(*self.arg)
  File "/tmp/dl-miniconda-1rlt6bqy/lib/python3.8/site-packages/datalad/tests/utils.py", line 764, in _wrap_with_tempfile
    return t(*(arg + (filename,)), **kw)
  File "/tmp/dl-miniconda-1rlt6bqy/lib/python3.8/site-packages/datalad/tests/test_auto.py", line 125, in _test_proxying_open
    annex.add([fpath1, fpath2])
  File "/tmp/dl-miniconda-1rlt6bqy/lib/python3.8/site-packages/datalad/support/gitrepo.py", line 324, in _wrap_normalize_paths
    result = func(self, files_new, *args, **kwargs)
  File "/tmp/dl-miniconda-1rlt6bqy/lib/python3.8/site-packages/datalad/support/annexrepo.py", line 1564, in add
    return list(self.add_(
  File "/tmp/dl-miniconda-1rlt6bqy/lib/python3.8/site-packages/datalad/support/annexrepo.py", line 1648, in add_
    for r in self._call_annex_records(
  File "/tmp/dl-miniconda-1rlt6bqy/lib/python3.8/site-packages/datalad/support/annexrepo.py", line 1122, in _call_annex_records
    raise e
  File "/tmp/dl-miniconda-1rlt6bqy/lib/python3.8/site-packages/datalad/support/annexrepo.py", line 1074, in _call_annex_records
    out = self._call_annex(
  File "/tmp/dl-miniconda-1rlt6bqy/lib/python3.8/site-packages/datalad/support/annexrepo.py", line 970, in _call_annex
    return runner.run_on_filelist_chunks(
  File "/tmp/dl-miniconda-1rlt6bqy/lib/python3.8/site-packages/datalad/cmd.py", line 658, in run_on_filelist_chunks
    res = self.run(
  File "/tmp/dl-miniconda-1rlt6bqy/lib/python3.8/site-packages/datalad/cmd.py", line 408, in run
    raise CommandError(
datalad.support.exceptions.CommandError: CommandError: 'git -c diff.ignoreSubmodules=none annex add --json --json-error-messages -c annex.dotfiles=true -c annex.retry=3 -J5 -- test d1/d2/test2' failed with exitcode 1 under /tmp/nfsmount/datalad_temp__test_proxying_open1uw2ymfm [err: 'git-annex: add: 1 failed'] [errors from JSON records: ["['git-annex: .git/annex/othertmp/5b7_d0f_SHA256E-s3--a665a45920422f9d417e4867efdc4fb8a04a1f3fff1fa07e998e86f7f7a27ae3.log: openFile: resource busy (file is locked)']"]] [info keys: stdout_json]

======================================================================
ERROR: datalad.tests.test_auto.test_proxying_os_stat(<function test_proxying_os_stat.<locals>.generate_dat at 0x7f2d4c94a8b0>, <function test_proxying_os_stat.<locals>.verify_dat at 0x7f2d4c8b8700>)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/tmp/dl-miniconda-1rlt6bqy/lib/python3.8/site-packages/nose/case.py", line 198, in runTest
    self.test(*self.arg)
  File "/tmp/dl-miniconda-1rlt6bqy/lib/python3.8/site-packages/datalad/tests/utils.py", line 764, in _wrap_with_tempfile
    return t(*(arg + (filename,)), **kw)
  File "/tmp/dl-miniconda-1rlt6bqy/lib/python3.8/site-packages/datalad/tests/test_auto.py", line 125, in _test_proxying_open
    annex.add([fpath1, fpath2])
  File "/tmp/dl-miniconda-1rlt6bqy/lib/python3.8/site-packages/datalad/support/gitrepo.py", line 324, in _wrap_normalize_paths
    result = func(self, files_new, *args, **kwargs)
  File "/tmp/dl-miniconda-1rlt6bqy/lib/python3.8/site-packages/datalad/support/annexrepo.py", line 1564, in add
    return list(self.add_(
  File "/tmp/dl-miniconda-1rlt6bqy/lib/python3.8/site-packages/datalad/support/annexrepo.py", line 1648, in add_
    for r in self._call_annex_records(
  File "/tmp/dl-miniconda-1rlt6bqy/lib/python3.8/site-packages/datalad/support/annexrepo.py", line 1122, in _call_annex_records
    raise e
  File "/tmp/dl-miniconda-1rlt6bqy/lib/python3.8/site-packages/datalad/support/annexrepo.py", line 1074, in _call_annex_records
    out = self._call_annex(
  File "/tmp/dl-miniconda-1rlt6bqy/lib/python3.8/site-packages/datalad/support/annexrepo.py", line 970, in _call_annex
    return runner.run_on_filelist_chunks(
  File "/tmp/dl-miniconda-1rlt6bqy/lib/python3.8/site-packages/datalad/cmd.py", line 658, in run_on_filelist_chunks
    res = self.run(
  File "/tmp/dl-miniconda-1rlt6bqy/lib/python3.8/site-packages/datalad/cmd.py", line 408, in run
    raise CommandError(
datalad.support.exceptions.CommandError: CommandError: 'git -c diff.ignoreSubmodules=none annex add --json --json-error-messages -c annex.dotfiles=true -c annex.retry=3 -J5 -- test d1/d2/test2' failed with exitcode 1 under /tmp/nfsmount/datalad_temp__test_proxying_opendiax6rto [err: 'git-annex: add: 1 failed'] [errors from JSON records: ["['git-annex: .git/annex/othertmp/5b7_d0f_SHA256E-s3--a665a45920422f9d417e4867efdc4fb8a04a1f3fff1fa07e998e86f7f7a27ae3.log: openFile: resource busy (file is locked)']"]] [info keys: stdout_json]
```

**Comment by adswa** [comment]
None of these reproduce locally for me with git annex version 8.20211123 on your old branch from #5735:

```
(handbook2) adina@muninn in ~/repos/datalad on git:remotes/gh-yaricoptic/enh-annex-jobs-auto
❱ DATALAD_RUNTIME_MAX__ANNEX__JOBS=5 python -m nose -s -v datalad/tests/test_auto.py:test_proxying_open_regular
datalad.tests.test_auto.test_proxying_open_regular(<function test_proxying_open_regular.<locals>.generate_dat at 0x7f1482a83dc0>, <function test_proxying_open_regular.<locals>.verify_dat at 0x7f1481604430>) ... ok
Versions: annexremote=1.4.5 appdirs=1.4.4 boto=2.49.0 cmd:7z=16.02 cmd:annex=8.20211123 cmd:bundled-git=UNKNOWN cmd:git=2.34.1 cmd:system-git=2.34.1 cmd:system-ssh=8.7p1 exifread=2.3.2 git=3.1.12 gitdb=4.0.5 humanize=3.2.0 iso8601=0.1.13 keyring=21.8.0 keyrings.alt=UNKNOWN msgpack=1.0.2 mutagen=1.45.1 requests=2.25.1 scrapy=2.5.1 wrapt=1.12.1
Obscure filename: str=b' |;&%b5{}\'"\xce\x94\xd0\x99\xd7\xa7\xd9\x85\xe0\xb9\x97\xe3\x81\x82 .datc ' repr=' |;&%b5{}\'"ΔЙקم๗あ .datc '
Encodings: default='utf-8' filesystem='utf-8' locale.prefered='UTF-8'
Environment: PATH='/home/adina/env/handbook2/bin:/home/adina/.dotfiles/bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/usr/X11R6/bin:/usr/local/games:/usr/games:/home/adina/.local/bin:/home/adina/bin:/snap/bin:/home/adina/repos/latexrun/:/home/adina/node_modules/.bin' LANGUAGE='en_US.UTF-8' LC_CTYPE='en_US.UTF-8' LANG='en_US.UTF-8' LC_ALL='en_US.UTF-8' GIT_CONFIG_PARAMETERS="'init.defaultBranch=dl-test-branch' 'clone.defaultRemoteName=dl-test-remote'"

----------------------------------------------------------------------
Ran 1 test in 2.019s

OK
(handbook2) adina@muninn in ~/repos/datalad on git:remotes/gh-yaricoptic/enh-annex-jobs-auto
❱ DATALAD_RUNTIME_MAX__ANNEX__JOBS=5 python -m nose -s -v datalad/tests/test_auto.py:test_proxying_io_open_regular
datalad.tests.test_auto.test_proxying_io_open_regular(<function test_proxying_io_open_regular.<locals>.generate_dat at 0x7f32ebf1cdc0>, <function test_proxying_io_open_regular.<locals>.verify_dat at 0x7f32eaa9c430>) ... ok
Versions: annexremote=1.4.5 appdirs=1.4.4 boto=2.49.0 cmd:7z=16.02 cmd:annex=8.20211123 cmd:bundled-git=UNKNOWN cmd:git=2.34.1 cmd:system-git=2.34.1 cmd:system-ssh=8.7p1 exifread=2.3.2 git=3.1.12 gitdb=4.0.5 humanize=3.2.0 iso8601=0.1.13 keyring=21.8.0 keyrings.alt=UNKNOWN msgpack=1.0.2 mutagen=1.45.1 requests=2.25.1 scrapy=2.5.1 wrapt=1.12.1
Obscure filename: str=b' |;&%b5{}\'"\xce\x94\xd0\x99\xd7\xa7\xd9\x85\xe0\xb9\x97\xe3\x81\x82 .datc ' repr=' |;&%b5{}\'"ΔЙקم๗あ .datc '
Encodings: default='utf-8' filesystem='utf-8' locale.prefered='UTF-8'
Environment: PATH='/home/adina/env/handbook2/bin:/home/adina/.dotfiles/bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/usr/X11R6/bin:/usr/local/games:/usr/games:/home/adina/.local/bin:/home/adina/bin:/snap/bin:/home/adina/repos/latexrun/:/home/adina/node_modules/.bin' LANGUAGE='en_US.UTF-8' LC_CTYPE='en_US.UTF-8' LANG='en_US.UTF-8' LC_ALL='en_US.UTF-8' GIT_CONFIG_PARAMETERS="'init.defaultBranch=dl-test-branch' 'clone.defaultRemoteName=dl-test-remote'"

----------------------------------------------------------------------
Ran 1 test in 2.698s

OK
(handbook2) adina@muninn in ~/repos/datalad on git:remotes/gh-yaricoptic/enh-annex-jobs-auto
❱ DATALAD_RUNTIME_MAX__ANNEX__JOBS=5 python -m nose -s -v datalad/tests/test_auto.py:test_proxying_os_stat       
datalad.tests.test_auto.test_proxying_os_stat(<function test_proxying_os_stat.<locals>.generate_dat at 0x7f41a850bdc0>, <function test_proxying_os_stat.<locals>.verify_dat at 0x7f41a708c430>) ... ok
Versions: annexremote=1.4.5 appdirs=1.4.4 boto=2.49.0 cmd:7z=16.02 cmd:annex=8.20211123 cmd:bundled-git=UNKNOWN cmd:git=2.34.1 cmd:system-git=2.34.1 cmd:system-ssh=8.7p1 exifread=2.3.2 git=3.1.12 gitdb=4.0.5 humanize=3.2.0 iso8601=0.1.13 keyring=21.8.0 keyrings.alt=UNKNOWN msgpack=1.0.2 mutagen=1.45.1 requests=2.25.1 scrapy=2.5.1 wrapt=1.12.1
Obscure filename: str=b' |;&%b5{}\'"\xce\x94\xd0\x99\xd7\xa7\xd9\x85\xe0\xb9\x97\xe3\x81\x82 .datc ' repr=' |;&%b5{}\'"ΔЙקم๗あ .datc '
Encodings: default='utf-8' filesystem='utf-8' locale.prefered='UTF-8'
Environment: PATH='/home/adina/env/handbook2/bin:/home/adina/.dotfiles/bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/usr/X11R6/bin:/usr/local/games:/usr/games:/home/adina/.local/bin:/home/adina/bin:/snap/bin:/home/adina/repos/latexrun/:/home/adina/node_modules/.bin' LANGUAGE='en_US.UTF-8' LC_CTYPE='en_US.UTF-8' LANG='en_US.UTF-8' LC_ALL='en_US.UTF-8' GIT_CONFIG_PARAMETERS="'init.defaultBranch=dl-test-branch' 'clone.defaultRemoteName=dl-test-remote'"

----------------------------------------------------------------------
Ran 1 test in 2.129s

OK
```

Closing; reopen if I am mistaken, please.
