### ISSUE TITLE
annex add -J5 :  "rename" and "getFileStatus": "does not exist"

### ISSUE THREAD

**Issue by yarikoptic** [datalad/datalad#5743]
continuation to #5742 found while testing #5735 with , while cmd:annex: 8.20201007-g903b2f1 and -J5 
```
======================================================================
ERROR: datalad.tests.test_auto.test_proxying_lzma_LZMAFile(<function test_proxying_lzma_LZMAFile.<locals>.generate_dat at 0x7f2d4c8ee670>, <function test_proxying_lzma_LZMAFile.<locals>.verify_dat at 0x7f2d4c841dc0>)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/tmp/dl-miniconda-1rlt6bqy/lib/python3.8/site-packages/nose/case.py", line 198, in runTest
    self.test(*self.arg)
  File "/tmp/dl-miniconda-1rlt6bqy/lib/python3.8/site-packages/datalad/tests/utils.py", line 764, in _wrap_with_tempfile
    return t(*(arg + (filename,)), **kw)
  File "/tmp/dl-miniconda-1rlt6bqy/lib/python3.8/site-packages/datalad/tests/test_auto.py", line 125, in _test_proxying_open
    annex.add([fpath1, fpath2])
  File "/tmp/dl-miniconda-1rlt6bqy/lib/python3.8/site-packages/datalad/support/gitrepo.py", line 324, in _wrap_normalize_paths
    result = func(self, files_new, *args, **kwargs)
  File "/tmp/dl-miniconda-1rlt6bqy/lib/python3.8/site-packages/datalad/support/annexrepo.py", line 1564, in add
    return list(self.add_(
  File "/tmp/dl-miniconda-1rlt6bqy/lib/python3.8/site-packages/datalad/support/annexrepo.py", line 1648, in add_
    for r in self._call_annex_records(
  File "/tmp/dl-miniconda-1rlt6bqy/lib/python3.8/site-packages/datalad/support/annexrepo.py", line 1122, in _call_annex_records
    raise e
  File "/tmp/dl-miniconda-1rlt6bqy/lib/python3.8/site-packages/datalad/support/annexrepo.py", line 1074, in _call_annex_records
    out = self._call_annex(
  File "/tmp/dl-miniconda-1rlt6bqy/lib/python3.8/site-packages/datalad/support/annexrepo.py", line 970, in _call_annex
    return runner.run_on_filelist_chunks(
  File "/tmp/dl-miniconda-1rlt6bqy/lib/python3.8/site-packages/datalad/cmd.py", line 658, in run_on_filelist_chunks
    res = self.run(
  File "/tmp/dl-miniconda-1rlt6bqy/lib/python3.8/site-packages/datalad/cmd.py", line 408, in run
    raise CommandError(
datalad.support.exceptions.CommandError: CommandError: 'git -c diff.ignoreSubmodules=none annex add --json --json-error-messages -c annex.dotfiles=true -c annex.retry=3 -J5 -- test d1/d2/test2' failed with exitcode 1 under /tmp/nfsmount/datalad_temp__test_proxying_opennme5xlj5 [err: 'git-annex: add: 1 failed'] [errors from JSON records: ["['git-annex: .git/annex/othertmp/fbf_82b_SHA256E-s60--d64328f12ce97f2d1802fda0a42d8d073489f40a23cd3afa8bce12ee0f8b3fe5.log: rename: does not exist (No such file or directory)']"]] [info keys: stdout_json]
```

and possibly unrelated but similar 

```
======================================================================
ERROR: datalad.support.tests.test_annexrepo.test_find_batch_equivalence
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/tmp/dl-miniconda-1rlt6bqy/lib/python3.8/site-packages/nose/case.py", line 198, in runTest
    self.test(*self.arg)
  File "/tmp/dl-miniconda-1rlt6bqy/lib/python3.8/site-packages/datalad/tests/utils.py", line 585, in _wrap_with_tree
    return t(*(arg + (d,)), **kw)
  File "/tmp/dl-miniconda-1rlt6bqy/lib/python3.8/site-packages/datalad/support/tests/test_annexrepo.py", line 537, in test_find_batch_equivalence
    ar.add(files + ["subdir"])
  File "/tmp/dl-miniconda-1rlt6bqy/lib/python3.8/site-packages/datalad/support/gitrepo.py", line 324, in _wrap_normalize_paths
    result = func(self, files_new, *args, **kwargs)
  File "/tmp/dl-miniconda-1rlt6bqy/lib/python3.8/site-packages/datalad/support/annexrepo.py", line 1564, in add
    return list(self.add_(
  File "/tmp/dl-miniconda-1rlt6bqy/lib/python3.8/site-packages/datalad/support/annexrepo.py", line 1648, in add_
    for r in self._call_annex_records(
  File "/tmp/dl-miniconda-1rlt6bqy/lib/python3.8/site-packages/datalad/support/annexrepo.py", line 1122, in _call_annex_records
    raise e
  File "/tmp/dl-miniconda-1rlt6bqy/lib/python3.8/site-packages/datalad/support/annexrepo.py", line 1074, in _call_annex_records
    out = self._call_annex(
  File "/tmp/dl-miniconda-1rlt6bqy/lib/python3.8/site-packages/datalad/support/annexrepo.py", line 970, in _call_annex
    return runner.run_on_filelist_chunks(
  File "/tmp/dl-miniconda-1rlt6bqy/lib/python3.8/site-packages/datalad/cmd.py", line 658, in run_on_filelist_chunks
    res = self.run(
  File "/tmp/dl-miniconda-1rlt6bqy/lib/python3.8/site-packages/datalad/cmd.py", line 408, in run
    raise CommandError(
datalad.support.exceptions.CommandError: CommandError: 'git -c diff.ignoreSubmodules=none annex add --json --json-error-messages -c annex.dotfiles=true -c annex.retry=3 -J5 -- a.txt b ' |;&%b5{}'"'"'"ΔЙקم๗あ .datc ' subdir' failed with exitcode 1 under /tmp/nfsmount/datalad_temp_tree_test_find_batch_equivalence1xd98oie [err: 'git-annex: add: 1 failed'] [errors from JSON records: ["['git-annex: /tmp/nfsmount/datalad_temp_tree_test_find_batch_equivalence1xd98oie/.git/annex/pidlock: getFileStatus: does not exist (No such file or directory)']"]] [info keys: stdout_json]
```

**Comment by adswa** [comment]
I'm not sure if I tried to reproduce these failures correctly, but running them locally on your old branch from #5735 with annex version 8.20211123 succeeds:

```
(handbook2) adina@muninn in ~/repos/datalad on git:remotes/gh-yaricoptic/enh-annex-jobs-auto
❱ DATALAD_RUNTIME_MAX__ANNEX__JOBS=5 python -m nose -s -v datalad/tests/test_auto.py:test_proxying_lzma_LZMAFile 
datalad.tests.test_auto.test_proxying_lzma_LZMAFile(<function test_proxying_lzma_LZMAFile.<locals>.generate_dat at 0x7fe6f8fb6dc0>, <function test_proxying_lzma_LZMAFile.<locals>.verify_dat at 0x7fe6f7b3a3a0>) ... ok
Versions: annexremote=1.4.5 appdirs=1.4.4 boto=2.49.0 cmd:7z=16.02 cmd:annex=8.20211123 cmd:bundled-git=UNKNOWN cmd:git=2.34.1 cmd:system-git=2.34.1 cmd:system-ssh=8.7p1 exifread=2.3.2 git=3.1.12 gitdb=4.0.5 humanize=3.2.0 iso8601=0.1.13 keyring=21.8.0 keyrings.alt=UNKNOWN msgpack=1.0.2 mutagen=1.45.1 requests=2.25.1 scrapy=2.5.1 wrapt=1.12.1
Obscure filename: str=b' |;&%b5{}\'"\xce\x94\xd0\x99\xd7\xa7\xd9\x85\xe0\xb9\x97\xe3\x81\x82 .datc ' repr=' |;&%b5{}\'"ΔЙקم๗あ .datc '
Encodings: default='utf-8' filesystem='utf-8' locale.prefered='UTF-8'
Environment: PATH='/home/adina/env/handbook2/bin:/home/adina/.dotfiles/bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/usr/X11R6/bin:/usr/local/games:/usr/games:/home/adina/.local/bin:/home/adina/bin:/snap/bin:/home/adina/repos/latexrun/:/home/adina/node_modules/.bin' LANGUAGE='en_US.UTF-8' LC_CTYPE='en_US.UTF-8' LANG='en_US.UTF-8' LC_ALL='en_US.UTF-8' GIT_CONFIG_PARAMETERS="'init.defaultBranch=dl-test-branch' 'clone.defaultRemoteName=dl-test-remote'"

----------------------------------------------------------------------
Ran 1 test in 2.836s

OK
DATALAD_RUNTIME_MAX__ANNEX__JOBS=5 python -m nose -s -v   3.00s user 2.27s system 143% cpu 3.674 total
(handbook2) adina@muninn in ~/repos/datalad on git:remotes/gh-yaricoptic/enh-annex-jobs-auto
❱ DATALAD_RUNTIME_MAX__ANNEX__JOBS=5 python -m nose -s -v datalad/support/tests/test_annexrepo.py:test_find_batch_equivalence
datalad.support.tests.test_annexrepo.test_find_batch_equivalence ... ok
Versions: annexremote=1.4.5 appdirs=1.4.4 boto=2.49.0 cmd:7z=16.02 cmd:annex=8.20211123 cmd:bundled-git=UNKNOWN cmd:git=2.34.1 cmd:system-git=2.34.1 cmd:system-ssh=8.7p1 exifread=2.3.2 git=3.1.12 gitdb=4.0.5 humanize=3.2.0 iso8601=0.1.13 keyring=21.8.0 keyrings.alt=UNKNOWN msgpack=1.0.2 mutagen=1.45.1 requests=2.25.1 scrapy=2.5.1 wrapt=1.12.1
Obscure filename: str=b' |;&%b5{}\'"\xce\x94\xd0\x99\xd7\xa7\xd9\x85\xe0\xb9\x97\xe3\x81\x82 .datc ' repr=' |;&%b5{}\'"ΔЙקم๗あ .datc '
Encodings: default='utf-8' filesystem='utf-8' locale.prefered='UTF-8'
Environment: PATH='/home/adina/env/handbook2/bin:/home/adina/.dotfiles/bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/usr/X11R6/bin:/usr/local/games:/usr/games:/home/adina/.local/bin:/home/adina/bin:/snap/bin:/home/adina/repos/latexrun/:/home/adina/node_modules/.bin' LANGUAGE='en_US.UTF-8' LC_CTYPE='en_US.UTF-8' LANG='en_US.UTF-8' LC_ALL='en_US.UTF-8' GIT_CONFIG_PARAMETERS="'init.defaultBranch=dl-test-branch' 'clone.defaultRemoteName=dl-test-remote'"

----------------------------------------------------------------------
Ran 1 test in 0.895s

OK
```

Thus closing, but please reopen if you disagree.
