### ISSUE TITLE
test_annexrepo.test_files_split: annex add -J5 on OSX:  rename: permission denied 

### ISSUE THREAD

**Issue by yarikoptic** [datalad/datalad#5745]
continuation to #5742 found while testing #5735 with , while very new cmd:annex: cmd:annex=8.20210428  and -J5 on OSX
```
2021-06-10T16:54:47.6295090Z ======================================================================
2021-06-10T16:54:47.6296900Z ERROR: datalad.support.tests.test_annexrepo.test_files_split(<class 'datalad.support.annexrepo.AnnexRepo'>,)
2021-06-10T16:54:47.6298390Z ----------------------------------------------------------------------
2021-06-10T16:54:47.6298960Z Traceback (most recent call last):
2021-06-10T16:54:47.6302450Z   File "/Users/runner/hostedtoolcache/Python/3.6.13/x64/lib/python3.6/site-packages/nose/case.py", line 198, in runTest
2021-06-10T16:54:47.6303270Z     self.test(*self.arg)
2021-06-10T16:54:47.6304790Z   File "/Users/runner/hostedtoolcache/Python/3.6.13/x64/lib/python3.6/site-packages/datalad/tests/utils.py", line 585, in _wrap_with_tree
2021-06-10T16:54:47.6305600Z     return t(*(arg + (d,)), **kw)
2021-06-10T16:54:47.6307000Z   File "/Users/runner/hostedtoolcache/Python/3.6.13/x64/lib/python3.6/site-packages/datalad/support/tests/test_annexrepo.py", line 2375, in check_files_split
2021-06-10T16:54:47.6307850Z     r.add(files)
2021-06-10T16:54:47.6309250Z   File "/Users/runner/hostedtoolcache/Python/3.6.13/x64/lib/python3.6/site-packages/datalad/support/gitrepo.py", line 324, in _wrap_normalize_paths
2021-06-10T16:54:47.6310240Z     result = func(self, files_new, *args, **kwargs)
2021-06-10T16:54:47.6311590Z   File "/Users/runner/hostedtoolcache/Python/3.6.13/x64/lib/python3.6/site-packages/datalad/support/annexrepo.py", line 1566, in add
2021-06-10T16:54:47.6312570Z     git_options=git_options, annex_options=annex_options, update=update
2021-06-10T16:54:47.6314150Z   File "/Users/runner/hostedtoolcache/Python/3.6.13/x64/lib/python3.6/site-packages/datalad/support/annexrepo.py", line 1652, in add_
2021-06-10T16:54:47.6315070Z     total_nbytes=sum(expected_additions.values())):
2021-06-10T16:54:47.6316540Z   File "/Users/runner/hostedtoolcache/Python/3.6.13/x64/lib/python3.6/site-packages/datalad/support/annexrepo.py", line 1122, in _call_annex_records
2021-06-10T16:54:47.6317360Z     raise e
2021-06-10T16:54:47.6319110Z   File "/Users/runner/hostedtoolcache/Python/3.6.13/x64/lib/python3.6/site-packages/datalad/support/annexrepo.py", line 1082, in _call_annex_records
2021-06-10T16:54:47.6320160Z     **kwargs,
2021-06-10T16:54:47.6321480Z   File "/Users/runner/hostedtoolcache/Python/3.6.13/x64/lib/python3.6/site-packages/datalad/support/annexrepo.py", line 975, in _call_annex
2021-06-10T16:54:47.6322260Z     **kwargs)
2021-06-10T16:54:47.6323490Z   File "/Users/runner/hostedtoolcache/Python/3.6.13/x64/lib/python3.6/site-packages/datalad/cmd.py", line 663, in run_on_filelist_chunks
2021-06-10T16:54:47.6324220Z     **kwargs)
2021-06-10T16:54:47.6325430Z   File "/Users/runner/hostedtoolcache/Python/3.6.13/x64/lib/python3.6/site-packages/datalad/cmd.py", line 412, in run
2021-06-10T16:54:47.6326150Z     **results,
2021-06-10T16:54:47.9212990Z datalad.support.exceptions.CommandError: CommandError: 'git -c diff.ignoreSubmodules=none annex add --json --json-error-messages -c annex.dotfiles=true -c annex.retry=3 -J3 -- dddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddd064/ffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffff055 
...
failed with exitcode 1 under /private/var/folders/24/8k48jl6d249_n_qfxwsl6xvm0000gn/T/datalad_temp_tree_check_files_splitk_hvme9u [err: 'git-annex: add: 1 failed'] [errors from JSON records: ["['git-annex: .git/annex/othertmp/ingest-fffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffff94498-1: rename: permission denied (Permission denied)']"]] [info keys: stdout_json]
```

There was a recent change to this test in #5734 to go from 10,000 of identical empty keys to 100 unique ones... not sure which was this run ATM.  Needs testing locally etc.

**Comment by adswa** [comment]
I can't try to reproduce this - the branch isn't available to restart the CIs, and I don't have a Mac around. Other test failures arising from that PR (#5741, #5743) didn't reproduce with git annex version 8.20211123 anymore, though. So there might be a chance that this has fixed itself. Maybe someone with a Mac would be in the mood of trying to reproduce this failure locally? 

If I'm not mistaken, the workflow would be 
- check out @yarikoptic old branch (`git co gh-yaricoptic/enh-annex-jobs-auto`)
- run this test with ``DATALAD_RUNTIME_MAX__ANNEX__JOBS=5 `` (``DATALAD_RUNTIME_MAX__ANNEX__JOBS=5 python -m nose -s -v datalad/support/test/test_annexrepo.py:test_files_split``)

**Comment by jsheunis** [comment]
I tested this on my Mac (Big Sur 11.2.3) as follows:

```
git remote add yarik https://github.com/yarikoptic/datalad
git pull yarik
git checkout yarik/enh-annex-jobs-auto
DATALAD_RUNTIME_MAX__ANNEX__JOBS=5 python -m nose -s -v datalad/support/test/test_annexrepo.py:test_files_split
```

which results in the following error:
```
Failure: ImportError (No module named 'test_annexrepo') ... ERROR

======================================================================
ERROR: Failure: ImportError (No module named 'test_annexrepo')
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/Users/jsheunis/opt/miniconda3/envs/dataladneuro/lib/python3.9/site-packages/nose/failure.py", line 39, in runTest
    raise self.exc_val.with_traceback(self.tb)
  File "/Users/jsheunis/opt/miniconda3/envs/dataladneuro/lib/python3.9/site-packages/nose/loader.py", line 417, in loadTestsFromName
    module = self.importer.importFromPath(
  File "/Users/jsheunis/opt/miniconda3/envs/dataladneuro/lib/python3.9/site-packages/nose/importer.py", line 47, in importFromPath
    return self.importFromDir(dir_path, fqname)
  File "/Users/jsheunis/opt/miniconda3/envs/dataladneuro/lib/python3.9/site-packages/nose/importer.py", line 79, in importFromDir
    fh, filename, desc = find_module(part, path)
  File "/Users/jsheunis/opt/miniconda3/envs/dataladneuro/lib/python3.9/imp.py", line 296, in find_module
    raise ImportError(_ERR_MSG.format(name), name=name)
ImportError: No module named 'test_annexrepo'

----------------------------------------------------------------------
Ran 1 test in 0.001s

FAILED (errors=1)
```

Not sure that this is useful...

**Comment by adswa** [comment]
Oh that's just nose not finding the test - I probably wrote down a wrong path. I think it's `tests` not `test`as the subdirectory, i.e. `datalad/support/tests/...`.
Sorry and thanks for trying!

**Comment by jsheunis** [comment]
Thanks for spotting that.

After fixing, this is the failed test output:

```
...
...
failed with exitcode 1 under /private/var/folders/g7/720mm8ns7hg3d28_3yyzkx_r0000gp/T/datalad_temp_tree_check_files_splitas8ouqe_ [err: 'git-annex: add: 1 failed'] [errors from JSON records: ["['git-annex: .git/annex/othertmp/ingest-fffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffff75433-0: rename: permission denied (Permission denied)']"]] [info keys: stdout_json]

----------------------------------------------------------------------
Ran 2 tests in 35.749s

FAILED (errors=1)
```

**Comment by adswa** [comment]
dang, but good to know it still fails :) Just to leave a record, which git-annex version are you using?

**Comment by jsheunis** [comment]
git-annex version: 8.20210310

**Comment by adswa** [comment]
ok sorry to bother you again, but in case its feasible for you, could you update git-annex? That version is older (March 2021) than the original one (April 2021) under which it failed. :see_no_evil: It looks like [brew](https://formulae.brew.sh/formula/git-annex) already has version ``10.20220127`` available.

**Comment by jsheunis** [comment]
woohoo. with `git-annex version: 10.20220127`:

```
>> DATALAD_RUNTIME_MAX__ANNEX__JOBS=5 python -m nose -s -v datalad/support/tests/test_annexrepo.py:test_files_split

datalad.support.tests.test_annexrepo.test_files_split(<class 'datalad.support.gitrepo.GitRepo'>,) ... ok
datalad.support.tests.test_annexrepo.test_files_split(<class 'datalad.support.annexrepo.AnnexRepo'>,) ... ok
Versions: annexremote=1.5.0 appdirs=1.4.4 boto=2.49.0 cmd:7z=17.04 cmd:annex=10.20220127 cmd:bundled-git=UNKNOWN cmd:git=2.31.1 cmd:system-git=2.31.1 cmd:system-ssh=8.1p1 exifread=2.3.2 humanize=3.14.0 iso8601=1.0.2 keyring=23.5.0 keyrings.alt=UNKNOWN msgpack=1.0.3 mutagen=1.45.1 requests=2.27.1 wrapt=1.13.3
Obscure filename: str=b' |;&%b5{}\'"\xce\x94\xd7\xa7\xd9\x85\xe0\xb9\x97\xe3\x81\x82 .datc ' repr=' |;&%b5{}\'"Δקم๗あ .datc '
Encodings: default='utf-8' filesystem='utf-8' locale.prefered='UTF-8'
Environment: LC_TERMINAL_VERSION='3.4.5' LC_CTYPE='en_US.UTF-8' PATH='/Users/jsheunis/.rbenv/shims:/Users/jsheunis/opt/miniconda3/envs/dataladyarik/bin:/Users/jsheunis/opt/miniconda3/condabin:/usr/local/bin:/usr/bin:/bin:/usr/sbin:/sbin:/opt/X11/bin:/Library/Apple/usr/bin:/Users/jsheunis/.dotfiles/bin:/usr/local/sbin:/usr/X11R6/bin:/usr/local/games:/usr/games' LC_TERMINAL='iTerm2' LANG='en_US.UTF-8' LANGUAGE='en_US.UTF-8' LC_ALL='en_US.UTF-8' GIT_CONFIG_PARAMETERS="'init.defaultBranch=dl-test-branch' 'clone.defaultRemoteName=dl-test-remote'"

----------------------------------------------------------------------
Ran 2 tests in 100.528s

OK
```

**Comment by adswa** [comment]
Wohoo! Then this should be good to close :tada:
