### ISSUE TITLE
two fresh failures for maint/release in datalad/git-annex

### ISSUE THREAD

**Issue by yarikoptic** [datalad/datalad#5759]
see e.g. https://github.com/datalad/git-annex/runs/2881114136?check_suite_focus=true

```
ERROR: datalad.distribution.tests.test_create_sibling.test_target_ssh_inherit('backup', False, False)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/opt/hostedtoolcache/Python/3.7.10/x64/lib/python3.7/site-packages/nose/case.py", line 198, in runTest
    self.test(*self.arg)
  File "/opt/hostedtoolcache/Python/3.7.10/x64/lib/python3.7/site-packages/datalad/tests/utils.py", line 764, in _wrap_with_tempfile
    return t(*(arg + (filename,)), **kw)
  File "/opt/hostedtoolcache/Python/3.7.10/x64/lib/python3.7/site-packages/datalad/tests/utils.py", line 764, in _wrap_with_tempfile
    return t(*(arg + (filename,)), **kw)
  File "/opt/hostedtoolcache/Python/3.7.10/x64/lib/python3.7/site-packages/datalad/distribution/tests/test_create_sibling.py", line 624, in _test_target_ssh_inherit
    ds.publish(to=remote)
  File "/opt/hostedtoolcache/Python/3.7.10/x64/lib/python3.7/site-packages/datalad/distribution/dataset.py", line 503, in apply_func
    return f(**kwargs)
  File "/opt/hostedtoolcache/Python/3.7.10/x64/lib/python3.7/site-packages/datalad/interface/utils.py", line 481, in eval_func
    return return_func(generator_func)(*args, **kwargs)
  File "/opt/hostedtoolcache/Python/3.7.10/x64/lib/python3.7/site-packages/datalad/interface/utils.py", line 474, in return_func
    results = list(results)
  File "/opt/hostedtoolcache/Python/3.7.10/x64/lib/python3.7/site-packages/datalad/interface/utils.py", line 461, in generator_func
    msg="Command did not complete successfully")
datalad.support.exceptions.IncompleteResultsError: Command did not complete successfully. 1 failed:
[{'action': 'publish',
  'message': ('failed to push to %s: %s;%s',
              'magical',
              'refs/heads/master -> refs/heads/master [rejected] '
              '(non-fast-forward)',
              " pushed: ['43c9324..5600e27']"),
  'path': '/tmp/datalad_temp__test_target_ssh_inheritdk_6i6mv',
  'refds': '/tmp/datalad_temp__test_target_ssh_inheritdk_6i6mv',
  'status': 'error',
  'type': 'dataset'}]

======================================================================
FAIL: datalad.core.distributed.tests.test_clone.test_reckless(True,)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/opt/hostedtoolcache/Python/3.7.10/x64/lib/python3.7/site-packages/nose/case.py", line 198, in runTest
    self.test(*self.arg)
  File "/opt/hostedtoolcache/Python/3.7.10/x64/lib/python3.7/site-packages/datalad/tests/utils.py", line 764, in _wrap_with_tempfile
    return t(*(arg + (filename,)), **kw)
  File "/opt/hostedtoolcache/Python/3.7.10/x64/lib/python3.7/site-packages/datalad/tests/utils.py", line 764, in _wrap_with_tempfile
    return t(*(arg + (filename,)), **kw)
  File "/opt/hostedtoolcache/Python/3.7.10/x64/lib/python3.7/site-packages/datalad/tests/utils.py", line 764, in _wrap_with_tempfile
    return t(*(arg + (filename,)), **kw)
  File "/opt/hostedtoolcache/Python/3.7.10/x64/lib/python3.7/site-packages/datalad/core/distributed/tests/test_clone.py", line 442, in check_reckless
    & stat.S_IWGRP)
AssertionError: None

----------------------------------------------------------------------
Ran 1264 tests in 3799.074s

FAILED (SKIP=93, errors=1, failures=1)
```

we did release `maint` since then but I guess the difference is due to `git-annex` version change/release

```
(tinuous-dev) datalad@smaug:/mnt/datasets/datalad/ci/git-annex/builds/2021/06$ grep 'Versions:' cron-2021062[12]/build-ubuntu.yaml-*-failed/2_test-datalad\ \(maint\).txt
cron-20210621/build-ubuntu.yaml-315-a1f634dc-failed/2_test-datalad (maint).txt:2021-06-21T04:22:30.3341980Z Versions: annexremote=1.5.0 appdirs=1.4.4 boto=2.49.0 cmd:7z=16.02 cmd:annex=8.20210428+git408-gc5149cfe9-1~ndall+1 cmd:bundled-git=2.24.0 cmd:git=2.24.0 cmd:system-git=2.32.0 cmd:system-ssh=8.2p1 humanize=3.9.0 iso8601=0.1.14 keyring=23.0.1 keyrings.alt=4.0.2 msgpack=1.0.2 patoolib=1.12 requests=2.25.1 tqdm=4.61.1 wrapt=1.12.1
cron-20210622/build-ubuntu.yaml-317-a1f634dc-failed/2_test-datalad (maint).txt:2021-06-22T04:01:41.3931603Z Versions: annexremote=1.5.0 appdirs=1.4.4 boto=2.49.0 cmd:7z=16.02 cmd:annex=8.20210621+git12-g4b1b9d7a8-1~ndall+1 cmd:bundled-git=2.24.0 cmd:git=2.24.0 cmd:system-git=2.32.0 cmd:system-ssh=8.2p1 humanize=3.9.0 iso8601=0.1.14 keyring=23.0.1 keyrings.alt=4.0.2 msgpack=1.0.2 patoolib=1.12 requests=2.25.1 tqdm=4.61.1 wrapt=1.12.1
```

going from `8.20210428+git408-gc5149cfe9-1~ndall+1` to `8.20210621+git12-g4b1b9d7a8-1~ndall+1`

**Comment by yarikoptic** [comment]
started to fail on CI OSX runs since OSX is getting fresh ones.  Eg. https://ci.appveyor.com/project/mih/datalad/builds/39901400/job/yp30hw4gdt7ih2cs  . will try to have a look.  Meanwhile just a gentle tap to @joeyh that those could be regressions in git-annex.

**Comment by yarikoptic** [comment]
re `test_target_ssh_inherit` -- it seems that now during `create_sibling` git-annex (sync? couldn't easily troubleshoot due to [regression --debug output](https://git-annex.branchable.com/bugs/wanted_started_to_dump_debug_output_to_stdout_/)) manages to create a (disconnected) commit on the remote which then what causes datalad's `publish` (well, `git push`) to freak out (left - older annex from 03, right -- from 06)
![image](https://user-images.githubusercontent.com/39889/124835976-2d943f00-df50-11eb-8463-c4907c7fcb4c.png)

**Comment by yarikoptic** [comment]
re 2nd one: filed https://git-annex.branchable.com/bugs/regression__58___index.lck_in_shared-group_is_not_g+w/

**Comment by yarikoptic** [comment]
I believe both are addresses within git annex now, see above referenced annex issues for more info

**Comment by yarikoptic** [comment]
FWIW fixed git annex released, provided by brew, and we switched to be base build osx in Datalad installer, these issues should no longer show their face in CI, but users with a buggy version might hit them... Should we introduce git annex versions black list?
