### ISSUE TITLE
`archive` remote related crash

### ISSUE THREAD

**Issue by mih** [datalad/datalad#5800]
```
% datalad install ///indi/fcon1000
% cd fcon1000
% datalad get AnnArbor_a/sub04111/anat/mprage_anonymized.nii.gz
[INFO   ] scanning for unlocked files (this may take some time)                                                            
install(ok): /tmp/fcon1000/AnnArbor_a (dataset) [Installed subdataset in order to get /tmp/fcon1000/AnnArbor_a/sub04111/anat/mprage_anonymized.nii.gz]
[ERROR  ] 'path' [get.py:__call__:953] (KeyError) 

% git -C AnnArbor_a annex get sub04111/anat/mprage_anonymized.nii.gz 
get sub04111/anat/mprage_anonymized.nii.gz (from datalad-archives...) 
[INFO] To obtain some keys we need to fetch an archive of size 1.6 GB 

  To obtain some keys we need to fetch an archive of size 1.6 GB

  TRANSFER failed with no reason given

  Unable to access these remotes: datalad-archives

  Maybe add some of these git remotes (git remote add ...):
        ccec1cce-6820-4a71-8041-7abd4d6603ac -- yoh@smaug:/mnt/datasets/datalad/crawl/indi/fcon1000/AnnArbor_a
failed
git-annex: get: 1 failed

      % datalad --dbg get AnnArbor_a/sub04111/anat/mprage_anonymized.nii.gz
Traceback (most recent call last):                                                                                         
  File "/home/mih/env/datalad-dev/bin/datalad", line 33, in <module>
    sys.exit(load_entry_point('datalad', 'console_scripts', 'datalad')())
  File "/home/mih/hacking/datalad/git/datalad/cmdline/main.py", line 440, in main
    ret = cmdlineargs.func(cmdlineargs)
  File "/home/mih/hacking/datalad/git/datalad/interface/base.py", line 783, in call_from_parser
    ret = list(ret)
  File "/home/mih/hacking/datalad/git/datalad/interface/utils.py", line 396, in generator_func
    for r in _process_results(
  File "/home/mih/hacking/datalad/git/datalad/interface/utils.py", line 574, in _process_results
    for res in results:
  File "/home/mih/hacking/datalad/git/datalad/distribution/get.py", line 953, in __call__
    if res['path'] not in content_by_ds:
KeyError: 'path'

> /home/mih/hacking/datalad/git/datalad/distribution/get.py(953)__call__()
-> if res['path'] not in content_by_ds:
(Pdb) p res
{'type': 'file', 'logger': <Logger datalad.distribution.get (INFO)>, 'refds': '/tmp/fcon1000', 'status': 'error'}
```

I can replicate the crash with `master` and `maint`. Independent of whether the download failure is justified, the crash is not. The generated result is broken, not `action`, no `path`, no `message`, despite being an error.

**Comment by mih** [comment]
Underlying trigger seems to be `verification of content failed`:

```
% git -C AnnArbor_a annex whereis sub04111/anat/mprage_anonymized.nii.gz        
whereis sub04111/anat/mprage_anonymized.nii.gz (2 copies) 
        ccec1cce-6820-4a71-8041-7abd4d6603ac -- yoh@smaug:/mnt/datasets/datalad/crawl/indi/fcon1000/AnnArbor_a
        f998b99f-33bf-4631-bd02-f72fe3489d9e -- [datalad-archives]

  datalad-archives: dl+archive:MD5E-s1602406400--2e30c496cecbc613c0f8e25bf8e16723.tar#path=sub04111/anat/mprage_anonymized.nii.gz&size=3914814
ok

% git -C AnnArbor_a annex get --key MD5E-s1602406400--2e30c496cecbc613c0f8e25bf8e16723.tar
get MD5E-s1602406400--2e30c496cecbc613c0f8e25bf8e16723.tar (from web...) 

  verification of content failed

  Unable to access these remotes: web

  Maybe add some of these git remotes (git remote add ...):
        ccec1cce-6820-4a71-8041-7abd4d6603ac -- yoh@smaug:/mnt/datasets/datalad/crawl/indi/fcon1000/AnnArbor_a
failed
git-annex: get: 1 failed
```

**Comment by yarikoptic** [comment]
thank you @mih for digging in... The final piece of information is that
```shell
$> git annex whereis --key MD5E-s1602406400--2e30c496cecbc613c0f8e25bf8e16723.tar
whereis MD5E-s1602406400--2e30c496cecbc613c0f8e25bf8e16723.tar (2 copies) 
  	00000000-0000-0000-0000-000000000001 -- web
   	ccec1cce-6820-4a71-8041-7abd4d6603ac -- yoh@smaug:/mnt/datasets/datalad/crawl/indi/fcon1000/AnnArbor_a

  web: http://www.nitrc.org/frs/downloadlink.php/1992
ok
```
and if you go to that link, you would now be needed to authenticate, which I guess was not the case before (attn/question to @chaselgrove : why that changed?) . 

I thought that quick workaround could be to 
<details>
<summary>add that particular download into nitrc provider config</summary> 

```patch
diff --git a/datalad/downloaders/configs/nitrc.cfg b/datalad/downloaders/configs/nitrc.cfg
index a97e16bf8..fbbd2e121 100644
--- a/datalad/downloaders/configs/nitrc.cfg
+++ b/datalad/downloaders/configs/nitrc.cfg
@@ -9,7 +9,7 @@
 # (upon each login) to download files -- so we need to figure out how
 # to accomplish the mission here
 url_re = https?://fcon_1000\.projects\.nitrc\.org/indi/adhd200/index\.html
-         https?://www\.nitrc\.org/frs/downloadlink\.php/(7058|3075|3479|9108)
+         https?://www\.nitrc\.org/frs/downloadlink\.php/(7058|3075|3479|9108|1992)
 credential = nitrc
 authentication_type = html_form
 html_form_url = https://www.nitrc.org/account/login.php
```
</details>
and enable `datalad` special remote, but it would not be sufficient since git-annex already knows that it is (was) available straight from `web` so it doesn't even try `datalad`. 

anyways -- let's wait for NITRC guru to reply -- may be it could just go back to non-authenticated access?

**Comment by mih** [comment]
Thanks for drilling down on this. Whatever fix will be adopted for the trigger, I think this error code path needs to be robustified to address the observed crash too.

**Comment by mih** [comment]
With #6165 this is now:

```
% datalad get AnnArbor_a/sub04111/anat/mprage_anonymized.nii.gz
get(error): AnnArbor_a/sub04111/anat/mprage_anonymized.nii.gz (file) [Failed to fetch any archive containing MD5E-s3914814--4d687b2607e63b2e3385f917fe206ceb.nii.gz. Tried: ['MD5E-s1602406400--2e30c496cecbc613c0f8e25bf8e16723.tar']
Failed to fetch any archive containing MD5E-s3914814--4d687b2607e63b2e3385f917fe206ceb.nii.gz. Tried: ['MD5E-s1602406400--2e30c496cecbc613c0f8e25bf8e16723.tar']
Failed to fetch any archive containing MD5E-s3914814--4d687b2607e63b2e3385f917fe206ceb.nii.gz. Tried: ['MD5E-s1602406400--2e30c496cecbc613c0f8e25bf8e16723.tar']]
action summary:
  get (error: 1, notneeded: 1)
```

because of our blunt `annex.retry=3` setting, this still takes forever to error out, still looks stupid with the error triplet, but no longer crashes.

Importantly, the reason is communicated (at least in debug, and of course three times!):

```
% git -C AnnArbor_a annex --debug get sub04111/anat/mprage_anonymized.nii.gz 2>&1 | grep verification
[2021-11-09 22:12:54.80054493] (Annex.ExternalAddonProcess) /home/mih/env/datalad-dev/bin/git-annex-remote-datalad-archives[1] --> DEBUG Failed to fetch MD5E-s1602406400--2e30c496cecbc613c0f8e25bf8e16723.tar containing MD5E-s3914814--4d687b2607e63b2e3385f917fe206ceb.nii.gz: CommandError(CommandError: 'git -c diff.ignoreSubmodules=none annex get --json --json-progress --key MD5E-s1602406400--2e30c496cecbc613c0f8e25bf8e16723.tar -c annex.dotfiles=true' failed with exitcode 1 under /tmp/fcon1000/AnnArbor_a [info keys: stdout_json]|> from web...|Unable to access these remotes: web| [err: 'verification of content failed|  downloading from all 1 known url(s) failed|  verification of content failed|  downloading from all 1 known url(s) failed|  verification of content failed|  downloading from all 1 known url(s) failed|get: 1 failed'])
[2021-11-09 22:12:54.800641699] (Remote.External) Failed to fetch MD5E-s1602406400--2e30c496cecbc613c0f8e25bf8e16723.tar containing MD5E-s3914814--4d687b2607e63b2e3385f917fe206ceb.nii.gz: CommandError(CommandError: 'git -c diff.ignoreSubmodules=none annex get --json --json-progress --key MD5E-s1602406400--2e30c496cecbc613c0f8e25bf8e16723.tar -c annex.dotfiles=true' failed with exitcode 1 under /tmp/fcon1000/AnnArbor_a [info keys: stdout_json]|> from web...|Unable to access these remotes: web| [err: 'verification of content failed|  downloading from all 1 known url(s) failed|  verification of content failed|  downloading from all 1 known url(s) failed|  verification of content failed|  downloading from all 1 known url(s) failed|get: 1 failed'])
```
