### ISSUE TITLE
Testing on Windows - non-existent path?

### ISSUE THREAD

**Issue by adswa** [datalad/datalad#5806]
I tried to run tests on our shared Windows box, but I can't get the tests to run. I am using an Anaconda prompt, with an editable install of today's master. Initially, I thought I would just be doing the testcall wrong. But it worked with the previously installed 0.13.5, and stopped working after a git pull to a recent master. Have you seen this before, @mih or @yarikoptic , or does anyone spot what I may be doing wrong?

Here is what I am seeing:
```

(base) C:\Users\datalads\repos\datalad>python -m nose --traverse-namespace -a -v datalad
Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "C:\Users\datalads\miniconda3\lib\multiprocessing\spawn.py", line 116, in spawn_main
    exitcode = _main(fd, parent_sentinel)
  File "C:\Users\datalads\miniconda3\lib\multiprocessing\spawn.py", line 126, in _main
    self = reduction.pickle.load(from_parent)
  File "C:\Users\datalads\repos\datalad\datalad\__init__.py", line 50, in <module>
    from .log import lgr
  File "C:\Users\datalads\repos\datalad\datalad\log.py", line 574, in <module>
    lgr = LoggerHelper().get_initialized_logger()
  File "C:\Users\datalads\repos\datalad\datalad\log.py", line 555, in get_initialized_logger
    ColorFormatter(use_color=use_color,
  File "C:\Users\datalads\repos\datalad\datalad\log.py", line 154, in __init__
    msg = colors.format_msg(self._get_format(log_name, log_pid),
  File "C:\Users\datalads\repos\datalad\datalad\support\ansi_colors.py", line 64, in format_msg
    if color_enabled() and use_color:
  File "C:\Users\datalads\repos\datalad\datalad\support\ansi_colors.py", line 57, in color_enabled
    ui_color = cfg.obtain('datalad.ui.color')
  File "C:\Users\datalads\repos\datalad\datalad\config.py", line 489, in obtain
    from datalad.interface.common_cfg import definitions as cfg_defs
  File "C:\Users\datalads\repos\datalad\datalad\interface\common_cfg.py", line 525, in <module>
    compute_cfg_defaults()
  File "C:\Users\datalads\repos\datalad\datalad\interface\common_cfg.py", line 522, in compute_cfg_defaults
    value['default'] = def_fn()
  File "C:\Users\datalads\repos\datalad\datalad\interface\common_cfg.py", line 105, in <lambda>
    'default_fn': lambda: dirs.user_cache_dir,
  File "C:\Users\datalads\miniconda3\lib\site-packages\appdirs.py", line 439, in user_cache_dir
    return user_cache_dir(self.appname, self.appauthor,
  File "C:\Users\datalads\miniconda3\lib\site-packages\appdirs.py", line 293, in user_cache_dir
    path = os.path.normpath(_get_win_folder("CSIDL_LOCAL_APPDATA"))
  File "C:\Users\datalads\miniconda3\lib\site-packages\appdirs.py", line 481, in _get_win_folder_with_pywin32
    dir = shell.SHGetFolderPath(0, getattr(shellcon, csidl_name), 0, 0)
pywintypes.com_error: (-2147024893, 'Das System kann den angegebenen Pfad nicht finden.', None, None)

----------------------------------------------------------------------
Ran 0 tests in 7.502s

OK

```

Funnily enough, it worked fine in the previously installed 0.13.5 version of datalad (started, and CTRL-C'd it shortly afterwards):

```

(base) C:\Users\datalads\repos\datalad>python -m nose -s -v --traverse-namespace .
Failure: SkipTest () ... SKIP
datalad.cmdline.tests.test_helpers.test_strip_arg_from_argv ... ok
datalad.cmdline.tests.test_helpers.test_get_repo_instance_annex ... Versions: annexremote=1.2.1 appdirs=1.4.4 boto=2.49.0 cmd:7z=19.00 cmd:annex=8.20201008-g7e24b2587 cmd:bundled-git=UNKNOWN cmd:git=2.29.2.windows.1 cmd:system-git=2.29.2.windows.1 cmd:system-ssh=for exifread=2.1.2 humanize=3.1.0 iso8601=0.1.13 keyring=21.4.0 keyrings.alt=3.1 msgpack=1.0.0 mutagen=1.41.1 patoolib=1.12 requests=2.23.0 tqdm=4.46.0 wrapt=1.12.1
Obscure filename: str=b";&%b5{}'.datc" repr=";&%b5{}'.datc"
Encodings: default='utf-8' filesystem='utf-8' locale.prefered='cp1252'
Environment: PATH='C:\\Users\\datalads\\miniconda3;C:\\Users\\datalads\\miniconda3\\Library\\mingw-w64\\bin;C:\\Users\\datalads\\miniconda3\\Library\\usr\\bin;C:\\Users\\datalads\\miniconda3\\Library\\bin;C:\\Users\\datalads\\miniconda3\\Scripts;C:\\Users\\datalads\\miniconda3\\bin;C:\\Users\\datalads\\miniconda3\\condabin;C:\\Program Files (x86)\\Intel\\Intel(R) Management Engine Components\\iCLS;C:\\Program Files\\Intel\\Intel(R) Management Engine Components\\iCLS;C:\\WINDOWS\\system32;C:\\WINDOWS;C:\\WINDOWS\\System32\\Wbem;C:\\WINDOWS\\System32\\WindowsPowerShell\\v1.0;C:\\WINDOWS\\System32\\OpenSSH;C:\\Program Files (x86)\\Intel\\Intel(R) Management Engine Components\\DAL;C:\\Program Files\\Intel\\Intel(R) Management Engine Components\\DAL;C:\\Program Files (x86)\\Intel\\Intel(R) Management Engine Components\\IPT;C:\\Program Files\\Intel\\Intel(R) Management Engine Components\\IPT;C:\\Program Files\\Git\\cmd;C:\\Users\\datalads\\miniconda3;C:\\Users\\datalads\\miniconda3\\Library\\mingw-w64\\bin;C:\\Users\\datalads\\miniconda3\\Library\\usr\\bin;C:\\Users\\datalads\\miniconda3\\Library\\bin;C:\\Users\\datalads\\miniconda3\\Scripts;C:\\Users\\datalads\\AppData\\Local\\Microsoft\\WindowsApps;.' GIT_CONFIG_PARAMETERS="'init.defaultBranch=dl-test-branch'"

----------------------------------------------------------------------
Ran 3 tests in 6.464s

```

**Comment by yarikoptic** [comment]
never saw it. smells like a bug in appdirs not guarding for non-existing folders ... I would've
- try with `--pdb --pdb-errors` and if it manages to fall under pdb -- see which path it talks about, but I guess you could also re-trigger it by doing that `dirs.user_cache_dir` request which it fails on
- searched up in appdirs etc on this issue, and if not there -- file one to see what authors think

**Comment by adswa** [comment]
Thanks. I couldn't get anywhere near pdb, and the remote connection to the Windows box doesn't make this anyhow pleasant. I asked in https://github.com/ActiveState/appdirs/issues/167 whether someone had encountered this before.

**Comment by adswa** [comment]
I don't know what caused the original problem, but reinstalling everything fixed it. It may have been an automatic (?) update from Windows 10 to Windows 11 that broke things...
