### ISSUE TITLE
test_runner_stdin_no_capture errors out while testing master on datalad/git-annex (github actions)

### ISSUE THREAD

**Issue by yarikoptic** [datalad/datalad#5810]
e.g. https://github.com/datalad/git-annex/runs/3130248890?check_suite_focus=true recently added in 0.14.4-477-gcdde06b73
seems to be failing only on ubuntu

```
======================================================================
ERROR: datalad.tests.test_witless_runner.test_runner_stdin_no_capture
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/opt/hostedtoolcache/Python/3.7.11/x64/lib/python3.7/site-packages/nose/case.py", line 198, in runTest
    self.test(*self.arg)
  File "/opt/hostedtoolcache/Python/3.7.11/x64/lib/python3.7/site-packages/nose/tools/nontrivial.py", line 97, in newfunc
    result = func(*arg, **kw)
  File "/opt/hostedtoolcache/Python/3.7.11/x64/lib/python3.7/site-packages/datalad/tests/test_witless_runner.py", line 162, in test_runner_stdin_no_capture
    protocol=None
  File "/opt/hostedtoolcache/Python/3.7.11/x64/lib/python3.7/site-packages/datalad/cmd.py", line 172, in run
    **results,
datalad.support.exceptions.CommandError: CommandError: '/opt/hostedtoolcache/Python/3.7.11/x64/bin/python -c 'import sys; print(sys.stdin.read())'' failed with exitcode 1
```

and consistently so

```shell
(git)smaug:/mnt/btrfs/datasets/datalad/ci/git-annex[master]builds/2021
$> cd 07
cron-20210701/  cron-20210703/  cron-20210705/  cron-20210707/  cron-20210709/  cron-20210711/  cron-20210713/  cron-20210715/  cron-20210717/  cron-20210719/  cron-20210721/  pr-70/  pr-UNK/
cron-20210702/  cron-20210704/  cron-20210706/  cron-20210708/  cron-20210710/  cron-20210712/  cron-20210714/  cron-20210716/  cron-20210718/  cron-20210720/  cron-20210722/  pr-72/

$> git grep test_runner_stdin_no_capture
cron-20210721/build-macos.yaml-360-69466103-failed/1_test-datalad (master).txt:2021-07-21T05:03:24.6620130Z datalad.tests.test_witless_runner.test_runner_stdin_no_capture ... ok
cron-20210721/build-macos.yaml-360-69466103-failed/test-datalad (master)/11_Run datalad tests.txt:2021-07-21T05:03:24.6620040Z datalad.tests.test_witless_runner.test_runner_stdin_no_capture ... ok
cron-20210721/build-ubuntu.yaml-352-69466103-failed/1_test-datalad (master).txt:2021-07-21T04:07:03.8113230Z datalad.tests.test_witless_runner.test_runner_stdin_no_capture ... Traceback (most recent call last):
cron-20210721/build-ubuntu.yaml-352-69466103-failed/1_test-datalad (master).txt:2021-07-21T04:10:36.3041083Z ERROR: datalad.tests.test_witless_runner.test_runner_stdin_no_capture
cron-20210721/build-ubuntu.yaml-352-69466103-failed/1_test-datalad (master).txt:2021-07-21T04:10:36.3050465Z   File "/opt/hostedtoolcache/Python/3.7.11/x64/lib/python3.7/site-packages/datalad/tests/test_witless_runner.py", line 162, in test_runner_stdin_no_capture
cron-20210721/build-ubuntu.yaml-352-69466103-failed/test-datalad (master)/12_Run datalad tests.txt:2021-07-21T04:07:03.8113207Z datalad.tests.test_witless_runner.test_runner_stdin_no_capture ... Traceback (most recent call last):
cron-20210721/build-ubuntu.yaml-352-69466103-failed/test-datalad (master)/12_Run datalad tests.txt:2021-07-21T04:10:36.3041079Z ERROR: datalad.tests.test_witless_runner.test_runner_stdin_no_capture
cron-20210721/build-ubuntu.yaml-352-69466103-failed/test-datalad (master)/12_Run datalad tests.txt:2021-07-21T04:10:36.3050457Z   File "/opt/hostedtoolcache/Python/3.7.11/x64/lib/python3.7/site-packages/datalad/tests/test_witless_runner.py", line 162, in test_runner_stdin_no_capture
cron-20210721/build-windows.yaml-323-69466103-failed/1_test-datalad (master).txt:2021-07-21T06:12:17.3062736Z datalad.tests.test_witless_runner.test_runner_stdin_no_capture ... ok
cron-20210721/build-windows.yaml-323-69466103-failed/test-datalad (master)/21_Run datalad tests.txt:2021-07-21T06:12:17.3062650Z datalad.tests.test_witless_runner.test_runner_stdin_no_capture ... ok
cron-20210722/build-macos.yaml-361-69466103-success/1_test-datalad (master).txt:2021-07-22T05:04:44.3417940Z datalad.tests.test_witless_runner.test_runner_stdin_no_capture ... ok
cron-20210722/build-macos.yaml-361-69466103-success/test-datalad (master)/11_Run datalad tests.txt:2021-07-22T05:04:44.3417900Z datalad.tests.test_witless_runner.test_runner_stdin_no_capture ... ok
cron-20210722/build-ubuntu.yaml-353-69466103-failed/1_test-datalad (master).txt:2021-07-22T03:53:44.1467324Z datalad.tests.test_witless_runner.test_runner_stdin_no_capture ... Traceback (most recent call last):
cron-20210722/build-ubuntu.yaml-353-69466103-failed/1_test-datalad (master).txt:2021-07-22T03:56:25.4199762Z ERROR: datalad.tests.test_witless_runner.test_runner_stdin_no_capture
cron-20210722/build-ubuntu.yaml-353-69466103-failed/1_test-datalad (master).txt:2021-07-22T03:56:25.4206667Z   File "/opt/hostedtoolcache/Python/3.7.11/x64/lib/python3.7/site-packages/datalad/tests/test_witless_runner.py", line 162, in test_runner_stdin_no_capture
cron-20210722/build-ubuntu.yaml-353-69466103-failed/test-datalad (master)/12_Run datalad tests.txt:2021-07-22T03:53:44.1467304Z datalad.tests.test_witless_runner.test_runner_stdin_no_capture ... Traceback (most recent call last):
cron-20210722/build-ubuntu.yaml-353-69466103-failed/test-datalad (master)/12_Run datalad tests.txt:2021-07-22T03:56:25.4199758Z ERROR: datalad.tests.test_witless_runner.test_runner_stdin_no_capture
cron-20210722/build-ubuntu.yaml-353-69466103-failed/test-datalad (master)/12_Run datalad tests.txt:2021-07-22T03:56:25.4206658Z   File "/opt/hostedtoolcache/Python/3.7.11/x64/lib/python3.7/site-packages/datalad/tests/test_witless_runner.py", line 162, in test_runner_stdin_no_capture
cron-20210722/build-windows.yaml-324-69466103-failed/1_test-datalad (master).txt:2021-07-22T06:21:28.4374257Z datalad.tests.test_witless_runner.test_runner_stdin_no_capture ... ok
cron-20210722/build-windows.yaml-324-69466103-failed/test-datalad (master)/21_Run datalad tests.txt:2021-07-22T06:21:28.4374161Z datalad.tests.test_witless_runner.test_runner_stdin_no_capture ... ok
```

looking into actual log files for the moment of invocation I see
```
2021-07-21T04:07:03.8113230Z datalad.tests.test_witless_runner.test_runner_stdin_no_capture ... Traceback (most recent call last):
2021-07-21T04:07:03.8115209Z   File "<string>", line 1, in <module>
2021-07-21T04:07:03.8116438Z BlockingIOError: [Errno 11] write could not complete without blocking
2021-07-21T04:07:03.8162062Z ERROR
@                                                                                            
```

any ideas/clues @christian-monch ?  I haven't tried to analyze yet to grasp why fails there and not on travis/appveyor ... but it seems we do not run this test in actions anywhere/how besides in datalad/git-annex

tested locally [*] for that test alone and was "suprised" that it dumps into my face lots of text regardless if I try running nose with -s or without .  

Also does it really need `'ABCDEFGHIJKLMNOPQRSTUVWXYZ-' * 10000` that long ? (that explains slow `git grep` I guess ;)) -- those get captured in the log files, makes them large, and also harder to analyze. 

[*] didn't reproduce with  3.9 and custom built 3.8 ... `tools/ci/bisect-python.sh` failed at pip installation stage on 3.7.11 when I tried to initiate such env

**Comment by adswa** [comment]
I don't know where that test went, but it doesn't seem to be part of the code base anymore. Thus, this issue seems obsolete and I will close it. Please reopen if I am mistaken.
