### ISSUE TITLE
CommandError when using conditional includes in git config

### ISSUE THREAD

**Issue by matrss** [datalad/datalad#5854]
#### What is the problem?

I have a conditional include in my git configuration, that sets a different e-mail address when $PWD is a specific directory:
```
[includeIf "gitdir:~/some_dir/"]
        path = "some_file"
```
`some_file` just contains a different `[user]` section for the configuration.

As long as I have this in my config I get a `CommandError` for any `datalad` command:
```
$ datalad
Traceback (most recent call last):
  File "/home/matrss/.conda/envs/datalad/bin/datalad", line 7, in <module>
    from datalad.cmdline.main import main
  File "/home/matrss/.conda/envs/datalad/lib/python3.9/site-packages/datalad/__init__.py", line 48, in <module>
    cfg = ConfigManager()
  File "/home/matrss/.conda/envs/datalad/lib/python3.9/site-packages/datalad/config.py", line 346, in __init__
    self.reload(force=True)
  File "/home/matrss/.conda/envs/datalad/lib/python3.9/site-packages/datalad/config.py", line 399, in reload
    self._stores[store_id] = self._reload(runargs)
  File "/home/matrss/.conda/envs/datalad/lib/python3.9/site-packages/datalad/config.py", line 427, in _reload
    stdout, stderr = self._run(
  File "/home/matrss/.conda/envs/datalad/lib/python3.9/site-packages/datalad/config.py", line 789, in _run
    out = self._runner.run(self._config_cmd + args, **kwargs)
  File "/home/matrss/.conda/envs/datalad/lib/python3.9/site-packages/datalad/cmd.py", line 408, in run
    raise CommandError(
datalad.support.exceptions.CommandError: CommandError: 'git --git-dir= config -z -l --show-origin' failed with exitcode 128 [err: 'fatal: The empty string is not a valid path']
```

#### What steps will reproduce the problem?

Adding a conditional include to the git config like above.

#### What version of DataLad are you using (run `datalad --version`)? On what operating system (consider running `datalad wtf`)?

0.14.6

**Comment by bpoldrack** [comment]
Thanks for reporting, @matrss 

First, I can confirm the issue. Somehow, `git config` can't deal with `--git-dir=` when evaluating that condition and we need to address that.

However, you said that your intend is to match $PWD. Note, that `gitdir` is NOT referring to PWD, but to the `.git` directory you're running on (which may not exist). This may have the desired effect the way you use it (particularly if `~/some_dir` is a repository itself), but it's not what git really does and may not do what you want in some cases.

**Comment by bpoldrack** [comment]
Regarding a fix for `ConfigManager` an additional note:
`git config -l` does show the `includeIf` directive itself regardless of condition evaluation:
`includeif.gitdir:~/somewhere/.path=~/somewhere/some_file`
Not sure about implications yet, but we may want to exclude such "config vars".

**Comment by matrss** [comment]
> Note, that gitdir is NOT referring to PWD, but to the .git directory you're running on (which may not exist).

Right, I miss-remembered how it works exactly. In my case, `~/some_dir/` is a directory which contains all my work related git repositories, the `includeIf` should work recursively for all repositories there due to the trailing slash in the path, I think. That way, I set my mail address in git correspondingly, based on the repo path.
