### ISSUE TITLE
`test_ria_http` fails on Windows with recent master and latest git-annex

### ISSUE THREAD

**Issue by mih** [datalad/datalad#5898]
```
======================================================================
FAIL: datalad.core.distributed.tests.test_clone.test_ria_http
----------------------------------------------------------------------
Traceback (most recent call last):
  File "C:\Users\datalads\AppData\Local\Programs\Python\Python39\lib\site-packages\nose\case.py", line 198, in runTest
    self.test(*self.arg)
  File "C:\Users\datalads\repos\datalad\datalad\tests\utils.py", line 560, in _wrap_with_tree
    return t(*(arg + (d,)), **kw)
  File "C:\Users\datalads\repos\datalad\datalad\tests\utils.py", line 739, in _wrap_with_tempfile
    return t(*(arg + (filename,)), **kw)
  File "C:\Users\datalads\repos\datalad\datalad\tests\utils.py", line 672, in _wrap_serve_path_via_http
    return tfunc(*(args + (path, url)), **kwargs)
  File "C:\Users\datalads\repos\datalad\datalad\core\distributed\tests\test_clone.py", line 859, in test_ria_http
    assert_in("not found in upstream", str(cme.exception))
AssertionError: 'not found in upstream' not found in "Command did not complete successfully. 1 failed:\r\n[{'action': 'install',\n  'message': ('Failed to clone from any candidate source URL. Encountered '\n              'errors per each url were:\\n'\n              '- %s',\n              'http://127.0.0.1:58960/6c6/48994-a3f3-410f-b754-398c14fc5d62\\n'\n              '  \\n'\n              '- '\n              'http://127.0.0.1:58960/6c6/48994-a3f3-410f-b754-398c14fc5d62/.git\\n'\n              '  '),\n  'path': 'C:\\\\Users\\\\datalads\\\\AppData\\\\Local\\\\Temp\\\\datalad_temp_tree_c7_ytoua\\\\clone_failed',\n  'source_url': 'ria+http://127.0.0.1:58960/#6c648994-a3f3-410f-b754-398c14fc5d62@impossible',\n  'status': 'error',\n  'type': 'dataset'}]"
-------------------- >> begin captured logging << --------------------
fasteners.process_lock: Level 5: Acquired file lock `b'C:\\Users\\datalads\\AppData\\Local\\datalad.org\\datalad\\Cache\\locks\\downloader-auth.lck'` after waiting 0.000s [1 attempts were required]
fasteners.process_lock: Level 5: Unlocked and closed file lock open on `b'C:\\Users\\datalads\\AppData\\Local\\datalad.org\\datalad\\Cache\\locks\\downloader-auth.lck'`
urllib3.connectionpool: DEBUG: Starting new HTTP connection (1): 127.0.0.1:58960
urllib3.connectionpool: DEBUG: http://127.0.0.1:58960 "GET /6c6/48994-a3f3-410f-b754-398c14fc5d62/config HTTP/1.1" 200 375
fasteners.process_lock: Level 5: Acquired file lock `b'C:\\Users\\datalads\\AppData\\Local\\datalad.org\\datalad\\Cache\\locks\\downloader-auth.lck'` after waiting 0.000s [1 attempts were required]
fasteners.process_lock: Level 5: Unlocked and closed file lock open on `b'C:\\Users\\datalads\\AppData\\Local\\datalad.org\\datalad\\Cache\\locks\\downloader-auth.lck'`
urllib3.connectionpool: DEBUG: Resetting dropped connection: 127.0.0.1
urllib3.connectionpool: DEBUG: http://127.0.0.1:58960 "GET /860/ab826-0155-4b82-b5ed-5aaf334cd991/config HTTP/1.1" 200 390
fasteners.process_lock: Level 5: Acquired file lock `b'C:\\Users\\datalads\\AppData\\Local\\datalad.org\\datalad\\Cache\\locks\\downloader-auth.lck'` after waiting 0.000s [1 attempts were required]
fasteners.process_lock: Level 5: Unlocked and closed file lock open on `b'C:\\Users\\datalads\\AppData\\Local\\datalad.org\\datalad\\Cache\\locks\\downloader-auth.lck'`
urllib3.connectionpool: DEBUG: Resetting dropped connection: 127.0.0.1
urllib3.connectionpool: DEBUG: http://127.0.0.1:58960 "GET /6c6/48994-a3f3-410f-b754-398c14fc5d62/config HTTP/1.1" 200 375
fasteners.process_lock: Level 5: Acquired file lock `b'C:\\Users\\datalads\\AppData\\Local\\datalad.org\\datalad\\Cache\\locks\\downloader-auth.lck'` after waiting 0.000s [1 attempts were required]
fasteners.process_lock: Level 5: Unlocked and closed file lock open on `b'C:\\Users\\datalads\\AppData\\Local\\datalad.org\\datalad\\Cache\\locks\\downloader-auth.lck'`
urllib3.connectionpool: DEBUG: Resetting dropped connection: 127.0.0.1
urllib3.connectionpool: DEBUG: http://127.0.0.1:58960 "GET /6c6/48994-a3f3-410f-b754-398c14fc5d62/config HTTP/1.1" 200 375
datalad.core.distributed.clone: ERROR: Failed to clone from any candidate source URL. Encountered errors per each url were:
- http://127.0.0.1:58960/6c6/48994-a3f3-410f-b754-398c14fc5d62

- http://127.0.0.1:58960/6c6/48994-a3f3-410f-b754-398c14fc5d62/.git
   [install(C:\Users\datalads\AppData\Local\Temp\datalad_temp_tree_c7_ytoua\clone_failed)]
--------------------- >> end captured logging << ---------------------

```

**Comment by adswa** [comment]
Don't know what happened in between but the test is fine on a recent build, e.g., https://ci.appveyor.com/project/mih/datalad/branch/master/job/c29gdackxpgjhstt

**Comment by adswa** [comment]
Checking another [recent build](https://ci.appveyor.com/project/mih/datalad/builds/45310268/job/vcqoi9klks5o6529), I only see

```
[gw0] PASSED ..\datalad\core\distributed\tests\test_clone.py::test_ria_http 
```

It also passes locally on a windows machine.
I'll close this issue, but feel free to reopen if my assessment is wrong or another failure surfaces.
