### ISSUE TITLE
test_get_open_files() fails on Windows (github actions of datalad/git-annex testing)

### ISSUE THREAD

**Issue by yarikoptic** [datalad/datalad#5926]
we had a similar fail before in #4192 but it was due to shortened paths, and was mitigated.
Now that I am adding forgotten `psutil` (and more) into that testing environment in https://github.com/datalad/git-annex/pull/75 we got it failing there as

```
2021-08-20T04:03:50.7670939Z ======================================================================
2021-08-20T04:03:50.7671889Z ERROR: datalad.tests.test_utils.test_get_open_files
2021-08-20T04:03:50.7673060Z ----------------------------------------------------------------------
2021-08-20T04:03:50.7673972Z Traceback (most recent call last):
2021-08-20T04:03:50.7677286Z   File "C:\hostedtoolcache\windows\Python\3.7.9\x64\lib\site-packages\nose\case.py", line 198, in runTest
2021-08-20T04:03:50.7678506Z     self.test(*self.arg)
2021-08-20T04:03:50.7679666Z   File "C:\hostedtoolcache\windows\Python\3.7.9\x64\lib\site-packages\datalad\tests\utils.py", line 585, in _wrap_with_tree
2021-08-20T04:03:50.7680752Z     return t(*(arg + (d,)), **kw)
2021-08-20T04:03:50.7681929Z   File "C:\hostedtoolcache\windows\Python\3.7.9\x64\lib\site-packages\datalad\tests\test_utils.py", line 1198, in test_get_open_files
2021-08-20T04:03:50.7683173Z     eq_(get_open_files(p, log_open=40)[str(f1.resolve())].pid,
2021-08-20T04:03:50.7684217Z KeyError: 'C:\\Users\\runneradmin\\AppData\\Local\\Temp\\datalad_temp_tree_muae08r9\\1'
```

I think the first step would be to RF that test that it becomes possible to figure WTF is going on from the failure without debugging...

**Comment by yarikoptic** [comment]
Pushed a new branch to troubleshoot on without sending a PR http://github.com/yarikoptic/datalad/pull/new/rf-test-open-files

eh, just a non-informative
https://github.com/datalad/git-annex/pull/75/checks?check_run_id=3383845175#step:20:94

```
AssertionError: 'C:\\Users\\runneradmin\\AppData\\Local\\Temp\\datalad_temp_tree_ew2p2xmf\\1' not found in {}
```
so needs more digging.

**Comment by adswa** [comment]
Don't know what happened in between, but the tests seems fine in a recent Windows build:
https://ci.appveyor.com/project/mih/datalad/branch/master/job/xe9o28jd5e81u05t

```
datalad.tests.test_utils.test_get_open_files ... ok
```

**Comment by adswa** [comment]
Given that this test was fine the last time I checked, I think we can close this issue. Please reopen if I am mistaken.
