### ISSUE TITLE
unicode encoding fiascos on a sample CentOS system 

### ISSUE THREAD

**Issue by yarikoptic** [datalad/datalad#5942]
Well, the system is somewhat unique, which lead to a number of recent issues/workarounds at git-annex level, see e.g. [xattr issue](https://git-annex.branchable.com/bugs/__34__357_out_of_984_tests_failed__34___on_NFS_lustre_mount/) but these particular ones seems to be all relating to some assumptions we have where we either need to instrument tests a bit differently or address them some other way

<details>
<summary>selection of tests failures all of some UnicodeEncodeError</summary> 

```shell
======================================================================
ERROR: datalad.support.tests.test_globbedpaths.test_globbedpaths
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/dartfs-hpc/rc/home/v/d31548v/.conda/envs/datalad/lib/python3.9/site-packages/nose/case.py", line 197, in runTest
    self.test(*self.arg)
  File "/dartfs-hpc/rc/home/v/d31548v/.conda/envs/datalad/lib/python3.9/site-packages/datalad/tests/utils.py", line 583, in _wrap_with_tree
    create_tree(d, tree, archives_leading_dir=archives_leading_dir)
  File "/dartfs-hpc/rc/home/v/d31548v/.conda/envs/datalad/lib/python3.9/site-packages/datalad/utils.py", line 2420, in create_tree
    with open_func(full_name, "wb") as f:
UnicodeEncodeError: 'latin-1' codec can't encode character '\u03b2' in position 90: ordinal not in range(256)

======================================================================
ERROR: datalad.support.tests.test_network.test_get_local_file_url
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/dartfs-hpc/rc/home/v/d31548v/.conda/envs/datalad/lib/python3.9/site-packages/nose/case.py", line 197, in runTest
    self.test(*self.arg)
  File "/dartfs-hpc/rc/home/v/d31548v/.conda/envs/datalad/lib/python3.9/site-packages/datalad/support/tests/test_network.py", line 477, in test_get_local_file_url
    print("D: %s" % path)
UnicodeEncodeError: 'latin-1' codec can't encode characters in position 12-17: ordinal not in range(256)

======================================================================
ERROR: datalad.tests.test_config.test_something
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/dartfs-hpc/rc/home/v/d31548v/.conda/envs/datalad/lib/python3.9/site-packages/nose/case.py", line 197, in runTest
    self.test(*self.arg)
  File "/dartfs-hpc/rc/home/v/d31548v/.conda/envs/datalad/lib/python3.9/site-packages/datalad/tests/utils.py", line 585, in _wrap_with_tree
    return t(*(arg + (d,)), **kw)
  File "/dartfs-hpc/rc/home/v/d31548v/.conda/envs/datalad/lib/python3.9/site-packages/datalad/tests/utils.py", line 764, in _wrap_with_tempfile
    return t(*(arg + (filename,)), **kw)
  File "/dartfs-hpc/rc/home/v/d31548v/.conda/envs/datalad/lib/python3.9/site-packages/datalad/tests/test_config.py", line 184, in test_something
    cfg.add('something.new', '\u306e')
  File "/dartfs-hpc/rc/home/v/d31548v/.conda/envs/datalad/lib/python3.9/site-packages/datalad/config.py", line 855, in add
    self._run(['--add', var, value], where=where, reload=reload,
  File "/dartfs-hpc/rc/home/v/d31548v/.conda/envs/datalad/lib/python3.9/site-packages/datalad/config.py", line 807, in _run
    out = self._runner.run(self._config_cmd + args, **kwargs)
  File "/dartfs-hpc/rc/home/v/d31548v/.conda/envs/datalad/lib/python3.9/site-packages/datalad/cmd.py", line 379, in run
    results = event_loop.run_until_complete(
  File "/dartfs-hpc/rc/home/v/d31548v/.conda/envs/datalad/lib/python3.9/asyncio/base_events.py", line 642, in run_until_complete
    return future.result()
  File "/dartfs-hpc/rc/home/v/d31548v/.conda/envs/datalad/lib/python3.9/site-packages/datalad/cmd.py", line 102, in run_async_cmd
    transport, protocol = await proc
  File "/dartfs-hpc/rc/home/v/d31548v/.conda/envs/datalad/lib/python3.9/asyncio/base_events.py", line 1661, in subprocess_exec
    transport = await self._make_subprocess_transport(
  File "/dartfs-hpc/rc/home/v/d31548v/.conda/envs/datalad/lib/python3.9/asyncio/unix_events.py", line 197, in _make_subprocess_transport
    transp = _UnixSubprocessTransport(self, protocol, args, shell,
  File "/dartfs-hpc/rc/home/v/d31548v/.conda/envs/datalad/lib/python3.9/asyncio/base_subprocess.py", line 36, in __init__
    self._start(args=args, shell=shell, stdin=stdin, stdout=stdout,
  File "/dartfs-hpc/rc/home/v/d31548v/.conda/envs/datalad/lib/python3.9/asyncio/unix_events.py", line 789, in _start
    self._proc = subprocess.Popen(
  File "/dartfs-hpc/rc/home/v/d31548v/.conda/envs/datalad/lib/python3.9/subprocess.py", line 951, in __init__
    self._execute_child(args, executable, preexec_fn, close_fds,
  File "/dartfs-hpc/rc/home/v/d31548v/.conda/envs/datalad/lib/python3.9/subprocess.py", line 1754, in _execute_child
    self.pid = _posixsubprocess.fork_exec(
UnicodeEncodeError: 'latin-1' codec can't encode character '\u306e' in position 0: ordinal not in range(256)

======================================================================
ERROR: datalad.tests.test_witless_runner.test_runner
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/dartfs-hpc/rc/home/v/d31548v/.conda/envs/datalad/lib/python3.9/site-packages/nose/case.py", line 197, in runTest
    self.test(*self.arg)
  File "/dartfs-hpc/rc/home/v/d31548v/.conda/envs/datalad/lib/python3.9/site-packages/datalad/tests/utils.py", line 1244, in _wrap_assert_cwd_unchanged
    raise exc_info[1]
  File "/dartfs-hpc/rc/home/v/d31548v/.conda/envs/datalad/lib/python3.9/site-packages/datalad/tests/utils.py", line 1216, in _wrap_assert_cwd_unchanged
    ret = func(*args, **kwargs)
  File "/dartfs-hpc/rc/home/v/d31548v/.conda/envs/datalad/lib/python3.9/site-packages/datalad/tests/utils.py", line 764, in _wrap_with_tempfile
    return t(*(arg + (filename,)), **kw)
  File "/dartfs-hpc/rc/home/v/d31548v/.conda/envs/datalad/lib/python3.9/site-packages/datalad/tests/test_witless_runner.py", line 61, in test_runner
    res = runner.run(cmd)
  File "/dartfs-hpc/rc/home/v/d31548v/.conda/envs/datalad/lib/python3.9/site-packages/datalad/cmd.py", line 379, in run
    results = event_loop.run_until_complete(
  File "/dartfs-hpc/rc/home/v/d31548v/.conda/envs/datalad/lib/python3.9/asyncio/base_events.py", line 642, in run_until_complete
    return future.result()
  File "/dartfs-hpc/rc/home/v/d31548v/.conda/envs/datalad/lib/python3.9/site-packages/datalad/cmd.py", line 102, in run_async_cmd
    transport, protocol = await proc
  File "/dartfs-hpc/rc/home/v/d31548v/.conda/envs/datalad/lib/python3.9/asyncio/base_events.py", line 1628, in subprocess_shell
    transport = await self._make_subprocess_transport(
  File "/dartfs-hpc/rc/home/v/d31548v/.conda/envs/datalad/lib/python3.9/asyncio/unix_events.py", line 197, in _make_subprocess_transport
    transp = _UnixSubprocessTransport(self, protocol, args, shell,
  File "/dartfs-hpc/rc/home/v/d31548v/.conda/envs/datalad/lib/python3.9/asyncio/base_subprocess.py", line 36, in __init__
    self._start(args=args, shell=shell, stdin=stdin, stdout=stdout,
  File "/dartfs-hpc/rc/home/v/d31548v/.conda/envs/datalad/lib/python3.9/asyncio/unix_events.py", line 789, in _start
    self._proc = subprocess.Popen(
  File "/dartfs-hpc/rc/home/v/d31548v/.conda/envs/datalad/lib/python3.9/subprocess.py", line 951, in __init__
    self._execute_child(args, executable, preexec_fn, close_fds,
  File "/dartfs-hpc/rc/home/v/d31548v/.conda/envs/datalad/lib/python3.9/subprocess.py", line 1754, in _execute_child
    self.pid = _posixsubprocess.fork_exec(
UnicodeEncodeError: 'latin-1' codec can't encode character '\u6771' in position 16: ordinal not in range(256)

======================================================================
ERROR: datalad.core.local.tests.test_diff.test_diff_nonexistent_ref_unicode
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/dartfs-hpc/rc/home/v/d31548v/.conda/envs/datalad/lib/python3.9/site-packages/nose/case.py", line 197, in runTest
    self.test(*self.arg)
  File "/dartfs-hpc/rc/home/v/d31548v/.conda/envs/datalad/lib/python3.9/site-packages/datalad/tests/utils.py", line 764, in _wrap_with_tempfile
    return t(*(arg + (filename,)), **kw)
  File "/dartfs-hpc/rc/home/v/d31548v/.conda/envs/datalad/lib/python3.9/site-packages/datalad/core/local/tests/test_diff.py", line 510, in test_diff_nonexistent_ref_unicode
    ds.diff(fr="HEAD", to=u"\u03b2", on_failure="ignore", result_renderer=None),
  File "/dartfs-hpc/rc/home/v/d31548v/.conda/envs/datalad/lib/python3.9/site-packages/datalad/distribution/dataset.py", line 503, in apply_func
    return f(**kwargs)
  File "/dartfs-hpc/rc/home/v/d31548v/.conda/envs/datalad/lib/python3.9/site-packages/datalad/interface/utils.py", line 481, in eval_func
    return return_func(generator_func)(*args, **kwargs)
  File "/dartfs-hpc/rc/home/v/d31548v/.conda/envs/datalad/lib/python3.9/site-packages/datalad/interface/utils.py", line 474, in return_func
    results = list(results)
  File "/dartfs-hpc/rc/home/v/d31548v/.conda/envs/datalad/lib/python3.9/site-packages/datalad/interface/utils.py", line 393, in generator_func
    for r in _process_results(
  File "/dartfs-hpc/rc/home/v/d31548v/.conda/envs/datalad/lib/python3.9/site-packages/datalad/interface/utils.py", line 556, in _process_results
    for res in results:
  File "/dartfs-hpc/rc/home/v/d31548v/.conda/envs/datalad/lib/python3.9/site-packages/datalad/core/local/diff.py", line 130, in __call__
    yield from diff_dataset(
  File "/dartfs-hpc/rc/home/v/d31548v/.conda/envs/datalad/lib/python3.9/site-packages/datalad/core/local/diff.py", line 270, in diff_dataset
    for res in _diff_ds(
  File "/dartfs-hpc/rc/home/v/d31548v/.conda/envs/datalad/lib/python3.9/site-packages/datalad/core/local/diff.py", line 312, in _diff_ds
    diff_state = repo.diffstatus(
  File "/dartfs-hpc/rc/home/v/d31548v/.conda/envs/datalad/lib/python3.9/site-packages/datalad/support/gitrepo.py", line 3700, in diffstatus
    to_state = self.get_content_info(
  File "/dartfs-hpc/rc/home/v/d31548v/.conda/envs/datalad/lib/python3.9/site-packages/datalad/support/gitrepo.py", line 3429, in get_content_info
    stdout = self.call_git(
  File "/dartfs-hpc/rc/home/v/d31548v/.conda/envs/datalad/lib/python3.9/site-packages/datalad/support/gitrepo.py", line 2199, in call_git
    out, _ = self._call_git(args, files,
  File "/dartfs-hpc/rc/home/v/d31548v/.conda/envs/datalad/lib/python3.9/site-packages/datalad/support/gitrepo.py", line 2140, in _call_git
    res = runner.run(
  File "/dartfs-hpc/rc/home/v/d31548v/.conda/envs/datalad/lib/python3.9/site-packages/datalad/cmd.py", line 379, in run
    results = event_loop.run_until_complete(
  File "/dartfs-hpc/rc/home/v/d31548v/.conda/envs/datalad/lib/python3.9/asyncio/base_events.py", line 642, in run_until_complete
    return future.result()
  File "/dartfs-hpc/rc/home/v/d31548v/.conda/envs/datalad/lib/python3.9/site-packages/datalad/cmd.py", line 102, in run_async_cmd
    transport, protocol = await proc
  File "/dartfs-hpc/rc/home/v/d31548v/.conda/envs/datalad/lib/python3.9/asyncio/base_events.py", line 1661, in subprocess_exec
    transport = await self._make_subprocess_transport(
  File "/dartfs-hpc/rc/home/v/d31548v/.conda/envs/datalad/lib/python3.9/asyncio/unix_events.py", line 197, in _make_subprocess_transport
    transp = _UnixSubprocessTransport(self, protocol, args, shell,
  File "/dartfs-hpc/rc/home/v/d31548v/.conda/envs/datalad/lib/python3.9/asyncio/base_subprocess.py", line 36, in __init__
    self._start(args=args, shell=shell, stdin=stdin, stdout=stdout,
  File "/dartfs-hpc/rc/home/v/d31548v/.conda/envs/datalad/lib/python3.9/asyncio/unix_events.py", line 789, in _start
    self._proc = subprocess.Popen(
  File "/dartfs-hpc/rc/home/v/d31548v/.conda/envs/datalad/lib/python3.9/subprocess.py", line 951, in __init__
    self._execute_child(args, executable, preexec_fn, close_fds,
  File "/dartfs-hpc/rc/home/v/d31548v/.conda/envs/datalad/lib/python3.9/subprocess.py", line 1754, in _execute_child
    self.pid = _posixsubprocess.fork_exec(
UnicodeEncodeError: 'latin-1' codec can't encode character '\u03b2' in position 0: ordinal not in range(256)

======================================================================
ERROR: datalad.core.local.tests.test_run.test_py2_unicode_command
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/dartfs-hpc/rc/home/v/d31548v/.conda/envs/datalad/lib/python3.9/site-packages/nose/case.py", line 197, in runTest
    self.test(*self.arg)
  File "/dartfs-hpc/rc/home/v/d31548v/.conda/envs/datalad/lib/python3.9/site-packages/datalad/tests/utils.py", line 764, in _wrap_with_tempfile
    return t(*(arg + (filename,)), **kw)
  File "/dartfs-hpc/rc/home/v/d31548v/.conda/envs/datalad/lib/python3.9/site-packages/datalad/core/local/tests/test_run.py", line 159, in test_py2_unicode_command
    ds.run(cmd_str)
  File "/dartfs-hpc/rc/home/v/d31548v/.conda/envs/datalad/lib/python3.9/site-packages/datalad/distribution/dataset.py", line 503, in apply_func
    return f(**kwargs)
  File "/dartfs-hpc/rc/home/v/d31548v/.conda/envs/datalad/lib/python3.9/site-packages/datalad/interface/utils.py", line 481, in eval_func
    return return_func(generator_func)(*args, **kwargs)
  File "/dartfs-hpc/rc/home/v/d31548v/.conda/envs/datalad/lib/python3.9/site-packages/datalad/interface/utils.py", line 474, in return_func
    results = list(results)
  File "/dartfs-hpc/rc/home/v/d31548v/.conda/envs/datalad/lib/python3.9/site-packages/datalad/interface/utils.py", line 393, in generator_func
    for r in _process_results(
  File "/dartfs-hpc/rc/home/v/d31548v/.conda/envs/datalad/lib/python3.9/site-packages/datalad/interface/utils.py", line 556, in _process_results
    for res in results:
  File "/dartfs-hpc/rc/home/v/d31548v/.conda/envs/datalad/lib/python3.9/site-packages/datalad/core/local/run.py", line 237, in __call__
    for r in run_command(cmd, dataset=dataset,
  File "/dartfs-hpc/rc/home/v/d31548v/.conda/envs/datalad/lib/python3.9/site-packages/datalad/core/local/run.py", line 617, in run_command
    cmd_exitcode, exc = _execute_command(
  File "/dartfs-hpc/rc/home/v/d31548v/.conda/envs/datalad/lib/python3.9/site-packages/datalad/core/local/run.py", line 467, in _execute_command
    runner.run(
  File "/dartfs-hpc/rc/home/v/d31548v/.conda/envs/datalad/lib/python3.9/site-packages/datalad/cmd.py", line 379, in run
    results = event_loop.run_until_complete(
  File "/dartfs-hpc/rc/home/v/d31548v/.conda/envs/datalad/lib/python3.9/asyncio/base_events.py", line 642, in run_until_complete
    return future.result()
  File "/dartfs-hpc/rc/home/v/d31548v/.conda/envs/datalad/lib/python3.9/site-packages/datalad/cmd.py", line 102, in run_async_cmd
    transport, protocol = await proc
  File "/dartfs-hpc/rc/home/v/d31548v/.conda/envs/datalad/lib/python3.9/asyncio/base_events.py", line 1628, in subprocess_shell
    transport = await self._make_subprocess_transport(
  File "/dartfs-hpc/rc/home/v/d31548v/.conda/envs/datalad/lib/python3.9/asyncio/unix_events.py", line 197, in _make_subprocess_transport
    transp = _UnixSubprocessTransport(self, protocol, args, shell,
  File "/dartfs-hpc/rc/home/v/d31548v/.conda/envs/datalad/lib/python3.9/asyncio/base_subprocess.py", line 36, in __init__
    self._start(args=args, shell=shell, stdin=stdin, stdout=stdout,
  File "/dartfs-hpc/rc/home/v/d31548v/.conda/envs/datalad/lib/python3.9/asyncio/unix_events.py", line 789, in _start
    self._proc = subprocess.Popen(
  File "/dartfs-hpc/rc/home/v/d31548v/.conda/envs/datalad/lib/python3.9/subprocess.py", line 951, in __init__
    self._execute_child(args, executable, preexec_fn, close_fds,
  File "/dartfs-hpc/rc/home/v/d31548v/.conda/envs/datalad/lib/python3.9/subprocess.py", line 1754, in _execute_child
    self.pid = _posixsubprocess.fork_exec(
UnicodeEncodeError: 'latin-1' codec can't encode character '\u03b2' in position 112: ordinal not in range(256)

```
</details>

```
(datalad) [d31548v@discovery7 _test_]$ locale
LANG=en_US
LC_CTYPE="en_US"
LC_NUMERIC="en_US"
LC_TIME="en_US"
LC_COLLATE="en_US"
LC_MONETARY="en_US"
LC_MESSAGES="en_US"
LC_PAPER="en_US"
LC_NAME="en_US"
LC_ADDRESS="en_US"
LC_TELEPHONE="en_US"
LC_MEASUREMENT="en_US"
LC_IDENTIFICATION="en_US"
LC_ALL=
```

<details>
<summary>WTF</summary> 

## credentials 
  - keyring: 
    - active_backends: 
      - PlaintextKeyring with no encyption v.1.0 at /dartfs-hpc/rc/home/v/d31548v/.local/share/python_keyring/keyring_pass.cfg
    - config_file: /dartfs-hpc/rc/home/v/d31548v/.config/python_keyring/keyringrc.cfg
    - data_root: /dartfs-hpc/rc/home/v/d31548v/.local/share/python_keyring
## datalad 
  - full_version: 0.14.7
  - version: 0.14.7
## dependencies 
  - annexremote: 1.5.0
  - appdirs: 1.4.4
  - boto: 2.49.0
  - cmd:7z: 16.02
  - cmd:annex: 8.20210803+git153-g63c2cfd47-1~ndall+1
  - cmd:bundled-git: UNKNOWN
  - cmd:git: 2.24.0
  - cmd:system-git: 2.24.0
  - cmd:system-ssh: 8.6p1
  - exifread: 2.1.2
  - humanize: 3.5.0
  - iso8601: 0.1.13
  - keyring: 23.0.1
  - keyrings.alt: 4.0.2
  - msgpack: 1.0.2
  - mutagen: 1.45.0
  - requests: 2.25.1
  - wrapt: 1.12.1
## environment 
  - LANG: en_US
  - PATH: /dartfs-hpc/rc/home/v/d31548v/bin/git-annex/8.20210803+git153-g63c2cfd47-1/usr/lib/git-annex.linux/:/dartfs-hpc/rc/home/v/d31548v/.conda/envs/datalad/bin:/optnfs/common/miniconda3-datalad/condabin:/dartfs-hpc/admin/opt/el7/intel/compilers_and_libraries_2018.1.163/linux/bin/intel64:/usr/local/bin:/usr/lib64/qt-3.3/bin:/opt/java/latest/bin:/usr/local/bin:/usr/bin:/usr/local/sbin:/usr/sbin:/opt/bin:/opt/slurm/bin:/dartfs-hpc/admin/etc/cluster_files/scripts:/dartfs-hpc/admin/local/bin:/dartfs-hpc/rc/home/v/d31548v/bin
## git-annex 
  - build flags: 
    - Assistant
    - Webapp
    - Pairing
    - Inotify
    - DBus
    - DesktopNotify
    - TorrentParser
    - MagicMime
    - Feeds
    - Testsuite
    - S3
    - WebDAV
  - dependency versions: 
    - aws-0.20
    - bloomfilter-2.0.1.0
    - cryptonite-0.25
    - DAV-1.3.3
    - feed-1.0.0.0
    - ghc-8.4.4
    - http-client-0.5.13.1
    - persistent-sqlite-2.8.2
    - torrent-10000.1.1
    - uuid-1.3.13
    - yesod-1.6.0
  - key/value backends: 
    - SHA256E
    - SHA256
    - SHA512E
    - SHA512
    - SHA224E
    - SHA224
    - SHA384E
    - SHA384
    - SHA3_256E
    - SHA3_256
    - SHA3_512E
    - SHA3_512
    - SHA3_224E
    - SHA3_224
    - SHA3_384E
    - SHA3_384
    - SKEIN256E
    - SKEIN256
    - SKEIN512E
    - SKEIN512
    - BLAKE2B256E
    - BLAKE2B256
    - BLAKE2B512E
    - BLAKE2B512
    - BLAKE2B160E
    - BLAKE2B160
    - BLAKE2B224E
    - BLAKE2B224
    - BLAKE2B384E
    - BLAKE2B384
    - BLAKE2BP512E
    - BLAKE2BP512
    - BLAKE2S256E
    - BLAKE2S256
    - BLAKE2S160E
    - BLAKE2S160
    - BLAKE2S224E
    - BLAKE2S224
    - BLAKE2SP256E
    - BLAKE2SP256
    - BLAKE2SP224E
    - BLAKE2SP224
    - SHA1E
    - SHA1
    - MD5E
    - MD5
    - WORM
    - URL
    - X*
  - operating system: linux x86_64
  - remote types: 
    - git
    - gcrypt
    - p2p
    - S3
    - bup
    - directory
    - rsync
    - web
    - bittorrent
    - webdav
    - adb
    - tahoe
    - glacier
    - ddar
    - git-lfs
    - httpalso
    - borg
    - hook
    - external
  - supported repository versions: 
    - 8
  - upgrade supported from repository versions: 
    - 0
    - 1
    - 2
    - 3
    - 4
    - 5
    - 6
    - 7
  - version: 8.20210803+git153-g63c2cfd47-1~ndall+1
## location 
  - path: /dartfs/rc/lab/D/DBIC/DBIC/inbox/BIDS/_test_
  - type: directory
## metadata_extractors 
  - annex (datalad 0.14.7): 
    - distribution: datalad 0.14.7
    - load_error: None
    - module: datalad.metadata.extractors.annex
    - version: None
  - audio (datalad 0.14.7): 
    - distribution: datalad 0.14.7
    - load_error: None
    - module: datalad.metadata.extractors.audio
    - version: None
  - datacite (datalad 0.14.7): 
    - distribution: datalad 0.14.7
    - load_error: None
    - module: datalad.metadata.extractors.datacite
    - version: None
  - datalad_core (datalad 0.14.7): 
    - distribution: datalad 0.14.7
    - load_error: None
    - module: datalad.metadata.extractors.datalad_core
    - version: None
  - datalad_rfc822 (datalad 0.14.7): 
    - distribution: datalad 0.14.7
    - load_error: None
    - module: datalad.metadata.extractors.datalad_rfc822
    - version: None
  - exif (datalad 0.14.7): 
    - distribution: datalad 0.14.7
    - load_error: None
    - module: datalad.metadata.extractors.exif
    - version: None
  - frictionless_datapackage (datalad 0.14.7): 
    - distribution: datalad 0.14.7
    - load_error: None
    - module: datalad.metadata.extractors.frictionless_datapackage
    - version: None
  - image (datalad 0.14.7): 
    - distribution: datalad 0.14.7
    - load_error: None
    - module: datalad.metadata.extractors.image
    - version: None
  - xmp (datalad 0.14.7): 
    - distribution: datalad 0.14.7
    - load_error: No module named 'libxmp' [xmp.py:<module>:20]
    - module: datalad.metadata.extractors.xmp
## python 
  - implementation: CPython
  - version: 3.9.4
## system 
  - distribution: centos/7/Core
  - encoding: 
    - default: utf-8
    - filesystem: iso8859-1
    - locale.prefered: ISO-8859-1
  - max_path_length: 300
  - name: Linux
  - release: 3.10.0-1160.31.1.el7.x86_64
  - type: posix
  - version: #1 SMP Thu Jun 10 13:32:12 UTC 2021

</details>

so likely due to that WTF reported

    - filesystem: iso8859-1
    - locale.prefered: ISO-8859-1

**Comment by mih** [comment]
@yarikoptic two related PR were merged. Is there a need to keep this open?

**Comment by yarikoptic** [comment]
Non emptiness of https://github.com/datalad/datalad/blob/debian/debian/patches/deb_no_utf8 suggests that likely the issue remains at least in part. I think we need more fixes and a CI run in similar env to ensure that none is left
