### ISSUE TITLE
test_download_url_need_datalad_remote: flaky?

### ISSUE THREAD

**Issue by yarikoptic** [datalad/datalad#5973]
was reported on happen on maint build on travis with the settings (not sure if matter): `_DL_TMPDIR="/var/tmp/sym link" NOSE_SELECTION_OP="" DATALAD_TESTS_OBSCURE_PREFIX=- DATALAD_LOG_TRACEBACK=collide`

https://app.travis-ci.com/github/datalad/datalad/jobs/536670774

```
======================================================================
ERROR: datalad.interface.tests.test_download_url.test_download_url_need_datalad_remote
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/tmp/dl-miniconda-a8svhy90/lib/python3.9/site-packages/nose/case.py", line 198, in runTest
    self.test(*self.arg)
  File "/tmp/dl-miniconda-a8svhy90/lib/python3.9/site-packages/datalad/tests/utils.py", line 190, in _wrap_skip_if_no_network
    return func(*args, **kwargs)
  File "/tmp/dl-miniconda-a8svhy90/lib/python3.9/site-packages/datalad/tests/utils.py", line 767, in _wrap_with_tempfile
    return t(*(arg + (filename,)), **kw)
  File "/tmp/dl-miniconda-a8svhy90/lib/python3.9/site-packages/datalad/interface/tests/test_download_url.py", line 243, in test_download_url_need_datalad_remote
    ds_b.get("foo")
  File "/tmp/dl-miniconda-a8svhy90/lib/python3.9/site-packages/datalad/distribution/dataset.py", line 503, in apply_func
    return f(**kwargs)
  File "/tmp/dl-miniconda-a8svhy90/lib/python3.9/site-packages/datalad/interface/utils.py", line 481, in eval_func
    return return_func(generator_func)(*args, **kwargs)
  File "/tmp/dl-miniconda-a8svhy90/lib/python3.9/site-packages/datalad/interface/utils.py", line 474, in return_func
    results = list(results)
  File "/tmp/dl-miniconda-a8svhy90/lib/python3.9/site-packages/datalad/interface/utils.py", line 459, in generator_func
    raise IncompleteResultsError(
datalad.support.exceptions.IncompleteResultsError: Command did not complete successfully. 1 failed:
[{'action': 'get',
  'annexkey': 'MD5E-s4008--ef4867d3c21a0034a98cd9453f14efe3',
  'message': 'not available',
  'path': '/tmp/datalad_temp_test_download_url_need_datalad_remoteggc61t1u/b/foo',
  'refds': '/tmp/datalad_temp_test_download_url_need_datalad_remoteggc61t1u/b',
  'status': 'error',
  'type': 'file'}]
```

**Comment by adswa** [comment]
Maybe I fail to find the right logs (``download_url`` moved into ``local``), but I can't see any recent failures of this test. Has it occurred in the meantime?

**Comment by mih** [comment]
I have not seen this in ages. I think we can close it. Thx
