### ISSUE TITLE
conda build: never exits, two ERRORED test_archives tests

### ISSUE THREAD

**Issue by yarikoptic** [datalad/datalad#5992]
trying to update conda package, linux build never finished after 3h. Looking inside [log](https://dev.azure.com/conda-forge/feedstock-builds/_build/results?buildId=377738&view=logs&j=d0d954b5-f111-5dc4-4d76-03b6c9d0cf7e) on azure:

edit: ha -- this one already has `@known_failure_githubci_win` so might be reminiscent of that setup (no longer used iirc -- all windows testing on appveyor)

```
ERROR: datalad.customremotes.tests.test_archives.test_annex_get_from_subdir
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/conda/feedstock_root/build_artifacts/datalad_1631894424778/_test_env_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehol/lib/python3.6/site-packages/nose/case.py", line 197, in runTest
    self.test(*self.arg)
  File "/home/conda/feedstock_root/build_artifacts/datalad_1631894424778/_test_env_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehol/lib/python3.6/site-packages/datalad/tests/utils.py", line 563, in _wrap_with_tree
    return t(*(arg + (d,)), **kw)
  File "/home/conda/feedstock_root/build_artifacts/datalad_1631894424778/_test_env_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehol/lib/python3.6/site-packages/datalad/customremotes/tests/test_archives.py", line 175, in test_annex_get_from_subdir
    protocol=KillOutput)   # run git annex get
  File "/home/conda/feedstock_root/build_artifacts/datalad_1631894424778/_test_env_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehol/lib/python3.6/site-packages/datalad/cmd.py", line 172, in run
    **results,
datalad.support.exceptions.CommandError: CommandError: 'git annex get -- ' |;&%b5{}'"'"'"ΔЙקم๗あ .datc '' failed with exitcode 1
-------------------- >> begin captured logging << --------------------
fasteners.process_lock: Level 5: Acquired file lock `b'/tmp/datalad_temp_tree_test_annex_get_from_subdiry0toeys9/.git/datalad/tmp/archives/121d2d62b2.extract-lck'` after waiting 0.000s [1 attempts were required]
fasteners.process_lock: Level 5: Unlocked and closed file lock open on `b'/tmp/datalad_temp_tree_test_annex_get_from_subdiry0toeys9/.git/datalad/tmp/archives/121d2d62b2.extract-lck'`
--------------------- >> end captured logging << ---------------------
```

and this too actually has `@known_failure_githubci_win`
```
======================================================================
ERROR: datalad.customremotes.tests.test_archives.test_basic_scenario
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/conda/feedstock_root/build_artifacts/datalad_1631894424778/_test_env_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehol/lib/python3.6/site-packages/nose/case.py", line 197, in runTest
    self.test(*self.arg)
  File "/home/conda/feedstock_root/build_artifacts/datalad_1631894424778/_test_env_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehol/lib/python3.6/site-packages/datalad/tests/utils.py", line 563, in _wrap_with_tree
    return t(*(arg + (d,)), **kw)
  File "/home/conda/feedstock_root/build_artifacts/datalad_1631894424778/_test_env_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehol/lib/python3.6/site-packages/datalad/tests/utils.py", line 742, in _wrap_with_tempfile
    return t(*(arg + (filename,)), **kw)
  File "/home/conda/feedstock_root/build_artifacts/datalad_1631894424778/_test_env_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehol/lib/python3.6/site-packages/datalad/customremotes/tests/test_archives.py", line 124, in test_basic_scenario
    annex.get(fn_extracted)
  File "/home/conda/feedstock_root/build_artifacts/datalad_1631894424778/_test_env_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehol/lib/python3.6/site-packages/datalad/support/gitrepo.py", line 316, in _wrap_normalize_paths
    result = func(self, files_new, *args, **kwargs)
  File "/home/conda/feedstock_root/build_artifacts/datalad_1631894424778/_test_env_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehol/lib/python3.6/site-packages/datalad/support/annexrepo.py", line 1434, in get
    total_nbytes=sum(filter(bool, expected_downloads.values())),
  File "/home/conda/feedstock_root/build_artifacts/datalad_1631894424778/_test_env_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehol/lib/python3.6/site-packages/datalad/support/annexrepo.py", line 1069, in _call_annex_records
    raise e
  File "/home/conda/feedstock_root/build_artifacts/datalad_1631894424778/_test_env_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehol/lib/python3.6/site-packages/datalad/support/annexrepo.py", line 1029, in _call_annex_records
    **kwargs,
  File "/home/conda/feedstock_root/build_artifacts/datalad_1631894424778/_test_env_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehol/lib/python3.6/site-packages/datalad/support/annexrepo.py", line 922, in _call_annex
    **kwargs)
  File "/home/conda/feedstock_root/build_artifacts/datalad_1631894424778/_test_env_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehol/lib/python3.6/site-packages/datalad/cmd.py", line 344, in run_on_filelist_chunks
    **kwargs)
  File "/home/conda/feedstock_root/build_artifacts/datalad_1631894424778/_test_env_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehol/lib/python3.6/site-packages/datalad/cmd.py", line 172, in run
    **results,
datalad.support.exceptions.CommandError: CommandError: 'git -c diff.ignoreSubmodules=none annex get -c annex.retry=3 --json --json-error-messages --json-progress -c annex.dotfiles=true -- ' |;&%b5{}'"'"'"ΔЙקم๗あ .dbtc '' failed with exitcode 1 under /tmp/datalad_temp_tree_test_basic_scenarioodya8fnl [info keys: stdout_json]
> from datalad-archives...
Unable to access these remotes: datalad-archives
  RuntimeError(Failed to fetch any archive containing MD5E-s3--202cb962ac59075b964b07152d234b70. Tried: ['MD5E-s178--0f7f9a17e9c0f87fcd05dacf856a6807.tar.gz'])
  RuntimeError(Failed to fetch any archive containing MD5E-s3--202cb962ac59075b964b07152d234b70. Tried: ['MD5E-s178--0f7f9a17e9c0f87fcd05dacf856a6807.tar.gz', 'MD5E-s178--0f7f9a17e9c0f87fcd05dacf856a6807.tar.gz'])
  RuntimeError(Failed to fetch any archive containing MD5E-s3--202cb962ac59075b964b07152d234b70. Tried: ['MD5E-s178--0f7f9a17e9c0f87fcd05dacf856a6807.tar.gz', 'MD5E-s178--0f7f9a17e9c0f87fcd05dacf856a6807.tar.gz']) [err: 'get: 1 failed']
-------------------- >> begin captured logging << --------------------
datalad.annex: INFO: Start annex operation
datalad.annex: INFO: Finished annex get
--------------------- >> end captured logging << ---------------------

----------------------------------------------------------------------
Ran 1278 tests in 6804.490s

FAILED (SKIP=129, errors=2)
```

consistent across all python versions.  For the "stall" (never quits that "Run docker build") I have only one clue to try: #5983 . I think I will also just patch to skip those two tests on conda for now.

**Comment by yarikoptic** [comment]
eh, patch of #5983 didn't help. still holding up with e.g. `OK (SKIP=129)`. Need probably try to replicate running build locally to be able to see what is holding up

**Comment by yarikoptic** [comment]
FTR, difficulty of running `./build-locally.py` locally on laptop or any other recent Debian with kernel > 4.9 is due to a change which hinted on in https://github.com/docker-library/mysql/issues/570#issuecomment-644963335 and referring to workaround in https://github.com/docker/for-linux/issues/58#issuecomment-315150740 : 

> Hi, specifying this command in /etc/default/grub:
>    GRUB_CMDLINE_LINUX_DEFAULT="vsyscall=emulate"

which allowed to start that elderly CentOS-6 based container on debian with 4.11 kernel (head3 of hydra).

**Comment by yarikoptic** [comment]
crap, with debug output , it seems like again a possible leakage from git-annex?
```
2021-09-22 18:50:26,690 {1095}[DEBUG] Caught Unterminated string starting at: line 1 column 7 (char 6) while trying to parse JSON line b'{"k": "vvvvvvvvvvv...
```
is still filling up the logs (over 600 hits, so need to interrupt and skip that test or smth like that)

**Comment by yarikoptic** [comment]
<details>
<summary>with this patch to wait on the http server process to terminate</summary> 

```shell
$> cat recipe/httpserve-join-mproc.patch 
diff --git a/datalad/tests/utils.py b/datalad/tests/utils.py
index 452385942..61c4e9d01 100644
--- a/datalad/tests/utils.py
+++ b/datalad/tests/utils.py
@@ -650,6 +650,10 @@ class HTTPPath(object):
         lgr.debug("HTTP: stopping server under %s", self.path)
         self._env_patch.stop()
         self._mproc.terminate()
+        # so to ensure that it exits, and not left as a zombie as happens while building
+        # conda pkg, but somehow only for a single test/invocation:
+        #
+        self._mproc.join()
 
 
 @optional_args
```
</details>

<details>
<summary>it still never exits while waiting then (I guess) for that process</summary> 

```shell
^CError in atexit._run_exitfuncs:
Traceback (most recent call last):
  File "/home/conda/feedstock_root/build_artifacts/datalad_1632414837975/_test_env_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehol/lib/python3.9/multiprocessing/popen_fork.py", line 27, in poll
    pid, sts = os.waitpid(self.pid, flag)
KeyboardInterrupt
Traceback (most recent call last):
  File "/opt/conda/bin/conda-build", line 11, in <module>
    sys.exit(main())
  File "/opt/conda/lib/python3.8/site-packages/conda_build/cli/main_build.py", line 481, in main
Process Process-1:
    execute(sys.argv[1:])
  File "/opt/conda/lib/python3.8/site-packages/conda_build/cli/main_build.py", line 470, in execute
    outputs = api.build(args.recipe, post=args.post, test_run_post=args.test_run_post,
  File "/opt/conda/lib/python3.8/site-packages/conda_build/api.py", line 186, in build
    return build_tree(
  File "/opt/conda/lib/python3.8/site-packages/conda_build/build.py", line 3079, in build_tree
Traceback (most recent call last):
  File "/home/conda/feedstock_root/build_artifacts/datalad_1632414837975/_test_env_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehol/lib/python3.9/multiprocessing/process.py", line 315, in _bootstrap
    self.run()
  File "/home/conda/feedstock_root/build_artifacts/datalad_1632414837975/_test_env_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehol/lib/python3.9/multiprocessing/process.py", line 108, in run
    self._target(*self._args, **self._kwargs)
  File "/home/conda/feedstock_root/build_artifacts/datalad_1632414837975/_test_env_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehol/lib/python3.9/site-packages/datalad/tests/utils.py", line 590, in _multiproc_serve_path_via_http
    httpd.serve_forever()
  File "/home/conda/feedstock_root/build_artifacts/datalad_1632414837975/_test_env_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehol/lib/python3.9/socketserver.py", line 232, in serve_forever
    ready = selector.select(poll_interval)
  File "/home/conda/feedstock_root/build_artifacts/datalad_1632414837975/_test_env_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehol/lib/python3.9/selectors.py", line 416, in select
    fd_event_list = self._selector.poll(timeout)
KeyboardInterrupt
    test(pkg, config=metadata.config.copy(), stats=stats)
  File "/opt/conda/lib/python3.8/site-packages/conda_build/build.py", line 2917, in test
    utils.check_call_env(cmd, env=env, cwd=metadata.config.test_dir, stats=test_stats, rewrite_stdout_env=rewrite_env)
  File "/opt/conda/lib/python3.8/site-packages/conda_build/utils.py", line 412, in check_call_env
    return _func_defaulting_env_to_os_environ('call', *popenargs, **kwargs)
  File "/opt/conda/lib/python3.8/site-packages/conda_build/utils.py", line 387, in _func_defaulting_env_to_os_environ
    proc = PopenWrapper(_args, **kwargs)
  File "/opt/conda/lib/python3.8/site-packages/conda_build/utils.py", line 272, in __init__
    self.out, self.err = self._execute(*args, **kwargs)
  File "/opt/conda/lib/python3.8/site-packages/conda_build/utils.py", line 337, in _execute
    time.sleep(time_int)
KeyboardInterrupt
Exception ignored in: <Finalize object, dead>
Traceback (most recent call last):
  File "/home/conda/feedstock_root/build_artifacts/datalad_1632414837975/_test_env_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehol/lib/python3.9/multiprocessing/util.py", line 224, in __call__
  File "/home/conda/feedstock_root/build_artifacts/datalad_1632414837975/_test_env_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehol/lib/python3.9/multiprocessing/util.py", line 464, in close_fds
AttributeError: 'NoneType' object has no attribute 'close'

```
</details>

so seems to point to the same problem but now in a different "perspective".  The real reason I guess is something on how that process gets terminated not in an entirely clean fashion.

**Comment by yarikoptic** [comment]
uff -- running only that `test_annexrepo_fake_dates_disables_batched` test doesn't cause the halt.  Running while excluding that test, still causes the stall.  so -- no resolution yet :-/ :angry:

**Comment by yarikoptic** [comment]
FWIW testing of datalad.tests for 0.14.7 build passes fine.  So it is likely not environment/conda change related but rather 0.15.0 changes (new Runner?)

**Comment by yarikoptic** [comment]
crap -- zombies seems were "red herring" . Running 
```
python /tmp/pluginps.py -s -v -e test_(system_ssh_version|get_open_files|serve_path_via_http|asyncio_forked) datalad.tests
```
so skipping the tests which did breed zombies, (e.g. asyncio_forked was forking itself, then just sending SIGTERM without any join etc) lead to the stalling even though that pluginps.py does not show any zombie left behind :-/

we have following full list of processes:
```
[root@1bfab014027d /]# ps auxw -H
USER       PID %CPU %MEM    VSZ   RSS TTY      STAT START   TIME COMMAND
root      8601  5.5  0.0 108384  3016 pts/1    Ss   14:52   0:00 bash
root      8621  0.0  0.0 110224  2168 pts/1    R+   14:53   0:00   ps auxw -H
root         1  0.0  0.0   4132   476 pts/0    Ss   14:27   0:00 /opt/conda/bin/tini -- /opt/docker/bin/entrypoint bash /home/conda/feedstock_root/.scripts/build_steps.sh
conda        6  0.0  0.0 108252  2928 pts/0    S+   14:27   0:00   bash /home/conda/feedstock_root/.scripts/build_steps.sh
conda      682 29.9  2.1 2016628 1419708 pts/0 Sl+  14:28   7:23     /opt/conda/bin/python /opt/conda/bin/conda-build /home/conda/recipe_root -m /home/conda/feedstock_root/.ci_support/linux_64_python3.9.____cpytho
conda      814  0.0  0.0 108248  2964 pts/0    S+   14:38   0:00       /bin/bash -o errexit /home/conda/feedstock_root/build_artifacts/datalad_1632839307790/test_tmp/conda_test_runner.sh
conda      882  0.0  0.0 108248  2924 pts/0    S+   14:38   0:00         /bin/bash -e /home/conda/feedstock_root/build_artifacts/datalad_1632839307790/test_tmp/run_test.sh
conda     1088  4.4  0.1 1391236 87756 pts/0   S+   14:38   0:39           python /tmp/pluginps.py -s -v -e test_(system_ssh_version|get_open_files|serve_path_via_http|asyncio_forked) datalad.tests
conda     1205  0.0  0.0 311492 42708 pts/0    Sl+  14:38   0:00             python /tmp/pluginps.py -s -v -e test_(system_ssh_version|get_open_files|serve_path_via_http|asyncio_forked) datalad.tests
```

```
[conda@1bfab014027d ~]$ ls -l /proc/1205/fd/
total 0
lr-x------ 1 conda conda 64 Sep 28 14:53 0 -> pipe:[9974279]
l-wx------ 1 conda conda 64 Sep 28 14:53 1 -> pipe:[9974278]
lrwx------ 1 conda conda 64 Sep 28 14:38 2 -> /dev/pts/0
lr-x------ 1 conda conda 64 Sep 28 14:53 3 -> /dev/urandom
lr-x------ 1 conda conda 64 Sep 28 14:53 4 -> pipe:[9978953]
l-wx------ 1 conda conda 64 Sep 28 14:53 5 -> pipe:[9978953]
lr-x------ 1 conda conda 64 Sep 28 14:53 6 -> /dev/null
l-wx------ 1 conda conda 64 Sep 28 14:53 7 -> pipe:[9978957]
lr-x------ 1 conda conda 64 Sep 28 14:53 8 -> pipe:[9978958]
lrwx------ 1 conda conda 64 Sep 28 14:53 9 -> socket:[9963454]
[conda@1bfab014027d ~]$ ls -l /proc/1088/fd/
total 0
lr-x------ 1 conda conda 64 Sep 28 14:54 0 -> pipe:[9974279]
l-wx------ 1 conda conda 64 Sep 28 14:54 1 -> pipe:[9974278]
lrwx------ 1 conda conda 64 Sep 28 14:54 10 -> socket:[10002911]
lrwx------ 1 conda conda 64 Sep 28 14:54 11 -> socket:[10002912]
l-wx------ 1 conda conda 64 Sep 28 14:54 12 -> pipe:[9999270]
lrwx------ 1 conda conda 64 Sep 28 14:38 2 -> /dev/pts/0
lr-x------ 1 conda conda 64 Sep 28 14:54 3 -> /dev/urandom
l-wx------ 1 conda conda 64 Sep 28 14:54 4 -> /tmp/datalad_temp_test_logging_to_a_filef9rk06tc (deleted)
lrwx------ 1 conda conda 64 Sep 28 14:54 5 -> anon_inode:[eventpoll]
lr-x------ 1 conda conda 64 Sep 28 14:54 6 -> pipe:[9978957]
l-wx------ 1 conda conda 64 Sep 28 14:54 7 -> pipe:[10002908]
lr-x------ 1 conda conda 64 Sep 28 14:54 8 -> pipe:[9999269]
l-wx------ 1 conda conda 64 Sep 28 14:54 9 -> pipe:[9978958]
[conda@1bfab014027d ~]$ ls -l /proc/882/fd/
total 0
lr-x------ 1 conda conda 64 Sep 28 14:54 0 -> pipe:[9974279]
l-wx------ 1 conda conda 64 Sep 28 14:54 1 -> pipe:[9974278]
lrwx------ 1 conda conda 64 Sep 28 14:38 2 -> /dev/pts/0
lr-x------ 1 conda conda 64 Sep 28 14:54 255 -> /home/conda/feedstock_root/build_artifacts/datalad_1632839307790/test_tmp/run_test.sh
```

1. seems we are not closing a file in one of the tests (unlikely should matter but still)
2.  https://jvns.ca/blog/2020/04/29/why-strace-doesnt-work-in-docker/ hints on adding `--cap-add=SYS_PTRACE` to older dockers invocation to allow for stracing within docker container (will do)

**Comment by yarikoptic** [comment]
Next suspicion (making most sense) -- the result of #5332 (and possibly interaction with test_misc.py:test_test where possibly setup_package would start yet another http_server which would never be exited explicitly).
