### ISSUE TITLE
Remove or fix AnnexRepo.annexstatus()

### ISSUE THREAD

**Issue by christian-monch** [datalad/datalad#6076]
### What is the problem?

1. The function `AnnexRepo.annexstatus` is not used outside of tests.
2. The function has an unused `untracked`-parameter
3. The function is missing  doc-string

**Comment by adswa** [comment]
I'm currently trying to remove this function, but its surprisingly difficult. The gotcha that Michael found in save is addressed easily, and I can also adjust the tests to rely on ``get_content_annexinfo`` instead.

But if I remove ``annexstatus`` at a time where *nothing* uses or calls this function anymore everything falls to pieces. WTF?

**Comment by adswa** [comment]
Just for posterity, here's the diff that leads to ``annexstatus`` becoming unused:

```diff
commit 97821f73bc5d37a4ab65019dda0614910d947a3a (HEAD -> mnt-6076)
Author: Adina Wagner <adina.wagner@t-online.de>
Date:   Thu Feb 3 09:39:13 2022 +0100
 
    MNT: Determine ds instance type based on uuid property instead of annexstatus
    
    The latter is a negligably used, to-be deprecated function, while UUID should
    be a reliable indicator of AnnexRepo instances as it is a property of
    AnnexRepo
 
diff --git a/datalad/core/local/save.py b/datalad/core/local/save.py
index fa8718fdd..e3684d974 100644
--- a/datalad/core/local/save.py
+++ b/datalad/core/local/save.py
@@ -309,7 +309,7 @@ class Save(Interface):
                         # calls
                         paths=None,
                         # prevent whining of GitRepo
-                        git=True if not hasattr(ds.repo, 'annexstatus')
+                        git=True if not hasattr(ds.repo, 'uuid')
                         else to_git,
                         # we are supplying the full status already, do not
                         # detect anything else

```
```diff
commit 0d829c1cdbf3b2178c71e2caf0a7cdc2c2c703bd
Author: Adina Wagner <adina.wagner@t-online.de>
Date:   Thu Feb 3 09:27:02 2022 +0100
 
    RF: Deprecate annexstatus, move it from a class method into a test helper
    
    This function was formerly used only in tests, with one exception in save
    that relied on its precence as an attribute in ds.repo to determine
    whether or not ds.repo was an AnnexRepo or GitRepo instance.
    
    Tests that desperately rely on this, or test its function, have been
    adjusted to use the test helper instead.
    
    Work towards #6067
 
diff --git a/datalad/support/annexrepo.py b/datalad/support/annexrepo.py
index 85f55ed88..e7b2f9742 100644
--- a/datalad/support/annexrepo.py
+++ b/datalad/support/annexrepo.py
@@ -3334,6 +3334,12 @@ class AnnexRepo(GitRepo, RepoInterface):
         return info
 
     def annexstatus(self, paths=None, untracked='all'):
+        """
+        .. deprecated:: 0.16
+
+        Use get_content_annexinfo() or the test helper
+        datalad/utils/get_annexstatus() instead.
+        """
         info = self.get_content_annexinfo(
             paths=paths,
             eval_availability=False,
diff --git a/datalad/support/tests/test_fileinfo.py b/datalad/support/tests/test_fileinfo.py
index 7ab03c825..302bb3385 100644
--- a/datalad/support/tests/test_fileinfo.py
+++ b/datalad/support/tests/test_fileinfo.py
@@ -19,6 +19,7 @@ from datalad.tests.utils import (
     assert_in,
     assert_not_in,
     assert_raises,
+    get_annexstatus,
     known_failure_githubci_win,
     slow,
     with_tempfile,
@@ -58,7 +59,7 @@ def test_get_content_info(path):
     # - git ls-files
     # - git annex findref HEAD
     # - git annex find --include '*'
-    for f, r in ds.repo.annexstatus().items():
+    for f, r in get_annexstatus(ds.repo).items():
         if f.match('*_untracked'):
             assert(r.get('gitshasum', None) is None)
         if f.match('*_deleted'):
@@ -116,7 +117,7 @@ def test_get_content_info(path):
                     assert_in(status[p]['type'], ('file', 'symlink'), p)
 
     # git annex status integrity
-    annexstatus = ds.repo.annexstatus()
+    annexstatus = get_annexstatus(ds.repo)
     for t in ('file',):
         for s in ('untracked', 'added', 'deleted', 'clean',
                   'ingit_clean', 'dropped_clean', 'modified',
diff --git a/datalad/support/tests/test_repo_save.py b/datalad/support/tests/test_repo_save.py
index 82a7d33fe..72367336b 100644
--- a/datalad/support/tests/test_repo_save.py
+++ b/datalad/support/tests/test_repo_save.py
@@ -22,6 +22,7 @@ from datalad.support.gitrepo import GitRepo
 from datalad.support.annexrepo import AnnexRepo
 from datalad.tests.utils import (
     assert_repo_status,
+    get_annexstatus,
     get_convoluted_situation,
     slow,
 )
@@ -92,7 +93,7 @@ def test_save_to_git(path):
     ds.repo.save(paths=['file_ingit'], git=True)
     ds.repo.save(paths=['file_inannex'])
     assert_repo_status(ds.repo)
-    for f, p in ds.repo.annexstatus().items():
+    for f, p in get_annexstatus(ds.repo).items():
         eq_(p['state'], 'clean')
         if f.match('*ingit'):
             assert_not_in('key', p, f)
diff --git a/datalad/tests/utils.py b/datalad/tests/utils.py
index a8cf20b7c..a5db50ab1 100644
--- a/datalad/tests/utils.py
+++ b/datalad/tests/utils.py
@@ -396,6 +396,30 @@ def _prep_file_under_git(path, filename):
         ds.repo
 
 
+def get_annexstatus(ds, paths=None):
+    """Report a status for annexed contents.
+    Assembles states for git content info, amended with annex info on 'HEAD'
+    (to get the last committed stage and with it possibly vanished content),
+    and lastly annex info wrt to the present worktree, to also get info on
+    added/staged content this fuses the info reported from
+    - git ls-files
+    - git annex findref HEAD
+    - git annex find --include '*'"""
+    info = ds.get_content_annexinfo(
+        paths=paths,
+        eval_availability=False,
+        init=ds.get_content_annexinfo(
+            paths=paths,
+            ref='HEAD',
+            eval_availability=False,
+            init=ds.status(
+                paths=paths,
+                eval_submodule_state='full')
+        )
+    )
+    ds._mark_content_availability(info)
+    return info
+
 #
 # Helpers to test symlinks
 #
```

```diff
commit a0ca6f286bbc441119d594cc86563bb053cd8fc5
Author: Adina Wagner <adina.wagner@t-online.de>
Date:   Thu Feb 3 09:23:07 2022 +0100
 
    RF: Where possible, replace ds.repo.annexstatus() with get_content_annexinfo().
    
    This is work towards #6067
 
diff --git a/datalad/core/local/tests/test_save.py b/datalad/core/local/tests/test_save.py
index cf698e5a9..006001e79 100644
--- a/datalad/core/local/tests/test_save.py
+++ b/datalad/core/local/tests/test_save.py
@@ -397,7 +397,7 @@ def test_add_files(path):
         # special case 4: give the dir:
         if arg[0] == test_list_4:
             result = ds.save('dir', to_git=arg[1])
-            status = ds.repo.annexstatus(['dir'])
+            status = ds.repo.get_content_annexinfo(['dir'])
         else:
             result = ds.save(arg[0], to_git=arg[1])
             for a in ensure_list(arg[0]):
@@ -505,7 +505,7 @@ def test_gh1597(path):
     # must not come under annex management
     assert_not_in(
         'key',
-        ds.repo.annexstatus(paths=['.gitmodules']).popitem()[1])
+        ds.repo.get_content_annexinfo(paths=['.gitmodules']).popitem()[1])
 
 
 @with_tempfile(mkdir=True)
```

if I then remote ``annexstatus`` from ``annexrepo.py``, things crash with test failures such as 

```
======================================================================
FAIL: datalad.core.local.tests.test_save.test_add_files
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/adina/env/handbook2/lib/python3.9/site-packages/nose/case.py", line 198, in runTest
    self.test(*self.arg)
  File "/home/adina/repos/datalad/datalad/tests/utils.py", line 579, in _wrap_with_tree
    return t(*(arg + (d,)), **kw)
  File "/home/adina/repos/datalad/datalad/core/local/tests/test_save.py", line 409, in test_add_files
    assert p.get('key', None) is None, f
AssertionError: /tmp/datalad_temp_tree_test_add_filesgjbcyrs4/test.txt

======================================================================
FAIL: datalad.core.local.tests.test_save.test_add_mimetypes
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/adina/env/handbook2/lib/python3.9/site-packages/nose/case.py", line 198, in runTest
    self.test(*self.arg)
  File "/home/adina/repos/datalad/datalad/tests/utils.py", line 579, in _wrap_with_tree
    return t(*(arg + (d,)), **kw)
  File "/home/adina/repos/datalad/datalad/core/local/tests/test_save.py", line 487, in test_add_mimetypes
    assert_in('key', annexinfo[p], p)
AssertionError: 'key' not found in {'gitshasum': '117df4eb1fbee1177d8109a6215ee91e265f1799', 'type': 'file'} : /tmp/datalad_temp_tree_test_add_mimetypes4rj1h7ob/file2.txt

======================================================================
FAIL: datalad.core.local.tests.test_save.test_save_dotfiles(True, None)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/adina/env/handbook2/lib/python3.9/site-packages/nose/case.py", line 198, in runTest
    self.test(*self.arg)
  File "/home/adina/repos/datalad/datalad/tests/utils.py", line 579, in _wrap_with_tree
    return t(*(arg + (d,)), **kw)
  File "/home/adina/repos/datalad/datalad/core/local/tests/test_save.py", line 811, in check_save_dotfiles
    check(path)
  File "/home/adina/repos/datalad/datalad/core/local/tests/test_save.py", line 805, in check
    _check(assert_not_in, p)
  File "/home/adina/repos/datalad/datalad/core/local/tests/test_save.py", line 801, in _check
    fn("key", annexinfo[repo.pathobj / p], p)
AssertionError: 'key' unexpectedly found in {'gitshasum': '8cdb1149f41acc060e753252dcd3a28a250038ce', 'type': 'file', 'bytesize': 2, 'mtime': 'unknown', 'keyname': '187ef4436122d1cc2f40dc2b92f0eba0', 'backend': 'MD5E', 'key': 'MD5E-s2--187ef4436122d1cc2f40dc2b92f0eba0', 'humansize': '2 B', 'error-messages': [], 'hashdirmixed': 'gq/xg/', 'hashdirlower': '8b2/4b5/'} : .dot

======================================================================
FAIL: datalad.core.local.tests.test_save.test_save_dotfiles(True, 'nodot-subdir')
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/adina/env/handbook2/lib/python3.9/site-packages/nose/case.py", line 198, in runTest
    self.test(*self.arg)
  File "/home/adina/repos/datalad/datalad/tests/utils.py", line 579, in _wrap_with_tree
    return t(*(arg + (d,)), **kw)
  File "/home/adina/repos/datalad/datalad/core/local/tests/test_save.py", line 811, in check_save_dotfiles
    check(path)
  File "/home/adina/repos/datalad/datalad/core/local/tests/test_save.py", line 805, in check
    _check(assert_not_in, p)
  File "/home/adina/repos/datalad/datalad/core/local/tests/test_save.py", line 801, in _check
    fn("key", annexinfo[repo.pathobj / p], p)
AssertionError: 'key' unexpectedly found in {'gitshasum': '1d15580fe6bc060adf932257b1d025153767ca63', 'type': 'file', 'bytesize': 2, 'mtime': 'unknown', 'keyname': 'feb78cc258bdc76867354f01c22dbe43', 'backend': 'MD5E', 'key': 'MD5E-s2--feb78cc258bdc76867354f01c22dbe43', 'humansize': '2 B', 'error-messages': [], 'hashdirmixed': '3W/V9/', 'hashdirlower': 'dc9/0ee/'} : nodot-subdir/.dot
```

I suspect that ``self._mark_content_availability(info)`` of ``annexstatus`` is somehow involved in this, but given that nothing calls this function I can't figure out why.

**Comment by mih** [comment]
The method is deprecated since #6413, I think we can close this.
