### ISSUE TITLE
appveyor ubuntus: libxmp.ExempiLoadError: Exempi library not found.

### ISSUE THREAD

**Issue by yarikoptic** [datalad/datalad#6141]
```
======================================================================
ERROR: datalad.metadata.tests.test_extract_metadata.test_ds_extraction
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/appveyor/dlvenv/lib/python3.8/site-packages/nose/case.py", line 198, in runTest
    self.test(*self.arg)
  File "/home/appveyor/projects/datalad/datalad/tests/utils.py", line 742, in _wrap_with_tempfile
    return t(*(arg + (filename,)), **kw)
  File "/home/appveyor/projects/datalad/datalad/metadata/tests/test_extract_metadata.py", line 48, in test_ds_extraction
    import libxmp
  File "/home/appveyor/dlvenv/lib/python3.8/site-packages/libxmp/__init__.py", line 50, in <module>
    from .core import XMPMeta, XMPIterator
  File "/home/appveyor/dlvenv/lib/python3.8/site-packages/libxmp/core.py", line 50, in <module>
    from . import exempi as _cexempi
  File "/home/appveyor/dlvenv/lib/python3.8/site-packages/libxmp/exempi.py", line 69, in <module>
    EXEMPI = _load_exempi()
  File "/home/appveyor/dlvenv/lib/python3.8/site-packages/libxmp/exempi.py", line 60, in _load_exempi
    raise ExempiLoadError('Exempi library not found.')
libxmp.ExempiLoadError: Exempi library not found.
======================================================================
ERROR: datalad.metadata.tests.test_extract_metadata.test_file_extraction
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/appveyor/dlvenv/lib/python3.8/site-packages/nose/case.py", line 198, in runTest
    self.test(*self.arg)
  File "/home/appveyor/projects/datalad/datalad/tests/utils.py", line 742, in _wrap_with_tempfile
    return t(*(arg + (filename,)), **kw)
  File "/home/appveyor/projects/datalad/datalad/metadata/tests/test_extract_metadata.py", line 88, in test_file_extraction
    import libxmp
  File "/home/appveyor/dlvenv/lib/python3.8/site-packages/libxmp/__init__.py", line 50, in <module>
    from .core import XMPMeta, XMPIterator
  File "/home/appveyor/dlvenv/lib/python3.8/site-packages/libxmp/core.py", line 50, in <module>
    from . import exempi as _cexempi
  File "/home/appveyor/dlvenv/lib/python3.8/site-packages/libxmp/exempi.py", line 69, in <module>
    EXEMPI = _load_exempi()
  File "/home/appveyor/dlvenv/lib/python3.8/site-packages/libxmp/exempi.py", line 60, in _load_exempi
    raise ExempiLoadError('Exempi library not found.')
libxmp.ExempiLoadError: Exempi library not found.
```
from https://github.com/datalad/datalad/pull/6135 against `maint` with changes which do not relate... although more recent run https://ci.appveyor.com/project/mih/datalad/builds/41404037 for  #6140 against maint seems to be green.

so me is confused -- but may be it rings the bell to some @datalad/developers ?

**Comment by adswa** [comment]
I don't know. but I have seen them a few weeks ago as well

**Comment by mih** [comment]
It is unclear to me how this can even happen. The Exception is defined as:

```py
class ExempiLoadError(Exception):
    """ Error signaling that the Exempi library cannot be loaded. """
    pass
```

The context of both test failures is:

```py
    try:
        import libxmp
    except Exception as e:
        raise SkipTest('Cannot import libxmp: {}'.format(e))
```

From my naive understanding of Python, such an exception should lead to a `SkipTest` being raised.
