### ISSUE TITLE
`remove` fails with confusing error

### ISSUE THREAD

**Issue by loj** [datalad/datalad#6180]
### What is the problem?

I am trying to remove an old dataset with the updated `remove` command, and am getting an error that is confusing. It is an old clone with nothing I care about, so I know I can wipe it out with the `--reckless` option. However, I find the error confusing and wanted to share.

### What steps will reproduce the problem?

I haven't been able to reproduce the error with other datasets or clones. The problem seems to come up in the check for undead annexes, but I'm not quite sure what the cause is. Here's what I'm seeing.

```
❱ datalad remove -d datalad-hirni                                                                                                                                                                               
[ERROR  ] TypeError(startswith first arg must be str or a tuple of str, not NoneType) (TypeError)
```

<details><summary>with debug</summary>

```
❱ datalad -l debug remove -d datalad-hirni                                                                                                                                                                      
[DEBUG  ] Command line args 1st pass for DataLad 0.15.3+208.g981aa95ba. Parsed: Namespace() Unparsed: ['remove', '-d', 'datalad-hirni'] 
[DEBUG  ] Building doc for <class 'datalad.core.local.status.Status'> 
[DEBUG  ] Building doc for <class 'datalad.core.local.save.Save'> 
[DEBUG  ] Building doc for <class 'datalad.distributed.drop.Drop'> 
[DEBUG  ] Building doc for <class 'datalad.local.remove.Remove'> 
[DEBUG  ] Parsing known args among ['/home/loj/.venvs/dl-latest/bin/datalad', '-l', 'debug', 'remove', '-d', 'datalad-hirni'] 
[DEBUG  ] Run ['git', '--git-dir=', 'config', '-z', '-l', '--show-origin'] (cwd=None) 
[DEBUG  ] Finished ['git', '--git-dir=', 'config', '-z', '-l', '--show-origin'] with status 0 
[DEBUG  ] Determined class of decorated function: <class 'datalad.local.remove.Remove'> 
[DEBUG  ] Run ['git', '-c', 'diff.ignoreSubmodules=none', 'for-each-ref', '--format=%(refname:strip=2)', 'refs/heads', 'refs/remotes'] (cwd=/home/loj/git/UXfix/datalad-hirni) 
[DEBUG  ] Finished ['git', '-c', 'diff.ignoreSubmodules=none', 'for-each-ref', '--format=%(refname:strip=2)', 'refs/heads', 'refs/remotes'] with status 0 
[DEBUG  ] Run ['git', '-c', 'diff.ignoreSubmodules=none', 'for-each-ref', '--format=%(refname:strip=2)', 'refs/heads', 'refs/remotes'] (cwd=/home/loj/git/UXfix/datalad-hirni) 
[DEBUG  ] Finished ['git', '-c', 'diff.ignoreSubmodules=none', 'for-each-ref', '--format=%(refname:strip=2)', 'refs/heads', 'refs/remotes'] with status 0 
[DEBUG  ] Run ['git', 'config', '-z', '-l', '--show-origin'] (cwd=/home/loj/git/UXfix/datalad-hirni) 
[DEBUG  ] Finished ['git', 'config', '-z', '-l', '--show-origin'] with status 0 
[DEBUG  ] Resolved dataset to remove: /home/loj/git/UXfix/datalad-hirni 
[DEBUG  ] Run ['git', '-c', 'diff.ignoreSubmodules=none', 'for-each-ref', '--format=%(refname:strip=2)', 'refs/heads', 'refs/remotes'] (cwd=/home/loj/git/UXfix/datalad-hirni) 
[DEBUG  ] Finished ['git', '-c', 'diff.ignoreSubmodules=none', 'for-each-ref', '--format=%(refname:strip=2)', 'refs/heads', 'refs/remotes'] with status 0 
[DEBUG  ] Run ['git', '-c', 'diff.ignoreSubmodules=none', 'for-each-ref', '--format=%(refname:strip=2)', 'refs/heads', 'refs/remotes'] (cwd=/home/loj/git/UXfix/datalad-hirni) 
[DEBUG  ] Finished ['git', '-c', 'diff.ignoreSubmodules=none', 'for-each-ref', '--format=%(refname:strip=2)', 'refs/heads', 'refs/remotes'] with status 0 
[DEBUG  ] Run ['git', 'config', '-z', '-l', '--show-origin'] (cwd=/home/loj/git/UXfix/datalad-hirni) 
[DEBUG  ] Finished ['git', 'config', '-z', '-l', '--show-origin'] with status 0 
[DEBUG  ] Determined class of decorated function: <class 'datalad.distributed.drop.Drop'> 
[DEBUG  ] Run ['git', '-c', 'diff.ignoreSubmodules=none', 'for-each-ref', '--format=%(refname:strip=2)', 'refs/heads', 'refs/remotes'] (cwd=/home/loj/git/UXfix/datalad-hirni) 
[DEBUG  ] Finished ['git', '-c', 'diff.ignoreSubmodules=none', 'for-each-ref', '--format=%(refname:strip=2)', 'refs/heads', 'refs/remotes'] with status 0 
[DEBUG  ] Resolved dataset to drop: /home/loj/git/UXfix/datalad-hirni 
[DEBUG  ] Run ['git', '-c', 'diff.ignoreSubmodules=none', 'for-each-ref', '--format=%(refname:strip=2)', 'refs/heads', 'refs/remotes'] (cwd=/home/loj/git/UXfix/datalad-hirni) 
[DEBUG  ] Finished ['git', '-c', 'diff.ignoreSubmodules=none', 'for-each-ref', '--format=%(refname:strip=2)', 'refs/heads', 'refs/remotes'] with status 0 
[DEBUG  ] Discovered 1 datasets to drop (from) 
[DEBUG  ] Starting to drop datasets at Dataset(/home/loj/git/UXfix/datalad-hirni) 
[DEBUG  ] Start dropping for Dataset(/home/loj/git/UXfix/datalad-hirni) 
[DEBUG  ] Importing datalad.api to possibly discover possibly not yet bound method 'subdatasets' 
[DEBUG  ] Building doc for <class 'datalad.core.local.create.Create'> 
[DEBUG  ] Building doc for <class 'datalad.local.subdatasets.Subdatasets'> 
[DEBUG  ] Building doc for <class 'datalad.core.distributed.clone.Clone'> 
[DEBUG  ] Building doc for <class 'datalad.distribution.get.Get'> 
[DEBUG  ] Building doc for <class 'datalad.distribution.install.Install'> 
[DEBUG  ] Building doc for <class 'datalad.core.local.diff.Diff'> 
[DEBUG  ] Building doc for <class 'datalad.core.distributed.push.Push'> 
[DEBUG  ] Building doc for <class 'datalad.distribution.uninstall.Uninstall'> 
[DEBUG  ] Building doc for <class 'datalad.distribution.update.Update'> 
[DEBUG  ] Building doc for <class 'datalad.distribution.siblings.Siblings'> 
[DEBUG  ] Building doc for <class 'datalad.distribution.create_sibling.CreateSibling'> 
[DEBUG  ] Failed to import requests_ftp, thus no ftp support: ModuleNotFoundError(No module named 'requests_ftp') 
[DEBUG  ] parseParameters: Given "headers: dict, optional
|   Header fields to be provided to the session. Unless User-Agent provided, a custom
|   one, available in `DEFAULT_USER_AGENT` constant of this module will be used.", we split into [('headers', 'headers: dict, optional\n  Header fields to be provided to the session. Unless User-Agent provided, a custom\n  one, available in `DEFAULT_USER_AGENT` constant of this module will be used.')] 
[DEBUG  ] parseParameters: Given "credential: Credential, optional
|   Provides necessary credential fields to be used by authenticator
| authenticator: Authenticator, optional
|   Authenticator to use for authentication.", we split into [('credential', 'credential: Credential, optional\n  Provides necessary credential fields to be used by authenticator'), ('authenticator', 'authenticator: Authenticator, optional\n  Authenticator to use for authentication.')] 
[DEBUG  ] Building doc for <class 'datalad.distributed.create_sibling_github.CreateSiblingGithub'>
[DEBUG  ] Building doc for <class 'datalad.distributed.create_sibling_gitlab.CreateSiblingGitlab'> 
[DEBUG  ] Building doc for <class 'datalad.distributed.create_sibling_gogs.CreateSiblingGogs'> 
[DEBUG  ] Building doc for <class 'datalad.distributed.create_sibling_gin.CreateSiblingGin'> 
[DEBUG  ] Building doc for <class 'datalad.distributed.create_sibling_gitea.CreateSiblingGitea'> 
[DEBUG  ] Building doc for <class 'datalad.distributed.create_sibling_ria.CreateSiblingRia'> 
[DEBUG  ] Building doc for <class 'datalad.interface.unlock.Unlock'> 
[DEBUG  ] Building doc for <class 'datalad.local.copy_file.CopyFile'> 
[DEBUG  ] Building doc for <class 'datalad.metadata.metadata.Metadata'> 
[DEBUG  ] Building doc for <class 'datalad.metadata.search.Search'> 
[DEBUG  ] Building doc for <class 'datalad.metadata.aggregate.AggregateMetaData'> 
[DEBUG  ] Building doc for <class 'datalad.metadata.extract_metadata.ExtractMetadata'> 
[DEBUG  ] Building doc for <class 'datalad.local.wtf.WTF'> 
[DEBUG  ] Building doc for <class 'datalad.local.no_annex.NoAnnex'> 
[DEBUG  ] Building doc for <class 'datalad.local.add_readme.AddReadme'> 
[DEBUG  ] Building doc for <class 'datalad.local.addurls.Addurls'> 
[DEBUG  ] Building doc for <class 'datalad.local.check_dates.CheckDates'> 
[DEBUG  ] Building doc for <class 'datalad.local.export_archive.ExportArchive'> 
[DEBUG  ] Building doc for <class 'datalad.distributed.export_to_figshare.ExportToFigshare'> 
[DEBUG  ] Building doc for <class 'datalad.interface.test.Test'> 
[DEBUG  ] Building doc for <class 'datalad.interface.clean.Clean'> 
[DEBUG  ] Building doc for <class 'datalad.interface.add_archive_content.AddArchiveContent'> 
[DEBUG  ] parseParameters: Given "", we split into [] 
[DEBUG  ] parseParameters: Given "credential: Credential, optional
|   Provides necessary credential fields to be used by authenticator
| authenticator: Authenticator, optional
|   Authenticator to use for authentication.", we split into [('credential', 'credential: Credential, optional\n  Provides necessary credential fields to be used by authenticator'), ('authenticator', 'authenticator: Authenticator, optional\n  Authenticator to use for authentication.')] 
[DEBUG  ] parseParameters: Given "", we split into [] 
[DEBUG  ] parseParameters: Given "headers: dict, optional
|   Header fields to be provided to the session. Unless User-Agent provided, a custom
|   one, available in `DEFAULT_USER_AGENT` constant of this module will be used.
| credential: Credential, optional
|   Provides necessary credential fields to be used by authenticator
| authenticator: Authenticator, optional
|   Authenticator to use for authentication.", we split into [('headers', 'headers: dict, optional\n  Header fields to be provided to the session. Unless User-Agent provided, a custom\n  one, available in `DEFAULT_USER_AGENT` constant of this module will be used.'), ('credential', 'credential: Credential, optional\n  Provides necessary credential fields to be used by authenticator'), ('authenticator', 'authenticator: Authenticator, optional\n  Authenticator to use for authentication.')] 
[DEBUG  ] parseParameters: Given "", we split into [] 
[DEBUG  ] parseParameters: Given "method : callable
|   A callable, usually a method of the same class, which we decorate
|   with access handling, and pass url as the first argument
| url : string
|   URL to access
| *args, **kwargs
|   Passed into the method call", we split into [('method', 'method : callable\n  A callable, usually a method of the same class, which we decorate\n  with access handling, and pass url as the first argument'), ('url', 'url : string\n  URL to access'), ('*args, **kwargs', '*args, **kwargs\n  Passed into the method call')] 
[DEBUG  ] Building doc for <class 'datalad.interface.download_url.DownloadURL'> 
[DEBUG  ] Building doc for <class 'datalad.interface.shell_completion.ShellCompletion'> 
[DEBUG  ] Building doc for <class 'datalad.core.local.run.Run'> 
[DEBUG  ] Building doc for <class 'datalad.interface.rerun.Rerun'> 
[DEBUG  ] Building doc for <class 'datalad.interface.run_procedure.RunProcedure'> 
[DEBUG  ] Building doc for <class 'datalad.distributed.export_archive_ora.ExportArchiveORA'> 
[DEBUG  ] Building doc for <class 'datalad.distribution.create_test_dataset.CreateTestDataset'> 
[DEBUG  ] Building doc for <class 'datalad.support.sshrun.SSHRun'> 
[DEBUG  ] Determined class of decorated function: <class 'datalad.local.subdatasets.Subdatasets'>
[DEBUG  ] Run ['git', '-c', 'diff.ignoreSubmodules=none', 'for-each-ref', '--format=%(refname:strip=2)', 'refs/heads', 'refs/remotes'] (cwd=/home/loj/git/UXfix/datalad-hirni) 
[DEBUG  ] Finished ['git', '-c', 'diff.ignoreSubmodules=none', 'for-each-ref', '--format=%(refname:strip=2)', 'refs/heads', 'refs/remotes'] with status 0 
[DEBUG  ] Resolved dataset to report on subdataset(s): /home/loj/git/UXfix/datalad-hirni 
[DEBUG  ] Run ['git', '-c', 'diff.ignoreSubmodules=none', 'for-each-ref', '--format=%(refname:strip=2)', 'refs/heads', 'refs/remotes'] (cwd=/home/loj/git/UXfix/datalad-hirni) 
[DEBUG  ] Finished ['git', '-c', 'diff.ignoreSubmodules=none', 'for-each-ref', '--format=%(refname:strip=2)', 'refs/heads', 'refs/remotes'] with status 0 
[DEBUG  ] Query subdatasets of Dataset(/home/loj/git/UXfix/datalad-hirni) 
[DEBUG  ] Run ['git', '-c', 'diff.ignoreSubmodules=none', 'for-each-ref', '--format=%(refname:strip=2)', 'refs/heads', 'refs/remotes'] (cwd=/home/loj/git/UXfix/datalad-hirni) 
[DEBUG  ] Finished ['git', '-c', 'diff.ignoreSubmodules=none', 'for-each-ref', '--format=%(refname:strip=2)', 'refs/heads', 'refs/remotes'] with status 0 
[DEBUG  ] Determined class of decorated function: <class 'datalad.local.subdatasets.Subdatasets'> 
[DEBUG  ] Run ['git', '-c', 'diff.ignoreSubmodules=none', 'for-each-ref', '--format=%(refname:strip=2)', 'refs/heads', 'refs/remotes'] (cwd=/home/loj/git/UXfix/datalad-hirni) 
[DEBUG  ] Finished ['git', '-c', 'diff.ignoreSubmodules=none', 'for-each-ref', '--format=%(refname:strip=2)', 'refs/heads', 'refs/remotes'] with status 0 
[DEBUG  ] Resolved dataset to report on subdataset(s): /home/loj/git/UXfix/datalad-hirni 
[DEBUG  ] Run ['git', '-c', 'diff.ignoreSubmodules=none', 'for-each-ref', '--format=%(refname:strip=2)', 'refs/heads', 'refs/remotes'] (cwd=/home/loj/git/UXfix/datalad-hirni) 
[DEBUG  ] Finished ['git', '-c', 'diff.ignoreSubmodules=none', 'for-each-ref', '--format=%(refname:strip=2)', 'refs/heads', 'refs/remotes'] with status 0 
[DEBUG  ] Query subdatasets of Dataset(/home/loj/git/UXfix/datalad-hirni) 
[DEBUG  ] Run ['git', '-c', 'diff.ignoreSubmodules=none', 'symbolic-ref', 'HEAD'] (cwd=/home/loj/git/UXfix/datalad-hirni) 
[DEBUG  ] Finished ['git', '-c', 'diff.ignoreSubmodules=none', 'symbolic-ref', 'HEAD'] with status 0 
[DEBUG  ] No sync necessary, no corresponding branch detected 
[DEBUG  ] Run ['git', '-c', 'diff.ignoreSubmodules=none', 'for-each-ref', '--format=%(refname:strip=2)', 'refs/heads'] (cwd=/home/loj/git/UXfix/datalad-hirni) 
[DEBUG  ] Finished ['git', '-c', 'diff.ignoreSubmodules=none', 'for-each-ref', '--format=%(refname:strip=2)', 'refs/heads'] with status 0 
[DEBUG  ] Run ['git', '-c', 'diff.ignoreSubmodules=none', 'symbolic-ref', 'HEAD'] (cwd=/home/loj/git/UXfix/datalad-hirni) 
[DEBUG  ] Finished ['git', '-c', 'diff.ignoreSubmodules=none', 'symbolic-ref', 'HEAD'] with status 0 
[DEBUG  ] Run ['git', '-c', 'diff.ignoreSubmodules=none', 'for-each-ref', '--format=%(refname:strip=2)', 'refs/remotes'] (cwd=/home/loj/git/UXfix/datalad-hirni) 
[DEBUG  ] Finished ['git', '-c', 'diff.ignoreSubmodules=none', 'for-each-ref', '--format=%(refname:strip=2)', 'refs/remotes'] with status 0 
[DEBUG  ] Run ['git', '-c', 'diff.ignoreSubmodules=none', 'merge-base', '--is-ancestor', 'bf-docs', 'origin/HEAD'] (cwd=/home/loj/git/UXfix/datalad-hirni) 
[DEBUG  ] Finished ['git', '-c', 'diff.ignoreSubmodules=none', 'merge-base', '--is-ancestor', 'bf-docs', 'origin/HEAD'] with status 1 
[DEBUG  ] Run ['git', '-c', 'diff.ignoreSubmodules=none', 'merge-base', '--is-ancestor', 'bf-docs', 'origin/bf-dflt-dsdescr'] (cwd=/home/loj/git/UXfix/datalad-hirni) 
[DEBUG  ] Finished ['git', '-c', 'diff.ignoreSubmodules=none', 'merge-base', '--is-ancestor', 'bf-docs', 'origin/bf-dflt-dsdescr'] with status 1 
[DEBUG  ] Run ['git', '-c', 'diff.ignoreSubmodules=none', 'merge-base', '--is-ancestor', 'bf-docs', 'origin/bf-docs'] (cwd=/home/loj/git/UXfix/datalad-hirni) 
[DEBUG  ] Finished ['git', '-c', 'diff.ignoreSubmodules=none', 'merge-base', '--is-ancestor', 'bf-docs', 'origin/bf-docs'] with status 0 
[DEBUG  ] Run ['git', '-c', 'diff.ignoreSubmodules=none', 'merge-base', '--is-ancestor', 'master', 'origin/HEAD'] (cwd=/home/loj/git/UXfix/datalad-hirni) 
[DEBUG  ] Finished ['git', '-c', 'diff.ignoreSubmodules=none', 'merge-base', '--is-ancestor', 'master', 'origin/HEAD'] with status 1 
[DEBUG  ] Run ['git', '-c', 'diff.ignoreSubmodules=none', 'merge-base', '--is-ancestor', 'master', 'origin/bf-dflt-dsdescr'] (cwd=/home/loj/git/UXfix/datalad-hirni) 
[DEBUG  ] Finished ['git', '-c', 'diff.ignoreSubmodules=none', 'merge-base', '--is-ancestor', 'master', 'origin/bf-dflt-dsdescr'] with status 1 
[DEBUG  ] Run ['git', '-c', 'diff.ignoreSubmodules=none', 'merge-base', '--is-ancestor', 'master', 'origin/bf-docs'] (cwd=/home/loj/git/UXfix/datalad-hirni) 
[DEBUG  ] Finished ['git', '-c', 'diff.ignoreSubmodules=none', 'merge-base', '--is-ancestor', 'master', 'origin/bf-docs'] with status 0 
[DEBUG  ] Run ['git', '-c', 'diff.ignoreSubmodules=none', 'cat-file', '-p', 'git-annex:uuid.log'] (cwd=/home/loj/git/UXfix/datalad-hirni) 
[DEBUG  ] Finished ['git', '-c', 'diff.ignoreSubmodules=none', 'cat-file', '-p', 'git-annex:uuid.log'] with status 128 
[Level 11] CommandError: 'git -c diff.ignoreSubmodules=none cat-file -p git-annex:uuid.log' failed with exitcode 128 under /home/loj/git/UXfix/datalad-hirni [err: 'fatal: Not a valid object name git-annex:uuid.log'] 
[DEBUG  ] Run ['git', '-c', 'diff.ignoreSubmodules=none', 'cat-file', '-p', 'upstream/git-annex:uuid.log'] (cwd=/home/loj/git/UXfix/datalad-hirni) 
[DEBUG  ] Finished ['git', '-c', 'diff.ignoreSubmodules=none', 'cat-file', '-p', 'upstream/git-annex:uuid.log'] with status 0 
[ERROR  ] TypeError(startswith first arg must be str or a tuple of str, not NoneType) (TypeError)
```
</details>

<details><summary>with dbg</summary>

```
❱ datalad --dbg remove -d datalad-hirni                                                                                                                                                                         
Traceback (most recent call last):
  File "/home/loj/.venvs/dl-latest/bin/datalad", line 33, in <module>
    sys.exit(load_entry_point('datalad', 'console_scripts', 'datalad')())
  File "/home/loj/git/new/datalad/datalad/cmdline/main.py", line 205, in main
    ret = cmdlineargs.func(cmdlineargs)
  File "/home/loj/git/new/datalad/datalad/interface/base.py", line 786, in call_from_parser
    ret = list(ret)
  File "/home/loj/git/new/datalad/datalad/interface/utils.py", line 396, in generator_func
    for r in _process_results(
  File "/home/loj/git/new/datalad/datalad/interface/utils.py", line 579, in _process_results
    for res in results:
  File "/home/loj/git/new/datalad/datalad/local/remove.py", line 189, in __call__
    for res in Drop.__call__(
  File "/home/loj/git/new/datalad/datalad/interface/utils.py", line 396, in generator_func
    for r in _process_results(
  File "/home/loj/git/new/datalad/datalad/interface/utils.py", line 579, in _process_results
    for res in results:
  File "/home/loj/git/new/datalad/datalad/distributed/drop.py", line 267, in __call__
    for res in _drop_dataset(
  File "/home/loj/git/new/datalad/datalad/distributed/drop.py", line 358, in _drop_dataset
    for res in _fatal_pre_drop_checks(
  File "/home/loj/git/new/datalad/datalad/distributed/drop.py", line 500, in _fatal_pre_drop_checks
    for r in _detect_nondead_annex_at_remotes(repo, repo.uuid)
  File "/home/loj/git/new/datalad/datalad/distributed/drop.py", line 664, in _detect_nondead_annex_at_remotes
    if line.startswith(annex_uuid):
TypeError: startswith first arg must be str or a tuple of str, not NoneType

> /home/loj/git/new/datalad/datalad/distributed/drop.py(664)_detect_nondead_annex_at_remotes()
-> if line.startswith(annex_uuid):

```

</details>

### Datalad information

```
❱ datalad --version
datalad 0.15.3+208.g981aa95ba
```

### Additional context

Since I couldn't provide a way to reproduce the error, let me know if there's any other information I can provide to help.

**Comment by mih** [comment]
Thx for the precise report. This seems to be `drop`'s fault. Can you confirm this also with

```
datalad drop -d datalad-hirni
```

?

**Comment by loj** [comment]
`datalad drop -d datalad-hirni` produced no output, not even an error.

**Comment by mih** [comment]
OK, will compose a test!

**Comment by mih** [comment]
From live debugging: This is an `AnnexRepo` that has no `annex.uuid`

**Comment by mih** [comment]
Conclusion: The reason is that this is a could-be-annex-repo that was just git-cloned -- not datalad-cloned.

In my implementation effort I posted https://github.com/datalad/datalad/issues/6103 which led my to implement `isinstance(repo, AnnexRepo)` as the test for an annex repo, which is the underlying cause of this issue, because decision making is based on whether something is a `AnnexRepo`. It seems that a more sophisticated evaluation needs to be made: "initialized vs uninitialized annexrepo".

**Comment by bpoldrack** [comment]
ATM, I think the fix is to not end up with an `AnnexRepo` in the first place.
Currently its `__init__` is actually checking that condition and trigger an `git annex init` call if the instantiation was also called with `create=True` or `init=True`. If neither one is given it just goes on and does not react to its realization that this is an uninitialized annex. It could raise instead, hence causing `ds.repo` to get a `GitRepo` instead.
I am not currently seeing where the behavior of succesfully initiating such an instance would be useful.

**Comment by mih** [comment]
I think this should be a separate issue that has likely more implications. I will fix this particular issue in a different fashion. Thx.
