### ISSUE TITLE
Nose is incompatible with Python 3.10

### ISSUE THREAD

**Issue by adswa** [datalad/datalad#6211]
Running the test suite under Python 3.10 throws internal errors:
```
C:\Users\adina\repos\datalad>python -m nose -s -v --traverse-namespace datalad/core/tests
Traceback (most recent call last):
  File "C:\Users\adina\AppData\Local\Programs\Python\Python310\lib\runpy.py", line 196, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "C:\Users\adina\AppData\Local\Programs\Python\Python310\lib\runpy.py", line 86, in _run_code
    exec(code, run_globals)
  File "C:\Users\adina\AppData\Local\Programs\Python\Python310\lib\site-packages\nose\__main__.py", line 8, in <module>
    run_exit()
  File "C:\Users\adina\AppData\Local\Programs\Python\Python310\lib\site-packages\nose\core.py", line 118, in __init__
    unittest.TestProgram.__init__(
  File "C:\Users\adina\AppData\Local\Programs\Python\Python310\lib\unittest\main.py", line 100, in __init__
    self.parseArgs(argv)
  File "C:\Users\adina\AppData\Local\Programs\Python\Python310\lib\site-packages\nose\core.py", line 179, in parseArgs
    self.createTests()
  File "C:\Users\adina\AppData\Local\Programs\Python\Python310\lib\site-packages\nose\core.py", line 193, in createTests
    self.test = self.testLoader.loadTestsFromNames(self.testNames)
  File "C:\Users\adina\AppData\Local\Programs\Python\Python310\lib\site-packages\nose\loader.py", line 481, in loadTestsFromNames
    return unittest.TestLoader.loadTestsFromNames(self, names, module)
  File "C:\Users\adina\AppData\Local\Programs\Python\Python310\lib\unittest\loader.py", line 220, in loadTestsFromNames
    suites = [self.loadTestsFromName(name, module) for name in names]
  File "C:\Users\adina\AppData\Local\Programs\Python\Python310\lib\unittest\loader.py", line 220, in <listcomp>
    suites = [self.loadTestsFromName(name, module) for name in names]
  File "C:\Users\adina\AppData\Local\Programs\Python\Python310\lib\site-packages\nose\loader.py", line 459, in loadTestsFromName
    return suite([
  File "C:\Users\adina\AppData\Local\Programs\Python\Python310\lib\site-packages\nose\suite.py", line 423, in __call__
    tests = self.wrapTests(tests)
  File "C:\Users\adina\AppData\Local\Programs\Python\Python310\lib\site-packages\nose\suite.py", line 541, in wrapTests
    if isinstance(tests, collections.Callable) or isinstance(tests, unittest.TestSuite):
AttributeError: module 'collections' has no attribute 'Callable'
```

This is known, seems to apply to Python 3.9 already, and won't be fixed: https://github.com/nose-devs/nose/issues/1099
A temporary work around for now is to do:

```
pip uninstall nose
pip install -U nose --no-binary :all:
```

**Comment by adswa** [comment]
Closing this FOI issue.
