### ISSUE TITLE
Potential Keyring problem buried in debug log

### ISSUE THREAD

**Issue by adswa** [datalad/datalad#6233]
I just received a report from a user failing to ``get`` HCP data. It was possible before, but failed after the user had their home directory on a cluster reset.

The error log looks like this:

```
(forlina) schaare@comps06h02:/data/pt_02319/schaare/cingulate/project/hcp-functional-connectivity > datalad get 100206/MNINonLinear/Results/rfMRI_REST1_LR/rfMRI_REST1_LR_hp2000_clean.nii.gz
get(error): 100206/MNINonLinear/Results/rfMRI_REST1_LR/rfMRI_REST1_LR_hp2000_clean.nii.gz (file) [RuntimeError(Failed to download from any of 1 locations)
RuntimeError(Failed to download from any of 1 locations)
RuntimeError(Failed to download from any of 1 locations)]
(forlina) schaare@comps06h02:/data/pt_02319/schaare/cingulate/project/hcp-functional-connectivity > git-annex get -v -d 100206/MNINonLinear/Results/rfMRI_REST1_LR/rfMRI_REST1_LR_hp2000_clean.nii.gz
[2021-11-22 23:01:59.793047] (Utility.Process) process [1023412] read: git ["--git-dir=.git","--work-tree=.","--literal-pathspecs","-c","annex.debug=true","symbolic-ref","-q","HEAD"]
[2021-11-22 23:01:59.79894] (Utility.Process) process [1023412] done ExitSuccess
[2021-11-22 23:01:59.79981] (Utility.Process) process [1023413] read: git ["--git-dir=.git","--work-tree=.","--literal-pathspecs","-c","annex.debug=true","show-ref","refs/heads/master"]
[2021-11-22 23:01:59.813973] (Utility.Process) process [1023413] done ExitSuccess
[2021-11-22 23:01:59.816022] (Utility.Process) process [1023414] read: git ["--git-dir=.git","--work-tree=.","--literal-pathspecs","-c","annex.debug=true","ls-files","--stage","-z","--","100206/MNINonLinear/Results/rfMRI_REST1_LR/rfMRI_REST1_LR_hp2000_clean.nii.gz"]
[2021-11-22 23:01:59.81696] (Utility.Process) process [1023415] chat: git ["--git-dir=.git","--work-tree=.","--literal-pathspecs","-c","annex.debug=true","cat-file","--batch-check=%(objectname) %(objecttype) %(objectsize)","--buffer"]
[2021-11-22 23:01:59.818167] (Utility.Process) process [1023416] chat: git ["--git-dir=.git","--work-tree=.","--literal-pathspecs","-c","annex.debug=true","cat-file","--batch=%(objectname) %(objecttype) %(objectsize)","--buffer"]
[2021-11-22 23:01:59.819044] (Utility.Process) process [1023417] chat: git ["--git-dir=.git","--work-tree=.","--literal-pathspecs","-c","annex.debug=true","cat-file","--batch=%(objectname) %(objecttype) %(objectsize)","--buffer"]
get 100206/MNINonLinear/Results/rfMRI_REST1_LR/rfMRI_REST1_LR_hp2000_clean.nii.gz [2021-11-22 23:01:59.850993] (Utility.Process) process [1023418] read: git ["--git-dir=.git","--work-tree=.","--literal-pathspecs","-c","annex.debug=true","show-ref","git-annex"]
[2021-11-22 23:01:59.857489] (Utility.Process) process [1023418] done ExitSuccess
[2021-11-22 23:01:59.858419] (Utility.Process) process [1023419] read: git ["--git-dir=.git","--work-tree=.","--literal-pathspecs","-c","annex.debug=true","show-ref","--hash","refs/heads/git-annex"]
[2021-11-22 23:01:59.865532] (Utility.Process) process [1023419] done ExitSuccess
[2021-11-22 23:01:59.867022] (Utility.Process) process [1023420] read: git ["--git-dir=.git","--work-tree=.","--literal-pathspecs","-c","annex.debug=true","log","refs/heads/git-annex..fcfac538b71e51dfafdbc59eca920926cd14a80f","--pretty=%H","-n1"]
[2021-11-22 23:01:59.875483] (Utility.Process) process [1023420] done ExitSuccess
[2021-11-22 23:01:59.876314] (Utility.Process) process [1023421] read: git ["--git-dir=.git","--work-tree=.","--literal-pathspecs","-c","annex.debug=true","log","refs/heads/git-annex..aa3b12ecd738da8464eb5186614b988fa5ccfda5","--pretty=%H","-n1"]
[2021-11-22 23:01:59.881743] (Utility.Process) process [1023421] done ExitSuccess
[2021-11-22 23:01:59.88468] (Utility.Process) process [1023422] chat: git ["--git-dir=.git","--work-tree=.","--literal-pathspecs","-c","annex.debug=true","cat-file","--batch"]
(from datalad...) 
[2021-11-22 23:01:59.918732] (Utility.Process) process [1023423] chat: /data/u_schaare_software/anaconda3/envs/forlina/bin/git-annex-remote-datalad []
[2021-11-22 23:02:00.866502] (Annex.ExternalAddonProcess) /data/u_schaare_software/anaconda3/envs/forlina/bin/git-annex-remote-datalad[1] --> VERSION 1
[2021-11-22 23:02:00.866789] (Annex.ExternalAddonProcess) /data/u_schaare_software/anaconda3/envs/forlina/bin/git-annex-remote-datalad[1] <-- EXTENSIONS INFO GETGITREMOTENAME ASYNC
[2021-11-22 23:02:00.867176] (Annex.ExternalAddonProcess) /data/u_schaare_software/anaconda3/envs/forlina/bin/git-annex-remote-datalad[1] --> UNSUPPORTED-REQUEST
[2021-11-22 23:02:00.867302] (Annex.ExternalAddonProcess) /data/u_schaare_software/anaconda3/envs/forlina/bin/git-annex-remote-datalad[1] <-- PREPARE
[2021-11-22 23:02:00.8675] (Annex.ExternalAddonProcess) /data/u_schaare_software/anaconda3/envs/forlina/bin/git-annex-remote-datalad[1] --> PREPARE-SUCCESS
[2021-11-22 23:02:00.867607] (Annex.ExternalAddonProcess) /data/u_schaare_software/anaconda3/envs/forlina/bin/git-annex-remote-datalad[1] <-- TRANSFER RETRIEVE MD5E-s997493205--ba3295e0281ed1d910107326a65d220f.nii.gz .git/annex/tmp/MD5E-s997493205--ba3295e0281ed1d910107326a65d220f.nii.gz
[2021-11-22 23:02:00.867726] (Annex.ExternalAddonProcess) /data/u_schaare_software/anaconda3/envs/forlina/bin/git-annex-remote-datalad[1] --> DEBUG Encodings: filesystem utf-8, default utf-8
[2021-11-22 23:02:00.867806] (Remote.External) Encodings: filesystem utf-8, default utf-8
[2021-11-22 23:02:00.867878] (Annex.ExternalAddonProcess) /data/u_schaare_software/anaconda3/envs/forlina/bin/git-annex-remote-datalad[1] --> GETURLS MD5E-s997493205--ba3295e0281ed1d910107326a65d220f.nii.gz http:
[2021-11-22 23:02:00.870526] (Annex.ExternalAddonProcess) /data/u_schaare_software/anaconda3/envs/forlina/bin/git-annex-remote-datalad[1] <-- VALUE 
[2021-11-22 23:02:00.870862] (Annex.ExternalAddonProcess) /data/u_schaare_software/anaconda3/envs/forlina/bin/git-annex-remote-datalad[1] --> GETURLS MD5E-s997493205--ba3295e0281ed1d910107326a65d220f.nii.gz https:
[2021-11-22 23:02:00.871074] (Annex.ExternalAddonProcess) /data/u_schaare_software/anaconda3/envs/forlina/bin/git-annex-remote-datalad[1] <-- VALUE 
[2021-11-22 23:02:00.871342] (Annex.ExternalAddonProcess) /data/u_schaare_software/anaconda3/envs/forlina/bin/git-annex-remote-datalad[1] --> GETURLS MD5E-s997493205--ba3295e0281ed1d910107326a65d220f.nii.gz s3:
[2021-11-22 23:02:00.871521] (Annex.ExternalAddonProcess) /data/u_schaare_software/anaconda3/envs/forlina/bin/git-annex-remote-datalad[1] <-- VALUE s3://hcp-openaccess/HCP_1200/100206/MNINonLinear/Results/rfMRI_REST1_LR/rfMRI_REST1_LR_hp2000_clean.nii.gz?versionId=N68j6mHhUPCEHIjZ7NOY2EgvsLo7gD.u
[2021-11-22 23:02:00.871637] (Annex.ExternalAddonProcess) /data/u_schaare_software/anaconda3/envs/forlina/bin/git-annex-remote-datalad[1] <-- VALUE 
[INFO] Downloading 's3://hcp-openaccess/HCP_1200/100206/MNINonLinear/Results/rfMRI_REST1_LR/rfMRI_REST1_LR_hp2000_clean.nii.gz?versionId=N68j6mHhUPCEHIjZ7NOY2EgvsLo7gD.u' into '.git/annex/tmp/MD5E-s997493205--ba3295e0281ed1d910107326a65d220f.nii.gz' 
[2021-11-22 23:02:01.233058] (Annex.ExternalAddonProcess) /data/u_schaare_software/anaconda3/envs/forlina/bin/git-annex-remote-datalad[1] --> DEBUG Failed to download url s3://hcp-openaccess/HCP_1200/100206/MNINonLinear/Results/rfMRI_REST1_LR/rfMRI_REST1_LR_hp2000_clean.nii.gz?versionId=N68j6mHhUPCEHIjZ7NOY2EgvsLo7gD.u for key MD5E-s997493205--ba3295e0281ed1d910107326a65d220f.nii.gz: InitError(Failed to create the collection: Prompt dismissed..)
[2021-11-22 23:02:01.233291] (Remote.External) Failed to download url s3://hcp-openaccess/HCP_1200/100206/MNINonLinear/Results/rfMRI_REST1_LR/rfMRI_REST1_LR_hp2000_clean.nii.gz?versionId=N68j6mHhUPCEHIjZ7NOY2EgvsLo7gD.u for key MD5E-s997493205--ba3295e0281ed1d910107326a65d220f.nii.gz: InitError(Failed to create the collection: Prompt dismissed..)
[2021-11-22 23:02:01.233379] (Annex.ExternalAddonProcess) /data/u_schaare_software/anaconda3/envs/forlina/bin/git-annex-remote-datalad[1] --> GETURLS MD5E-s997493205--ba3295e0281ed1d910107326a65d220f.nii.gz shub:
[2021-11-22 23:02:01.233571] (Annex.ExternalAddonProcess) /data/u_schaare_software/anaconda3/envs/forlina/bin/git-annex-remote-datalad[1] <-- VALUE 
[2021-11-22 23:02:01.235499] (Annex.ExternalAddonProcess) /data/u_schaare_software/anaconda3/envs/forlina/bin/git-annex-remote-datalad[1] --> TRANSFER-FAILURE RETRIEVE MD5E-s997493205--ba3295e0281ed1d910107326a65d220f.nii.gz RuntimeError(Failed to download from any of 1 locations)

  RuntimeError(Failed to download from any of 1 locations)
[2021-11-22 23:02:01.239246] (Utility.Process) process [1023422] done ExitSuccess

  Unable to access these remotes: datalad
[2021-11-22 23:02:01.247356] (Utility.Process) process [1023458] chat: git ["--git-dir=.git","--work-tree=.","--literal-pathspecs","-c","annex.debug=true","cat-file","--batch"]

  No other repository is known to contain the file.

  (Note that these git remotes have annex-ignore set: origin)
failed
[2021-11-22 23:02:01.258319] (Utility.Process) process [1023458] done ExitSuccess
[2021-11-22 23:02:01.258544] (Utility.Process) process [1023417] done ExitSuccess
[2021-11-22 23:02:01.258673] (Utility.Process) process [1023416] done ExitSuccess
[2021-11-22 23:02:01.258783] (Utility.Process) process [1023415] done ExitSuccess
[2021-11-22 23:02:01.258875] (Utility.Process) process [1023414] done ExitSuccess
[2021-11-22 23:02:01.359254] (Utility.Process) process [1023423] done ExitSuccess
get: 1 failed
```

My initial guess for the cause is in

```
[2021-11-22 23:02:01.233291] (Remote.External) Failed to download url s3://hcp-openaccess/HCP_1200/100206/MNINonLinear/Results/rfMRI_REST1_LR/rfMRI_REST1_LR_hp2000_clean.nii.gz?versionId=N68j6mHhUPCEHIjZ7NOY2EgvsLo7gD.u for key MD5E-s997493205--ba3295e0281ed1d910107326a65d220f.nii.gz: InitError(Failed to create the collection: Prompt dismissed..)
```
Which is an internal error of the keyring. The user also reports that the paths to keyring configurations and files reported by ``datalad wtf`` do not exist.
If it turns out to be the keyring, maybe we can find a way to bubble this up more gracefully than a ``RunTimeError``

**Comment by bpoldrack** [comment]
Is there an existing provider config (either in dataset or `~/.config/datalad/providers`)?

The issue may arise from datalad looking for a particular credential and failing to ask when this is suddenly missing (as opposed to the situation where there is nothing specified to look up).

**Comment by adswa** [comment]
> Is there an existing provider config (either in dataset or ~/.config/datalad/providers)?

No, none. 

More hints that something is wrong with the key ring:

```
>>> keyring.get_password("datalad-hcp-s3","secret_id")
Traceback (most recent call last):
  File "/data/u_schaare_software/anaconda3/envs/foradina/lib/python3.7/site-packages/secretstorage/util.py", line 46, in send_and_get_reply
    return self._connection.send_and_get_reply(msg, unwrap=True)
  File "/data/u_schaare_software/anaconda3/envs/foradina/lib/python3.7/site-packages/jeepney/io/blocking.py", line 190, in send_and_get_reply
    return unwrap_msg(msg_in)
  File "/data/u_schaare_software/anaconda3/envs/foradina/lib/python3.7/site-packages/jeepney/wrappers.py", line 214, in unwrap_msg
    raise DBusErrorResponse(msg)
jeepney.wrappers.DBusErrorResponse: [org.freedesktop.DBus.Error.UnknownMethod] ("No such interface 'org.freedesktop.DBus.Properties' on object at path /org/freedesktop/secrets/collection/login",)

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/data/u_schaare_software/anaconda3/envs/foradina/lib/python3.7/site-packages/secretstorage/collection.py", line 161, in get_default_collection
    return Collection(connection)
  File "/data/u_schaare_software/anaconda3/envs/foradina/lib/python3.7/site-packages/secretstorage/collection.py", line 44, in __init__
    self._collection.get_property('Label')
  File "/data/u_schaare_software/anaconda3/envs/foradina/lib/python3.7/site-packages/secretstorage/util.py", line 64, in get_property
    (signature, value), = self.send_and_get_reply(msg)
  File "/data/u_schaare_software/anaconda3/envs/foradina/lib/python3.7/site-packages/secretstorage/util.py", line 49, in send_and_get_reply
    raise ItemNotFoundException('Item does not exist!') from resp
secretstorage.exceptions.ItemNotFoundException: Item does not exist!

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/data/u_schaare_software/anaconda3/envs/foradina/lib/python3.7/site-packages/keyring/backends/SecretService.py", line 61, in get_preferred_collection
    collection = secretstorage.get_default_collection(bus)
  File "/data/u_schaare_software/anaconda3/envs/foradina/lib/python3.7/site-packages/secretstorage/collection.py", line 164, in get_default_collection
    'default', session)
  File "/data/u_schaare_software/anaconda3/envs/foradina/lib/python3.7/site-packages/secretstorage/collection.py", line 145, in create_collection
    raise PromptDismissedException('Prompt dismissed.')
secretstorage.exceptions.PromptDismissedException: Prompt dismissed.

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/data/u_schaare_software/anaconda3/envs/foradina/lib/python3.7/site-packages/keyring/core.py", line 55, in get_password
    return get_keyring().get_password(service_name, username)
  File "/data/u_schaare_software/anaconda3/envs/foradina/lib/python3.7/site-packages/keyring/backends/chainer.py", line 51, in get_password
    password = keyring.get_password(service, username)
  File "/data/u_schaare_software/anaconda3/envs/foradina/lib/python3.7/site-packages/keyring/backends/SecretService.py", line 78, in get_password
    collection = self.get_preferred_collection()
  File "/data/u_schaare_software/anaconda3/envs/foradina/lib/python3.7/site-packages/keyring/backends/SecretService.py", line 63, in get_preferred_collection
    raise InitError("Failed to create the collection: %s." % e)
keyring.errors.InitError: Failed to create the collection: Prompt dismissed..
```

**Comment by adswa** [comment]
DataLad ``0.15.3`` from ``conda-forge``, git annex from October 2021

**Comment by adswa** [comment]
User reported back, IT fixed password management and the issue resolved itself.
