### ISSUE TITLE
1 ERROR and 1 FAIL on windows while testing recent git-annex on master

### ISSUE THREAD

**Issue by yarikoptic** [datalad/datalad#6237]
Started to happen awhile back: example recent run  https://github.com/datalad/git-annex/runs/4294977555?check_suite_focus=true

1.

```
======================================================================
FAIL: datalad.distribution.tests.test_install.test_install_dataset_from_just_source
----------------------------------------------------------------------
Traceback (most recent call last):
  File "C:\hostedtoolcache\windows\Python\3.7.9\x64\lib\site-packages\nose\case.py", line 198, in runTest
    self.test(*self.arg)
  File "C:\hostedtoolcache\windows\Python\3.7.9\x64\lib\site-packages\datalad\tests\utils.py", line 1157, in _wrap_with_testrepos
    t(*(arg + (uri,)), **kw)
  File "C:\hostedtoolcache\windows\Python\3.7.9\x64\lib\site-packages\datalad\tests\utils.py", line 856, in _wrap_with_tempfile
    return t(*(arg + (filename,)), **kw)
  File "C:\hostedtoolcache\windows\Python\3.7.9\x64\lib\site-packages\datalad\distribution\tests\test_install.py", line 248, in test_install_dataset_from_just_source
    assert_repo_status(ds.path, annex=None)
  File "C:\hostedtoolcache\windows\Python\3.7.9\x64\lib\site-packages\datalad\tests\utils.py", line 1738, in assert_repo_status
    % (state, state_files, oktobefound))
AssertionError: unexpected content of state "deleted": [WindowsPath('C:/Users/runneradmin/AppData/Local/Temp/datalad_temp_m6cumsrj/testrepo--basic--r1/test-annex.dat')] != []
```

has been failing for a while (didn't check prior month)

```shell
$> git grep 'datalad.distribution.tests.test_install.test_install_dataset_from_just_source\>' | grep windows | grep master
cron-20211101/build-windows.yaml-439-280a49ed-failed/1_test-datalad (master).txt:2021-11-01T04:41:06.7132507Z datalad.distribution.tests.test_install.test_install_dataset_from_just_source ... FAIL
cron-20211101/build-windows.yaml-439-280a49ed-failed/1_test-datalad (master).txt:2021-11-01T06:06:16.3347737Z FAIL: datalad.distribution.tests.test_install.test_install_dataset_from_just_source
cron-20211101/build-windows.yaml-439-280a49ed-failed/test-datalad (master)/21_Run datalad tests.txt:2021-11-01T04:41:06.7132456Z datalad.distribution.tests.test_install.test_install_dataset_from_just_source ... FAIL
cron-20211101/build-windows.yaml-439-280a49ed-failed/test-datalad (master)/21_Run datalad tests.txt:2021-11-01T06:06:16.3347731Z FAIL: datalad.distribution.tests.test_install.test_install_dataset_from_just_source
cron-20211102/build-windows.yaml-440-280a49ed-failed/1_test-datalad (master).txt:2021-11-02T04:38:53.3262426Z datalad.distribution.tests.test_install.test_install_dataset_from_just_source ... FAIL
```
and that one only in `master` it is skipped as known to fail in `maint`

```shell
$> git grep 'datalad.distribution.tests.test_install.test_install_dataset_from_just_source\>' | grep windows | grep master
cron-20211101/build-windows.yaml-439-280a49ed-failed/1_test-datalad (master).txt:2021-11-01T04:41:06.7132507Z datalad.distribution.tests.test_install.test_install_dataset_from_just_source ... FAIL
cron-20211101/build-windows.yaml-439-280a49ed-failed/1_test-datalad (master).txt:2021-11-01T06:06:16.3347737Z FAIL: datalad.distribution.tests.test_install.test_install_dataset_from_just_source
cron-20211101/build-windows.yaml-439-280a49ed-failed/test-datalad (master)/21_Run datalad tests.txt:2021-11-01T04:41:06.7132456Z datalad.distribution.tests.test_install.test_install_dataset_from_just_source ... FAIL
cron-20211101/build-windows.yaml-439-280a49ed-failed/test-datalad (master)/21_Run datalad tests.txt:2021-11-01T06:06:16.3347731Z FAIL: datalad.distribution.tests.test_install.test_install_dataset_from_just_source
cron-20211102/build-windows.yaml-440-280a49ed-failed/1_test-datalad (master).txt:2021-11-02T04:38:53.3262426Z datalad.distribution.tests.test_install.test_install_dataset_from_just_source ... FAIL
```
and that one only in `master` it is skipped as known to fail in `maint`

2.

```
======================================================================
ERROR: datalad.local.tests.test_rerun.test_run_failure
----------------------------------------------------------------------
Traceback (most recent call last):
  File "C:\hostedtoolcache\windows\Python\3.7.9\x64\lib\site-packages\nose\case.py", line 198, in runTest
    self.test(*self.arg)
  File "C:\hostedtoolcache\windows\Python\3.7.9\x64\lib\site-packages\datalad\tests\utils.py", line 856, in _wrap_with_tempfile
    return t(*(arg + (filename,)), **kw)
  File "C:\hostedtoolcache\windows\Python\3.7.9\x64\lib\site-packages\datalad\local\tests\test_rerun.py", line 309, in test_run_failure
    ds.run("echo x>{} & false".format(op.join("sub", "grows")))
  File "C:\hostedtoolcache\windows\Python\3.7.9\x64\lib\site-packages\datalad\distribution\dataset.py", line 485, in apply_func
    return f(**kwargs)
  File "C:\hostedtoolcache\windows\Python\3.7.9\x64\lib\site-packages\datalad\interface\utils.py", line 486, in eval_func
    return return_func(*args, **kwargs)
  File "C:\hostedtoolcache\windows\Python\3.7.9\x64\lib\site-packages\datalad\interface\utils.py", line 478, in return_func
    results = list(results)
  File "C:\hostedtoolcache\windows\Python\3.7.9\x64\lib\site-packages\datalad\interface\utils.py", line 408, in generator_func
    allkwargs):
  File "C:\hostedtoolcache\windows\Python\3.7.9\x64\lib\site-packages\datalad\interface\utils.py", line 585, in _process_results
    for res in results:
  File "C:\hostedtoolcache\windows\Python\3.7.9\x64\lib\site-packages\datalad\core\local\run.py", line 277, in __call__
    dry_run=dry_run):
  File "C:\hostedtoolcache\windows\Python\3.7.9\x64\lib\site-packages\datalad\core\local\run.py", line 800, in run_command
    msg_path = relpath(opj(str(repo.dot_git), "COMMIT_EDITMSG"))
  File "C:\hostedtoolcache\windows\Python\3.7.9\x64\lib\ntpath.py", line 562, in relpath
    path_drive, start_drive))
ValueError: path is on mount 'C:', start on mount 'D:'
```

may be was just recently added?

**Comment by adswa** [comment]
They were enabled in #6120

**Comment by mih** [comment]
And the appveyor CI continues to be green. Environment differences?

**Comment by yarikoptic** [comment]
environment or "setup" or git-annex version (feels less likely), didn't investigate . 

`test_run_failure` is "interesting" though suggesting that may be there is possibly an assumption that CWD is on the same drive as may be the TMPDIR (is there multiple drives on appveyor?)

**Comment by yarikoptic** [comment]
from recent build refreshing the memory 

1st one was skipped: 2022-11-21T05:02:42.2365102Z ..\datalad\distribution\tests\test_install.py::test_install_dataset_from_just_source SKIPPED since

```
❯ git grep -B5 'test_install_dataset_from_just_source('
datalad/distribution/tests/test_install.py-@known_failure_githubci_win
datalad/distribution/tests/test_install.py-@with_tree(tree={'test.dat': "doesn't matter",
datalad/distribution/tests/test_install.py-                 'INFO.txt': "some info",
datalad/distribution/tests/test_install.py-                 'test-annex.dat': "irrelevant"})
datalad/distribution/tests/test_install.py-@with_tempfile
datalad/distribution/tests/test_install.py:def test_install_dataset_from_just_source(src_repo=None, path=None):
```

and the 2nd one is ok

```
2022-11-21T05:36:29.4825861Z ..\datalad\local\tests\test_rerun.py::test_run_failure create(ok): . (dataset)
2022-11-21T05:36:33.5738430Z add(ok): sub (dataset)
2022-11-21T05:36:33.9028605Z add(ok): .gitmodules (file)
2022-11-21T05:36:35.2173800Z save(ok): . (dataset)
2022-11-21T05:36:35.2180700Z create(ok): sub (dataset)
2022-11-21T05:36:35.2182814Z action summary:
2022-11-21T05:36:35.2183178Z   add (ok: 2)
2022-11-21T05:36:35.2183472Z   create (ok: 1)
2022-11-21T05:36:35.2183834Z   save (ok: 1)
2022-11-21T05:36:37.4072209Z add(ok): grows (file)
2022-11-21T05:36:37.4075101Z save(ok): sub (dataset)
2022-11-21T05:36:37.5483128Z add(ok): sub (dataset)
2022-11-21T05:36:37.5487128Z add(ok): .gitmodules (file)
2022-11-21T05:36:38.6435873Z save(ok): . (dataset)
2022-11-21T05:36:38.6439881Z action summary:
2022-11-21T05:36:38.6440325Z   add (ok: 3)
2022-11-21T05:36:38.6440798Z   save (ok: 2)
2022-11-21T05:36:38.8515379Z PASSED
```

since we have many other known to fail on windows which we skip
```
❯ git grep '@known_fail.*_win'|nl | tail -n1
    76	datalad/tests/test_tests_utils_pytest.py:@known_failure_githubci_win
```
no point to keep this issue open since those two were "mitigated" as far as our CI runs go
