### ISSUE TITLE
test_parent_on_unborn_branch fails locally on master

### ISSUE THREAD

**Issue by yarikoptic** [datalad/datalad#6274]
```
(git)lena:~datalad/datalad-master[master]git
$> python -m nose -s -v datalad/local/tests/test_subdataset.py:test_parent_on_unborn_branch        
datalad.local.tests.test_subdataset.test_parent_on_unborn_branch ... FAIL
Versions: annexremote=1.5.0 boto=2.49.0 cmd:7z=16.02 cmd:annex=8.20210903+git120-gdb55bec8b-1~ndall+1 cmd:bundled-git=2.24.0 cmd:git=2.24.0 cmd:system-git=2.33.1 cmd:system-ssh=8.4p1 humanize=3.11.0 iso8601=0.1.16 keyring=23.2.1 keyrings.alt=UNKNOWN msgpack=1.0.2 platformdirs=2.3.0 requests=2.26.0
Obscure filename: str=b' |;&%b5{}\'"\xce\x94\xd0\x99\xd7\xa7\xd9\x85\xe0\xb9\x97\xe3\x81\x82 .datc ' repr=' |;&%b5{}\'"ΔЙקم๗あ .datc '
Encodings: default='utf-8' filesystem='utf-8' locale.prefered='UTF-8'
Environment: PATH='/home/yoh/proj/datalad/datalad-fuse/venvs/dev3/bin:/home/yoh/gocode/bin:/home/yoh/gocode/bin:/home/yoh/bin:/home/yoh/.local/bin:/usr/local/bin:/usr/bin:/bin:/usr/local/games:/usr/games:/sbin:/usr/sbin:/usr/local/sbin' LANG='en_US.UTF-8' GIT_PAGER='less --no-init --quit-if-one-screen' GIT_CONFIG_PARAMETERS="'init.defaultBranch=master' 'clone.defaultRemoteName=origin'"

======================================================================
FAIL: datalad.local.tests.test_subdataset.test_parent_on_unborn_branch
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/yoh/proj/datalad/datalad-fuse/venvs/dev3/lib/python3.9/site-packages/nose/case.py", line 198, in runTest
    self.test(*self.arg)
  File "/home/yoh/proj/datalad/datalad-master/datalad/tests/utils.py", line 856, in _wrap_with_tempfile
    return t(*(arg + (filename,)), **kw)
  File "/home/yoh/proj/datalad/datalad-master/datalad/local/tests/test_subdataset.py", line 326, in test_parent_on_unborn_branch
    eq_(ds.subdatasets(result_xfm='relpaths'),
AssertionError: [] != ['sub']

----------------------------------------------------------------------
Ran 1 test in 0.358s

FAILED (failures=1)
```

this is on master (0.15.3-408-g07a288c6a) and on `maint` it is ok

```
(git)lena:~datalad/datalad-master[maint]git
$> git describe
0.15.3-23-gabcc1abab

$> python -m nose -s -v datalad/local/tests/test_subdataset.py:test_parent_on_unborn_branch
datalad.local.tests.test_subdataset.test_parent_on_unborn_branch ... subdataset(ok): sub (dataset)
ok
Versions: annexremote=1.5.0 appdirs=1.4.4 boto=2.49.0 cmd:7z=16.02 cmd:annex=8.20210903+git120-gdb55bec8b-1~ndall+1 cmd:bundled-git=2.24.0 cmd:git=2.24.0 cmd:system-git=2.33.1 cmd:system-ssh=8.4p1 humanize=3.11.0 iso8601=0.1.16 keyring=23.2.1 keyrings.alt=UNKNOWN msgpack=1.0.2 requests=2.26.0 wrapt=1.12.1
Obscure filename: str=b' |;&%b5{}\'"\xce\x94\xd0\x99\xd7\xa7\xd9\x85\xe0\xb9\x97\xe3\x81\x82 .datc ' repr=' |;&%b5{}\'"ΔЙקم๗あ .datc '
Encodings: default='utf-8' filesystem='utf-8' locale.prefered='UTF-8'
Environment: PATH='/home/yoh/proj/datalad/datalad-fuse/venvs/dev3/bin:/home/yoh/gocode/bin:/home/yoh/gocode/bin:/home/yoh/bin:/home/yoh/.local/bin:/usr/local/bin:/usr/bin:/bin:/usr/local/games:/usr/games:/sbin:/usr/sbin:/usr/local/sbin' LANG='en_US.UTF-8' GIT_PAGER='less --no-init --quit-if-one-screen' GIT_CONFIG_PARAMETERS="'init.defaultBranch=master' 'clone.defaultRemoteName=origin'"

----------------------------------------------------------------------
Ran 1 test in 0.881s

OK
```

bisection claims that e07724c5c3a3b0b4a2a4222a5d7c50b43745fbc2 is the first bad commit. Reversing back this diff
```
diff --git a/datalad/local/tests/test_subdataset.py b/datalad/local/tests/test_subdataset.py
index 7ddfbc2c8..83cb142c2 100644
--- a/datalad/local/tests/test_subdataset.py
+++ b/datalad/local/tests/test_subdataset.py
@@ -321,6 +321,6 @@ def test_parent_on_unborn_branch(path):
     subrepo = GitRepo(opj(path, "sub"), create=True)
     subrepo.commit(msg="c", options=["--allow-empty"])
 
-    ds.repo.add_submodule(path="sub")
+    ds.repo.save(path="sub")
     eq_(ds.subdatasets(result_xfm='relpaths'),
         ["sub"])
```
"fixes" the test back then.  So, why `.save` is special on my system?

**Comment by mih** [comment]
Which of your git versions is the test using? 2.33 or 2.24?

**Comment by yarikoptic** [comment]
It said `cmd:git=2.24.0`

**Comment by mih** [comment]
Can you also try with your `cmd:system-git=2.33.1`?

**Comment by yarikoptic** [comment]
<details>
<summary>that one is ok</summary> 

```shell
$> DATALAD_USE_DEFAULT_GIT=1 python -m nose -s -v datalad/local/tests/test_subdataset.py:test_parent_on_unborn_branch
datalad.local.tests.test_subdataset.test_parent_on_unborn_branch ... subdataset(ok): sub (dataset)
ok
Versions: annexremote=1.5.0 boto=2.49.0 cmd:7z=16.02 cmd:annex=8.20210903+git120-gdb55bec8b-1~ndall+1 cmd:bundled-git=2.24.0 cmd:git=2.33.1 cmd:system-git=2.33.1 cmd:system-ssh=8.4p1 exifread=2.3.2 git=3.1.23 gitdb=4.0.7 humanize=0.0.0 iso8601=0.1.16 keyring=23.2.0 keyrings.alt=UNKNOWN msgpack=1.0.2 mutagen=1.45.1 platformdirs=2.4.0 requests=2.25.1 scrapy=2.5.1
Obscure filename: str=b' |;&%b5{}\'"\xce\x94\xd0\x99\xd7\xa7\xd9\x85\xe0\xb9\x97\xe3\x81\x82 .datc ' repr=' |;&%b5{}\'"ΔЙקم๗あ .datc '
Encodings: default='utf-8' filesystem='utf-8' locale.prefered='UTF-8'
Environment: PATH='/home/yoh/proj/datalad/datalad-crawler/venvs/dev3/bin:/home/yoh/gocode/bin:/home/yoh/gocode/bin:/home/yoh/bin:/home/yoh/.local/bin:/usr/local/bin:/usr/bin:/bin:/usr/local/games:/usr/games:/sbin:/usr/sbin:/usr/local/sbin' LANG='en_US.UTF-8' GIT_PAGER='less --no-init --quit-if-one-screen' GIT_CONFIG_PARAMETERS="'init.defaultBranch=dl-test-branch' 'clone.defaultRemoteName=dl-test-remote'" GIT_CONFIG_GLOBAL='/home/yoh/.tmp/datalad_temp_juvfrwdo/.gitconfig'

----------------------------------------------------------------------
Ran 1 test in 0.582s

OK
```
</details>

**Comment by adswa** [comment]
I quickly browsed the release notes of Git but I only found 

```
 * Running "git add" on a repository created inside the current
   repository is an explicit indication that the user wants to add it
   as a submodule, but when the HEAD of the inner repository is on an
   unborn branch, it cannot be added as a submodule.  Worse, the files
   in its working tree can be added as if they are a part of the outer
   repository, which is not what the user wants.  These problems are
   being addressed.
   (merge f937bc2f86 km/empty-repo-is-still-a-repo later to maint).
```

(in ``2.22.0`` which is a [commit made by Kyle](https://github.com/git/git/commit/f937bc2f86ba2c2956b4228bd2386aaafc9afe83) and relates to https://github.com/datalad/datalad/pull/3476). I couldn't find more afterwards, but maybe if we find the git version this first fails with one can take a closer look?
