### ISSUE TITLE
runner timeout test fails on windows

### ISSUE THREAD

**Issue by mih** [datalad/datalad#6308]
```
======================================================================
FAIL: datalad.runner.tests.test_nonasyncrunner.test_timeout
----------------------------------------------------------------------
Traceback (most recent call last):
  File "C:\Python39-x64\lib\site-packages\nose\case.py", line 198, in runTest
    self.test(*self.arg)
  File "c:\projects\datalad\datalad\runner\tests\test_nonasyncrunner.py", line 427, in test_timeout
    assert_true(len(TestProtocol.received_timeouts) > 0)
AssertionError: False is not true
```

This seems to happen continuously now. @christian-monch can you have a look please?

**Comment by mih** [comment]
Closed by #6311. Thanks @christian-monch
