### ISSUE TITLE
[ERROR  ] ImportError(cannot import name 'Runner') (ImportError)

### ISSUE THREAD

**Issue by dorianps** [datalad/datalad#6348]
### What is the problem?

Does anyone know what does this mean, and if it's a problem:

```
[dorian@mri bids]$ datalad siblings add --recursive --name sandy --url $baseremote
.: sandy(+) [/DATA/user1/study1/data/bids (git)]
[ERROR  ] ImportError(cannot import name 'Runner') (ImportError)
```

The sibling is added, and I am about to merge some data from this remote/sibling, but wanted to make sure what is this problem about before I proceed.

### What steps will reproduce the problem?

Command is above.

### Datalad information

datalad 0.15.4 -- (recently updated from v13.x)

Please note:
```
[dorian@mri bids]$ datalad wtf
[ERROR  ] ImportError(cannot import name 'Runner') (ImportError)
```

### Additional context

NA

### Have you had any success using DataLad before?

Yes, as usual.

**Comment by yarikoptic** [comment]
Could you run with --dbg - may be we would be lucky to see backtrace (ie it is not swallowed)?

**Comment by dorianps** [comment]
```
[dorian@mri bids]$ datalad --dbg wtf
Traceback (most recent call last):
  File "/usr/local/bin/datalad", line 8, in <module>
    sys.exit(main())
  File "/usr/local/lib/python3.6/site-packages/datalad/cmdline/main.py", line 211, in main
    ret = cmdlineargs.func(cmdlineargs)
  File "/usr/local/lib/python3.6/site-packages/datalad/interface/base.py", line 786, in call_from_parser
    ret = list(ret)
  File "/usr/local/lib/python3.6/site-packages/datalad/interface/utils.py", line 408, in generator_func
    allkwargs):
  File "/usr/local/lib/python3.6/site-packages/datalad/interface/utils.py", line 579, in _process_results
    for res in results:
  File "/usr/local/lib/python3.6/site-packages/datalad/local/wtf.py", line 455, in __call__
    infos[s] = section_callables[s]()
  File "/usr/local/lib/python3.6/site-packages/datalad/local/wtf.py", line 239, in _describe_dataset
    from datalad.api import metadata
  File "/usr/local/lib/python3.6/site-packages/datalad/api.py", line 79, in <module>
    _generate_extension_api()
  File "/usr/local/lib/python3.6/site-packages/datalad/api.py", line 68, in _generate_extension_api
    mod = import_module(intfspec[0])
  File "/usr/lib64/python3.6/importlib/__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "/usr/local/lib/python3.6/site-packages/datalad_container/containers_add.py", line 13, in <module>
    from datalad.cmd import Runner
ImportError: cannot import name 'Runner'

> /usr/local/lib/python3.6/site-packages/datalad_container/containers_add.py(13)<module>()
-> from datalad.cmd import Runner
```

**Comment by yarikoptic** [comment]
please `pip install -u datalad-container` . Unfortunately python/setuptools does not allow to declare "Breaks" dependency (like Debian does) so whenever a new datalad version breaks compatibility with some extension, we can't really declare that :-/ BUT it doesn't mean that we shouldn't be able to 
- improve `api.py", line 68, in _generate_extension_api` to report that it is the extension X which fails to import (and just skip it probably without crashing entire process)
- we could even use etelemetry may be somehow to check if newer version of extension is available and report to the user that.

**Comment by dorianps** [comment]
@yarikoptic  thanks. This works, my issue is resolved, you can close it unless you need it open as a reminder.

On a side note, I still keep seeing the strange "Installing dataset" line when I merge datasets locally. It is not a problem for me worth opening a new issue, but I kind of remember that you said sometime ago that the message is incorrect:

```
[dorian@mri bids]$ datalad get --source john --recursive .
[INFO   ] Installing Dataset(/DATA/FEDERATED_DATASETS/Study1/data/bids) to get /DATA/FEDERATED_DATASETS/Study1/data/bids recursively
Total:   2%|██▍                                                                                                     | 2.01G/85.4G [00:25<17:49, 78.0M Bytes/s]
```

**Comment by yarikoptic** [comment]
Re original issue -- retitled this one, we better address it.

Re "Installing dataset" -- please do file a separate issue (unless you find that there is an already open one). Note: that I also do not get why this particular message since "to get" part should be only if first path is not the same as the 2nd one and they are identical here.
