### ISSUE TITLE
'NoneType' object has no attribute 'isatty'

### ISSUE THREAD

**Issue by r-levchenko** [datalad/datalad#6357]
### What is the problem?

There was a strange glitch in the library, 
failure is not stable, usually everything works

> unable to use special remote due to protocol error
  external special remote protocol error, unexpectedly received "<EOF>" (unable to parse command) [err: 'Traceback (most recent call last):
  File "/p/fastdata/bigbrains/software/miniconda3/bin/git-annex-remote-ora", line 7, in <module>
    from datalad.distributed.ora_remote import main
  File "/p/home/jusers/levchenko1/jureca/.local/lib/python3.8/site-packages/datalad/__init__.py", line 50, in <module>
    from .log import lgr
  File "/p/home/jusers/levchenko1/jureca/.local/lib/python3.8/site-packages/datalad/log.py", line 24, in <module>
    from .support import ansi_colors as colors
  File "/p/home/jusers/levchenko1/jureca/.local/lib/python3.8/site-packages/datalad/support/ansi_colors.py", line 13, in <module>
    from ..ui import ui
  File "/p/home/jusers/levchenko1/jureca/.local/lib/python3.8/site-packages/datalad/ui/__init__.py", line 110, in <module>
    ui = _UI_Switcher()
  File "/p/home/jusers/levchenko1/jureca/.local/lib/python3.8/site-packages/datalad/ui/__init__.py", line 60, in __init__
    self.set_backend(backend)
  File "/p/home/jusers/levchenko1/jureca/.local/lib/python3.8/site-packages/datalad/ui/__init__.py", line 84, in set_backend
    backend = 'dialog' if is_interactive() else 'no-progress'
  File "/p/home/jusers/levchenko1/jureca/.local/lib/python3.8/site-packages/datalad/utils.py", line 296, in is_interactive
    return all(_is_stream_tty(s) for s in (sys.stdin, sys.stdout, sys.stderr))
  File "/p/home/jusers/levchenko1/jureca/.local/lib/python3.8/site-packages/datalad/utils.py", line 296, in <genexpr>
    return all(_is_stream_tty(s) for s in (sys.stdin, sys.stdout, sys.stderr))
  File "/p/home/jusers/levchenko1/jureca/.local/lib/python3.8/site-packages/datalad/utils.py", line 279, in _is_stream_tty
    return stream.isatty()
AttributeError: 'NoneType' object has no attribute 'isatty'

### What steps will reproduce the problem?

Dataset(path).push(to=ria_subdataset, jobs=32, force='checkdatapresent')

### Datalad information

version: 0.15.2

### Additional context

environment: JURECA worker node

**Comment by yarikoptic** [comment]
#6360 potentially provides a fix or workaround.  Curious if ` jobs=32` does "good" for you? ;) if over ssh, I found recently that serial was typically overperforming any parallelization in our case.  And `32` sounds like 'quite a bit'

**Comment by r-levchenko** [comment]
#6360 thx ! this will work

about "jobs=32" - yes,
in one step we add 29 files where each is 11GB,
After testing, we found out that for the optimal speed is achieved when the number of jobs slightly exceeds the number of files

**Comment by r-levchenko** [comment]
I noticed another similar crash:
AttributeError: 'NoneType' object has no attribute 'readline'

the error was fixed by updating the library: from annexremote-1.4.3 to annexremote-1.6.0
Maybe you want to add a minimum version check for AnnexRemote in DataLad.
PS: I do not understand the reasons for the error, since the same code has been successfully working for the last 2 months. I can only assume that something has changed in the system configuration recently.

stack:
2022-01-20 19:40:50,862 addzstack-no-verification ERROR    DataLadAction.isolationGit > DataLadAction.publishDataset / datalad.publish / path = /p/fastdata/bigbrains/pipeline/zstack-incoming/B31/0600_0699 : Unhandled exception : Traceback (most recent call last):
  File "/p/fastdata/bigbrains/pipeline/code/zstk_core/datalad_helper.py", line 43, in isolationGit
    res = func()
  File "/p/fastdata/bigbrains/pipeline/code/zstk_core/datalad_helper.py", line 323, in <lambda>
    if not TransactionState.isDone(DataLadAction.isolationGit(lambda: ds.push(to=env.CONSTANTS.ria_subdataset, jobs=jobs, force='checkdatapresent'),  # checkdatapresent - fix for This could have failed because --fast is enabled.
  File "/p/home/jusers/levchenko1/jureca/.local/lib/python3.8/site-packages/datalad/distribution/dataset.py", line 484, in apply_func
    return f(**kwargs)
  File "/p/home/jusers/levchenko1/jureca/.local/lib/python3.8/site-packages/datalad/interface/utils.py", line 483, in eval_func
    return return_func(generator_func)(*args, **kwargs)
  File "/p/home/jusers/levchenko1/jureca/.local/lib/python3.8/site-packages/datalad/interface/utils.py", line 476, in return_func
    results = list(results)
  File "/p/home/jusers/levchenko1/jureca/.local/lib/python3.8/site-packages/datalad/interface/utils.py", line 396, in generator_func
    for r in _process_results(
  File "/p/home/jusers/levchenko1/jureca/.local/lib/python3.8/site-packages/datalad/interface/utils.py", line 574, in _process_results
    for res in results:
  File "/p/home/jusers/levchenko1/jureca/.local/lib/python3.8/site-packages/datalad/core/distributed/push.py", line 259, in __call__
    yield from _push(
  File "/p/home/jusers/levchenko1/jureca/.local/lib/python3.8/site-packages/datalad/core/distributed/push.py", line 571, in _push
    yield from _push(
  File "/p/home/jusers/levchenko1/jureca/.local/lib/python3.8/site-packages/datalad/core/distributed/push.py", line 595, in _push
    yield from _push_data(
  File "/p/home/jusers/levchenko1/jureca/.local/lib/python3.8/site-packages/datalad/core/distributed/push.py", line 867, in _push_data
    res = ds_repo._call_annex_records(
  File "/p/home/jusers/levchenko1/jureca/.local/lib/python3.8/site-packages/datalad/support/annexrepo.py", line 1069, in _call_annex_records
    raise e
  File "/p/home/jusers/levchenko1/jureca/.local/lib/python3.8/site-packages/datalad/support/annexrepo.py", line 1021, in _call_annex_records
    out = self._call_annex(
  File "/p/home/jusers/levchenko1/jureca/.local/lib/python3.8/site-packages/datalad/support/annexrepo.py", line 924, in _call_annex
    return runner.run(
  File "/p/home/jusers/levchenko1/jureca/.local/lib/python3.8/site-packages/datalad/runner/runner.py", line 145, in run
    raise CommandError(
datalad.runner.exception.CommandError: CommandError: 'git -c diff.ignoreSubmodules=none annex copy --batch -z --to datastore-storage --jobs 32 --json --json-error-messages --json-progress -c annex.dotfiles=true' failed with exitcode 1 under /p/fastdata/bigbrains/pipeline/zstack-incoming/B31/0600_0699 [info keys: stdout_json]
> fd:149: hFlush: resource vanished (Broken pipe)
 [err: 'Traceback (most recent call last):
  File "/p/fastdata/bigbrains/software/miniconda3/bin/git-annex-remote-ora", line 8, in <module>
    main()
  File "/p/home/jusers/levchenko1/jureca/.local/lib/python3.8/site-packages/datalad/distributed/ora_remote.py", line 1415, in main
    master.Listen()
  File "/p/fastdata/bigbrains/software/miniconda3/lib/python3.8/site-packages/annexremote/annexremote.py", line 855, in Listen
    line = self.input.readline()
AttributeError: 'NoneType' object has no attribute 'readline'
copy: 1 failed']

**Comment by yarikoptic** [comment]
well, it seems to boil down to `input` somehow becoming `None` whenever it wasn't such before.

**Comment by adswa** [comment]
closed by #6360
