### ISSUE TITLE
Fresh git-annex: 1 fail, 1 error on datalad/git-annex

### ISSUE THREAD

**Issue by yarikoptic** [datalad/datalad#6369]
From 
```
  File "/opt/hostedtoolcache/Python/3.7.12/x64/lib/python3.7/site-packages/datalad/support/tests/test_annexrepo.py", line 1293, in test_repo_version
    eq_(version, v6_lands_on)
AssertionError: 10 != 8
```
smells like git-annex is now v10 (not v8) by default (didn't check in default) and our tests hardcode to 8 .

<details>
<summary>Details</summary> 

```shell
======================================================================
3731
ERROR: datalad.distribution.tests.test_create_sibling.test_target_ssh_simple
3732
----------------------------------------------------------------------
3733
Traceback (most recent call last):
3734
  File "/opt/hostedtoolcache/Python/3.7.12/x64/lib/python3.7/site-packages/nose/case.py", line 198, in runTest
3735
    self.test(*self.arg)
3736
  File "/opt/hostedtoolcache/Python/3.7.12/x64/lib/python3.7/site-packages/datalad/tests/utils.py", line 210, in _wrap_skip_if_on_windows
3737
    return func(*args, **kwargs)
3738
  File "/opt/hostedtoolcache/Python/3.7.12/x64/lib/python3.7/site-packages/datalad/tests/utils.py", line 284, in _wrap_skip_ssh
3739
    return func(*args, **kwargs)
3740
  File "/opt/hostedtoolcache/Python/3.7.12/x64/lib/python3.7/site-packages/datalad/tests/utils.py", line 1043, in _wrap_with_testrepos
3741
    t(*(arg + (uri,)), **kw)
3742
  File "/opt/hostedtoolcache/Python/3.7.12/x64/lib/python3.7/site-packages/datalad/tests/utils.py", line 742, in _wrap_with_tempfile
3743
    return t(*(arg + (filename,)), **kw)
3744
  File "/opt/hostedtoolcache/Python/3.7.12/x64/lib/python3.7/site-packages/datalad/tests/utils.py", line 742, in _wrap_with_tempfile
3745
    return t(*(arg + (filename,)), **kw)
3746
  File "/opt/hostedtoolcache/Python/3.7.12/x64/lib/python3.7/site-packages/datalad/distribution/tests/test_create_sibling.py", line 284, in test_target_ssh_simple
3747
    push(dataset=source, to="local_target")
3748
  File "/opt/hostedtoolcache/Python/3.7.12/x64/lib/python3.7/site-packages/datalad/interface/utils.py", line 484, in eval_func
3749
    return return_func(generator_func)(*args, **kwargs)
3750
  File "/opt/hostedtoolcache/Python/3.7.12/x64/lib/python3.7/site-packages/datalad/interface/utils.py", line 476, in return_func
3751
    results = list(results)
3752
  File "/opt/hostedtoolcache/Python/3.7.12/x64/lib/python3.7/site-packages/datalad/interface/utils.py", line 463, in generator_func
3753
    msg="Command did not complete successfully")
3754
datalad.support.exceptions.IncompleteResultsError: Command did not complete successfully. 1 failed:
3755
[{'action': 'publish',
3756
  'hints': None,
3757
  'message': 'refs/heads/dl-test-branch->local_target:refs/heads/dl-test-branch '
3758
             '[remote rejected] (Could not update working tree to new HEAD)',
3759
  'operations': ['remote-rejected', 'error'],
3760
  'path': '/tmp/datalad_temp_test_target_ssh_simple33yc7kwq',
3761
  'refds': '/tmp/datalad_temp_test_target_ssh_simple33yc7kwq',
3762
  'refspec': 'refs/heads/dl-test-branch:refs/heads/dl-test-branch',
3763
  'status': 'error',
3764
  'target': 'local_target',
3765
  'type': 'dataset'}]
3766
-------------------- >> begin captured logging << --------------------
3767
fasteners.process_lock: Level 5: Acquired file lock `b'/tmp/datalad_temp_8cpghpsf/.cache/datalad/sockets/dc75c924.lck'` after waiting 0.000s [1 attempts were required]
3768
fasteners.process_lock: Level 5: Unlocked and closed file lock open on `b'/tmp/datalad_temp_8cpghpsf/.cache/datalad/sockets/dc75c924.lck'`
3769
fasteners.process_lock: Level 5: Acquired file lock `b'/tmp/datalad_temp_8cpghpsf/.cache/datalad/sockets/dc75c924.lck'` after waiting 0.000s [1 attempts were required]
3770
fasteners.process_lock: Level 5: Unlocked and closed file lock open on `b'/tmp/datalad_temp_8cpghpsf/.cache/datalad/sockets/dc75c924.lck'`
3771
fasteners.process_lock: Level 5: Acquired file lock `b'/tmp/datalad_temp_8cpghpsf/.cache/datalad/sockets/dc75c924.lck'` after waiting 0.000s [1 attempts were required]
3772
fasteners.process_lock: Level 5: Unlocked and closed file lock open on `b'/tmp/datalad_temp_8cpghpsf/.cache/datalad/sockets/dc75c924.lck'`
3773
fasteners.process_lock: Level 5: Acquired file lock `b'/tmp/datalad_temp_8cpghpsf/.cache/datalad/sockets/dc75c924.lck'` after waiting 0.000s [1 attempts were required]
3774
fasteners.process_lock: Level 5: Unlocked and closed file lock open on `b'/tmp/datalad_temp_8cpghpsf/.cache/datalad/sockets/dc75c924.lck'`
3775
fasteners.process_lock: Level 5: Acquired file lock `b'/tmp/datalad_temp_8cpghpsf/.cache/datalad/sockets/dc75c924.lck'` after waiting 0.000s [1 attempts were required]
3776
fasteners.process_lock: Level 5: Unlocked and closed file lock open on `b'/tmp/datalad_temp_8cpghpsf/.cache/datalad/sockets/dc75c924.lck'`
3777
fasteners.process_lock: Level 5: Acquired file lock `b'/tmp/datalad_temp_8cpghpsf/.cache/datalad/sockets/dc75c924.lck'` after waiting 0.000s [1 attempts were required]
3778
fasteners.process_lock: Level 5: Unlocked and closed file lock open on `b'/tmp/datalad_temp_8cpghpsf/.cache/datalad/sockets/dc75c924.lck'`
3779
fasteners.process_lock: Level 5: Acquired file lock `b'/tmp/datalad_temp_8cpghpsf/.cache/datalad/sockets/dc75c924.lck'` after waiting 0.000s [1 attempts were required]
3780
fasteners.process_lock: Level 5: Unlocked and closed file lock open on `b'/tmp/datalad_temp_8cpghpsf/.cache/datalad/sockets/dc75c924.lck'`
3781
fasteners.process_lock: Level 5: Acquired file lock `b'/tmp/datalad_temp_8cpghpsf/.cache/datalad/sockets/dc75c924.lck'` after waiting 0.000s [1 attempts were required]
3782
fasteners.process_lock: Level 5: Unlocked and closed file lock open on `b'/tmp/datalad_temp_8cpghpsf/.cache/datalad/sockets/dc75c924.lck'`
3783
fasteners.process_lock: Level 5: Acquired file lock `b'/tmp/datalad_temp_8cpghpsf/.cache/datalad/sockets/dc75c924.lck'` after waiting 0.000s [1 attempts were required]
3784
fasteners.process_lock: Level 5: Unlocked and closed file lock open on `b'/tmp/datalad_temp_8cpghpsf/.cache/datalad/sockets/dc75c924.lck'`
3785
fasteners.process_lock: Level 5: Acquired file lock `b'/tmp/datalad_temp_8cpghpsf/.cache/datalad/sockets/dc75c924.lck'` after waiting 0.000s [1 attempts were required]
3786
fasteners.process_lock: Level 5: Unlocked and closed file lock open on `b'/tmp/datalad_temp_8cpghpsf/.cache/datalad/sockets/dc75c924.lck'`
3787
fasteners.process_lock: Level 5: Acquired file lock `b'/tmp/datalad_temp_8cpghpsf/.cache/datalad/sockets/dc75c924.lck'` after waiting 0.000s [1 attempts were required]
3788
fasteners.process_lock: Level 5: Unlocked and closed file lock open on `b'/tmp/datalad_temp_8cpghpsf/.cache/datalad/sockets/dc75c924.lck'`
3789
fasteners.process_lock: Level 5: Acquired file lock `b'/tmp/datalad_temp_8cpghpsf/.cache/datalad/sockets/d1eaf3a6.lck'` after waiting 0.000s [1 attempts were required]
3790
fasteners.process_lock: Level 5: Unlocked and closed file lock open on `b'/tmp/datalad_temp_8cpghpsf/.cache/datalad/sockets/d1eaf3a6.lck'`
3791
fasteners.process_lock: Level 5: Acquired file lock `b'/tmp/datalad_temp_8cpghpsf/.cache/datalad/sockets/d1eaf3a6.lck'` after waiting 0.000s [1 attempts were required]
3792
fasteners.process_lock: Level 5: Unlocked and closed file lock open on `b'/tmp/datalad_temp_8cpghpsf/.cache/datalad/sockets/d1eaf3a6.lck'`
3793
fasteners.process_lock: Level 5: Acquired file lock `b'/tmp/datalad_temp_8cpghpsf/.cache/datalad/sockets/d1eaf3a6.lck'` after waiting 0.000s [1 attempts were required]
3794
fasteners.process_lock: Level 5: Unlocked and closed file lock open on `b'/tmp/datalad_temp_8cpghpsf/.cache/datalad/sockets/d1eaf3a6.lck'`
3795
fasteners.process_lock: Level 5: Acquired file lock `b'/tmp/datalad_temp_8cpghpsf/.cache/datalad/sockets/d1eaf3a6.lck'` after waiting 0.000s [1 attempts were required]
3796
fasteners.process_lock: Level 5: Unlocked and closed file lock open on `b'/tmp/datalad_temp_8cpghpsf/.cache/datalad/sockets/d1eaf3a6.lck'`
3797
fasteners.process_lock: Level 5: Acquired file lock `b'/tmp/datalad_temp_8cpghpsf/.cache/datalad/sockets/d1eaf3a6.lck'` after waiting 0.000s [1 attempts were required]
3798
fasteners.process_lock: Level 5: Unlocked and closed file lock open on `b'/tmp/datalad_temp_8cpghpsf/.cache/datalad/sockets/d1eaf3a6.lck'`
3799
fasteners.process_lock: Level 5: Acquired file lock `b'/tmp/datalad_temp_8cpghpsf/.cache/datalad/sockets/d1eaf3a6.lck'` after waiting 0.000s [1 attempts were required]
3800
fasteners.process_lock: Level 5: Unlocked and closed file lock open on `b'/tmp/datalad_temp_8cpghpsf/.cache/datalad/sockets/d1eaf3a6.lck'`
3801
fasteners.process_lock: Level 5: Acquired file lock `b'/tmp/datalad_temp_8cpghpsf/.cache/datalad/sockets/d1eaf3a6.lck'` after waiting 0.000s [1 attempts were required]
3802
fasteners.process_lock: Level 5: Unlocked and closed file lock open on `b'/tmp/datalad_temp_8cpghpsf/.cache/datalad/sockets/d1eaf3a6.lck'`
3803
fasteners.process_lock: Level 5: Acquired file lock `b'/tmp/datalad_temp_8cpghpsf/.cache/datalad/sockets/d1eaf3a6.lck'` after waiting 0.000s [1 attempts were required]
3804
fasteners.process_lock: Level 5: Unlocked and closed file lock open on `b'/tmp/datalad_temp_8cpghpsf/.cache/datalad/sockets/d1eaf3a6.lck'`
3805
fasteners.process_lock: Level 5: Acquired file lock `b'/tmp/datalad_temp_8cpghpsf/.cache/datalad/sockets/d1eaf3a6.lck'` after waiting 0.000s [1 attempts were required]
3806
fasteners.process_lock: Level 5: Unlocked and closed file lock open on `b'/tmp/datalad_temp_8cpghpsf/.cache/datalad/sockets/d1eaf3a6.lck'`
3807
fasteners.process_lock: Level 5: Acquired file lock `b'/tmp/datalad_temp_8cpghpsf/.cache/datalad/sockets/d1eaf3a6.lck'` after waiting 0.000s [1 attempts were required]
3808
fasteners.process_lock: Level 5: Unlocked and closed file lock open on `b'/tmp/datalad_temp_8cpghpsf/.cache/datalad/sockets/d1eaf3a6.lck'`
3809
fasteners.process_lock: Level 5: Acquired file lock `b'/tmp/datalad_temp_8cpghpsf/.cache/datalad/sockets/d1eaf3a6.lck'` after waiting 0.000s [1 attempts were required]
3810
fasteners.process_lock: Level 5: Unlocked and closed file lock open on `b'/tmp/datalad_temp_8cpghpsf/.cache/datalad/sockets/d1eaf3a6.lck'`
3811
fasteners.process_lock: Level 5: Acquired file lock `b'/tmp/datalad_temp_8cpghpsf/.cache/datalad/sockets/d1eaf3a6.lck'` after waiting 0.000s [1 attempts were required]
3812
fasteners.process_lock: Level 5: Unlocked and closed file lock open on `b'/tmp/datalad_temp_8cpghpsf/.cache/datalad/sockets/d1eaf3a6.lck'`
3813
fasteners.process_lock: Level 5: Acquired file lock `b'/tmp/datalad_temp_8cpghpsf/.cache/datalad/sockets/d1eaf3a6.lck'` after waiting 0.000s [1 attempts were required]
3814
fasteners.process_lock: Level 5: Unlocked and closed file lock open on `b'/tmp/datalad_temp_8cpghpsf/.cache/datalad/sockets/d1eaf3a6.lck'`
3815
fasteners.process_lock: Level 5: Acquired file lock `b'/tmp/datalad_temp_8cpghpsf/.cache/datalad/sockets/d1eaf3a6.lck'` after waiting 0.000s [1 attempts were required]
3816
fasteners.process_lock: Level 5: Unlocked and closed file lock open on `b'/tmp/datalad_temp_8cpghpsf/.cache/datalad/sockets/d1eaf3a6.lck'`
3817
fasteners.process_lock: Level 5: Acquired file lock `b'/tmp/datalad_temp_8cpghpsf/.cache/datalad/sockets/d1eaf3a6.lck'` after waiting 0.000s [1 attempts were required]
3818
fasteners.process_lock: Level 5: Unlocked and closed file lock open on `b'/tmp/datalad_temp_8cpghpsf/.cache/datalad/sockets/d1eaf3a6.lck'`
3819
fasteners.process_lock: Level 5: Acquired file lock `b'/tmp/datalad_temp_8cpghpsf/.cache/datalad/sockets/d1eaf3a6.lck'` after waiting 0.000s [1 attempts were required]
3820
fasteners.process_lock: Level 5: Unlocked and closed file lock open on `b'/tmp/datalad_temp_8cpghpsf/.cache/datalad/sockets/d1eaf3a6.lck'`
3821
fasteners.process_lock: Level 5: Acquired file lock `b'/tmp/datalad_temp_8cpghpsf/.cache/datalad/sockets/d1eaf3a6.lck'` after waiting 0.000s [1 attempts were required]
3822
fasteners.process_lock: Level 5: Unlocked and closed file lock open on `b'/tmp/datalad_temp_8cpghpsf/.cache/datalad/sockets/d1eaf3a6.lck'`
3823
fasteners.process_lock: Level 5: Acquired file lock `b'/tmp/datalad_temp_8cpghpsf/.cache/datalad/sockets/d1eaf3a6.lck'` after waiting 0.000s [1 attempts were required]
3824
fasteners.process_lock: Level 5: Unlocked and closed file lock open on `b'/tmp/datalad_temp_8cpghpsf/.cache/datalad/sockets/d1eaf3a6.lck'`
3825
fasteners.process_lock: Level 5: Acquired file lock `b'/tmp/datalad_temp_8cpghpsf/.cache/datalad/sockets/d1eaf3a6.lck'` after waiting 0.000s [1 attempts were required]
3826
fasteners.process_lock: Level 5: Unlocked and closed file lock open on `b'/tmp/datalad_temp_8cpghpsf/.cache/datalad/sockets/d1eaf3a6.lck'`
3827
fasteners.process_lock: Level 5: Acquired file lock `b'/tmp/datalad_temp_8cpghpsf/.cache/datalad/sockets/d1eaf3a6.lck'` after waiting 0.000s [1 attempts were required]
3828
fasteners.process_lock: Level 5: Unlocked and closed file lock open on `b'/tmp/datalad_temp_8cpghpsf/.cache/datalad/sockets/d1eaf3a6.lck'`
3829
fasteners.process_lock: Level 5: Acquired file lock `b'/tmp/datalad_temp_8cpghpsf/.cache/datalad/sockets/d1eaf3a6.lck'` after waiting 0.000s [1 attempts were required]
3830
fasteners.process_lock: Level 5: Unlocked and closed file lock open on `b'/tmp/datalad_temp_8cpghpsf/.cache/datalad/sockets/d1eaf3a6.lck'`
3831
fasteners.process_lock: Level 5: Acquired file lock `b'/tmp/datalad_temp_8cpghpsf/.cache/datalad/sockets/d1eaf3a6.lck'` after waiting 0.000s [1 attempts were required]
3832
fasteners.process_lock: Level 5: Unlocked and closed file lock open on `b'/tmp/datalad_temp_8cpghpsf/.cache/datalad/sockets/d1eaf3a6.lck'`
3833
fasteners.process_lock: Level 5: Acquired file lock `b'/tmp/datalad_temp_8cpghpsf/.cache/datalad/sockets/d1eaf3a6.lck'` after waiting 0.000s [1 attempts were required]
3834
fasteners.process_lock: Level 5: Unlocked and closed file lock open on `b'/tmp/datalad_temp_8cpghpsf/.cache/datalad/sockets/d1eaf3a6.lck'`
3835
--------------------- >> end captured logging << ---------------------
3836

3837
======================================================================
3838
FAIL: datalad.support.tests.test_annexrepo.test_repo_version
3839
----------------------------------------------------------------------
3840
Traceback (most recent call last):
3841
  File "/opt/hostedtoolcache/Python/3.7.12/x64/lib/python3.7/site-packages/nose/case.py", line 198, in runTest
3842
    self.test(*self.arg)
3843
  File "/opt/hostedtoolcache/Python/3.7.12/x64/lib/python3.7/site-packages/datalad/tests/utils.py", line 742, in _wrap_with_tempfile
3844
    return t(*(arg + (filename,)), **kw)
3845
  File "/opt/hostedtoolcache/Python/3.7.12/x64/lib/python3.7/site-packages/datalad/tests/utils.py", line 742, in _wrap_with_tempfile
3846
    return t(*(arg + (filename,)), **kw)
3847
  File "/opt/hostedtoolcache/Python/3.7.12/x64/lib/python3.7/site-packages/datalad/tests/utils.py", line 742, in _wrap_with_tempfile
3848
    return t(*(arg + (filename,)), **kw)
3849
  File "/opt/hostedtoolcache/Python/3.7.12/x64/lib/python3.7/site-packages/datalad/support/tests/test_annexrepo.py", line 1293, in test_repo_version
3850
    eq_(version, v6_lands_on)
3851
AssertionError: 10 != 8
3852
-------------------- >> begin captured logging << --------------------
3853
datalad.annex: INFO: Annex repository version 6 will be upgraded to 8
3854
--------------------- >> end captured logging << ---------------------
3855

3856
----------------------------------------------------------------------
3857
Ran 1301 tests in 4373.574s
3858

3859
FAILED (SKIP=92, errors=1, fai...
```
</details>

<details>
<summary>seems to be consistent across platforms/datalad "versions"</summary> 

```shell
(git)smaug:/mnt/datasets/datalad/ci/git-annex/builds/2022/01[master]cron-20220124
$> git grep errors= 
build-ubuntu.yaml-553-85dd9355-failed/1_test-datalad (master).txt:2022-01-24T04:05:29.6285481Z FAILED (SKIP=81, errors=1, failures=1)
build-ubuntu.yaml-553-85dd9355-failed/2_test-datalad (maint).txt:2022-01-24T04:09:44.9799089Z FAILED (SKIP=92, errors=1, failures=1)
build-ubuntu.yaml-553-85dd9355-failed/3_test-datalad (release).txt:2022-01-24T04:13:21.2198843Z FAILED (SKIP=92, errors=1, failures=1)
build-ubuntu.yaml-553-85dd9355-failed/test-datalad (maint)/14_Run datalad tests.txt:2022-01-24T04:09:44.9799085Z FAILED (SKIP=92, errors=1, failures=1)
build-ubuntu.yaml-553-85dd9355-failed/test-datalad (master)/14_Run datalad tests.txt:2022-01-24T04:05:29.6285478Z FAILED (SKIP=81, errors=1, failures=1)
build-ubuntu.yaml-553-85dd9355-failed/test-datalad (release)/14_Run datalad tests.txt:2022-01-24T04:13:21.2198839Z FAILED (SKIP=92, errors=1, failures=1)

$> git grep '\(FAIL\|ERROR\): datalad.*'                 
build-macos.yaml-567-85dd9355-failed/1_test-datalad (master).txt:2022-01-24T03:44:03.7041390Z FAIL: datalad.support.tests.test_annexrepo.test_repo_version
build-macos.yaml-567-85dd9355-failed/2_test-datalad (maint).txt:2022-01-24T03:45:33.5707250Z FAIL: datalad.support.tests.test_annexrepo.test_repo_version
build-macos.yaml-567-85dd9355-failed/3_test-datalad (release).txt:2022-01-24T04:05:07.6982370Z FAIL: datalad.support.tests.test_annexrepo.test_repo_version
build-macos.yaml-567-85dd9355-failed/test-datalad (maint)/11_Run datalad tests.txt:2022-01-24T03:45:33.5707240Z FAIL: datalad.support.tests.test_annexrepo.test_repo_version
build-macos.yaml-567-85dd9355-failed/test-datalad (master)/11_Run datalad tests.txt:2022-01-24T03:44:03.7041380Z FAIL: datalad.support.tests.test_annexrepo.test_repo_version
build-macos.yaml-567-85dd9355-failed/test-datalad (release)/11_Run datalad tests.txt:2022-01-24T04:05:07.6982370Z FAIL: datalad.support.tests.test_annexrepo.test_repo_version
build-ubuntu.yaml-553-85dd9355-failed/1_test-datalad (master).txt:2022-01-24T04:05:29.6153900Z ERROR: datalad.distribution.tests.test_create_sibling.test_target_ssh_simple
build-ubuntu.yaml-553-85dd9355-failed/1_test-datalad (master).txt:2022-01-24T04:05:29.6276058Z FAIL: datalad.support.tests.test_annexrepo.test_repo_version
build-ubuntu.yaml-553-85dd9355-failed/2_test-datalad (maint).txt:2022-01-24T04:09:44.9636030Z ERROR: datalad.distribution.tests.test_create_sibling.test_target_ssh_simple
build-ubuntu.yaml-553-85dd9355-failed/2_test-datalad (maint).txt:2022-01-24T04:09:44.9716514Z FAIL: datalad.support.tests.test_annexrepo.test_repo_version
build-ubuntu.yaml-553-85dd9355-failed/3_test-datalad (release).txt:2022-01-24T04:13:21.1975240Z ERROR: datalad.distribution.tests.test_create_sibling.test_target_ssh_simple
build-ubuntu.yaml-553-85dd9355-failed/3_test-datalad (release).txt:2022-01-24T04:13:21.2189273Z FAIL: datalad.support.tests.test_annexrepo.test_repo_version
build-ubuntu.yaml-553-85dd9355-failed/test-datalad (maint)/14_Run datalad tests.txt:2022-01-24T04:09:44.9636023Z ERROR: datalad.distribution.tests.test_create_sibling.test_target_ssh_simple
build-ubuntu.yaml-553-85dd9355-failed/test-datalad (maint)/14_Run datalad tests.txt:2022-01-24T04:09:44.9716509Z FAIL: datalad.support.tests.test_annexrepo.test_repo_version
build-ubuntu.yaml-553-85dd9355-failed/test-datalad (master)/14_Run datalad tests.txt:2022-01-24T04:05:29.6153893Z ERROR: datalad.distribution.tests.test_create_sibling.test_target_ssh_simple
build-ubuntu.yaml-553-85dd9355-failed/test-datalad (master)/14_Run datalad tests.txt:2022-01-24T04:05:29.6276055Z FAIL: datalad.support.tests.test_annexrepo.test_repo_version
build-ubuntu.yaml-553-85dd9355-failed/test-datalad (release)/14_Run datalad tests.txt:2022-01-24T04:13:21.1975233Z ERROR: datalad.distribution.tests.test_create_sibling.test_target_ssh_simple
build-ubuntu.yaml-553-85dd9355-failed/test-datalad (release)/14_Run datalad tests.txt:2022-01-24T04:13:21.2189269Z FAIL: datalad.support.tests.test_annexrepo.test_repo_version
build-windows.yaml-520-85dd9355-failed/1_test-datalad (master).txt:2022-01-24T05:57:03.0392223Z FAIL: datalad.support.tests.test_annexrepo.test_repo_version
build-windows.yaml-520-85dd9355-failed/2_test-datalad (maint).txt:2022-01-24T05:48:08.4140763Z FAIL: datalad.support.tests.test_annexrepo.test_repo_version
build-windows.yaml-520-85dd9355-failed/3_test-datalad (release).txt:2022-01-24T05:49:40.8215190Z FAIL: datalad.support.tests.test_annexrepo.test_repo_version
build-windows.yaml-520-85dd9355-failed/test-datalad (maint)/21_Run datalad tests.txt:2022-01-24T05:48:08.4140758Z FAIL: datalad.support.tests.test_annexrepo.test_repo_version
build-windows.yaml-520-85dd9355-failed/test-datalad (master)/21_Run datalad tests.txt:2022-01-24T05:57:03.0392216Z FAIL: datalad.support.tests.test_annexrepo.test_repo_version
build-windows.yaml-520-85dd9355-failed/test-datalad (release)/21_Run datalad tests.txt:2022-01-24T05:49:40.8215186Z FAIL: datalad.support.tests.test_annexrepo.test_repo_version

```

</details>

both  started to fail/error on cron-20220122 .

on version upgrade to 10 -- asking @joeyh [here](https://git-annex.branchable.com/bugs/init__58___autoupgrade___60__8_annex_version_to_8_not_10/?updated)

**Comment by yarikoptic** [comment]
<details>
<summary>heh, unfortunately I am failing to reproduce `test_target_ssh_simple` locally after git-annex upgrade
</summary> 

```
(git)lena:~datalad/datalad-maint[maint]
$> DATALAD_TESTS_SSH=1 python -m nose -s -v --pdb datalad/distribution/tests/test_create_sibling.py:test_target_ssh_simple
datalad.distribution.tests.test_create_sibling.test_target_ssh_simple ... ok
Versions: annexremote=1.5.0 appdirs=1.4.4 boto=2.49.0 cmd:7z=16.02 cmd:annex=8.20211231+git126-gf7a3c1355-1~ndall+1 cmd:bundled-git=2.30.2 cmd:git=2.30.2 cmd:system-git=2.34.1 cmd:system-ssh=8.7p1 exifread=2.3.2 humanize=3.13.1 iso8601=1.0.2 keyring=23.5.0 keyrings.alt=UNKNOWN msgpack=1.0.3 mutagen=1.45.1 requests=2.27.0 wrapt=1.13.3
Obscure filename: str=b' |;&%b5{}\'"\xce\x94\xd0\x99\xd7\xa7\xd9\x85\xe0\xb9\x97\xe3\x81\x82 .datc ' repr=' |;&%b5{}\'"ΔЙקم๗あ .datc '
Encodings: default='utf-8' filesystem='utf-8' locale.prefered='UTF-8'
Environment: PATH='/home/yoh/proj/datalad/datalad-maint/venvs/dev3/bin:/home/yoh/gocode/bin:/home/yoh/gocode/bin:/home/yoh/bin:/home/yoh/.local/bin:/usr/local/bin:/usr/bin:/bin:/usr/local/games:/usr/games:/sbin:/usr/sbin:/usr/local/sbin' LANG='en_US.UTF-8' GIT_PAGER='less --no-init --quit-if-one-screen' GIT_CONFIG_PARAMETERS="'init.defaultBranch=dl-test-branch' 'clone.defaultRemoteName=dl-test-remote'"

----------------------------------------------------------------------
Ran 1 test in 29.455s

OK
```

</details>

so might be tricky to troubleshoot why we are getting `[remote rejected] (Could not update working tree to new HEAD)` on github actions :-/

**Comment by joeyh** [comment]
Repositories are still v8 by default but this is going to change to v9/v10,
and the git-annex version number will be 10.x in the next release.

-- 
see shy jo

**Comment by yarikoptic** [comment]
@joeyh :

> Repositories are still v8 by default but this is going to change to v9/v10

FWIW: I quite often got "discomforted" by inability to access git-annex repos using older version of git-annex (e.g. which I have inside or outside of a container) whenever repo had already a newer one (again by using newer git-annex one way or another on that box). I wonder if there should be some period of time/git-annex releases still stick to the previous "default" version?  That would allow for proliferation of newer versions of git-annex tool (which would support newer version of annex) through deployments, thus making it more likely for the git-annex tool to "understand" newer version of the repo whenever migrations do happen.

**Comment by yarikoptic** [comment]
we are green on https://github.com/datalad/git-annex -- I believe the issue was resolved on git-annex side.
