### ISSUE TITLE
CLI API RF broke extension(s) CLI

### ISSUE THREAD

**Issue by yarikoptic** [datalad/datalad#6406]
Just spotted on datalad-neuroimaging:

```shell
$> time datalad containers-run --help-np 1>/dev/null
Traceback (most recent call last):
  File "/home/yoh/proj/datalad/datalad-maint/venvs/dev3/bin/datalad", line 33, in <module>
    sys.exit(load_entry_point('datalad', 'console_scripts', 'datalad')())
  File "/home/yoh/proj/datalad/datalad-maint/venvs/dev3/bin/datalad", line 25, in importlib_load_entry_point
    return next(matches).load()
  File "/usr/lib/python3.9/importlib/metadata.py", line 77, in load
    module = import_module(match.group('module'))
  File "/usr/lib/python3.9/importlib/__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1030, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1007, in _find_and_load
  File "<frozen importlib._bootstrap>", line 984, in _find_and_load_unlocked
ModuleNotFoundError: No module named 'datalad.cmdline.main'
datalad containers-run --help-np > /dev/null  0.14s user 0.03s system 87% cpu 0.193 total
```

all is as good as before on https://github.com/datalad/datalad-extensions/ (only some red for xnat) so I guess we do not test that in extensions

**Comment by yarikoptic** [comment]
disregard, seems some fluke in installation etc.  Reinstalled in venv and problem is gone
