### ISSUE TITLE
test_gitcredential* tests are failing in datalad/git-annex

### ISSUE THREAD

**Issue by yarikoptic** [datalad/datalad#6442]
see eg https://github.com/datalad/git-annex/runs/5135259987?check_suite_focus=true

<details>
<summary>cut/paste of 3 tests</summary> 

```
======================================================================
ERROR: datalad.local.tests.test_gitcredential.test_credential_cycle
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/opt/hostedtoolcache/Python/3.7.12/x64/lib/python3.7/site-packages/nose/case.py", line 198, in runTest
    self.test(*self.arg)
  File "/opt/hostedtoolcache/Python/3.7.12/x64/lib/python3.7/site-packages/datalad/tests/utils.py", line 874, in _wrap_with_tempfile
    return t(*(arg + (filename,)), **kw)
  File "/opt/hostedtoolcache/Python/3.7.12/x64/lib/python3.7/site-packages/datalad/local/tests/test_gitcredential.py", line 191, in test_credential_cycle
    gitcred.fill()
  File "/opt/hostedtoolcache/Python/3.7.12/x64/lib/python3.7/site-packages/datalad/local/gitcredential.py", line 140, in fill
    stdin=self._format_props()
  File "/opt/hostedtoolcache/Python/3.7.12/x64/lib/python3.7/site-packages/datalad/runner/runner.py", line 205, in run
    **results,
datalad.runner.exception.CommandError: CommandError: 'git credential fill' failed with exitcode 128 under /tmp/datalad_temp_test_credential_cycleyew2otwj [err: 'Traceback (most recent call last):
install(ok): /tmp/datalad_temp_test_cached_datasetov9i6wci/https___github.com_datalad_testrepo--minimalds (dataset)
install(ok): /tmp/datalad_temp__wrap_cached_datasetl8514v2c (dataset)
.: here(+) [git]
.: dl-test-remote(+) [/tmp/datalad_temp_test_cached_datasetov9i6wci/https___github.com_datalad_testrepo--minimalds (git)]
install(ok): /tmp/datalad_temp__wrap_cached_datasetbidrf4xk (dataset)
get(ok): inannex/animated.gif (file) [from dl-test-remote...]
.: here(+) [git]
.: dl-test-remote(+) [/tmp/datalad_temp_test_cached_datasetov9i6wci/https___github.com_datalad_testrepo--minimalds (git)]
install(ok): /tmp/datalad_temp__wrap_cached_datasettqyzt07z (dataset)
.: here(+) [git]
.: dl-test-remote(+) [/tmp/datalad_temp_test_cached_datasetov9i6wci/https___github.com_datalad_testrepo--minimalds (git)]
install(ok): /tmp/datalad_temp__wrap_cached_datasetss6_ot7o (dataset)
.: here(+) [git]
.: dl-test-remote(+) [/tmp/datalad_temp_test_cached_datasetov9i6wci/https___github.com_datalad_testrepo--minimalds (git)]
install(ok): /tmp/datalad_temp_test_cached_url1ymd5w1i/https___github.com_datalad_testrepo--minimalds (dataset)
install(ok): /tmp/datalad_temp_test_get_cached_dataset9_orbmhw/https___github.com_datalad_testrepo--minimalds (dataset)
install(ok): /tmp/datalad_temp_test_get_cached_dataset9_orbmhw/https___github.com_datalad_datalad.org (dataset)
Versions: annexremote=1.5.0 boto=2.49.0 cmd:7z=16.02 cmd:annex=10.20220127+git41-gc90804623-1~ndall+1 cmd:bundled-git=2.30.2 cmd:git=2.30.2 cmd:system-git=2.35.1 cmd:system-ssh=8.2p1 humanize=3.14.0 iso8601=1.0.2 keyring=23.5.0 keyrings.alt=UNKNOWN msgpack=1.0.3 patoolib=1.12 platformdirs=2.5.0 requests=2.27.1 tqdm=4.62.3
Obscure filename: str=b' |;&%b5{}\'"\xce\x94\xd0\x99\xd7\xa7\xd9\x85\xe0\xb9\x97\xe3\x81\x82 .datc ' repr=' |;&%b5{}\'"ΔЙקم๗あ .datc '
Encodings: default='utf-8' filesystem='utf-8' locale.prefered='UTF-8'
Environment: LANG='C' PATH='/opt/hostedtoolcache/Python/3.7.12/x64/bin:/opt/hostedtoolcache/Python/3.7.12/x64:/home/linuxbrew/.linuxbrew/bin:/home/linuxbrew/.linuxbrew/sbin:/home/runner/.local/bin:/opt/pipx_bin:/home/runner/.cargo/bin:/home/runner/.config/composer/vendor/bin:/usr/local/.ghcup/bin:/home/runner/.dotnet/tools:/snap/bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/usr/games:/usr/local/games:/snap/bin' LC_CTYPE='C.UTF-8' GIT_CONFIG_PARAMETERS="'init.defaultBranch=dl-test-branch' 'clone.defaultRemoteName=dl-test-remote'"
  File "/opt/hostedtoolcache/Python/3.7.12/x64/bin/git-credential-datalad", line 8, in <module>
    sys.exit(git_credential_datalad())
  File "/opt/hostedtoolcache/Python/3.7.12/x64/lib/python3.7/site-packages/datalad/local/gitcredential_datalad.py", line 87, in git_credential_datalad
    _action_get(attrs, providers)
  File "/opt/hostedtoolcache/Python/3.7.12/x64/lib/python3.7/site-packages/datalad/local/gitcredential_datalad.py", line 175, in _action_get
    dlcred = UserPassword()
TypeError: __init__() missing 1 required positional argument: 'name'
fatal: could not read Username for 'https://some.data.exampe.com/': No such device or address']

======================================================================
ERROR: datalad.local.tests.test_gitcredential.test_datalad_credential_helper
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/opt/hostedtoolcache/Python/3.7.12/x64/lib/python3.7/site-packages/nose/case.py", line 198, in runTest
    self.test(*self.arg)
  File "/opt/hostedtoolcache/Python/3.7.12/x64/lib/python3.7/site-packages/datalad/tests/utils.py", line 874, in _wrap_with_tempfile
    return t(*(arg + (filename,)), **kw)
  File "/opt/hostedtoolcache/Python/3.7.12/x64/lib/python3.7/site-packages/datalad/local/tests/test_gitcredential.py", line 97, in test_datalad_credential_helper
    gitcred.fill()
  File "/opt/hostedtoolcache/Python/3.7.12/x64/lib/python3.7/site-packages/datalad/local/gitcredential.py", line 140, in fill
    stdin=self._format_props()
  File "/opt/hostedtoolcache/Python/3.7.12/x64/lib/python3.7/site-packages/datalad/runner/runner.py", line 205, in run
    **results,
datalad.runner.exception.CommandError: CommandError: 'git credential fill' failed with exitcode 128 under /tmp/datalad_temp_test_datalad_credential_helpersplt4o2c [err: 'Traceback (most recent call last):
  File "/opt/hostedtoolcache/Python/3.7.12/x64/bin/git-credential-datalad", line 8, in <module>
    sys.exit(git_credential_datalad())
  File "/opt/hostedtoolcache/Python/3.7.12/x64/lib/python3.7/site-packages/datalad/local/gitcredential_datalad.py", line 87, in git_credential_datalad
    _action_get(attrs, providers)
  File "/opt/hostedtoolcache/Python/3.7.12/x64/lib/python3.7/site-packages/datalad/local/gitcredential_datalad.py", line 175, in _action_get
    dlcred = UserPassword()
TypeError: __init__() missing 1 required positional argument: 'name'
fatal: could not read Username for 'https://datalad-test.org/': No such device or address']

======================================================================
ERROR: datalad.local.tests.test_gitcredential.test_gitcredential_interface
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/opt/hostedtoolcache/Python/3.7.12/x64/lib/python3.7/site-packages/nose/case.py", line 198, in runTest
    self.test(*self.arg)
  File "/opt/hostedtoolcache/Python/3.7.12/x64/lib/python3.7/site-packages/datalad/tests/utils.py", line 874, in _wrap_with_tempfile
    return t(*(arg + (filename,)), **kw)
  File "/opt/hostedtoolcache/Python/3.7.12/x64/lib/python3.7/site-packages/datalad/local/tests/test_gitcredential.py", line 68, in test_gitcredential_interface
    cred.fill()
  File "/opt/hostedtoolcache/Python/3.7.12/x64/lib/python3.7/site-packages/datalad/local/gitcredential.py", line 140, in fill
    stdin=self._format_props()
  File "/opt/hostedtoolcache/Python/3.7.12/x64/lib/python3.7/site-packages/datalad/runner/runner.py", line 205, in run
    **results,
datalad.runner.exception.CommandError: CommandError: 'git credential fill' failed with exitcode 128 under /tmp/datalad_temp_test_gitcredential_interface2_40ghom [err: 'fatal: could not read Username for 'https://example.datalad.org/': No such device or address']

----------------------------------------------------------------------
Ran 1365 tests in 4629.975s

FAILED (SKIP=78, errors=3)
```
</details>

marking important since it masks other potentially important fails within datalad/git-annex testing which was green for a blessed week ;)

**Comment by bpoldrack** [comment]
@yarikoptic : The CI environment needs `GIT_ASKPASS=true` and/or `git config --global core.askpass ""` (depends on git version which one is respected).
