### ISSUE TITLE
external special remote protocol error, unexpectedly received "<EOF>" (unable to parse command)

### ISSUE THREAD

**Issue by mih** [datalad/datalad#6453]
On 158859e7b37d827bddc14b869438b77c1ba6e161

```
% git -C hcp/HCP1200/193441/ annex whereis .xdlm/193441_3T_Diffusion_unproc.json
whereis .xdlm/193441_3T_Diffusion_unproc.json Traceback (most recent call last):
  File "/home/mih/venvs/datalad/bin/git-annex-remote-datalad", line 33, in <module>
    sys.exit(load_entry_point('datalad', 'console_scripts', 'git-annex-remote-datalad')())
  File "/home/mih/code/datalad/datalad/customremotes/datalad.py", line 121, in main
    master.Listen()
  File "/home/mih/venvs/datalad/lib/python3.7/site-packages/annexremote/annexremote.py", line 413, in Listen
    reply = self.protocol.command(line)
  File "/home/mih/venvs/datalad/lib/python3.7/site-packages/annexremote/annexremote.py", line 168, in command
    reply = method(parts[1])
  File "/home/mih/venvs/datalad/lib/python3.7/site-packages/annexremote/annexremote.py", line 305, in do_WHEREIS
    reply = self.remote.whereis(key)
  File "/home/mih/code/datalad/datalad/customremotes/base.py", line 95, in whereis
    raise RemoteError()
annexremote.annexremote.RemoteError

  external special remote protocol error, unexpectedly received "<EOF>" (unable to parse command)

  unable to query remote datalad for urls: unable to use special remote due to protocol error
(1 copy) 
        cf781544-dd72-449d-817c-85e061d18061 -- [datalad]

  datalad: s3://hcp-openaccess/HCP_1200/193441/.xdlm/193441_3T_Diffusion_unproc.json?versionId=bHvP1.g.Qi7nb7znIlWxBNGG5Jn_kK8F
ok
```

**Comment by adswa** [comment]
I see this on ``maint`` as well.
However, I can't get an error as verbose as yours, what did you configure to get the traceback? On the same commit as you, I see:

```
❱ git -C human-connectome-project-openaccess/HCP1200/193441/ annex whereis .xdlm/193441_3T_Diffusion_unproc.json  
whereis .xdlm/193441_3T_Diffusion_unproc.json 
  unable to query remote datalad for urls: external special remote error: 
(1 copy) 
  	cf781544-dd72-449d-817c-85e061d18061 -- [datalad]

  datalad: s3://hcp-openaccess/HCP_1200/193441/.xdlm/193441_3T_Diffusion_unproc.json?versionId=bHvP1.g.Qi7nb7znIlWxBNGG5Jn_kK8F
ok
```

**Comment by adswa** [comment]
Maybe a too naive guess, but I think we are responsible for the remote error because we raise it ourselves?

https://github.com/datalad/datalad/blob/158859e7b37d827bddc14b869438b77c1ba6e161/datalad/customremotes/base.py#L92-L95

**Comment by mih** [comment]
Ok, we must not release with this issue present. Scary that noone saw it.

**Comment by yarikoptic** [comment]
might be even worth doing (or CPing) into `maint` as well since present in `maint`

**Comment by yarikoptic** [comment]
oddly I don't observe it on `maint`:

```shell
(git)lena:/tmp/hcp-openaccess[master]git
$> git -C HCP1200/193441/ annex whereis .xdlm/193441_3T_Diffusion_unproc.json
whereis .xdlm/193441_3T_Diffusion_unproc.json (1 copy) 
  	cf781544-dd72-449d-817c-85e061d18061 -- [datalad]

  datalad: s3://hcp-openaccess/HCP_1200/193441/.xdlm/193441_3T_Diffusion_unproc.json?versionId=bHvP1.g.Qi7nb7znIlWxBNGG5Jn_kK8F
ok

$> git-annex-remote-datalad --version
datalad 0.15.5+1.g6e96447d1
```

and confirming on `master`:
```
$> git -C HCP1200/193441/ annex whereis .xdlm/193441_3T_Diffusion_unproc.json
whereis .xdlm/193441_3T_Diffusion_unproc.json 
  unable to query remote datalad for urls: external special remote error: 
(1 copy) 
  	cf781544-dd72-449d-817c-85e061d18061 -- [datalad]

  datalad: s3://hcp-openaccess/HCP_1200/193441/.xdlm/193441_3T_Diffusion_unproc.json?versionId=bHvP1.g.Qi7nb7znIlWxBNGG5Jn_kK8F
ok

$> datalad --version
datalad 0.15.5+701.gf852dfe53
```
filed related  https://github.com/datalad/datalad/issues/6460

**Comment by adswa** [comment]
ah my bad, I was in the wrong venv when I tried it :facepalm:

**Comment by mih** [comment]
Interestingly, my original error report is more informative than those of @yarikoptic and @adswa. Even more interestingly, I get the same uninformative report on my laptop...
