### ISSUE TITLE
4 (maint)/6 (master) test fails with super fresh (3 days old) git-annex

### ISSUE THREAD

**Issue by yarikoptic** [datalad/datalad#6492]
https://github.com/datalad/git-annex/runs/5292823639?check_suite_focus=true

```
======================================================================
FAIL: datalad.core.local.tests.test_save.test_partial_unlocked
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/opt/hostedtoolcache/Python/3.7.12/x64/lib/python3.7/site-packages/nose/case.py", line 198, in runTest
    self.test(*self.arg)
  File "/opt/hostedtoolcache/Python/3.7.12/x64/lib/python3.7/site-packages/datalad/tests/utils.py", line 742, in _wrap_with_tempfile
    return t(*(arg + (filename,)), **kw)
  File "/opt/hostedtoolcache/Python/3.7.12/x64/lib/python3.7/site-packages/datalad/core/local/tests/test_save.py", line 648, in test_partial_unlocked
    assert_repo_status(ds.path)
  File "/opt/hostedtoolcache/Python/3.7.12/x64/lib/python3.7/site-packages/datalad/tests/utils.py", line 1624, in assert_repo_status
    % (state, state_files, oktobefound))
AssertionError: unexpected content of state "modified": [PosixPath('/tmp/datalad_temp_test_partial_unlockedgjlcmggh/culprit.txt')] != []

======================================================================
FAIL: datalad.core.local.tests.test_status.test_status_symlinked_dir_within_repo
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/opt/hostedtoolcache/Python/3.7.12/x64/lib/python3.7/site-packages/nose/case.py", line 198, in runTest
    self.test(*self.arg)
  File "/opt/hostedtoolcache/Python/3.7.12/x64/lib/python3.7/site-packages/datalad/tests/utils.py", line 742, in _wrap_with_tempfile
    return t(*(arg + (filename,)), **kw)
  File "/opt/hostedtoolcache/Python/3.7.12/x64/lib/python3.7/site-packages/datalad/core/local/tests/test_status.py", line 302, in test_status_symlinked_dir_within_repo
    call()
AssertionError: CommandError not raised

======================================================================
FAIL: datalad.local.tests.test_addurls.TestAddurls.test_addurls_metafail
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/opt/hostedtoolcache/Python/3.7.12/x64/lib/python3.7/site-packages/nose/case.py", line 198, in runTest
    self.test(*self.arg)
  File "/opt/hostedtoolcache/Python/3.7.12/x64/lib/python3.7/site-packages/datalad/tests/utils.py", line 742, in _wrap_with_tempfile
    return t(*(arg + (filename,)), **kw)
  File "/opt/hostedtoolcache/Python/3.7.12/x64/lib/python3.7/site-packages/datalad/local/tests/test_addurls.py", line 763, in test_addurls_metafail
    result_renderer=None)
AssertionError: IncompleteResultsError not raised

======================================================================
FAIL: datalad.support.tests.test_annexrepo.test_annexjson_protocol
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/opt/hostedtoolcache/Python/3.7.12/x64/lib/python3.7/site-packages/nose/case.py", line 198, in runTest
    self.test(*self.arg)
  File "/opt/hostedtoolcache/Python/3.7.12/x64/lib/python3.7/site-packages/datalad/tests/utils.py", line 563, in _wrap_with_tree
    return t(*(arg + (d,)), **kw)
  File "/opt/hostedtoolcache/Python/3.7.12/x64/lib/python3.7/site-packages/datalad/support/tests/test_annexrepo.py", line 2197, in test_annexjson_protocol
    protocol=AnnexJsonProtocol)
AssertionError: CommandError not raised

----------------------------------------------------------------------
Ran 1300 tests in [3767](https://github.com/datalad/git-annex/runs/5292823639?check_suite_focus=true#step:14:3767).414s

FAILED (SKIP=93, failures=4)
Error: Process completed with exit code 1.
```

<details>
<summary>and master got 6 failing</summary> 

```shell
======================================================================
35329
FAIL: datalad.core.local.tests.test_save.test_partial_unlocked
35330
----------------------------------------------------------------------
35331
Traceback (most recent call last):
35332
  File "/opt/hostedtoolcache/Python/3.7.12/x64/lib/python3.7/site-packages/nose/case.py", line 198, in runTest
35333
    self.test(*self.arg)
35334
  File "/opt/hostedtoolcache/Python/3.7.12/x64/lib/python3.7/site-packages/datalad/tests/utils.py", line 874, in _wrap_with_tempfile
35335
    return t(*(arg + (filename,)), **kw)
35336
  File "/opt/hostedtoolcache/Python/3.7.12/x64/lib/python3.7/site-packages/datalad/core/local/tests/test_save.py", line 650, in test_partial_unlocked
35337
    assert_repo_status(ds.path)
35338
  File "/opt/hostedtoolcache/Python/3.7.12/x64/lib/python3.7/site-packages/datalad/tests/utils.py", line 1738, in assert_repo_status
35339
    % (state, state_files, oktobefound))
35340
AssertionError: unexpected content of state "modified": [PosixPath('/tmp/datalad_temp_test_partial_unlockedp49cit1q/culprit.txt')] != []
35341

35342
======================================================================
35343
FAIL: datalad.core.local.tests.test_status.test_status_symlinked_dir_within_repo
35344
----------------------------------------------------------------------
35345
Traceback (most recent call last):
35346
  File "/opt/hostedtoolcache/Python/3.7.12/x64/lib/python3.7/site-packages/nose/case.py", line 198, in runTest
35347
    self.test(*self.arg)
35348
  File "/opt/hostedtoolcache/Python/3.7.12/x64/lib/python3.7/site-packages/datalad/tests/utils.py", line 874, in _wrap_with_tempfile
35349
    return t(*(arg + (filename,)), **kw)
35350
  File "/opt/hostedtoolcache/Python/3.7.12/x64/lib/python3.7/site-packages/datalad/core/local/tests/test_status.py", line 311, in test_status_symlinked_dir_within_repo
35401
----------------------------------------------------------------------
35402
Traceback (most recent call last):
35403
  File "/opt/hostedtoolcache/Python/3.7.12/x64/lib/python3.7/site-packages/nose/case.py", line 198, in runTest
35404
    self.test(*self.arg)
35405
  File "/opt/hostedtoolcache/Python/3.7.12/x64/lib/python3.7/site-packages/datalad/tests/utils.py", line 874, in _wrap_with_tempfile
35406
    return t(*(arg + (filename,)), **kw)
35407
  File "/opt/hostedtoolcache/Python/3.7.12/x64/lib/python3.7/site-packages/datalad/local/tests/test_addurls.py", line 774, in test_addurls_metafail
35408
    result_renderer='disabled')
35409
AssertionError: IncompleteResultsError not raised
35410

35411
======================================================================
35412
FAIL: datalad.support.tests.test_annexrepo.test_annexjson_protocol
35413
----------------------------------------------------------------------
35414
Traceback (most recent call last):
35415
  File "/opt/hostedtoolcache/Python/3.7.12/x64/lib/python3.7/site-packages/nose/case.py", line 198, in runTest
35416
    self.test(*self.arg)
35417
  File "/opt/hostedtoolcache/Python/3.7.12/x64/lib/python3.7/site-packages/datalad/tests/utils.py", line 579, in _wrap_with_tree
35418
    return t(*(arg + (d,)), **kw)
35419
  File "/opt/hostedtoolcache/Python/3.7.12/x64/lib/python3.7/site-packages/datalad/support/tests/test_annexrepo.py", line 2185, in test_annexjson_protocol
35420
    protocol=AnnexJsonProtocol)
35421
AssertionError: CommandError not raised
35422

35423
======================================================================
35424
FAIL: datalad.support.tests.test_fileinfo.test_get_file_annexinfo
35425
----------------------------------------------------------------------
35426
Traceback (most recent call last):
35427
  File "/opt/hostedtoolcache/Python/3.7.12/x64/lib/python3.7/site-packages/nose/case.py", line 198, in runTest
35428
    self.test(*self.arg)
35429
  File "/opt/hostedtoolcache/Python/3.7.12/x64/lib/python3.7/site-packages/datalad/tests/utils.py", line 579, in _wrap_with_tree
35430
    return t(*(arg + (d,)), **kw)
35431
  File "/opt/hostedtoolcache/Python/3.7.12/x64/lib/python3.7/site-packages/datalad/support/tests/test_fileinfo.py", line 346, in test_get_file_annexinfo
35432
    assert_raises(NoSuchPathError, repo.get_file_annexinfo, 'nothere')
35433
AssertionError: NoSuchPathError not raised by get_file_annexinfo
35434

35435
----------------------------------------------------------------------
35436
Ran 1373 tests in 3841.706s
35437

35438
FAILED (SKIP=79, failures=6)
```
</details>

Versions: annexremote=1.5.0 boto=2.49.0 cmd:7z=16.02 cmd:annex=10.20220222-1~ndall+1 cmd:bundled-git=2.30.2 cmd:git=2.30.2 cmd:system-git=2.35.1 cmd:system-ssh=8.2p1 humanize=4.0.0 iso8601=1.0.2 keyring=23.5.0 keyrings.alt=UNKNOWN msgpack=1.0.3 patoolib=1.12 platformdirs=2.5.1 requests=2.27.1 tqdm=4.62.3

so seems to correspond to a fresh release of git-annex unfortunately .  

<details>
<summary>seems started to appear 3 days ago</summary> 

```shell
(git)smaug:/mnt/datasets/datalad/ci/git-annex/builds/2022/02[master]
$> grep -Ra 'FAIL: datalad.core.local.tests.test_save.test_partial_unlocked'
cron-20220219/build-macos.yaml-595-85dd9355-failed/test-datalad (release)/11_Run datalad tests.txt:2022-02-19T04:07:29.9693860Z FAIL: datalad.core.local.tests.test_save.test_partial_unlocked
cron-20220219/build-macos.yaml-595-85dd9355-failed/test-datalad (master)/11_Run datalad tests.txt:2022-02-19T04:01:39.5815990Z FAIL: datalad.core.local.tests.test_save.test_partial_unlocked
cron-20220219/build-macos.yaml-595-85dd9355-failed/test-datalad (maint)/11_Run datalad tests.txt:2022-02-19T03:51:13.8345930Z FAIL: datalad.core.local.tests.test_save.test_partial_unlocked
cron-20220219/build-macos.yaml-595-85dd9355-failed/1_test-datalad (master).txt:2022-02-19T04:01:39.5816010Z FAIL: datalad.core.local.tests.test_save.test_partial_unlocked
cron-20220219/build-macos.yaml-595-85dd9355-failed/2_test-datalad (maint).txt:2022-02-19T03:51:13.8345940Z FAIL: datalad.core.local.tests.test_save.test_partial_unlocked
cron-20220219/build-macos.yaml-595-85dd9355-failed/3_test-datalad (release).txt:2022-02-19T04:07:29.9693870Z FAIL: datalad.core.local.tests.test_save.test_partial_unlocked
cron-20220219/build-ubuntu.yaml-583-85dd9355-failed/test-datalad (release)/14_Run datalad tests.txt:2022-02-19T03:56:12.2824740Z FAIL: datalad.core.local.tests.test_save.test_partial_unlocked
cron-20220219/build-ubuntu.yaml-583-85dd9355-failed/test-datalad (master)/14_Run datalad tests.txt:2022-02-19T04:01:21.7902184Z FAIL: datalad.core.local.tests.test_save.test_partial_unlocked
cron-20220219/build-ubuntu.yaml-583-85dd9355-failed/test-datalad (maint)/14_Run datalad tests.txt:2022-02-19T03:59:24.4669037Z FAIL: datalad.core.local.tests.test_save.test_partial_unlocked
cron-20220219/build-ubuntu.yaml-583-85dd9355-failed/1_test-datalad (master).txt:2022-02-19T04:01:21.7902194Z FAIL: datalad.core.local.tests.test_save.test_partial_unlocked
cron-20220219/build-ubuntu.yaml-583-85dd9355-failed/2_test-datalad (maint).txt:2022-02-19T03:59:24.4669041Z FAIL: datalad.core.local.tests.test_save.test_partial_unlocked
cron-20220219/build-ubuntu.yaml-583-85dd9355-failed/3_test-datalad (release).txt:2022-02-19T03:56:12.2824759Z FAIL: datalad.core.local.tests.test_save.test_partial_unlocked
cron-20220220/build-macos.yaml-596-85dd9355-failed/test-datalad (release)/11_Run datalad tests.txt:2022-02-20T03:59:46.1641580Z FAIL: datalad.core.local.tests.test_save.test_partial_unlocked
cron-20220220/build-macos.yaml-596-85dd9355-failed/test-datalad (master)/11_Run datalad tests.txt:2022-02-20T04:21:24.0459130Z FAIL: datalad.core.local.tests.test_save.test_partial_unlocked
cron-20220220/build-macos.yaml-596-85dd9355-failed/test-datalad (maint)/11_Run datalad tests.txt:2022-02-20T03:49:35.7382450Z FAIL: datalad.core.local.tests.test_save.test_partial_unlocked
cron-20220220/build-macos.yaml-596-85dd9355-failed/1_test-datalad (master).txt:2022-02-20T04:21:24.0459140Z FAIL: datalad.core.local.tests.test_save.test_partial_unlocked
cron-20220220/build-macos.yaml-596-85dd9355-failed/2_test-datalad (maint).txt:2022-02-20T03:49:35.7382460Z FAIL: datalad.core.local.tests.test_save.test_partial_unlocked
cron-20220220/build-macos.yaml-596-85dd9355-failed/3_test-datalad (release).txt:2022-02-20T03:59:46.1641580Z FAIL: datalad.core.local.tests.test_save.test_partial_unlocked
cron-20220220/build-ubuntu.yaml-584-85dd9355-failed/test-datalad (release)/14_Run datalad tests.txt:2022-02-20T03:59:42.4813134Z FAIL: datalad.core.local.tests.test_save.test_partial_unlocked
cron-20220220/build-ubuntu.yaml-584-85dd9355-failed/test-datalad (master)/14_Run datalad tests.txt:2022-02-20T04:07:06.8879676Z FAIL: datalad.core.local.tests.test_save.test_partial_unlocked
cron-20220220/build-ubuntu.yaml-584-85dd9355-failed/test-datalad (maint)/14_Run datalad tests.txt:2022-02-20T04:11:19.8988367Z FAIL: datalad.core.local.tests.test_save.test_partial_unlocked
cron-20220220/build-ubuntu.yaml-584-85dd9355-failed/1_test-datalad (master).txt:2022-02-20T04:07:06.8879684Z FAIL: datalad.core.local.tests.test_save.test_partial_unlocked
cron-20220220/build-ubuntu.yaml-584-85dd9355-failed/2_test-datalad (maint).txt:2022-02-20T04:11:19.8988406Z FAIL: datalad.core.local.tests.test_save.test_partial_unlocked
cron-20220220/build-ubuntu.yaml-584-85dd9355-failed/3_test-datalad (release).txt:2022-02-20T03:59:42.4813141Z FAIL: datalad.core.local.tests.test_save.test_partial_unlocked
cron-20220221/build-macos.yaml-597-85dd9355-failed/test-datalad (release)/11_Run datalad tests.txt:2022-02-21T04:23:04.9391210Z FAIL: datalad.core.local.tests.test_save.test_partial_unlocked
cron-20220221/build-macos.yaml-597-85dd9355-failed/test-datalad (master)/11_Run datalad tests.txt:2022-02-21T03:58:45.0953960Z FAIL: datalad.core.local.tests.test_save.test_partial_unlocked
cron-20220221/build-macos.yaml-597-85dd9355-failed/test-datalad (maint)/11_Run datalad tests.txt:2022-02-21T03:50:37.6780240Z FAIL: datalad.core.local.tests.test_save.test_partial_unlocked
cron-20220221/build-macos.yaml-597-85dd9355-failed/1_test-datalad (master).txt:2022-02-21T03:58:45.0953970Z FAIL: datalad.core.local.tests.test_save.test_partial_unlocked
cron-20220221/build-macos.yaml-597-85dd9355-failed/2_test-datalad (maint).txt:2022-02-21T03:50:37.6780250Z FAIL: datalad.core.local.tests.test_save.test_partial_unlocked
cron-20220221/build-macos.yaml-597-85dd9355-failed/3_test-datalad (release).txt:2022-02-21T04:23:04.9391220Z FAIL: datalad.core.local.tests.test_save.test_partial_unlocked
cron-20220221/build-ubuntu.yaml-585-85dd9355-failed/test-datalad (release)/14_Run datalad tests.txt:2022-02-21T03:54:10.3201919Z FAIL: datalad.core.local.tests.test_save.test_partial_unlocked
cron-20220221/build-ubuntu.yaml-585-85dd9355-failed/3_test-datalad (release).txt:2022-02-21T03:54:10.3201923Z FAIL: datalad.core.local.tests.test_save.test_partial_unlocked
cron-20220222/build-macos.yaml-598-85dd9355-failed/test-datalad (release)/11_Run datalad tests.txt:2022-02-22T04:16:58.1148250Z FAIL: datalad.core.local.tests.test_save.test_partial_unlocked
cron-20220222/build-macos.yaml-598-85dd9355-failed/test-datalad (master)/11_Run datalad tests.txt:2022-02-22T04:07:41.4377330Z FAIL: datalad.core.local.tests.test_save.test_partial_unlocked
cron-20220222/build-macos.yaml-598-85dd9355-failed/test-datalad (maint)/11_Run datalad tests.txt:2022-02-22T04:01:08.9866460Z FAIL: datalad.core.local.tests.test_save.test_partial_unlocked
cron-20220222/build-macos.yaml-598-85dd9355-failed/1_test-datalad (master).txt:2022-02-22T04:07:41.4377340Z FAIL: datalad.core.local.tests.test_save.test_partial_unlocked
cron-20220222/build-macos.yaml-598-85dd9355-failed/2_test-datalad (maint).txt:2022-02-22T04:01:08.9866470Z FAIL: datalad.core.local.tests.test_save.test_partial_unlocked
cron-20220222/build-macos.yaml-598-85dd9355-failed/3_test-datalad (release).txt:2022-02-22T04:16:58.1148260Z FAIL: datalad.core.local.tests.test_save.test_partial_unlocked
cron-20220222/build-ubuntu.yaml-586-85dd9355-failed/test-datalad (release)/14_Run datalad tests.txt:2022-02-22T03:57:09.4454167Z FAIL: datalad.core.local.tests.test_save.test_partial_unlocked
cron-20220222/build-ubuntu.yaml-586-85dd9355-failed/test-datalad (maint)/14_Run datalad tests.txt:2022-02-22T04:02:07.4484981Z FAIL: datalad.core.local.tests.test_save.test_partial_unlocked
cron-20220222/build-ubuntu.yaml-586-85dd9355-failed/test-datalad (master)/14_Run datalad tests.txt:2022-02-22T04:11:56.0010232Z FAIL: datalad.core.local.tests.test_save.test_partial_unlocked
cron-20220222/build-ubuntu.yaml-586-85dd9355-failed/1_test-datalad (master).txt:2022-02-22T04:11:56.0010237Z FAIL: datalad.core.local.tests.test_save.test_partial_unlocked
cron-20220222/build-ubuntu.yaml-586-85dd9355-failed/2_test-datalad (maint).txt:2022-02-22T04:02:07.4485258Z FAIL: datalad.core.local.tests.test_save.test_partial_unlocked
cron-20220222/build-ubuntu.yaml-586-85dd9355-failed/3_test-datalad (release).txt:2022-02-22T03:57:09.4454171Z FAIL: datalad.core.local.tests.test_save.test_partial_unlocked
manual-20220222/build-ubuntu.yaml-587-85dd9355-failed/test-datalad (release)/14_Run datalad tests.txt:2022-02-22T19:24:24.5820283Z FAIL: datalad.core.local.tests.test_save.test_partial_unlocked
manual-20220222/build-ubuntu.yaml-587-85dd9355-failed/test-datalad (maint)/14_Run datalad tests.txt:2022-02-22T19:20:22.5890260Z FAIL: datalad.core.local.tests.test_save.test_partial_unlocked
manual-20220222/build-ubuntu.yaml-587-85dd9355-failed/test-datalad (master)/14_Run datalad tests.txt:2022-02-22T19:21:09.4683815Z FAIL: datalad.core.local.tests.test_save.test_partial_unlocked
manual-20220222/build-ubuntu.yaml-587-85dd9355-failed/1_test-datalad (master).txt:2022-02-22T19:21:09.4683819Z FAIL: datalad.core.local.tests.test_save.test_partial_unlocked
manual-20220222/build-ubuntu.yaml-587-85dd9355-failed/2_test-datalad (maint).txt:2022-02-22T19:20:22.5890274Z FAIL: datalad.core.local.tests.test_save.test_partial_unlocked
manual-20220222/build-ubuntu.yaml-587-85dd9355-failed/3_test-datalad (release).txt:2022-02-22T19:24:24.5820287Z FAIL: datalad.core.local.tests.test_save.test_partial_unlocked

```
</details>

I guess it would have been nice to have git-annex releases to first ensure that no downstream testing in datalad is broken before a release (attn @joeyh)

**Comment by notestaff** [comment]
Maybe, change the dependency requirements in the datalad feedstock to require last known version of git-annex that works?

**Comment by yarikoptic** [comment]
Yet to analyze - might be just a change in expected behavior (no longer errors when did previously) which wouldn't really affect user much

**Comment by adswa** [comment]
At least for ``datalad.support.tests.test_fileinfo.test_get_file_annexinfo`` the test failure is caused by us expecting a CommandError when we run `git annex find` on a non-existing file. Previous versions threw this Exception:
```
(Pdb) 
datalad.runner.exception.CommandError: CommandError: 'git -c diff.ignoreSubmodules=none annex find --copies 0 --json --json-error-messages -c annex.dotfiles=true -- nothere' failed with exitcode 1 under /tmp/datalad_temp_tree_test_get_file_annexinforotnl4h6 [info keys: stdout_json] [err: 'git-annex: nothere not found
find: 1 failed']
```

In https://github.com/datalad/datalad/blob/b1c84867db31f0fd9529a289aaafca9cd57885c0/datalad/support/annexrepo.py#L1053-L1090 we then parsed this error to determine if its cause is a missing file.

With the most recent git-annex, the output of such a call is

```
(Pdb) p out
{'stdout': '', 'stderr': "error: pathspec 'nothere' did not match any file(s) known to git\nDid you forget to 'git add'?\n", 'stdout_json': []}
```

**Comment by adswa** [comment]
This patch fixes the test failure for ``test_get_file_annexinfo`` for me, but I find it not very elegant and maybe there is a better way to do it:

```diff
diff --git a/datalad/support/annexrepo.py b/datalad/support/annexrepo.py
index 8dc063b22..c4570e895 100644
--- a/datalad/support/annexrepo.py
+++ b/datalad/support/annexrepo.py
@@ -1063,7 +1063,7 @@ class AnnexRepo(GitRepo, RepoInterface):
             )
         except CommandError as e:
             # Note: Workaround for not existing files as long as annex doesn't
-            # report it within JSON response:
+            # report it within JSON response (for annex versions < 10.20220128):
             # see http://git-annex.branchable.com/bugs/copy_does_not_reflect_some_failed_copies_in_--json_output/
             not_existing = [
                 # cut the file path from the middle, no useful delimiter
@@ -1116,7 +1116,24 @@ class AnnexRepo(GitRepo, RepoInterface):
             #        "Running %s resulted in stderr output: %s",
             #        args, shorten(e.stderr)
             #    )
-
+        if external_versions['cmd:annex'] >= '10.20220128':
+            if 'did not match any file(s) known to git' in out['stderr']:
+                not_existing = [
+                    line[17:-70] for line in out['stderr'].splitlines()
+                    if line.startswith('error:') and
+                    line.endswith('to git')
+                ]
+                if not_existing:
+                    out = {'stdout_json': []}
+                out['stdout_json'].extend(
+                    {
+                    "command": args[0],
+                    "file": f,
+                    "note": "not found",
+                    "success": False,
+                    }
+                    for f in not_existing
+                )
         json_objects = out.pop('stdout_json')
 ```

**Comment by adswa** [comment]
I think the failure of ``datalad.core.local.tests.test_save.test_partial_unlocked`` points to a regression of https://github.com/datalad/datalad/issues/1651. When an originally annexed file is unlocked, and then the attributes are changed to store it in git a ``datalad save`` puts it back into annex. I haven't investigated closely, but I think datalad is at fault here because can't reproduce it with only git and git-annex.

**Comment by adswa** [comment]
```datalad.core.local.tests.test_status.test_status_symlinked_dir_within_repo``` fails because git-annex seems to operate again on files in symlinked directories.

Running the test case in the test in question - Before:
```
❱ git annex find bar/f
git-annex: bar/f is beyond a symbolic link
git-annex: find: 1 failed
```

now:

```
datalad status --annex availability bar/f 
nothing to save, working tree clean
```

because:
```
git annex find --copies 0 bar/f 
error: pathspec 'bar/f' did not match any file(s) known to git
Did you forget to 'git add'?
```

The test that fails has the following note:
```
# As of 2a8fdfc7d (Display a warning message when asked to operate on a
# file inside a symlinked directory, 2020-05-11), git-annex will error.
```

And a git-show of this commit suggests that the introduction of the warning message was a bug fix:

```
commit 2a8fdfc7d8a4cb8bdeff3ff3b760a9b83ab80e19
Author: Joey Hess <id@joeyh.name>
Date:   Mon May 11 15:03:35 2020 -0400

    Display a warning message when asked to operate on a file inside a directory that's a symbolic link to elsewh>
    
    This relicates git's behavior. It adds a few stat calls for the command
    line parameters, so there is some minor slowdown, but even with thousands
    of parameters it will not be very noticable, and git does the same statting
    in similar circumstances.
    
    Note that this does not prevent eg "git annex add symlink"; the symlink
    will be added to git as usual. And "git annex find symlink" will silently
    list nothing as well. It's only "symlink/foo" or "subdir/symlink/foo" that
    triggers the warning.
```

I briefly scanned the commits and changelogs of git-annex for a clue why this change was made. I didn't find anything (but did not look closely), so I'm wondering, given the original commit message, whether this change is intentional.

**Comment by joeyh** [comment]
@adswa re the change in handing of a file in a symlinked directory, commit 2a8fdfc7d8a4cb8bdeff3ff3b760a9b83ab80e19 tried to replicate git's behavior, but in fact different parts of git have different behavior in that situation. Eg, git add fails with "is beyond a symbolic link", but git ls-files --error-unmatch fails with "did not match any file(s) known to git".

Since git-annex changed to use git ls-files --error-unmatch (when annex.skipunknown is true), it doesn't have to try to replicate git's behavior in the symlink case or any of the other cases. (The behavior is really rather complicated and difficult to replicate perfectly, which part of what motivated this change, see 89b2542d3caae29f64dd95de96d8259b31f489a8 for the entire motivation.). git-annex add does still replicate the "is beyone a symbolic link" behavior though.

**Comment by joeyh** [comment]
Why not just have datalad.core.local.tests.test_status.test_status_symlinked_dir_within_repo run git-annex find and ignore whatever stderr there might be, and simply look at what filenames the command outputs to stdout? If it does not output any when given a symlink to another directory, it has the right behavior.

Parsing git-annex or any command's stderr seems like an invitation to fragility.

**Comment by yarikoptic** [comment]
> Parsing git-annex or any command's stderr seems like an invitation to fragility.

and we would be happy to get rid of all and any of those kludges we added: adding `--json --json-error-messages` to all `annex` commands and ensuring that they would provide all needed information could help, but as we are playing a catch up game, we might need to carry the kludges for a little while.

**Comment by bpoldrack** [comment]
> I think the failure of datalad.core.local.tests.test_save.test_partial_unlocked points to a regression of #1651. When an originally annexed file is unlocked, and then the attributes are changed to store it in git a datalad save puts it back into annex. I haven't investigated closely, but I think datalad is at fault here because can't reproduce it with only git and git-annex.

FTR: I am looking into it and on AppVeyor (macOS) I can see it happening, when stopping that very test right before the `save` in question and go into that repo, trying to reproduce what datalad save does:

```
appveyor$ git status
On branch dl-test-branch
Changes to be committed:
  (use "git restore --staged <file>..." to unstage)
        typechange: culprit.txt

Changes not staged for commit:
  (use "git add <file>..." to update what will be committed)
  (use "git restore <file>..." to discard changes in working directory)
        modified:   .gitattributes
appveyor$ git annex add -c annex.dotfiles=true -- .gitattributes culprit.txt 
add .gitattributes (non-large file; adding content to git repository) ok
add culprit.txt (non-large file; adding content to git repository) ok
(recording state in git...)
appveyor$ git status
On branch dl-test-branch
Changes to be committed:
  (use "git restore --staged <file>..." to unstage)
        modified:   .gitattributes
        typechange: culprit.txt

appveyor$ git commit -m bla .gitattributes culprit.txt 
[dl-test-branch 7c9e09f] bla
 2 files changed, 2 insertions(+), 1 deletion(-)
 rewrite culprit.txt (100%)
 mode change 120000 => 100644
appveyor$ git status
On branch dl-test-branch
Changes to be committed:
  (use "git restore --staged <file>..." to unstage)
        modified:   culprit.txt

appveyor$ git diff --staged
diff --git a/culprit.txt b/culprit.txt
index 5ca234c..f10ecb0 100644
--- a/culprit.txt
+++ b/culprit.txt
@@ -1 +1 @@
-345
\ No newline at end of file
+/annex/objects/MD5E-s3--d81f9c1be2e08964bf9f24b15f0e4900.txt
```

Whereas a direct call to `commit`, omitting the `annex add` seems to be fine:

```
appveyor$ git status
On branch dl-test-branch
Changes to be committed:
  (use "git restore --staged <file>..." to unstage)
        typechange: culprit.txt

Changes not staged for commit:
  (use "git add <file>..." to update what will be committed)
  (use "git restore <file>..." to discard changes in working directory)
        modified:   .gitattributes

appveyor$ git commit -m bla -- .gitattributes culprit.txt 
[dl-test-branch 9824815] bla
 2 files changed, 2 insertions(+), 1 deletion(-)
 rewrite culprit.txt (100%)
 mode change 120000 => 100644
appveyor$ git status
On branch dl-test-branch
nothing to commit, working tree clean
appveyor$ ls -la culprit.txt 
-rw-r--r--  1 appveyor  staff  3 Mar 15 10:54 culprit.txt
appveyor$ cat culprit.txt 
345
```

**Comment by bpoldrack** [comment]
> Doesn't this suggest a problem in git-annex's hooks?

Smells like it. Also seems to be some race condition. Here is a script that reproduces it w/o datalad on that appveyor machine but only most of the times - sometimes it ends up with a clean repo:

```
set -x
chmod -R u+w testrepo
rm -rf testrepo

mkdir testrepo
cd testrepo
git init
git annex init
echo "**/.git* annex.largfiles=nothing" > .gitattributes
git annex add .gitattributes
echo "something" > somefile
git annex add -c annex.dotfiles=true -- .gitattributes somefile
git commit -m "to annex"
ls -la
git status
#----------Setup done-----------------
git annex unlock somefile
echo "* annex.largefiles=nothing" >> .gitattributes
git annex add -c annex.dotfiles=true -- .gitattributes somefile
git commit -m "adding to git" .gitattributes somefile
git status  # <- this will (most of the time) show a modified `somefile`
git annex version
git --version
```

Will post to annex and link here
