### ISSUE TITLE
`_guess_ri_cls(ri)` must be guarded

### ISSUE THREAD

**Issue by mih** [datalad/datalad#6494]
I made a mistake when hand-converting an SSH-type clone URL to the https equivalent and ended up here:

```
% datalad clone https://github.com:datalad-datasets/human-connectome-project-openaccess.git hcp
[ERROR  ] ValueError(invalid literal for int() with base 10: 'datalad-datasets') (ValueError) 
```

The URL is invalid, but the error is not very clear. It is caused here:

```
Traceback (most recent call last):
  File "/home/mih/venvs/datalad/bin/datalad", line 33, in <module>
    sys.exit(load_entry_point('datalad', 'console_scripts', 'datalad')())
  File "/home/mih/code/datalad/datalad/cli/main.py", line 135, in main
    if cmdlineargs.common_debug or cmdlineargs.common_idebug \
  File "/home/mih/code/datalad/datalad/cli/main.py", line 147, in _run_with_debugger
    return cmdlineargs.func(cmdlineargs)
  File "/home/mih/code/datalad/datalad/cli/exec.py", line 107, in call_from_parser
    ret = list(ret)
  File "/home/mih/code/datalad/datalad/interface/utils.py", line 369, in generator_func
    allkwargs):
  File "/home/mih/code/datalad/datalad/interface/utils.py", line 544, in _process_results
    for res in results:
  File "/home/mih/code/datalad/datalad/core/distributed/clone.py", line 344, in __call__
    clone_opts=git_clone_opts,
  File "/home/mih/code/datalad/datalad/core/distributed/clone.py", line 546, in clone_dataset
    candidate_sources = [decode_source_spec(s, cfg=cfg) for s in srcs]
  File "/home/mih/code/datalad/datalad/core/distributed/clone.py", line 546, in <listcomp>
    candidate_sources = [decode_source_spec(s, cfg=cfg) for s in srcs]
  File "/home/mih/code/datalad/datalad/core/distributed/clone.py", line 1451, in decode_source_spec
    source_ri = RI(spec) if not isinstance(spec, RI) else spec
  File "/home/mih/code/datalad/datalad/support/network.py", line 409, in __new__
    cls = _guess_ri_cls(ri)
  File "/home/mih/code/datalad/datalad/support/network.py", line 326, in _guess_ri_cls
    fields = URL._pr_to_fields(urlparse(ri))
  File "/home/mih/code/datalad/datalad/support/network.py", line 653, in _pr_to_fields
    return {f: (_getattr(pr, f) or '') for f in cls._FIELDS}
  File "/home/mih/code/datalad/datalad/support/network.py", line 653, in <dictcomp>
    return {f: (_getattr(pr, f) or '') for f in cls._FIELDS}
  File "/usr/lib/python3.7/urllib/parse.py", line 169, in port
    port = int(port, 10)
ValueError: invalid literal for int() with base 10: 'datalad-datasets'
```

**Comment by yarikoptic** [comment]
there is no limits to perfection!
