### ISSUE TITLE
test_basic_scenario_local_url -- FAILs on cron run on master

### ISSUE THREAD

**Issue by yarikoptic** [datalad/datalad#6541]
in `_DL_ANNEX_INSTALL_SCENARIO="miniconda --batch git-annex=8.20200309 -m conda"` matrix run -- so likely just annex incompatibility

Spotted in a failed run on master
https://app.travis-ci.com/github/datalad/datalad/jobs/563044933

```
======================================================================
FAIL: datalad.customremotes.tests.test_datalad.test_basic_scenario_local_url
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/tmp/dl-miniconda-k9cqsqre/lib/python3.9/site-packages/nose/case.py", line 198, in runTest
    self.test(*self.arg)
  File "/tmp/dl-miniconda-k9cqsqre/lib/python3.9/site-packages/datalad/tests/utils.py", line 579, in _wrap_with_tree
    return t(*(arg + (d,)), **kw)
  File "/tmp/dl-miniconda-k9cqsqre/lib/python3.9/site-packages/datalad/tests/utils.py", line 807, in _wrap_serve_path_via_http
    return tfunc(*(args + (path, url)), **kwargs)
  File "/tmp/dl-miniconda-k9cqsqre/lib/python3.9/site-packages/datalad/customremotes/tests/test_datalad.py", line 87, in test_basic_scenario_local_url
    check_basic_scenario("%s3versions-allversioned.txt" % local_url)
  File "/tmp/dl-miniconda-k9cqsqre/lib/python3.9/site-packages/datalad/tests/utils.py", line 874, in _wrap_with_tempfile
    return t(*(arg + (filename,)), **kw)
  File "/tmp/dl-miniconda-k9cqsqre/lib/python3.9/site-packages/datalad/tests/utils.py", line 194, in _wrap_skip_if_no_network
    return func(*args, **kwargs)
  File "/tmp/dl-miniconda-k9cqsqre/lib/python3.9/site-packages/datalad/customremotes/tests/test_datalad.py", line 52, in check_basic_scenario
    assert_in('_', filename)
AssertionError: '_' not found in '3versions-allversioned.txt'
```

started to fail in november last year
```
(git)smaug:/mnt/datasets/datalad/ci/logs/2021[master]git
$> datalad foreach-dataset --subdatasets-only -J0 git grep FAIL:.*test_basic_scenario_local_url
foreach-dataset(error): /mnt/datasets/datalad/ci/logs/2021/05 (dataset) [CommandError: 'git grep 'FAIL:.*test_basic_scenario_local_url'' failed with exitcode 1 under /mnt/datasets/datalad/ci/logs/2021/05]
foreach-dataset(error): /mnt/datasets/datalad/ci/logs/2021/06 (dataset) [CommandError: 'git grep 'FAIL:.*test_basic_scenario_local_url'' failed with exitcode 1 under /mnt/datasets/datalad/ci/logs/2021/06]
foreach-dataset(error): /mnt/datasets/datalad/ci/logs/2021/07 (dataset) [CommandError: 'git grep 'FAIL:.*test_basic_scenario_local_url'' failed with exitcode 1 under /mnt/datasets/datalad/ci/logs/2021/07]
foreach-dataset(error): /mnt/datasets/datalad/ci/logs/2021/08 (dataset) [CommandError: 'git grep 'FAIL:.*test_basic_scenario_local_url'' failed with exitcode 1 under /mnt/datasets/datalad/ci/logs/2021/08]
foreach-dataset(error): /mnt/datasets/datalad/ci/logs/2021/09 (dataset) [CommandError: 'git grep 'FAIL:.*test_basic_scenario_local_url'' failed with exitcode 1 under /mnt/datasets/datalad/ci/logs/2021/09]
foreach-dataset(error): /mnt/datasets/datalad/ci/logs/2021/10 (dataset) [CommandError: 'git grep 'FAIL:.*test_basic_scenario_local_url'' failed with exitcode 1 under /mnt/datasets/datalad/ci/logs/2021/10]
12/cron/20211112T191610/417c95d/travis-12950-failed/10.txt:FAIL: datalad.customremotes.tests.test_datalad.test_basic_scenario_local_url
19/cron/20211119T210829/e6e7720/travis-13021-failed/10.txt:FAIL: datalad.customremotes.tests.test_datalad.test_basic_scenario_local_url
26/cron/20211126T210741/b7ed22e/travis-13095-failed/10.txt:FAIL: datalad.customremotes.tests.test_datalad.test_basic_scenario_local_url
foreach-dataset(ok): /mnt/datasets/datalad/ci/logs/2021/11 (dataset)
...
```

**Comment by yarikoptic** [comment]
eh, nobody looked into it, failed again https://app.travis-ci.com/github/datalad/datalad/jobs/576842693 . 

<details>
<summary>seems to start failing less frequently recently?</summary> 

```shell
$> datalad foreach-dataset git grep "AssertionError: '_' not found in '3versions-allversioned.txt"
foreach-dataset(error): /mnt/datasets/datalad/ci/logs/2022 (dataset) [CommandError: 'git grep 'AssertionError: '"'"'_'"'"' not found in '"'"'3versions-allversioned.txt'' failed with exitcode 1 under /mnt/datasets/datalad/ci/logs/2022]
01/cron/20220401T192523/f15fea0/travis-13792-failed/11.txt:AssertionError: '_' not found in '3versions-allversioned.txt'
07/cron/20220107T192017/251e780/travis-13270-failed/10.txt:AssertionError: '_' not found in '3versions-allversioned.txt'
14/cron/20220114T192057/d8c8383/travis-13283-failed/10.txt:AssertionError: '_' not found in '3versions-allversioned.txt'
04/cron/20220304T192357/8b4236c/travis-13616-failed/11.txt:AssertionError: '_' not found in '3versions-allversioned.txt'
21/cron/20220121T192130/c666b36/travis-13304-failed/10.txt:AssertionError: '_' not found in '3versions-allversioned.txt'
08/cron/20220408T195551/6b4280d/travis-13830-failed/11.txt:AssertionError: '_' not found in '3versions-allversioned.txt'
11/cron/20220311T192943/eeb2ccc/travis-13642-failed/11.txt:AssertionError: '_' not found in '3versions-allversioned.txt'
12/cron/20220412T214110/a69fc7d/travis-13840-failed/11.txt:AssertionError: '_' not found in '3versions-allversioned.txt'
07/cron/20220607T214906/e3470ec/travis-14117-failed/11.txt:AssertionError: '_' not found in '3versions-allversioned.txt'
15/cron/20220415T192628/4aff4a2/travis-13845-failed/11.txt:AssertionError: '_' not found in '3versions-allversioned.txt'
19/cron/20220419T214205/1389fe8/travis-13858-failed/11.txt:AssertionError: '_' not found in '3versions-allversioned.txt'
28/cron/20220128T192159/01793cc/travis-13367-failed/11.txt:AssertionError: '_' not found in '3versions-allversioned.txt'
04/cron/20220204T192219/cc84266/travis-13417-failed/11.txt:AssertionError: '_' not found in '3versions-allversioned.txt'
03/cron/20220503T214546/3fc0f47/travis-13990-failed/11.txt:AssertionError: '_' not found in '3versions-allversioned.txt'
foreach-dataset(ok): /mnt/datasets/datalad/ci/logs/2022/01 (dataset)
14/cron/20220614T214941/a220bfc/travis-14151-failed/11.txt:AssertionError: '_' not found in '3versions-allversioned.txt'
26/cron/20220426T214213/413ba87/travis-13913-failed/11.txt:AssertionError: '_' not found in '3versions-allversioned.txt'
21/cron/20220621T215022/a220bfc/travis-14158-failed/11.txt:AssertionError: '_' not found in '3versions-allversioned.txt'
28/cron/20220628T215114/9a332d3/travis-14167-failed/11.txt:AssertionError: '_' not found in '3versions-allversioned.txt'
18/cron/20220318T192424/c74e75c/travis-13713-failed/11.txt:AssertionError: '_' not found in '3versions-allversioned.txt'
29/cron/20220429T201230/dd6077f/travis-13958-failed/11.txt:AssertionError: '_' not found in '3versions-allversioned.txt'
05/cron/20220705T215106/6ec85d4/travis-14213-failed/11.txt:AssertionError: '_' not found in '3versions-allversioned.txt'
10/cron/20220510T214257/8017e42/travis-14022-failed/11.txt:AssertionError: '_' not found in '3versions-allversioned.txt'
foreach-dataset(ok): /mnt/datasets/datalad/ci/logs/2022/06 (dataset)
foreach-dataset(ok): /mnt/datasets/datalad/ci/logs/2022/04 (dataset)
17/cron/20220517T214308/1f734f6/travis-14028-failed/11.txt:AssertionError: '_' not found in '3versions-allversioned.txt'
11/cron/20220211T192231/aebb5ce/travis-13478-failed/11.txt:AssertionError: '_' not found in '3versions-allversioned.txt'
24/cron/20220524T214754/439a3ca/travis-14047-failed/11.txt:AssertionError: '_' not found in '3versions-allversioned.txt'
18/cron/20220218T215831/ac55016/travis-13521-failed/11.txt:AssertionError: '_' not found in '3versions-allversioned.txt'
foreach-dataset(ok): /mnt/datasets/datalad/ci/logs/2022/07 (dataset)
25/cron/20220325T192427/ee720b8/travis-13757-failed/11.txt:AssertionError: '_' not found in '3versions-allversioned.txt'
31/cron/20220531T224356/ab52d00/travis-14075-failed/11.txt:AssertionError: '_' not found in '3versions-allversioned.txt'
foreach-dataset(ok): /mnt/datasets/datalad/ci/logs/2022/05 (dataset)
foreach-dataset(ok): /mnt/datasets/datalad/ci/logs/2022/03 (dataset)
25/cron/20220225T203641/b1c8486/travis-13593-failed/11.txt:AssertionError: '_' not found in '3versions-allversioned.txt'
foreach-dataset(ok): /mnt/datasets/datalad/ci/logs/2022/02 (dataset)

```
</details>
