### ISSUE TITLE
different git version when switching between datalad versions

### ISSUE THREAD

**Issue by djarecka** [datalad/datalad#6551]
### What is the problem?

When I use my older `datalad` conda environment on a cluster (openmind) it changes my git to a higher version (2.3), but when I use the latest version of `datalad` (0.15.6) it doesn't do it. Was this change done on purpose?

### What steps will reproduce the problem?

This is what I run:
```
[19:09][194.73][-36%]djarecka@openmind7:~$ git --version
git version 1.8.3.1
[19:10][194.88][-35%]djarecka@openmind7:~$ conda activate datalad
[19:10][194.89][-35%]djarecka@openmind7:~$ git --version
git version 2.30.0
[19:10][194.81][-35%]djarecka@openmind7:~$ datalad --version
datalad 0.15.2
[19:10][194.75][-35%]djarecka@openmind7:~$ conda activate datalad_0.15.6
[19:10][194.97][-35%]djarecka@openmind7:~$ git --version
git version 1.8.3.1
```

### Datalad information

Ha! I can't run any datalad commands: getting `datalad.runner.exception.CommandError: CommandError: 'git --git-dir= config -z -l --show-origin' failed with exitcode 129 [err: 'error: unknown option 'show-origin' `, but I just run `pip install datalad`, so should be `0.15.6`.

<details>
<summary> But I can run `datalad wtf` with my old environment </summary>

[19:24][196.74][-38%]djarecka@openmind7:~$ datalad --version
datalad 0.15.2
[19:25][196.39][-38%]djarecka@openmind7:~$ datalad wtf
# WTF
## credentials 
  - keyring: 
    - active_backends: 
      - PlaintextKeyring with no encyption v.1.0 at /home/djarecka/.local/share/python_keyring/keyring_pass.cfg
    - config_file: /home/djarecka/.config/python_keyring/keyringrc.cfg
    - data_root: /home/djarecka/.local/share/python_keyring
## datalad 
  - full_version: 0.15.2
  - version: 0.15.2
## dependencies 
  - annexremote: 1.5.0
  - appdirs: 1.4.4
  - boto: 2.49.0
  - cmd:7z: 16.02
  - cmd:annex: 8.20201129-geb388e6
  - cmd:bundled-git: UNKNOWN
  - cmd:git: 2.30.0
  - cmd:system-git: 2.30.0
  - cmd:system-ssh: 8.4p1
  - humanize: 3.2.0
  - iso8601: 0.1.13
  - keyring: 22.0.1
  - keyrings.alt: 4.0.2
  - msgpack: 1.0.2
  - requests: 2.25.1
  - wrapt: 1.12.1
## environment 
  - LANG: en_US.UTF-8
  - PATH: /om2/user/djarecka/miniconda/envs/datalad/bin:/om2/user/djarecka/miniconda/condabin:/om/user/djarecka/elastix/bin:/home/djarecka/bin:/cm/shared/apps/gcc/4.8.4/bin:/usr/lib64/qt-3.3/bin:/usr/local/bin:/usr/bin:/usr/local/sbin:/usr/sbin
## git-annex 
  - build flags: 
    - Assistant
    - Webapp
    - Pairing
    - Inotify
    - DBus
    - DesktopNotify
    - TorrentParser
    - MagicMime
    - Feeds
    - Testsuite
    - S3
    - WebDAV
  - dependency versions: 
    - aws-0.22
    - bloomfilter-2.0.1.0
    - cryptonite-0.26
    - DAV-1.3.4
    - feed-1.3.0.1
    - ghc-8.8.4
    - http-client-0.6.4.1
    - persistent-sqlite-2.10.6.2
    - torrent-10000.1.1
    - uuid-1.3.13
    - yesod-1.6.1.0
  - key/value backends: 
    - SHA256E
    - SHA256
    - SHA512E
    - SHA512
    - SHA224E
    - SHA224
    - SHA384E
    - SHA384
    - SHA3_256E
    - SHA3_256
    - SHA3_512E
    - SHA3_512
    - SHA3_224E
    - SHA3_224
    - SHA3_384E
    - SHA3_384
    - SKEIN256E
    - SKEIN256
    - SKEIN512E
    - SKEIN512
    - BLAKE2B256E
    - BLAKE2B256
    - BLAKE2B512E
    - BLAKE2B512
    - BLAKE2B160E
    - BLAKE2B160
    - BLAKE2B224E
    - BLAKE2B224
    - BLAKE2B384E
    - BLAKE2B384
    - BLAKE2BP512E
    - BLAKE2BP512
    - BLAKE2S256E
    - BLAKE2S256
    - BLAKE2S160E
    - BLAKE2S160
    - BLAKE2S224E
    - BLAKE2S224
    - BLAKE2SP256E
    - BLAKE2SP256
    - BLAKE2SP224E
    - BLAKE2SP224
    - SHA1E
    - SHA1
    - MD5E
    - MD5
    - WORM
    - URL
    - X*
  - operating system: linux x86_64
  - remote types: 
    - git
    - gcrypt
    - p2p
    - S3
    - bup
    - directory
    - rsync
    - web
    - bittorrent
    - webdav
    - adb
    - tahoe
    - glacier
    - ddar
    - git-lfs
    - httpalso
    - borg
    - hook
    - external
  - supported repository versions: 
    - 8
  - upgrade supported from repository versions: 
    - 0
    - 1
    - 2
    - 3
    - 4
    - 5
    - 6
    - 7
  - version: 8.20201129-geb388e6
## location 
  - path: /home/djarecka
  - type: directory
## metadata_extractors 
  - annex (datalad 0.15.2): 
    - distribution: datalad 0.15.2
    - load_error: None
    - module: datalad.metadata.extractors.annex
    - version: None
  - audio (datalad 0.15.2): 
    - distribution: datalad 0.15.2
    - load_error: ModuleNotFoundError(No module named 'mutagen')
    - module: datalad.metadata.extractors.audio
  - datacite (datalad 0.15.2): 
    - distribution: datalad 0.15.2
    - load_error: None
    - module: datalad.metadata.extractors.datacite
    - version: None
  - datalad_core (datalad 0.15.2): 
    - distribution: datalad 0.15.2
    - load_error: None
    - module: datalad.metadata.extractors.datalad_core
    - version: None
  - datalad_rfc822 (datalad 0.15.2): 
    - distribution: datalad 0.15.2
    - load_error: None
    - module: datalad.metadata.extractors.datalad_rfc822
    - version: None
  - exif (datalad 0.15.2): 
    - distribution: datalad 0.15.2
    - load_error: ModuleNotFoundError(No module named 'exifread')
    - module: datalad.metadata.extractors.exif
  - frictionless_datapackage (datalad 0.15.2): 
    - distribution: datalad 0.15.2
    - load_error: None
    - module: datalad.metadata.extractors.frictionless_datapackage
    - version: None
  - image (datalad 0.15.2): 
    - distribution: datalad 0.15.2
    - load_error: ModuleNotFoundError(No module named 'PIL')
    - module: datalad.metadata.extractors.image
  - xmp (datalad 0.15.2): 
    - distribution: datalad 0.15.2
    - load_error: ModuleNotFoundError(No module named 'libxmp')
    - module: datalad.metadata.extractors.xmp
## python 
  - implementation: CPython
  - version: 3.8.6
## system 
  - distribution: centos/7/Core
  - encoding: 
    - default: utf-8
    - filesystem: utf-8
    - locale.prefered: UTF-8
  - max_path_length: 270
  - name: Linux
  - release: 3.10.0-1062.el7.x86_64
  - type: posix
  - version: #1 SMP Wed Aug 7 18:08:02 UTC 2019

</details>

**Comment by yarikoptic** [comment]
DataLad changes nothing. It seems you have two conda environments you installed with different git versions, or not installed at all. And two different datalads, who knows how (conda? pip?).  I guess we might not know, although reproman could help ;-)

I would guess 
- you have system wide elderly git 1.8.3.1
- in `datalad` conda env you installed datalad using conda, that installed some more recent then `git`
- in `datalad_0.15.6` you either didn't even install datalad (was not shown) or installed it via `pip` so no `git` was installed.  `which git` would help to confirm (or not) that.

**Comment by djarecka** [comment]
oh, ok, perhaps I did use conda to install `datalad` last time. In `datalad_0.15.6` I did install datald as well, but as I mentioned I used `pip`, so it would be consistent with what you wrote. Will close the issue, but perhaps you could still provide some simpler error message when `datalad` finds too old git.

**Comment by yarikoptic** [comment]
>  but perhaps you could still provide some simpler error message when datalad finds too old git.
fair enough, especially since we did do that in #4650 so indeed the question - why it wasn't triggered... how exactly did you invoke datalad @djarecka? (I might try to reproduce tomorrow)

**Comment by djarecka** [comment]
conda env:
```
conda create -n tmp_datalad python=3.8
conda activate tmp_datalad
pip install datalad
```

after this many (all?) datalad commands give this error:
```
[23:34][192.65][-49%]djarecka@openmind7:~$ datalad --version
Traceback (most recent call last):
  File "/om2/user/djarecka/miniconda/envs/tmp_datalad/bin/datalad", line 5, in <module>
    from datalad.cmdline.main import main
  File "/om2/user/djarecka/miniconda/envs/tmp_datalad/lib/python3.8/site-packages/datalad/__init__.py", line 48, in <module>
    cfg = ConfigManager()
  File "/om2/user/djarecka/miniconda/envs/tmp_datalad/lib/python3.8/site-packages/datalad/config.py", line 345, in __init__
    self.reload(force=True)
  File "/om2/user/djarecka/miniconda/envs/tmp_datalad/lib/python3.8/site-packages/datalad/config.py", line 399, in reload
    self._stores[store_id] = self._reload(runargs)
  File "/om2/user/djarecka/miniconda/envs/tmp_datalad/lib/python3.8/site-packages/datalad/config.py", line 427, in _reload
    stdout, stderr = self._run(
  File "/om2/user/djarecka/miniconda/envs/tmp_datalad/lib/python3.8/site-packages/datalad/config.py", line 789, in _run
    out = self._runner.run(self._config_cmd + args, **kwargs)
  File "/om2/user/djarecka/miniconda/envs/tmp_datalad/lib/python3.8/site-packages/datalad/runner/runner.py", line 145, in run
    raise CommandError(
datalad.runner.exception.CommandError: CommandError: 'git --git-dir= config -z -l --show-origin' failed with exitcode 129 [err: 'error: unknown option `show-origin'
usage: git config [options]

Config file location
    --global              use global config file
    --system              use system config file
    --local               use repository config file
    -f, --file <file>     use given config file
    --blob <blob-id>      read config from given blob object
....
````

**Comment by yarikoptic** [comment]
Eh, config manager kicks in before that check has a chance. I guess we should just move that check to init and be done

**Comment by adswa** [comment]
FTR: I tried to whack at this, but I found it surprisingly difficult to move the check into `__init__` before the config manager kicks in - it seems it is required to import the relevant functions from ``datalad.support`` or even the runner...
