### ISSUE TITLE
create-sibling-ria crashes if ran in a repo without a known to annex remote

### ISSUE THREAD

**Issue by yarikoptic** [datalad/datalad#6559]
might be a user error but

```shell
(git-annex)lena:/tmp/testds[master]
$> datalad create-sibling-ria -s my-ria ria+file:///tmp/my-ria
Query siblings: 0.00 Siblings [00:00, ? Siblings/s]CommandError: 'git -c diff.ignoreSubmodules=none cat-file blob git-annex:remote.log' failed with exitcode 128 under /tmp/testds
fatal: path 'remote.log' does not exist in 'git-annex'

$> git ls-tree git-annex
040000 tree 1cdd10dc4ffaec97bbf0f34d253ee2e8fee4f829	18a
040000 tree 6b1c4bf667da08a401994390516350fe6b283b95	1ed
040000 tree 86f1d50d5e096b11116ac0d6cd8538c052e5f5c2	299
040000 tree f9eaf97f7570164a2515f91f335052cc029c6097	337
040000 tree f18543855ca2f6e0fc1e7b8e014713ce30ffb2ac	60e
040000 tree 214f4ffca2bb5c876912a3d87cdbe35ba0dfb625	752
040000 tree 3dfff73cb3aab430701e53e0042b5e20646ba242	a26
040000 tree 2e0c02a0511976f1bdbfd5aadd9fc0291eed6151	bd6
040000 tree 4de9081f43a859069dcafb0baa7204f84dbbe3bc	ff4
100644 blob 676603fa4c393a51cd981b9a0c22519dbb1bc8a9	uuid.log

$> datalad --version
datalad 0.15.5
```

the same with fresh master 0.15.6+829.gb23174877 .

**Comment by bpoldrack** [comment]
I consider this a bug, not a user error, since `remote.log` does not always exist yet and we need to account for it. But at a first glance smells like a bug in `siblings`, not `create-sibling-ria`. Confusing thing is, that I don't see yet, how we manage to miss that in the tests.

**Comment by yarikoptic** [comment]
not sure... I also see that (I think) now while running tests locally:

```
(git)lena:~datalad/datalad-maint[maint]git
$> python -m nose -s -v datalad/core/local/tests/test_save.py:test_add_subdataset
datalad.core.local.tests.test_save.test_add_subdataset ... subdataset(ok): dir (dataset)
ERROR
Versions: annexremote=1.5.0 appdirs=1.4.4 boto=2.49.0 cmd:7z=16.02 cmd:annex=8.20211123 cmd:bundled-git=UNKNOWN cmd:git=2.35.1.473.g83b2b277ed cmd:system-git=2.35.1.473.g83b2b277ed cmd:system-ssh=8.7p1 exifread=2.3.2 humanize=4.0.0 iso8601=1.0.2 keyring=23.5.0 keyrings.alt=UNKNOWN msgpack=1.0.3 mutagen=1.45.1 requests=2.27.1 wrapt=1.13.3
Obscure filename: str=b' |;&%b5{}\'"\xce\x94\xd0\x99\xd7\xa7\xd9\x85\xe0\xb9\x97\xe3\x81\x82 .datc ' repr=' |;&%b5{}\'"ΔЙקم๗あ .datc '
Encodings: default='utf-8' filesystem='utf-8' locale.prefered='UTF-8'
Environment: PATH='/home/yoh/proj/datalad/datalad-maint/venvs/dev3/bin:/home/yoh/gocode/bin:/home/yoh/gocode/bin:/home/yoh/bin:/home/yoh/.local/bin:/usr/local/bin:/usr/bin:/bin:/usr/local/games:/usr/games:/sbin:/usr/sbin:/usr/local/sbin' LANG='en_US.UTF-8' GIT_PAGER='less --no-init --quit-if-one-screen' GIT_CONFIG_PARAMETERS="'init.defaultBranch=dl-test-branch' 'clone.defaultRemoteName=dl-test-remote'"

======================================================================
ERROR: datalad.core.local.tests.test_save.test_add_subdataset
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/yoh/proj/datalad/datalad-maint/venvs/dev3/lib/python3.9/site-packages/nose/case.py", line 198, in runTest
    self.test(*self.arg)
  File "/home/yoh/proj/datalad/datalad-maint/datalad/tests/utils.py", line 563, in _wrap_with_tree
    return t(*(arg + (d,)), **kw)
  File "/home/yoh/proj/datalad/datalad-maint/datalad/tests/utils.py", line 742, in _wrap_with_tempfile
    return t(*(arg + (filename,)), **kw)
  File "/home/yoh/proj/datalad/datalad-maint/datalad/core/local/tests/test_save.py", line 443, in test_add_subdataset
    other_clone = install(source=other.path, path=op.join(ds.path, 'other'))
  File "/home/yoh/proj/datalad/datalad-maint/datalad/interface/utils.py", line 484, in eval_func
    return return_func(generator_func)(*args, **kwargs)
  File "/home/yoh/proj/datalad/datalad-maint/datalad/interface/utils.py", line 476, in return_func
    results = list(results)
  File "/home/yoh/proj/datalad/datalad-maint/datalad/interface/utils.py", line 396, in generator_func
    for r in _process_results(
  File "/home/yoh/proj/datalad/datalad-maint/datalad/interface/utils.py", line 579, in _process_results
    for res in results:
  File "/home/yoh/proj/datalad/datalad-maint/datalad/distribution/install.py", line 368, in __call__
    for r in res:
  File "/home/yoh/proj/datalad/datalad-maint/datalad/interface/utils.py", line 396, in generator_func
    for r in _process_results(
  File "/home/yoh/proj/datalad/datalad-maint/datalad/interface/utils.py", line 579, in _process_results
    for res in results:
  File "/home/yoh/proj/datalad/datalad-maint/datalad/core/distributed/clone.py", line 321, in __call__
    for r in clone_dataset(
  File "/home/yoh/proj/datalad/datalad-maint/datalad/core/distributed/clone.py", line 706, in clone_dataset
    yield from postclonecfg_annexdataset(
  File "/home/yoh/proj/datalad/datalad-maint/datalad/core/distributed/clone.py", line 1196, in postclonecfg_annexdataset
    for uuid, config in repo.get_special_remotes().items():
  File "/home/yoh/proj/datalad/datalad-maint/datalad/support/annexrepo.py", line 812, in get_special_remotes
    raise e
  File "/home/yoh/proj/datalad/datalad-maint/datalad/support/annexrepo.py", line 800, in get_special_remotes
    list(
  File "/home/yoh/proj/datalad/datalad-maint/datalad/dataset/gitrepo.py", line 343, in call_git_items_
    out, _ = self._call_git(args, files, expect_stderr=expect_stderr,
  File "/home/yoh/proj/datalad/datalad-maint/datalad/dataset/gitrepo.py", line 259, in _call_git
    res = runner.run(
  File "/home/yoh/proj/datalad/datalad-maint/datalad/runner/runner.py", line 145, in run
    raise CommandError(
datalad.runner.exception.CommandError: CommandError: 'git -c diff.ignoreSubmodules=none cat-file blob git-annex:remote.log' failed with exitcode 128 under /home/yoh/.tmp/datalad_temp_tree_test_add_subdatasetktmq2yq9/other [err: 'fatal: path 'remote.log' does not exist in 'git-annex'']

```
