### ISSUE TITLE
test_clone.test_ria_postclonecfg: Failed to clone  on  MacOS

### ISSUE THREAD

**Issue by yarikoptic** [datalad/datalad#6653]
```

======================================================================
ERROR: datalad.core.distributed.tests.test_clone.test_ria_postclonecfg('ssh://datalad-test:/Users/appveyor/DLTMP/datalad_temp_98cnl5np', '986fca60-e1bf-48b3-9b06-413b5f3e1f65')
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/Users/appveyor/venv3.8.12/lib/python3.8/site-packages/nose/case.py", line 198, in runTest
    self.test(*self.arg)
  File "/Users/appveyor/projects/datalad/datalad/tests/utils.py", line 288, in _wrap_skip_ssh
    return func(*args, **kwargs)
  File "/Users/appveyor/projects/datalad/datalad/tests/utils.py", line 874, in _wrap_with_tempfile
    return t(*(arg + (filename,)), **kw)
  File "/Users/appveyor/projects/datalad/datalad/tests/utils.py", line 874, in _wrap_with_tempfile
    return t(*(arg + (filename,)), **kw)
  File "/Users/appveyor/projects/datalad/datalad/core/distributed/tests/test_clone.py", line 958, in _test_ria_postclonecfg
    riaclone = clone('ria+{}#{}'.format(url, dsid), clone_path)
  File "/Users/appveyor/projects/datalad/datalad/interface/utils.py", line 447, in eval_func
    return return_func(*args, **kwargs)
  File "/Users/appveyor/projects/datalad/datalad/interface/utils.py", line 439, in return_func
    results = list(results)
  File "/Users/appveyor/projects/datalad/datalad/interface/utils.py", line 424, in generator_func
    raise IncompleteResultsError(
datalad.support.exceptions.IncompleteResultsError: Command did not complete successfully. 1 failed:
[{'action': 'install',
  'message': ('Failed to clone from any candidate source URL. Encountered '
              'errors per each url were:\n'
              '- %s',
              'ssh://datalad-test/Users/appveyor/DLTMP/datalad_temp_98cnl5np/986/fca60-e1bf-48b3-9b06-413b5f3e1f65\n'
              "  CommandError: 'git -c diff.ignoreSubmodules=none clone "
              '--progress '
              'ssh://datalad-test/Users/appveyor/DLTMP/datalad_temp_98cnl5np/986/fca60-e1bf-48b3-9b06-413b5f3e1f65 '
              "/Users/appveyor/DLTMP/datalad_temp__test_ria_postclonecfgfc5i8p2z' "
              "failed with exitcode 128 [err: 'Cloning into "
              "'/Users/appveyor/DLTMP/datalad_temp__test_ria_postclonecfgfc5i8p2z'...\n"
              '\r'
              'remote: Total 37 (delta 7), reused 0 (delta 0)        \n'
              "fatal: remote transport reported error']"),
  'path': '/Users/appveyor/DLTMP/datalad_temp__test_ria_postclonecfgfc5i8p2z',
  'source_url': 'ria+ssh://datalad-test:/Users/appveyor/DLTMP/datalad_temp_98cnl5np#986fca60-e1bf-48b3-9b06-413b5f3e1f65',
  'status': 'error',
  'type': 'dataset'}]
-------------------- >> begin captured logging << --------------------
datalad.core.distributed.clone: INFO: Cloning dataset to Dataset(/Users/appveyor/DLTMP/datalad_temp__test_ria_postclonecfgfc5i8p2z)

```
in a run https://ci.appveyor.com/project/mih/datalad/builds/43337298/job/9ivu29ncpmpamlqu for https://github.com/datalad/datalad/pull/6648

**Comment by bpoldrack** [comment]
This is actually the same as https://github.com/datalad/datalad/issues/6599
