### ISSUE TITLE
'{' is not recognized as an internal or external command

### ISSUE THREAD

**Issue by yarikoptic** [datalad/datalad#67]
```
======================================================================
FAIL: Verify that all our repos are clonable
----------------------------------------------------------------------
Traceback (most recent call last):
  File "C:\Python27\lib\site-packages\nose\case.py", line 197, in runTest
    self.test(*self.arg)
  File "c:\buildslave\datalad-tests-virtualbox-dl-win7-64\build\datalad\tests\utils.py", line 349, in newfunc
    t(repo, *arg, **kw)
  File "c:\buildslave\datalad-tests-virtualbox-dl-win7-64\build\datalad\tests\utils.py", line 239, in newfunc
    t(*(arg + (filename,)), **kw)
  File "c:\buildslave\datalad-tests-virtualbox-dl-win7-64\build\datalad\tests\test_testrepos.py", line 38, in test_clone
    eq_(status, 0, msg="Status: %d  Output was: %r" % (status, output))
AssertionError: Status: 1  Output was: "'{' is not recognized as an internal or external command,\noperable program or batch file.
```
Message seems to be way off for figuring out WTF.  Reference:
http://smaug.datalad.org:8020/builders/datalad-tests-virtualbox-dl-win7-64/builds/3/steps/nosetests/logs/stdio

**Comment by bpoldrack** [comment]
You don't use the Runner-class in these tests, as far as I remember. You
call os.popen with someting like '{ ' +comands+ '} 2>&1' ....
Windows doesn't know what this means.

2015-03-16 20:52 GMT+01:00 Yaroslav Halchenko <notifications@github.com>:

**Comment by bpoldrack** [comment]
So, we need to refactor and clean up calls like this, redirecting it to Runner-class. (As we should anyway). I can take care of this.

**Comment by yarikoptic** [comment]
ah -- right -- great! thanks ;)

**Comment by yarikoptic** [comment]
I think they all would be gone after https://github.com/datalad/datalad/pull/78 is merged... and even now probably this specific one was already dealt with, just waasn't closed appropriately
