### ISSUE TITLE
c-s-github: existing="skip" -- errors out if sibling exists but remote not -- should it silently skip?

### ISSUE THREAD

**Issue by yarikoptic** [datalad/datalad#6723]
```
(git-annex)lena:/tmp/ds003233[master]
$> python -c 'import datalad.api as dl; print(dl.Dataset(".").create_sibling_github(reponame="ds003233-temp", existing="skip", name="github", access_protocol="https"))'
create_sibling_github(ok): [sibling repository 'github' created at https://github.com/yarikoptic/ds003233-temp]
configure-sibling(ok): . (sibling)
action summary:
  configure-sibling (ok: 1)
  create_sibling_github (ok: 1)
[{'action': 'create_sibling_github', ...

(git-annex)lena:/tmp/ds003233[master]
$> python -c 'import datalad.api as dl; print(dl.Dataset(".").create_sibling_github(reponame="ds003233-temp", existing="skip", name="github", access_protocol="https"))'
[{'action': 'create_sibling_github', 'path': '/tmp/ds003233', 'type': 'dataset', 'refds': '/tmp/ds003233', 'status': 'notneeded', 'message': ('already has a configured sibling "%s"', 'github')}]

$> git remote remove github

$> python -c 'import datalad.api as dl; print(dl.Dataset(".").create_sibling_github(reponame="ds003233-temp", existing="skip", name="github", access_protocol="https"))'
create_sibling_github(error): [A repository 'ds003233-temp' already exists at 'https://api.github.com', use existing=reconfigure to use it as a sibling]
Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "/home/yoh/proj/datalad/datalad-master/datalad/distribution/dataset.py", line 502, in apply_func
    return f(*args, **kwargs)
  File "/home/yoh/proj/datalad/datalad-master/datalad/interface/utils.py", line 447, in eval_func
    return return_func(*args, **kwargs)
  File "/home/yoh/proj/datalad/datalad-master/datalad/interface/utils.py", line 439, in return_func
    results = list(results)
  File "/home/yoh/proj/datalad/datalad-master/datalad/interface/utils.py", line 424, in generator_func
    raise IncompleteResultsError(
datalad.support.exceptions.IncompleteResultsError: Command did not complete successfully. 1 failed:
[{'action': 'create_sibling_github',
  'message': ("A repository '%s' already exists at '%s', use "
              'existing=reconfigure to use it as a sibling',
              'ds003233-temp',
              'https://api.github.com'),
  'preexisted': True,
  'refds': '/tmp/ds003233',
  'status': 'error'}]
```

I just wonder if that is "expected" behavior or what expected best behavior could be?  to some degree I would have expected it to skip but case here is tricky -- we have sibling create but not git remote configured.  Having it errored out allowed me to investigate and rerun with 'reconfigure' but it required changing of a script/library which interfaces datalad.

**Comment by adswa** [comment]
Mhhh I agree the case is tricky, but I don't think that silently skipping is expected behavior for me either. For some reason (might well be my own user error) I've regarded the ``--existing`` mode to mostly refer to local dataset configs (i.e., the configured git remotes) - personally, I would expect a silent skip (well, notneeded result) in the case that my dataset has a remote ``github`` configured and I'm trying to add another one (i.e., consistent with the first two examples).
Until your issue prompted me to look into the sourcecode I didn't know that the ``--existing`` mode had an effect on command behavior also in light of the Github repo (I falsely assumed we would always error when an existing repo name was given - in that sense, I found it reasonable for the command to error upon finding a preexisting github repo).
