### ISSUE TITLE
Failing tests with git annex version: 10.20220624

### ISSUE THREAD

**Issue by christian-monch** [datalad/datalad#6778]
### What is the problem?

The test

`datalad/local/tests/test_add_archive_content.py::TestAddArchiveOptions::test_add_archive_leading_dir`

fails with git annex version `10.20220624`

### What steps will reproduce the problem?

Install git annex version 10.20220624, and execute the test

```
> git clone https://github.com/datalad/datalad.git
> cd datalad
> pip install --upgrade pip
> pip install -r requirements-devel.txt
> python -m nose datalad/local/tests/test_add_archive_content.py:TestAddArchiveOptions.test_add_archive_leading_dir
```

Will yield something like:

```
======================================================================
ERROR: datalad.local.tests.test_add_archive_content.TestAddArchiveOptions.test_add_archive_leading_dir
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/cristian/venv/datalad-python3.9/lib/python3.9/site-packages/nose/case.py", line 198, in runTest
    self.test(*self.arg)
  File "/home/cristian/Develop/datalad/datalad/local/tests/test_add_archive_content.py", line 522, in test_add_archive_leading_dir
    self.ds.save(message="renamed")
  File "/home/cristian/Develop/datalad/datalad/distribution/dataset.py", line 502, in apply_func
    return f(*args, **kwargs)
  File "/home/cristian/Develop/datalad/datalad/interface/utils.py", line 447, in eval_func
    return return_func(*args, **kwargs)
  File "/home/cristian/Develop/datalad/datalad/interface/utils.py", line 439, in return_func
    results = list(results)
  File "/home/cristian/Develop/datalad/datalad/interface/utils.py", line 357, in generator_func
    for r in _process_results(
  File "/home/cristian/Develop/datalad/datalad/interface/utils.py", line 544, in _process_results
    for res in results:
  File "/home/cristian/Develop/datalad/datalad/core/local/save.py", line 390, in __call__
    yield from ProducerConsumerProgressLog(
  File "/home/cristian/Develop/datalad/datalad/support/parallel.py", line 535, in __iter__
    for res in super().__iter__():
  File "/home/cristian/Develop/datalad/datalad/support/parallel.py", line 265, in __iter__
    yield from self._iter_threads(self._jobs)
  File "/home/cristian/Develop/datalad/datalad/support/parallel.py", line 417, in _iter_threads
    self.shutdown(force=True, exception=self._producer_exception or interrupted_by_exception)
  File "/home/cristian/Develop/datalad/datalad/support/parallel.py", line 233, in shutdown
    raise exception
  File "/home/cristian/Develop/datalad/datalad/support/parallel.py", line 401, in _iter_threads
    done_useful |= self._pop_done_futures(lgr)
  File "/home/cristian/Develop/datalad/datalad/support/parallel.py", line 463, in _pop_done_futures
    raise exception
  File "/usr/lib64/python3.9/concurrent/futures/thread.py", line 58, in run
    result = self.fn(*self.args, **self.kwargs)
  File "/home/cristian/Develop/datalad/datalad/support/parallel.py", line 329, in consumer_worker
    for r in res:
  File "/home/cristian/Develop/datalad/datalad/core/local/save.py", line 309, in save_ds
    for res in pds_repo.save_(
  File "/home/cristian/Develop/datalad/datalad/support/gitrepo.py", line 3465, in save_
    yield from self._save_add(
  File "/home/cristian/Develop/datalad/datalad/support/annexrepo.py", line 3501, in _save_add
    for r in self._call_annex_records(
  File "/home/cristian/Develop/datalad/datalad/support/annexrepo.py", line 1079, in _call_annex_records
    raise e
  File "/home/cristian/Develop/datalad/datalad/support/annexrepo.py", line 1043, in _call_annex_records
    out = self._call_annex(
  File "/home/cristian/Develop/datalad/datalad/support/annexrepo.py", line 939, in _call_annex
    return runner.run_on_filelist_chunks(
  File "/home/cristian/Develop/datalad/datalad/runner/gitrunner.py", line 222, in run_on_filelist_chunks
    for res in self._get_chunked_results(cmd=cmd,
  File "/home/cristian/Develop/datalad/datalad/runner/gitrunner.py", line 156, in _get_chunked_results
    yield self.run(
  File "/home/cristian/Develop/datalad/datalad/runner/runner.py", line 201, in run
    raise CommandError(
datalad.runner.exception.CommandError: CommandError: 'git -c diff.ignoreSubmodules=none annex add --json --json-error-messages -c annex.dotfiles=true -- sub/123.tar' failed with exitcode 1 under /tmp/datalad_temp_tree_setupdlb1lb8u [info keys: stdout_json]
>git-annex: sub/123.tar: rename: does not exist (No such file or directory) [err: 'add: 1 failed']
```

Although `sub/123.tar` exists, it is a link to a non-existing annex-object. The call that fails is `self.ds.save(message="renamed")`.

### Datalad information

(on branch `maint`)

datalad 0.16.6+7.gbac08c85f

**Comment by adswa** [comment]
I touched that code base a bit recently-ish, although I let those old tests basically completely intact. Looking at it briefly, I have a suspicion that it is not `add_archive_content` specific, but rather that ```self.annex.remove('1.tar', force=True)``` is a good candidate for investigation. The remove method looks ancient (untouched since 2016) and has ``normalize_paths``. I don't know for sure if there are more modern helpers to remove annex content from datasets in the code base, can @mih or @yarikoptic or @bpoldrack hint towards them, should they exist?

**Comment by christian-monch** [comment]
Thx for the input, will have a look at it and wait for further comments from the gang that you mentioned. It nothing moves forward, I will add a skip to keep CI going.

**Comment by adswa** [comment]
I'd personally not yet add a skip-ci to that test, too high is the likelihood that this will slip everyone's mid- or post-Covid attention. It might point to important internal changes, or give us the chance to RIP another normalize_path method more. If it happens across the board and is unrelated to changes in PRs, I'd say they can go forward without disabling the test entirely.

**Comment by yarikoptic** [comment]
FTR  -- this test fails since cron-20220615 build:
```
$> git grep test_add_archive_leading_dir.*ERR | head -n 1
cron-20220615/build-macos.yaml-724-90215d4e-failed/2_test-datalad (maint).txt:2022-06-15T04:37:21.8712920Z datalad.local.tests.test_add_archive_content.TestAddArchiveOptions.test_add_archive_leading_dir ... ERROR
```
and that was the git-annex version:
```
$> grep '10\.2022' cron-20220615/build-macos.yaml-724-90215d4e-failed/2_test-datalad*
2022-06-15T02:39:40.4669690Z   name: git-annex-macos-dmg_10.20220525+git96-gf259be7f3_x64
2022-06-15T02:39:40.5373650Z Starting download for git-annex-macos-dmg_10.20220525+git96-gf259be7f3_x64
...
```
and prior build:

```
$> grep '10\.2022' cron-20220614/build-macos.yaml-*/2_test-datalad*        
2022-06-14T02:33:50.4326850Z   name: git-annex-macos-dmg_10.20220525+git81-g8916c818b_x64
2022-06-14T02:33:50.5116370Z Starting download for git-annex-macos-dmg_10.20220525+git81-g8916c818b_x64
```

<details>
<summary>output of  git log 10.20220525+git81-g8916c818b..10.20220525+git96-gf259be7f3 </summary> 

```shell
commit f259be7f39d6c1746b6b809f15b9a227624a0cd8
Author: Joey Hess <id@joeyh.name>
Date:   Tue Jun 14 16:38:34 2022 -0400

    fix overwrite race with small file that got large
    
    When adding a small file, it does not get locked down, so can be modified
    after git-annex checks that it's small. The use of queued git add made the
    race window nice and wide too.
    
    Fixed by checking if the file has changed, and by not using git add.
    Instead, have to recapitulate git add's handling of things like symlinks
    and executable files.
    
    Sponsored-by: Jochen Bartl on Patreon

commit 56e095aaf400601315aaf17662ef906fffca1ec0
Merge: 78a3d44ea 60a02af85
Author: Joey Hess <id@joeyh.name>
Date:   Tue Jun 14 14:56:16 2022 -0400

    Merge branch 'master' of ssh://git-annex.branchable.com

commit 60a02af8569171f2f09837b5537a3b46b89e7e44
Author: yarikoptic <yarikoptic@web>
Date:   Tue Jun 14 18:47:25 2022 +0000

    Added a comment: hold it... ;)

commit 78a3d44ea0a3a32699ddd7b2b5cb7cf2c5150ce7
Author: Joey Hess <id@joeyh.name>
Date:   Tue Jun 14 14:40:55 2022 -0400

    get rid of racy addLink
    
    The remaining callers all did not rely on it checking gitignore, so were
    easy to convert.
    
    They were susceptable to the same overwrite race as add and fix,
    although less likely to have it and a narrower window than add's race.
    
    Command.Rekey in passing got an unncessary call to removeFile deleted.
    addSymlink handles deleting any existing worktree file.

commit 7ace804d8e287432c4c77f27e2a792bad0b90cd5
Author: Joey Hess <id@joeyh.name>
Date:   Tue Jun 14 14:30:12 2022 -0400

    avoid writing same symlink twice in a row
    
    Oddly, the second write did not cause it to lose the mtime inherited
    from the file being added, although the mtime was not provided to that
    write but only to the first. I don't quite know why that worked before!

commit 64c7f60f7a11dd0db206bbdc3d8d4cfc6afecc1d
Author: Joey Hess <id@joeyh.name>
Date:   Tue Jun 14 14:19:58 2022 -0400

    fixed overwrite race with git-annex fix
    
    Similar to git-annex add, git-annex fix queued git add, so if a file
    got modified before git add ran, the wrong content would be staged,
    perhaps a large file content.
    
    Sponsored-by: Brock Spratlen on Patreon

commit e47219bcb5c210e908fcf390eb01dc96f85cd548
Author: Joey Hess <id@joeyh.name>
Date:   Tue Jun 14 14:13:48 2022 -0400

    bug report

commit 5ef79125ad0eddd5467b6bec451fdcdbd748b96f
Author: Joey Hess <id@joeyh.name>
Date:   Tue Jun 14 13:56:17 2022 -0400

    fix overwrite race with git-annex add of annex symlink
    
    In the unlikely case where git-annex add is run on an annex symlink that
    is not already added, and while it's processing it, the annex symlink is
    overwritten with something else, avoid git-annex overwriting that with
    the symlink again.
    
    Sponsored-by: Jack Hill on Patreon

commit dd6dec4eb1ae7dbd4bde1a3434ff97517361e4f7
Author: Joey Hess <id@joeyh.name>
Date:   Tue Jun 14 13:20:42 2022 -0400

    fix add overwrite race with git-annex add to annex
    
    This is not a complete fix for all such races, only the one where a
    large file gets changed while adding and gets added to git rather than
    to the annex.
    
    addLink needs to go away, any caller of it is probably subject to the
    same kind of race. (Also, addLink itself fails to check gitignore when
    symlinks are not supported.)
    
    ingestAdd no longer checks gitignore. (It didn't check it consistently
    before either, since there were cases where it did not run git add!)
    When git-annex import calls it, it's already checked gitignore itself
    earlier. When git-annex add calls it, it's usually on files found
    by withFilesNotInGit, which handles checking ignores.
    
    There was one other case, when git-annex add --batch calls it. In that
    case, old git-annex behaved rather badly, it would seem to add the file,
    but git add would later fail, leaving the file as an unstaged annex symlink.
    That behavior has also been fixed.
    
    Sponsored-by: Brett Eisenberg on Patreon

commit b471438c51036c3cc69ecec0977a10fc791d4e78
Author: Joey Hess <id@joeyh.name>
Date:   Tue Jun 14 12:51:04 2022 -0400

    bug report
    
    Sponsored-by: Luke Shumaker on Patreon

commit b9e9ad1ffb842e01b5ce32a577d55bfef2a3b008
Author: Joey Hess <id@joeyh.name>
Date:   Tue Jun 14 12:23:33 2022 -0400

    comment

commit f7552e4e288162ef4f8fbf8d36ca002e6e5b1bd0
Merge: 596ead85a 216a78a3e
Author: Joey Hess <id@joeyh.name>
Date:   Tue Jun 14 11:51:44 2022 -0400

    Merge branch 'master' of ssh://git-annex.branchable.com

commit 216a78a3e9846e69bb5b646a8b0a8e727138c5e1
Author: KachoOji <KachoOji@web>
Date:   Tue Jun 14 15:32:48 2022 +0000

    Added a comment

commit 596ead85a1489bad046d3ec3e648e78474a9772a
Author: Joey Hess <id@joeyh.name>
Date:   Mon Jun 13 16:04:12 2022 -0400

    add rf

commit 49ab46778407cb2dbb306b44a3a49054946096c9
Author: Joey Hess <id@joeyh.name>
Date:   Mon Jun 13 14:20:54 2022 -0400

    comment

```
</details>

so someone , or @joeyh could immediately see what has lead to this failure in our tests

**Comment by christian-monch** [comment]
@yarikoptic Thx for the input.

I am actually not sure about the purpose of the test, and whether its implementation serves the purpose. Maybe you can clarify and verify it?

The test creates an annex repo in a temporary location:
```
> tree
.
|-- 1.tar -> .git/annex/objects/4M/Zv/MD5E-s10240--5f7763582cf529b56ba494b5a1360bdd.tar/MD5E-s10240--5f7763582cf529b56ba494b5a1360bdd.tar
`-- sub
```

Then uses `mv` to move `1.tar` to `sub/123.tar`, leading to the following directory layout:
```
> tree
.
`-- sub
    `-- 123.tar -> .git/annex/objects/4M/Zv/MD5E-s10240--5f7763582cf529b56ba494b5a1360bdd.tar/MD5E-s10240--5f7763582cf529b56ba494b5a1360bdd.tar
```

That creates the following state for git:
``` 
> git status
On branch dl-test-branch
Changes not staged for commit:
  (use "git add/rm <file>..." to update what will be committed)
  (use "git restore <file>..." to discard changes in working directory)
        deleted:    1.tar

Untracked files:
  (use "git add <file>..." to include in what will be committed)
        sub/
```

the following state for git annex:
```
> git annex status
D ./1.tar
? ./sub/123.tar

```

and the following state for datalad
```
> datalad status
untracked: sub (directory)
  deleted: 1.tar (symlink)
```

In this state `AnnexRepo.remove('1.tar', force=True)`, leaving the dataset in the following state:
```shell
> git status
On branch dl-test-branch
Changes to be committed:
  (use "git restore --staged <file>..." to unstage)
        deleted:    1.tar

Untracked files:
  (use "git add <file>..." to include in what will be committed)
        sub/

> git annex status
D ./1.tar
? ./sub/123.tar
> datalad status
untracked: sub (directory)
  deleted: 1.tar (symlink)
```

In this state `Dataset.save(message="renamed")` is called, which in turn calls `git annex add`, which fails. More precisely:
```shell
> git -c diff.ignoreSubmodules=none annex add --json --json-error-messages -c annex.dotfiles=true -- sub/123.tar
{"command":"add","file":"sub/123.tar","input":["sub/123.tar"],"success":false,"error-messages":["git-annex: sub/123.tar: rename: does not exist (No such file or directory)"]}
add: 1 failed
```

My question is: what behavior is expected of `git annex` and why?

As a remark: `git annex add` would succeed, if the object that the link points to exists (more precisely, if `.git` is copied to `sub/.git`), or if `sub/123.tar` is not a dangling link, but, for example, a binary file.

**Comment by joeyh** [comment]
This is fixed in git-annex and it has a test case.

**Comment by yarikoptic** [comment]
indeed all good,
```
(git)lena:~datalad/datalad-maint[maint]git
$> git describe
0.17.2-80-g804b3c90f
(dev3) 1 44434 [2].....................................:Tue 16 Aug 2022 09:43:14 AM EDT:.
(git)lena:~datalad/datalad-maint[maint]git
$> python -m pytest -s -v -k test_add_archive_leading_dir
========================================== test session starts ===========================================
platform linux -- Python 3.10.5, pytest-7.1.2, pluggy-1.0.0 -- /home/yoh/proj/datalad/datalad-maint/venvs/dev3/bin/python
cachedir: .pytest_cache
rootdir: /home/yoh/proj/datalad/datalad-maint, configfile: tox.ini
plugins: fail-slow-0.2.0, cov-3.0.0, forked-1.4.0, xdist-2.5.0
collected 1303 items / 1302 deselected / 1 selected                                                      

datalad/local/tests/test_add_archive_content.py::TestAddArchiveOptions::test_add_archive_leading_dir create(ok): . (dataset)
add(ok): 1.tar (file)
save(ok): . (dataset)
action summary:
  add (ok: 1)
  save (ok: 1)
add(ok): sub/123.tar (file)
save(ok): . (dataset)
action summary:
  add (ok: 1)
  save (ok: 1)
add-archive-content(ok): /home/yoh/.tmp/datalad_temp_tree_9gl76_2c (dataset)
PASSEDVersions: annexremote=1.6.0 boto=2.49.0 cmd:7z=16.02 cmd:annex=10.20220724+git120-g7286f408f-1~ndall+1 cmd:bundled-git=2.30.2 cmd:git=2.30.2 cmd:ssh=9.0p1 cmd:system-git=2.35.1 cmd:system-ssh=9.0p1 datalad=0.17.2+80.g804b3c90f exifread=3.0.0 humanize=4.2.3 iso8601=1.0.2 keyring=23.6.0 keyrings.alt=UNKNOWN msgpack=1.0.4 mutagen=1.45.1 patoolib=1.12 platformdirs=2.5.2 requests=2.28.1 tqdm=4.64.0
Obscure filename: str=b' |;&%b5{}\'"<>\xce\x94\xd0\x99\xd7\xa7\xd9\x85\xe0\xb9\x97\xe3\x81\x82 .datc ' repr=' |;&%b5{}\'"<>ΔЙקم๗あ .datc '
Encodings: default='utf-8' filesystem='utf-8' locale.prefered='UTF-8'
Environment: PATH='/home/yoh/proj/datalad/datalad-maint/venvs/dev3/bin:/home/yoh/gocode/bin:/home/yoh/gocode/bin:/home/yoh/bin:/home/yoh/.local/bin:/usr/local/bin:/usr/bin:/bin:/usr/local/games:/usr/games:/sbin:/usr/sbin:/usr/local/sbin' LANG='en_US.UTF-8' GIT_PAGER='less --no-init --quit-if-one-screen' GIT_CONFIG_PARAMETERS="'init.defaultBranch=dl-test-branch' 'clone.defaultRemoteName=dl-test-remote'" GIT_ASKPASS='true'


=================================== 1 passed, 1302 deselected in 5.11s
```
thank you @joeyh
