### ISSUE TITLE
various tests fail under Windows

### ISSUE THREAD

**Issue by yarikoptic** [datalad/datalad#68]
This is just a placeholder to point to the problem of failing tests (such as #67) on Windows.  Some of them are due to max path length limit (#58) but there might be more.  Just requires a thorough pass
Reference: http://smaug.datalad.org:8020/builders/datalad-tests-virtualbox-dl-win7-64/builds/3/steps/nosetests/logs/stdio

**Comment by bpoldrack** [comment]
So, let's make a list of identified issues. I'm working on this right now, it's just about narrowing it down and adding issues as they appear.

1. We still have unix-style command calls, due to not using the Runner-class
2. path length problems. Partly solved.
3. If you look at this:

======================================================================
FAIL: datalad.tests.test_kraut.TestKrautTests.test_get_basic_minimal
----------------------------------------------------------------------
_StringException: Binary content:
  dep_info (application/json)
  env_info (application/json)
  exec_info (application/json)
  metric_info (application/json)
  output_info (application/json)
  spec_info (application/json)
  sys_info (application/json)

Traceback (most recent call last):
  File "c:\buildslave\datalad-tests-virtualbox-dl-win7-64\build\testkraut\testcase.py", line 68, in wrapped
    return func(self, *(args + parameters), **kw)
  File "c:\buildslave\datalad-tests-virtualbox-dl-win7-64\build\testkraut\testcase.py", line 718, in _run_spec_test
    return TestFromSPEC._run_spec_test(self, spec_filename)
  File "c:\buildslave\datalad-tests-virtualbox-dl-win7-64\build\testkraut\testcase.py", line 209, in _run_spec_test
    self._check_output_presence(spec)
  File "c:\buildslave\datalad-tests-virtualbox-dl-win7-64\build\testkraut\testcase.py", line 465, in _check_output_presence
    matcher(target)))
  File "C:\Python27\lib\site-packages\testtools\testcase.py", line 433, in assertThat
    raise mismatch_error
MismatchError: '''\
\r
\r
\r
(merging origin/git-annex into git-annex...)\r
(recording state in git...)\r
\r
get test-annex.dat \r
(from web...) \r
\r
  Unable to access these remotes: web\r
\r
  Try making some of these repositories available:\r
  \t00000000-0000-0000-0000-000000000001 -- web\r
failed\r
(recording state in git...)\r
''' does not end with u'''\
ecording state in git...)
'''.: unexpected output for 'tests::0::stdout'


This seems to be a problem with conversion of line endings or better it's absence.

4. Some tests ignore that there's a direct mode. So a not yet getted file is not a link, but an actual file. Checking for "not exists" before, is just wrong in direct mode.

5. Message below seems to be a problem not connected to windows and already resolved, right?

======================================================================
FAIL: datalad.tests.test_cmd.test_link_file_load
----------------------------------------------------------------------
Traceback (most recent call last):
  File "C:\Python27\lib\site-packages\nose\case.py", line 197, in runTest
    self.test(*self.arg)
  File "c:\buildslave\datalad-tests-virtualbox-dl-win7-64\build\datalad\tests\utils.py", line 239, in newfunc
    t(*(arg + (filename,)), **kw)
  File "c:\buildslave\datalad-tests-virtualbox-dl-win7-64\build\datalad\tests\test_cmd.py", line 189, in test_link_file_load
    assert_equal(stats(tempfile), stats(tempfile2))
AssertionError: Tuples differ: (33206, 0, 0, 4L, 1426535023.6... != (33206, 0, 0, 4L, 1426535023.6...

First differing element 4:
1426535023.62
1426535023.62

- (33206, 0, 0, 4L, 1426535023.618778)
?                                   ^

+ (33206, 0, 0, 4L, 1426535023.618777)
?                                   ^


6. Have to adapt obscure filenames

7. Look at this:

======================================================================
ERROR: datalad.tests.test_main.test_page2annex_separate_public(True, 'relaxed', 'keep')
----------------------------------------------------------------------
Traceback (most recent call last):
  File "C:\Python27\lib\site-packages\nose\case.py", line 197, in runTest
    self.test(*self.arg)
  File "c:\buildslave\datalad-tests-virtualbox-dl-win7-64\build\datalad\tests\utils.py", line 103, in newfunc
    t(*((d,) + arg), **kw)
  File "c:\buildslave\datalad-tests-virtualbox-dl-win7-64\build\datalad\tests\utils.py", line 188, in newfunc
    func(*((url,)+arg), **kw_)
  File "c:\buildslave\datalad-tests-virtualbox-dl-win7-64\build\datalad\tests\test_main.py", line 151, in check_page2annex_separate_public
    stats1 = drepo.page2annex()
  File "c:\buildslave\datalad-tests-virtualbox-dl-win7-64\build\datalad\crawler\main.py", line 306, in page2annex
    git_add=git_add,
  File "c:\buildslave\datalad-tests-virtualbox-dl-win7-64\build\datalad\support\repos.py", line 259, in annex_file
    public_annex.add_file(public_filename, href=href, add_mode=add_mode, git_add=git_add)
  File "c:\buildslave\datalad-tests-virtualbox-dl-win7-64\build\datalad\support\repos.py", line 110, in add_file
    return self.run(_esc(annex_filename), git_cmd="add")
  File "c:\buildslave\datalad-tests-virtualbox-dl-win7-64\build\datalad\support\repos.py", line 51, in run
    "cd %s && git %s %s" % (self.path, git_cmd, cmd))
  File "c:\buildslave\datalad-tests-virtualbox-dl-win7-64\build\datalad\cmd.py", line 173, in run
    raise RuntimeError(msg)
RuntimeError: Failed to run u'cd c:\\users\\datalad\\appdata\\local\\temp\\tmpu3d2t5 && git add "files\\test.ascii"'. Exit code=128

There is no "git add" in direct mode, I think. Because there is no working tree. We have to adapt tests like this in general, to not call any command directly, but the annex or dataset methods. So, these classes know they are in direct mode and can act accordingly.

**Comment by yarikoptic** [comment]
```test_main``` tests disabled, some other fixed up. Amen for now
