### ISSUE TITLE
datalad error on branching git config

### ISSUE THREAD

**Issue by progtw** [datalad/datalad#6815]
### What is the problem?

datalad errors when a directive such as the following is presetn in .gitconfig:

```
[includeIf "gitdir:**/devbgc/**"]
    path = ~/.gitconfig_bgc
```

With error that is confusing novice users:

```
(base) twutz@macadamia tmp> datalad --version
Traceback (most recent call last):
  File "/User/homes/twutz/scratch/twutz/miniconda3/bin/datalad", line 7, in <module>
    from datalad.cmdline.main import main
  File "/User/homes/twutz/scratch/twutz/miniconda3/lib/python3.8/site-packages/datalad/__init__.py", line 110, in <module>
    cfg = ConfigManager()
  File "/User/homes/twutz/scratch/twutz/miniconda3/lib/python3.8/site-packages/datalad/config.py", line 394, in __init__
    self.reload(force=True)
  File "/User/homes/twutz/scratch/twutz/miniconda3/lib/python3.8/site-packages/datalad/config.py", line 469, in reload
    self._stores[store_id] = self._reload(runargs)
  File "/User/homes/twutz/scratch/twutz/miniconda3/lib/python3.8/site-packages/datalad/config.py", line 497, in _reload
    stdout, stderr = self._run(
  File "/User/homes/twutz/scratch/twutz/miniconda3/lib/python3.8/site-packages/datalad/config.py", line 878, in _run
    out = self._runner.run(self._config_cmd + args, **kwargs)
  File "/User/homes/twutz/scratch/twutz/miniconda3/lib/python3.8/site-packages/datalad/runner/runner.py", line 201, in run
    raise CommandError(
datalad.runner.exception.CommandError: CommandError: 'git --git-dir= config -z -l --show-origin' failed with exitcode 128 [err: 'fatal: The empty string is not a valid path']

```

### What steps will reproduce the problem?

- include a git directive such as above
- run `datalad --version`

### Datalad information

-     datalad version 0.16.5
-     linuxmint/20.2/uma, release 5.4.0-121-generic
-     git annex version: 10.20220525-gf1fdc90
-     git version 2.34.1

### Additional context

My usual .gitconfig is set so that I use a different name, email and certificates in work-related projects (in specific folders) versus private projects.

First reported in  [neurostars question](https://neurostars.org/t/beginners-problem-with-datalad/22995)

### Have you had any success using DataLad before?

I was quite disappointed by this unlucky first encounter with datalad. However, by just reading along the 101 tutorial I am impressed by your work. Thanks.

**Comment by yarikoptic** [comment]
note: providing some bogus value (instead of an empty string) seems to mitigate the situation:

```
$> git --git-dir=/really-not-there config -l | grep '^branch\.'
```
works fine.  I will *quickly* run by git folks
