### ISSUE TITLE
should problematic extension  cause overall disfunction of datalad core?

### ISSUE THREAD

**Issue by yarikoptic** [datalad/datalad#6844]
I feel like we had such issue filed but I failed to find it.

```shell
(dandisets) dandi@drogon:/tmp$ datalad -l debug --dbg -c datalad.repo.backend=SHA256E create -c text2git buga
[DEBUG  ] Command line args 1st pass for DataLad 0.17.0. Parsed: Namespace(cfg_overrides=['datalad.repo.backend=SHA256E', 'text2git'], common_debug=True) Unparsed: ['create', 'buga']
[DEBUG  ] Building doc for <class 'datalad.core.local.create.Create'>
[DEBUG  ] Parsing known args among ['/home/dandi/miniconda3/envs/dandisets/bin/datalad', '-l', 'debug', '--dbg', '-c', 'datalad.repo.backend=SHA256E', 'create', '-c', 'text2git', 'buga']
...
[DEBUG  ] Building doc for <class 'datalad.interface.shell_completion.ShellCompletion'>
[DEBUG  ] Processing entrypoints
[DEBUG  ] Loading entrypoint crawler from datalad.extensions
[WARNING] Failed to load entrypoint crawler from datalad.extensions: ModuleNotFoundError(No module named 'pytest')
[DEBUG  ] Loading entrypoint deprecated from datalad.extensions
[DEBUG  ] Building doc for <class 'datalad_deprecated.ls.Ls'>
[DEBUG  ] Loaded entrypoint deprecated from datalad.extensions
[DEBUG  ] Done processing entrypoints
[DEBUG  ] Determined class of decorated function: <class 'datalad.local.run_procedure.RunProcedure'>
[DEBUG  ] Run ['git', '--git-dir=', 'config', '-z', '-l', '--show-origin'] (cwd=None)
[DEBUG  ] Finished ['git', '--git-dir=', 'config', '-z', '-l', '--show-origin'] with status 0
[DEBUG  ] Resolved dataset to run a procedure: /tmp/buga
[DEBUG  ] Looking for procedure '*' in '/home/dandi/.config/datalad/procedures'
[DEBUG  ] Looking for procedure '*' in '/etc/xdg/datalad/procedures'
[DEBUG  ] Processing entrypoints
Traceback (most recent call last):
  File "/home/dandi/miniconda3/envs/dandisets/lib/python3.8/site-packages/pkg_resources/__init__.py", line 356, in get_provider
    module = sys.modules[moduleOrReq]
KeyError: 'datalad_crawler'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/dandi/miniconda3/envs/dandisets/bin/datalad", line 8, in <module>
    sys.exit(main())
  File "/home/dandi/miniconda3/envs/dandisets/lib/python3.8/site-packages/datalad/cli/main.py", line 140, in main
    _run(cmdlineargs)
  File "/home/dandi/miniconda3/envs/dandisets/lib/python3.8/site-packages/datalad/cli/main.py", line 164, in _run
    ret = _run_with_debugger(namespace) \
  File "/home/dandi/miniconda3/envs/dandisets/lib/python3.8/site-packages/datalad/cli/main.py", line 177, in _run_with_debugger
    return cmdlineargs.func(cmdlineargs)
  File "/home/dandi/miniconda3/envs/dandisets/lib/python3.8/site-packages/datalad/cli/exec.py", line 107, in call_from_parser
    ret = list(ret)
  File "/home/dandi/miniconda3/envs/dandisets/lib/python3.8/site-packages/datalad/interface/utils.py", line 357, in generator_func
    for r in _process_results(
  File "/home/dandi/miniconda3/envs/dandisets/lib/python3.8/site-packages/datalad/interface/utils.py", line 544, in _process_results
    for res in results:
  File "/home/dandi/miniconda3/envs/dandisets/lib/python3.8/site-packages/datalad/core/local/create.py", line 355, in __call__
    for discovered_proc in discovered_procs:
  File "/home/dandi/miniconda3/envs/dandisets/lib/python3.8/site-packages/datalad/interface/utils.py", line 357, in generator_func
    for r in _process_results(
  File "/home/dandi/miniconda3/envs/dandisets/lib/python3.8/site-packages/datalad/interface/utils.py", line 544, in _process_results
    for res in results:
  File "/home/dandi/miniconda3/envs/dandisets/lib/python3.8/site-packages/datalad/local/run_procedure.py", line 350, in __call__
    for m, cmd_name, cmd_tmpl, cmd_help in \
  File "/home/dandi/miniconda3/envs/dandisets/lib/python3.8/site-packages/datalad/local/run_procedure.py", line 157, in _get_procedure_implementation
    if resource_isdir(epmodule, 'resources/procedures'):
  File "/home/dandi/miniconda3/envs/dandisets/lib/python3.8/site-packages/pkg_resources/__init__.py", line 1148, in resource_isdir
    return get_provider(package_or_requirement).resource_isdir(
  File "/home/dandi/miniconda3/envs/dandisets/lib/python3.8/site-packages/pkg_resources/__init__.py", line 358, in get_provider
    __import__(moduleOrReq)
  File "/home/dandi/miniconda3/envs/dandisets/lib/python3.8/site-packages/datalad_crawler/__init__.py", line 33, in <module>
    import datalad.tests.utils
  File "/home/dandi/miniconda3/envs/dandisets/lib/python3.8/site-packages/datalad/tests/utils.py", line 79, in <module>
    from datalad import (
  File "/home/dandi/miniconda3/envs/dandisets/lib/python3.8/site-packages/datalad/conftest.py", line 5, in <module>
    import pytest
ModuleNotFoundError: No module named 'pytest'

> /home/dandi/miniconda3/envs/dandisets/lib/python3.8/site-packages/datalad/conftest.py(5)<module>()
-> import pytest
(Pdb) c
(dandisets) dandi@drogon:/tmp$ datalad --version
datalad 0.17.0
(dandisets) dandi@drogon:/tmp$ 
```

datalad-crawler pip installed in that conda env and of version `0.9.3` .

so no commands from datalad-crawler were used but it managed to "crash" `datalad create` command.

- also related -- are will allowing for extensions to "overload" our procedures in the core?  since if not, there were no need to even try to load them from extensions here.  If we do - the question is then what should we do here since then the overload might not happen and one logical behavior is this -- just error out. The other -- to skip with a warning.  I would vote for latter but there might be arguments for former.

**Comment by mih** [comment]
The issue title poses a grand question. The failure seems to happen on a smaller scale: `run-procedure --discover` finds the `crawler` extension to be installed and assumes it to be importable for getting a list of its procedures.

I suggest that `run-procedure` should be altered to ignore broken extensions.
