### ISSUE TITLE
datalad.api.get not working with dataset keyword argument but works fine when changing working directory using os.chdir

### ISSUE THREAD

**Issue by JohannesWiesner** [datalad/datalad#6908]
### What is the problem?

When trying to install subdatasets, I get the following error:

```
runfile('/home/johannes.wiesner/datalad_download_resting_state.py', wdir='/home/johannes.wiesner')
get(error): /home/johannes.wiesner/HCP1200/100206 [path not associated with dataset Dataset(/home/johannes.wiesner/hcp)]
Traceback (most recent call last):

  File "/csp-tools/anaconda3/envs/dl/lib/python3.9/site-packages/spyder_kernels/py3compat.py", line 356, in compat_exec
    exec(code, globals, locals)

  File "/home/johannes.wiesner/datalad_download_resting_state.py", line 29, in <module>
    get(dataset='/home/johannes.wiesner/hcp',

  File "/csp-tools/anaconda3/envs/dl/lib/python3.9/site-packages/datalad/interface/utils.py", line 447, in eval_func
    return return_func(*args, **kwargs)

  File "/csp-tools/anaconda3/envs/dl/lib/python3.9/site-packages/datalad/interface/utils.py", line 439, in return_func
    results = list(results)

  File "/csp-tools/anaconda3/envs/dl/lib/python3.9/site-packages/datalad/interface/utils.py", line 424, in generator_func
    raise IncompleteResultsError(

IncompleteResultsError: Command did not complete successfully. 1 failed:
[{'action': 'get',
  'message': ('path not associated with dataset %s',
              Dataset('/home/johannes.wiesner/hcp')),
  'path': '/home/johannes.wiesner/HCP1200/100206',
  'status': 'error'}]
```

### What steps will reproduce the problem?

When I use the `dataset` keyword argument, I get the error above:

```
from datalad.api import install
from datalad.api import get

# install the Human Connectome Project dataset as a datalad dataset
install(source='https://github.com/datalad-datasets/human-connectome-project-openaccess.git',
        path='./hcp')

# install subdataset
get(dataset='/home/johannes.wiesner/hcp',path='./HCP1200/100206',get_data=False,recursive=True)
```

However, when I simply skip the `dataset` argument and change the working directory using `os.chdir`, everything works fine:

```
# this works
os.chdir('/home/johannes.wiesner/hcp')
get(path='./HCP1200/100206',
    get_data=False,recursive=True)
```

### Datalad information

Datalad version is : 0.16.3
OS is: linuxmint/19.3/tricia

**Comment by adswa** [comment]
Thanks for the detailed report and reproducer. I can reproduce this. 
I think its a deficiency in documentation and maybe functionality of [``resolve_path``](https://github.com/datalad/datalad/blob/1ccf79623aebfe8fdb04a6bb374436522b1d172e/datalad/distribution/dataset.py#L605)

```
(Pdb) p contains
'HCP1200/100307/'
(Pdb) p dataset
'/tmp/hcp'
> /home/adina/repos/datalad/datalad/local/subdatasets.py(265)__call__()
-> if contains:
(Pdb) 
> /home/adina/repos/datalad/datalad/local/subdatasets.py(266)__call__()
-> contains = resolve_path(ensure_list(contains), dataset, ds)
(Pdb) p contains
[PosixPath('/tmp/HCP1200/100307')]
```

The docstrings of [``resolve_path``](https://github.com/datalad/datalad/blob/1ccf79623aebfe8fdb04a6bb374436522b1d172e/datalad/distribution/dataset.py#L605) suggests that it just can't handle the situation where the dataset is a string and the path is relative to that dataset. I think it either needs to learn how to do this, or we need to improve the documentation.

>   Any path is returned as an absolute path. If, and only if, a dataset
    object instance is given as `ds`, relative paths are interpreted as
    relative to the given dataset. In all other cases, relative paths are
    treated as relative to the current working directory.

So in your case, one of two alternatives works:

1) Use a Dataset object instead of a string:
```python
In [1]: from datalad.api import install, get, Dataset
In [2]: ds = Dataset('/tmp/hcp')
In [3]: get(dataset=ds, path='HCP1200/100307' ,get_data=False,recursive=True)
[INFO   ] Installing Dataset(/tmp/hcp/HCP1200/100307) to get /tmp/hcp/HCP1200/100307 recursively 
[INFO   ] scanning for annexed files (this may take some time) 
install(ok): /tmp/hcp/HCP1200/100307/MEG (dataset)                              
[INFO   ] scanning for annexed files (this may take some time)                  
install(ok): /tmp/hcp/HCP1200/100307/MNINonLinear (dataset)                     
install(ok): /tmp/hcp/HCP1200/100307/T1w (dataset)                              
install(ok): /tmp/hcp/HCP1200/100307/unprocessed (dataset)                      
action summary:                                                                 
  get (notneeded: 1)
  install (ok: 4)
```

2) or use a path relative to your current working directory (my PWD in both cases was ``/tmp``):

```python
In [4]: get(dataset='/tmp/hcp', path='/tmp/hcp/HCP1200/100408/' ,get_data=False,
   ...: recursive=True)
install(ok): /tmp/hcp/HCP1200/100408 (dataset) [Installed subdataset in order to get /tmp/hcp/HCP1200/100408]
[INFO   ] Installing Dataset(/tmp/hcp) to get /tmp/hcp/HCP1200/100408 recursively 
[INFO   ] scanning for annexed files (this may take some time)                  
install(ok): /tmp/hcp/HCP1200/100408/MNINonLinear (dataset)                     
install(ok): /tmp/hcp/HCP1200/100408/T1w (dataset)                              
install(ok): /tmp/hcp/HCP1200/100408/unprocessed (dataset)                      
action summary:                                                                 
  install (ok: 4)
```

**Comment by yarikoptic** [comment]
FWIW: I confirm that "In all other cases, relative paths are treated as relative to the current working directory." was conscious design decision so in the command line `-d DSPATH RELPATH` (where DSPATH passed as a string) RELPATH naturally considered relative to CWD, while in Python API `ds.get(RELPATH)` is considered relative to `ds.path`.

As such, and given that documentation is describing this behavior, I think we can close this issue.  But truly feel welcome to reopen if anyone considers otherwise.
