### ISSUE TITLE
Disambiguate PATHs and pathspecs in DataLad API/CLI

### ISSUE THREAD

**Issue by yarikoptic** [datalad/datalad#6933]
This issue is an extract from #6922 which would primarily concern with long list of files argument, but also might have more of relevant information.  

`--literal-pathspecs` git option  should be used whenever we are invoking `git` / `git-annex` command on a list of paths ( e.g. after our status/diff analysis etc).  But also in principle in our CLI/API we never promote `datalad` supporting `refspec`s but in effect supporting them at least to some, overall untested (see some usages below), degree.

I did a little experiment below and I think that we are not really supporting pathspecs and may be shouldn't pretend that we do? or if we do decide to support them, we would also need to add `--literal-pathspecs` option into our API/CLI to disambiguate.

```shell
/home/yoh/proj/datalad/datalad/docs > git diff --stat HEAD^^^ ':(top,glob)*.py'
 setup.py | 1 +
 1 file changed, 1 insertion(+)

/home/yoh/proj/datalad/datalad/docs > touch ':(top,glob)*.py'

/home/yoh/proj/datalad/datalad/docs > git status ':(top,glob)*.py'
HEAD detached at 7df694467
nothing to commit, working tree clean

/home/yoh/proj/datalad/datalad/docs > git --literal-pathspecs status ':(top,glob)*.py'
HEAD detached at 7df694467
Untracked files:
  (use "git add <file>..." to include in what will be committed)
	:(top,glob)*.py

nothing added to commit but untracked files present (use "git add" to track)

/home/yoh/proj/datalad/datalad/docs > datalad save -m 'do we save literal pathspec  or  pathspec?? ;)' ':(top,glob)*.py'      
[WARNING] Some elements of your dataset are not compatible with Windows systems. Disable this check by changing datalad.save.windows-compat-warning or consider renaming the following elements: 
| Elements with illegal characters: [':(top,glob)*.py'] 
add(ok): docs/:(top,glob)*.py (file)                                                                                                                   
save(ok): . (dataset)                                                                                                                                  
action summary:                                                                                                                                        
  add (ok: 1)
  save (ok: 1)

/home/yoh/proj/datalad/datalad/docs > git --literal-pathspecs log ':(top,glob)*.py'                               
commit 71e273484767b2330129cc6cadc06cde5d081151 (HEAD)
Author: Yaroslav Halchenko <debian@onerussian.com>
Date:   Wed Aug 10 16:27:48 2022 -0400

    do we save literal pathspec  or  pathspec?? ;)

/home/yoh/proj/datalad/datalad/docs > echo "so we saved literal pathspec"
so we saved literal pathspec
```

BUT ATM application of 
```patch
diff --git a/datalad/dataset/gitrepo.py b/datalad/dataset/gitrepo.py
index 3d1b210f7..7ce49eb78 100644
--- a/datalad/dataset/gitrepo.py
+++ b/datalad/dataset/gitrepo.py
@@ -104,7 +104,7 @@ class GitRepo(RepoInterface, metaclass=PathBasedFlyweight):
     """
     # Could be used to e.g. disable automatic garbage and autopacking
     # ['-c', 'receive.autogc=0', '-c', 'gc.auto=0']
-    _GIT_COMMON_OPTIONS = ["-c", "diff.ignoreSubmodules=none"]
+    _GIT_COMMON_OPTIONS = ["-c", "diff.ignoreSubmodules=none", "--literal-pathspecs"]
     _git_cmd_prefix = ["git"] + _GIT_COMMON_OPTIONS
 
     # Begin Flyweight:
```

immediately leads to some tests to error out because apparently we rely on conveniences like `repo.add('*')` which would work in CLI because shell would expand pathspec `*` as a glob.  Here is a quick grep for similar locations

```
$> git grep "('\*'"
benchmarks/common.py:        self.log("Setup ran in %s, existing paths: %s", getpwd(), glob('*'))
datalad/core/local/tests/test_save.py:        [('*', dict(mycustomthing='this'))],
datalad/core/local/tests/test_save.py:        ('*', {'annex.largefiles': 'nothing'})])
datalad/local/clean.py:                paths = [p for p in topdir.glob('*')]
datalad/local/run_procedure.py:                    _get_procedure_implementation('*', ds=ds):
datalad/metadata/metadata.py:            info_glob = op.join(ds.path, agginfo_relpath_template.format('*'))
datalad/resources/procedures/cfg_text2git.py:attrs = ds.repo.get_gitattributes('*')
datalad/resources/procedures/cfg_text2git.py:if not attrs.get('*', {}).get(
datalad/resources/procedures/cfg_text2git.py:        ('*', {'annex.largefiles': annex_largefiles})])
datalad/resources/procedures/cfg_yoda.py:ds.repo.set_gitattributes([('*', {'annex.largefiles': 'nothing'})],
datalad/support/annexrepo.py:                    [('*', {'annex.backend': backend})],
datalad/support/tests/test_gitrepo.py:    gr.add('*')
datalad/support/tests/test_gitrepo.py:    eq_(set(gr.remove('*', r=True, f=True)), {'file2', 'd2/f1', 'd2/f2'})
datalad/support/tests/test_gitrepo.py:    repo.add('*')
datalad/support/tests/test_gitrepo.py:    repo.add('*')
datalad/support/tests/test_gitrepo.py:    repo.add('*')
datalad/support/tests/test_gitrepo.py:    gr.set_gitattributes([('*', {'tag': True}), ('*', {'sec.key': 'val'})])
datalad/support/tests/test_gitrepo.py:    gr.set_gitattributes([('*', {'tag': False})])
datalad/support/tests/test_gitrepo.py:    gr.set_gitattributes([('*', {'king': 'kong'})], mode='a')
datalad/support/tests/test_gitrepo.py:    gr.set_gitattributes([('*', {'ding': 'dong'})], mode='a')
``` 

So, the main decision to make is first to decide on either we should add documented/tested support of `pathspecs` in our API?! 

If we decide to not bother, we could just go with aforementioned patch and fix up some tests to avoid `'*'` pathspec.

**Comment by yarikoptic** [comment]
While looking at #7013 -- `drop` is not taking in pathspecs:

```shell
> datalad drop --what all --reckless kill -r '*'
drop(error): * (file) [File unknown to git]
```

so we might need to check all commands and come to consensus.

**Comment by yarikoptic** [comment]
- check for a way to do type annotation where we explicitly separate PATH vs PATHSPEC, and start annotating code - nobody objected
-To make it literal-pathspecs by default but make it possible to disable via config – was not accepted.

@bpoldrack mentioned that claiming to support pathspecs open the pandera box in case of recursive operation etc. @yarikoptic argued that it is a good reason to actually disable pathspecs,... Decision remains:
![image](https://user-images.githubusercontent.com/39889/193834577-e7247a0b-4e34-430d-9aae-2b4e018f5ca7.png)

**Comment by yarikoptic** [comment]
<details>
<summary>FWIW Re typing idea, here is an "exploration code samples".</summary> 

### 1: NewType for both

```python
from typing import Any, cast, NewType

PATH = NewType("PATH", str)
PATHSPEC = NewType("PATHSPEC", str)

def func_working_on_pathspec(path: PATHSPEC) -> PATH:
     print(f"working on pathspec {path} of type {type(path)}")
     return cast(PATH, path)  # in reality more complex converted_to_path_pathspec

def func_working_on_path(path: PATH) -> Any:
     print(f"working on path {path} of type {type(path)}")


# somewhat annoying but likely tollerable -- need explicit typed instantiation
path: PATH = PATH("*")
pathspec: PATHSPEC = PATHSPEC("*")

func_working_on_pathspec(pathspec)  # ok
func_working_on_pathspec(path)  # WARNING!

func_working_on_path(pathspec)  # WARNING!
func_working_on_path(path)  # ok
```

where in both cases underlying data type for both `PATH` and `PATHSPEC` is str, the inconvenience is that initial value needs to be explicitly placed into `PATH` or `PATHSPEC` type. But the most annoying would be if we use any `os.path` functions which return `str` -- we would need to cast back into `PATH` ...   Well -- we have `datalad.support.path` where we could centralize that...  `mypy` nicely points to both problematic usages:

```shell
❯ mypy path_pathspec.py
path_pathspec.py:19: error: Argument 1 to "func_working_on_pathspec" has incompatible type "PATH"; expected "PATHSPEC"
path_pathspec.py:21: error: Argument 1 to "func_working_on_path" has incompatible type "PATHSPEC"; expected "PATH"
Found 2 errors in 1 file (checked 1 source file)
```

### 2: NewType only for PATHSPEC

Another solution is to have just `PATH = str` and only define one for PATHSPEC which is IMHO makes sense it is a special construct, might even want to become some class at some point. So first example is tuned up to 

```python
from typing import Any, cast, NewType
import os.path as op

PATH = str
PATHSPEC = NewType("PATHSPEC", str)

def func_working_on_pathspec(path: PATHSPEC) -> PATH:
     print(f"working on pathspec {path} of type {type(path)}")
     return cast(PATH, path)  # in reality more complex converted_to_path_pathspec

def func_working_on_path(path: PATH) -> PATH:
     print(f"working on path {path} of type {type(path)}")
     # Should be kosher!
     return op.join(path, "random.file")


# somewhat annoying but likely tollerable -- need explicit typed instantiation
path: PATH = PATH("*")
pathspec: PATHSPEC = PATHSPEC("*")

func_working_on_pathspec(pathspec)  # ok
func_working_on_pathspec(path)  # WARNING!

print(func_working_on_path(pathspec))  # WARNING!
print(func_working_on_path(path))  # ok
```
but then `mypy` would not catch where we pass `PATHSPEC` into `PATH`:

```
❯ mypy path_pathspec_enh.py
path_pathspec_enh.py:22: error: Argument 1 to "func_working_on_pathspec" has incompatible type "str"; expected "PATHSPEC"
Found 1 error in 1 file (checked 1 source file)
```
because I guess `PATHSPEC` is derived from `str` and thus could be explicitly cast into it.  

### 3: Just a new class for PATHSPEC:

We might indeed want more specific class:

```
from typing import Any, cast, NewType
import os.path as op

PATH = str

class PATHSPEC:
    def __init__(self, pathspec: str):
        self._value = pathspec

    def __str__(self):
        # in reality might be more complex and bound to specific dataset etc
        return self._value

def func_working_on_pathspec(path: PATHSPEC) -> PATH:
     print(f"working on pathspec {path} of type {type(path)}")
     return cast(PATH, path)  # in reality more complex converted_to_path_pathspec

def func_working_on_path(path: PATH) -> PATH:
     print(f"working on path {path} of type {type(path)}")
     # Should be kosher!
     return op.join(path, "random.file")


# somewhat annoying but likely tollerable -- need explicit typed instantiation
path: PATH = PATH("*")
pathspec: PATHSPEC = PATHSPEC("*")

func_working_on_pathspec(pathspec)  # ok
func_working_on_pathspec(path)  # WARNING!

print(func_working_on_path(pathspec))  # WARNING!
print(func_working_on_path(path))  # ok
```

which I like most since we get a guard where we try to use PATHSPEC as str (even with `__str__` defined)

```shell
❯ python path_pathspec_enh2.py
working on pathspec * of type <class '__main__.PATHSPEC'>
working on pathspec * of type <class 'str'>
working on path * of type <class '__main__.PATHSPEC'>
Traceback (most recent call last):
  File "/home/yoh/proj/datalad/trash/path_pathspec_enh2.py", line 31, in <module>
    print(func_working_on_path(pathspec))  # WARNING!
  File "/home/yoh/proj/datalad/trash/path_pathspec_enh2.py", line 21, in func_working_on_path
    return op.join(path, "random.file")
  File "/usr/lib/python3.10/posixpath.py", line 76, in join
    a = os.fspath(a)
TypeError: expected str, bytes or os.PathLike object, not PATHSPEC
```

and we get `mypy` reporting both warnings
```
❯ mypy path_pathspec_enh2.py
path_pathspec_enh2.py:29: error: Argument 1 to "func_working_on_pathspec" has incompatible type "str"; expected "PATHSPEC"
path_pathspec_enh2.py:31: error: Argument 1 to "func_working_on_path" has incompatible type "PATHSPEC"; expected "str"
Found 2 errors in 1 file (checked 1 source file)
```

so if I were to get back to this to make PATHSPEC specifically supported, I would just define a new class for it.

</details>

**Comment by mih** [comment]
FTR: I have spent the last few days looking at the problem and what it would take to support them.

I believe it boils down to being able to mangle pathspecs for recursion across repositories. Most essential low-level Git command do not support the kind of recursion into submodules that we need (or no recursion at all). if we accept pathspecs at the toplevel, we need to be able to translate them for subsequent internal calls, constrained to the respective submodules.

I am presently composing a test battery for this purpose. After trying for a day to implement something per-design, I gave up, because the docs are shit. I am now using Git itself as the ground-truth.

I am not confident that it is possible (even theoretically) to perform such a translation under all circumstances. Any future documentation need to be clear on the limitations. But I believe that I have a solid chance of supporting a good chunk (maybe even all) common use cases.
