### ISSUE TITLE
OS restore, datalad issues: AttributeError: module 'collections' has no attribute 'Callable'

### ISSUE THREAD

**Issue by dorianps** [datalad/datalad#7065]
Hi all, I have recently restored Centos7 after a crash. I reinstalled datalad with pip3 (avoiding to install python2 completely), but obviously there is something that is not working. I have the feeling annex is too new (v10) and datalad too old (v15.6) but I am not sure. I used to install the most recent datalad but looks like pip3 does not go beyond 15.6. Logs below:

Note, the data were on a separate drive and were not affected by the OS restore, so annex files and logs within the data are from the version I had before of datalad/annex (don't remember which).

```
[dorian@mri bids]$ datalad siblings
CommandError: 'git -c diff.ignoreSubmodules=none cat-file blob git-annex:remote.log' failed with exitcode 128 under /DATA/FEDERATED_DATASETS/STUDY1/data/bids
fatal: path 'remote.log' does not exist in 'git-annex'
[dorian@mri bids]$ datalad wtf
/usr/local/lib/python3.6/site-packages/secretstorage/util.py:23: CryptographyDeprecationWarning: Python 3.6 is no longer supported by the Python core team. Therefore, support for it is deprecated in cryptography and will be removed in a future release.
  from cryptography.hazmat.primitives.ciphers import Cipher, algorithms, modes
/usr/local/lib/python3.6/site-packages/requests/__init__.py:104: RequestsDependencyWarning: urllib3 (1.26.10) or chardet (5.0.0)/charset_normalizer (2.0.12) doesn't match a supported version!
  RequestsDependencyWarning)
# WTF
## configuration <SENSITIVE, report disabled by configuration>
## credentials
  - keyring:
    - active_backends:
      - PlaintextKeyring with no encyption v.1.0 at /home/dorian/.local/share/python_keyring/keyring_pass.cfg
    - config_file: /home/dorian/.config/python_keyring/keyringrc.cfg
    - data_root: /home/dorian/.local/share/python_keyring
## datalad
  - version: 0.15.6
## dataset
  - branches:
    - GoodImages@282b9b6
    - git-annex@5fc76a6
    - master@f5d68ab
    - synced/master@26218d7
  - id: ba744c4a-189a-11ea-91d6-ecebb88942b0
  - metadata: <SENSITIVE, report disabled by configuration>
  - path: /DATA/FEDERATED_DATASETS/STUDY1/data/bids
  - repo: AnnexRepo
## dependencies
  - annexremote: 1.6.0
  - appdirs: 1.4.4
  - boto: 2.49.0
  - cmd:annex: 10.20220724-g05cae5801
  - cmd:bundled-git: 2.36.1
  - cmd:git: 2.36.1
  - cmd:system-git: 2.37.1
  - cmd:system-ssh: 7.4p1
  - humanize: 3.14.0
  - iso8601: 1.0.2
  - keyring: 23.4.1
  - keyrings.alt: 4.1.0
  - msgpack: 1.0.4
  - requests: 2.27.1
  - wrapt: 1.14.1
## environment
  - LANG: en_US.UTF-8
  - PATH: /DATA/DAPPS/R/3.5.0/bin:/lib64/qt5/bin/:/DATA/DAPPS/PMOD-client/Pmod4.2/Start/:/DATA/DAPPS/MRtrix/2018_10_18/mrtrix3/bin/:/DATA/DAPPS/MIPAV/mipav/:/DATA/DAPPS/matlab/bin/bin/:/DATA/DAPPS/itksnap/nightly3.8_Dec102018/bin/:/DATA/DAPPS/FSL/2019_08_05/bin:/DATA/DAPPS/freesurfer/2019_08_05/freesurfer//bin:/DATA/DAPPS/freesurfer/2019_08_05/freesurfer//fsfast/bin:/DATA/DAPPS/freesurfer/2019_08_05/freesurfer//tktools:/DATA/DAPPS/freesurfer/2019_08_05/freesurfer//mni/bin:/DATA/DAPPS/dcm2niix/build/bin/:/usr/local/cuda/bin/:/DATA/DAPPS/ants/bin-20181026/bin:/DATA/DAPPS/ants/source-20181026/ANTs/Scripts:/DATA/DAPPS/AFNI/abin/:/usr/local/bin:/usr/bin:/usr/local/sbin:/usr/sbin:/opt/sge/bin/lx-amd64/:/opt/admintools:/home/dorian/.local/bin:/home/dorian/bin
## extensions
## git-annex
  - build flags:
    - Assistant
    - Webapp
    - Pairing
    - Inotify
    - DBus
    - DesktopNotify
    - TorrentParser
    - MagicMime
    - DebugLocks
    - Feeds
    - Testsuite
    - S3
    - WebDAV
  - dependency versions:
    - aws-0.22
    - bloomfilter-2.0.1.0
    - cryptonite-0.26
    - DAV-1.3.4
    - feed-1.3.0.1
    - ghc-8.8.4
    - http-client-0.6.4.1
    - persistent-sqlite-2.10.6.2
    - torrent-10000.1.1
    - uuid-1.3.13
    - yesod-1.6.1.0
  - key/value backends:
    - SHA256E
    - SHA256
    - SHA512E
    - SHA512
    - SHA224E
    - SHA224
    - SHA384E
    - SHA384
    - SHA3_256E
    - SHA3_256
    - SHA3_512E
    - SHA3_512
    - SHA3_224E
    - SHA3_224
    - SHA3_384E
    - SHA3_384
    - SKEIN256E
    - SKEIN256
    - SKEIN512E
    - SKEIN512
    - BLAKE2B256E
    - BLAKE2B256
    - BLAKE2B512E
    - BLAKE2B512
    - BLAKE2B160E
    - BLAKE2B160
    - BLAKE2B224E
    - BLAKE2B224
    - BLAKE2B384E
    - BLAKE2B384
    - BLAKE2BP512E
    - BLAKE2BP512
    - BLAKE2S256E
    - BLAKE2S256
    - BLAKE2S160E
    - BLAKE2S160
    - BLAKE2S224E
    - BLAKE2S224
    - BLAKE2SP256E
    - BLAKE2SP256
    - BLAKE2SP224E
    - BLAKE2SP224
    - SHA1E
    - SHA1
    - MD5E
    - MD5
    - WORM
    - URL
    - X*
  - local repository version: 8
  - operating system: linux x86_64
  - remote types:
    - git
    - gcrypt
    - p2p
    - S3
    - bup
    - directory
    - rsync
    - web
    - bittorrent
    - webdav
    - adb
    - tahoe
    - glacier
    - ddar
    - git-lfs
    - httpalso
    - borg
    - hook
    - external
  - supported repository versions:
    - 8
    - 9
    - 10
  - upgrade supported from repository versions:
    - 0
    - 1
    - 2
    - 3
    - 4
    - 5
    - 6
    - 7
    - 8
    - 9
    - 10
  - version: 10.20220724-g05cae5801
## location
  - path: /DATA/FEDERATED_DATASETS/STUDY1/data/bids
  - type: dataset
## metadata_extractors
  - annex (datalad 0.15.6):
    - distribution: datalad 0.15.6
    - load_error: None
    - module: datalad.metadata.extractors.annex
    - version: None
  - audio (datalad 0.15.6):
    - distribution: datalad 0.15.6
    - load_error: ModuleNotFoundError(No module named 'mutagen')
    - module: datalad.metadata.extractors.audio
  - datacite (datalad 0.15.6):
    - distribution: datalad 0.15.6
    - load_error: None
    - module: datalad.metadata.extractors.datacite
    - version: None
  - datalad_core (datalad 0.15.6):
    - distribution: datalad 0.15.6
    - load_error: None
    - module: datalad.metadata.extractors.datalad_core
    - version: None
  - datalad_rfc822 (datalad 0.15.6):
    - distribution: datalad 0.15.6
    - load_error: None
    - module: datalad.metadata.extractors.datalad_rfc822
    - version: None
  - exif (datalad 0.15.6):
    - distribution: datalad 0.15.6
    - load_error: ModuleNotFoundError(No module named 'exifread')
    - module: datalad.metadata.extractors.exif
  - frictionless_datapackage (datalad 0.15.6):
    - distribution: datalad 0.15.6
    - load_error: None
    - module: datalad.metadata.extractors.frictionless_datapackage
    - version: None
  - image (datalad 0.15.6):
    - distribution: datalad 0.15.6
    - load_error: ModuleNotFoundError(No module named 'PIL')
    - module: datalad.metadata.extractors.image
  - xmp (datalad 0.15.6):
    - distribution: datalad 0.15.6
    - load_error: ModuleNotFoundError(No module named 'libxmp')
    - module: datalad.metadata.extractors.xmp
## metadata_indexers
## python
  - implementation: CPython
  - version: 3.6.8
## system
  - distribution: CentOS Linux/7.9.2009/Core
  - encoding:
    - default: utf-8
    - filesystem: utf-8
    - locale.prefered: UTF-8
  - max_path_length: 296
  - name: Linux
  - release: 3.10.0-1160.71.1.el7.x86_64
  - type: posix
  - version: #1 SMP Tue Jun 28 15:37:28 UTC 2022
```

**Comment by yarikoptic** [comment]
python 3.6. support for it was dropped in 0.16.0 . So - use freshier python to get freshier datalad. could get yourself conda env with it. Consider `pip install datalad-installer` and using it to set it all up in a single invocation.  I do not think there is anything in datalad to fix for this, so closing the issue

**Comment by dorianps** [comment]
Thank you. Can you point me to some resource how to use `datalad-installer`. I already instaleld it as root, and tried to use it without success. Trying as user also did not help (log below). My aim is to install datalad for all users.

```
[dorian@mri bids]$ datalad-installer
2022-10-04T11:59:07-0400 [INFO    ] datalad_installer Writing environment modifications to /tmp/dl-env-dnj7czxa.sh
Traceback (most recent call last):
  File "/usr/local/bin/datalad-installer", line 8, in <module>
    sys.exit(main())
  File "/usr/local/lib/python3.6/site-packages/datalad_installer.py", line 2640, in main
    return manager.main(argv)
  File "/usr/local/lib/python3.6/site-packages/datalad_installer.py", line 757, in main
    self.addcomponent(name=cr.name, **cr.kwargs)
  File "/usr/local/lib/python3.6/site-packages/datalad_installer.py", line 796, in addcomponent
    component(self).provide(**kwargs)
  File "/usr/local/lib/python3.6/site-packages/datalad_installer.py", line 1251, in provide
    raise RuntimeError(f"No viable installation method for {self.NAME}")
RuntimeError: No viable installation method for datalad
```

**Comment by yarikoptic** [comment]
unfortunately despite its power, it can't yet read the minds although I do hope that it will eventually (or at least resort to some opinionated default, ref https://github.com/datalad/datalad-installer/issues/94#issuecomment-1198435847). Try

```
datalad-installer -E ~/miniconda.sh miniconda --batch --spec python=3.10 --path ~/miniconda datalad -m conda
```

so then you could `source ~/miniconda.sh` to end up in that environment.  But also check `datalad-installer --help` and https://github.com/datalad/datalad-installer/#usage for more usage information.

NB above example invocation is just "suggestive", running it on smaug but conda is thinking too hard/too long for me ATM.

**Comment by dorianps** [comment]
Thanks for the tips. The local user install with the command suggested above did not end up well either. I will see if I can find a better system-wide solution. As I said, I need to install datalad in system folders for all users to make sure we are all using the same version rather than local user installs.

Best.

**Comment by yarikoptic** [comment]
well -- not it is an issue!  I need to wake up to grasp how it is possible since AFAIK we do test on 3.10.

**Comment by yarikoptic** [comment]
quick update: the reason is 
```
  datalad            conda-forge/noarch::datalad-0.9.3-py_0 None
...
$> grep __version /tmp/miniconda/lib/python3.10/site-packages/datalad/version.py
__version__ = '0.9.3'
```
i.e. conda for some reason installs ancient datalad version!  I guess that lengthy "Solving environment:" really failed to solve it :-/  there must be some version conflicts which conda is trying to resolve and fails.  Again -- I think nothing for us to solve here, I will move this into feedstock - https://github.com/conda-forge/datalad-feedstock/issues/88 . It seems to be python 3.10 specific, if you use `python=3.9` not `python=3.10` in above, so 

```
datalad-installer -E ~/miniconda.sh miniconda --batch --spec python=3.9 --path ~/miniconda datalad -m conda
```
then it works.  Well, it installs standalone git-annex build (suboptimal but not end of the world) and we get that annoying warning
```
/tmp/miniconda3.9/lib/python3.9/site-packages/requests/__init__.py:102: RequestsDependencyWarning: urllib3 (1.26.8) or chardet (5.0.0)/charset_normalizer (2.0.4) doesn't match a supported version!
  warnings.warn("urllib3 ({}) or chardet ({})/charset_normalizer ({}) doesn't match a supported "
```
(attn @kimsin98 ) but I believe it must work just fine.

**Comment by bpoldrack** [comment]
Thanks for digging, @yarikoptic - that's strange!

However, I'd like to add something here explicitly, @dorianps: It seems to me you initially didn't go the conda path, but simply got an old datalad version. Just making it explicit: If your `pip3` is actually using a newer python version (> 3.6) you should get datalad 0.17.6 via pip.

**Comment by yarikoptic** [comment]
FWIW forcing installation of non-standalone git-annex 
```
conda install -c conda-forge git-annex=*=alldep*
```
works just fine . We will continue discussion on that in https://github.com/conda-forge/git-annex-feedstock/issues/136

**Comment by yarikoptic** [comment]
FWIW, datalad installs just fine now in conda-forge, so original datalad-installer invocation also works out fine.
