### ISSUE TITLE
JSONDecodeError when running cubids-validate

### ISSUE THREAD

**Issue by marcjaskir** [datalad/datalad#7143]
### What is the problem?

I recently installed CuBIDS and datalad, and checked a BIDS dataset into datalad (called "raw"). Running `cubids-validate raw v0 --sequential` returned:

`(cubids) cubids-validate raw v0 --sequential
  0%|                                                                                                               | 0/130 [00:00<?, ?it/s]ERROR:cubids-cli:Errors returned from validator run, parsing now
  0%|                                                                                                               | 0/130 [00:00<?, ?it/s]
Traceback (most recent call last):
  File "/cbica/projects/bbl_22q/miniconda3/envs/cubids/bin/cubids-validate", line 8, in <module>
    sys.exit(cubids_validate())
  File "/cbica/projects/bbl_22q/miniconda3/envs/cubids/lib/python3.8/site-packages/cubids/cli.py", line 190, in cubids_validate
    tmp_parse = parse_validator_output(decoded)
  File "/cbica/projects/bbl_22q/miniconda3/envs/cubids/lib/python3.8/site-packages/cubids/validator.py", line 91, in parse_validator_output
    data = json.loads(output)
  File "/cbica/projects/bbl_22q/miniconda3/envs/cubids/lib/python3.8/json/__init__.py", line 357, in loads
    return _default_decoder.decode(s)
  File "/cbica/projects/bbl_22q/miniconda3/envs/cubids/lib/python3.8/json/decoder.py", line 337, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "/cbica/projects/bbl_22q/miniconda3/envs/cubids/lib/python3.8/json/decoder.py", line 355, in raw_decode
    raise JSONDecodeError("Expecting value", s, err.value) from None
json.decoder.JSONDecodeError: Expecting value: line 1 column 1 (char 0)`

### What steps will reproduce the problem?

conda create -n cubids python=3.8
conda activate cubids
pip install CuBIDS
conda install nodejs
npm install -g bids-validator
conda install -c conda-forge datalad
cubids-validate raw v0 --sequential

### DataLad information

datalad 0.17.6
operating system: linux x86_64

### Have you had any success using DataLad before?

First time using DataLad

**Comment by marcjaskir** [comment]
Feel free to remove this issue as it's irrelevant - this was intended as CuBIDS issue, not DataLad. Thanks!

**Comment by bpoldrack** [comment]
@marcjaskir 

Just for the record and as a possible hint:

> `JSONDecodeError("Expecting value", s, err.value) from None json.decoder.JSONDecodeError: Expecting value: line 1 column 1 (char 0)`

It may try to read JSON from an annexed file. Either trying to read the symlink rather than its target or the content is actually missing (as in: `datalad get <file>` required beforehand).
