### ISSUE TITLE
PaxHeader in tar.gz file create problems with add-archive-content

### ISSUE THREAD

**Issue by bpinsard** [datalad/datalad#7171]
### What is the problem?

I get the following error when running `add-archive-content` on a `tar.gz` generated from python.

```
[INFO   ] Adding content of the archive p01_mario3005.tar.gz into annex AnnexRepo(/data/neuromod/DATA/tests/tests_dl_archive)
0.00 [00:00, ?/s]Traceback (most recent call last):                                                                                                        File "/data/neuromod/virtualenvs/neuromod_data/bin/datalad", line 8, in <module>
    sys.exit(main())                                                                                                                                       File "/data/neuromod/virtualenvs/neuromod_data/lib/python3.7/site-packages/datalad/cli/main.py", line 143, in main             
    _run(cmdlineargs)
  File "/data/neuromod/virtualenvs/neuromod_data/lib/python3.7/site-packages/datalad/cli/main.py", line 168, in _run
    if namespace.common_debug or namespace.common_idebug \                                                                                        
  File "/data/neuromod/virtualenvs/neuromod_data/lib/python3.7/site-packages/datalad/cli/main.py", line 181, in _run_with_debugger
    return cmdlineargs.func(cmdlineargs)
  File "/data/neuromod/virtualenvs/neuromod_data/lib/python3.7/site-packages/datalad/cli/exec.py", line 107, in call_from_parser
    ret = list(ret)
  File "/data/neuromod/virtualenvs/neuromod_data/lib/python3.7/site-packages/datalad/interface/utils.py", line 452, in _execute_command_
    allkwargs):
  File "/data/neuromod/virtualenvs/neuromod_data/lib/python3.7/site-packages/datalad/interface/utils.py", line 619, in _process_results
    for res in results:
  File "/data/neuromod/virtualenvs/neuromod_data/lib/python3.7/site-packages/datalad/local/add_archive_content.py", line 432, in __call__
    extracted_files = list(earchive.get_extracted_files())
  File "/data/neuromod/virtualenvs/neuromod_data/lib/python3.7/site-packages/datalad/support/archives.py", line 364, in get_extracted_files
    path = self.assure_extracted()
  File "/data/neuromod/virtualenvs/neuromod_data/lib/python3.7/site-packages/datalad/support/archives.py", line 318, in assure_extracted
    self._extract_archive(path)
  File "/data/neuromod/virtualenvs/neuromod_data/lib/python3.7/site-packages/datalad/support/archives.py", line 337, in _extract_archive
    decompress_file(self._archive, path, leading_directories=None)
  File "/data/neuromod/virtualenvs/neuromod_data/lib/python3.7/site-packages/datalad/support/archives.py", line 83, in decompress_file 
    _decompress_file(archive, dir_)
  File "/data/neuromod/virtualenvs/neuromod_data/lib/python3.7/site-packages/datalad/support/archive_utils_7z.py", line 62, in decompress_file
    runner.run(cmd, protocol=KillOutput)
  File "/data/neuromod/virtualenvs/neuromod_data/lib/python3.7/site-packages/datalad/runner/runner.py", line 215, in run
    **results,
datalad.runner.exception.CommandError: CommandError: '7z x /data/neuromod/DATA/tests/tests_dl_archive/.git/annex/objects/7p/KG/MD5E-s1515295049--418e0d1a
4c817c2ced7bbf3829995c95.tar.gz/MD5E-s1515295049--418e0d1a4c817c2ced7bbf3829995c95.tar.gz -so | 7z x -si -ttar' failed with exitcode 2 under /data/neurom
od/DATA/tests/tests_dl_archive/.git/datalad/tmp/archives/755ff670a3

> /data/neuromod/virtualenvs/neuromod_data/lib/python3.7/site-packages/datalad/runner/runner.py(215)run()
```

Running the `7z` commands give the following error:

``` 
7z x /data/neuromod/DATA/tests/tests_dl_archive/.git/annex/objects/7p/KG/MD5E-s1515295049--418e0d1a4c817c2ced7bbf3829995c95.tar.gz/MD5E-s1515295049--418e0d1a4c817c2ced7bbf3829995c95.tar.gz -so | 7z x -si -ttar

7-Zip [64] 16.02 : Copyright (c) 1999-2016 Igor Pavlov : 2016-05-21
p7zip Version 16.02 (locale=en_CA.UTF-8,Utf16=on,HugeFiles=on,64 bits,64 CPUs AMD Opteron(tm) Processor 6386 SE               (600F20),ASM,AES-NI)


Extracting archive: 
--
Path = 
Type = tar
Code Page = UTF-8

    
Would you like to replace the existing file:
  Path:     ./@PaxHeader
  Size:     28 bytes (1 KiB)
  Modified: 2022-11-11 15:53:09
with the file from archive:
  Path:     ././@PaxHeader
  Size:     27 bytes (1 KiB)
? (Y)es / (N)o / (A)lways / (S)kip all / A(u)to rename all / (Q)uit? (Y)es / (N)o / (A)lways / (S)kip all / A(u)to rename all / (Q)uit? 

ERROR:
Illegal character in input stream
```

Should be simply solved adding `"-x.\.\@PaxHeader"` to the second `7z` call. 

### What steps will reproduce the problem?

Create a tar.gz with PaxHeader, run `add-archive-content`  on it.

### DataLad information

0.17.9

### Have you had any success using DataLad before?

yes :D

**Comment by bpinsard** [comment]
I am able to index the archive using `-c datalad.runtime.use-patool=1` to avoid `7z` limitations. 
However, `datalad -c datalad.runtime.use-patool=1 get` on the indexed files fail as this config seems not to be passed to git-annex-remote-datalad-archives. Also it would require any user to use that config to make it work with the problematic archive. 

Just to be sure to fully understand how archives work in datalad: if I read the code correcly, when calling `get` on a single file, the whole archive gets extracted, which seems really costly. Are there any compression format that would allow some kind of relatively efficient random access?

**Comment by yarikoptic** [comment]
> Are there any compression format that would allow some kind of relatively efficient random access?

.xz , .zip, .rar?

**Comment by bpinsard** [comment]
So in theory the code for archive customremote could be rewritten to behave similarly to that of ORA archives:  extracting a single file without fully decompressing the archive for 7z/xz files.

**Comment by mih** [comment]
> Are there any compression format that would allow some kind of relatively efficient random access?

`7z` itself is good for that. However, flat-fee random access generally only works with uncompressed archives.
