### ISSUE TITLE
`datalad download-url --archive` fails to unpack downloaded archive on Windows

### ISSUE THREAD

**Issue by mslw** [datalad/datalad#7302]
### Problem description
Running `datalad download-url --archive` on Windows downloads the archive and commits it to a dataset, but fails to unpack it:

```
PS C:\Users\mslw9\Documents\workshop\bar> datalad download-url --archive https://osf.io/d6qbz/download
[INFO] Downloading 'https://osf.io/d6qbz/download' into 'C:\\Users\\mslw9\\Documents\\workshop\\bar\\'
download_url(ok): C:\Users\mslw9\Documents\workshop\bar\imagenette2-160.tgz (file)
add(ok): imagenette2-160.tgz (file)
save(ok): . (dataset)
[INFO] Adding content of the archive C:\Users\mslw9\Documents\workshop\bar\imagenette2-160.tgz into annex AnnexRepo("C:\Users\mslw9\Documents\workshop\bar")
[INFO] Initializing special remote datalad-archives
[ERROR] a bytes-like object is required, not 'str'
0.00 [00:00, ?/s]
```

The downloaded archive is left unpacked in the dataset, and the download step is committed to git history.

### Context
<details><summary>WTF output</summary>

```
# WTF
## configuration <SENSITIVE, report disabled by configuration>
## credentials
  - keyring:
    - active_backends:
      - Windows WinVaultKeyring
      - Windows RegistryKeyring
      - EncryptedKeyring with not defined v.1.0 at C:\Users\mslw9\AppData\Local\Python Keyring\wincrypto_pass.cfg
      - PlaintextKeyring with no encyption v.1.0 at C:\Users\mslw9\AppData\Local\Python Keyring\keyring_pass.cfg
    - config_file: C:\Users\mslw9\AppData\Local\Python Keyring\keyringrc.cfg
    - data_root: C:\Users\mslw9\AppData\Local\Python Keyring
## datalad
  - version: 0.18.1+42.gd94c12664
## dataset
  - branches:
    - adjusted/main(unlocked)@fe0e482
    - git-annex@a331398
    - main@2587649
  - id: 28e25307-8d1f-4c48-8ff4-f90ef3033744
  - path: C:\Users\mslw9\Documents\workshop\bar
  - repo: AnnexRepo
## dependencies
  - annexremote: 1.6.0
  - boto: 2.49.0
  - cmd:annex: 10.20221212-gab11fd70e
  - cmd:bundled-git: UNKNOWN
  - cmd:git: 2.39.2.windows.1
  - cmd:ssh: 8.6p1
  - cmd:system-git: 2.39.2.windows.1
  - cmd:system-ssh: 8.6p1
  - humanize: 4.6.0
  - iso8601: 1.1.0
  - keyring: 23.13.1
  - keyrings.alt: 4.2.0
  - msgpack: 1.0.4
  - platformdirs: 3.0.0
  - requests: 2.28.2
## environment
  - PATH: C:\Users\mslw9\Documents\workshop\dev\Scripts;C:\WINDOWS\system32;C:\WINDOWS;C:\WINDOWS\System32\Wbem;C:\WINDOWS\System32\WindowsPowerShell\v1.0\;C:\WINDOWS\System32\OpenSSH\;C:\Program Files\Git\cmd;C:\Users\mslw9\AppData\Local\Programs\Python\Python311\Scripts\;C:\Users\mslw9\AppData\Local\Programs\Python\Python311\;C:\Users\mslw9\AppData\Local\Microsoft\WindowsApps
## extensions
## git-annex
  - build flags:
    - Assistant
    - Webapp
    - Pairing
    - TorrentParser
    - MagicMime
    - Benchmark
    - Feeds
    - Testsuite
    - S3
    - WebDAV
  - dependency versions:
    - aws-0.22
    - bloomfilter-2.0.1.0
    - cryptonite-0.29
    - DAV-1.3.4
    - feed-1.3.2.0
    - ghc-8.10.7
    - http-client-0.7.9
    - persistent-sqlite-2.13.0.3
    - torrent-10000.1.1
    - uuid-1.3.15
    - yesod-1.6.1.2
  - key/value backends:
    - SHA256E
    - SHA256
    - SHA512E
    - SHA512
    - SHA224E
    - SHA224
    - SHA384E
    - SHA384
    - SHA3_256E
    - SHA3_256
    - SHA3_512E
    - SHA3_512
    - SHA3_224E
    - SHA3_224
    - SHA3_384E
    - SHA3_384
    - SKEIN256E
    - SKEIN256
    - SKEIN512E
    - SKEIN512
    - BLAKE2B256E
    - BLAKE2B256
    - BLAKE2B512E
    - BLAKE2B512
    - BLAKE2B160E
    - BLAKE2B160
    - BLAKE2B224E
    - BLAKE2B224
    - BLAKE2B384E
    - BLAKE2B384
    - BLAKE2BP512E
    - BLAKE2BP512
    - BLAKE2S256E
    - BLAKE2S256
    - BLAKE2S160E
    - BLAKE2S160
    - BLAKE2S224E
    - BLAKE2S224
    - BLAKE2SP256E
    - BLAKE2SP256
    - BLAKE2SP224E
    - BLAKE2SP224
    - SHA1E
    - SHA1
    - MD5E
    - MD5
    - WORM
    - URL
    - X*
  - local repository version: 10
  - operating system: mingw32 x86_64
  - remote types:
    - git
    - gcrypt
    - p2p
    - S3
    - bup
    - directory
    - rsync
    - web
    - bittorrent
    - webdav
    - adb
    - tahoe
    - glacier
    - ddar
    - git-lfs
    - httpalso
    - borg
    - hook
    - external
  - supported repository versions:
    - 8
    - 9
    - 10
  - upgrade supported from repository versions:
    - 2
    - 3
    - 4
    - 5
    - 6
    - 7
    - 8
    - 9
    - 10
  - version: 10.20221212-gab11fd70e
## location
  - path: C:\Users\mslw9\Documents\workshop\bar
  - type: dataset
## python
  - implementation: CPython
  - version: 3.11.2
## system
  - distribution:   10/10.0.22621/SP0/Multiprocessor Free
  - encoding:
    - default: utf-8
    - filesystem: utf-8
    - locale.prefered: cp1250
  - filesystem:
    - CWD:
      - path: C:\Users\mslw9\Documents\workshop\bar
    - HOME:
      - path: C:\Users\mslw9
    - TMP:
      - path: C:\Users\mslw9\AppData\Local\Temp
  - max_path_length: 259
  - name: Windows
  - release: 10
  - type: nt
  - version: 10.0.22621
```
</details>

### Debugging

This is the traceback:

```
datalad --dbg download-url --archive https://osf.io/d6qbz/download
[INFO] Downloading 'https://osf.io/d6qbz/download' into 'C:\\Users\\mslw9\\Documents\\workshop\\bar\\'
download_url(ok): C:\Users\mslw9\Documents\workshop\bar\imagenette2-160.tgz (file)
add(ok): imagenette2-160.tgz (file)
[INFO] Adding content of the archive C:\Users\mslw9\Documents\workshop\bar\imagenette2-160.tgz into annex AnnexRepo("C:\Users\mslw9\Documents\workshop\bar")
0.00 [00:00, ?/s]Traceback (most recent call last):
  File "<frozen runpy>", line 198, in _run_module_as_main
  File "<frozen runpy>", line 88, in _run_code
  File "C:\Users\mslw9\Documents\workshop\dev\Scripts\datalad.exe\__main__.py", line 7, in <module>
    sys.exit(main())
             ^^^^^^
  File "C:\Users\mslw9\Documents\datalad\datalad\cli\main.py", line 143, in main
    _run(cmdlineargs)
  File "C:\Users\mslw9\Documents\datalad\datalad\cli\main.py", line 167, in _run
    ret = _run_with_debugger(namespace) \
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\mslw9\Documents\datalad\datalad\cli\main.py", line 181, in _run_with_debugger
    return cmdlineargs.func(cmdlineargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\mslw9\Documents\datalad\datalad\cli\exec.py", line 107, in call_from_parser
    ret = list(ret)
          ^^^^^^^^^
  File "C:\Users\mslw9\Documents\datalad\datalad\interface\base.py", line 873, in _execute_command_
    for r in _process_results(
  File "C:\Users\mslw9\Documents\datalad\datalad\interface\utils.py", line 319, in _process_results
    for res in results:
  File "C:\Users\mslw9\Documents\datalad\datalad\local\download_url.py", line 294, in __call__
    yield from ds.add_archive_content(
  File "C:\Users\mslw9\Documents\datalad\datalad\interface\base.py", line 873, in _execute_command_
    for r in _process_results(
  File "C:\Users\mslw9\Documents\datalad\datalad\interface\utils.py", line 319, in _process_results
    for res in results:
  File "C:\Users\mslw9\Documents\datalad\datalad\local\add_archive_content.py", line 432, in __call__
    extracted_files = list(earchive.get_extracted_files())
                      ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\mslw9\Documents\datalad\datalad\support\archives.py", line 364, in get_extracted_files
    path = self.assure_extracted()
           ^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\mslw9\Documents\datalad\datalad\support\archives.py", line 318, in assure_extracted
    self._extract_archive(path)
  File "C:\Users\mslw9\Documents\datalad\datalad\support\archives.py", line 337, in _extract_archive
    decompress_file(self._archive, path, leading_directories=None)
  File "C:\Users\mslw9\Documents\datalad\datalad\support\archives.py", line 83, in decompress_file
    _decompress_file(archive, dir_)
  File "C:\Users\mslw9\Documents\datalad\datalad\support\archive_utils_patool.py", line 138, in decompress_file
    outdir = unixify_path(dir_)
             ^^^^^^^^^^^^^^^^^^
  File "C:\Users\mslw9\Documents\datalad\datalad\support\archive_utils_patool.py", line 112, in unixify_path
    path_ = path_.split(os.sep)
            ^^^^^^^^^^^^^^^^^^^
TypeError: a bytes-like object is required, not 'str'

> c:\users\mslw9\documents\datalad\datalad\support\archive_utils_patool.py(112)unixify_path()
-> path_ = path_.split(os.sep)
```

And digging in a little:
```
(Pdb) p path
b'C:\\Users\\mslw9\\Documents\\workshop\\bar\\.git\\datalad\\tmp\\archives\\467adf2ce3'
(Pdb) p os.sep
'\\'
(Pdb) p type(path), type(os.sep)
(<class 'bytes'>, <class 'str'>)
(Pdb) p path_.split(os.sep.encode('utf-8'))
[b'', b'Users', b'mslw9', b'Documents', b'workshop', b'bar', b'.git', b'datalad', b'tmp', b'archives', b'467adf2ce3']
```

So, the `path_` is for some reason a bytes object...

A quick fix would be to decode path or encode the path separator, but this seems weird.

A fix I like more would be to switch the `unixify_path` (and , consequently the entire small `archive_utils_patool`) to pathlib (side note: in line with #4598 & #4056).

But why `path_` is a bytes object in first place? I'll dig some more with the debugger.

**Comment by mslw** [comment]
> But why path_ is a bytes object in first place? I'll dig some more with the debugger.

Ok, I was selectively blind. Just before `decompress_files` calls `unixify_path(dir_)` it does `dir_ = ensure_bytes(dir_)` (and it uses `ensure_unicode` afterwards):

https://github.com/datalad/datalad/blob/d94c126643d86288012f6f3181a483c07d355440/datalad/support/archive_utils_patool.py#L132-L141

These lines go way back to 932788c and before

Interestingly, `datalad.support.archves` will only use `archive_utils_patool` if it can't use 7z. Looking at the latest Appveyor run, wtf output lists `cmd:7z` there, but mine does not, which may be the reason why it slips through testing.

With that knowledge, I think rewriting to Pathlib is the best way.

**Comment by mslw** [comment]
That's my local outcome of `pytest .\datalad\tests\test_archives.py`:
```
=============================================== short test summary info ===============================================
FAILED datalad/tests/test_archives.py::test_decompress_file[None] - TypeError: a bytes-like object is required, not 'str'
FAILED datalad/tests/test_archives.py::test_decompress_file[strip] - TypeError: a bytes-like object is required, not 'str'
FAILED datalad/tests/test_archives.py::test_decompress_file_unknown - TypeError: a bytes-like object is required, not 'str'
FAILED datalad/tests/test_archives.py::test_compress_dir[.tar.xz] - patoolib.util.PatoolError: Command `['C:\\WINDOWS\\system32\\tar.EXE', '--create', '--use-compress-program', 'xz', ...
FAILED datalad/tests/test_archives.py::test_compress_dir[.tar.gz] - patoolib.util.PatoolError: Command `['C:\\WINDOWS\\system32\\tar.EXE', '--create', '-z', '--verbose', '--file', '/C...
FAILED datalad/tests/test_archives.py::test_compress_dir[.tgz] - patoolib.util.PatoolError: Command `['C:\\WINDOWS\\system32\\tar.EXE', '--create', '-z', '--verbose', '--file', '/C...
FAILED datalad/tests/test_archives.py::test_compress_dir[.tbz2] - patoolib.util.PatoolError: Command `['C:\\WINDOWS\\system32\\tar.EXE', '--create', '-j', '--verbose', '--file', '/C...
FAILED datalad/tests/test_archives.py::test_compress_dir[.tar] - patoolib.util.PatoolError: Command `['C:\\WINDOWS\\system32\\tar.EXE', '--create', '--verbose', '--file', '/C/Users...
FAILED datalad/tests/test_archives.py::test_compress_dir[.zip] - assert False
FAILED datalad/tests/test_archives.py::test_compress_dir[.7z] - assert False
FAILED datalad/tests/test_archives.py::test_ExtractedArchive - TypeError: a bytes-like object is required, not 'str'
====================================== 11 failed, 13 passed, 8 skipped in 2.65s =======================================
```

**Comment by adswa** [comment]
one quick side question: did you install 7z on that Windows computer?

**Comment by mslw** [comment]
Yes, I have 7 zip installed - but apparently only the GUI.

(so yes, this requires being on windows and not having cli 7z)

**Comment by mslw** [comment]
Rewriting `unixify_path()` to use pathlib, and getting rid of bytes is easy, but it only opened another problem for me -- although the docstring to `unixify_path` says: 
```
    On windows convert paths from drive:\d\file to /drive/d/file

    This overcomes problems with various cmdline tools we are to use,
    such as tar etc
```

it seems that for me the requirement is opposite.

Assuming `mypath` is a `WindowsPath`, I can call `patoolib.extract_archive()` with:
- `str(mypath)` (e.g. `C:\\Users\\mslw9\\...`)
- `mypath.as_posix()` (e.g. `C:/Users/mslw9/...`),
- but NOT the "unixified" version (e.g. ``/C/Users/mslw9/...``)
because then tar refuses to operate...

```
>>> patoolib._extract_archive(
...     "/C/Users/mslw9/Documents/archive.tar.gz",
...     verbosity=0,
...     outdir="/C/Users/mslw9/Documents/existingdir",
... )
patool: running C:\WINDOWS\system32\tar.EXE --extract -z --file /C/Users/mslw9/Documents/archive.tar.gz --directory /C/Users/mslw9/Documents/existingdir
tar.EXE: Error opening archive: Failed to open '/C/Users/mslw9/Documents/archive.tar.gz'
```
(note: just like in `decompress_files` we're calling `_extract_archive()` not `extract_archive()` - the latter would first try to validate the "unixified" path and say that it doesn't exist, because it uses `os.path.exists()` undereath)

FTR, this is is the tar that gets called by patool:
```
C:\WINDOWS\system32\tar.exe --version
bsdtar 3.5.2 - libarchive 3.5.2 zlib/1.2.5.f-ipp bz2lib/1.0.6
```

So for me, getting rid of `unixify_path`, `ensure_bytes`/`ensure_unicode` altogether makes things work - the following function passes tests (removed comments and not on windows clause for brevity):

``` python
def decompress_file(archive, dir_):
    """Decompress `archive` into a directory `dir_`

    Parameters
    ----------
    archive: str
    dir_: str
    """

    with swallow_outputs() as cmo:

        patoolib.util.check_existing_filename(archive)
        patoolib.util.check_existing_filename(dir_, onlyfiles=False)

        format_compression = patoolib.get_archive_format(archive)
        if format_compression == ('gzip', None):
            # <comment snipped>
            program = patoolib.find_archive_program(
                format_compression[0], 'extract')
            if basename(program) != '7z':
                raise MissingExternalDependency(
                    "cmd:7z",
                    msg="(Not) Funny enough but ATM we need p7zip installation "
                        "to handle .gz files extraction 'correctly'"
                )

        patoolib._extract_archive(archive,
                                  outdir=dir_,
                                  verbosity=100)

        if cmo.out:
            lgr.debug("patool gave stdout:\n%s", cmo.out)
        if cmo.err:
            lgr.debug("patool gave stderr:\n%s", cmo.err)

    # <comment snipped>

    if not on_windows:
         # (...) - this bit not relevant here

```

Question is, am I the norm or the exception?

**Comment by mslw** [comment]
> I have 7 zip installed (don't remember how) - but apparently only the GUI.
> 
> (so yes, this requires being on windows and not having cli 7z to happen)

To close the 7zip lead - 7zip comes with command line 7z.exe, but the 7zip installer puts executables in Program Files, without adding that location to the PATH. For a single PowerShell session, `$env:Path += ';C:\Program Files\7-Zip'` is enough (this can also be set persistently, I think through system settings). Having 7zip (or, more specifically, 7z) works around all the issues above, as patool serves only as fallback. So from the user experience, 7z is the solution.

And although I would like the fallback to also be functional, I will step away from this issue now.

Code-wise, on my specific installation, removal of old patool workarounds would be a quick and sufficient fix, but I'm not 100% sure if that's alright to do. And, since 7z is treated as de facto primary method, maybe there's reason to get away from using patool?

**Comment by NeroBlackstone** [comment]
I also ran into this problem when executing the commands in this [tutorial](https://handbook.datalad.org/en/latest/beyond_basics/101-168-dvc.html#datalad-workflow). Maybe we should point out in the documentation that we need to have 7z installed beforehand.

**Comment by adswa** [comment]
I would be fine adding a note to this specific tutorial about 7zip in a Windows Wit - however, do not that the handbook's installation instructions recommend installing 7zip highly: https://handbook.datalad.org/en/latest/intro/installation.html#windows-10-and-11

**Comment by NeroBlackstone** [comment]
Maybe during installation we can remind the user to install 7zip, or throw an error message about 7zip if the decompression fails.
