### ISSUE TITLE
Circular import

### ISSUE THREAD

**Issue by mih** [datalad/datalad#7393]
```
❯ python -c 'from datalad.support.extensions import has_config'
Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "/home/mih/hacking/datalad/git/datalad/support/extensions.py", line 12, in <module>
    from datalad.interface.common_cfg import (
  File "/home/mih/hacking/datalad/git/datalad/interface/common_cfg.py", line 33, in <module>
    from datalad.utils import on_windows
  File "/home/mih/hacking/datalad/git/datalad/utils.py", line 98, in <module>
    from datalad.consts import TIMESTAMP_FMT
  File "/home/mih/hacking/datalad/git/datalad/consts.py", line 52, in <module>
    from datalad.runner.gitrunner import GIT_SSH_COMMAND
  File "/home/mih/hacking/datalad/git/datalad/runner/__init__.py", line 12, in <module>
    from .coreprotocols import (
  File "/home/mih/hacking/datalad/git/datalad/runner/coreprotocols.py", line 14, in <module>
    from .protocol import WitlessProtocol
  File "/home/mih/hacking/datalad/git/datalad/runner/protocol.py", line 24, in <module>
    from datalad.utils import ensure_unicode
ImportError: cannot import name 'ensure_unicode' from partially initialized module 'datalad.utils' (most likely due to a circular import) (/home/mih/hacking/datalad/git/datalad/utils.py)
```

I believe it is unnecessary and not beneficial to have `GIT_SSH_COMMAND` be imported from runner code in `consts.py`.

**Comment by adswa** [comment]
Note from the call: @yarikoptic suggested that there should be no imports in ``datalad/consts.py``
