### ISSUE TITLE
PR #682: unfortunately doesn't load json with utf-8 correctly

### ISSUE THREAD

**Issue by yarikoptic** [datalad/datalad#755]
Relates to #682 (decided to file as a separate issue to not get lost among comments)
```shell
(git)smaug:/mnt/scrap/datalad/datasets.datalad.org/openfmri/ds000052[master]git
$> grep Blagoev .datalad/meta/meta.json
      "Pare-Blagoev, E. J.",
      "Poldrack, R.A., Clark, J., Paré-Blagoev, E.J., Shohamy, D., Creso Moyano, J., Myers, C., Gluck, M.A. (2001). Interactive memory systems in the human brain. Nature, 414(6863):546-50"
```
so there is `é` in `Paré-Blagoev`
```
$> datalad search-datasets BIDS                                                                                                                  
2016-09-03 20:52:19,409 [INFO   ] Next one is slow, but can be made faster by your contribution! (search_datasets.py:67)
2016-09-03 20:52:23,810 [INFO   ] Fast again... (search_datasets.py:70)
Traceback (most recent call last):
  File "/home/yoh/proj/datalad/datalad/venv-tests/bin/datalad", line 9, in <module>
    load_entry_point('datalad==0.2.3', 'console_scripts', 'datalad')()
  File "/home/yoh/proj/datalad/datalad/datalad/cmdline/main.py", line 262, in main
    cmdlineargs.result_renderer(ret, cmdlineargs)
  File "/home/yoh/proj/datalad/datalad/datalad/metadata/search_datasets.py", line 118, in result_renderer_cmdline
    ', '.join(['{}: {}'.format(k, str(r[k])) for k in r])))
UnicodeEncodeError: 'ascii' codec can't encode character u'\xe9' in position 30: ordinal not in range(128)

$> datalad --dbg search-datasets BIDS
2016-09-03 20:52:38,118 [INFO   ] Next one is slow, but can be made faster by your contribution! (search_datasets.py:67)
2016-09-03 20:52:40,602 [INFO   ] Fast again... (search_datasets.py:70)
Traceback (most recent call last):
  File "/home/yoh/proj/datalad/datalad/venv-tests/bin/datalad", line 9, in <module>
    load_entry_point('datalad==0.2.3', 'console_scripts', 'datalad')()
  File "/home/yoh/proj/datalad/datalad/datalad/cmdline/main.py", line 262, in main
    cmdlineargs.result_renderer(ret, cmdlineargs)
  File "/home/yoh/proj/datalad/datalad/datalad/metadata/search_datasets.py", line 118, in result_renderer_cmdline
    ', '.join(['{}: {}'.format(k, str(r[k])) for k in r])))
UnicodeEncodeError: 'ascii' codec can't encode character u'\xe9' in position 30: ordinal not in range(128)
()
> /home/yoh/proj/datalad/datalad/datalad/metadata/search_datasets.py(118)result_renderer_cmdline()
-> ', '.join(['{}: {}'.format(k, str(r[k])) for k in r])))
(Pdb) p r
{u'name': u'Classification learning and reversal', u'license': u'PDDL', u'author': [u'Poldrack, R.A.', u'Clark, J.', u'Pare-Blagoev, E. J.', u'Shohamy, D.', u'Creso Moyano, J.', u'Myers, C.', u'Gluck, M'], u'type': u'Dataset', u'citation': u'Poldrack, R.A., Clark, J., Par\xe9-Blagoev, E.J., Shohamy, D., Creso Moyano, J., Myers, C., Gluck, M.A. (2001). Interactive memory systems in the human brain. Nature, 414(6863):546-50', u'dc:conformsTo': u'BIDS 1.0.0rc3', u'id': u'4f9efb3a-7173-11e6-a924-002590f97d84'}
```
so it seems it wasn't even loaded correctly (line is marked as unicode but feels like it wasn't decoded from utf-8)

As a workaround (just to proceed) I will submit a PR swallowing upon those problematic ones

**Comment by yarikoptic** [comment]
this issue was addressed as a part of #847.  Now it looks splendid, at least in custom text output ;)

```shell
$> datalad search -R Blagoev
openfmri/ds000052:
 author: Poldrack, R.A., Clark, J., Pare-Blagoev, E. J., Shohamy, D., Creso Moyano, J., Myers, C., Gluck, M
 citation: Poldrack, R.A., Clark, J., Paré-Blagoev, E.J., Shohamy, D., Creso Moyano, J., Myers, C., Gluck, M.A. (2001). Interactive memory systems in the human brain. Nature, 414(6863):546-50
changes on filesystem:                                                                                                                                  
 openfmri | 0
(venv-tests) 2 19497 [1].....................................:Tue 20 Sep 2016 09:51:33 AM EDT:.
(git)hopa:/tmp/datasets.datalad.org[master]
$> datalad search -R -f json Blagoev
[
  {
    "citation": "Poldrack, R.A., Clark, J., Par\u00e9-Blagoev, E.J., Shohamy, D., Creso Moyano, J., Myers, C., Gluck, M.A. (2001). Interactive memory systems in the human brain. Nature, 414(6863):546-50", 
    "author": [
      "Poldrack, R.A.", 
      "Clark, J.", 
      "Pare-Blagoev, E. J.", 
      "Shohamy, D.", 
      "Creso Moyano, J.", 
      "Myers, C.", 
      "Gluck, M"
    ]
  }
]
```
