### ISSUE TITLE
pyld seems not ready for Python 3.x

### ISSUE THREAD

**Issue by mih** [datalad/datalad#756]
````
  File "/usr/lib/python3/dist-packages/pyld/jsonld.py", line 4465, in __str__
    rval = repr(self.message)
AttributeError: 'JsonLdError' object has no attribute 'message'
````

Putting it here to not forget about it, until I can investigate.

**Comment by yarikoptic** [comment]
On September 5, 2016 12:01:08 PM EDT, Michael Hanke <notifications@github.com> wrote:
>````
>File "/usr/lib/python3/dist-packages/pyld/jsonld.py", line 4465, in
>__str__
>    rval = repr(self.message)
>AttributeError: 'JsonLdError' object has no attribute 'message'
>````
>
>Putting it here to not forget about it, until I can investigate.
>
>-- 
>You are receiving this because you are subscribed to this thread.
>Reply to this email directly or view it on GitHub:
>https://github.com/datalad/datalad/issues/756

Smells like a bug on their side
-- 
Sent from a phone which beats iPhone.

**Comment by yarikoptic** [comment]
code in `search` (after rename in #847) is not yet PY3 ready (use of `unicode`) I think and for me test fails due to different error msg which I now made visible:
```
$> .tox/py34/bin/nosetests -s -v datalad/metadata/                                                              
datalad.metadata.parsers.tests.test_bids.test_get_metadata ... ok
datalad.metadata.parsers.tests.test_bids.test_has_metadata ... ok
datalad.metadata.parsers.tests.test_bids.test_has_no_metadata ... ok
datalad.metadata.parsers.tests.test_frictionless_datapackage.test_get_metadata ... ok
datalad.metadata.parsers.tests.test_frictionless_datapackage.test_has_metadata ... ok
datalad.metadata.parsers.tests.test_frictionless_datapackage.test_has_no_metadata ... ok
datalad.metadata.tests.test_base.test_aggregation ... SKIP: pyld code is not ready for Python 3.5 it seems (see: #756): ('Could not expand input before flattening.',)
Type: jsonld.FlattenError
Cause: ('Could not perform JSON-LD expansion.',)
Type: jsonld.ExpandError
Cause: ('Dereferencing a URL did not result in a valid JSON-LD context.',)
Type: jsonld.ContextUrlError
Code: loading remote context failed
Details: {'url': 'http://schema.org/'}
Cause: 'str' does not support the buffer interface  File "/home/yoh/proj/datalad/datalad/.tox/py34/lib/python3.4/site-packages/pyld/jsonld.py", line 4070, in _retrieve_context_urls
    remote_doc = load_document(url)
  File "/home/yoh/proj/datalad/datalad/datalad/metadata/__init__.py", line 328, in _cached_load_document
    doc = pickle.load(open(doc_fname))
  File "/home/yoh/proj/datalad/datalad/.tox/py34/lib/python3.4/site-packages/pyld/jsonld.py", line 812, in expand
    input_, {}, options['documentLoader'], options['base'])
  File "/home/yoh/proj/datalad/datalad/.tox/py34/lib/python3.4/site-packages/pyld/jsonld.py", line 4077, in _retrieve_context_urls
    code='loading remote context failed', cause=cause)
  File "/home/yoh/proj/datalad/datalad/.tox/py34/lib/python3.4/site-packages/pyld/jsonld.py", line 865, in flatten
    expanded = self.expand(input_, options)
  File "/home/yoh/proj/datalad/datalad/.tox/py34/lib/python3.4/site-packages/pyld/jsonld.py", line 816, in expand
    'jsonld.ExpandError', cause=cause)
 [jsonld.py:flatten:869]
datalad.metadata.tests.test_base.test_basic_metadata ... ok
datalad.metadata.tests.test_base.test_get_multiple_metadata_types ... ok
datalad.metadata.tests.test_base.test_get_metadata_type ... ok
```
```shell
hopa:/tmp/ds000201
$> datalad search Stu.* Sle.ps
Traceback (most recent call last):
  File "/home/yoh/proj/datalad/datalad/.tox/py34/bin/datalad", line 9, in <module>
    load_entry_point('datalad', 'console_scripts', 'datalad')()
  File "/home/yoh/proj/datalad/datalad/datalad/cmdline/main.py", line 265, in main
    cmdlineargs.result_renderer(ret, cmdlineargs)
  File "/home/yoh/proj/datalad/datalad/datalad/metadata/search.py", line 190, in result_renderer_cmdline
    for r in res:
  File "/home/yoh/proj/datalad/datalad/datalad/metadata/search.py", line 91, in __call__
    meta, checksum = pickle.load(open(mcache_fname))
  File "/home/yoh/proj/datalad/datalad/.tox/py34/lib/python3.4/codecs.py", line 319, in decode
    (result, consumed) = self._buffer_decode(data, self.errors, final)
UnicodeDecodeError: 'utf-8' codec can't decode byte 0xc5 in position 254: invalid continuation byte
```

**Comment by yarikoptic** [comment]
did you report this issue upstream @mih?  according to https://github.com/digitalbazaar/pyld (.travis.yml) it should support all python s3 just fine, so it might as well be a bug on our side!
