### ISSUE TITLE
Publish fails on subdataset with detached HEAD. Should it ?

### ISSUE THREAD

**Issue by debanjum** [datalad/datalad#758]
Me and Yarik think it should probably give an error message or something instead of crashing like it currently did. Checking out master fixed it for now

``` sh
         2016-09-02 18:37:01,510 [INFO   ] Publishing dataset <Dataset path=/home/debanjum/datasets.datalad.org/openfmri/ds000200> to sibling public-server ... (publish.py:270)
         2016-09-02 18:37:02,546 [WARNING] Nothing was pushed. (publish.py:48)
         2016-09-02 18:37:03,674 [WARNING] Nothing was pushed. (publish.py:48)
         Traceback (most recent call last):
           File "/home/debanjum/datalad/venv-tests/bin/datalad", line 9, in <module>
             load_entry_point('datalad==0.2.3', 'console_scripts', 'datalad')()
           File "/home/debanjum/datalad/datalad/cmdline/main.py", line 245, in main
             ret = cmdlineargs.func(cmdlineargs)
           File "/home/debanjum/datalad/datalad/interface/base.py", line 285, in call_from_parser
             return cls.__call__(**kwargs)
           File "/home/debanjum/datalad/datalad/distribution/publish.py", line 235, in __call__
             published_, skipped_ = ds_.publish(to=to, recursive=recursive, **pkw)
           File "/home/debanjum/datalad/datalad/distribution/dataset.py", line 510, in apply_func
             return f(**kwargs)
           File "/home/debanjum/datalad/datalad/distribution/publish.py", line 235, in __call__
             published_, skipped_ = ds_.publish(to=to, recursive=recursive, **pkw)
           File "/home/debanjum/datalad/datalad/distribution/dataset.py", line 510, in apply_func
             return f(**kwargs)
           File "/home/debanjum/datalad/datalad/distribution/publish.py", line 176, in __call__
             track_remote, track_branch = ds.repo.get_tracking_branch()
           File "/home/debanjum/datalad/datalad/support/gitrepo.py", line 1432, in get_tracking_branch
             branch = self.get_active_branch()
           File "/home/debanjum/datalad/datalad/support/gitrepo.py", line 758, in get_active_branch
             return self.repo.active_branch.name
           File "/home/debanjum/datalad/venv-tests/local/lib/python2.7/site-packages/git/repo/base.py", line 670, in active_branch
             return self.head.reference
           File "/home/debanjum/datalad/venv-tests/local/lib/python2.7/site-packages/git/refs/symbolic.py", line 258, in _get_reference
             raise TypeError("%s is a detached symbolic reference as it points to %r" % (self, sha))
         TypeError: HEAD is a detached symbolic reference as it points to 'd364a1aa832f808a64e387f3c26b4b13afba0ae4'
         ()
         > /home/debanjum/datalad/venv-tests/local/lib/python2.7/site-packages/git/refs/symbolic.py(258)_get_reference()
         -> raise TypeError("%s is a detached symbolic reference as it points to %r" % (self, sha))

```

**Comment by mih** [comment]
I don't think it should crash (of course), but I also think it should not fail. A detached head doesn't seem like something that we should make impossible.

**Comment by bpoldrack** [comment]
Note to myself: Wrong order of line 176ff. First check, whether a remote was given and only then search for a tracking branch.
