### ISSUE TITLE
Dataset.get_subdatasets() cannot deal with subdataset removal

### ISSUE THREAD

**Issue by mih** [datalad/datalad#803]
Either that, or removal needs to be implemented in a different way. Evidence: https://github.com/datalad/datalad/pull/796/commits/1e03671cde1a5fbb6f3b3f3e4e5b058cef877618

````
nosetests -s datalad/distribution/tests/test_uninstall.py:test_clean_subds_removal
F
======================================================================
FAIL: datalad.distribution.tests.test_uninstall.test_clean_subds_removal
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/usr/lib/python2.7/dist-packages/nose/case.py", line 197, in runTest
    self.test(*self.arg)
  File "/home/mih/hacking/datalad/git/datalad/tests/utils.py", line 516, in newfunc
    return t(*(arg + (filename,)), **kw)
  File "/home/mih/hacking/datalad/git/datalad/distribution/tests/test_uninstall.py", line 55, in test_clean_subds_removal
    eq_(ds.get_subdatasets(), ['two'])
AssertionError: [] != ['two']
````

**Comment by mih** [comment]
Culprit:

````
(Pdb) ds.repo.get_submodules()
*** InvalidGitRepositoryError: Gitmodule path u'one' did not exist in revision of parent commit HEAD
````
