### ISSUE TITLE
installing in a clean env without appdirs causes the error since durinng manpage generation already needs it

### ISSUE THREAD

**Issue by yarikoptic** [datalad/datalad#896]
saw it happen while installing on mac

**Comment by yarikoptic** [comment]
actually in a VERY clean env it would fail even before appdirs:
```shell
$> virtualenv venv-datalad       
Running virtualenv with interpreter /home/yoh/proj/datalad/datalad/venv-tests/bin/python2
Using real prefix '/usr'
New python executable in /tmp/venv-datalad/bin/python2
Also creating executable in /tmp/venv-datalad/bin/python
Installing setuptools, pkg_resources, pip, wheel...done.
s%                                                                                                                                                      (venv-tests) 2 

$> venv-datalad/bin/pip install datalad==0.3
Collecting datalad==0.3
  Downloading datalad-0.3.tar.gz (772kB)
    100% |████████████████████████████████| 778kB 1.7MB/s 
Collecting appdirs (from datalad==0.3)
  Using cached appdirs-1.4.0-py2.py3-none-any.whl
Collecting GitPython>=2.0.8 (from datalad==0.3)
...
Building wheels for collected packages: datalad, cryptography
  Running setup.py bdist_wheel for datalad ... error
  Complete output from command /tmp/venv-datalad/bin/python2 -u -c "import setuptools, tokenize;__file__='/tmp/pip-build-Le93kp/datalad/setup.py';exec(compile(getattr(tokenize, 'open', open)(__file__).read().replace('\r\n', '\n'), __file__, 'exec'))" bdist_wheel -d /tmp/tmp8tumTxpip-wheel- --python-tag cp27:
  running bdist_wheel
  running build
  running build_py
  running build_manpage
  Traceback (most recent call last):
    File "<string>", line 1, in <module>
    File "/tmp/pip-build-Le93kp/datalad/setup.py", line 130, in <module>
      findsome('downloaders/configs', {'cfg'})
    File "/usr/lib/python2.7/distutils/core.py", line 151, in setup
      dist.run_commands()
    File "/usr/lib/python2.7/distutils/dist.py", line 953, in run_commands
      self.run_command(cmd)
    File "/usr/lib/python2.7/distutils/dist.py", line 972, in run_command
      cmd_obj.run()
    File "/tmp/venv-datalad/local/lib/python2.7/site-packages/wheel/bdist_wheel.py", line 199, in run
      self.run_command('build')
    File "/usr/lib/python2.7/distutils/cmd.py", line 326, in run_command
      self.distribution.run_command(command)
    File "/usr/lib/python2.7/distutils/dist.py", line 972, in run_command
      cmd_obj.run()
    File "/usr/lib/python2.7/distutils/command/build.py", line 128, in run
      self.run_command(cmd_name)
    File "/usr/lib/python2.7/distutils/cmd.py", line 326, in run_command
      self.distribution.run_command(command)
    File "/usr/lib/python2.7/distutils/dist.py", line 972, in run_command
      cmd_obj.run()
    File "/tmp/pip-build-Le93kp/datalad/setup.py", line 100, in run
      self.run_command('build_manpage')
    File "/usr/lib/python2.7/distutils/cmd.py", line 326, in run_command
      self.distribution.run_command(command)
    File "/usr/lib/python2.7/distutils/dist.py", line 971, in run_command
      cmd_obj.ensure_finalized()
    File "/usr/lib/python2.7/distutils/cmd.py", line 109, in ensure_finalized
      self.finalize_options()
    File "/tmp/pip-build-Le93kp/datalad/setup_support.py", line 65, in finalize_options
      raise err
  ImportError: No module named six.moves.builtins
  
```

not sure if there are side-effects of failure but I guess that functionality (manpage generation) shoudl be either guarded for failure and better even moved (if possible) to happen after installation finishes

**Comment by mih** [comment]
I don't mind to simply protect it against failure and move on without manpages. In all situations where we actually want to build them we can do in a custom way at any later point.

**Comment by yarikoptic** [comment]
On Fri, 23 Sep 2016, Michael Hanke wrote:

>    I don't mind to simply protect it against failure and move on without
>    manpages. In all situations where we actually want to build them we can do
>    in a custom way at any later point.

agreed
