### ISSUE TITLE
datalad search fails on Py2 with some pyld caching

### ISSUE THREAD

**Issue by satra** [datalad/datalad#975]
datalad 0.3.1
pyld.jsonld.__version__ : '0.7.1'

```
$ datalad search bids
No DataLad dataset found at current location
Would you like to search within DataLad meta-dataset under '/Users/satra/datalad' and search within it? (choices: yes, no): yes

2016-10-04 14:01:54,726 [INFO   ] Performing search using central dataset '/Users/satra/datalad' (search.py:174)
2016-10-04 14:01:54,747 [INFO   ] Loading and caching local meta-data... might take a few seconds (search.py:201)
Traceback (most recent call last):
  File "/software/anaconda/envs/devpype/bin/datalad", line 11, in <module>
    sys.exit(main())
  File "/software/anaconda/envs/devpype/lib/python2.7/site-packages/datalad/cmdline/main.py", line 273, in main
    cmdlineargs.result_renderer(ret, cmdlineargs)
  File "/software/anaconda/envs/devpype/lib/python2.7/site-packages/datalad/metadata/search.py", line 357, in result_renderer_cmdline
    for location, r in res:
  File "/software/anaconda/envs/devpype/lib/python2.7/site-packages/datalad/metadata/search.py", line 180, in __call__
    format=format, regex=regex):
  File "/software/anaconda/envs/devpype/lib/python2.7/site-packages/datalad/metadata/search.py", line 208, in __call__
    meta = flatten_metadata_graph(meta)
  File "/software/anaconda/envs/devpype/lib/python2.7/site-packages/datalad/metadata/__init__.py", line 348, in flatten_metadata_graph
    return jsonld.flatten(obj, ctx={"@context": "http://schema.org/"})
  File "/software/anaconda/envs/devpype/lib/python2.7/site-packages/pyld/jsonld.py", line 189, in flatten
    return JsonLdProcessor().flatten(input_, ctx, options)
  File "/software/anaconda/envs/devpype/lib/python2.7/site-packages/pyld/jsonld.py", line 869, in flatten
    'jsonld.FlattenError', cause=cause)
pyld.jsonld.JsonLdError: ('Could not expand input before flattening.',)
Type: jsonld.FlattenError
Cause: ('Could not perform JSON-LD expansion.',)
Type: jsonld.ExpandError
Cause: ('Dereferencing a URL did not result in a valid JSON-LD context.',)
Type: jsonld.ContextUrlError
Code: loading remote context failed
Details: {'url': 'http://schema.org/'}
Cause:   File "/software/anaconda/envs/devpype/lib/python2.7/site-packages/pyld/jsonld.py", line 4070, in _retrieve_context_urls
    remote_doc = load_document(url)
  File "/software/anaconda/envs/devpype/lib/python2.7/site-packages/datalad/metadata/__init__.py", line 326, in _cached_load_document
    doc = pickle.load(open(doc_fname))
  File "/software/anaconda/envs/devpype/lib/python2.7/site-packages/pyld/jsonld.py", line 812, in expand
    input_, {}, options['documentLoader'], options['base'])
  File "/software/anaconda/envs/devpype/lib/python2.7/site-packages/pyld/jsonld.py", line 4077, in _retrieve_context_urls
    code='loading remote context failed', cause=cause)
  File "/software/anaconda/envs/devpype/lib/python2.7/site-packages/pyld/jsonld.py", line 865, in flatten
    expanded = self.expand(input_, options)
  File "/software/anaconda/envs/devpype/lib/python2.7/site-packages/pyld/jsonld.py", line 816, in expand
    'jsonld.ExpandError', cause=cause)
```

**Comment by satra** [comment]
```
$ rm -rf /Users/satra/Library/Caches/datalad
$ datalad search bids
```

now works!!
