### ISSUE TITLE
datalad save -m "msg" -  fails with index out of range (GitPython?)

### ISSUE THREAD

**Issue by yarikoptic** [datalad/datalad#991]
by mistake was using #959 but the issue seems to be the same (although initial save did add it as a submodule I believe while I was in #959)

``` shell
$> git status
On branch master
Changes to be committed:
  (use "git reset HEAD <file>..." to unstage)
1
    new file:   .gitmodules
    new file:   33

$> cat .gitmodules     
[submodule "33"]
    path = 33
    url = ./33

$> datalad save -m "Added pilot study" -a
2016-10-11 14:48:30,533 [ERROR  ] list index out of range [tree.py:__getitem__:293] (IndexError) 
```

actually might be a duplicate or related of #970 -- yet to check with current GitPython master etc

**Comment by mih** [comment]
It is related to the path "33" being treated as an integer index by GitPython. Call it "aa" and it works.

**Comment by mih** [comment]
You can also generate different error, by using different numbers ;-)

````
% git st
On branch master
Changes to be committed:
  (use "git reset HEAD <file>..." to unstage)

	modified:   .gitmodules
	new file:   1

% datalad save -m "Added pilot study" -a
datalad --dbg save
<snip>
2016-10-12 13:10:23,760 [DEBUG  ] Resolved dataset for saving: <Dataset path=/tmp/bf991> 
Traceback (most recent call last):
  File "/home/mih/hacking/datalad/git/bin/datalad", line 9, in <module>
    load_entry_point('datalad', 'console_scripts', 'datalad')()
  File "/home/mih/hacking/datalad/git/datalad/cmdline/main.py", line 260, in main
    ret = cmdlineargs.func(cmdlineargs)
  File "/home/mih/hacking/datalad/git/datalad/interface/base.py", line 296, in call_from_parser
    return cls.__call__(**kwargs)
  File "/home/mih/hacking/datalad/git/datalad/interface/save.py", line 156, in __call__
    deinit_deleted_submodules(ds)
  File "/home/mih/hacking/datalad/git/datalad/interface/save.py", line 73, in deinit_deleted_submodules
    for subdspath in ds.get_subdatasets(absolute=False, recursive=False):
  File "/home/mih/hacking/datalad/git/datalad/distribution/dataset.py", line 270, in get_subdatasets
    submodules = repo.get_submodules()
  File "/home/mih/hacking/datalad/git/datalad/support/gitrepo.py", line 1431, in get_submodules
    submodules = self.repo.submodules
  File "/usr/lib/python2.7/dist-packages/git/repo/base.py", line 289, in submodules
    return Submodule.list_items(self)
  File "/usr/lib/python2.7/dist-packages/git/util.py", line 733, in list_items
    out_list.extend(cls.iter_items(repo, *args, **kwargs))
  File "/usr/lib/python2.7/dist-packages/git/objects/submodule/base.py", line 1175, in iter_items
    sm._name = n
AttributeError: 'Blob' object has no attribute '_name'
()
> /usr/lib/python2.7/dist-packages/git/objects/submodule/base.py(1175)iter_items()
-> sm._name = n

````

**Comment by mih** [comment]
Here is a shell script to document this without any datalad code involved:

````
mkdir -p bug/1
touch bug/1/test
git -C bug/1 init
git -C bug/1 add .
git -C bug/1 commit -m 'some'
touch bug/test
git -C bug init
git -C bug add test
git -C bug commit -m "some"
git -C bug submodule add ./1 1
cd bug && python -c "import git; print git.Repo('.').submodules"

Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "/usr/lib/python2.7/dist-packages/git/repo/base.py", line 289, in submodules
    return Submodule.list_items(self)
  File "/usr/lib/python2.7/dist-packages/git/util.py", line 733, in list_items
    out_list.extend(cls.iter_items(repo, *args, **kwargs))
  File "/usr/lib/python2.7/dist-packages/git/objects/submodule/base.py", line 1162, in iter_items
    sm = rt[p]
  File "/usr/lib/python2.7/dist-packages/git/objects/tree.py", line 293, in __getitem__
    info = self._cache[item]
IndexError: list index out of range

````

**Comment by bpoldrack** [comment]
I think it just adds to the cons on using GitPython at all. While some things can be easily fixed, others cannot or probably won't be merged into GitPython even if we provide a "fix". This is especially true for dealing with direct mode, where we would need to provide a mechanism for GitPython that enables us to use it with an annex repo in direct mode, but in a way this would not be an actual bug to fix from the point of view of GitPython. So, I think this will keep hurting us.

**Comment by yarikoptic** [comment]
if there were no direct mode difficulty, then I would say "nah -- if there is a problem to fix, let's fix it in GitPython and be done!", since upstream grew up a little recently and they are quite responsive.  But that also makes me want actually to add another env to our travis which would keep testing against current GitPython master so we catch regressions earlier than later!

but with direct mode I guess there might come difficulty.  Can't we though do something what 'git annex proxy' does while decorating then GitPython for such use-cases?

Re the bug -- it is a fun one if just 'int-caused' (thanks @mih !)... someone needs to reproduce/report to GitPython ;-)

**Comment by mih** [comment]
Just checked again...stable performance...

````
mih@meiner /tmp/t1 % datalad create
[INFO   ] Creating a new annex repo at /tmp/t1 
Created dataset at /tmp/t1.
mih@meiner /tmp/t1 (git)-[master] % datalad create -d . 1
[INFO   ] Creating a new annex repo at /tmp/t1/1 
[ERROR  ] list index out of range [tree.py:__getitem__:293] (IndexError) 
% python -c'import git; print(git.__version__)'
2.1.1
````

**Comment by mih** [comment]
With new-style approach (working with paths and not with GitPython) this is no longer an issue:

````
mih@meiner /tmp/demo % datalad create
[INFO   ] Creating a new annex repo at /tmp/demo 
create(ok): /tmp/demo (dataset)                                                                                       
mih@meiner /tmp/demo (git)-[master] % datalad create -d . 1
[INFO   ] Creating a new annex repo at /tmp/demo/1 
add(ok): 1 (dataset) [added new subdataset]                                                                           
add(notneeded): .gitmodules (file) [already included in the dataset]                                                  
add(notneeded): 1 (directory) [nothing to add from /tmp/demo/1]
save(ok): /tmp/demo (dataset)                                                                                         
create(ok): 1 (dataset)
action summary:
  add (notneeded: 2, ok: 1)
  create (ok: 1)
  save (ok: 1)
````
