### ISSUE TITLE
datalad search tries to create a cache in a local (has nothing to do with annex/datalad) repo

### ISSUE THREAD

**Issue by yarikoptic** [datalad/datalad#997]
```shell
(git)hopa:~datalad/datalad[master]git
$> datalad search bids
2016-10-13 00:40:57,565 [INFO   ] Loading and caching local meta-data... might take a few seconds 
Traceback (most recent call last):
  File "/home/yoh/proj/datalad/datalad/venv-tests/bin/datalad", line 11, in <module>
    load_entry_point('datalad', 'console_scripts', 'datalad')()
  File "/home/yoh/proj/datalad/datalad/datalad/cmdline/main.py", line 282, in main
    cmdlineargs.result_renderer(ret, cmdlineargs)
  File "/home/yoh/proj/datalad/datalad/datalad/metadata/search.py", line 361, in result_renderer_cmdline
    for location, r in res:
  File "/home/yoh/proj/datalad/datalad/datalad/metadata/search.py", line 201, in __call__
    os.makedirs(cache_dir)
  File "/home/yoh/proj/datalad/datalad/venv-tests/lib/python2.7/os.py", line 157, in makedirs
    mkdir(name, mode)
OSError: [Errno 20] Not a directory: '/home/yoh/proj/datalad/datalad/.git/datalad/cache'
```
IMHO if a current directory/repo is not a datalad dataset, shouldnt try to search within it since it wouldn't find anything -- should get to the logic asking to install central repo, or just bail
PS in above it fails since I do have .git/datalad which is readonly/root-owned (for reasons to catch such cases)

**Comment by mih** [comment]
Without this permission issue it still doesn't work:

````
datalad/git (git)-[master] % datalad search bids
2016-10-14 08:39:02,602 [INFO   ] Loading and caching local meta-data... might take a few seconds 
Traceback (most recent call last):
  File "/home/mih/hacking/datalad/git/bin/datalad", line 9, in <module>
    load_entry_point('datalad', 'console_scripts', 'datalad')()
  File "/home/mih/hacking/datalad/git/datalad/cmdline/main.py", line 282, in main
    cmdlineargs.result_renderer(ret, cmdlineargs)
  File "/home/mih/hacking/datalad/git/datalad/metadata/search.py", line 361, in result_renderer_cmdline
    for location, r in res:
  File "/home/mih/hacking/datalad/git/datalad/metadata/search.py", line 204, in __call__
    ignore_cache=False)
  File "/home/mih/hacking/datalad/git/datalad/metadata/__init__.py", line 231, in get_metadata
    ds, ds_identifier, subdatasets=subdss)
  File "/home/mih/hacking/datalad/git/datalad/metadata/__init__.py", line 123, in _get_implicit_metadata
    repo_info = ds.repo.repo_info(fast=True)
  File "/home/mih/hacking/datalad/git/datalad/support/annexrepo.py", line 1273, in repo_info
    assert(len(json_records) == 1)
AssertionError
````
